import type { Unit } from "./medicationCalculations";

export type DoseType = "weight" | "fixed" | "weight-table" | "age-band";
export type Category = "Dosisberechnung" | "mg–ml-Umrechnung" | "Verdünnung" | "Wiederholung/Höchstdosis" | "Infusionsmengen";
export interface MedicationRule { id:string; drug:string; indication:string; route:string; group:"Erwachsene"|"Kinder"; doseType:DoseType; parameter:string; concentration?:string; singleMaximum?:string; cumulativeMaximum?:string; repeat?:string; source:string; active:boolean }
export interface Answer { id:string; label:string; value:number; unit:Unit; decimals:number; calculation:string; errorHint?:string }
export interface MedicationCase { id:string; ruleId:string; title:string; age:number; weight:number; group:"Erwachsene"|"Kinder"; phase:string; category:Category; text:string; question:string; answers:Answer[]; hint:string }

export const sourceIssues = [
  "VFA 37: Tabellenzeile 40 kg trotz Überschrift Kinder < 40 kg; aktive Fälle auf 10–35 kg begrenzt.",
  "VFA 29/30: exakt 30 kg und i.m. exakt 40 kg wegen uneindeutiger Abgrenzung ausgeschlossen.",
  "VFA 30: MAD-Aufziehtabelle weicht von Formel plus Totraum ab; nicht als Formel-Sollwert freigegeben.",
  "Morphin: keine Interpolation; nur Gewichte der Tabelle aus Anlage B2B freigegeben.",
] as const;

export const medicationRules: MedicationRule[] = [
 {id:"esk-adult",drug:"Esketamin (Ketanest S)",indication:"Trauma-Analgesie",route:"i.v.",group:"Erwachsene",doseType:"weight",parameter:"initial 0,2 mg/kg; Wiederholung 0,1 mg/kg",concentration:"5 mg/ml",repeat:"nach Reevaluation nach 5 Minuten",source:"VFA 36; Anlage B2A; Stand 01.07.2026",active:true},
 {id:"esk-child",drug:"Esketamin (Ketanest S)",indication:"pädiatrische Trauma-Analgesie",route:"i.v./i.m./intranasal",group:"Kinder",doseType:"weight",parameter:"i.v. 0,2/0,1; i.m. 0,5/0,25; nasal 1/0,5 mg/kg",concentration:"5 bzw. 25 mg/ml",repeat:"nach Reevaluation nach 5 Minuten",source:"VFA 37; Anlage B2A; Stand 01.07.2026",active:true},
 {id:"morphine",drug:"Morphin",indication:"Analgesie",route:"i.v.",group:"Erwachsene",doseType:"weight-table",parameter:"40/50: 2; 60/70: 3; 80/90: 4; 100/110: 5 mg",concentration:"1 mg/ml",cumulativeMaximum:"10 mg",repeat:"halbe Tabellendosis nach 5 Minuten",source:"VFA 38; Anlage B2A/B2B; Stand 01.07.2026",active:true},
 {id:"mid-seizure",drug:"Midazolam (Dormicum)",indication:"anhaltender Krampfanfall",route:"i.v./i.m./intranasal",group:"Erwachsene",doseType:"fixed",parameter:"weg- und gewichtsgruppenabhängige Festdosis",concentration:"1 bzw. 5 mg/ml",repeat:"VFA 29 nach 5 Minuten; VFA 30 einmal nach 10 Minuten",source:"VFA 29/30; Anlage B2A; Stand 01.07.2026",active:true},
 {id:"heparin",drug:"Heparin",indication:"STEMI",route:"i.v.",group:"Erwachsene",doseType:"weight",parameter:"100 I.E./kg",concentration:"1.000 I.E./ml",singleMaximum:"5.000 I.E.",source:"VFA 14; Anlage B2A; Stand 01.07.2026",active:true},
 {id:"anaphylaxis",drug:"Adrenalin/Dimetinden/Prednisolon",indication:"Anaphylaxie",route:"i.m./i.v.",group:"Kinder",doseType:"age-band",parameter:"alters- bzw. gewichtsgestufte Dosen",source:"VFA 25/26; Anlage B2A; Stand 01.07.2026",active:true},
 {id:"cpr",drug:"Adrenalin/Amiodaron",indication:"Kinderreanimation",route:"i.v./i.o.",group:"Kinder",doseType:"weight",parameter:"Adrenalin 10 µg/kg; Amiodaron 5 mg/kg",singleMaximum:"Adrenalin 1 mg; Amiodaron 300/150 mg",source:"ERC-2025-Abbildung, gedruckte Seite 48; Anlage B2A; Stand 01.07.2026",active:true},
 {id:"glucose",drug:"Glukose 20 %",indication:"kindliche Hypoglykämie",route:"i.v.",group:"Kinder",doseType:"weight",parameter:"initial 2 ml/kg; weitere Gabe 1 ml/kg",concentration:"0,2 g/ml",source:"VFA 28; Anlage B2A; Stand 01.07.2026",active:true},
 {id:"fluids",drug:"Kristalloide Infusionslösung",indication:"Anaphylaxie/Sepsis/Verbrennung",route:"i.v./i.o.",group:"Erwachsene",doseType:"weight",parameter:"10 ml/kg; max. 30 ml/kg; max. 10 ml/kg/h",source:"VFA 10/26/34; Stand 01.07.2026",active:true},
];

const a=(id:string,label:string,value:number,unit:Unit,decimals:number,calculation:string,errorHint?:string):Answer=>({id,label,value,unit,decimals,calculation,errorHint});
const rows: Array<[string,string,number,number,"Erwachsene"|"Kinder",string,Category,string,string,Answer[],string]> = [
["esk-01","Esketamin initial",42,80,"Erwachsene","Initialgabe","Dosisberechnung","Ein 42-jähriger Mann (80 kg) hat nach einem Sturz starke Beinschmerzen. Der geprüfte VFA-36-Pfad sieht 0,2 mg/kg Esketamin i.v. vor; die fertige Lösung enthält 5 mg/ml.","Berechne Wirkstoffmenge und Volumen.",[a("dose","Dosis",16,"mg",0,"80 kg × 0,2 mg/kg = 16 mg"),a("volume","Volumen",3.2,"ml",1,"16 mg ÷ 5 mg/ml = 3,2 ml")],"Erst die Dosis, dann durch die Endkonzentration teilen."],
["esk-02","Esketamin initial",35,65,"Erwachsene","Initialgabe","mg–ml-Umrechnung","Ein 35-jähriger Patient (65 kg) hat ein unkompliziertes Extremitätentrauma. Vorgesehen sind 0,2 mg/kg Esketamin i.v.; bereit stehen 5 mg/ml.","Wie viele mg und ml werden benötigt?",[a("dose","Dosis",13,"mg",0,"65 × 0,2 = 13 mg"),a("volume","Volumen",2.6,"ml",1,"13 ÷ 5 = 2,6 ml")],"Nutze die Konzentration der vorbereiteten Lösung."],
["esk-03","Esketamin Wiederholung",42,80,"Erwachsene","Wiederholung nach Reevaluation","Wiederholung/Höchstdosis","Bei einem 80-kg-Patienten ist die Wirkung nach fünf Minuten unzureichend. Der gewählte Pfad sieht 0,1 mg/kg Esketamin i.v. aus 5 mg/ml vor.","Berechne die ausdrücklich vorgesehene Wiederholung.",[a("dose","Dosis",8,"mg",0,"80 × 0,1 = 8 mg"),a("volume","Volumen",1.6,"ml",1,"8 ÷ 5 = 1,6 ml")],"Nicht erneut den Initialfaktor verwenden."],
["esk-04","Midazolam-Begleitgabe",42,80,"Erwachsene","Begleitgabe","Dosisberechnung","Im Erwachsenen-Esketaminpfad ist Midazolam (Dormicum) als feste Begleitgabe von 1 mg i.v. vorgesehen. Es liegt mit 1 mg/ml vor.","Berechne feste Dosis und Volumen.",[a("dose","Dosis",1,"mg",0,"Feste Dosis = 1 mg","Die feste Dosis nicht mit dem Gewicht multiplizieren."),a("volume","Volumen",1,"ml",0,"1 mg ÷ 1 mg/ml = 1 ml")],"Dies ist keine gewichtsbezogene Krampfanfall-Dosis."],
["esk-05","Esketamin verdünnen",30,70,"Erwachsene","Vorbereitung","Verdünnung","Eine Ampulle Esketamin enthält 50 mg in 2 ml. Die 2 ml Medikament sollen mit NaCl 0,9 % auf insgesamt 10 ml aufgefüllt werden.","Wie viel NaCl wird ergänzt und welche Endkonzentration entsteht?",[a("diluent","NaCl",8,"ml",0,"10 ml − 2 ml = 8 ml","Auf insgesamt 10 ml, nicht plus 10 ml."),a("concentration","Konzentration",5,"mg/ml",0,"50 mg ÷ 10 ml = 5 mg/ml")],"Das Konzentrationsfeld erwartet den Zahlenwert in mg/ml."],
["esk-06","Esketamin Kind i.v.",8,20,"Kinder","Initialgabe","Dosisberechnung","Ein 8-jähriges Kind (20 kg) hat nach einem Sturz starke Schmerzen. Der geprüfte VFA-37-i.v.-Pfad sieht 0,2 mg/kg aus 5 mg/ml vor.","Berechne Dosis und Volumen.",[a("dose","Dosis",4,"mg",0,"20 × 0,2 = 4 mg"),a("volume","Volumen",.8,"ml",1,"4 ÷ 5 = 0,8 ml")],"i.v.-Faktor verwenden."],
["esk-07","Esketamin Kind i.m.",8,20,"Kinder","Initialgabe","Dosisberechnung","Bei einem 20-kg-Kind wurde der i.m.-Pfad gewählt. Vorgesehen sind 0,5 mg/kg Esketamin; Konzentration 5 mg/ml.","Berechne Dosis und Volumen.",[a("dose","Dosis",10,"mg",0,"20 × 0,5 = 10 mg"),a("volume","Volumen",2,"ml",0,"10 ÷ 5 = 2 ml")],"i.m. hat einen anderen Faktor als i.v."],
["esk-08","Esketamin Kind nasal",7,20,"Kinder","Initialgabe","mg–ml-Umrechnung","Bei einem 20-kg-Kind ist 1 mg/kg Esketamin intranasal vorgesehen. Unverdünnte Konzentration: 25 mg/ml; gefragt ist das theoretische Wirkstoffvolumen ohne Totraum.","Berechne Dosis und theoretisches Volumen.",[a("dose","Dosis",20,"mg",0,"20 × 1 = 20 mg"),a("volume","Wirkstoffvolumen",.8,"ml",1,"20 ÷ 25 = 0,8 ml")],"Keinen nicht genannten Totraum addieren."],
["esk-09","Esketamin nasal wiederholen",7,20,"Kinder","Wiederholung nach 5 Minuten","Wiederholung/Höchstdosis","Nach Reevaluation ist beim 20-kg-Kind die nasale Wiederholung mit 0,5 mg/kg vorgesehen. Esketamin liegt unverdünnt mit 25 mg/ml vor.","Berechne Dosis und theoretisches Volumen ohne Totraum.",[a("dose","Dosis",10,"mg",0,"20 × 0,5 = 10 mg"),a("volume","Wirkstoffvolumen",.4,"ml",1,"10 ÷ 25 = 0,4 ml")],"Wiederholungsfaktor beachten."],
["morph-10","Morphin nach Tabelle",44,70,"Erwachsene","Initialgabe","Dosisberechnung","Ein 44-jähriger Patient (70 kg) erhält im festgelegten Morphinpfad langsam i.v. Die Tabelle nennt 3 mg; Lösung 1 mg/ml.","Nenne Tabellendosis und Volumen.",[a("dose","Dosis",3,"mg",0,"70-kg-Tabellenwert = 3 mg"),a("volume","Volumen",3,"ml",0,"3 ÷ 1 = 3 ml")],"Nicht in eine mg/kg-Formel umwandeln."],
["morph-11","Morphin wiederholen",44,70,"Erwachsene","Wiederholung nach 5 Minuten","Wiederholung/Höchstdosis","Bei 70 kg betrug die initiale Tabellendosis 3 mg. Nach Reevaluation ist die halbe Tabellendosis vorgesehen; Lösung 1 mg/ml.","Berechne Wiederholungsdosis und Volumen.",[a("dose","Wiederholungsdosis",1.5,"mg",1,"3 mg ÷ 2 = 1,5 mg"),a("volume","Volumen",1.5,"ml",1,"1,5 ÷ 1 = 1,5 ml")],"Halbiere den Tabellenwert."],
["morph-12","Morphin 100 kg",50,100,"Erwachsene","Initialgabe","Dosisberechnung","Ein 50-jähriger Patient wiegt 100 kg. Die Morphintabelle nennt 5 mg i.v.; die vorbereitete Lösung enthält 1 mg/ml.","Berechne Dosis und Volumen.",[a("dose","Dosis",5,"mg",0,"100-kg-Tabellenwert = 5 mg"),a("volume","Volumen",5,"ml",0,"5 ÷ 1 = 5 ml")],"Tabellenwert verwenden."],
["morph-13","Morphin Restmenge",38,80,"Erwachsene","Kumulative Gabe","Wiederholung/Höchstdosis","Bei einem Patienten wurden tatsächlich insgesamt 8 mg Morphin gegeben. Die kumulative Obergrenze im dargestellten Pfad beträgt 10 mg.","Wie viel bleibt rechnerisch bis zur Grenze?",[a("remaining","Restdifferenz",2,"mg",0,"max(0, 10 − 8) = 2 mg")],"Die Restdifferenz ist keine Empfehlung für eine neue Gabe."],
["morph-14","Morphin und Gesamtgrenze",46,70,"Erwachsene","Wiederholung bei bisher 9 mg","Wiederholung/Höchstdosis","Ein 70-kg-Patient hat bereits 9 mg Morphin erhalten. Die volle Wiederholung nach Tabelle wäre 1,5 mg; kumulative Grenze 10 mg.","Berechne resultierende Summe und Restdifferenz.",[a("sum","Summe bei voller Wiederholung",10.5,"mg",1,"9 + 1,5 = 10,5 mg"),a("remaining","Restdifferenz",1,"mg",0,"10 − 9 = 1 mg")],"Die volle Wiederholung überschreitet; keine automatische Teilgabe ableiten."],
["hep-15","Heparin STEMI",55,45,"Erwachsene","Initialgabe","Dosisberechnung","Bei einem 55-jährigen STEMI-Patienten (45 kg) sind die Voraussetzungen geprüft. Heparin: 100 I.E./kg, maximal 5.000 I.E.; Lösung 1.000 I.E./ml.","Berechne Dosis und Volumen.",[a("dose","Dosis",4500,"I.E.",0,"45 × 100 = 4.500 I.E."),a("volume","Volumen",4.5,"ml",1,"4.500 ÷ 1.000 = 4,5 ml")],"Einzelgabegrenze prüfen."],
["hep-16","Heparin mit Begrenzung",61,80,"Erwachsene","Initialgabe","Wiederholung/Höchstdosis","Ein 61-jähriger STEMI-Patient wiegt 80 kg. Regel: 100 I.E./kg, maximal 5.000 I.E.; 1.000 I.E./ml.","Berechne Rohwert, begrenzte Dosis und Volumen.",[a("raw","Rohwert",8000,"I.E.",0,"80 × 100 = 8.000 I.E."),a("dose","Begrenzte Dosis",5000,"I.E.",0,"min(8.000, 5.000) = 5.000 I.E.","Höchstdosis übersehen."),a("volume","Volumen",5,"ml",0,"5.000 ÷ 1.000 = 5 ml")],"Hier greift die Einzelgabegrenze."],
["mid-17","Midazolam i.v.",49,75,"Erwachsene","Initialgabe","mg–ml-Umrechnung","Ein 49-jähriger Patient über 30 kg krampft anhaltend. Im i.v.-Pfad sind fest 3 mg Midazolam (Dormicum) langsam vorgesehen; 1 mg/ml.","Berechne Dosis und Volumen.",[a("dose","Dosis",3,"mg",0,"Festdosis = 3 mg"),a("volume","Volumen",3,"ml",0,"3 ÷ 1 = 3 ml")],"Nicht gewichtsbezogen rechnen."],
["mid-18","Midazolam i.m. über 40 kg",52,70,"Erwachsene","Initialgabe","Dosisberechnung","Ein 52-jähriger Patient (70 kg) krampft anhaltend. Gewählter i.m.-Pfad über 40 kg: 10 mg Midazolam; 5 mg/ml.","Berechne Dosis und Volumen.",[a("dose","Dosis",10,"mg",0,"Festdosis = 10 mg"),a("volume","Volumen",2,"ml",0,"10 ÷ 5 = 2 ml")],"Gewichtsgruppe bestimmt die Festdosis."],
["mid-19","Midazolam i.m. 35 kg",14,35,"Kinder","Initialgabe","Dosisberechnung","Ein 14-jähriges Kind (35 kg) krampft anhaltend. Der i.m.-Pfad über 30 und unter 40 kg nennt 5 mg; Konzentration 5 mg/ml.","Berechne Dosis und Volumen.",[a("dose","Dosis",5,"mg",0,"Festdosis der Gewichtsgruppe = 5 mg"),a("volume","Volumen",1,"ml",0,"5 ÷ 5 = 1 ml")],"Kein Grenzgewicht und keine mg/kg-Formel."],
["mid-20","Midazolam nasal mit Totraum",6,20,"Kinder","Initialgabe","mg–ml-Umrechnung","Ein 6-jähriges Kind (20 kg) krampft anhaltend. Ansatz 0,2 mg/kg, 5 mg/ml; der Fall nennt ausdrücklich 0,1 ml Gesamt-Totraum.","Berechne Dosis, theoretisches Wirkstoff- und Aufziehvolumen.",[a("dose","Dosis",4,"mg",0,"20 × 0,2 = 4 mg"),a("volume","Wirkstoffvolumen",.8,"ml",1,"4 ÷ 5 = 0,8 ml"),a("draw","Aufziehvolumen",.9,"ml",1,"0,8 + 0,1 = 0,9 ml")],"Totraum erhöht das Aufziehvolumen, nicht die Dosis."],
["glu-21","Glukose initial",7,20,"Kinder","Initialgabe","Dosisberechnung","Ein nicht waches, nicht kooperatives 7-jähriges Kind (20 kg) hat eine bestätigte Hypoglykämie. Vorgesehen: 2 ml/kg Glukose 20 % i.v.; 0,2 g/ml.","Berechne Volumen und Glukosemenge.",[a("volume","Volumen",40,"ml",0,"20 × 2 = 40 ml"),a("dose","Glukose",8,"g",0,"40 × 0,2 = 8 g")],"ml/kg nicht als mg/kg lesen."],
["glu-22","Glukose weitere Gabe",7,20,"Kinder","Weitere Gabe nach BZ-Kontrolle","Wiederholung/Höchstdosis","Beim 20-kg-Kind ist nach erneuter BZ-Kontrolle die weitere Gabe von 1 ml/kg Glukose 20 % vorgesehen; Konzentration 0,2 g/ml.","Berechne Volumen und Glukosemenge.",[a("volume","Volumen",20,"ml",0,"20 × 1 = 20 ml"),a("dose","Glukose",4,"g",0,"20 × 0,2 = 4 g")],"Faktor der weiteren Gabe verwenden."],
["ana-23","Dimetinden Erwachsene",33,60,"Erwachsene","Ergänzende Einmalgabe","Dosisberechnung","Bei einer 33-jährigen Patientin (60 kg) mit Anaphylaxie sind vorrangige Maßnahmen eingeleitet. Ergänzend: 0,1 mg/kg Dimetinden i.v.; 1 mg/ml.","Berechne Dosis und Volumen.",[a("dose","Dosis",6,"mg",0,"60 × 0,1 = 6 mg"),a("volume","Volumen",6,"ml",0,"6 ÷ 1 = 6 ml")],"Keine nicht angegebene Höchstdosis erfinden."],
["ana-24","Zusatzgaben Kind 20 kg",8,20,"Kinder","Ergänzende Einmalgaben","Dosisberechnung","Bei einem 8-jährigen Kind (20 kg) mit Anaphylaxie laufen die vorrangigen Maßnahmen. Die Gewichtsstufe 15–30 kg nennt Prednisolon 100 mg (50 mg/ml) und Dimetinden 2 mg (1 mg/ml).","Berechne beide Dosen und Volumina.",[a("pred-dose","Prednisolon",100,"mg",0,"Tabellenwert = 100 mg"),a("pred-volume","Prednisolon-Volumen",2,"ml",0,"100 ÷ 50 = 2 ml"),a("dim-dose","Dimetinden",2,"mg",0,"Tabellenwert = 2 mg"),a("dim-volume","Dimetinden-Volumen",2,"ml",0,"2 ÷ 1 = 2 ml")],"Beide Präparate getrennt berechnen."],
["ana-25","Zusatzgaben Kind 35 kg",11,35,"Kinder","Ergänzende Einmalgaben","Dosisberechnung","Bei einem 11-jährigen Kind (35 kg) sind vorrangige Anaphylaxiemaßnahmen erfolgt. Die Stufe über 30 kg nennt Prednisolon 250 mg (50 mg/ml) und Dimetinden 4 mg (1 mg/ml).","Berechne beide Dosen und Volumina.",[a("pred-dose","Prednisolon",250,"mg",0,"Tabellenwert = 250 mg"),a("pred-volume","Prednisolon-Volumen",5,"ml",0,"250 ÷ 50 = 5 ml"),a("dim-dose","Dimetinden",4,"mg",0,"Tabellenwert = 4 mg"),a("dim-volume","Dimetinden-Volumen",4,"ml",0,"4 ÷ 1 = 4 ml")],"Gewichtsstufe über 30 kg."],
["adr-26","Adrenalin Anaphylaxie",8,28,"Kinder","Initialgabe","Dosisberechnung","Ein 8-jähriges Kind hat eine Anaphylaxie; der i.m.-Pfad ist festgelegt. Für 6 bis einschließlich 12 Jahre gelten 0,3 mg; Konzentration 1 mg/ml.","Berechne Dosis und Volumen.",[a("dose","Dosis",.3,"mg",1,"Altersstufe = 0,3 mg"),a("volume","Volumen",.3,"ml",1,"0,3 ÷ 1 = 0,3 ml")],"Nicht die CPR-Konzentration verwenden."],
["cpr-27","Adrenalin Kinderreanimation",4,15,"Kinder","Vorgesehene Reanimationsgabe","Dosisberechnung","Bei der Reanimation eines 15-kg-Kindes ist jetzt Adrenalin i.v./i.o. vorgesehen: 10 µg/kg, Lösung 100 µg/ml.","Berechne µg, mg und Volumen.",[a("micro","Dosis",150,"µg",0,"15 × 10 = 150 µg"),a("mg","Dosis in mg",.15,"mg",2,"150 µg ÷ 1.000 = 0,15 mg"),a("volume","Volumen",1.5,"ml",1,"150 ÷ 100 = 1,5 ml")],"µg und mg sauber umrechnen; CPR-Lösung nutzen."],
["cpr-28","Amiodaron erste Gabe",6,20,"Kinder","Nach drittem Schock","Dosisberechnung","Ein 20-kg-Kind wird bei defibrillierbarem Rhythmus reanimiert. Nach dem dritten Schock: 5 mg/kg, maximal 300 mg; Ampulle 50 mg/ml.","Berechne Dosis und zu entnehmendes Wirkstoffvolumen.",[a("dose","Dosis",100,"mg",0,"20 × 5 = 100 mg"),a("volume","Ampullenvolumen",2,"ml",0,"100 ÷ 50 = 2 ml")],"Keine zusätzliche Verdünnungsanweisung ableiten."],
["cpr-29","Amiodaron zweite Gabe",12,40,"Kinder","Nach fünftem Schock","Wiederholung/Höchstdosis","Ein 40-kg-Kind wird bei defibrillierbarem Rhythmus reanimiert. Zweite Gabe nach fünftem Schock: 5 mg/kg, maximal 150 mg; Ampulle 50 mg/ml.","Berechne Rohwert, begrenzte Dosis und Ampullenvolumen.",[a("raw","Rohwert",200,"mg",0,"40 × 5 = 200 mg"),a("dose","Begrenzte Dosis",150,"mg",0,"min(200, 150) = 150 mg"),a("volume","Ampullenvolumen",3,"ml",0,"150 ÷ 50 = 3 ml")],"Für die zweite Gabe gilt 150 mg, nicht 300 mg."],
["fluid-30","Flüssigkeit Anaphylaxie",7,20,"Kinder","Beschriebener Flüssigkeitsschritt","Infusionsmengen","Bei einem 20-kg-Kind mit Anaphylaxie ist im beschriebenen Schritt 10 ml/kg kristalloide Lösung vorgesehen.","Berechne das Volumen.",[a("volume","Volumen",200,"ml",0,"20 × 10 = 200 ml")],"Gewicht mal ml/kg."],
["fluid-31","Sepsis Obergrenze",58,70,"Erwachsene","Flüssigkeit nach Kreislaufwirkung","Infusionsmengen","Ein 58-jähriger Sepsispatient wiegt 70 kg. Die kristalloide Flüssigkeit wird nach Kreislaufwirkung gegeben, maximal 30 ml/kg.","Berechne die rechnerische Obergrenze in ml und l.",[a("ml","Obergrenze",2100,"ml",0,"70 × 30 = 2.100 ml"),a("litres","Obergrenze",2.1,"l",1,"2.100 ml ÷ 1.000 = 2,1 l")],"Das Ergebnis ist keine automatische Zielmenge."],
["fluid-32","Verbrennung maximale Rate",39,80,"Erwachsene","Infusion über 30 Minuten","Infusionsmengen","Ein 39-jähriger Verbrennungspatient wiegt 80 kg. Gefragt ist die maximale Rate nach 10 ml/kg/h und das rechnerische Volumen in 30 Minuten bei dieser Rate.","Berechne Rate und 30-Minuten-Volumen.",[a("rate","Maximale Rate",800,"ml/h",0,"80 × 10 = 800 ml/h"),a("volume","Volumen in 30 Minuten",400,"ml",0,"800 × 30 ÷ 60 = 400 ml")],"Die Maximalrate ist keine automatische Zielrate."],
];

export const medicationCases: MedicationCase[] = rows.map(([id,title,age,weight,group,phase,category,text,question,answers,hint])=>({id,ruleId:id.split("-")[0].startsWith("morph")?"morphine":id.startsWith("hep")?"heparin":id.startsWith("mid")?"mid-seizure":id.startsWith("ana")||id.startsWith("adr")?"anaphylaxis":id.startsWith("cpr")?"cpr":id.startsWith("glu")?"glucose":id.startsWith("fluid")?"fluids":id.startsWith("esk")? (group==="Kinder"?"esk-child":"esk-adult"):"fluids",title,age,weight,group,phase,category,text,question,answers,hint}));
