import { supplementalQuestions } from "./supplemental-questions";

export type AbdominaltraumaChoiceQuestion = {
  id: string;
  mode: "multiple";
  prompt: string;
  options: Array<{ text: string; correct?: boolean }>;
  source: string;
  difficulty: 1 | 2 | 3;
};

export type AbdominaltraumaFlashcard = {
  id: string;
  area: string;
  question: string;
  answer: string;
};

export const abdominaltraumaFlashcards: AbdominaltraumaFlashcard[] = [
  { id: "abd-card-01", area: "Definition", question: "Definieren Sie das Abdominaltrauma und grenzen Sie die beiden Grundmechanismen ab.", answer: "Verletzung der Bauchorgane durch stumpfe oder penetrierende Gewalteinwirkung. Stumpf: Bauchdecke bleibt intakt, Kraftübertragung verursacht Kontusion, Riss oder Ruptur. Penetrierend: Bauchdecke und Peritoneum werden durchdrungen; Organe und Gefäße können direkt verletzt werden." },
  { id: "abd-card-02", area: "Peritoneum", question: "Erklären Sie parietales und viszerales Peritoneum sowie die Peritonealhöhle.", answer: "Das parietale Blatt kleidet die Bauch- und Beckenwand aus, das viszerale Blatt überzieht die Organe. Dazwischen liegt die Peritonealhöhle als schmaler, flüssigkeitsbenetzter Spaltraum für die Verschieblichkeit der Organe." },
  { id: "abd-card-03", area: "Wandaufbau", question: "Leiten Sie den allgemeinen Wandaufbau des Verdauungstrakts von innen nach außen her.", answer: "Tunica mucosa → Tunica submucosa → Tunica muscularis mit Ring- und Längsmuskulatur → Subserosa/Tunica serosa bei peritonealem Überzug beziehungsweise Adventitia bei Organabschnitten ohne Bauchfellüberzug." },
  { id: "abd-card-04", area: "Gefäßversorgung", question: "Welche Gefäßbeziehungen sind bei einer Blutung im Oberbauch besonders wichtig?", answer: "Aorta abdominalis mit Truncus coeliacus und A. mesenterica superior; die A. hepatica versorgt die Leber, die A. splenica die Milz. Venös gelangt Blut der Verdauungsorgane und Milz über die Pfortader zur Leber; Lebervenen münden in die V. cava inferior." },
  { id: "abd-card-05", area: "Organverletzungen", question: "Ordnen Sie typische Verletzungsfolgen von Leber, Milz, Magen/Darm und Pankreas zu.", answer: "Leber/Milz: starke intraperitoneale Blutung bis Schock, Milzruptur auch zweizeitig. Magen/Darm: Blutung und Austritt von Hohlorganinhalt mit Peritonitis/Sepsis. Pankreas: Quetschung oder Riss mit Enzymleck, Autodigestion und Entzündung." },
  { id: "abd-card-06", area: "Retroperitoneum", question: "Warum kann eine retroperitoneale Verletzung präklinisch leicht unterschätzt werden?", answer: "Nieren- oder große Gefäßverletzungen können erheblich retroperitoneal bluten, obwohl äußerlich und am vorderen Bauch zunächst wenig zu sehen ist. Flankenschmerz, Flankenhämatom, Hämaturie und Schockzeichen sind wichtige Hinweise." },
  { id: "abd-card-07", area: "Symptome", question: "Welche Befunde stützen die Arbeitsdiagnose Abdominaltrauma?", answer: "Passender Mechanismus, Hämatome/Prellmarken/Gurtzeichen/Wunden, lokaler oder diffuser Druckschmerz, Abwehrspannung, Umfangszunahme oder geblähtes Abdomen, Eviszeration sowie Schockzeichen ohne erkennbare äußere Blutungsquelle." },
  { id: "abd-card-08", area: "Erstmaßnahmen", question: "Strukturieren Sie das Vorgehen nach cABCDE und IPAP.", answer: "Kritische äußere Blutung kontrollieren; Atemweg und Atmung einschließlich Thorax beurteilen; Kreislauf mit Rekapillarisierung, Puls, RR, Monitoring und großen Blutungsräumen prüfen; GCS/BZ/Pupillen; vollständig exponieren und wärmeerhalten. Abdomen inspizieren, auskultieren, vorsichtig palpieren und den Verlauf wiederholt beurteilen." },
  { id: "abd-card-09", area: "Offenes Trauma", question: "Wie versorgen Sie eine Eviszeration?", answer: "Nicht zurückverlagern und keine Fremdkörper entfernen. Wunde beziehungsweise Organe steril und feucht abdecken, anschließend schützen, Manipulation vermeiden, Wärmeerhalt und zügigen Transport fortführen." },
  { id: "abd-card-10", area: "Schock", question: "Welche Kreislaufstrategie nennt L2 bei nicht beherrschbarer Blutung?", answer: "Möglichst großlumiger i.v.-Zugang, bei Versagen i.o.; keine Volumentherapie ohne Hinweis auf Volumenmangel. Bei nicht beherrschbarer Blutung reduzierte Volumentherapie mit Ziel-RRsys etwa 80 mmHg; abweichende Ziele gelten unter anderem bei führendem SHT, Schwangerschaft und Kindern." },
  { id: "abd-card-11", area: "Tranexamsäure", question: "Nennen Sie Indikation, Zubereitung und Gabe von Tranexamsäure nach Thüringer VFA.", answer: "Bei Erwachsenen mit lebensbedrohlicher Blutung und/oder hämorrhagischem Schock: 1 g Tranexamsäure. Anlage B2A: 1 g = 10 ml aus 500 mg/5 ml, mit 90 ml NaCl 0,9 %; L2: als Kurzinfusion über 10 Minuten." },
  { id: "abd-card-12", area: "Analgesie", question: "Wie wird starke traumatische Schmerzsymptomatik eingeordnet?", answer: "Bei NRS ≥ 5 cABCDE und OPQRST; traumatischer Schmerz führt nach VFA 35 je nach Vorgabe des zuständigen ÄLRD zum passenden Esketamin- oder Morphinpfad. NRS, Beatmungsbereitschaft, EKG/RR, Wirkung, Nebenwirkungen, kontinuierliches Monitoring und Transport sind zu beachten." },
  { id: "abd-card-13", area: "Transport", question: "Welche Transportentscheidung ist bei Verdacht auf relevante innere Blutung erforderlich?", answer: "Patient als kritisch einstufen, früh Notarzt/RTH und geeignetes Traumazentrum mit OP-Bereitschaft planen, Load-go-and-treat, voranmelden und die Prähospitalzeit einschließlich Anfahrt und Transport nach L2 unter 60 Minuten halten." },
  { id: "abd-card-14", area: "Übergabe", question: "Welche Angaben müssen in Dokumentation und Übergabe enthalten sein?", answer: "Unfallmechanismus, Zeitpunkt, sichtbare Zeichen, Bauchbefund und Verlauf, Schmerz/NRS, Vitalparameter und Schockzeichen, vermutete Blutungsräume/Begleitverletzungen, Zugänge, Flüssigkeit, Tranexamsäure und Analgesie mit Dosis/Zeit/Wirkung sowie Transportpriorität." },
];

const abdominaltraumaBaseQuestions: AbdominaltraumaChoiceQuestion[] = [
  { id: "abd-q-01", mode: "multiple", prompt: "Welche Aussagen definieren ein Abdominaltrauma korrekt?", options: [{ text: "Stumpfe Gewalteinwirkung kann trotz intakter Bauchdecke Organrupturen verursachen", correct: true }, { text: "Penetrierende Gewalt kann Bauchdecke und Peritoneum durchdringen und Organe direkt verletzen", correct: true }, { text: "Ein Abdominaltrauma setzt zwingend eine sichtbare offene Wunde voraus" }, { text: "Ohne initiale Abwehrspannung ist eine relevante Organverletzung ausgeschlossen" }], source: "Das Abdominaltrauma umfasst stumpfe und penetrierende Verletzungen; äußerlich geringe Befunde schließen innere Schäden nicht aus.", difficulty: 1 },
  { id: "abd-q-02", mode: "multiple", prompt: "Welche Zuordnungen zum Peritoneum sind richtig?", options: [{ text: "Das parietale Blatt kleidet die Bauch- und Beckenwand aus", correct: true }, { text: "Das viszerale Blatt überzieht die Organe", correct: true }, { text: "Peritonealflüssigkeit unterstützt die Verschieblichkeit der Organe", correct: true }, { text: "Die Peritonealhöhle ist physiologisch ein großer luftgefüllter Raum" }], source: "Zwischen parietalem und viszeralem Peritoneum liegt ein schmaler flüssigkeitsbenetzter Spaltraum.", difficulty: 1 },
  { id: "abd-q-03", mode: "multiple", prompt: "Welche Aussagen zum Wandaufbau des Verdauungstrakts treffen zu?", options: [{ text: "Die Tunica mucosa bildet die innere Schleimhautschicht", correct: true }, { text: "Die Tunica submucosa enthält unter anderem größere Gefäßstämme", correct: true }, { text: "Die Tunica muscularis ermöglicht durch glatte Muskulatur die Peristaltik", correct: true }, { text: "Die Adventitia ist immer die innerste Schicht des Darms" }], source: "Der allgemeine Wandaufbau besteht aus Mucosa, Submucosa, Muscularis und äußerer Serosa beziehungsweise Adventitia.", difficulty: 1 },
  { id: "abd-q-04", mode: "multiple", prompt: "Welche Aussagen zur Gefäßversorgung des Oberbauchs sind korrekt?", options: [{ text: "Der Truncus coeliacus entspringt aus der Aorta abdominalis", correct: true }, { text: "Die A. hepatica versorgt Lebergewebe und die A. splenica die Milz", correct: true }, { text: "Die Pfortader führt Blut aus Verdauungsorganen und Milz zur Leber", correct: true }, { text: "Die Pfortader führt das Blut direkt aus der Leber in den rechten Vorhof" }], source: "Die arterielle Versorgung erfolgt über Äste der Aorta; das portalvenöse Blut gelangt zunächst zur Leber.", difficulty: 1 },
  { id: "abd-q-05", mode: "multiple", prompt: "Welche Mechanismen können nach stumpfem Abdominaltrauma auftreten?", options: [{ text: "Kontusion oder Ruptur von Leber, Milz, Niere oder Darm", correct: true }, { text: "Blutung in die Peritonealhöhle oder das Retroperitoneum", correct: true }, { text: "Hohlorganverletzung trotz äußerlich intakter Bauchdecke", correct: true }, { text: "Ausschließlich oberflächliche Hautschäden ohne innere Kraftübertragung" }], source: "Gurt-, Lenkrad-, Schlag-, Sturz- oder Quetschmechanismen übertragen Kraft auf Organe und Gefäße.", difficulty: 1 },
  { id: "abd-q-06", mode: "multiple", prompt: "Welche Befunde stützen die Arbeitsdiagnose einer relevanten abdominalen Verletzung?", options: [{ text: "Gurtzeichen, Prellmarken oder penetrierende Wunden", correct: true }, { text: "Lokaler oder diffuser Druckschmerz und Abwehrspannung", correct: true }, { text: "Schockzeichen ohne erkennbare äußere Blutungsquelle", correct: true }, { text: "Ein normaler erster Blutdruck schließt eine innere Blutung sicher aus" }], source: "Mechanismus, lokaler Befund und Kreislaufentwicklung werden gemeinsam beurteilt und wiederholt kontrolliert.", difficulty: 1 },
  { id: "abd-q-07", mode: "multiple", prompt: "Welche Folgen sind typischen Organverletzungen richtig zugeordnet?", options: [{ text: "Milzruptur: massive Blutung, möglicherweise zweizeitiger Verlauf und Kehr-Zeichen", correct: true }, { text: "Magen- oder Darmperforation: Austritt von Inhalt mit Peritonitis- und Sepsisgefahr", correct: true }, { text: "Pankreasverletzung: Enzymleck mit Autodigestion und Entzündungsreaktion", correct: true }, { text: "Leberruptur: ausschließlich chemische Peritonitis ohne Blutungsgefahr" }], source: "Parenchymorgane bedrohen durch Blutung; Hohlorgane zusätzlich durch Kontamination und Peritonitis.", difficulty: 2 },
  { id: "abd-q-08", mode: "multiple", prompt: "Welche Aussagen zur Milzverletzung sind prüfungsrelevant?", options: [{ text: "Anfangs kann der Patient trotz relevanter Verletzung scheinbar stabil sein", correct: true }, { text: "Eine zweizeitige Ruptur kann später zur plötzlichen Blutung führen", correct: true }, { text: "Linksseitiger Oberbauchschmerz kann in die linke Schulter ausstrahlen", correct: true }, { text: "Fehlende Schulterschmerzen schließen eine Milzverletzung aus" }], source: "Milzverletzungen können verzögert dekompensieren; das Kehr-Zeichen ist möglich, aber nicht obligat.", difficulty: 2 },
  { id: "abd-q-09", mode: "multiple", prompt: "Welche Maßnahmen gehören zur Versorgung einer Eviszeration?", options: [{ text: "Eingeweide nicht zurückverlagern", correct: true }, { text: "Steril und feucht abdecken und anschließend schützen", correct: true }, { text: "Manipulation vermeiden und zügigen Transport fortführen", correct: true }, { text: "Sichtbare Fremdkörper routinemäßig am Einsatzort entfernen" }], source: "Offenes Bauchtrauma wird steril geschützt; Reposition und Fremdkörperentfernung unterbleiben präklinisch.", difficulty: 2 },
  { id: "abd-q-10", mode: "multiple", prompt: "Welche Aussagen entsprechen dem Thüringer Trauma-Leitalgorithmus bei vermuteter innerer Blutung?", options: [{ text: "Ein möglichst großlumiger i.v.-Zugang wird angestrebt; bei Versagen ist ein i.o.-Zugang zu prüfen", correct: true }, { text: "Ohne Hinweis auf Volumenmangel erfolgt keine routinemäßige Volumentherapie", correct: true }, { text: "Bei nicht beherrschbarer Blutung wird die Volumentherapie reduziert und RRsys etwa 80 mmHg angestrebt", correct: true }, { text: "Unabhängig vom Verletzungsmuster wird immer ein systolischer Blutdruck über 140 mmHg angestrebt" }], source: "L2 nennt eine differenzierte Volumenstrategie; besondere Zielwerte gelten unter anderem bei SHT, Schwangerschaft und Kindern.", difficulty: 2 },
  { id: "abd-q-11", mode: "multiple", prompt: "Welche Befunde sprechen bei einem Abdominaltrauma für hämorrhagischen Schock?", options: [{ text: "Tachykardie, Tachypnoe und periphere Zentralisation", correct: true }, { text: "Hypotonie oder zunehmende Kreislaufinstabilität", correct: true }, { text: "Bewusstseinsveränderung bei fehlender äußerer Blutungsquelle", correct: true }, { text: "Isolierte Normothermie beweist eine stabile Hämodynamik" }], source: "Die innere Blutung kann sich vor allem durch dynamische Schockzeichen zeigen; Einzelwerte dürfen nicht isoliert beruhigen.", difficulty: 2 },
  { id: "abd-q-12", mode: "multiple", prompt: "Welche Aussagen zur Tranexamsäure entsprechen L2 und Anlage B2A?", options: [{ text: "Indikation sind lebensbedrohliche Blutungen und/oder hämorrhagischer Schock beim Erwachsenen", correct: true }, { text: "Verabreicht wird 1 g Tranexamsäure als Kurzinfusion über 10 Minuten", correct: true }, { text: "Aus 500 mg/5 ml werden 10 ml entnommen und mit 90 ml NaCl 0,9 % zubereitet", correct: true }, { text: "Tranexamsäure wird bei jedem leichten Bauchschmerz ohne Blutungszeichen routinemäßig gegeben" }], source: "L2 nennt 1 g über 10 Minuten; B2A nennt 1 g (10 ml) plus 90 ml NaCl 0,9 %.", difficulty: 2 },
  { id: "abd-q-13", mode: "multiple", prompt: "Welche Aussagen zur starken traumatischen Schmerzsymptomatik sind nach VFA 35 korrekt?", options: [{ text: "Der Basisalgorithmus gilt ab NRS ≥ 5", correct: true }, { text: "OPQRST und das Ergründen der Schmerzursache gehören vor die Medikamentenauswahl", correct: true }, { text: "Bei traumatischem Schmerz führt der Pfad je nach ÄLRD-Vorgabe zu Esketamin oder Morphin", correct: true }, { text: "Eine Analgesie ersetzt Monitoring und Transportentscheidung" }], source: "VFA 35 verbindet cABCDE, OPQRST, ursachenbezogene Einordnung, passenden Medikamentenpfad, Monitoring und Transport.", difficulty: 2 },
  { id: "abd-q-14", mode: "multiple", prompt: "Ein Patient ist nach Lenkradaufprall zunächst normoton, wird aber blass und tachykard. Welche Schlüsse sind begründet?", options: [{ text: "Eine kompensierte innere Blutung bleibt möglich", correct: true }, { text: "Serielle Vitalwerte und wiederholter Bauchbefund sind erforderlich", correct: true }, { text: "Frühzeitige Transport- und Traumazentrumsentscheidung darf nicht bis zur Hypotonie warten", correct: true }, { text: "Der erste normale Blutdruck beendet die Schockdiagnostik" }], source: "Die Dynamik ist entscheidend; eine relevante Blutung kann vor dem Blutdruckabfall kompensiert sein.", difficulty: 3 },
  { id: "abd-q-15", mode: "multiple", prompt: "Welche Konstellationen erfordern eine zeitkritische Traumazentrumsversorgung?", options: [{ text: "Schockzeichen ohne kontrollierbare äußere Blutungsquelle", correct: true }, { text: "Penetrierendes Bauchtrauma mit möglicher Organ- oder Gefäßverletzung", correct: true }, { text: "Abwehrspannung, Eviszeration oder zunehmender Bauchumfang nach Trauma", correct: true }, { text: "Isolierter kleiner Hautkratzer ohne Schmerz, Mechanismus oder Auffälligkeit" }], source: "Bei relevanter innerer Verletzung gilt Load-go-and-treat mit Voranmeldung und geeigneter OP-Bereitschaft.", difficulty: 3 },
  { id: "abd-q-16", mode: "multiple", prompt: "Welche Aussagen helfen, retroperitoneale Verletzungen nicht zu übersehen?", options: [{ text: "Ein geringer vorderer Bauchbefund schließt eine erhebliche retroperitoneale Blutung nicht aus", correct: true }, { text: "Flankenschmerz, Flankenhämatom oder Hämaturie können auf eine Nierenverletzung hinweisen", correct: true }, { text: "Hochrasanz- und Beckentrauma können große Gefäße oder Urogenitalorgane verletzen", correct: true }, { text: "Retroperitoneale Blutungen verursachen zwingend sofort eine Eviszeration" }], source: "Nieren, große Gefäße und Beckenstrukturen können retroperitoneal verletzt sein und äußerlich zunächst wenig Befund zeigen.", difficulty: 3 },
  { id: "abd-q-17", mode: "multiple", prompt: "Welche Handlungen würden bei möglicher innerer Blutung die Versorgung korrekt priorisieren?", options: [{ text: "cABCDE und parallele Notarzt-, Transport- und Zielklinikplanung", correct: true }, { text: "Wärmeerhalt und Vermeidung unnötiger Verzögerungen am Einsatzort", correct: true }, { text: "Tranexamsäure bei erfüllter VFA-Indikation sowie überwachte Analgesie nach passendem Pfad", correct: true }, { text: "Ausführliche wiederholte Palpation bis eine Organverletzung sicher lokalisiert ist" }], source: "Lebensrettende Maßnahmen, Blutungs- und Schockmanagement sowie zügige definitive Versorgung laufen parallel.", difficulty: 3 },
  { id: "abd-q-18", mode: "multiple", prompt: "Welche Angaben sind für Voranmeldung und Übergabe bei Abdominaltrauma wesentlich?", options: [{ text: "Mechanismus, Zeitpunkt und vermutete betroffene Körperregionen", correct: true }, { text: "Vitaltrend, Schockzeichen und Verlauf des Bauchbefunds", correct: true }, { text: "Zugänge, Flüssigkeit, Tranexamsäure und Analgesie mit Dosis, Zeitpunkt und Wirkung", correct: true }, { text: "Nur die Bezeichnung Abdominaltrauma ohne Befunde oder Verlauf" }], source: "Die strukturierte Übergabe muss Mechanismus, Befunde, Dynamik, Maßnahmen und begründete Zielwahl enthalten.", difficulty: 3 },
];

export const abdominaltraumaQuestions: AbdominaltraumaChoiceQuestion[] = [...abdominaltraumaBaseQuestions, ...supplementalQuestions.abdominaltrauma];
