import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct: boolean];
function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  const shift = (number * 2) % options.length;
  return { id: `akutes-abdomen-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty };
}

export const akutesAbdomenFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "akutes-abdomen-card-01", area: "Definition", question: "Warum ist das akute Abdomen keine eigenständige Diagnose?", answer: "Es ist ein potenziell lebensbedrohlicher Symptomenkomplex unterschiedlicher abdominaler, extraabdominaler oder metabolischer Ursachen. Präklinisch werden Gefährdung, Arbeitshypothesen und Transportpriorität bestimmt; die endgültige Diagnose erfolgt klinisch." },
  { id: "akutes-abdomen-card-02", area: "Schmerzphysiologie", question: "Grenzen Sie viszeralen, somatischen und kolikartigen Schmerz ab.", answer: "Viszeraler Schmerz ist meist diffus und schlecht lokalisierbar. Somatischer Schmerz durch parietale Peritonealreizung ist scharf, lokalisierbar und bewegungsabhängig. Kolik entsteht durch wellenförmige Kontraktionen eines Hohlorgans gegen einen Widerstand." },
  { id: "akutes-abdomen-card-03", area: "Anatomie", question: "Nennen Sie die wesentlichen Wandschichten eines Hohlorgans und ihre Bedeutung.", answer: "Mukosa für Barriere, Sekretion und Resorption; Submukosa mit Gefäßen und Nerven; Muscularis mit Ring- und Längsmuskulatur für Motilität; außen Serosa als viszerales Peritoneum oder Adventitia zur Verbindung mit der Umgebung." },
  { id: "akutes-abdomen-card-04", area: "Appendizitis", question: "Erklären Sie die typische Schmerzwanderung bei Appendizitis.", answer: "Frühe viszerale Afferenzen erzeugen häufig diffusen periumbilikalen Schmerz. Greift die Entzündung auf das parietale Peritoneum über, wird der Schmerz im rechten Unterbauch genauer lokalisierbar und bewegungsempfindlich." },
  { id: "akutes-abdomen-card-05", area: "Ileus", question: "Warum unterscheiden Darmgeräusche mechanischen und paralytischen Ileus nicht sicher?", answer: "Ein mechanischer Ileus kann früh hochgestellte Geräusche verursachen, wird im Verlauf aber ebenfalls still. Ein paralytischer Ileus ist oft geräuscharm. Einzelne oder normale Geräusche schließen weder Verschluss noch Ischämie aus." },
  { id: "akutes-abdomen-card-06", area: "Mesenterialischämie", question: "Welche Prüfungsfalle kennzeichnet die frühe Mesenterialischämie?", answer: "Der Schmerz kann plötzlich extrem sein, während der Bauch zunächst weich und palpatorisch wenig auffällig bleibt. Eine spätere Schmerzabnahme kann durch Darmwandnekrose entstehen und ist keine sichere Besserung." },
  { id: "akutes-abdomen-card-07", area: "Peritonitis", question: "Wie entstehen Abwehrspannung und Kreislaufstörung?", answer: "Reizung des parietalen Peritoneums löst reflektorische Muskelanspannung aus. Entzündungsbedingte Vasodilatation, Kapillarleck und Third Spacing können zusammen mit Flüssigkeitsverlust eine distributive und hypovolämische Kreislaufkomponente erzeugen." },
  { id: "akutes-abdomen-card-08", area: "Diagnostik", question: "Wie untersuchen Sie den Bauch präklinisch schonend?", answer: "Inspektion, Auskultation, vorsichtige Perkussion und zuletzt sanfte Palpation, möglichst von schmerzfern nach schmerznah. Keine wiederholten oder erzwungenen Provokationstests; Untersuchung darf Transport und Analgesie nicht verzögern." },
  { id: "akutes-abdomen-card-09", area: "Red Flags", question: "Welche Befunde machen das akute Abdomen zeitkritisch?", answer: "Schockzeichen, Peritonismus, plötzlicher oder progredienter Schmerz, innere Blutungszeichen, persistierendes Erbrechen, Stuhl- und Windverhalt, hohes Fieber, Schmerz-Befund-Diskrepanz sowie besondere Risiken wie Schwangerschaft, Antikoagulation oder Vorhofflimmern." },
  { id: "akutes-abdomen-card-10", area: "Differenzialdiagnosen", question: "Welche nicht primär abdominalen Ursachen dürfen nicht übersehen werden?", answer: "ACS beziehungsweise inferiorer Infarkt, Aortendissektion, basale Pneumonie, Lungenembolie, diabetische Ketoazidose, Intoxikation und muskuloskelettale Ursachen; bei gebärfähigen Personen zusätzlich gynäkologische Notfälle." },
  { id: "akutes-abdomen-card-11", area: "Metamizol", question: "Nennen Sie Wirkung, VFA-Grenzen und zentrale Risiken von Metamizol.", answer: "Analgetisch, antipyretisch und spasmolytisch. VFA 39: nicht bei Schwangerschaft/Stillzeit und im Ablauf nicht bei RRsys unter 100 mmHg. Risiken sind vor allem Hypotonie bei zu rascher i.v.-Gabe, Anaphylaxie und Agranulozytose." },
  { id: "akutes-abdomen-card-12", area: "Agranulozytose", question: "Was ist eine Agranulozytose und welche Warnzeichen gehören in die Risikoaufklärung?", answer: "Ein ausgeprägter Abfall neutrophiler Granulozyten mit hoher Gefahr schwerer Infektionen. Warnzeichen sind Fieber, Schüttelfrost, starkes Krankheitsgefühl, Halsschmerzen sowie schmerzhafte Veränderungen der Mund- und Rachenschleimhaut." },
  { id: "akutes-abdomen-card-13", area: "Butylscopolamin", question: "Wie wirkt Butylscopolamin und wann ist es problematisch?", answer: "Als peripheres Antimuskarinikum entspannt es glatte Muskulatur im GI-, Gallen- und Urogenitaltrakt. Kontraindikationen sind unter anderem mechanischer Ileus, Megakolon, tachykarde Rhythmusstörung, Engwinkelglaukom und Myasthenia gravis." },
  { id: "akutes-abdomen-card-14", area: "VFA 39", question: "Leiten Sie den Thüringer Medikamentenpfad für starke sonstige Schmerzen her.", answer: "Ab NRS 5 cABCDE; bei Schmerz oberhalb des Nabels STEMI-Kriterien prüfen. Bei RRsys mindestens 100 mmHg und nach Risikoaufklärung 1 g Metamizol mit NaCl 0,9 % auf insgesamt 100 ml, Gabe über 5 Minuten. Bei kolikartigem Charakter und fehlender Kontraindikation 20 mg Butylscopolamin mit 9 ml NaCl langsam i.v.; Monitoring und Transport." },
  { id: "akutes-abdomen-card-15", area: "Zubereitung", question: "Berechnen Sie die VFA-Zubereitungen von Metamizol und Butylscopolamin.", answer: "Metamizol: 1 g in 2 ml plus 98 ml NaCl ergibt 100 ml mit 10 mg/ml. Butylscopolamin: 20 mg in 1 ml plus 9 ml NaCl ergibt 10 ml mit 2 mg/ml. Beide Medikamente werden getrennt zubereitet." },
  { id: "akutes-abdomen-card-16", area: "Entscheidung", question: "Wie priorisieren Sie stabiles, dringliches und instabiles akutes Abdomen?", answer: "Stabil ohne Red Flags: fokussierte Diagnostik und zeitnaher Transport. Starker Schmerz oder Peritonismus: Analgesie, kurze Einsatzzeit, geeignete Klinik und Notarzt nach Lage. Schock oder Rupturverdacht: sofortiges Load-and-go mit paralleler Stabilisierung und Reanimationsbereitschaft." },
];

export const akutesAbdomenQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen definieren das akute Abdomen fachlich korrekt?", [["Es beschreibt einen dringlich abklärungsbedürftigen Symptomenkomplex", true], ["Die Ursache kann abdominal, extraabdominal oder metabolisch sein", true], ["Eine endgültige Organdiagnose ist präklinisch nicht zwingend erforderlich", true], ["Es bezeichnet ausschließlich eine bakterielle Peritonitis", false], ["Ein weicher Bauch schließt das Syndrom sicher aus", false]], "Das akute Abdomen ist ein Syndrom mit breitem Ursachenspektrum.", 1),
  q(2, "Welche Zuordnungen zur Schmerzphysiologie sind korrekt?", [["Viszeraler Schmerz ist häufig diffus und schlecht lokalisierbar", true], ["Parietale Peritonealreizung verursacht eher lokalisierbaren Bewegungsschmerz", true], ["Kolik entsteht durch Kontraktion eines Hohlorgans gegen Widerstand", true], ["Somatischer Schmerz bleibt typischerweise immer mittig und diffus", false], ["Kolik beweist eine bestimmte Organdiagnose", false]], "Die Schmerzqualität hilft bei der Einordnung, beweist aber keine Ursache.", 2),
  q(3, "Welche Aussagen zum Aufbau der Darmwand treffen zu?", [["Die Mukosa erfüllt Barriere-, Sekretions- und Resorptionsfunktionen", true], ["Die Submukosa führt Gefäße und Nerven", true], ["Ring- und Längsmuskulatur ermöglichen Motilität", true], ["Die Serosa liegt immer lumennah innerhalb der Mukosa", false], ["Die Adventitia erzeugt als einzige Schicht Kolikschmerz", false]], "Wandaufbau und Muskelschichten erklären Entzündung, Ödem und Motilität.", 2),
  q(4, "Welche Befunde passen zu einem Übergang von viszeralem zu somatischem Schmerz bei Appendizitis?", [["Anfangs diffuser periumbilikaler Schmerz", true], ["Später lokalisierter Schmerz im rechten Unterbauch", true], ["Zunehmende Bewegungs- oder Erschütterungsempfindlichkeit", true], ["Dauerhaft ausschließlich linksseitiger Thoraxschmerz", false], ["Schlagartige Beschwerdefreiheit beweist Heilung", false]], "Die Ausbreitung auf das parietale Peritoneum verändert Lokalisation und Schmerzcharakter.", 2),
  q(5, "Welche Aussagen zu Darmgeräuschen bei Ileus sind belastbar?", [["Früher mechanischer Ileus kann hochgestellte Geräusche verursachen", true], ["Im Verlauf kann auch ein mechanischer Ileus geräuscharm werden", true], ["Darmgeräusche werden nur zusammen mit Klinik und Verlauf gewertet", true], ["Stille beweist immer einen rein paralytischen Ileus", false], ["Normale Geräusche schließen eine Obstruktion sicher aus", false]], "Auskultation allein trennt Ileusformen nicht sicher.", 3),
  q(6, "Welche Konstellationen erhöhen den Verdacht auf einen mechanischen Ileus?", [["Kolikartiger Schmerz mit Erbrechen und Windverhalt", true], ["Voroperationen mit möglicher Adhäsionsbildung", true], ["Schmerzhafte oder nicht reponible Hernie", true], ["Isolierte Halsschmerzen ohne Bauchbeschwerden", false], ["Unauffällige Ausscheidung beweist einen vollständigen Verschluss", false]], "Obstruktive Symptome und typische Ursachen werden gemeinsam bewertet.", 2),
  q(7, "Welche Aussagen zur Mesenterialischämie sind prüfungsrelevant?", [["Extremer Schmerz kann einem zunächst geringen Palpationsbefund gegenüberstehen", true], ["Vorhofflimmern ist ein wichtiger embolischer Risikofaktor", true], ["Spätere Schmerzabnahme kann durch Darmwandnekrose entstehen", true], ["Ein weicher Bauch schließt frühe Ischämie aus", false], ["Weniger Schmerz beweist eine erfolgreiche Reperfusion", false]], "Schmerz-Befund-Diskrepanz und trügerische Schmerzabnahme sind klassische Fallen.", 3),
  q(8, "Welche Befunde können eine akute Pankreatitis stützen?", [["Oberbauchschmerz mit Ausstrahlung in den Rücken", true], ["Übelkeit und wiederholtes Erbrechen", true], ["Entlastung in vorgebeugter Haltung", true], ["Obligate Schmerzfreiheit in Rückenlage", false], ["Pankreatitis kann keinen paralytischen Ileus auslösen", false]], "Pankreatitis kann ein schweres systemisches Krankheitsbild und einen Ileus verursachen.", 2),
  q(9, "Welche Vorgänge können bei Peritonitis zur Kreislaufstörung beitragen?", [["Kapillarleck und Flüssigkeitsverschiebung in den dritten Raum", true], ["Entzündungsbedingte Vasodilatation", true], ["Zusätzlicher Flüssigkeitsverlust durch Erbrechen", true], ["Obligate isolierte arterielle Hypertonie", false], ["Ausschließlich ein mechanischer Verschluss der Aorta", false]], "Distributive und hypovolämische Komponenten können zusammenwirken.", 3),
  q(10, "Welche Befunde gelten als Red Flags beim akuten Abdomen?", [["Abwehrspannung oder ausgeprägter Peritonismus", true], ["Schockzeichen oder Zeichen innerer Blutung", true], ["Plötzlicher stärkster oder rasch progredienter Schmerz", true], ["Kurzfristige Besserung nach heftigem Schmerz als sichere Entwarnung", false], ["Einmalig normale Temperatur als Ausschluss einer Sepsis", false]], "Red Flags bestimmen Zeitkritik stärker als eine präklinische Ortsdiagnose.", 2),
  q(11, "Welche Untersuchungsstrategie ist präklinisch sinnvoll?", [["Zuerst Inspektion und schonende Beobachtung", true], ["Auskultation vor tiefer Palpation", true], ["Sanfte Palpation von schmerzfern nach schmerznah", true], ["Loslassschmerz mehrfach maximal provozieren", false], ["Untersuchung bis zur sicheren Diagnose ausdehnen und Transport zurückstellen", false]], "Die Untersuchung bleibt schonend, fokussiert und transportorientiert.", 2),
  q(12, "Welche Maßnahmen gehören zur Erstversorgung?", [["cABCDE und engmaschige Kreislaufbeurteilung", true], ["BZ, Temperatur und bei Oberbauchschmerz 12-Kanal-EKG", true], ["Schmerzadaptierte Lagerung, Nüchternheit und Wärmeerhalt", true], ["Routinemäßige orale Flüssigkeitsgabe bei möglichem Ileus", false], ["Analgesie grundsätzlich bis zur Klinik vermeiden", false]], "Basisdiagnostik, Symptomkontrolle und zügiger Transport laufen parallel.", 2),
  q(13, "Welche Anamnesepunkte verändern die Gefährdungseinschätzung besonders?", [["Vorhofflimmern bei plötzlich extremem Schmerz", true], ["Antikoagulation bei möglicher innerer Blutung", true], ["Schwangerschaftsmöglichkeit bei Unterbauchschmerz", true], ["Frühere Bauchoperationen ohne Bedeutung für Ileus", false], ["Alter schließt atypische Verläufe aus", false]], "Risikofaktoren lenken auf zeitkritische, anfangs diskrete Ursachen.", 3),
  q(14, "Welche extraabdominalen oder metabolischen Differenzialdiagnosen müssen bedacht werden?", [["Akutes Koronarsyndrom", true], ["Basale Pneumonie oder Lungenembolie", true], ["Diabetische Ketoazidose", true], ["Appendizitis als extraabdominale Ursache", false], ["Peritonitis als reine Stoffwechselstörung", false]], "Bauchschmerz kann Ausdruck kardialer, thorakaler oder metabolischer Erkrankung sein.", 2),
  q(15, "Welche Aussagen zur Analgesie beim akuten Abdomen sind korrekt?", [["Starke Schmerzen dürfen indiziert und überwacht behandelt werden", true], ["Befunde und Wirkung werden vor und nach Gabe dokumentiert", true], ["Analgesie darf Transport oder Diagnostik nicht unnötig verzögern", true], ["Jedes Analgetikum macht eine spätere Diagnose unmöglich", false], ["Schmerztherapie ist nur nach endgültiger Organdiagnose zulässig", false]], "Moderne Akutversorgung verbindet Analgesie mit Verlaufskontrolle.", 2),
  q(16, "Welche Wirkungen treffen auf Metamizol zu?", [["Analgetische Wirkung", true], ["Antipyretische Wirkung", true], ["Spasmolytischer Wirkanteil", true], ["Direkte kompetitive Blockade muskarinischer Rezeptoren als Hauptmechanismus", false], ["Obligate Atemdepression wie bei einem starken Opioid", false]], "Metamizol ist ein nichtopioides Analgetikum mit antipyretischer und spasmolytischer Wirkung.", 1),
  q(17, "Welche Risiken von Metamizol müssen aktiv bedacht werden?", [["Hypotonie, besonders bei rascher i.v.-Gabe oder Volumenmangel", true], ["Anaphylaktische Reaktion", true], ["Agranulozytose mit schwerem Infektionsrisiko", true], ["Sichere Tachyphylaxie nach einer Einzeldosis", false], ["Vollständiger Schutz vor Fieber", false]], "Kreislauf, Allergie und seltene schwere Blutbildveränderung sind zentral.", 2),
  q(18, "Welche Symptome passen zur Risikoaufklärung über Agranulozytose?", [["Fieber und Schüttelfrost", true], ["Halsschmerzen und ausgeprägtes Krankheitsgefühl", true], ["Schmerzhafte Mund- oder Rachenschleimhautveränderungen", true], ["Isolierter Muskelkater nach Sport als Leitsymptom", false], ["Dauerhafte Mydriasis als typischer Erstbefund", false]], "Warnzeichen einer schweren Infektion erfordern sofortige ärztliche Abklärung.", 2),
  q(19, "Welche Aussagen beschreiben Butylscopolamin korrekt?", [["Es blockiert peripher muskarinische Acetylcholinrezeptoren", true], ["Es entspannt glatte Muskulatur im Gastrointestinal- und Urogenitaltrakt", true], ["Es wirkt spasmolytisch, ist aber kein eigenständiges Analgetikum", true], ["Es stimuliert gezielt die Darmmotilität bei mechanischem Ileus", false], ["Es ist ein Opioidagonist am μ-Rezeptor", false]], "Butylscopolamin ist ein peripheres Antimuskarinikum.", 2),
  q(20, "Welche Befunde sprechen gegen Butylscopolamin?", [["Verdacht auf mechanischen Ileus", true], ["Tachykarde Rhythmusstörung", true], ["Engwinkelglaukom oder Myasthenia gravis", true], ["Kolikartiger Schmerz ohne Kontraindikation", false], ["Normofrequenter Sinusrhythmus als alleinige Kontraindikation", false]], "Kolikcharakter ersetzt nie die Prüfung der Arzneimittelkontraindikationen.", 3),
  q(21, "Welche Nebenwirkungen sind bei Butylscopolamin plausibel?", [["Tachykardie", true], ["Mundtrockenheit und Akkommodationsstörung", true], ["Mydriasis, Schwindel oder Hautreaktion", true], ["Ausgeprägte Bronchorrhö als typische antimuskarine Wirkung", false], ["Zuverlässige Bradykardie bei jeder Gabe", false]], "Die Nebenwirkungen entsprechen überwiegend peripher anticholinergen Effekten.", 2),
  q(22, "Welche Angaben entsprechen dem Thüringer Pfad für sonstige starke Schmerzzustände?", [["Der Pfad beginnt bei NRS mindestens 5", true], ["Bei Schmerz oberhalb des Nabels werden STEMI-Kriterien geprüft", true], ["Kontinuierliches Monitoring und Transport gehören zum Ablauf", true], ["Bei positivem STEMI-Kriterium wird der Bauchschmerzpfad unverändert fortgesetzt", false], ["Ein Blutdruck unter 100 mmHg ist ohne Bedeutung für Metamizol", false]], "VFA 39 verbindet Schmerzeinschätzung, ACS-Screening und Kreislaufgrenze.", 3),
  q(23, "Welche Metamizol-Zubereitung entspricht der Thüringer Anlage B2A?", [["1 g Metamizol entspricht 2 ml Wirkstoff", true], ["Mit 98 ml NaCl beträgt das Gesamtvolumen 100 ml", true], ["Die resultierende Konzentration beträgt 10 mg/ml", true], ["Die Infusion wird als 10-ml-Bolus gegeben", false], ["2 ml Wirkstoff plus 8 ml NaCl ergeben die VFA-Kurzinfusion", false]], "1.000 mg in 100 ml ergeben 10 mg/ml; Gabe über 5 Minuten.", 3),
  q(24, "Welche Butylscopolamin-Zubereitung entspricht der Thüringer Anlage B2A?", [["20 mg befinden sich in 1 ml Wirkstoff", true], ["Mit 9 ml NaCl beträgt das Gesamtvolumen 10 ml", true], ["Die fertige Lösung enthält 2 mg/ml", true], ["Die VFA verlangt 20 mg als unverdünnten 10-ml-Bolus", false], ["Die fertige Konzentration beträgt 20 mg/ml", false]], "20 mg in 10 ml ergeben 2 mg/ml und werden langsam i.v. gegeben.", 3),
  q(25, "Ein Patient hat kolikartigen Schmerz, Erbrechen, Windverhalt und einen geblähten Bauch. Welche Schlüsse sind begründet?", [["Ein mechanischer Ileus muss als Ursache erwogen werden", true], ["Butylscopolamin ist trotz Kolikcharakter wegen Ileusverdachts kritisch beziehungsweise kontraindiziert", true], ["Absaug- und Reanimationsbereitschaft sind bei Verschlechterung sinnvoll", true], ["Kolikcharakter verpflichtet unabhängig von Gegenanzeigen zur Spasmolyse", false], ["Normale SpO₂ schließt eine zeitkritische abdominale Ursache aus", false]], "Der Ileusverdacht hat Vorrang vor einer automatischen Spasmolytikagabe.", 3),
  q(26, "Ein älterer Patient mit Vorhofflimmern berichtet plötzlich stärkste Bauchschmerzen; der Bauch ist zunächst weich. Welche Entscheidungen sind richtig?", [["Mesenterialischämie hat hohe Priorität", true], ["Der geringe Palpationsbefund darf nicht beruhigen", true], ["Kurze Einsatzzeit und dringliche klinische Abklärung sind erforderlich", true], ["Eine lokale Druckempfindlichkeit ist zwingend nötig", false], ["Erst bei bretthartem Bauch entsteht Zeitkritik", false]], "Die Diskrepanz von Schmerz und Befund ist bei vaskulärer Ursache besonders relevant.", 3),
  q(27, "Eine antikoagulierte Patientin im gebärfähigen Alter hat Unterbauchschmerz, Blässe und Tachykardie. Welche Schritte sind sinnvoll?", [["Innere Blutung und Extrauteringravidität aktiv erwägen", true], ["Schwangerschaftsanamnese und Blutungsverlauf erheben", true], ["Schockbehandlung und zügigen Transport parallel organisieren", true], ["Fehlende äußere Blutung als Entwarnung werten", false], ["Bis zur sicheren Diagnose orale Flüssigkeit anbieten", false]], "Innere Blutung kann ohne äußeres Zeichen fortschreiten; gynäkologische Ursachen gehören in die Differenzialdiagnose.", 3),
  q(28, "Welche vollständige Prüfungsantwort zeigt eine sichere Priorisierung?", [["Red Flags und cABCDE bestimmen die Dringlichkeit vor der Organdiagnose", true], ["Analgesie, Verlaufskontrolle und Transport werden parallel organisiert", true], ["Extraabdominale Ursachen sowie VFA-Kontraindikationen bleiben im Blick", true], ["Ein einzelner Schmerzpunkt beweist das betroffene Organ", false], ["Jede kolikartige Symptomatik wird unabhängig vom Ileusverdacht mit Butylscopolamin behandelt", false]], "Eine starke Antwort verbindet Gefährdung, Differenzialdiagnostik, Therapiegrenzen und Transportentscheidung.", 3),
];
