import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct: boolean];
function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  const shift = (number * 2) % options.length;
  return { id: `alkoholintoxikation-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty };
}

export const alkoholintoxikationFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "alkoholintoxikation-card-01", area: "Definition", question: "Definieren Sie die akute Alkoholintoxikation und nennen Sie die rettungsdienstliche Hauptgefahr.", answer: "Akute Vergiftung durch Ethanol mit dosis- und toleranzabhängiger Beeinträchtigung vor allem des ZNS. Vital bedrohlich sind Atemwegsverlust, Hypoventilation, Aspiration, Hypothermie, Hypoglykämie und übersehene Begleiterkrankungen oder Verletzungen." },
  { id: "alkoholintoxikation-card-02", area: "Leber", question: "Beschreiben Sie Aufnahme und Abbau von Ethanol.", answer: "Ethanol wird vor allem über Magen und Dünndarm aufgenommen, gelangt über die Pfortader zur Leber und wird überwiegend über Alkoholdehydrogenase zu Acetaldehyd sowie über Aldehyddehydrogenase zu Acetat oxidiert." },
  { id: "alkoholintoxikation-card-03", area: "Kinetik", question: "Was bedeutet Eliminationskinetik nullter Ordnung bei Ethanol?", answer: "Pro Zeiteinheit wird näherungsweise eine konstante Menge abgebaut. Eine höhere Konzentration beschleunigt den Abbau nicht proportional; Infusion oder Kaffee machen die hepatische Elimination nicht schneller." },
  { id: "alkoholintoxikation-card-04", area: "Neurophysiologie", question: "Wie verändert Ethanol die synaptische Erregung?", answer: "Ethanol verstärkt hemmende GABA-vermittelte Effekte und hemmt erregende glutamaterge, besonders NMDA-vermittelte, Signalübertragung. Netzwerke arbeiten langsamer; Koordination, Urteilsvermögen, Vigilanz und bei schwerer Intoxikation Schutzreflexe und Atmung nehmen ab." },
  { id: "alkoholintoxikation-card-05", area: "Gehirn", question: "Ordnen Sie typische Ausfälle den betroffenen Hirnregionen zu.", answer: "Großhirn: Enthemmung, Urteils-, Sprach- und Bewusstseinsstörung. Kleinhirn: Ataxie und Koordinationsstörung. Zwischenhirn/Hypothalamus: vegetative und thermische Regulation. Hirnstamm: Schutzreflexverlust, Atem- und Kreislaufstörung." },
  { id: "alkoholintoxikation-card-06", area: "Stoffwechsel", question: "Warum droht eine Hypoglykämie?", answer: "Der hepatische Ethanolabbau verändert das Redoxgleichgewicht und hemmt die Glukoneogenese. Das Risiko steigt besonders bei leeren Glykogenspeichern, Mangelernährung, Kindern oder längerer Nüchternheit." },
  { id: "alkoholintoxikation-card-07", area: "Wärme und Flüssigkeit", question: "Warum können Hypothermie und Flüssigkeitsverlust entstehen?", answer: "Periphere Vasodilatation steigert den Wärmeverlust, obwohl sich die Haut warm anfühlen kann. Gehemmte ADH-Freisetzung fördert Diurese; Erbrechen und fehlende Zufuhr können den Flüssigkeitsmangel verstärken." },
  { id: "alkoholintoxikation-card-08", area: "Symptome", question: "Warum dürfen Promillebereiche nicht allein die Schwere festlegen?", answer: "Toleranz, Trinkgeschwindigkeit, Magenfüllung, Alter, Körperzusammensetzung, Begleiterkrankungen und Mischkonsum verändern die klinische Wirkung. Behandelt wird der aktuelle ABCDE-Befund, nicht eine vermutete Zahl." },
  { id: "alkoholintoxikation-card-09", area: "Gefahren", question: "Nennen Sie sechs zeitkritische Gefahren.", answer: "Atemwegsverlegung, Aspiration, Hypoventilation/Apnoe, Hypoglykämie, Hypothermie sowie übersehenes SHT, Schlaganfall, Krampfanfall oder Mischintoxikation; zusätzlich kann ein Kreislaufstillstand eintreten." },
  { id: "alkoholintoxikation-card-10", area: "Erstmaßnahmen", question: "Strukturieren Sie die Erstversorgung.", answer: "Eigenschutz und Umfeld, cABCDE, Atemweg öffnen und absaugbereit sein, Atmung direkt beurteilen und bei Bedarf beatmen, Monitoring, BZ, Temperatur, Pupillen und fokale Neurologie, schnelle Traumauntersuchung, Wärmeerhalt und kontinuierliche Reevaluation." },
  { id: "alkoholintoxikation-card-11", area: "Atemweg", question: "Wann reicht eine stabile Seitenlage nicht aus?", answer: "Bei unzureichender Ventilation, nicht beherrschbarer Aspiration, fortschreitendem Schutzreflexverlust oder nicht offen zu haltendem Atemweg. Dann sind Maskenbeatmung und das eskalierende Atemwegsmanagement vorzubereiten beziehungsweise durchzuführen." },
  { id: "alkoholintoxikation-card-12", area: "Differenzialdiagnosen", question: "Welche Diagnosen dürfen nicht vorschnell als Rausch fehlgedeutet werden?", answer: "Hypoglykämie, SHT oder intrakranielle Blutung, Apoplex, postiktaler Zustand, Hypothermie, Sepsis, CO-Exposition, metabolische Störung sowie Opiat-, Benzodiazepin- oder andere Mischintoxikation." },
  { id: "alkoholintoxikation-card-13", area: "Trauma", question: "Warum gehört eine strukturierte Traumauntersuchung dazu?", answer: "Stürze, Gewalt und Verkehrsunfälle sind häufig; Schmerz, Erinnerung und Kooperation können vermindert sein. Alkohol erklärt weder äußere Verletzungen noch Anisokorie, fokale Neurologie oder eine unerwartete Vigilanzdynamik." },
  { id: "alkoholintoxikation-card-14", area: "Therapiegrenze", question: "Beschleunigt eine kristalloide Infusion den Alkoholabbau?", answer: "Nein. Sie kann bei klinischem Volumenmangel oder Kreislaufproblem indiziert sein, beschleunigt aber nicht die enzymatisch begrenzte hepatische Elimination und ersetzt weder Atemwegsmanagement noch Wärmeerhalt." },
  { id: "alkoholintoxikation-card-15", area: "Entscheidungsfähigkeit", question: "Wie ist eine Transportverweigerung einzuordnen?", answer: "Intoxikation macht nicht automatisch jede Entscheidung unwirksam. Verständnis, Einsicht, Abwägungsfähigkeit und freie Willensbildung müssen konkret geprüft und dokumentiert werden. Bei Zweifel, Selbst- oder Fremdgefährdung früh Notarzt und gegebenenfalls Polizei einbinden." },
  { id: "alkoholintoxikation-card-16", area: "Übergabe", question: "Welche Informationen gehören in die Klinikübergabe?", answer: "Getränk/Substanz, geschätzte Menge und Zeitraum, letzte sichere Normalität, Mischkonsum und Suizidkontext, initialer und aktueller ABCDE-Befund, BZ/Temperatur/Neurologie, Erbrechen/Aspiration, Trauma, Maßnahmen und Verlauf." },
];

export const alkoholintoxikationQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen beschreiben eine Alkoholintoxikation fachlich korrekt?", [["Ethanol kann das zentrale Nervensystem bis zum Schutzreflexverlust dämpfen", true], ["Die klinische Gefährdung hängt nicht allein von der Blutalkoholkonzentration ab", true], ["Begleiterkrankungen und Verletzungen müssen parallel gesucht werden", true], ["Alkohol erklärt jedes fokale neurologische Defizit ausreichend", false], ["Ein wacher Patient kann keine relevante Mischintoxikation haben", false]], "Entscheidend sind klinischer Befund, Toleranz, Dynamik und Begleitursachen.", 1),
  q(2, "Welche Schritte gehören zum Weg des Ethanols durch den Körper?", [["Resorption über Magen und vor allem Dünndarm", true], ["Transport über die Pfortader zur Leber", true], ["Oxidation über Alkohol- und Aldehyddehydrogenase", true], ["Primäre Ausscheidung unverändert ausschließlich über die Niere", false], ["Abbau ohne Beteiligung von Hepatozyten", false]], "Die Leber ist das zentrale Stoffwechselorgan des Ethanolabbaus.", 2),
  q(3, "Was folgt aus der annähernden Kinetik nullter Ordnung?", [["Pro Zeiteinheit wird näherungsweise eine konstante Menge abgebaut", true], ["Eine höhere Konzentration steigert die Eliminationsrate nicht proportional", true], ["Zeit bleibt ein wesentlicher Faktor der Ausnüchterung", true], ["Kristalloide Infusion verdoppelt regelhaft die Abbaugeschwindigkeit", false], ["Kaffee aktiviert einen schnellen renalen Ethanolabbau", false]], "Supportive Therapie behandelt Folgen, nicht die enzymatisch begrenzte Eliminationsgeschwindigkeit.", 2),
  q(4, "Welche neurophysiologischen Wirkungen erklären den Rausch?", [["Verstärkung hemmender GABA-vermittelter Effekte", true], ["Hemmung erregender glutamaterger Signalübertragung", true], ["Verlangsamung neuronaler Netzwerkfunktionen", true], ["Selektive Aktivierung aller NMDA-Rezeptoren", false], ["Dauerhafte Blockade sämtlicher Synapsen bereits im Exzitationsstadium", false]], "Die Verschiebung zugunsten neuronaler Hemmung erklärt Koordinations- und Vigilanzstörungen.", 2),
  q(5, "Welche Zuordnungen von Hirnregion und Befund sind plausibel?", [["Kleinhirn – Ataxie und Koordinationsstörung", true], ["Großhirn – Enthemmung, Sprache und Bewusstsein", true], ["Hirnstamm – Schutzreflexe und Atmungsregulation", true], ["Okzipitallappen – alleinige Steuerung der Glukoneogenese", false], ["Rückenmark – alleiniger Ursprung der alkoholbedingten Amnesie", false]], "Das klinische Bild entsteht durch die Beeinträchtigung mehrerer neuronaler Netzwerke.", 2),
  q(6, "Welche Mechanismen erhöhen das Hypoglykämierisiko?", [["Hemmung der hepatischen Glukoneogenese", true], ["Leere Glykogenspeicher nach Nüchternheit", true], ["Mangelernährung oder junges Alter", true], ["Verlässlich gesteigerte Glukoseneubildung durch Ethanol", false], ["Ein warmer Hautbefund schließt Hypoglykämie aus", false]], "BZ-Messung gehört zur frühen Differenzialdiagnostik der Bewusstseinsstörung.", 3),
  q(7, "Welche Aussagen erklären Hypothermie und Flüssigkeitsverlust?", [["Periphere Vasodilatation erhöht die Wärmeabgabe", true], ["Gehemmte ADH-Freisetzung kann die Diurese steigern", true], ["Erbrechen und fehlende Zufuhr können Volumenmangel verstärken", true], ["Subjektives Wärmegefühl beweist eine stabile Kerntemperatur", false], ["Alkohol verhindert Wärmeverlust durch dauerhafte Vasokonstriktion", false]], "Warme Haut kann einen fortschreitenden Verlust der Körperwärme verschleiern.", 2),
  q(8, "Welche Aussagen zur Stadieneinteilung sind prüfungsrelevant?", [["Mit zunehmender Wirkung können Bewusstsein und Schutzreflexe abnehmen", true], ["Erbrechen und Aggressivität können bereits vor dem Koma auftreten", true], ["Promillebereiche sind nur orientierend und individuell variabel", true], ["Eine bestimmte Promillezahl ersetzt die ABCDE-Beurteilung", false], ["Gewöhnung macht eine schwere Intoxikation grundsätzlich ungefährlich", false]], "Die Therapie richtet sich nach dem klinischen Zustand und Verlauf.", 2),
  q(9, "Ein somnolenter Patient riecht nach Alkohol. Welche Untersuchungen sind unverzichtbar?", [["Blutzuckermessung und Temperatur", true], ["Pupillen, fokale Neurologie und Verlauf des Bewusstseins", true], ["Schnelle Traumauntersuchung einschließlich Kopf", true], ["Verzicht auf Neurologie bei glaubhafter Fremdanamnese", false], ["Alleinige Schätzung der Trinkmenge", false]], "Alkoholgeruch ist ein Befund, aber keine Ausschlussdiagnostik.", 3),
  q(10, "Welche Befunde sprechen für eine unmittelbar gefährdete Atemwegssituation?", [["Wiederholtes Erbrechen bei deutlich reduzierter Vigilanz", true], ["Fehlende oder unsichere Schutzreflexe", true], ["Unzureichende Eigenatmung mit steigender CO₂-Tendenz", true], ["Lallende Sprache bei sicherem Atemweg als alleinige Intubationsindikation", false], ["Ein einzelner normaler SpO₂-Wert unter Sauerstoff als Entwarnung", false]], "Atemweg, Ventilation und Aspirationsrisiko werden gemeinsam beurteilt.", 3),
  q(11, "Welche Maßnahmen sind bei Erbrechen und Bewusstseinsminderung sinnvoll?", [["Absaugbereitschaft herstellen und Atemweg öffnen", true], ["Bei ausreichender Eigenatmung geeignete Seitenlagerung erwägen", true], ["Ventilation fortlaufend direkt beurteilen", true], ["Aktivkohle bei fehlenden Schutzreflexen routinemäßig geben", false], ["Den Patienten zur Aspirationsprophylaxe flach fixieren", false]], "Lagerung allein ersetzt keine Beatmung oder weiterführende Atemwegssicherung.", 2),
  q(12, "Welche Differenzialdiagnosen können wie ein Alkoholrausch erscheinen?", [["Hypoglykämie", true], ["Schädel-Hirn-Trauma oder intrakranielle Blutung", true], ["Postiktaler Zustand oder Apoplex", true], ["Isolierte Alkoholintoxikation als einzige mögliche Ursache bei Alkoholgeruch", false], ["Normothermie als Beweis gegen eine Mischintoxikation", false]], "Bewusstseinsstörung bleibt ein Syndrom mit breiter Differenzialdiagnose.", 2),
  q(13, "Welche Befunde machen eine zusätzliche Kopfverletzung wahrscheinlicher?", [["Unplausible Vigilanzdynamik", true], ["Anisokorie oder fokales neurologisches Defizit", true], ["Traumazeichen und passende Kinematik", true], ["Alkoholgeruch ohne äußere Verletzung", false], ["Vorübergehende Enthemmung als sicherer Ausschluss", false]], "Eine Intoxikation kann Symptome und Schmerzen einer Verletzung überdecken.", 3),
  q(14, "Welche Aussagen zur Mischintoxikation treffen zu?", [["Benzodiazepine oder Opioide können die Atemdepression verstärken", true], ["Suizidaler Kontext erhöht die Wahrscheinlichkeit weiterer Substanzen", true], ["Pupillenbefund und Atmung können vom reinen Alkoholbild abweichen", true], ["Eine bekannte Trinkmenge schließt weitere Substanzen aus", false], ["Aufklaren nach Ansprache beweist eine Monointoxikation", false]], "Fremdanamnese, Umfeld und Verlauf sind für die Erkennung entscheidend.", 3),
  q(15, "Welche Aussagen zur intravenösen Flüssigkeitsgabe sind korrekt?", [["Sie kann bei klinischem Volumenmangel indiziert sein", true], ["Sie behandelt nicht den alkoholbedingten Schutzreflexverlust", true], ["Sie beschleunigt den hepatischen Ethanolabbau nicht relevant", true], ["Sie ersetzt Wärmeerhalt und Blutzuckerkontrolle", false], ["Sie ist bei jedem alkoholisierten Patienten unabhängig vom Befund zwingend", false]], "Die Behandlung bleibt befundorientiert; eine Infusion ist kein Ausnüchterungsmittel.", 3),
  q(16, "Welche Parameter beurteilen eine beginnende respiratorische Verschlechterung?", [["Atemfrequenz, Atemtiefe und Thoraxexkursion", true], ["Kapnografie und klinischer Verlauf", true], ["SpO₂ zusammen mit der verabreichten Sauerstoffmenge", true], ["Nur die Pupillenweite", false], ["Nur ein einmaliger Blutdruckwert", false]], "Unter Sauerstoff kann die Pulsoxymetrie eine Hypoventilation verzögert anzeigen.", 3),
  q(17, "Welche Aussagen zum eskalierenden Atemwegsmanagement passen zur Thüringer VFA?", [["Zunächst werden Absaugung, Positionierung und Beutel-Masken-Beatmung optimiert", true], ["Bei erforderlicher Sicherung ist die supraglottische Atemwegshilfe eine Eskalationsstufe", true], ["Nach jeder Stufe werden Beatmung und Erfolg erneut geprüft", true], ["Eine Intubation ist stets der erste Schritt vor Maskenbeatmung", false], ["Kapnografie ist nach Atemwegssicherung entbehrlich", false]], "VFA 04 strukturiert das Vorgehen stufenweise und erfolgskontrolliert.", 3),
  q(18, "Welche Gefahren müssen im Verlauf aktiv verhindert werden?", [["Aspiration und Atemstillstand", true], ["Hypothermie und Hypoglykämie", true], ["Übersehene Verletzung oder neurologische Erkrankung", true], ["Beschleunigte Ausnüchterung durch unkontrollierte Hyperventilation", false], ["Therapieabbruch nach einmaligem Aufklaren", false]], "Reevaluation ist nötig, weil Bewusstsein und Atmung dynamisch verlaufen können.", 2),
  q(19, "Ein Patient wird aggressiv und lehnt den Transport ab. Welche Aussagen tragen die Entscheidung?", [["Entscheidungsfähigkeit muss konkret geprüft werden", true], ["Verständnis, Abwägung und freie Willensbildung sind zu dokumentieren", true], ["Bei Gefährdung oder erheblichem Zweifel sind Notarzt und gegebenenfalls Polizei früh einzubinden", true], ["Jeder Alkoholkonsum bedeutet automatisch vollständige Einwilligungsunfähigkeit", false], ["Aggressivität erlaubt ohne weitere Prüfung den alleinigen Abbruch der Versorgung", false]], "Die Entscheidung richtet sich nach der konkreten Fähigkeit und Gefährdung, nicht nur nach einem Etikett.", 3),
  q(20, "Welche Inhalte gehören in eine fokussierte SAMPLERS-Anamnese?", [["Menge, Art, Zeitraum und Applikationsweg", true], ["Mischkonsum, Medikamente und Suizidabsicht", true], ["Trauma, Krampfanfall und letzte sichere Normalität", true], ["Nur die Lieblingsgetränkemarke", false], ["Ausschließlich eine Promilleschätzung durch Angehörige", false]], "Die Anamnese verbindet Exposition, Begleitumstände und gefährliche Alternativursachen.", 2),
  q(21, "Ein Patient ist komatös, erbricht und atmet unregelmäßig. Welche Prioritäten sind richtig?", [["Atemweg öffnen, absaugen und wirksam beatmen", true], ["Notarzt- und Atemwegshilfe früh nachfordern", true], ["Parallel BZ, Temperatur und Traumahinweise erfassen, ohne die Ventilation zu verzögern", true], ["Zunächst die genaue Trinkmenge berechnen", false], ["Auf eine spontane Ausnüchterung am Einsatzort warten", false]], "Vitale Maßnahmen haben Vorrang; Differenzialdiagnostik läuft parallel.", 3),
  q(22, "Welche vollständige Prüfungsantwort verbindet Pathophysiologie und Versorgung korrekt?", [["Zentrale Hemmung erklärt Koordinations-, Vigilanz- und Atemstörung", true], ["Gehemmte Glukoneogenese und Wärmeverlust begründen BZ- und Temperaturkontrolle", true], ["Aspirationsgefahr und mögliche Begleitdiagnosen verlangen cABCDE und Reevaluation", true], ["Promillewert und Alkoholgeruch machen weitere Diagnostik überflüssig", false], ["Infusion und Kaffee ersetzen Zeit und Atemwegsmanagement", false]], "Eine starke Antwort verbindet ZNS, Leberstoffwechsel, Gefahren und konsequente Differenzialdiagnostik.", 3),
];
