import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function AlkoholintoxikationLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, kicker: string, title: string, body: ReactNode) => <details open className="lesson-section rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>{kicker}</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;

  return <article className="lesson-article angina-pectoris-lesson reference-reading-lesson alkoholintoxikation-lesson">
    <div className="lesson-intro"><p className="lead">Alkoholgeruch erklärt keine Bewusstseinsstörung. Entscheidend sind cABCDE, die frühe Suche nach Hypoglykämie, Hypothermie, Trauma und Mischintoxikation sowie ein konsequentes Atemwegsmanagement bei fehlenden Schutzreflexen oder unzureichender Ventilation.</p></div>

    {section("01", "Begriff und Einordnung", "Definition", <><p>Eine akute Alkoholintoxikation ist eine Vergiftung durch Ethanol mit dosis-, zeit- und toleranzabhängiger Beeinträchtigung vor allem des zentralen Nervensystems. Das klinische Spektrum reicht von Enthemmung und Koordinationsstörung bis zu Koma, Schutzreflexverlust, Atemdepression und Kreislaufstillstand.</p><aside className="knowledge-note"><b>Prüfungsgrundsatz</b><p>Eine vermutete Blutalkoholkonzentration beschreibt keine sichere klinische Schwere. Befund, Dynamik, Begleiterkrankungen und mögliche Verletzungen bestimmen die Versorgung.</p></aside></>)}

    {section("02", "Leber, Gehirn und Synapse", "Anatomie und Physiologie", <><div className="pulmo-compare"><div><small>Zentrales Stoffwechselorgan</small><h3>Leber</h3><p>Ethanol gelangt nach der Resorption über die Pfortader zur Leber. Hepatozyten bauen ihn überwiegend enzymatisch ab.</p></div><div><small>Zentrales Wirkorgan</small><h3>Gehirn</h3><p>Ethanol überwindet die Blut-Hirn-Schranke und verändert hemmende und erregende Signalübertragung in mehreren neuronalen Netzwerken.</p></div></div><Figure src="/lessons/akutes-abdomen/leber.jpg" alt="Anatomische Darstellung der Leber mit Gefäßen und Gallenwegen" caption="Leber · zentrales Organ des Ethanolabbaus" wide /><Figure src="/lessons/alkoholintoxikation/leberlaeppchen.jpg" alt="Aufbau eines Leberläppchens mit Zentralvene und Glisson-Trias" caption="Leberläppchen · Blut aus Pfortader und Leberarterie passiert die Sinusoide in Richtung Zentralvene" wide /><Figure src="/lessons/krampfanfall/gehirn-sagittal.jpg" alt="Sagittaler Schnitt des Gehirns mit Großhirn, Kleinhirn, Zwischenhirn und Hirnstamm" caption="Gehirn · die klinische Wirkung betrifft mehrere funktionelle Ebenen" wide /><div className="pulmo-anatomy-grid"><div><small>Großhirn</small><b>Urteil, Sprache, Bewusstsein</b><p>Enthemmung, verlangsamtes Denken, Dysarthrie und zunehmende Bewusstseinsstörung.</p></div><div><small>Kleinhirn</small><b>Koordination</b><p>Gangunsicherheit, Dysmetrie und Ataxie.</p></div><div><small>Zwischenhirn</small><b>Vegetative Regulation</b><p>Temperatur-, Flüssigkeits- und hormonelle Regulation können beeinträchtigt werden.</p></div><div><small>Hirnstamm</small><b>Atmung und Schutzreflexe</b><p>Bei schwerer Intoxikation drohen Hypoventilation, Schutzreflexverlust und Aspiration.</p></div></div><Figure src="/lessons/krampfanfall/neuron-axon-synapse.jpg" alt="Beschriftetes Neuron mit Zellkörper, Axon und Synapse" caption="Neuron und Synapse · Ethanol verschiebt die Signalübertragung zugunsten zentraler Hemmung" wide /></>)}

    {section("03", "Vom Ethanol zur Organwirkung", "Pathophysiologie und Ursachen", <><div className="pulmo-path"><span>Resorption</span><i>→</i><span>Pfortader</span><i>→</i><span>Ethanol</span><i>ADH</i><span>Acetaldehyd</span><i>ALDH</i><span>Acetat</span></div><p>Ethanol wird über Magen und besonders Dünndarm aufgenommen. In der Leber oxidiert die Alkoholdehydrogenase Ethanol zu Acetaldehyd; die Aldehyddehydrogenase bildet daraus Acetat. Der Abbau folgt näherungsweise einer Kinetik nullter Ordnung: Pro Zeiteinheit wird annähernd eine konstante Menge eliminiert. Kaffee, kalte Dusche oder eine Infusion beschleunigen diesen enzymatisch begrenzten Prozess nicht relevant.</p><div className="pulmo-risk-grid"><div><b>GABA-Wirkung verstärkt</b><p>Hemmende Signalübertragung nimmt zu: Reaktion, Koordination und Vigilanz sinken.</p></div><div><b>Glutamat-Wirkung gehemmt</b><p>Erregende, besonders NMDA-vermittelte Signalübertragung wird reduziert.</p></div><div><b>Glukoneogenese gehemmt</b><p>Vor allem bei Nüchternheit, Mangelernährung oder im Kindesalter kann eine Hypoglykämie entstehen.</p></div><div><b>ADH-Freisetzung gehemmt</b><p>Vermehrte Diurese, Erbrechen und fehlende Flüssigkeitszufuhr begünstigen Volumenmangel.</p></div><div><b>Periphere Vasodilatation</b><p>Die Haut kann warm wirken, während die Körperkerntemperatur durch Wärmeverlust sinkt.</p></div><div><b>Ursachen der Überdosierung</b><p>Hohe Trinkmenge, rasche Aufnahme, geringe Toleranz, Nüchternheit oder zusätzlicher Konsum sedierender Substanzen.</p></div></div></>)}

    {section("04", "Arbeitsdiagnose stützen", "Symptome und Befunde", <><div className="pulmo-compare"><div><small>Exzitatorisch</small><h3>Enthemmung</h3><p>Euphorie, Distanzlosigkeit, verminderte Kritikfähigkeit, verlängerte Reaktionszeit und erste Koordinationsstörungen.</p></div><div><small>Hypnotisch</small><h3>Deutliche Dämpfung</h3><p>Dysarthrie, Ataxie, Erbrechen, Aggressivität oder Somnolenz.</p></div><div><small>Narkotisch</small><h3>Vitale Gefährdung</h3><p>Stupor bis Koma, Hypothermie, Hypotonie und zunehmender Schutzreflexverlust.</p></div><div><small>Asphyktisch</small><h3>Atem- und Kreislaufversagen</h3><p>Schwere Hypoventilation, Apnoe, Kreislaufdepression und Reanimationsgefahr.</p></div></div><div className="pulmo-symptoms"><span>Alkoholgeruch</span><span>Dysarthrie</span><span>Ataxie</span><span>Nystagmus</span><span>Enthemmung / Aggressivität</span><span>Übelkeit / Erbrechen</span><span>Somnolenz bis Koma</span><span>Hypothermie</span><span>Hypoventilation</span></div><aside className="diagnostic-boundary"><span>!</span><div><b>Promillebereiche sind nur Orientierung</b><p>Toleranz, Trinkgeschwindigkeit, Magenfüllung, Alter, Körperzusammensetzung und Mischkonsum verändern das Bild erheblich. Behandelt wird der aktuelle ABCDE-Befund.</p></div></aside></>)}

    {section("05", "Was unmittelbar gefährlich wird", "Komplikationen und Gefahren", <div className="pulmo-risk-grid"><div><b>Aspiration</b><p>Erbrechen bei verminderten Schutzreflexen kann zu Atemwegsverlegung und Aspirationspneumonitis führen.</p></div><div><b>Hypoventilation</b><p>Zentrale Dämpfung kann über Hyperkapnie und Hypoxie in Apnoe und Kreislaufstillstand übergehen.</p></div><div><b>Hypoglykämie</b><p>Eine behandelbare Ursache der Bewusstseinsstörung darf besonders bei Nüchternheit nicht übersehen werden.</p></div><div><b>Hypothermie</b><p>Vasodilatation, Immobilität und Umgebungsexposition verstärken den Wärmeverlust.</p></div><div><b>Trauma</b><p>Sturz, Gewalt oder Verkehrsunfall können hinter dem vermeintlichen Rausch verborgen bleiben.</p></div><div><b>Mischintoxikation</b><p>Opioide, Benzodiazepine und andere Sedativa können die Atemdepression erheblich verstärken.</p></div></div>)}

    {section("06", "Vorbereitet zum Patienten", "Einsatzmaterialien", <div className="material-chips">{["PSA", "Absaugung", "O₂ und Beatmungsbeutel", "Guedel- / Wendl-Tubus", "Supraglottischer Atemweg", "Kapnografie / Monitoring", "BZ-Messung", "Temperaturmessung", "i.v.- / i.o.-Material", "Wärmeerhalt", "Reanimationsbereitschaft"].map(item => <span key={item}>{item}</span>)}</div>)}

    {section("07", "cABCDE ohne diagnostischen Tunnelblick", "Erstmaßnahmen und SAMPLERS", <><div className="pulmo-care-grid"><div><span>01</span><b>Atemweg</b><small>Öffnen, Sekret oder Erbrochenes entfernen, Absaugung bereithalten und Schutzreflexe beurteilen.</small></div><div><span>02</span><b>Atmung</b><small>AF, Atemtiefe und Thoraxexkursion beurteilen; bei Insuffizienz unverzüglich assistiert beatmen.</small></div><div><span>03</span><b>Diagnostik</b><small>Monitoring, BZ, Temperatur, Pupillen, fokale Neurologie und schnelle Traumauntersuchung.</small></div><div><span>04</span><b>Schützen</b><small>Bei ausreichender Eigenatmung geeignete Seitenlagerung erwägen, Wärmeerhalt und engmaschige Reevaluation.</small></div></div><h3>SAMPLERS · fokussiert</h3><div className="samplers-grid">{[["S · Symptome", "Beginn, Verlauf, Erbrechen, Trauma, Krampf"], ["A · Allergien", "Bekannte Unverträglichkeiten"], ["M · Medikamente", "Sedativa, Opioide, Antidiabetika"], ["P · Vorgeschichte", "Diabetes, Epilepsie, Lebererkrankung"], ["L · Letzte Aufnahme", "Getränk, Menge, Zeitraum, Nahrung"], ["E · Ereignis", "Sturz, Gewalt, Suizidabsicht, Auffindeort"], ["R · Risiken", "Mischkonsum, Auskühlung, lange Liegezeit"], ["S · Schwangerschaft", "Schwangerschaft möglich?"]].map(([label, text]) => <p key={label}><b>{label}</b>{text}</p>)}</div></>)}

    {section("08", "Nicht alles ist der Alkohol", "Differenzialdiagnosen und Entscheidungen", <><div className="differential-grid">{["Hypoglykämie", "Schädel-Hirn-Trauma", "Intrakranielle Blutung", "Apoplex", "Postiktaler Zustand", "Opioid- / Benzodiazepinintoxikation", "CO-Exposition", "Sepsis", "Hypothermie", "Metabolische Entgleisung"].map(item => <span key={item}>{item}</span>)}</div><aside className="red-flags"><span>!</span><div><small>Red Flags</small><h3>Anisokorie · fokale Neurologie · unplausibler Verlauf</h3><p>Auch bei deutlichem Alkoholgeruch sprechen Traumazeichen, fokale Ausfälle, Krampfanfall, ausgeprägte Hypoglykämie oder eine unerwartete Vigilanzdynamik für eine zusätzliche oder andere Ursache.</p></div></aside><p>Eine Transportverweigerung wird nicht allein mit „alkoholisiert“ beantwortet. Verständnis, Einsicht, Abwägungsfähigkeit und freie Willensbildung sind konkret zu prüfen und zu dokumentieren. Bei erheblichem Zweifel oder Selbst- beziehungsweise Fremdgefährdung werden Notarzt und gegebenenfalls Polizei früh eingebunden.</p></>)}

    {section("09", "Befundorientiert weiterbehandeln", "Weitere Maßnahmen", <><div className="pulmo-vfa-flow"><div><span>1</span><b>Ventilation sichern</b><small>Maskenbeatmung optimieren, Absaugung und Atemwegshilfen vorbereiten.</small></div><div><span>2</span><b>Ursachen behandeln</b><small>Hypoglykämie, Hypothermie, Volumenmangel oder Trauma nach Befund versorgen.</small></div><div><span>3</span><b>Verlauf kontrollieren</b><small>Bewusstsein, Atmung, EtCO₂, SpO₂, Kreislauf und Temperatur wiederholt bewerten.</small></div><div><span>4</span><b>Strukturiert übergeben</b><small>Substanz, Menge, Zeitraum, Mischkonsum, Trauma, Befunde, Maßnahmen und Dynamik.</small></div></div><p>Eine kristalloide Infusion kann bei klinischem Volumenmangel oder Kreislaufproblem angezeigt sein, beschleunigt aber nicht den Ethanolabbau. Aktivkohle ist bei reiner Ethanolintoxikation ohne Nutzen und bei fehlenden Schutzreflexen zusätzlich gefährlich.</p></>)}

    {section("10", "Thüringen 2026/2027", "Eskalierendes Atemwegsmanagement", <><Vfa src="/lessons/alkoholintoxikation/vfa-04-atemwegsmanagement.png" alt="Thüringer VFA 04 zum eskalierenden Atemwegsmanagement" caption="VFA 04 · Eskalierendes Atemwegsmanagement · Version 2026/27" wide /><div className="pulmo-vfa-flow"><div><span>1</span><b>Beutel-Masken-Beatmung</b><small>Positionierung, Esmarch-Handgriff, Doppel-C-Griff, Atemwegshilfe und Absaugung optimieren.</small></div><div><span>2</span><b>Supraglottischer Atemweg</b><small>Bei erforderlicher Atemwegssicherung als nächste Eskalationsstufe einsetzen und Erfolg prüfen.</small></div><div><span>3</span><b>Endotracheale Intubation</b><small>Bei fortbestehender Indikation, entsprechender Kompetenz und unter begrenzten Versuchen.</small></div><div><span>4</span><b>Erfolgskontrolle</b><small>Thoraxexkursion, Auskultation, Kapnografie, Oxygenierung und Kreislauf nach jeder Stufe reevaluieren.</small></div></div><aside className="knowledge-note"><b>Prüfungsfalle</b><p>Die Seitenlage ist keine Therapie einer unzureichenden Ventilation. Bei Bradypnoe, flacher Atmung oder Apnoe hat eine wirksame Beatmung Vorrang.</p></aside></>)}

    {children}
    <p className="lesson-source">Grundlagen: bereitgestellte Unterlagen „37. Alkoholintoxikation“, Thüringer Verfahrensanweisungen 2026/27 und ergänzende rettungsdienstliche Einordnung des RD-Factsheets Alkohol-Intoxikation. Es wurden keine externen Medikamentendosierungen übernommen.</p>
  </article>;
}
