import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct?: boolean];
const q = (number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion => ({ id: `amputationsverletzung-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: options.map(([text, correct]) => ({ text, correct })), source, difficulty });

export const amputationsverletzungFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "amputationsverletzung-card-01", area: "Definition", question: "Wie unterscheiden sich Total- und Subtotalamputation?", answer: "Bei der Totalamputation besteht keine Gewebebrücke. Bei der Subtotalamputation verbindet mindestens eine Struktur beide Teile; diese Verbindung wird erhalten, knick- und zugfrei stabilisiert und niemals präklinisch vollständig durchtrennt." },
  { id: "amputationsverletzung-card-02", area: "Priorität", question: "Was bedeutet life before limb bei einer Amputationsverletzung?", answer: "Lebensrettende cABCDE-Maßnahmen, Blutungskontrolle, Schocktherapie und Transport haben Vorrang vor der Extremität oder einer möglichen Replantation." },
  { id: "amputationsverletzung-card-03", area: "Mechanismus", question: "Warum ist eine Quetsch- oder Avulsionsamputation ungünstiger als eine glatte Schnittamputation?", answer: "Quetschung und Ausriss erzeugen eine größere Zone aus Gefäß-, Nerven- und Weichteilschaden, Mikrozirkulationsstörung und Kontamination. Die sichtbare Trennfläche unterschätzt den Gewebeschaden." },
  { id: "amputationsverletzung-card-04", area: "Schock", question: "Erkläre die hämodynamische Kette nach massivem Blutverlust.", answer: "Blutverlust senkt venösen Rückstrom und Vorlast, dadurch Schlagvolumen und Herzzeitvolumen. Die Sauerstofflieferung fällt, anaerober Stoffwechsel und Azidose entstehen, Organe dekompensieren." },
  { id: "amputationsverletzung-card-05", area: "Letale Trias", question: "Welche Faktoren bilden die letale Trias und warum verstärken sie sich?", answer: "Hypothermie hemmt Enzyme und Thrombozyten, Minderperfusion erzeugt Azidose, beide verschlechtern die Gerinnung. Die Koagulopathie verstärkt die Blutung und damit Auskühlung und Minderperfusion." },
  { id: "amputationsverletzung-card-06", area: "Tourniquet", question: "Wann und wie wird ein Tourniquet nach VFA 31 angelegt?", answer: "Bei lebensbedrohlicher Extremitätenblutung, die anders nicht kontrolliert ist: möglichst 5–10 cm proximal der Wunde, nicht über Kleidung und nicht am Fibulaköpfchen, bis zur vollständigen Blutstillung. Anlagezeit dokumentieren und Analgesie durchführen." },
  { id: "amputationsverletzung-card-07", area: "Tourniquet", question: "Was ist bei unzureichender Tourniquetwirkung zu tun?", answer: "Manuelle Kompression beziehungsweise Kompressionsverband fortführen und ein zweites Tourniquet unmittelbar proximal des ersten anlegen. Eine unvollständige Anlage kann venöse Stauung und weitere Blutung verursachen." },
  { id: "amputationsverletzung-card-08", area: "Amputat", question: "Beschreibe die Vier-Schritt-Verpackung eines Amputats.", answer: "Nicht reinigen; trocken-steril einschlagen; in einen wasserdicht verschlossenen, gekennzeichneten Innenbeutel legen; diesen in einen äußeren Beutel mit Wasser und Eis/Kühlpacks geben. Kein direkter Wasser-, Eis- oder Gefrierkontakt." },
  { id: "amputationsverletzung-card-09", area: "Subtotal", question: "Wie wird eine subtotale Amputation versorgt?", answer: "Gewebebrücke belassen, trocken-steril abdecken, anatomienah ohne Zug, Knick oder Torsion schienen und pDMS vor sowie nach der Maßnahme dokumentieren, soweit ohne Verzögerung möglich." },
  { id: "amputationsverletzung-card-10", area: "Transport", question: "Wann ist ein RTH sinnvoll?", answer: "Wenn Verfügbarkeit, Flugzeit und geeignete replantationsfähige Zielklinik einen relevanten Zeitvorteil ergeben. Früh disponieren, aber nicht auf den RTH warten, wenn der Bodentransport schneller ist." },
  { id: "amputationsverletzung-card-11", area: "Zielklinik", question: "Welche Befunde sind nach B3C relevante Schockraumkriterien?", answer: "Unter anderem Amputation proximal von Händen oder Füßen sowie die Anlage eines Tourniquets. Zusätzlich entscheidet das Gesamtverletzungsmuster." },
  { id: "amputationsverletzung-card-12", area: "Tranexamsäure", question: "Welche TXA-Regel nennt der Thüringer Traumaalgorithmus?", answer: "Bei erwachsenen Traumapatienten mit lebensbedrohlicher Blutung und/oder hypovolämischem Schock 1 g als Kurzinfusion über 10 Minuten. TXA ersetzt keine mechanische oder operative Blutungskontrolle." },
  { id: "amputationsverletzung-card-13", area: "Esketamin", question: "Wie lautet der VFA-36-Pfad für Erwachsene?", answer: "1,0 mg Midazolam i.v., danach Esketamin 0,2 mg/kgKG langsam i.v.; nach fünf Minuten neu bewerten. Bei unzureichender Wirkung 0,1 mg/kgKG als Wiederholungsdosis nach VFA." },
  { id: "amputationsverletzung-card-14", area: "Morphin", question: "Welche Kernregeln gelten für Morphin nach VFA 38?", answer: "Ab 40 kg gewichtsbezogene Initialdosis langsam i.v., Wirkung nach fünf Minuten kontrollieren, Wiederholung mit halber Initialdosis, maximal 10 mg; Atmung, Kreislauf und Vigilanz überwachen." },
  { id: "amputationsverletzung-card-15", area: "Prüfungsfalle", question: "Warum darf präklinisch keine starre Replantations-Zeitgrenze genannt werden?", answer: "Toleranz und Entscheidung hängen von Gewebeart, Amputationshöhe, Mechanismus, Kontamination, Ischämie, Kühlung, Begleitverletzungen und Allgemeinzustand ab. Deshalb sofort fachlich abstimmen und ohne Verzögerung transportieren." },
];

export const amputationsverletzungQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen grenzen Total- und Subtotalamputation korrekt ab?", [["Bei der Totalamputation besteht keine Gewebebrücke.", true], ["Bei der Subtotalamputation kann bereits eine erhaltene Haut-, Sehnen-, Nerven- oder Gefäßverbindung entscheidend sein.", true], ["Eine subtotale Amputation wird zur besseren Verpackung vollständig getrennt."], ["Eine erhaltene Gewebebrücke wird zug- und knickfrei stabilisiert.", true], ["Der Begriff Amputation gilt ausschließlich für ganze Extremitäten."]], "Definition und Erstversorgung"),
  q(2, "Welche Faktoren verschlechtern typischerweise die Chance auf funktionellen Erhalt oder Replantation?", [["Ausgedehnte Quetschzone", true], ["Avulsion mit langstreckiger Gefäß- und Nervenläsion", true], ["Starke Kontamination", true], ["Korrekte indirekte Kühlung"], ["Eine glatte, scharf begrenzte Schnittverletzung"]], "Verletzungsmechanismus und Gewebeschaden"),
  q(3, "Welche Aussagen erklären die Schockentwicklung nach massiver Amputationsblutung?", [["Der verminderte venöse Rückstrom senkt die Vorlast.", true], ["Das Schlagvolumen und damit das Herzzeitvolumen können abfallen.", true], ["Die Sauerstofflieferung ans Gewebe nimmt ab.", true], ["Eine frühe normale Blutdruckmessung schließt den kompensierten Schock aus."], ["Tachykardie kann zunächst kompensatorisch auftreten.", true]], "Pathophysiologie des hämorrhagischen Schocks"),
  q(4, "Welche Kombination beschreibt die letale Trias?", [["Hypothermie", true], ["Azidose", true], ["Koagulopathie", true], ["Hyperglykämie"], ["Respiratorische Alkalose"]], "Letale Trias"),
  q(5, "Welche Maßnahmen unterbrechen den Teufelskreis der letalen Trias präklinisch sinnvoll?", [["Konsequente mechanische Blutungskontrolle", true], ["Früher Wärmeerhalt", true], ["Zügige definitive Versorgung", true], ["Ungezielte große Mengen kalter Infusionslösung"], ["Vollständige Entkleidung bis zum Kliniktransport"]], "Traumaalgorithmus L2"),
  q(6, "Eine stark blutende Unterschenkelamputation ist durch manuellen Druck und Kompressionsverband nicht kontrolliert. Welche Schritte passen zur VFA 31?", [["Tourniquet möglichst 5–10 cm proximal der Wunde anlegen.", true], ["Wenn möglich direkt auf der Haut anlegen.", true], ["Bis zur vollständigen Blutstillung festziehen.", true], ["Am Fibulaköpfchen positionieren, weil der Knochen Widerlager bietet."], ["Anlagezeit dokumentieren.", true]], "VFA 31 · Tourniquet"),
  q(7, "Welche Fehler können die Blutung trotz angelegtem Tourniquet verschlechtern?", [["Zu geringe Spannung mit fortbestehendem arteriellem Zufluss und venöser Stauung", true], ["Anlage über Kleidung mit möglichem Verrutschen", true], ["Position direkt über einer ungeeigneten knöchernen Struktur", true], ["Dokumentation der Anlagezeit"], ["Zweites Tourniquet unmittelbar proximal bei unzureichender Wirkung"]], "VFA 31 · Tourniquet"),
  q(8, "Das erste Tourniquet stoppt die lebensbedrohliche Blutung nicht vollständig. Welche Maßnahmen sind richtig?", [["Manuelle Kompression beziehungsweise Kompressionsverband fortführen.", true], ["Ein zweites Tourniquet unmittelbar proximal des ersten anlegen.", true], ["Beide Tourniquets auf vollständige Hämostase prüfen.", true], ["Das erste Tourniquet lösen, bevor das zweite wirksam ist."], ["Analgesie und Zeitdokumentation berücksichtigen.", true]], "VFA 31 · Tourniquet"),
  q(9, "Welche Reihenfolge beschreibt die korrekte Amputatverpackung?", [["Nicht reinigen oder desinfizieren.", true], ["Trocken-steril einschlagen.", true], ["In einen wasserdicht verschlossenen Innenbeutel legen.", true], ["Innenbeutel indirekt in einem äußeren Kühlbeutel lagern.", true], ["Das Amputat direkt in Eiswasser geben."]], "Amputatversorgung · DRK"),
  q(10, "Welche Aussagen zur Kühlung eines Amputats sind korrekt?", [["Direkter Kontakt mit Eis ist zu vermeiden.", true], ["Das Gewebe darf nicht gefrieren.", true], ["Der wasserdichte Innenbeutel verhindert direkten Wasserkontakt.", true], ["Desinfektionslösung eignet sich als Kühlmedium."], ["Kühlung ersetzt den schnellen Transport."]], "Amputatversorgung · DRK"),
  q(11, "Bei einer subtotalen Handamputation bestehen noch Haut- und Sehnenbrücken. Welche Maßnahmen sind richtig?", [["Die Verbindungen bleiben erhalten.", true], ["Die Hand wird ohne Zug und Torsion anatomienah stabilisiert.", true], ["Die Wunde wird trocken-steril bedeckt.", true], ["pDMS wird vor und nach der Schienung dokumentiert, sofern ohne Verzögerung möglich.", true], ["Die Restverbindungen werden zur besseren Blutungskontrolle getrennt."]], "Subtotale Amputation"),
  q(12, "Welche Aussagen zur pDMS-Prüfung sind bei Amputationsverletzungen zutreffend?", [["Sie ist besonders bei subtotaler Amputation und Begleitverletzung relevant.", true], ["Sie wird im Verlauf und nach Verband oder Schienung erneut beurteilt.", true], ["Sie darf die Kontrolle einer kritischen Blutung nicht verzögern.", true], ["Ein tastbarer Puls schließt eine Nervenverletzung aus."], ["Fehlende Motorik beweist immer eine vollständige Nervendurchtrennung."]], "Neurovaskuläre Beurteilung"),
  q(13, "Welche Aussagen beschreiben die RTH-Entscheidung fachlich korrekt?", [["Der RTH sollte früh geprüft und disponiert werden, wenn ein Zeitvorteil zu erwarten ist.", true], ["Zielklinik und Replantationsmöglichkeit müssen in die Entscheidung einfließen.", true], ["Auf den RTH zu warten ist falsch, wenn der Bodentransport schneller wäre.", true], ["Jede Fingeramputation erfordert zwingend einen RTH."], ["Die Amputatversorgung darf den Abtransport beliebig verzögern."]], "Transport- und Zielklinikentscheidung"),
  q(14, "Welche Konstellationen sprechen nach den hinterlegten Kriterien für eine Schockraumanmeldung?", [["Amputation proximal von Händen oder Füßen", true], ["Anlage eines Tourniquets", true], ["Zusätzliche hämodynamische Instabilität", true], ["Isolierte oberflächliche Fingerkuppenverletzung ohne Blutung"], ["Allein die Hoffnung auf Replantation ohne Beurteilung des Gesamttraumas"]], "B3C · Schockraumkriterien"),
  q(15, "Welche Aussagen zur präklinischen Replantationsprognose sind belastbar?", [["Der Verletzungsmechanismus beeinflusst die Prognose.", true], ["Ischämie und Qualität der Kühlung sind relevant.", true], ["Kontamination und Begleitverletzungen fließen ein.", true], ["Eine einzige starre Stundenangabe entscheidet präklinisch sicher über die Replantierbarkeit."], ["Die definitive Entscheidung trifft die geeignete Fachklinik.", true]], "S3-Leitlinie Polytrauma"),
  q(16, "Ein erwachsener Patient hat eine lebensbedrohliche traumatische Blutung mit hypovolämischem Schock. Welche Aussagen zu Tranexamsäure passen zum Thüringer Traumaalgorithmus?", [["1 g wird als Kurzinfusion über 10 Minuten gegeben.", true], ["Die Indikation setzt eine lebensbedrohliche Blutung und/oder hypovolämischen Schock voraus.", true], ["Tranexamsäure ersetzt das Tourniquet."], ["Mechanische Blutungskontrolle bleibt erforderlich.", true], ["Die Regel wird unverändert auf jedes Kind übertragen."]], "L2 / B2A · Tranexamsäure"),
  q(17, "Welche Ziele passen zur Kreislaufstrategie bei nicht kontrollierter traumatischer Blutung nach L2?", [["Ein systolischer Zielwert um 80 mmHg kann ohne führendes Schädel-Hirn-Trauma angestrebt werden.", true], ["Bei führendem oder isoliertem Schädel-Hirn-Trauma soll der systolische Druck mindestens 90 mmHg betragen.", true], ["Normotonie um jeden Preis durch unbegrenzte Volumengabe"], ["Wärmeerhalt und rasche definitive Blutungskontrolle bleiben parallel wichtig.", true], ["Ein einmal normaler Blutdruck hebt die Transportpriorität auf."]], "L2 · Traumaalgorithmus"),
  q(18, "Welche Aussagen entsprechen dem Esketaminpfad für erwachsene Traumapatienten?", [["Vor Esketamin nennt die VFA 1,0 mg Midazolam i.v.", true], ["Die Initialdosis beträgt 0,2 mg/kgKG langsam i.v.", true], ["Nach fünf Minuten wird die Wirkung neu bewertet.", true], ["Bei unzureichender Wirkung nennt die VFA 0,1 mg/kgKG als Wiederholung.", true], ["Monitoring und Atemwegsbereitschaft sind entbehrlich, weil die Spontanatmung immer erhalten bleibt."]], "VFA 36 · Esketamin"),
  q(19, "Welche Aussagen passen zur Morphingabe nach VFA 38?", [["Der Pfad gilt in der hinterlegten Gewichtstabelle ab 40 kg.", true], ["Die Dosis wird langsam i.v. gegeben.", true], ["Nach fünf Minuten wird die Wirkung kontrolliert.", true], ["Wiederholungsdosen entsprechen der halben Initialdosis.", true], ["Die Maximaldosis beträgt 20 mg."]], "VFA 38 · Morphin"),
  q(20, "Welche Befunde können trotz scheinbar geringer äußerer Blutung eine schwere Verletzung anzeigen?", [["Tachykardie und verlängerte Rekapillarisierung", true], ["Zunehmende Schwellung proximal des Stumpfes", true], ["Kalte, blasse Haut und Unruhe", true], ["Erhaltene spontane Sprache schließt einen Schock aus."], ["Vasokonstriktion kann den Wundbefund vorübergehend abschwächen.", true]], "Schock und Gefäßverletzung"),
  q(21, "Welche Aussagen zu Stumpf und Wunde sind korrekt?", [["Der Stumpf wird trocken-steril bedeckt.", true], ["Unnötige Manipulation und Reinigung werden vermieden.", true], ["Grobe Kontamination wird präklinisch mit Bürste entfernt."], ["Blutungskontrolle hat Vorrang vor kosmetischer Versorgung.", true], ["Alle auffindbaren Amputate werden eindeutig dem Patienten zugeordnet.", true]], "Stumpf- und Amputatversorgung"),
  q(22, "Welche Differenzialdiagnosen oder Begleitverletzungen müssen bei einer vermeintlichen Amputation bedacht werden?", [["Degloving-Verletzung", true], ["Offene Trümmerfraktur", true], ["Isolierte Gefäß- oder Nervenverletzung", true], ["Kompartmentsyndrom nach Quetschung", true], ["Eine erhaltene Hautbrücke beweist eine harmlose Verletzung."]], "Differenzialdiagnosen"),
  q(23, "Welche Maßnahmen dürfen den Abtransport eines kritisch verletzten Patienten nicht unnötig verzögern?", [["Ausführliche Wundreinigung", true], ["Rekonstruktionsversuch an der Einsatzstelle", true], ["Warten auf ein Luftrettungsmittel ohne Zeitvorteil", true], ["Nicht dringliche vollständige Anamnese vor Blutungskontrolle", true], ["Frühe Voranmeldung der geeigneten Zielklinik"]], "Zeitkritische Versorgung"),
  q(24, "Welche Gesamtaussagen entsprechen einem prüfungssicheren Vorgehen?", [["Kritische Blutung wird im cABCDE vor dem Atemweg adressiert.", true], ["Ein wirksames Tourniquet wird präklinisch nicht routinemäßig gelöst.", true], ["Das Amputat wird indirekt gekühlt und gemeinsam mit dem Patienten übergeben.", true], ["Analgesie und Wärmeerhalt laufen parallel zum schnellen Transport.", true], ["Extremitätenerhalt hat bei instabilem Patienten Vorrang vor der Kreislaufstabilisierung."]], "Gesamtalgorithmus · Thüringen 2026/2027"),
];
