import type { ComponentType, ReactNode } from "react";
import AnaphylaxiePreparation from "./anaphylaxie-preparation";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function AnaphylaxieLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>Anaphylaxie</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;

  return <article className="lesson-article rippenfraktur-lesson anaphylaxie-lesson">
    <div className="lesson-intro"><p className="lead">Bei der Anaphylaxie treffen fehlgeleitete Immunreaktion, akutes Kapillarleck, Vasodilatation und Atemwegsbedrohung aufeinander. Für die Prüfung entscheidend: Die Mechanismen erklären, den Schweregrad erkennen und Adrenalin ohne Verzögerung dem richtigen VFA-Pfad zuordnen.</p></div>

    {section("01", "Definition", <><p>Eine <b>Anaphylaxie</b> ist eine akut einsetzende, systemische und potenziell lebensbedrohliche Überempfindlichkeitsreaktion. Sie kann Haut und Schleimhäute, Atemwege, Herz-Kreislauf-System und Gastrointestinaltrakt gleichzeitig oder nacheinander betreffen.</p><p>Der <b>anaphylaktische Schock</b> bezeichnet die schwere Kreislaufbeteiligung: Mediatoren führen zu ausgeprägter Vasodilatation, erhöhter Gefäßpermeabilität, intravasalem Volumenverlust und vermindertem Herzzeitvolumen. Das Sauerstoffangebot reicht für den Gewebebedarf nicht mehr aus.</p><aside className="red-flags"><span>!</span><div><small>Prüfungsfalle</small><h3>Keine Hautzeichen nötig</h3><p>Eine schwere Anaphylaxie kann ohne Urtikaria oder Flush auftreten. Akute Atemwegs- oder Kreislaufreaktionen nach möglicher Allergenexposition bleiben hochverdächtig.</p></div></aside></>)}

    {section("02", "Anatomie und Physiologie", <><h3>Immunabwehr · die beteiligten Zellen</h3><div className="ana-system-grid"><div><small>Erkennen</small><b>Antigenpräsentierende Zelle</b><p>Nimmt allergenes Material auf und präsentiert Bestandteile an T-Helferzellen.</p></div><div><small>Steuern</small><b>TH2-Zelle</b><p>IL-4 und IL-13 fördern den Klassenwechsel von B-Zellen zu IgE.</p></div><div><small>Produzieren</small><b>B-Zelle / Plasmazelle</b><p>Bildet allergenspezifisches Immunglobulin E.</p></div><div><small>Reagieren</small><b>Mastzelle / Basophiler</b><p>Trägt hochaffine FcεRI-Rezeptoren; Aktivierung setzt Mediatoren frei.</p></div></div><h3>Gefäßsystem · wo der Schock entsteht</h3><div className="ana-vessel-compare"><div><span>Arterie / Arteriole</span><b>Widerstandsgefäß</b><p>Eine ausgeprägte Dilatation senkt den systemischen Gefäßwiderstand und damit den arteriellen Druck.</p><i>Tunica media mit glatter Muskulatur</i></div><div><span>Vene</span><b>Kapazitätsgefäß</b><p>Venodilatation vergrößert den Speicherraum. Der venöse Rückstrom und die Vorlast sinken.</p><i>Dünnere Muskelschicht, großes Volumenreservoir</i></div><div><span>Kapillare</span><b>Austauschbarriere</b><p>Endothel und Basalmembran trennen Plasma vom Interstitium. Mediatoren erhöhen die Durchlässigkeit.</p><i>Keine ausgeprägte Tunica media</i></div></div><h3>Histaminrezeptoren im Körper</h3><div className="ana-receptor-grid"><article><span>H₁</span><b>Gefäße · Bronchien · Nerven</b><p>Endotheliale NO-Freisetzung, Vasodilatation, erhöhte Permeabilität, Bronchokonstriktion und Juckreiz.</p></article><article><span>H₂</span><b>Magen · Herz · Gefäße</b><p>Magensäuresekretion, kardiale Stimulation und ein zusätzlicher vasodilatierender Anteil.</p></article><article><span>H₃</span><b>Zentrales Nervensystem</b><p>Vorwiegend präsynaptische Regulation der Transmitterfreisetzung; im Akutalgorithmus nicht das Therapieziel.</p></article><article><span>H₄</span><b>Immunzellen</b><p>Beteiligt an Chemotaxis und Modulation der Entzündungsantwort.</p></article></div></>)}

    {section("03", "Ursachen, Entstehung und Pathophysiologie", <><p>Häufige Auslöser sind Nahrungsmittel, Insektengifte und Medikamente. Bei Kindern dominieren häufiger Nahrungsmittel, bei Erwachsenen häufiger Insektengifte und Medikamente. Entscheidend ist nicht der genaue Auslöser, sondern das frühe Erkennen einer gefährlichen Atemwegs- oder Kreislaufreaktion.</p><h3>Von der Sensibilisierung zum Schock</h3><div className="ana-cascade"><div><span>01</span><b>Erster Kontakt</b><p>Der Körper stuft einen eigentlich harmlosen Stoff fälschlich als gefährlich ein und bildet spezifische IgE-Antikörper.</p></div><div><span>02</span><b>Sensibilisierung</b><p>Die IgE-Antikörper setzen sich auf Mastzellen. Der Patient bemerkt davon häufig noch nichts.</p></div><div><span>03</span><b>Erneuter Kontakt</b><p>Das Allergen verbindet benachbarte IgE-Antikörper auf der Mastzelle und aktiviert sie.</p></div><div><span>04</span><b>Mediatorfreisetzung</b><p>Die Mastzelle schüttet vor allem Histamin und weitere Entzündungsbotenstoffe aus.</p></div><div><span>05</span><b>Organreaktion</b><p>Gefäße werden weit und durchlässig; Bronchien verengen sich und Schleimhäute schwellen an.</p></div><div><span>06</span><b>Dekompensation</b><p>Der Blutdruck fällt, das zirkulierende Volumen nimmt ab und gleichzeitig kann die Atmung schwer beeinträchtigt sein.</p></div></div><Figure src="/lessons/anaphylaxie/immunreaktion-hd.png" alt="Scharfe Darstellung: Allergen vernetzt mastzellgebundenes IgE und löst die Freisetzung von Histamin sowie weitere Organreaktionen aus" caption="Mastzellaktivierung · vom Allergenkontakt zu Gefäß-, Atemwegs-, Haut- und Magen-Darm-Reaktionen" wide /><h3>Was passiert dabei im Körper?</h3><div className="ana-shock-equation"><span>Gefäße werden weit</span><i>＋</i><span>Flüssigkeit tritt ins Gewebe</span><i>＋</i><span>Bronchien und Schleimhäute reagieren</span><i>＝</i><b>Schock- und Erstickungsgefahr</b></div><p>Durch die Gefäßerweiterung sinkt der Gefäßwiderstand. Gleichzeitig macht Histamin die Kapillarwände durchlässiger: Plasma verlässt die Blutbahn und sammelt sich im Gewebe. Dadurch entstehen Schwellungen, während dem Kreislauf Volumen fehlt. Venöser Rückstrom, Vorlast und Herzzeitvolumen sinken; der Blutdruck kann rasch abfallen.</p><p>Parallel verengen sich die Bronchien, die Atemwegsschleimhaut schwillt an und es wird mehr Sekret gebildet. So können Bronchospasmus, Stridor und eine gefährliche Oxygenierungsstörung gleichzeitig mit dem Schock auftreten.</p><aside className="knowledge-note"><b>So lässt es sich mündlich erklären</b><p>„Beim erneuten Allergenkontakt werden Mastzellen aktiviert und setzen Histamin frei. Die Gefäße werden weit und undicht, wodurch Blutdruck und zirkulierendes Volumen abfallen. Gleichzeitig können Bronchien verkrampfen und die Atemwege anschwellen. Deshalb drohen gleichzeitig Schock und Atemwegsverschluss.“</p></aside></>)}

    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", <><div className="rib-fracture-grid">{[["Haut / Schleimhaut", "Flush, Juckreiz, Urtikaria, Angioödem, Brennen an Handflächen oder Fußsohlen."], ["Obere Atemwege", "Heiserkeit, Dysphonie, Schluckstörung, inspiratorischer Stridor, Zungen- oder Rachenschwellung."], ["Untere Atemwege", "Giemen, verlängerte Exspiration, Bronchospasmus, Dyspnoe, erhöhte Atemarbeit."], ["Kreislauf", "Tachykardie oder Bradykardie, Hypotonie, Synkope, Schock, Rhythmusstörung."], ["Gastrointestinal", "Krämpfe, Übelkeit, Erbrechen und Diarrhoe."], ["Neurologisch", "Angst, Unruhe, Schwindel, Vigilanzminderung als mögliche Hypoperfusionszeichen."]].map(([title,text]) => <div key={title}><b>{title}</b><span>{text}</span></div>)}</div><h3>Schweregrade nach Ring und Messmer</h3><div className="ana-grade-strip"><div><b>I</b><span>Haut / Schleimhaut</span></div><div><b>II</b><span>Moderate Organbeteiligung</span></div><div><b>III</b><span>Schwere Atemwegs- oder Kreislaufreaktion</span></div><div><b>IV</b><span>Atem-/Kreislaufstillstand</span></div></div><aside className="diagnostic-boundary"><span>!</span><div><b>Das schwerste Zeichen bestimmt die Priorität</b><p>Eine Person mit wenig Hautausschlag, aber Stridor oder Hypotonie ist nicht „leicht allergisch“. Atemweg und Kreislauf entscheiden über das Stadium und die Therapie.</p></div></aside></>)}

    {section("05", "Komplikationen und Gefahren", <><div className="pulmo-risk-grid"><div><b>Atemwegsverlust</b><p>Fortschreitendes Larynx- und Zungenödem kann Maskenbeatmung und Intubation erschweren oder unmöglich machen.</p></div><div><b>Respiratorisches Versagen</b><p>Bronchospasmus, Schleimhautschwellung, Hypersekretion und Erschöpfung führen zu Hypoxämie.</p></div><div><b>Distributiver Schock</b><p>Vasoplegie und Kapillarleck vermindern Vorlast, Blutdruck und Organperfusion.</p></div><div><b>Kardiale Beteiligung</b><p>Rhythmusstörung, Ischämie oder anaphylaxiebedingte Myokarddepression können den Schock verstärken.</p></div><div><b>Aspiration</b><p>Erbrechen bei eingeschränkter Vigilanz gefährdet den Atemweg zusätzlich.</p></div><div><b>Biphasischer Verlauf</b><p>Nach Besserung können erneut systemische Symptome auftreten; Monitoring und Transport bleiben erforderlich.</p></div></div><aside className="red-flags"><span>!</span><div><small>Sofort eskalieren</small><h3>Stridor · Silent Chest · Hypotonie · Synkope</h3><p>Bradykardie, Erschöpfung und Vigilanzverlust können späte Dekompensationszeichen sein. Reanimationsbereitschaft herstellen.</p></div></aside></>)}

    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", <div className="material-chips">{["PSA", "Monitoring / EKG / RR / SpO₂", "Sauerstoff", "Absaugung", "Beatmungsgerät", "Atemwegsmaterial", "i.m.-Kanüle", "Großlumiger i.v.-/i.o.-Zugang", "Adrenalin", "Histakut / Dimetinden", "Prednisolon", "Kristalloide Infusion", "Vernebler", "Reanimationsausrüstung"].map(item => <span key={item}>{item}</span>)}</div>)}

    {section("07", "Erstmaßnahmen, Diagnostik und Anamnese", <><div className="pulmo-care-grid"><div><span>cA</span><b>Exposition &amp; Atemweg</b><small>Zufuhr stoppen, Stachel möglichst entfernen, Stimme, Stridor und Schwellung beurteilen.</small></div><div><span>B</span><b>Atmung</b><small>AF, SpO₂, Auskultation, Atemarbeit; Sauerstoff und Verneblung vorbereiten.</small></div><div><span>C</span><b>Kreislauf</b><small>Puls, Rekap, Haut, RR-Trend, EKG; großlumiger Zugang und Volumen.</small></div><div><span>DE</span><b>Neurologie &amp; Verlauf</b><small>Vigilanz, BZ, Ganzkörperinspektion, Temperatur und wiederholte Stadiumseinteilung.</small></div></div><h3>SAMPLERS · kurz und prüfungsnah</h3><div className="samplers-grid">{[["S · Symptome", "Beginn, Dynamik, Haut, Atmung, Kreislauf, GI"], ["A · Allergien", "Bekannte Auslöser und frühere Schweregrade"], ["M · Medikamente", "ACE-Hemmer, Betablocker, Notfallset, bereits erfolgte Gabe"], ["P · Vorgeschichte", "Asthma, Mastozytose, Herzkrankheit, frühere Anaphylaxie"], ["L · Letzte Aufnahme", "Nahrung, Medikamente, Infusionen, Stiche"], ["E · Ereignis", "Exposition, Weg, Zeitpunkt, Belastung als Kofaktor"], ["R · Risiken", "Rasche Dynamik, Asthma, verzögerte Adrenalingabe"], ["S · Schwangerschaft", "Schwangerschaft und angepasste Lagerung"]].map(([label,text]) => <p key={label}><b>{label}</b>{text}</p>)}</div><h3>Lagerung</h3><ul className="script-list"><li><b>Führende Atemnot:</b> Oberkörper erhöht, wenn der Kreislauf dies toleriert.</li><li><b>Hypotonie/Schock:</b> flach lagern, gegebenenfalls Beine anheben; nicht plötzlich aufstehen lassen.</li><li><b>Bewusstlos mit Atmung:</b> stabile Seitenlage; bei Kreislaufstillstand Reanimation.</li><li><b>Schwangere:</b> Linksseitenentlastung unter Erhalt der notwendigen Atemwegs- und Schockversorgung.</li></ul></>)}

    {section("08", "Differenzialdiagnosen und Entscheidungsfindung", <><div className="differential-grid">{["Asthma / COPD", "Fremdkörperaspiration", "Bradykinin-Angioödem", "Vasovagale Synkope", "Kardiogener oder septischer Schock", "Panik / Hyperventilation", "Mastozytose", "Intoxikation", "Hereditäres Angioödem"].map(item => <span key={item}>{item}</span>)}</div><div className="pulmo-compare"><div><small>Histaminvermittelt</small><h3>Anaphylaxie</h3><p>Oft Juckreiz, Urtikaria, Bronchospasmus und systemische Reaktion nach Allergenexposition.</p><span>Adrenalin ist bei Stadium II/III zeitkritisch wirksam.</span></div><div><small>Bradykininvermittelt</small><h3>Angioödem</h3><p>Häufig isolierte, nicht juckende Schwellung ohne Urtikaria, etwa unter ACE-Hemmern oder hereditär.</p><span>Spricht oft schlechter auf Antihistaminikum und Steroid an; Atemweg trotzdem akut sichern.</span></div></div><h3>Prüfungsfallen</h3><ul className="script-list"><li><b>Keine Hautreaktion:</b> schließt eine schwere Anaphylaxie nicht aus.</li><li><b>Antihistaminikum zuerst:</b> darf Adrenalin bei Stadium II/III nicht verzögern.</li><li><b>i.v. statt i.m.:</b> Die VFA nennt 1:1000 unverdünnt i.m.; nicht mit Reanimationsverdünnungen verwechseln.</li><li><b>Besserung:</b> ist kein Grund, Monitoring und Transport abzubrechen.</li><li><b>Adrenalin inhalativ:</b> bei Stridor zusätzlich; es ersetzt die i.m.-Gabe im Stadium II/III nicht.</li></ul></>)}

    {section("09", "Weitere Maßnahmen und Medikamente", <><div className="pulmo-vfa-flow"><div><span>25</span><b>Erwachsene</b><small>Stadium erfassen; ab II/III Adrenalin i.m., bei Stridor zusätzlich inhalativ, Volumen und Zusatzmedikation.</small></div><div><span>26</span><b>Kinder</b><small>Altersstufen für Adrenalin, Gewichtsgruppen für Volumen, Prednisolon und Dimetinden.</small></div><div><span>B3B</span><b>Notarzt</b><small>Anaphylaxie ab Stadium II ist eine Nachforderungsindikation.</small></div><div><span>↻</span><b>Reevaluation</b><small>ABCDE, Stadium, Wirkung, Nebenwirkung und erneute Verschlechterung fortlaufend prüfen.</small></div></div><div className="ana-drug-grid"><article><span>Katecholamin · α₁ · β₁ · β₂</span><h3>Adrenalin</h3><p><b>Wirkung:</b> α₁ führt zu Vasokonstriktion, Blutdruckanstieg und Schleimhautabschwellung; β₁ erhöht Herzfrequenz, Kontraktionskraft und Erregungsleitung; β₂ bronchodilatiert und kann weitere Mediatorfreisetzung hemmen.</p><p><b>Nebenwirkungen:</b> Tachykardie, Rhythmusstörung, Blutdruckanstieg, Tremor und Unruhe.</p><p><b>Kontraindikation:</b> Bei vitaler Anaphylaxie besteht keine absolute Kontraindikation gegen die indizierte i.m.-Gabe.</p></article><article><span>H₁-Antagonist</span><h3>Histakut / Dimetinden</h3><p><b>Wirkung:</b> Dämpft histaminvermittelten Juckreiz, Urtikaria und Schleimhauteffekte.</p><p><b>Nebenwirkungen:</b> Müdigkeit, Schwindel, Mundtrockenheit, Magen-Darm- und Sehstörungen, gelegentlich Hypotonie. Anticholinerge Effekte können Tachykardie, Obstipation, Miktionsstörung und eine Glaukomproblematik begünstigen.</p><p><b>Wechselwirkung:</b> Alkohol, Opioide, Benzodiazepine und andere Sedativa können die zentrale Dämpfung verstärken.</p></article><article><span>Glukokortikoidrezeptor</span><h3>Prednisolon</h3><p><b>Wirkung:</b> Verändert Genexpression, stabilisiert Zell- und Gefäßreaktionen, erhöht die Katecholaminempfindlichkeit und wirkt antiinflammatorisch, antiödematös sowie immunsuppressiv – mit verzögertem Wirkungseintritt.</p><p><b>Nebenwirkungen:</b> Unter anderem Hyperglykämie, Dyspepsie sowie Schlaf- und Stimmungseffekte.</p><p><b>Grenze:</b> Kein Ersatz für Adrenalin, Volumen oder Atemwegsmanagement; bei kurzfristiger vitaler Indikation werden relative Gegenanzeigen anders gewichtet.</p></article></div><p>Monitoring, zügiger Transport und Voranmeldung erfolgen auch bei Besserung. Der zeitliche Verlauf, höchste Schweregrad, jede Dosis, Applikationsart und Wirkung werden exakt dokumentiert.</p></>)}

    {section("10", "Thüringer VFA 2026/2027 und Dosierungsansichten", <><div className="vfa-stack"><Vfa src="/lessons/anaphylaxie/vfa-25-erwachsene.png" alt="Thüringer VFA 25 Anaphylaxie Erwachsene" caption="VFA 25 · Anaphylaxie Erwachsene"/><Vfa src="/lessons/anaphylaxie/vfa-26-kind.png" alt="Thüringer VFA 26 Anaphylaxie Kind" caption="VFA 26 · Anaphylaxie Kind"/></div><AnaphylaxiePreparation/></>)}

    {children}
    <p className="lesson-source">Hauptgrundlage: „Anaphylaktischer Schock ZwiPrü.pdf“, „51. anaphylaktischer Schock.docx“ und „20260112_Anaphylaxie_Erwachsener.pdf“. Therapie und sämtliche Dosierungen: <a href="https://www.aelrd-thueringen.de/verfahrensanweisungen-fuer-den-thueringer-rettungsdienst-algorithmen/" target="_blank" rel="noreferrer">Thüringer VFA 25/26 und Anlage B2A, 2026/27</a>. Ergänzend fachlich abgeglichen mit der <a href="https://register.awmf.org/de/leitlinien/detail/061-025" target="_blank" rel="noreferrer">AWMF-Leitlinie Anaphylaxie</a>. Im Einsatz gelten die aktuelle VFA, lokale Vorgaben und ärztliche Anweisungen.</p>
  </article>;
}
