import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct?: boolean];

function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  return { id: `anaphylaxie-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: options.map(([text, correct]) => ({ text, correct })), source, difficulty };
}

export const anaphylaxieFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "anaphylaxie-card-01", area: "Definition", question: "Definieren Sie Anaphylaxie und anaphylaktischen Schock.", answer: "Anaphylaxie ist eine akut einsetzende, systemische und potenziell lebensbedrohliche Überempfindlichkeitsreaktion. Ein anaphylaktischer Schock liegt vor, wenn Vasodilatation, Kapillarleck und gegebenenfalls kardiale Beteiligung zu kritischer Hypotonie, vermindertem Herzzeitvolumen und Gewebehypoperfusion führen." },
  { id: "anaphylaxie-card-02", area: "Sensibilisierung", question: "Erklären Sie die Sensibilisierungsphase einer IgE-vermittelten Anaphylaxie.", answer: "Antigenpräsentierende Zellen aktivieren eine TH2-geprägte Immunantwort. IL-4 und IL-13 fördern in B-Zellen den Klassenwechsel zu allergenspezifischem IgE. Dieses bindet mit seinem Fc-Anteil an hochaffine FcεRI-Rezeptoren von Mastzellen und Basophilen; die Zellen sind damit sensibilisiert." },
  { id: "anaphylaxie-card-03", area: "Reexposition", question: "Was geschieht bei erneutem Allergenkontakt an der Mastzelle?", answer: "Das Allergen vernetzt benachbarte, an FcεRI gebundene IgE-Moleküle. Dadurch wird die Mastzelle aktiviert und setzt gespeicherte sowie neu gebildete Mediatoren frei, unter anderem Histamin, Tryptase, Leukotriene, Prostaglandine, PAF und Zytokine." },
  { id: "anaphylaxie-card-04", area: "Histaminrezeptoren", question: "Welche prüfungsrelevanten Wirkungen entstehen über H₁- und H₂-Rezeptoren?", answer: "H₁ fördert über Endothel und NO Vasodilatation und erhöhte Gefäßpermeabilität, kontrahiert Bronchialmuskulatur und vermittelt Juckreiz. H₂ steigert die Magensäuresekretion, beeinflusst das Herz positiv chrono- und inotrop und trägt ebenfalls zur Vasodilatation bei." },
  { id: "anaphylaxie-card-05", area: "Gefäßsystem", question: "Warum entsteht bei Anaphylaxie gleichzeitig ein relativer und funktionell absoluter Volumenmangel?", answer: "Die Mediatorwirkung erweitert vor allem Widerstands- und Kapazitätsgefäße: Blut versackt in der Peripherie und der venöse Rückstrom sinkt. Gleichzeitig tritt durch erhöhte Endothelpermeabilität Plasma ins Interstitium aus. Damit fehlt Volumen tatsächlich intravasal, obwohl keine äußere Blutung besteht." },
  { id: "anaphylaxie-card-06", area: "Atemwege", question: "Nennen Sie die drei zentralen Mechanismen der respiratorischen Bedrohung.", answer: "Schleimhaut- und Larynxödem gefährden den oberen Atemweg; Bronchokonstriktion verengt die unteren Atemwege; Hypersekretion und ein mögliches Permeabilitätsödem verschlechtern Ventilation und Oxygenierung zusätzlich." },
  { id: "anaphylaxie-card-07", area: "Adrenalin", question: "Begründen Sie die Wirkung von Adrenalin über α₁, β₁ und β₂ bei Anaphylaxie.", answer: "α₁ bewirkt Vasokonstriktion, steigert den systemischen Gefäßwiderstand und vermindert Schleimhautödem. β₁ erhöht Herzfrequenz und Kontraktilität. β₂ bronchodilatiert und kann die weitere Mediatorfreisetzung aus Mastzellen und Basophilen hemmen." },
  { id: "anaphylaxie-card-08", area: "Zusatzmedikation", question: "Warum dürfen Dimetinden und Prednisolon Adrenalin nicht ersetzen?", answer: "Dimetinden blockiert nur histaminvermittelte H₁-Effekte und nicht die übrigen Mediatoren. Prednisolon wirkt über intrazelluläre Glukokortikoidrezeptoren verzögert. Beide sind Zusatzmedikamente; bei Stadium II/III ist Adrenalin i.m. die zeitkritische VFA-Maßnahme." },
  { id: "anaphylaxie-card-09", area: "Schweregrade", question: "Ordnen Sie die Stadien I bis IV nach Ring und Messmer zu.", answer: "I: Haut/Schleimhaut. II: zusätzlich moderate respiratorische, kardiovaskuläre oder gastrointestinale Beteiligung. III: schwere Atemwegs- oder Kreislaufreaktion. IV: Atem- oder Herz-Kreislauf-Stillstand. Hautzeichen können bei schwerer Anaphylaxie fehlen." },
  { id: "anaphylaxie-card-10", area: "VFA Erwachsene", question: "Nennen Sie den Medikamenten- und Volumenpfad der Thüringer VFA 25 bei Stadium II/III.", answer: "Adrenalin 1 mg/ml: 0,5 mg beziehungsweise 0,5 ml i.m.; bei Stridor 5 mg beziehungsweise 5 ml pur mit O₂ vernebeln; 1.000 ml kristalloide Infusionslösung; einmalig 500 mg Prednisolonäquivalent und 0,1 mg/kgKG Dimetinden. Bei ausbleibendem oder nachlassendem Effekt Adrenalin 0,5 mg i.m. alle fünf Minuten." },
  { id: "anaphylaxie-card-11", area: "VFA Kind", question: "Welche altersabhängigen Adrenalindosen nennt die Thüringer VFA 26?", answer: "Über 12 Jahre: 0,5 mg i.m.; 6 bis 12 Jahre: 0,3 mg i.m.; unter 6 Jahren: 0,15 mg i.m. Verwendet wird Adrenalin 1 mg/ml unverdünnt; bei ausbleibendem oder nachlassendem Effekt Wiederholung der vollen Initialdosis alle fünf Minuten." },
  { id: "anaphylaxie-card-12", area: "VFA Kind", question: "Welche Prednisolon- und Dimetindendosen nennt VFA 26 nach Gewicht?", answer: "Über 30 kg: 250 mg Prednisolon plus 4 mg Dimetinden; 15–30 kg: 100 mg plus 2 mg; unter 15 kg: 50 mg plus 1 mg. Diese i.v.-Gaben erfolgen laut VFA erst ab einem Jahr. Im Stadium-I-Zweig ist 100 mg Prednisolon rektal dargestellt." },
  { id: "anaphylaxie-card-13", area: "Diagnostik", question: "Welche Konstellationen erlauben die klinische Diagnose auch ohne vollständiges Hautbild?", answer: "Akuter Beginn nach möglicher Exposition mit Beteiligung mehrerer Organsysteme, Haut-/Schleimhautzeichen plus Atemwegs- oder Kreislaufbeteiligung sowie Hypotonie nach bekanntem Allergen. Eine isolierte schwere Kreislauf- oder Atemwegsreaktion kann vorkommen; fehlende Urtikaria schließt Anaphylaxie nicht aus." },
  { id: "anaphylaxie-card-14", area: "Differenzialdiagnose", question: "Wie grenzen Sie eine histaminvermittelte Anaphylaxie von einem bradykininvermittelten Angioödem ab?", answer: "Urtikaria, Juckreiz, Bronchospasmus und rascher Bezug zu Allergenexposition sprechen eher für Histamin. Ein ACE-Hemmer- oder hereditär bedingtes Angioödem zeigt häufig isolierte, nicht juckende Schwellung ohne Urtikaria und spricht schlechter auf Adrenalin, Antihistaminikum und Steroid an; der Atemweg bleibt trotzdem akut gefährdet." },
  { id: "anaphylaxie-card-15", area: "Einsatz", question: "Welche Lagerung wählen Sie bei Atemnot, Schock und Bewusstlosigkeit?", answer: "Bei führender Atemnot Oberkörper erhöht, sofern der Kreislauf es erlaubt. Bei Hypotonie flach beziehungsweise mit angehobenen Beinen, wenn toleriert. Bewusstlose mit erhaltener Atmung stabil seitlich; bei Atem- oder Kreislaufstillstand Reanimation. Plötzliches Aufstehen vermeiden." },
  { id: "anaphylaxie-card-16", area: "Prüfungsfalle", question: "Warum ist eine Besserung nach der ersten Behandlung noch keine Entwarnung?", answer: "Symptome können erneut auftreten oder nachlassen und wieder zunehmen. Deshalb sind fortlaufende ABCDE-Reevaluation, Monitoring, Transport und ärztliche Weiterbehandlung erforderlich. Eine biphasische Reaktion ist möglich; Prednisolon garantiert deren Verhinderung nicht." },
  { id: "anaphylaxie-card-17", area: "Histakut", question: "Nennen Sie Wirkung und relevante Risiken von Histakut (Dimetinden).", answer: "Dimetinden ist ein H₁-Antihistaminikum und vermindert Juckreiz, Urtikaria sowie histaminbedingte Schleimhauteffekte. Mögliche Nebenwirkungen sind Müdigkeit, Schläfrigkeit, Schwindel, Mundtrockenheit, Magen-Darm- und Sehstörungen sowie gelegentlich Hypotonie; zentral dämpfende Mittel können die Sedierung verstärken." },
  { id: "anaphylaxie-card-18", area: "Prednisolon", question: "Erklären Sie Wirkungseintritt und Wirkprinzip von Prednisolon.", answer: "Prednisolon bindet intrazellulär an den Glukokortikoidrezeptor und verändert die Genexpression. Proinflammatorische Mediatoren, Ödembildung und Immunaktivität werden gedämpft. Der Wirkungseintritt ist verzögert; es korrigiert weder den akuten Gefäßkollaps noch den Bronchospasmus so schnell wie Adrenalin." },
];

export const anaphylaxieQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Vorgänge gehören zur Sensibilisierung vor einer IgE-vermittelten Anaphylaxie?", [["TH2-Zytokine fördern den Klassenwechsel von B-Zellen zu allergenspezifischem IgE", true], ["IgE bindet an hochaffine FcεRI-Rezeptoren von Mastzellen und Basophilen", true], ["Bei Reexposition kann die Kreuzvernetzung dieses gebundenen IgE die Degranulation auslösen", true], ["Die erste Exposition führt regelhaft bereits zum Stadium IV", false], ["T-Lymphozyten werden durch Adrenalin in Immunglobulin E umgewandelt", false]], "Sensibilisierung bereitet Mastzellen vor; die massive Sofortreaktion wird typischerweise durch erneute Allergenbindung ausgelöst."),
  q(2, "Welche Mediatoren und Folgen passen zur frühen anaphylaktischen Reaktion?", [["Histamin erhöht über H₁-Signalwege Gefäßpermeabilität und Vasodilatation", true], ["Leukotriene tragen zu Bronchokonstriktion und Schleimproduktion bei", true], ["PAF und Prostaglandine können Kreislauf- und Atemwegsreaktionen verstärken", true], ["Tryptase ist ein typischer Mastzellmediator", true], ["Insulin ist der entscheidende Auslöser des Kapillarlecks", false]], "Nicht nur Histamin, sondern mehrere Mastzell- und Entzündungsmediatoren formen das Krankheitsbild."),
  q(3, "Welche Aussagen erklären den Kreislaufschock bei Anaphylaxie?", [["Periphere Vasodilatation senkt den systemischen Gefäßwiderstand", true], ["Venöse Kapazitätserhöhung vermindert venösen Rückstrom und Vorlast", true], ["Kapillarleck verschiebt Plasma aus dem Gefäßraum ins Interstitium", true], ["Sinkende Vorlast und mögliche myokardiale Beteiligung reduzieren das Herzzeitvolumen", true], ["Der Schock entsteht ausschließlich durch eine äußere Blutung", false]], "Distributive und intravasal volumenarme Komponenten wirken gleichzeitig; das Herzzeitvolumen kann zusätzlich sinken."),
  q(4, "Welche Rezeptorwirkungen von Histamin sind korrekt zugeordnet?", [["H₁ am Endothel: NO-vermittelte Vasodilatation und erhöhte Permeabilität", true], ["H₁ an Bronchialmuskulatur: Bronchokonstriktion", true], ["H₂ an Belegzellen: gesteigerte Magensäuresekretion", true], ["H₄ auf Immunzellen: Beteiligung an Chemotaxis und Entzündungsmodulation", true], ["H₂ blockiert als körpereigener Rezeptor die gesamte Mastzelldegranulation", false]], "Die Histaminrezeptoren liegen in unterschiedlichen Geweben; klinisch dominieren bei Anaphylaxie vor allem H₁-vermittelte Gefäß-, Atemwegs- und Hautwirkungen."),
  q(5, "Welche Kombinationen sprechen für eine schwere Anaphylaxie, auch wenn keine Urtikaria sichtbar ist?", [["Plötzliche Hypotonie nach bekanntem Allergen", true], ["Stridor und progrediente Schleimhautschwellung nach Medikamentengabe", true], ["Giemen, Kreislaufinstabilität und akuter Beginn nach Insektenstich", true], ["Isolierter chronischer Husten seit mehreren Monaten", false], ["Mechanisch erklärbarer Schmerz ohne systemische Symptome", false]], "Hautzeichen sind häufig, aber für die Diagnose einer schweren Anaphylaxie nicht obligat."),
  q(6, "Welche Befunde ordnen Sie den Stadien nach Ring und Messmer korrekt zu?", [["Stadium I: generalisierte Haut- und Schleimhautreaktion", true], ["Stadium II: moderate Atemwegs-, Kreislauf- oder gastrointestinale Beteiligung", true], ["Stadium III: schwere Bronchospastik, Larynxödem oder Schock", true], ["Stadium IV: Atem- oder Herz-Kreislauf-Stillstand", true], ["Stadium I bedeutet grundsätzlich Symptomfreiheit", false]], "Der Schweregrad richtet sich nach der bedrohlichsten Organbeteiligung, nicht nach der Zahl sichtbarer Hautveränderungen."),
  q(7, "Warum ist Adrenalin bei Stadium II/III das zentrale Medikament?", [["α₁-vermittelte Vasokonstriktion erhöht den Gefäßtonus und vermindert Schleimhautödem", true], ["β₁-Stimulation unterstützt Herzfrequenz und Kontraktilität", true], ["β₂-Stimulation bronchodilatiert", true], ["β₂-Wirkung kann die weitere Mediatorfreisetzung begrenzen", true], ["Es neutralisiert das Allergen chemisch im Blut", false]], "Adrenalin greift gleichzeitig an Gefäßen, Herz, Bronchien und Mediatorfreisetzung an."),
  q(8, "Welche Angaben entsprechen bei einem Erwachsenen mit Stadium II/III der Thüringer VFA 25?", [["0,5 mg Adrenalin 1:1000 i.m.", true], ["Bei Stridor 5 mg Adrenalin pur mit O₂ vernebeln", true], ["1.000 ml kristalloide Infusionslösung", true], ["Einmalig 500 mg Prednisolonäquivalent und 0,1 mg/kgKG Dimetinden", true], ["Adrenalin wird zuerst als 0,5-mg-Bolus i.v. gegeben", false]], "Die Dosierungen stammen ausschließlich aus VFA 25, Stand 2026/27; die i.m.-Gabe ist vom i.v.-Reanimationsweg zu trennen."),
  q(9, "Ein Erwachsener wiegt 82 kg. Welche Rechnungen zur VFA-25-Zusatzmedikation stimmen?", [["Dimetinden: 8,2 mg", true], ["Bei 1 mg/ml entsprechen 8,2 mg einem Volumen von 8,2 ml", true], ["500 mg Prednisolon entsprechen bei 50 mg/ml insgesamt 10 ml rekonstituierter Lösung", true], ["0,5 mg Adrenalin entsprechen bei 1 mg/ml 0,5 ml", true], ["Dimetinden wird unabhängig vom Gewicht immer mit 4 mg dosiert", false]], "0,1 mg/kgKG Dimetinden; B2A: Dimetinden 1 mg/ml und Prednisolon nach Rekonstitution 50 mg/ml."),
  q(10, "Welche altersabhängigen i.m.-Adrenalindosen nennt VFA 26 für Kinder?", [["Unter 6 Jahren: 0,15 mg", true], ["6 bis 12 Jahre: 0,3 mg", true], ["Über 12 Jahre: 0,5 mg", true], ["Bei 1 mg/ml entsprechen die Milligrammwerte jeweils demselben Zahlenwert in Millilitern", true], ["Die Initialdosis wird immer als 0,01 mg/kg ohne Altersstufen berechnet", false]], "VFA 26 verwendet feste Altersstufen und Adrenalin 1 mg/ml unverdünnt."),
  q(11, "Welche Aussagen zum Kinderpfad der Thüringer VFA 26 sind korrekt?", [["Bei Stadium II/III werden 10 ml/kgKG kristalloide Infusionslösung genannt", true], ["Bei Stridor werden 5 mg Adrenalin pur mit O₂ vernebelt", true], ["Bei ausbleibendem oder nachlassendem Effekt wird die volle i.m.-Initialdosis alle fünf Minuten wiederholt", true], ["Für die i.v.-Gaben von Prednisolon und Dimetinden gilt laut VFA: erst ab einem Jahr", true], ["Im Stadium IV wird nur ein Antihistaminikum verabreicht", false]], "Stadium IV führt in den pädiatrischen ERC-Reanimationsalgorithmus; die übrigen Angaben stammen aus VFA 26."),
  q(12, "Ein achtjähriges Kind wiegt 20 kg. Welche VFA-26-Angaben und Volumina sind richtig?", [["Adrenalin i.m.: 0,3 mg beziehungsweise 0,3 ml", true], ["Kristalloide Infusionslösung: 200 ml", true], ["Prednisolon i.v.: 100 mg beziehungsweise 2 ml bei 50 mg/ml", true], ["Dimetinden i.v.: 2 mg beziehungsweise 2 ml bei 1 mg/ml", true], ["Prednisolon i.v.: 500 mg wie beim Erwachsenen", false]], "Alter bestimmt die i.m.-Adrenalindosis; Gewicht bestimmt Flüssigkeit sowie Prednisolon-/Dimetindenstufe."),
  q(13, "Welche Aussagen zur Zusatzmedikation sind fachlich korrekt?", [["Dimetinden blockiert H₁-Rezeptoren, aber nicht alle anaphylaktischen Mediatorwege", true], ["Prednisolon wirkt über intrazelluläre Glukokortikoidrezeptoren verzögert", true], ["Beide dürfen zeitkritisches Adrenalin bei Stadium II/III nicht verzögern", true], ["Prednisolon beseitigt einen Larynxverschluss innerhalb weniger Sekunden", false], ["Dimetinden ersetzt bei Schock die Volumentherapie", false]], "Antihistaminikum und Glukokortikoid sind Ergänzungen, keine gleichwertigen Ersatzmittel für Adrenalin und ABCDE-Maßnahmen."),
  q(14, "Welche Maßnahmen sind bei anaphylaktischer Atemwegsbedrohung sinnvoll?", [["Frühzeitig auf Stridor, Stimme, Schluckstörung und zunehmende Schwellung achten", true], ["Sauerstoffgabe und vollständiges Monitoring vorbereiten", true], ["Bei Stridor den inhalativen Adrenalinpfad der VFA zusätzlich anwenden", true], ["Atemwegsmaterial, Absaugung und Eskalation frühzeitig bereithalten", true], ["Bis zum vollständigen Verschluss mit jeder Atemwegsplanung warten", false]], "Das Larynxödem kann rasch fortschreiten; eine späte Atemwegssicherung kann technisch unmöglich werden."),
  q(15, "Welche Lagerungsentscheidungen sind angemessen?", [["Bei führender Dyspnoe Oberkörper hoch, sofern der Kreislauf dies toleriert", true], ["Bei Hypotonie flach lagern und plötzliche Aufrichtung vermeiden", true], ["Bewusstlose mit erhaltener Atmung situationsgerecht in stabile Seitenlage bringen", true], ["Bei Kreislaufstillstand unverzüglich Reanimation beginnen", true], ["Jede anaphylaktische Person muss unabhängig vom Zustand gehen", false]], "Lagerung richtet sich nach Atemweg, Atmung, Kreislauf und Vigilanz; abruptes Aufstehen kann den venösen Rückstrom weiter vermindern."),
  q(16, "Welche Differenzialdiagnosen müssen bei Schwellung oder Atemnot aktiv bedacht werden?", [["Bradykininvermitteltes Angioödem unter ACE-Hemmern", true], ["Asthma oder COPD ohne systemische allergische Zeichen", true], ["Fremdkörperaspiration bei plötzlichem Beginn", true], ["Vasovagale Synkope bei Blässe und Bradykardie", true], ["Eine sichtbare Quaddel beweist immer einen anaphylaktischen Schock", false]], "Exposition, Hautbild, Atemgeräusch, Kreislauf, Begleitmedikation und Verlauf helfen bei der Abgrenzung."),
  q(17, "Welche Merkmale sprechen eher für ein bradykininvermitteltes als für ein histaminvermitteltes Angioödem?", [["Isolierte, nicht juckende Schwellung ohne Urtikaria", true], ["Einnahme eines ACE-Hemmers oder hereditäre Episoden", true], ["Schwaches Ansprechen auf Antihistaminikum und Glukokortikoid", true], ["Trotzdem mögliche akute Bedrohung des Atemwegs", true], ["Ausgeprägte Quaddeln und generalisierter Juckreiz sind zwingend", false]], "Bradykininangioödem und Anaphylaxie haben unterschiedliche Mediatorwege, können aber beide den Atemweg gefährden."),
  q(18, "Welche Informationen sind in SAMPLERS besonders relevant?", [["Exakter Beginn, Dynamik und betroffene Organsysteme", true], ["Mögliches Allergen, Expositionsweg und bereits beendete Exposition", true], ["Frühere Reaktionen, Asthma, Mastozytose und bekannte Notfallmedikation", true], ["Medikamente einschließlich ACE-Hemmer und Betablocker", true], ["Nur die letzte Mahlzeit; alle übrigen Angaben sind entbehrlich", false]], "Die Anamnese unterstützt Auslösererkennung, Differenzialdiagnose und Risikoeinschätzung, darf aber Akutmaßnahmen nicht verzögern."),
  q(19, "Welche Aussagen zur biphasischen Reaktion sind korrekt?", [["Nach vorübergehender Besserung können Symptome erneut auftreten", true], ["Kontinuierliche Überwachung und Transport bleiben deshalb erforderlich", true], ["Eine Kortikoidgabe garantiert nicht, dass keine zweite Phase folgt", true], ["Eine symptomfreie Minute beendet automatisch die Behandlungs- und Transportindikation", false], ["Biphasisch bedeutet ausschließlich eine zweite Hautrötung ohne Organbeteiligung", false]], "Eine erneute systemische Reaktion ist möglich; Verlaufskontrolle ist Teil der Sicherheit."),
  q(20, "Welche Nebenwirkungen oder Risiken passen zu den drei Medikamenten?", [["Adrenalin kann Tachykardie, Rhythmusstörungen, Tremor und Unruhe auslösen", true], ["Dimetinden kann Müdigkeit, Schwindel, Mundtrockenheit und Sehstörungen verursachen", true], ["Prednisolon kann unter anderem Hyperglykämie und Magenbeschwerden begünstigen", true], ["Adrenalin verursacht regelhaft eine Agranulozytose", false], ["Dimetinden steigert zuverlässig die Wachheit", false]], "Die Risiken werden überwacht, dürfen bei vitaler Anaphylaxie aber nicht zu einer gefährlichen Verzögerung der indizierten Therapie führen."),
  q(21, "Welche Aussagen zur Gefäßanatomie erklären das Kapillarleck?", [["Kapillaren bestehen im Wesentlichen aus Endothel und Basalmembran", true], ["Mediatorwirkung kann Zellkontakte am Endothel funktionell öffnen", true], ["Plasma tritt ins Interstitium über und vermindert das wirksame intravasale Volumen", true], ["Ödeme können gleichzeitig an Haut, Schleimhäuten und Atemwegen entstehen", true], ["Die Tunica media der Kapillaren kontrahiert wie ein großer Skelettmuskel", false]], "Das Endothel ist die entscheidende Barriere; Kapillaren besitzen keine ausgeprägte glatte Muskelschicht wie Arterien."),
  q(22, "Welche Befunde sind unmittelbar lebensbedrohliche Red Flags?", [["Inspiratorischer Stridor oder rasch zunehmende Zungen-/Rachenschwellung", true], ["Erschöpfung, Silent Chest oder fallende SpO₂", true], ["Hypotonie, Synkope oder zunehmende Bewusstseinsstörung", true], ["Bradykardie als mögliches spätes Dekompensationszeichen", true], ["Isolierter, seit Tagen unveränderter lokaler Juckreiz", false]], "Atemwegsverlust, respiratorisches Versagen und Kreislaufdekompensation verlangen parallele Eskalation."),
  q(23, "Welche Aussagen zur Notarztnachforderung und Versorgung passen zur Thüringer Systematik?", [["Anaphylaxie ab Stadium II ist in Anlage B3B als Nachforderungsindikation aufgeführt", true], ["ABCDE, Adrenalin, Volumen und Transportplanung laufen parallel", true], ["Wirkung und Nebenwirkungen jeder Maßnahme werden wiederholt evaluiert", true], ["Das Eintreffen des Notarztes muss vor jeder indizierten i.m.-Adrenalingabe abgewartet werden", false], ["Ein Hautausschlag schließt einen späteren schweren Verlauf aus", false]], "Die VFA strukturiert eigenverantwortliche Akutmaßnahmen; Notarztnachforderung darf zeitkritische Versorgung nicht verzögern."),
  q(24, "Welche Übergabe zeigt eine prüfungsreife Priorisierung?", [["Auslöser und Zeitpunkt der Exposition sowie Beginn und Dynamik nennen", true], ["Höchstes Stadium und betroffene Organsysteme benennen", true], ["Adrenalin mit Konzentration, Dosis, Weg, Zeit und Wirkung dokumentieren", true], ["Volumen, Prednisolon, Dimetinden, Monitoringtrend und erneute Symptome angeben", true], ["Nur 'Allergie' ohne Verlauf und Behandlung übergeben", false]], "Eine strukturierte Übergabe verbindet Exposition, ABCDE-Verlauf, Schweregrad, Therapie, Wirkung und erneute Verschlechterung."),
];
