import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct: boolean];

function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  const shift = (number * 2) % options.length;
  return {
    id: `angina-q-${String(number).padStart(2, "0")}`,
    mode: "multiple",
    prompt,
    options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })),
    source,
    difficulty,
  };
}

export const anginaPectorisFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "angina-card-01", area: "Definition", question: "Definieren Sie Angina pectoris und grenzen Sie sie vom Myokardinfarkt ab.", answer: "Angina pectoris ist ein klinisches Beschwerdebild durch vorübergehende Myokardischämie bei Missverhältnis zwischen Sauerstoffangebot und -bedarf. Eine nachgewiesene Myokardnekrose gehört nicht zur Angina; sie kennzeichnet den Infarkt. Präklinisch kann diese Abgrenzung nicht allein über Schmerz oder EKG erfolgen." },
  { id: "angina-card-02", area: "Stabil oder instabil", question: "Entwickeln Sie aus einer Beschwerdeanamnese die Kriterien für stabile und instabile Angina pectoris.", answer: "Stabil: bekanntes, reproduzierbares Belastungsmuster, gleichbleibende Schwelle und rasches Nachlassen in Ruhe oder nach wirksamem Nitrat. Instabil: Erstmanifestation, Ruhebeschwerden, Crescendo mit mehr Häufigkeit/Intensität, geringere Auslöseschwelle oder verlängerte Episode. Instabile Angina gehört zum ACS." },
  { id: "angina-card-03", area: "Koronarphysiologie", question: "Erklären Sie, warum eine feste Koronarstenose zunächst nur bei Belastung Beschwerden erzeugen kann.", answer: "In Ruhe kann der Blutfluss trotz Stenose noch ausreichen. Bei Belastung steigen Herzfrequenz, Kontraktilität und Wandspannung; der Sauerstoffbedarf nimmt zu. Die eingeengte Arterie kann den Fluss wegen verminderter Koronarreserve nicht entsprechend steigern, sodass eine Ischämie entsteht." },
  { id: "angina-card-04", area: "Pathophysiologie", question: "Leiten Sie den Übergang von stabiler KHK zur instabilen Angina her.", answer: "Endothelschaden und Atherosklerose erzeugen eine Plaque und Stenose. Rupturiert oder erodiert eine instabile Plaque, folgen Thrombozytenaktivierung und Thrombusbildung. Der Blutfluss sinkt akut; aus dem vorhersehbaren Belastungsmuster werden neue, stärkere oder in Ruhe auftretende Beschwerden." },
  { id: "angina-card-05", area: "Prinzmetal-Angina", question: "Wie unterscheidet sich die vasospastische Angina mechanistisch von der klassischen Belastungsangina?", answer: "Bei der vasospastischen Angina verursacht ein vorübergehender Koronarspasmus die Minderperfusion, häufig in Ruhe. Bei der klassischen stabilen Belastungsangina begrenzt meist eine feste atherosklerotische Stenose die Flussreserve bei steigendem Bedarf." },
  { id: "angina-card-06", area: "Arbeitsdiagnose", question: "Welche Befundkonstellation stützt eine koronare Ischämie und welche atypischen Präsentationen müssen Sie berücksichtigen?", answer: "Retrosternaler Druck oder Enge mit Ausstrahlung, Dyspnoe, Kaltschweißigkeit, Blässe, Übelkeit, Schwindel und Palpitationen stützen den Verdacht. Bei älteren Menschen, Frauen, Diabetes oder Niereninsuffizienz können Dyspnoe, Schwäche, Übelkeit oder Leistungsknick ohne klassischen Schmerz dominieren." },
  { id: "angina-card-07", area: "Diagnostik", question: "Warum schließen ein unauffälliges Erst-EKG und eine Beschwerdebesserung ein ACS nicht aus?", answer: "Instabile Angina und NSTEMI können ohne anhaltende ST-Hebung auftreten; Ischämiezeichen können dynamisch sein. Auch eine Besserung nach Ruhe oder Nitro ist nicht spezifisch. Klinik, Verlauf, Wiederholungsbeurteilung und klinische Biomarkerdiagnostik bleiben erforderlich." },
  { id: "angina-card-08", area: "Gefahren", question: "Leiten Sie die möglichen vitalen Komplikationen einer fortschreitenden Koronarischämie her.", answer: "Anhaltende Ischämie kann Myokardnekrose verursachen. Elektrische Instabilität begünstigt ventrikuläre Tachykardie und Kammerflimmern. Kontraktionsverlust kann Linksherzversagen, Lungenödem, niedriges Herzzeitvolumen und kardiogenen Schock auslösen." },
  { id: "angina-card-09", area: "Anamnese", question: "Welche Angaben aus SAMPLERS und OPQRST verändern Ihre präklinische Entscheidung besonders?", answer: "Erstmanifestation, Ruhe-/Belastungsbezug, Crescendo, Dauer und Ausstrahlung; Synkope oder Dyspnoe; bekannte KHK und frühere Interventionen; PDE-5-Hemmer und Zeitpunkt, Nitrate, Antikoagulation; vaskuläre Risiken sowie Hinweise auf Aortendissektion. Das bekannte individuelle Muster muss mit der aktuellen Episode verglichen werden." },
  { id: "angina-card-10", area: "Differenzialdiagnose", question: "Welche Befunde lassen Sie vor einer ACS-Therapie besonders an eine Aortendissektion denken?", answer: "Reißender Schmerz mit Ausstrahlung zwischen die Schulterblätter, Blutdruckdifferenz über 20 mmHg, Pulsdefizit, bekanntes thorakales Aortenaneurysma oder neurologisches Defizit. Diese Befunde verändern insbesondere die Entscheidung über antithrombotische Maßnahmen." },
  { id: "angina-card-11", area: "VFA 12", question: "Strukturieren Sie den Thüringer Basisalgorithmus bei akutem Thoraxschmerz.", answer: "cABCDE, Indikationsprüfung anhand Beschwerdebild und fehlendem neurologischem Defizit, zielgerichtete Sauerstoffgabe mit Ziel-SpO₂ über 90 %, Prüfung von Glyceroltrinitrat, 12-Kanal-EKG mit 50 mm/s innerhalb von 10 Minuten, kontinuierliches Monitoring, geeigneter Transport und bei STEMI/neuem LSB die verknüpften VFA-Pfade." },
  { id: "angina-card-12", area: "Glyceroltrinitrat", question: "Erklären Sie Wirkung, Dosis, Kontrolle und Kontraindikationen von Glyceroltrinitrat nach Thüringer VFA.", answer: "NO-Freisetzung erhöht cGMP und relaxiert glatte Gefäßmuskulatur; venöses Pooling senkt Vorlast und Wandspannung. VFA 13: 0,4 mg, ein Hub sublingual; nach 5 Minuten Wirkung und RR prüfen, maximal zwei Wiederholungen. Nicht bei PDE-5-Hemmern in 48 Stunden, RRsys < 120 mmHg oder Verdacht auf Hinterwandinfarkt." },
  { id: "angina-card-13", area: "VFA-Abgrenzung", question: "Warum werden ASS und Heparin bei instabiler Angina nicht automatisch aus VFA 14 abgeleitet?", answer: "VFA 14 trägt die konkrete Indikation STEMI oder neu aufgetretener Linksschenkelblock und fordert zusätzlich eine Kontraindikationsprüfung. Eine instabile Angina ohne diese Kriterien führt daher nicht automatisch in diesen Medikamentenpfad; sie bleibt dennoch ein ACS mit Monitoring und Kliniktransport." },
  { id: "angina-card-14", area: "Fallentscheidung", question: "Bekannte Belastungsangina, heute erstmals Schmerz in Ruhe; RR 126 mmHg, Sildenafil vor 30 Stunden. Begründen Sie Diagnose- und Nitroentscheidung.", answer: "Die Ruheepisode verändert das bekannte Muster und ist als instabile Angina beziehungsweise ACS zu behandeln. Trotz RR über 120 mmHg ist Glyceroltrinitrat nach VFA 13 wegen PDE-5-Hemmer innerhalb 48 Stunden kontraindiziert. cABCDE, EKG, Monitoring und zeitgerechter Transport werden fortgeführt." },
];

export const anginaPectorisQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen grenzen Angina pectoris und Myokardinfarkt fachlich korrekt ab?", [["Angina pectoris beruht auf einer vorübergehenden Myokardischämie", true], ["Eine nachgewiesene Myokardnekrose spricht für einen Infarkt", true], ["Schmerzfreiheit nach Nitro schließt einen Infarkt sicher aus", false], ["Ein unauffälliges EKG beweist eine stabile Angina", false], ["Instabile Angina gehört zum akuten Koronarsyndrom", true]], "Angina beschreibt Ischämie ohne nachgewiesene Nekrose; die instabile Form ist Teil des ACS.", 1),
  q(2, "Welche Merkmale sprechen für eine stabile Angina pectoris?", [["Reproduzierbare Beschwerden bei vergleichbarer Belastung", true], ["Nachlassen in Ruhe innerhalb weniger Minuten", true], ["Erstmaliger retrosternaler Schmerz in Ruhe", false], ["Zunehmende Häufigkeit bei sinkender Belastungsschwelle", false], ["Über längere Zeit gleichbleibendes Beschwerdemuster", true]], "Stabile Angina zeigt ein bekanntes, vorhersehbares Belastungsmuster ohne Crescendo oder Ruhebeschwerden.", 1),
  q(3, "Welche Veränderungen machen eine bisher bekannte Belastungsangina instabil?", [["Die Beschwerden treten nun in Ruhe auf", true], ["Die Episoden werden häufiger oder intensiver", true], ["Die Auslöseschwelle sinkt deutlich", true], ["Das seit Jahren unveränderte Muster bleibt bestehen", false], ["Die bekannte Episode endet rasch nach Belastungsende", false]], "Ruheangina, Crescendo und geringere Auslöseschwelle kennzeichnen Instabilität.", 2),
  q(4, "Welche Zusammenhänge erklären die Belastungsischämie bei fester Koronarstenose?", [["Der Sauerstoffbedarf steigt mit Herzfrequenz und Kontraktilität", true], ["Die Stenose begrenzt die Steigerung des Koronarflusses", true], ["In Ruhe kann die Restperfusion zunächst ausreichen", true], ["Belastung senkt grundsätzlich die myokardiale Wandspannung", false], ["Die Koronarreserve steigt durch die Stenose", false]], "Steigender Bedarf trifft auf eine verminderte Koronarreserve; in Ruhe kann das Angebot noch genügen.", 2),
  q(5, "Welche Schritte gehören zur Entwicklung der koronaren Atherosklerose?", [["Endothelschädigung", true], ["Plaquebildung in der Gefäßwand", true], ["Abnahme des Gefäßlumens und der Elastizität", true], ["Zwingende vollständige Rekanalisation durch Belastung", false], ["Dauerhafte Erweiterung der Koronarreserve", false]], "Endothelschaden, Plaque und Stenose vermindern Lumen und Koronarreserve.", 1),
  q(6, "Welche Mechanismen können aus stabiler KHK ein akutes Koronarsyndrom entstehen lassen?", [["Plaqueruptur oder -erosion", true], ["Thrombozytenaktivierung und Thrombusbildung", true], ["Plötzliche weitere Verminderung des Koronarflusses", true], ["Allein die dauerhafte Schmerzfreiheit", false], ["Eine unveränderte feste Stenose ohne neue Dynamik beweist ACS", false]], "Plaqueinstabilität und Thrombus führen zur akuten Flussminderung und klinischen Instabilität.", 2),
  q(7, "Welche Aussagen zur Prinzmetal-Angina treffen zu?", [["Rezidivierende Koronarspasmen können die Minderperfusion auslösen", true], ["Beschwerden können in Ruhe auftreten", true], ["Sie setzt definitionsgemäß eine vollständige Plaqueruptur voraus", false], ["Der Mechanismus unterscheidet sich von der festen Belastungsstenose", true], ["Ein Spasmus kann niemals EKG-Veränderungen verursachen", false]], "Vasospastische Angina entsteht durch vorübergehende Koronarspasmen, häufig in Ruhe.", 2),
  q(8, "Welche Befunde stützen die Arbeitsdiagnose einer koronaren Ischämie?", [["Retrosternaler Druck mit Ausstrahlung", true], ["Dyspnoe und Kaltschweißigkeit", true], ["Übelkeit oder fahle Blässe", true], ["Isolierter lagerungsabhängiger Stich beweist ACS", false], ["Schmerzfreiheit schließt ein atypisches ACS aus", false]], "Thoraxdruck, Ausstrahlung und vegetative Begleitsymptome bilden eine typische, aber nicht beweisende Konstellation.", 2),
  q(9, "Bei welchen Personen kann ein ACS besonders atypisch erscheinen?", [["Ältere Menschen", true], ["Menschen mit Diabetes mellitus", true], ["Frauen", true], ["Nur Patienten mit bekannter KHK", false], ["Ausschließlich junge Leistungssportler", false]], "Dyspnoe, Schwäche, Übelkeit oder Leistungsknick können ohne klassischen Thoraxschmerz dominieren.", 2),
  q(10, "Das erste 12-Kanal-EKG zeigt keine ST-Hebung. Welche Bewertungen sind angemessen?", [["Instabile Angina bleibt möglich", true], ["NSTEMI bleibt möglich", true], ["Klinik und Verlauf müssen weiter beurteilt werden", true], ["ACS ist damit ausgeschlossen", false], ["Monitoring und Transport sind grundsätzlich entbehrlich", false]], "Ein Einzel-EKG ohne ST-Hebung schließt weder instabile Angina noch NSTEMI aus.", 3),
  q(11, "Welche Komplikationen können aus fortschreitender Myokardischämie entstehen?", [["Ventrikuläre Rhythmusstörung", true], ["Myokardinfarkt", true], ["Akutes Linksherzversagen", true], ["Garantierte spontane Gefäßheilung", false], ["Ausschließlich eine vorübergehende Tachypnoe", false]], "Nekrose, elektrische Instabilität und Pumpversagen sind zentrale Gefahren.", 2),
  q(12, "Welche präklinischen Maßnahmen sind bei Verdacht auf instabile Angina sinnvoll?", [["cABCDE und wiederholte Beurteilung", true], ["12-Kanal-EKG innerhalb von 10 Minuten", true], ["Kontinuierliches Monitoring und geeigneter Transport", true], ["Belastungsprovokation zur Diagnosesicherung", false], ["Entlassung allein wegen Beschwerdebesserung", false]], "Instabile Angina wird als ACS mit früher Diagnostik, Überwachung und Transport behandelt.", 2),
  q(13, "Welche Angaben müssen vor einer möglichen Glyceroltrinitratgabe aktiv erhoben werden?", [["Systolischer Blutdruck", true], ["PDE-5-Hemmer in den letzten 48 Stunden", true], ["Hinweise auf einen Hinterwandinfarkt", true], ["Nur der aktuelle Schmerzscore", false], ["Die letzte Tetanusimpfung", false]], "VFA 13 nennt RRsys, PDE-5-Hemmer und Verdacht auf Hinterwandinfarkt als entscheidende Sicherheitsprüfung.", 3),
  q(14, "Welche Aussagen beschreiben die Wirkung von Glyceroltrinitrat?", [["NO erhöht über cGMP die Relaxation glatter Gefäßmuskulatur", true], ["Venöses Pooling kann Vorlast und Wandspannung senken", true], ["Arterielle Dilatation kann die Nachlast vermindern", true], ["Es steigert gezielt die Thrombozytenaggregation", false], ["Es erhöht grundsätzlich den systolischen Blutdruck", false]], "GTN wirkt vasodilatierend; venöse Effekte senken Vorlast und myokardialen Sauerstoffbedarf.", 3),
  q(15, "Welche Nebenwirkungen passen zur Glyceroltrinitratgabe?", [["Kopfschmerzen oder Schwindel", true], ["Hypotonie mit möglicher Reflextachykardie", true], ["Flush oder Übelkeit", true], ["Zwingende schwere Bradykardie", false], ["Dauerhafte Koronarthrombose", false]], "Vasodilatation kann Kopfschmerz, Flush, orthostatische Beschwerden und Blutdruckabfall verursachen.", 2),
  q(16, "Ein Patient mit ACS-Verdacht hat RRsys 118 mmHg und keine PDE-5-Einnahme. Welche Aussagen treffen nach VFA 13 zu?", [["Glyceroltrinitrat ist wegen RRsys unter 120 mmHg kontraindiziert", true], ["Die übrige ACS-Versorgung wird fortgesetzt", true], ["Der Blutdruck wird im Verlauf erneut beurteilt", true], ["Ein Hub ist erlaubt, weil RRsys über 100 mmHg liegt", false], ["Ohne Nitro ist ein 12-Kanal-EKG entbehrlich", false]], "Die Thüringer VFA setzt für GTN RRsys mindestens 120 mmHg voraus; der ACS-Pfad bleibt davon unberührt.", 3),
  q(17, "RRsys 138 mmHg, Tadalafil vor 36 Stunden, kein Hinterwandverdacht: Welche Entscheidungen sind richtig?", [["Glyceroltrinitrat wird nach VFA 13 nicht gegeben", true], ["Die PDE-5-Einnahme liegt innerhalb der 48-Stunden-Grenze", true], ["Monitoring und Transport bleiben erforderlich", true], ["Der ausreichende Blutdruck hebt die Wechselwirkung auf", false], ["Tadalafil ist für die Nitro-Anamnese bedeutungslos", false]], "PDE-5-Hemmer innerhalb 48 Stunden sind trotz ausreichendem Ausgangs-RR eine Kontraindikation.", 3),
  q(18, "Welche Schritte gehören zum Glyceroltrinitrat-Algorithmus bei erfüllter Indikation?", [["0,4 mg als ein Hub sublingual", true], ["Nach 5 Minuten Wirkung und Blutdruck kontrollieren", true], ["Maximal zwei Wiederholungen nach erneuter Prüfung", true], ["0,4 mg langsam intravenös injizieren", false], ["Zwischen den Gaben auf Blutdruckkontrollen verzichten", false]], "VFA 13: ein Hub 0,4 mg sublingual, Kontrolle nach 5 Minuten, höchstens zwei Wiederholungen.", 3),
  q(19, "Welche Aussagen zur Thüringer VFA 14 sind korrekt?", [["Der Pfad gilt bei STEMI oder neu aufgetretenem Linksschenkelblock", true], ["Aktive Blutung ist eine Kontraindikation", true], ["Eine akute Aortendissektion muss ausgeschlossen werden", true], ["Jede stabile Belastungsangina führt automatisch zu ASS und Heparin", false], ["Ein frischer Schlaganfall ist für die Entscheidung irrelevant", false]], "VFA 14 besitzt eine enge Indikation und nennt aktive Blutung, frischen Schlaganfall und akute Aortendissektion als Kontraindikationen.", 3),
  q(20, "Welche Befunde sprechen bei akutem Thoraxschmerz besonders für eine mögliche Aortendissektion?", [["Reißender Schmerz zwischen den Schulterblättern", true], ["Blutdruckdifferenz über 20 mmHg zwischen den Armen", true], ["Pulsdefizit oder neurologischer Ausfall", true], ["Isolierte bekannte Belastungsangina ohne Musteränderung", false], ["Besserung nach Ruhe als sicherer Ausschluss", false]], "Schmerzcharakter, Blutdruckdifferenz, Pulsdefizit, Aneurysma und neurologisches Defizit verändern die Therapieentscheidung.", 3),
  q(21, "Bekannte stabile Angina: heute erstmals Ruhebeschwerden, RRsys 126 mmHg, Sildenafil vor 30 Stunden, Erst-EKG ohne ST-Hebung. Welche Schlussfolgerungen sind richtig?", [["Die Musteränderung spricht für instabile Angina und damit ACS", true], ["Nitro ist wegen PDE-5-Hemmer innerhalb 48 Stunden kontraindiziert", true], ["Das unauffällige Erst-EKG schließt NSTEMI oder instabile Angina nicht aus", true], ["Der Patient kann wegen RRsys über 120 mmHg zu Hause bleiben", false], ["ASS und Heparin sind allein aufgrund des Ruhedrucks automatisch nach VFA 14 zu geben", false]], "Die Kombination erfordert ACS-Versorgung und Transport; VFA 13 verbietet GTN, VFA 14 setzt STEMI oder neuen LSB voraus.", 3),
];
