import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function AnginaPectorisLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, kicker: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>{kicker}</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;

  return <article className="lesson-article angina-pectoris-lesson">
    <div className="lesson-intro"><p className="lead">Angina pectoris beschreibt eine vorübergehende Minderversorgung des Herzmuskels. Prüfungsentscheidend ist die Trennung zwischen einer bekannten, belastungsabhängigen stabilen Angina und einer instabilen Angina als Teil des akuten Koronarsyndroms.</p></div>

    {section("01", "Grundverständnis", "Definition oder Erklärung", <><p><b>Angina pectoris</b> bedeutet sinngemäß „Enge der Brust“. Gemeint ist ein klinisches Beschwerdebild durch eine vorübergehende Myokardischämie: Das Sauerstoffangebot reicht für den aktuellen Bedarf des Herzmuskels nicht aus.</p><p>Eine Angina pectoris verursacht noch keine nachgewiesene Myokardnekrose. Bei anhaltender oder zunehmender Ischämie kann sie jedoch in einen Myokardinfarkt übergehen.</p><div className="pulmo-compare"><div><small>Vorhersehbares Muster</small><h3>Stabile Angina pectoris</h3><p>Beschwerden treten reproduzierbar bei körperlicher oder psychischer Belastung auf und lassen in Ruhe oder nach wirksamer Nitratgabe innerhalb weniger Minuten nach. Das bekannte Muster bleibt zunächst gleich.</p><span>Eine stabile Angina ist kein akutes Koronarsyndrom. Jede Abweichung vom bekannten Muster muss neu bewertet werden.</span></div><div><small>Akutes Koronarsyndrom</small><h3>Instabile Angina pectoris</h3><p>Erstmalige Beschwerden, Ruhebeschwerden, deutlich häufigere oder stärkere Episoden sowie länger anhaltende Beschwerden sprechen für Instabilität.</p><span>Präklinisch wird diese Konstellation als ACS behandelt. Die Abgrenzung zum NSTEMI ist erst mit der klinischen Diagnostik und Troponinbestimmung möglich.</span></div></div><aside className="red-flags"><span>!</span><div><small>Prüfungsentscheidung</small><h3>Neu, in Ruhe, zunehmend oder anhaltend = instabil</h3><p>Eine erstmalig aufgetretene Angina pectoris ist bis zur weiteren Abklärung als instabil zu werten.</p></div></aside></>)}

    {section("02", "Anatomie und Physiologie", "Herz und Koronargefäße", <><p>Das rechte Herz nimmt venöses Blut auf und pumpt es über die Lungenarterien zur Lunge. Sauerstoffreiches Blut gelangt über die Lungenvenen zum linken Herzen und wird über die Aorta in den Körperkreislauf ausgeworfen.</p><Figure src="/lessons/angina-pectoris/herz-kreislauf.jpeg" alt="Beschrifteter Aufbau des Herzens mit Blutfluss, Herzklappen und großen Gefäßen" caption="Herzaufbau und Blutfluss aus dem Skript" wide /><h3>Koronararterien</h3><p>Die rechte und die linke Koronararterie entspringen aus der Aorta und versorgen das Myokard. Die linke Koronararterie teilt sich unter anderem in den Ramus interventricularis anterior und den Ramus circumflexus. Wird ein Koronargefäß relevant eingeengt, kann der Blutfluss bei steigendem Sauerstoffbedarf nicht ausreichend zunehmen.</p><Figure src="/lessons/angina-pectoris/koronargefaesse.jpeg" alt="Beschriftete äußere Ansicht des Herzens mit rechter und linker Koronararterie" caption="Herzkranzgefäße aus dem Skript" wide /><div className="pulmo-path"><span>Sauerstoffangebot</span><i>↔</i><span>Sauerstoffbedarf</span><i>→</i><span>Gleichgewicht hält das Myokard arbeitsfähig</span></div><p>Der myokardiale Sauerstoffbedarf steigt besonders mit Herzfrequenz, Kontraktilität und Wandspannung. Das Sauerstoffangebot hängt vor allem vom Koronarblutfluss und vom Sauerstoffgehalt des Blutes ab.</p></>)}

    {section("03", "Ursachen und Pathophysiologie", "Entstehung der Ischämie", <><p>Häufige Grunderkrankung ist die koronare Herzkrankheit. Endothelschädigung und Risikofaktoren wie Hypertonie, Rauchen oder Hypercholesterinämie fördern die Atherosklerose. Plaques verengen das Gefäßlumen und vermindern die Koronarreserve.</p><div className="pulmo-path"><span>Endothelschaden</span><i>→</i><span>Plaquebildung</span><i>→</i><span>Stenose</span><i>→</i><span>Koronarreserve sinkt</span><i>→</i><span>Belastungsischämie</span></div><div className="pulmo-risk-grid"><div><b>Stabile Plaque</b><p>Eine feste Stenose begrenzt den maximalen Blutfluss. In Ruhe kann die Versorgung genügen; bei Belastung entsteht ein Missverhältnis zwischen Angebot und Bedarf.</p></div><div><b>Plaqueruptur und Thrombus</b><p>Eine instabile Plaque kann einreißen. Thrombozytenaktivierung und Thrombusbildung vermindern den Blutfluss plötzlich und machen aus dem stabilen Muster ein ACS.</p></div><div><b>Vasospastische Angina</b><p>Bei der Prinzmetal-Angina führen rezidivierende Koronarspasmen zu einer vorübergehenden Minderperfusion, häufig auch in Ruhe.</p></div><div><b>Folge der Ischämie</b><p>Anaerober Stoffwechsel und lokale Metabolite verursachen Beschwerden und beeinträchtigen zuerst die Relaxation, später Kontraktion und elektrische Stabilität.</p></div></div><aside className="knowledge-note"><b>Angina oder Infarkt?</b><p>Bei Angina pectoris besteht noch eine Restperfusion ohne nachgewiesene ausgedehnte Nekrose. Dauer und Schmerzreaktion allein beweisen präklinisch aber weder eine stabile Angina noch den Ausschluss eines Infarkts.</p></aside></>)}

    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", "Symptome", <><div className="pulmo-symptoms">{["Retrosternaler Druck, Enge oder Schmerz", "Ausstrahlung in Arm, Schulter, Kiefer oder Rücken", "Atemnot", "Übelkeit oder Brechreiz", "Kalter Schweiß und fahle Blässe", "Schwindel, Schwäche oder Synkope", "Palpitationen", "Angst oder Unruhe"].map((item) => <span key={item}>{item}</span>)}</div><p>Atypische oder schmerzarme Verläufe sind insbesondere bei älteren Menschen, Frauen sowie Menschen mit Diabetes oder Niereninsuffizienz möglich. Dyspnoe, Leistungsknick, Übelkeit oder Schwäche können im Vordergrund stehen.</p><aside className="red-flags"><span>!</span><div><small>Instabilitätszeichen</small><h3>Beschwerdemuster aktiv vergleichen</h3><p>Erstmanifestation, Ruhebeschwerden, Crescendo-Symptomatik, verlängerte Episode, Synkope, Hypotonie, Rhythmusstörung oder Zeichen der Herzinsuffizienz sprechen gegen eine harmlose bekannte Belastungsangina.</p></div></aside></>)}

    {section("05", "Welche Gefahren und Komplikationen gibt es?", "Komplikationen und Gefahren", <><div className="pulmo-risk-grid"><div><b>Myokardinfarkt</b><p>Anhaltende Ischämie kann zum irreversiblen Untergang von Herzmuskelzellen führen.</p></div><div><b>Rhythmusstörungen</b><p>Elektrische Instabilität kann ventrikuläre Tachykardien oder Kammerflimmern auslösen.</p></div><div><b>Linksherzversagen</b><p>Sinkende Pumpfunktion kann ein kardiales Lungenödem verursachen.</p></div><div><b>Kardiogener Schock</b><p>Ausgeprägter Funktionsverlust vermindert Herzzeitvolumen und Organperfusion.</p></div></div><p>Eine zunächst stabile Angina kann ihr Muster verändern und instabil werden. Deshalb werden Dynamik, Vitalparameter, EKG und Wirkung jeder Maßnahme wiederholt beurteilt.</p></>)}

    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", "Einsatzmaterialien", <div className="material-chips">{["Notfallrucksack", "EKG / Monitor / Defibrillator", "12-Kanal-EKG", "RR-Manschetten", "Pulsoxymetrie", "i.v.-Zugangsset", "Ampullarium", "Sauerstoff und Beatmungsgerät", "Absaugung", "Trage / Tragestuhl", "Reanimationsbereitschaft"].map((item) => <span key={item}>{item}</span>)}</div>)}

    {section("07", "Erstmaßnahmen, Diagnostik und Anamnese", "cABCDE und SAMPLERS", <><div className="pulmo-care-grid"><div><span>01</span><b>cABCDE</b><small>Lebensbedrohliche Störungen erkennen und parallel behandeln.</small></div><div><span>02</span><b>Monitoring</b><small>RR beidseits initial, Puls, SpO₂, Rhythmus und klinischen Verlauf erfassen.</small></div><div><span>03</span><b>12-Kanal-EKG</b><small>Bei ACS-Verdacht innerhalb von 10 Minuten mit 50 mm/s; ein unauffälliges Erst-EKG schließt ACS nicht aus.</small></div><div><span>04</span><b>Schonung</b><small>Nicht laufen lassen, beruhigen und symptomgerecht mit erhöhtem Oberkörper lagern, sofern der Kreislauf dies erlaubt.</small></div></div><h3>SAMPLERS und OPQRST gezielt</h3><div className="samplers-grid">{[["S · Symptome", "Beginn, Dauer, Dynamik, Ruhe-/Belastungsbezug, Begleitsymptome"], ["A · Allergien", "Arzneimittelallergien und Unverträglichkeiten"], ["M · Medikamente", "PDE-5-Hemmer, Nitrate, Antikoagulation, Herzmedikation"], ["P · Vorgeschichte", "KHK, frühere Angina, Infarkt, Interventionen, Herzinsuffizienz"], ["L · Letzte Aufnahme", "Nahrung, Flüssigkeit, Alkohol und Zeitpunkt"], ["E · Ereignis", "Auslöser, Belastung und Veränderung des bekannten Musters"], ["R · Risiken", "Rauchen, Hypertonie, Diabetes, Dyslipidämie, familiäre Belastung"], ["S · Schwangerschaft", "Falls relevant"]].map(([name, text]) => <p key={name}><b>{name}</b>{text}</p>)}</div><p><b>OPQRST:</b> Onset, Provocation/Palliation, Quality, Radiation, Severity und Time. Eine Besserung nach Nitro beweist keine koronare Ursache und ersetzt die weitere Abklärung nicht.</p></>)}

    {section("08", "Differenzialdiagnosen und Entscheidungsfindung", "Gefährliche Alternativen", <><div className="differential-grid">{["Akuter Myokardinfarkt", "Aortendissektion", "Lungenarterienembolie", "Pneumothorax", "Perikarditis / Myokarditis", "Akute Herzinsuffizienz", "Hypertensiver Notfall", "Pneumonie / Pleuritis", "Ösophageale oder gastrointestinale Ursache", "Interkostalneuralgie / muskuloskelettaler Schmerz", "Pankreatitis"].map((item) => <span key={item}>{item}</span>)}</div><aside className="diagnostic-boundary"><span>!</span><div><b>Aortendissektion vor antithrombotischer Therapie bedenken</b><p>Reißender Schmerz, Ausstrahlung zwischen die Schulterblätter, Blutdruckdifferenz über 20 mmHg, Pulsdefizit, bekanntes thorakales Aortenaneurysma oder neurologisches Defizit lenken zur akuten Aortendissektion.</p></div></aside><p>Präklinisch lässt sich eine instabile Angina nicht sicher vom NSTEMI abgrenzen. Ein unauffälliges EKG oder nachlassender Schmerz beendet deshalb weder Monitoring noch Transportentscheidung.</p></>)}

    {section("09", "Weitere Maßnahmen", "Versorgung nach Thüringer VFA", <><div className="pulmo-vfa-flow"><div><span>12</span><b>ACS-Basisalgorithmus</b><small>cABCDE, zielgerichtete O₂-Gabe mit Ziel-SpO₂ über 90 %, frühes 12-Kanal-EKG, kontinuierliches Monitoring und Transport.</small></div><div><span>13</span><b>Glyceroltrinitrat prüfen</b><small>0,4 mg als ein Hub sublingual nur ohne VFA-Kontraindikation; RR engmaschig kontrollieren.</small></div><div><span>5 min</span><b>Wirkung re-evaluieren</b><small>Schmerz, RR, Kreislauf und Beschwerden prüfen; nach VFA maximal zwei Wiederholungen.</small></div><div><span>14</span><b>ASS und Heparin nicht pauschal</b><small>Der VFA-14-Pfad gilt bei STEMI oder neu aufgetretenem Linksschenkelblock und nach Prüfung seiner Kontraindikationen.</small></div></div><div className="pulmo-medicine-grid"><div><small>Wirkprinzip</small><b>NO → cGMP → Relaxation glatter Muskulatur</b><p>Vorwiegend venöses Pooling senkt Vorlast und myokardiale Wandspannung. Zusätzlich können koronare und arterielle Gefäße dilatieren.</p></div><div><small>Nebenwirkungen</small><b>Hypotonie aktiv erwarten</b><p>Kopfschmerz, Schwindel, Übelkeit, Flush, orthostatische Beschwerden und Reflextachykardie sind möglich.</p></div></div><aside className="red-flags"><span>×</span><div><small>Kontraindikationen nach VFA 13</small><h3>Vor jedem Hub neu prüfen</h3><p>PDE-5-Hemmer innerhalb der letzten 48 Stunden, systolischer Blutdruck unter 120 mmHg oder Verdacht auf Hinterwandinfarkt.</p></div></aside><div className="eug-destination"><span>→</span><div><small>Transport</small><b>ACS-Verdacht bleibt überwachungspflichtig</b><p>Geeignete Zielklinik früh informieren. EKG, Beschwerdeverlauf, Vitalwerte, Medikamente, Zeitpunkt und Wirkung strukturiert übergeben.</p></div></div></>)}

    {section("10", "Originalalgorithmen", "VFA Thüringen 2026/2027", <><p>Die aktuellen Originalseiten sind einklappbar und im Vollbild lesbar. Dosis, Wiederholung und Kontraindikationen richten sich ausschließlich nach diesen Thüringer Verfahrensanweisungen.</p><div className="vfa-stack"><Vfa src="/lessons/acs/vfa-acs-basis-12.png" alt="VFA 12 Basisalgorithmus akuter Thoraxschmerz ACS Thüringen 2026/27" caption="VFA 12 · Basisalgorithmus akuter Thoraxschmerz (ACS)" /><Vfa src="/lessons/acs/vfa-glyceroltrinitrat-13.png" alt="VFA 13 Glyceroltrinitrat-Spray bei Verdacht auf ACS Thüringen 2026/27" caption="VFA 13 · Glyceroltrinitrat-Spray" /><Vfa src="/lessons/acs/vfa-ass-heparin-14.png" alt="VFA 14 Acetylsalicylsäure und Heparin bei STEMI oder neuem Linksschenkelblock Thüringen 2026/27" caption="VFA 14 · ASS und Heparin bei STEMI / neuem LSB" /></div></>)}

    {children}
    <p className="lesson-source">Hauptgrundlage: „2. Angina Pectoris.docx“. Medikamentöse Wirkung und Nebenwirkungen ergänzt nach <a href="https://rd-factsheets.de/fs/glyceroltrinitrat-2/" target="_blank" rel="noreferrer">Rettungsdienst FactSheets – Glyceroltrinitrat</a>. Dosis, Wiederholung, Kontraindikationen und Behandlungswege ausschließlich nach den <a href="https://www.aelrd-thueringen.de/verfahrensanweisungen-fuer-den-thueringer-rettungsdienst-algorithmen/" target="_blank" rel="noreferrer">Thüringer VFA 2026/27</a>, insbesondere VFA 12 bis 14.</p>
  </article>;
}
