import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct?: boolean];

function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  return { id: `barotrauma-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: options.map(([text, correct]) => ({ text, correct })), source, difficulty };
}

export const barotraumaFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "barotrauma-card-01", area: "Definition", question: "Definieren Sie ein Barotrauma und nennen Sie die notwendige physikalische Voraussetzung.", answer: "Ein Barotrauma ist eine Gewebeschädigung durch eine Druckdifferenz zwischen Umgebung und einem gasgefüllten Körperraum. Voraussetzung ist ein luft- oder gasgefüllter Raum, dessen Druck sich nicht ausreichend anpassen kann, etwa Mittelohr, Nasennebenhöhle oder Lunge." },
  { id: "barotrauma-card-02", area: "Boyle-Mariotte", question: "Erklären Sie das Gesetz von Boyle-Mariotte für Ab- und Auftauchen.", answer: "Bei konstanter Temperatur gilt p × V = konstant. Beim Abtauchen steigt der Umgebungsdruck und das Gasvolumen nimmt ab. Beim Auftauchen sinkt der Umgebungsdruck und eingeschlossenes Gas dehnt sich aus. Kann es nicht entweichen, droht ein Überdehnungstrauma." },
  { id: "barotrauma-card-03", area: "Dalton und Henry", question: "Welche Bedeutung haben Dalton und Henry für einen Tauchunfall?", answer: "Dalton: Der Gesamtdruck ist die Summe der Partialdrücke; mit der Tiefe steigen die Partialdrücke der Atemgase. Henry: Mit steigendem Partialdruck löst sich mehr Gas im Gewebe. Beim zu schnellen Auftauchen kann gelöstes Inertgas ausperlen und eine Dekompressionskrankheit verursachen." },
  { id: "barotrauma-card-04", area: "Phasen", question: "Nennen Sie die drei Tauchphasen und ihre typischen Gefahren.", answer: "Kompression/Abstieg: Volumenabnahme und fehlender Druckausgleich in Ohr oder Nebenhöhlen. Isopression in Tiefe: kein akutes Druckänderungstrauma, aber Risiken durch Atemgas, Belastung und Panik. Dekompression/Aufstieg: Gasexpansion, pulmonales Barotrauma und bei zu schneller Entsättigung Dekompressionskrankheit." },
  { id: "barotrauma-card-05", area: "Pulmonales Barotrauma", question: "Leiten Sie die Entstehung eines pulmonalen Barotraumas schrittweise her.", answer: "Beim Aufstieg fällt der Umgebungsdruck, alveoläre Luft dehnt sich aus. Luftanhalten, Laryngospasmus oder Air-Trapping behindern das Entweichen. Der transpulmonale Druck steigt, Alveolen beziehungsweise kleine Atemwege reißen; Luft gelangt in Pleura, Mediastinum, Subkutis oder über verletzte Gefäße in den arteriellen Kreislauf." },
  { id: "barotrauma-card-06", area: "Folgen", question: "Welche vier schweren Folgen kann ein pulmonales Barotrauma haben?", answer: "Pneumothorax beziehungsweise Spannungspneumothorax, Mediastinalemphysem, subkutanes Emphysem und arterielle Gasembolie. Hämoptysen und alveoläre Einblutungen können zusätzlich auftreten." },
  { id: "barotrauma-card-07", area: "Abgrenzung", question: "Grenzen Sie pulmonales Barotrauma, arterielle Gasembolie und Dekompressionskrankheit ab.", answer: "Pulmonales Barotrauma ist eine mechanische Überdehnungs- und Rissverletzung. Bei der arteriellen Gasembolie gelangt Gas meist über verletzte Lungengefäße in Arterien und verursacht akute Organischämien. Die Dekompressionskrankheit entsteht durch Ausperlen gelöster Inertgase aus Blut und Gewebe." },
  { id: "barotrauma-card-08", area: "Symptome", question: "Welche Befunde sprechen nach dem Auftauchen für eine arterielle Gasembolie?", answer: "Plötzlich, häufig unmittelbar oder binnen Minuten auftretende neurologische Ausfälle, Bewusstseinsstörung, Krampfanfall, Verwirrtheit, Schwindel oder schlaganfallähnliche Zeichen nach raschem Aufstieg. Gleichzeitiger Thoraxschmerz oder Dyspnoe stützt ein pulmonales Barotrauma, ist aber nicht obligat." },
  { id: "barotrauma-card-09", area: "Anamnese", question: "Welche tauchspezifischen Informationen müssen erhoben und gesichert werden?", answer: "Tiefe, Grundzeit, Aufstiegsgeschwindigkeit, Sicherheits-/Dekompressionsstopps, Atemgas, Wiederholungstauchgänge und Oberflächenintervalle, Probleme und Symptomzeitpunkt. Buddy befragen; Tauchcomputer und Ausrüstung kennzeichnen und mitführen, ohne die Patientenversorgung zu verzögern." },
  { id: "barotrauma-card-10", area: "Erstmaßnahmen", question: "Strukturieren Sie die präklinische Versorgung eines symptomatischen Tauchers.", answer: "Eigenschutz und Rettung nur durch Wasserrettung/Feuerwehr, cABCDE, früh höchstmögliche Sauerstoffkonzentration, Monitoring, neurologischer Status, Wärmeerhalt, venöser Zugang und Re-Evaluation. Tauchmedizinische Beratung und geeignete Klinik/Druckkammer früh koordinieren; Symptome trotz Besserung ernst nehmen." },
  { id: "barotrauma-card-11", area: "Druckkammer", question: "Wie wirkt eine hyperbare Sauerstofftherapie bei Dekompressionsunfall?", answer: "Rekompression verkleinert Gasblasen; Sauerstoff unter erhöhtem Umgebungsdruck steigert die Gewebeoxygenierung und verbessert den Gradienten für die Elimination von Inertgas. Die anschließende kontrollierte Dekompression erfolgt nach festgelegtem Schema in einer Druckkammer." },
  { id: "barotrauma-card-12", area: "Beatmung", question: "Was ist bei notwendiger positiver Druckbeatmung nach möglichem pulmonalem Barotrauma zu beachten?", answer: "Eine notwendige Beatmung darf nicht unterlassen werden, erhöht aber bei verletzter Lunge das Risiko weiterer Überdehnung und eines Spannungspneumothorax. Deshalb niedrigste wirksame Drücke und Volumina, engmaschige Thorax- und Kreislaufkontrolle sowie Entlastungsbereitschaft nach VFA bei klinischer Spannungskomponente." },
  { id: "barotrauma-card-13", area: "Zusammenarbeit", question: "Wie teilen Rettungsdienst, Wasserrettung und Feuerwehr die Aufgaben sinnvoll auf?", answer: "Wasserrettung/Feuerwehr übernehmen Gefahrenbereich, Rettung aus dem Wasser, technische Sicherung und Information zu Umgebung/Ausrüstung. Der Rettungsdienst übernimmt nach Übergabe cABCDE, Sauerstoff, Monitoring, Anamnese, Dokumentation und medizinische Zielsteuerung. Transportweg, RTH-Einsatz und Druckkammerkontakt werden gemeinsam koordiniert." },
  { id: "barotrauma-card-14", area: "Prüfungsfallen", question: "Nennen Sie vier typische Prüfungsfallen beim Tauchunfall.", answer: "Barotrauma nicht mit Dekompressionskrankheit (DCS) gleichsetzen; Besserung unter Sauerstoff beendet die Abklärung nicht; keine improvisierte Wiederkompression im Wasser; neurologische Symptome nicht vorschnell als Schlaganfall ohne Tauchbezug behandeln; unkritische Luftrettung mit großer Flughöhe vermeiden und Druckkammertransport abstimmen." },
  { id: "barotrauma-card-15", area: "Partialdruck", question: "Erklären Sie den Stickstoffpartialdruck bei Pressluft in 20 Metern Tiefe und seine Bedeutung für die Gewebesättigung.", answer: "In 20 Metern Tiefe herrschen etwa 3 bar absolut. Bei idealisiert 79 % Stickstoff beträgt pN₂ ungefähr 0,79 × 3 = 2,37 bar. Der erhöhte alveoläre pN₂ vergrößert den Gradienten zu Blut und Gewebe, sodass zeitabhängig mehr Stickstoff aufgenommen wird. Beim kontrollierten Aufstieg muss er über den umgekehrten Gradienten zur Lunge zurückkehren und abgeatmet werden." },
];

export const barotraumaQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen beschreiben ein Barotrauma korrekt?", [["Es setzt eine Druckdifferenz an einem gasgefüllten Körperraum voraus", true], ["Mittelohr, Nasennebenhöhlen und Lunge können betroffen sein", true], ["Es kann beim Ab- oder Auftauchen entstehen", true], ["Es bezeichnet ausschließlich Stickstoffblasen in Geweben"]], "Barotrauma ist eine mechanische Druckschädigung; Inertgasblasen kennzeichnen dagegen die Dekompressionskrankheit.", 2),
  q(2, "Welche Folgerungen ergeben sich aus Boyle-Mariotte beim Tauchen?", [["Beim Abtauchen nimmt das Volumen eingeschlossenen Gases ab", true], ["Beim Auftauchen dehnt sich eingeschlossenes Gas aus", true], ["Verdoppelt sich der absolute Druck, halbiert sich idealisiert das Gasvolumen", true], ["Der Gasdruck bleibt unabhängig von Tiefe und Volumen konstant"]], "Bei konstanter Temperatur ist das Produkt aus Druck und Volumen konstant.", 2),
  q(3, "Welche Aussagen verbinden Dalton und Henry korrekt mit dem Tauchgang?", [["Mit dem Gesamtdruck steigen die Partialdrücke der Atemgase", true], ["Ein höherer Inertgaspartialdruck begünstigt die Lösung von Gas im Gewebe", true], ["Zu schnelle Druckentlastung kann gelöstes Inertgas ausperlen lassen", true], ["Henry erklärt unmittelbar den Riss von Alveolen durch Gasexpansion"]], "Dalton beschreibt Partialdrücke, Henry die druckabhängige Gaslösung; der Alveolarriss folgt vor allem Boyle-Mariotte.", 3),
  q(4, "Welche Zuordnungen zu den Tauchphasen treffen zu?", [["Kompression: Gefahr mangelnden Druckausgleichs im Mittelohr", true], ["Isopression: stabiler Umgebungsdruck, aber Atemgas- und Belastungsrisiken bleiben", true], ["Dekompression: Gasexpansion und mögliche Inertgasblasenbildung", true], ["Isopression: das Lungenvolumen verdoppelt sich fortlaufend"]], "Kompression, Isopression und Dekompression besitzen unterschiedliche physikalische und klinische Schwerpunkte.", 2),
  q(5, "Welche Faktoren können beim Auftauchen ein pulmonales Barotrauma begünstigen?", [["Luftanhalten", true], ["Laryngospasmus", true], ["Air-Trapping bei Emphysem oder obstruktiven Atemwegen", true], ["Ein funktionierender freier Ausatemweg bei langsamem Aufstieg"]], "Entscheidend ist die Behinderung des Entweichens expandierender Alveolarluft.", 2),
  q(6, "Welche Schritte beschreiben die Entstehung eines pulmonalen Barotraumas in richtiger Logik?", [["Sinkender Umgebungsdruck führt zur Expansion alveolärer Luft", true], ["Behinderte Exspiration erhöht den transpulmonalen Druck", true], ["Geweberiss eröffnet Wege in Pleura, Mediastinum oder Gefäße", true], ["Zuerst perlen zwingend Stickstoffblasen im Muskel aus und zerreißen danach die Lunge"]], "Das pulmonale Barotrauma ist primär eine mechanische Überdehnungsverletzung der Lunge.", 3),
  q(7, "Welche Folgen sind nach pulmonalem Barotrauma möglich?", [["Pneumothorax oder Spannungspneumothorax", true], ["Mediastinal- oder Subkutisemphysem", true], ["Arterielle Gasembolie", true], ["Isolierte venöse Thrombose als obligate Erstfolge"]], "Die Ausbreitungsrichtung der ausgetretenen Luft bestimmt das klinische Folgebild.", 2),
  q(8, "Welche Befunde sprechen nach einem raschen Notaufstieg besonders für eine arterielle Gasembolie?", [["Plötzlich einsetzende fokal-neurologische Ausfälle", true], ["Bewusstseinsstörung oder Krampfanfall kurz nach dem Auftauchen", true], ["Akute Verwirrtheit oder schlaganfallähnliche Klinik", true], ["Ausschließlich langsam zunehmender Gelenkschmerz nach vielen Stunden"]], "Die arterielle Gasembolie (AGE) manifestiert sich häufig sehr früh und neurologisch; die Dekompressionskrankheit (DCS) kann variabler und verzögert auftreten.", 3),
  q(9, "Welche Aussagen grenzen Dekompressionskrankheit und pulmonales Barotrauma korrekt ab?", [["Die Dekompressionskrankheit (DCS) entsteht durch Ausperlen gelöster Inertgase", true], ["Pulmonales Barotrauma beruht auf mechanischer Überdehnung und Geweberiss", true], ["Eine arterielle Gasembolie (AGE) kann Folge eines pulmonalen Barotraumas sein", true], ["Beide Begriffe beschreiben immer denselben Entstehungsmechanismus"]], "Die präklinische Therapie überschneidet sich, die Pathophysiologie muss dennoch klar getrennt werden.", 3),
  q(10, "Welche Maßnahmen sind bei einem symptomatischen Tauchunfall präklinisch schlüssig?", [["cABCDE und früh die höchstmögliche Sauerstoffkonzentration", true], ["Neurologischen Status und Symptomverlauf dokumentieren", true], ["Tauchmedizinische Beratung und Druckkammeroption früh koordinieren", true], ["Bei rascher Besserung unter Sauerstoff die Abklärung beenden"]], "Früher Sauerstoff kann Symptome bessern; ein Rückfall bleibt möglich und die Zielplanung wird fortgeführt.", 3),
  q(11, "Welche Informationen gehören in die tauchspezifische Anamnese?", [["Tiefe, Grundzeit und Aufstiegsgeschwindigkeit", true], ["Atemgas, Wiederholungstauchgänge und Oberflächenintervalle", true], ["Zeitpunkt, Reihenfolge und Dynamik der Symptome", true], ["Nur die maximale Tiefe, weil weitere Angaben die Druckkammerentscheidung nicht beeinflussen"]], "Das vollständige Profil der letzten Tauchgänge und der zeitliche Symptomverlauf sind entscheidend.", 2),
  q(12, "Welche Aussagen zur Zusammenarbeit am Gewässer sind richtig?", [["Ungesicherte Wasserrettung bleibt geschulten Kräften von Wasserrettung oder Feuerwehr vorbehalten", true], ["Buddy, Tauchcomputer und Ausrüstung können wichtige Informationen liefern", true], ["Rettungsdienstliche Diagnostik und Sauerstoffgabe beginnen nach sicherer Übergabe ohne vermeidbare Verzögerung", true], ["Der Rettungsdienst muss zur Anamnese selbst in den Gefahrenbereich eintauchen"]], "Eigenschutz und klare Aufgabenverteilung verhindern einen zweiten Notfall und sichern gleichzeitig medizinische Informationen.", 2),
  q(13, "Welche Aussagen zur Druckkammertherapie sind korrekt?", [["Rekompression verkleinert Gasblasen", true], ["Hyperbarer Sauerstoff verbessert Gewebeoxygenierung und Inertgaselimination", true], ["Die Dekompression erfolgt kontrolliert nach einem Behandlungsprotokoll", true], ["Eine Druckkammer ersetzt die initiale Stabilisierung von Atemweg und Kreislauf"]], "Lebensrettende Stabilisierung und frühestmögliche Sauerstoffgabe haben Vorrang; die Druckkammer ist die definitive spezifische Therapie bei DCI.", 3),
  q(14, "Welche Aussagen zur Wiederkompression im Wasser treffen für den Regelrettungsdienst zu?", [["Ein symptomatischer Taucher wird aus dem Wasser gerettet und an der Oberfläche versorgt", true], ["Improvisierte Wiederkompression im Wasser birgt Risiken durch Vigilanzverlust, Sauerstofftoxizität und Auskühlung", true], ["Der Transport zur medizinischen Abklärung wird nicht durch einen erneuten Tauchversuch ersetzt", true], ["Ein Notfallsanitäter führt ohne Spezialteam routinemäßig einen erneuten Abstieg durch"]], "In-Water-Recompression ist keine reguläre rettungsdienstliche Maßnahme.", 3),
  q(15, "Welche Befunde sprechen bei einem Tauchunfall für eine Spannungskomponente?", [["Zunehmende Dyspnoe mit einseitig deutlich abgeschwächtem Atemgeräusch", true], ["Hämodynamische Instabilität", true], ["Verschlechterung unter positiver Druckbeatmung", true], ["Isolierter symmetrischer Gelenkschmerz bei stabilem Kreislauf"]], "Ein pulmonales Barotrauma kann einen Spannungspneumothorax verursachen; die klinische Kombination entscheidet über die VFA-Entlastung.", 3),
  q(16, "Welche Aussagen gelten bei notwendiger Beatmung nach möglichem pulmonalem Barotrauma?", [["Eine vital notwendige Beatmung darf nicht unterlassen werden", true], ["Niedrigste wirksame Beatmungsdrücke und Volumina sind anzustreben", true], ["Thoraxbefund und Kreislauf werden engmaschig re-evaluiert", true], ["Hohe Drücke sind zur sicheren Vermeidung eines Pneumothorax grundsätzlich vorzuziehen"]], "Positive Druckbeatmung kann verletzte Lungenabschnitte weiter überdehnen; Oxygenierung und Ventilation bleiben dennoch vital zu sichern.", 3),
  q(17, "Welche Differenzial- und Begleitdiagnosen müssen nach einem Tauchunfall aktiv bedacht werden?", [["Ertrinkungs- oder Aspirationsgeschehen", true], ["Hypothermie", true], ["Trauma, Schlaganfall oder Krampfanfall anderer Ursache", true], ["Ein Tauchbezug schließt ein akutes Koronarsyndrom sicher aus"]], "Tauchmedizinische Diagnosen und allgemeine Notfalldiagnosen können gleichzeitig bestehen.", 3),
  q(18, "Welche Transportentscheidungen sind bei möglicher Dekompressionskrankheit oder arterieller Gasembolie (AGE) sinnvoll?", [["Druckkammer beziehungsweise tauchmedizinische Beratung frühzeitig kontaktieren", true], ["Ziel und Transportmittel mit Blick auf Stabilität und Druckexposition abstimmen", true], ["Unnötige Höhenexposition vermeiden", true], ["Jeder Hubschraubertransport ist unabhängig von Flughöhe und Kabinendruck automatisch überlegen"]], "Die schnellste geeignete Versorgung zählt; zusätzliche Druckabnahme durch Höhe kann problematisch sein und gehört in die Abstimmung.", 3),
  q(19, "Welche Aussagen zum Barotrauma des Ohres sind richtig?", [["Beim Abstieg kann fehlender Druckausgleich das Trommelfell nach innen belasten", true], ["Beim Aufstieg kann ein Reverse Block durch eingeschlossene expandierende Luft entstehen", true], ["Schmerz, Hörminderung, Schwindel oder Trommelfellruptur sind möglich", true], ["Kräftiges wiederholtes Valsalva ist bei akutem starken Ohrschmerz zwingend fortzusetzen"]], "Druckausgleich darf nicht gewaltsam erzwungen werden; vestibuläre Symptome erhöhen die Sturz- und Aspirationsgefahr.", 2),
  q(20, "Ein Taucher wird nach Notaufstieg mit Thoraxschmerz, Dyspnoe und Hemiparese übergeben. Welche Schlussfolgerungen sind begründet?", [["Pulmonales Barotrauma mit einer arteriellen Gasembolie (AGE) ist hochverdächtig", true], ["Höchstmögliche Sauerstoffkonzentration und cABCDE haben sofort Priorität", true], ["Pneumothorax und Spannungskomponente müssen wiederholt geprüft werden", true], ["Eine isolierte Dekompressionskrankheit (DCS) ist bewiesen und eine Thoraxuntersuchung deshalb entbehrlich"]], "Thorax- und neurologische Symptome unmittelbar nach Notaufstieg verbinden pulmonales Barotrauma, arterielle Gasembolie (AGE) und mögliche Spannungskomponente zu einem zeitkritischen Fall.", 3),
  q(21, "Ein Taucher atmet in 20 Metern Tiefe Pressluft. Welche Aussagen zu den vereinfachten Partialdrücken sind richtig?", [["Der absolute Umgebungsdruck beträgt ungefähr 3 bar", true], ["Der Sauerstoffpartialdruck beträgt ungefähr 0,63 bar", true], ["Der Stickstoffpartialdruck beträgt ungefähr 2,37 bar", true], ["Der Stickstoffanteil steigt dabei von 79 auf 237 Prozent"]], "Der prozentuale Gasanteil bleibt gleich. Partialdruck = Gasanteil × absoluter Umgebungsdruck; alveolär ergeben sich durch Wasserdampf und CO₂ geringfügig andere Werte.", 3),
  q(22, "Welche Aussagen erklären die Dekompressionskrankheit pathophysiologisch korrekt?", [["In der Tiefe erhöht ein hoher alveolärer pN₂ den Stickstoffgradienten zum Gewebe", true], ["Beim kontrollierten Aufstieg wird Stickstoff über Blut und Lunge abgegeben", true], ["Bei zu raschem Druckabfall kann Übersättigung mit Blasenbildung entstehen", true], ["Die Dekompressionskrankheit (DCS) setzt zwingend eine vorherige Alveolarruptur voraus"]], "Dekompressionskrankheit (DCS) entsteht aus zuvor gelöstem Inertgas. Eine Alveolarruptur gehört dagegen zum pulmonalen Barotrauma und kann eine arterielle Gasembolie (AGE) verursachen.", 3),
];
