import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct?: boolean];

function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  return { id: `beckentrauma-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: options.map(([text, correct]) => ({ text, correct })), source, difficulty };
}

export const beckentraumaFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "beckentrauma-card-01", area: "Definition", question: "Definieren Sie ein Beckentrauma und grenzen Sie Kontusion, stabile und instabile Beckenringverletzung voneinander ab.", answer: "Beckentrauma bezeichnet eine unfallbedingte Verletzung des knöchernen Beckens und/oder seiner Band-, Gefäß-, Nerven- und Organstrukturen. Eine Kontusion verletzt Weichteile ohne nachgewiesene Fraktur. Bei stabiler Verletzung bleibt die Lastübertragung des Beckenrings erhalten; instabile Ringverletzungen verlieren Rotations- und/oder Vertikalstabilität und können mit massiver Blutung einhergehen." },
  { id: "beckentrauma-card-02", area: "Anatomie", question: "Aus welchen Knochen besteht der Beckenring und wo liegen seine wichtigsten Verbindungen?", answer: "Beide Ossa coxae bestehen aus Os ilium, Os ischii und Os pubis. Dorsal verbinden die Iliosakralgelenke die Hüftbeine mit dem Os sacrum, ventral verbindet die Symphyse beide Schambeine. Am Acetabulum treffen Darm-, Sitz- und Schambein zusammen." },
  { id: "beckentrauma-card-03", area: "Gefäße", question: "Warum kann eine Beckenringverletzung trotz geringer äußerer Blutung zum hämorrhagischen Schock führen?", answer: "Frakturflächen, venöse Plexus und arterielle Äste können in den großen intrapelvinen und retroperitonealen Raum bluten. Der Blutverlust bleibt äußerlich unsichtbar; sinkende Vorlast und vermindertes Herzzeitvolumen führen zu Gewebehypoperfusion, Schock und Koagulopathie." },
  { id: "beckentrauma-card-04", area: "Mechanismen", question: "Ordnen Sie laterale Kompression, anteroposteriore Kompression und vertikale Scherung den typischen Instabilitäten zu.", answer: "Laterale Kompression führt zur Innenrotation einer Beckenhälfte. Anteroposteriore Kompression kann die Symphyse und den hinteren Ring aufsprengen (Open Book) und verursacht Rotationsinstabilität. Vertikale Scherung verschiebt eine Beckenhälfte kranial und verursacht kombinierte Rotations- und Vertikalinstabilität." },
  { id: "beckentrauma-card-05", area: "Symptome", question: "Welche Befunde stützen die Arbeitsdiagnose einer relevanten Beckenringverletzung?", answer: "Passender Mechanismus, Becken-, Hüft-, Kreuzbein- oder Leistenschmerz, sichtbare Deformität, Beinlängendifferenz oder Rotationsfehler, Hämatome oder Wunden, perineale Ekchymosen, Blut aus Urethra, Vagina oder Anus sowie Schockzeichen. Fehlende Einzelzeichen schließen die Verletzung nicht aus." },
  { id: "beckentrauma-card-06", area: "S-KIPS / VFA", question: "Wie verbinden Sie S-KIPS mit der Thüringer VFA 32?", answer: "S-KIPS setzt Schock beziehungsweise hämodynamische Instabilität voran und ergänzt Kinematik, Inspektion, vorsichtige seitliche Palpation und Schmerz. Die Thüringer VFA 32 fordert Anhaltspunkte für eine Beckenfraktur (KISS) und hämodynamische Instabilität. Damit ist nicht der Mechanismus allein, sondern die Kombination aus Instabilität und mindestens einem Verletzungshinweis entscheidend." },
  { id: "beckentrauma-card-07", area: "Beckenschlinge", question: "Beschreiben Sie Anlage, Kontrollen und wichtige Verbote bei der Beckenschlinge.", answer: "Schlinge auf Höhe der Trochanteren anlegen und sicher schließen; Beine nur situationsgerecht und schonend positionieren. Neurologie und Gefäßstatus vor und nach Anlage sowie im Verlauf prüfen, festen Sitz kontrollieren und die Schlinge präklinisch nicht öffnen. Keine wiederholte Federungs- oder Kompressionsprüfung des Beckens." },
  { id: "beckentrauma-card-08", area: "Differenzialdiagnose", question: "Wie unterscheiden Sie eine isolierte Schenkelhalsfraktur von einer indizierten Beckenschlinge?", answer: "Eine Schenkelhalsfraktur zeigt häufig Leisten-/Hüftschmerz, Belastungsunfähigkeit sowie ein verkürztes, außenrotiertes Bein, besonders nach Niedrigenergietrauma älterer Menschen. Sie allein ist keine Regelindikation für die Schlinge. VFA 32 verlangt Hinweise auf Beckenfraktur plus hämodynamische Instabilität." },
  { id: "beckentrauma-card-09", area: "Erstmaßnahmen", question: "Strukturieren Sie die ersten Maßnahmen beim hämodynamisch instabilen Beckentrauma.", answer: "Eigenschutz, Unfallmechanismus und cABCDE; äußere Blutung kontrollieren, Sauerstoff/Beatmung nach Befund, Kreislauf und große Blutungsräume beurteilen, VFA-Indikation zur Beckenschlinge prüfen, früh Notarzt/RTH und Traumazentrum organisieren, großlumigen i.v.- oder bei Versagen i.o.-Zugang etablieren, Wärmeerhalt, zielgerichtete Volumentherapie und Load-go-and-treat mit wiederholter Reevaluation." },
  { id: "beckentrauma-card-10", area: "Kreislauf", question: "Welche Blutdruckziele nennt der Thüringer Traumaalgorithmus?", answer: "Bei nicht beherrschbarer Blutung RRsys etwa 80 mmHg. Bei führendem oder isoliertem SHT mindestens 90 mmHg. Bei Schwangeren ab dem fünften Monat 120 mmHg; bei Kindern etwa 70 + 2 × Alter. Das Muster der Begleitverletzungen entscheidet, welches Ziel gilt." },
  { id: "beckentrauma-card-11", area: "Tranexamsäure", question: "Nennen Sie Indikation, Wirkung, Dosis und Zubereitung von Tranexamsäure nach Thüringer VFA.", answer: "Bei Erwachsenen mit lebensbedrohlicher Blutung und/oder hämorrhagischem Schock: 1 g als Kurzinfusion über 10 Minuten. B2A: 1 g = 10 ml aus 500 mg/5 ml plus 90 ml NaCl 0,9 %. Tranexamsäure hemmt die Aktivierung von Plasminogen zu Plasmin und stabilisiert bestehendes Fibrin; sie ersetzt keine Blutungskontrolle." },
  { id: "beckentrauma-card-12", area: "Esketamin", question: "Leiten Sie den Erwachsenenpfad für Esketamin bei starkem traumatischem Schmerz her.", answer: "Beatmungsbereitschaft, EKG/RR, angepasste O₂-Gabe und NRS-Dokumentation. VFA 36: 1 mg Midazolam i.v., danach Esketamin 0,2 mg/kgKG langsam i.v. aus 5 mg/ml. Nach fünf Minuten bei unzureichender Wirkung 0,1 mg/kgKG; nach weiterer Kontrolle kann gemäß Algorithmus erneut die halbe Initialdosis folgen." },
  { id: "beckentrauma-card-13", area: "Morphin", question: "Wie wird Morphin nach Thüringer VFA 38 vorbereitet und dosiert?", answer: "10 mg/1 ml plus 9 ml NaCl 0,9 % ergeben 1 mg/ml. Ab 40 kg langsame i.v.-Gabe nach Tabelle: 40/50 kg 2 mg, 60/70 kg 3 mg, 80/90 kg 4 mg, 100/110 kg 5 mg. Nach fünf Minuten bei Bedarf halbe Initialdosis; insgesamt maximal 10 mg, mit fortlaufender Atem-, Kreislauf- und NRS-Kontrolle." },
  { id: "beckentrauma-card-14", area: "Prüfungsfall", question: "Ein Patient nach Motorradunfall hat Beckenschmerz, RRsys 78 mmHg und ein verkürztes außenrotiertes Bein. Begründen Sie Ihre Prioritäten.", answer: "cABCDE und Schockbehandlung haben Vorrang. Mechanismus, Beckenschmerz und Instabilität erfüllen die Schwelle zur Beckenschlinge; die Fehlstellung kann zusätzlich für eine proximale Femurverletzung sprechen. Keine provozierende Beckenprüfung, pDMS vor/nach Schlinge, Ziel-RR bei nicht beherrschbarer Blutung etwa 80 mmHg, TXA-Indikation prüfen sowie sofortige Transport- und Traumazentrumplanung." },
];

export const beckentraumaQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen beschreiben den Beckenring anatomisch korrekt?", [["Die beiden Hüftbeine sind dorsal über die Iliosakralgelenke mit dem Kreuzbein verbunden", true], ["Ventral verbindet die Symphyse die beiden Schambeine", true], ["Os ilium, Os ischii und Os pubis beteiligen sich am Acetabulum", true], ["Das Foramen obturatum bildet die Gelenkpfanne des Hüftkopfs"]], "Der Beckenring wird ventral durch die Symphyse und dorsal durch Sakrum und Iliosakralgelenke geschlossen; die drei Anteile des Os coxae treffen am Acetabulum zusammen.", 2),
  q(2, "Welche Strukturen können bei einer instabilen Beckenringverletzung die Blutungsquelle bilden?", [["Venöse Beckenplexus", true], ["Frakturflächen des spongiösen Knochens", true], ["Äste des iliakalen Gefäßsystems", true], ["Ausschließlich oberflächliche Hautgefäße"]], "Verletzte Venenplexus, Knochenflächen und arterielle Gefäße können in den intrapelvinen oder retroperitonealen Raum bluten.", 2),
  q(3, "Welche Zuordnungen zwischen Mechanismus und Verletzungsmuster sind plausibel?", [["Anteroposteriore Kompression kann eine Open-Book-Verletzung erzeugen", true], ["Vertikale Scherung kann eine Beckenhälfte kranial verschieben", true], ["Laterale Kompression kann eine Innenrotation der Beckenhälfte bewirken", true], ["Vertikale Scherung führt regelhaft nur zu einer stabilen isolierten Kontusion"]], "Die Kraftrichtung hilft, Rotations- und Vertikalinstabilität sowie mögliche Begleitverletzungen vorauszudenken.", 2),
  q(4, "Welche Befunde stützen den Verdacht auf eine relevante Beckenverletzung?", [["Beckenschmerz mit passendem Mechanismus", true], ["Perineale Ekchymose oder Blutung aus Urethra, Vagina oder Anus", true], ["Beinlängendifferenz oder Rotationsfehlstellung", true], ["Ein einzelner normwertiger Blutdruck schließt eine innere Blutung aus"]], "Mechanismus, Schmerz, sichtbare Zeichen und hämodynamischer Verlauf werden gemeinsam beurteilt; ein kompensierter Schock kann anfangs normotensiv sein.", 2),
  q(5, "Welche Aussagen zur präklinischen Beckenuntersuchung sind richtig?", [["Inspektion und Spontanschmerz werden erfasst", true], ["Eine notwendige Palpation erfolgt vorsichtig und seitlich", true], ["Wiederholtes kräftiges Komprimieren kann eine Blutung oder Instabilität verschlimmern", true], ["Eine negative Federungsprüfung schließt eine Fraktur sicher aus"]], "Das Becken wird nicht durch wiederholte provozierende Stabilitätsprüfungen untersucht; indirekte Zeichen, Schmerz und Verlauf sind entscheidend.", 2),
  q(6, "Wann erfüllt ein erwachsener Patient die Thüringer Indikation zur Beckenschlinge?", [["Es bestehen Anhaltspunkte für eine Beckenfraktur", true], ["Zusätzlich liegt hämodynamische Instabilität vor", true], ["Kinematik, sichtbare Zeichen oder Beckenschmerz können den Frakturhinweis liefern", true], ["Jeder Sturz aus Standhöhe genügt unabhängig von Befund und Kreislauf"]], "VFA 32 verbindet Anhaltspunkte für Beckenfraktur (KISS) mit hämodynamischer Instabilität.", 3),
  q(7, "Welche Aussagen verbinden S-KIPS fachlich mit der Thüringer VFA?", [["Das erste S steht für Schock beziehungsweise hämodynamische Instabilität", true], ["Zu Schock muss mindestens ein Hinweis aus Kinematik, Inspektion, Palpation oder Schmerz hinzukommen", true], ["Der Mechanismus allein ist keine ausreichende Schlingenindikation", true], ["S-KIPS verlangt eine kräftige anteroposteriore Kompressionsprüfung"]], "S-KIPS betont die hämodynamische Instabilität als Voraussetzung. Das passt zur VFA, die Instabilität plus Frakturhinweis verlangt.", 3),
  q(8, "Welche Schritte gehören zur sicheren Anlage und Kontrolle einer Beckenschlinge?", [["Die Schlinge liegt auf Höhe der Trochanteren", true], ["Neurologie und Gefäßstatus werden vor und nach Anlage sowie im Verlauf geprüft", true], ["Sitz und Festigkeit werden kontrolliert, die Schlinge präklinisch nicht geöffnet", true], ["Die Schlinge wird über den Beckenkämmen möglichst hoch positioniert"]], "Die trochantere Anlage verkleinert den Beckenraum zielgerichtet; Kontrollen und das Verbot der präklinischen Öffnung stehen in VFA 32.", 3),
  q(9, "Welche Befunde sprechen eher für eine isolierte Schenkelhalsfraktur als für eine instabile Beckenringverletzung?", [["Älterer Patient nach Niedrigenergietrauma", true], ["Leisten- oder Hüftschmerz mit Belastungsunfähigkeit", true], ["Verkürztes, außenrotiertes Bein bei zunächst stabilem Kreislauf", true], ["Hämodynamische Instabilität mit perinealer Blutung spricht typischerweise für eine unkomplizierte isolierte Schenkelhalsfraktur"]], "Die typische Schenkelhalsfraktur zeigt lokale Hüftzeichen; Schock und urogenitale/perineale Zeichen lenken zum komplexen Beckentrauma.", 3),
  q(10, "Welche Aussagen zur Beckenschlinge bei vermuteter Schenkelhalsfraktur sind korrekt?", [["Eine isolierte Schenkelhalsfraktur ist keine Regelindikation", true], ["Bei zusätzlichem Verdacht auf Beckenringverletzung und Instabilität wird VFA 32 geprüft", true], ["Hochrasanzmechanismus und weitere Beckenzeichen verändern die Einordnung", true], ["Ein außenrotiertes Bein allein verpflichtet immer zur Beckenschlinge"]], "Die Schlinge richtet sich nach Beckenfrakturhinweis plus hämodynamischer Instabilität, nicht nach dem Einzelzeichen der proximalen Femurfraktur.", 3),
  q(11, "Welche Konsequenzen folgen aus der Schockpathophysiologie beim Beckentrauma?", [["Sinkende Vorlast kann das Herzzeitvolumen vermindern", true], ["Blasse kühle Haut und verlängerte Rekapillarisierung können frühe Kompensationszeichen sein", true], ["Hypothermie und Azidose können die Gerinnung weiter verschlechtern", true], ["Ein noch normaler RRsys beweist eine ausreichende Organperfusion"]], "Verdeckter Blutverlust kann lange kompensiert bleiben; Trend, Haut, Puls, Bewusstsein und Rekapillarisierung ergänzen den Blutdruck.", 3),
  q(12, "Ein instabiler Patient mit vermuteter nicht beherrschbarer Beckenblutung hat kein führendes SHT. Welche Aussagen passen zum Traumaalgorithmus?", [["Die Volumentherapie erfolgt reduziert mit Ziel RRsys etwa 80 mmHg", true], ["Beckenschlinge und definitive Blutungskontrolle dürfen nicht durch das Erreichen eines Normaldrucks verzögert werden", true], ["Wärmeerhalt und schneller Transport ins geeignete Traumazentrum laufen parallel", true], ["Ein RRsys von 120 mmHg ist in jeder Traumakonstellation das verbindliche Ziel"]], "L2 nennt bei nicht beherrschbarer Blutung permissive Hypotonie um 80 mmHg; Sonderziele gelten bei führendem SHT, Schwangerschaft und Kindern.", 3),
  q(13, "Welche Aussagen zu Tranexamsäure entsprechen der Thüringer VFA?", [["Indikation sind lebensbedrohliche Blutungen und/oder hämorrhagischer Schock beim Erwachsenen", true], ["Die Dosis beträgt 1 g als Kurzinfusion über 10 Minuten", true], ["10 ml Tranexamsäure werden mit 90 ml NaCl 0,9 % zubereitet", true], ["Tranexamsäure ersetzt die mechanische Stabilisierung und definitive Blutungskontrolle"]], "L2 und B2A nennen 1 g in 100 ml Gesamtvolumen über 10 Minuten; die Antifibrinolyse ergänzt, aber ersetzt keine Blutungskontrolle.", 3),
  q(14, "Welche Aussagen erklären die Wirkung von Tranexamsäure?", [["Sie hemmt die Aktivierung von Plasminogen zu Plasmin", true], ["Sie stabilisiert dadurch bereits gebildetes Fibrin", true], ["Zu schnelle Gabe kann einen Blutdruckabfall begünstigen", true], ["Sie erzeugt unmittelbar einen mechanischen Verschluss zerrissener Beckengefäße"]], "Tranexamsäure wirkt antifibrinolytisch; mechanische und operative Blutungskontrolle bleiben notwendig.", 3),
  q(15, "Welche Aussagen gehören zum Erwachsenenpfad Esketamin bei traumabedingtem starkem Schmerz?", [["Vor der Esketamingabe nennt VFA 36 1 mg Midazolam i.v.", true], ["Esketamin wird langsam mit 0,2 mg/kgKG i.v. initial gegeben", true], ["Die vorbereitete Konzentration beträgt 5 mg/ml", true], ["Beatmungsbereitschaft und Kreislaufüberwachung entfallen bei erhaltener Spontanatmung"]], "VFA 36 verbindet Midazolam, gewichtsbezogenes Esketamin, NRS-Kontrollen, Beatmungsbereitschaft, EKG/RR und Monitoring.", 3),
  q(16, "Ein 75-kg-Patient erhält Esketamin nach VFA 36 aus 5 mg/ml. Welche Rechnungen stimmen?", [["Die Initialdosis beträgt 15 mg", true], ["Das Initialvolumen beträgt 3 ml", true], ["Eine halbe Initialdosis beträgt 7,5 mg beziehungsweise 1,5 ml", true], ["Die Initialdosis beträgt 37,5 mg, weil 0,5 mg/kg verwendet wird"]], "75 × 0,2 mg/kg = 15 mg; 15 mg ÷ 5 mg/ml = 3 ml. Die halbe Initialdosis beträgt 7,5 mg = 1,5 ml.", 3),
  q(17, "Welche Aussagen zum Morphinpfad sind richtig?", [["Morphin wird aus 10 mg/1 ml mit 9 ml NaCl auf 1 mg/ml verdünnt", true], ["Die Initialdosis folgt einer Gewichtstabelle und wird langsam i.v. gegeben", true], ["Nach fünf Minuten ist bei Bedarf die halbe Initialdosis vorgesehen; insgesamt maximal 10 mg", true], ["Jede Gewichtsstufe erhält initial 0,2 mg/kg Morphin"]], "VFA 38 nutzt feste Gewichtsgruppen, nicht eine frei interpolierte mg/kg-Dosis.", 3),
  q(18, "Ein 90-kg-Patient erhielt 4 mg Morphin aus 1 mg/ml. Welche Aussagen treffen zu?", [["Die Initialgabe entspricht 4 ml", true], ["Nach fünf Minuten wären bei unzureichender Wirkung 2 mg beziehungsweise 2 ml die halbe Tabellendosis", true], ["Atmung, Vigilanz, RR, EKG und NRS bleiben zu überwachen", true], ["Die vorbereitete Spritze enthält 10 mg Morphin pro Milliliter"]], "Für 90 kg nennt VFA 38 initial 4 mg; bei 1 mg/ml sind das 4 ml. Die Wiederholung ist die halbe Tabellendosis.", 3),
  q(19, "Welche Entscheidungen zeigen bei einem kritischen Beckentrauma die richtige Zeitpriorität?", [["Notarzt/RTH und Traumazentrum werden früh parallel organisiert", true], ["Lebensrettende Maßnahmen erfolgen während der Transportvorbereitung", true], ["Die Prähospitalzeit soll einschließlich Anfahrt und Transport unter 60 Minuten bleiben", true], ["Die Abfahrt wartet bis zur vollständigen Schmerzfreiheit und endgültigen Frakturklassifikation"]], "L2 fordert beim zeitkritischen Patienten Load-go-and-treat, frühe Zielklinikplanung und eine Prähospitalzeit unter 60 Minuten.", 3),
  q(20, "Welche Angaben gehören in die Übergabe eines Beckentraumas?", [["Mechanismus, Zeitpunkt, vermutete Kraftrichtung und Begleitverletzungen", true], ["Kreislauftrend, Schockzeichen, Beckenbefunde und pDMS vor/nach Schlinge", true], ["Zugänge, Flüssigkeit, TXA und Analgesie mit Dosis, Zeitpunkt und Wirkung", true], ["Nur die Diagnosebezeichnung, weil Schlinge und Medikamente in der Klinik sichtbar sind"]], "Eine hochwertige Übergabe verbindet Mechanismus, Befunde, Dynamik, Interventionen und Wirkung mit der gewählten Transportpriorität.", 3),
];
