import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function BeckentraumaLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>Beckentrauma</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;

  return <article className="lesson-article rippenfraktur-lesson polytrauma-lesson beckentrauma-lesson">
    <div className="lesson-intro"><p className="lead">Beim Beckentrauma kann äußerlich wenig zu sehen sein, während im Becken und Retroperitoneum eine lebensbedrohliche Blutung fortschreitet. Entscheidend sind Kreislauftrend, schonende Untersuchung, korrekte Schlingenindikation und ein schneller Transport zur definitiven Blutungskontrolle.</p></div>

    {section("01", "Definition", <><p>Ein <b>Beckentrauma</b> ist eine unfallbedingte Verletzung des knöchernen Beckens und/oder seiner Band-, Gefäß-, Nerven- und Organstrukturen. Es reicht von der Kontusion über stabile Frakturen bis zur rotations- oder vertikal instabilen Beckenringverletzung.</p><aside className="red-flags"><span>!</span><div><small>Killer</small><h3>Verdeckte Hämorrhagie</h3><p>Eine instabile Beckenringverletzung kann eine massive innere Blutung und einen hämorrhagischen Schock verursachen. Ein einzelner zunächst normaler Blutdruck schließt das nicht aus.</p></div></aside></>)}

    {section("02", "Anatomie und Physiologie", <><p>Der Beckenring verbindet Rumpf und untere Extremitäten. Jedes Hüftbein (<b>Os coxae</b>) entsteht aus Darmbein, Sitzbein und Schambein; alle drei beteiligen sich am Acetabulum. Dorsal verbinden die Iliosakralgelenke beide Hüftbeine mit dem Kreuzbein, ventral schließt die Symphyse den Ring.</p><div className="pulmo-anatomy-grid">{[["Os ilium", "Darmbein", "Trägt den Darmbeinkamm und bildet den kranialen Anteil des Hüftbeins."], ["Os ischii", "Sitzbein", "Bildet den dorsokaudalen Anteil mit Sitzbeinhöcker und Ischiasdorn."], ["Os pubis", "Schambein", "Bildet den ventralen Ring und verbindet sich in der Symphyse mit der Gegenseite."], ["Acetabulum", "Hüftpfanne", "Gelenkfläche für den Femurkopf; alle drei Hüftbeinteile wirken an ihrer Bildung mit."], ["Art. sacroiliaca", "Iliosakralgelenk", "Überträgt Last zwischen Wirbelsäule und Becken; kräftige Bänder sichern den hinteren Ring."], ["Pelvis minor", "Kleines Becken", "Enthält Blase, Rektum und geschlechtsspezifische Organe; Verletzungen können komplex sein."]].map(([tag,title,text]) => <div key={title}><small>{tag}</small><b>{title}</b><p>{text}</p></div>)}</div><Figure src="/lessons/beckentrauma/becken-anterior.png" alt="Beschriftete Vorderansicht des knöchernen Beckens" caption="Knöchernes Becken · Vorderansicht" wide /><Figure src="/lessons/beckentrauma/becken-posterior.png" alt="Beschriftete Rückansicht des knöchernen Beckens" caption="Knöchernes Becken · Rückansicht" wide /><h3>Gefäßversorgung und Blutungsraum</h3><p>Die Aorta teilt sich in die Arteriae iliacae communes, anschließend in innere und äußere Beckenarterien. Die Venen verlaufen weitgehend parallel; zusätzlich liegen venöse Plexus vor dem Kreuzbein. Frakturflächen, Venenplexus und arterielle Äste können in das Becken und Retroperitoneum bluten.</p></>)}

    {section("03", "Ursachen, Entstehung und Pathophysiologie", <><p>Typisch sind Verkehrsunfälle, ungeschützte Verkehrsteilnehmende, Überroll-, Einklemm-, Verschüttungs- und Explosionstrauma sowie Stürze aus Höhe. Bei älteren Menschen können Osteoporose und ein Sturz aus niedriger Höhe ausreichen.</p><h3>Kraftrichtung und Instabilität</h3><div className="pulmo-risk-grid"><div><b>Laterale Kompression</b><p>Innenrotation einer Beckenhälfte; das Verletzungsspektrum reicht von stabil bis komplex.</p></div><div><b>Anteroposteriore Kompression</b><p>Außenrotation mit Symphysensprengung und möglicher Beteiligung des hinteren Rings: Open Book.</p></div><div><b>Vertikale Scherung</b><p>Kraniale Verschiebung einer Beckenhälfte; rotations- und vertikal instabil.</p></div><div><b>Niedrigenergie</b><p>Fragilitätsfrakturen bei Osteoporose können klinisch weniger spektakulär erscheinen.</p></div></div><Figure src="/lessons/beckentrauma/verletzungsmechanismen.png" alt="Schematische Darstellung von lateraler Kompression, Open-Book-Verletzung und vertikaler Scherung" caption="Verletzungsmechanismen aus der Themenunterlage" wide /><h3>Schockkette</h3><div className="pulmo-vfa-flow"><div><span>01</span><b>Blutung</b><small>Frakturflächen, Venenplexus oder arterielle Äste bluten in einen großen verdeckten Raum.</small></div><div><span>02</span><b>Vorlast sinkt</b><small>Das venöse Rückstromvolumen und anschließend das Herzzeitvolumen nehmen ab.</small></div><div><span>03</span><b>Kompensation</b><small>Tachykardie und Vasokonstriktion zentralisieren den Kreislauf; Blutdruck kann zunächst erhalten sein.</small></div><div><span>04</span><b>Dekompensation</b><small>Gewebehypoxie, Azidose, Hypothermie und Koagulopathie verstärken Blutung und Organversagen.</small></div></div><Figure src="/lessons/beckentrauma/beckenfrakturen.png" alt="Beckenzeichnung mit Beispielen leichter und schwerer Beckenfrakturen" caption="Frakturverläufe am Beckenring · Themenunterlage" wide /></>)}

    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", <><div className="rib-fracture-grid">{[["Schmerz", "Becken, Hüfte, Leiste, Kreuzbein oder Lendenwirbelsäule; Bewegung häufig deutlich eingeschränkt."], ["Äußere Zeichen", "Hämatome, Abschürfungen, Wunden, Deformität oder perineale Ekchymose."], ["Beinstellung", "Beinlängendifferenz, Außen- oder Innenrotation; mögliche Begleitverletzung von Hüfte oder Femur."], ["Komplexverletzung", "Blut aus Urethra, Vagina oder Anus sowie Genitalhämatom sprechen für urogenitale oder viszerale Beteiligung."], ["Schock", "Tachykardie, Tachypnoe, blasse-kalte Haut, verlängerte Rekapillarisierung, schwache Pulse, Unruhe oder Bewusstseinsänderung."], ["Verlauf", "Fallender RR, zunehmender Schmerz oder neue Vigilanzstörung sind dynamische Warnzeichen."]].map(([title,text]) => <div key={title}><b>{title}</b><span>{text}</span></div>)}</div><aside className="diagnostic-boundary"><span>!</span><div><b>Keine provozierende Stabilitätsprüfung</b><p>Becken nicht wiederholt kräftig komprimieren oder „federn“. Inspektion, Spontanschmerz, vorsichtige seitliche Palpation, Mechanismus und Kreislauftrend liefern die entscheidenden Informationen.</p></div></aside></>)}

    {section("05", "Komplikationen und Gefahren", <><div className="pulmo-risk-grid"><div><b>Hämorrhagischer Schock</b><p>Verdeckter Blutverlust mit Hypoperfusion, Azidose und Kreislaufversagen.</p></div><div><b>Urogenitalverletzung</b><p>Blase, Urethra und Genitalorgane können bei komplexen Ringverletzungen mitbetroffen sein.</p></div><div><b>Nerven- und Gefäßschaden</b><p>Lumbosakraler Plexus, N. ischiadicus und iliakale Gefäße sind gefährdet.</p></div><div><b>Begleitverletzungen</b><p>Abdomen, Thorax, Wirbelsäule, SHT und lange Röhrenknochen aktiv mituntersuchen.</p></div></div><p>Weitere Gefahren sind offene Fraktur mit Infektion, abdominelles Kompartmentsyndrom, thromboembolische Komplikationen und sekundäre Organschäden. Das Becken ist bei jungen Betroffenen nach Hochrasanztrauma häufig nur ein Teil eines Polytraumas.</p></>)}

    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", <div className="material-chips">{["PSA und Wärmeerhalt", "Monitoring / EKG / RR / SpO₂", "Sauerstoff / Beatmung / Absaugung", "Großlumiger i.v.- und i.o.-Zugang", "Beckenschlinge", "Schaufeltrage / Vakuummatratze", "Blutungskontrolle", "Tranexamsäure", "Esketamin / Midazolam", "Morphin", "Infusionslösung", "Reanimationsbereitschaft"].map(item => <span key={item}>{item}</span>)}</div>)}

    {section("07", "Erstmaßnahmen, Diagnostik und Anamnese", <><div className="pulmo-care-grid"><div><span>c</span><b>Kritische Blutung</b><small>Äußere Blutung sofort stillen; inneren Blutungsraum mitdenken.</small></div><div><span>AB</span><b>Atemweg &amp; Atmung</b><small>HWS-Bezug, Oxygenierung, Thoraxverletzung und Beatmungsbedarf prüfen.</small></div><div><span>C</span><b>Kreislauf</b><small>Pulse, Rekap, Haut, RR-Trend, große Blutungsräume und Zugangsstrategie.</small></div><div><span>DE</span><b>Neurologie &amp; Exploration</b><small>GCS, Pupillen, BZ, schonende Ganzkörperuntersuchung und Wärmeerhalt.</small></div></div><h3>S-KIPS als Denkstütze</h3><div className="pulmo-vfa-flow"><div><span>S</span><b>Schock</b><small>Hämodynamische Instabilität ist die Voraussetzung der Schlingenentscheidung.</small></div><div><span>K</span><b>Kinematik</b><small>Unfallenergie und Kraftrichtung erhöhen oder senken die Wahrscheinlichkeit.</small></div><div><span>I</span><b>Inspektion</b><small>Deformität, Wunden, Hämatome, Beinlänge, Rotation und Blutungen.</small></div><div><span>PS</span><b>Palpation / Schmerz</b><small>Nur vorsichtig seitlich; Spontan- und Druckschmerz ohne provozierendes Federn.</small></div></div><p><b>Thüringer Prüfungsformulierung:</b> VFA 32 nennt Anhaltspunkte für Beckenfraktur nach KISS <em>und</em> hämodynamische Instabilität. S-KIPS macht dieselbe Sicherheitslogik leichter sichtbar: Schock plus mindestens ein Verletzungshinweis.</p><h3>SAMPLERS · beckenspezifisch</h3><div className="samplers-grid">{[["S · Symptome", "Schmerz, Blutung, Schwindel, Verlauf"], ["A · Allergien", "Medikamente und Materialien"], ["M · Medikamente", "Antikoagulation, Plättchenhemmer, Betablocker"], ["P · Vorgeschichte", "Osteoporose, Prothesen, Gerinnung, frühere OP"], ["L · Letzte Aufnahme", "Essen, Trinken, Substanzen"], ["E · Ereignis", "Kraft, Richtung, Höhe, Geschwindigkeit, Zeit"], ["R · Risiken", "Einklemmung, Schwangerschaft, Begleitverletzung"], ["S · Schwangerschaft", "Woche und Linksseitenentlastung" ]].map(([label,text]) => <p key={label}><b>{label}</b>{text}</p>)}</div><h3>Beckenschlinge · VFA 32</h3><ul className="script-list"><li>Indikation: Frakturhinweis plus hämodynamische Instabilität.</li><li>Schlinge auf Höhe der <b>Trochanteren</b>, nicht über den Beckenkämmen.</li><li>Neurologie und Gefäßstatus vor und nach Anlage sowie im Verlauf prüfen.</li><li>Sichere feste Anlage kontrollieren und präklinisch nicht öffnen.</li></ul></>)}

    {section("08", "Differenzialdiagnosen und Entscheidungsfindung", <><div className="differential-grid">{["Beckenprellung", "Schenkelhalsfraktur", "Femurkopf- oder Acetabulumfraktur", "Hüftluxation", "Femurschaftfraktur", "Abdominal- oder Retroperitonealtrauma", "Urogenitalverletzung", "Wirbelsäulenverletzung", "Lumboischialgie"].map(item => <span key={item}>{item}</span>)}</div><div className="pulmo-compare"><div><small>Isolierte Schenkelhalsfraktur</small><h3>Lokal schmerzhaft</h3><p>Häufig ältere Person nach Sturz, Leisten-/Hüftschmerz, Belastungsunfähigkeit sowie verkürztes außenrotiertes Bein.</p><span>Keine routinemäßige Beckenschlinge nur wegen dieser Diagnose; schonend lagern, polstern, Analgesie und unfallchirurgische Zielklinik.</span></div><div><small>Instabile Beckenringverletzung</small><h3>Systemisch bedrohlich</h3><p>Passender Mechanismus oder Beckenzeichen treffen auf hämodynamische Instabilität und mögliche Begleitverletzungen.</p><span>Beckenschlinge, Schockbehandlung und sofortige Traumazentrumplanung laufen parallel.</span></div></div><h3>Prüfungsfallen</h3><ul className="script-list"><li><b>Normaler Anfangs-RR:</b> schließt kompensierten Blutverlust nicht aus.</li><li><b>Mechanismus allein:</b> reicht nach VFA 32 nicht; Instabilität muss hinzukommen.</li><li><b>Außenrotiertes Bein:</b> kann eine proximale Femurfraktur anzeigen und ist nicht allein Beweis einer instabilen Beckenfraktur.</li><li><b>Schmerzfreiheit nach Analgesie:</b> ändert die Blutungs- und Transportpriorität nicht.</li><li><b>Schlinge öffnen:</b> präklinisch nicht zur „Kontrolle“ lösen.</li></ul></>)}

    {section("09", "Weitere Maßnahmen", <><div className="pulmo-vfa-flow"><div><span>L2</span><b>Trauma</b><small>Load-go-and-treat, Zugang, Wärmeerhalt, Zielblutdruck, TXA und Traumazentrum.</small></div><div><span>32</span><b>Beckenschlinge</b><small>Frakturhinweis plus hämodynamische Instabilität; pDMS/Neurologie kontrollieren.</small></div><div><span>35</span><b>Schmerzalgorithmus</b><small>Ab NRS ≥ 5 Ursache und OPQRST, dann lokaler Morphin- oder Esketaminpfad.</small></div><div><span>B2</span><b>Zubereitung</b><small>TXA-Infusion sowie eindeutig beschriftete Esketamin- und Morphinlösungen.</small></div></div><h3>Kreislauf und Tranexamsäure</h3><div className="reading-columns"><div><h3>Zielblutdruck</h3><p>Nicht beherrschbare Blutung ohne führendes SHT: RRsys etwa 80 mmHg. Führendes/isoliertes SHT: mindestens 90 mmHg. Sonderziele für Schwangerschaft und Kinder beachten.</p></div><div><h3>TXA</h3><p>Erwachsene mit lebensbedrohlicher Blutung und/oder hämorrhagischem Schock: 1 g als Kurzinfusion über 10 Minuten. B2A: 10 ml Wirkstoff plus 90 ml NaCl 0,9 %.</p></div></div><p><b>Wirkung:</b> Tranexamsäure hemmt die Aktivierung von Plasminogen zu Plasmin und stabilisiert dadurch bestehendes Fibrin. Sie ergänzt die Blutungskontrolle, erzeugt aber keinen mechanischen Gefäßverschluss.</p><h3>Analgesie</h3><div className="reading-columns"><div><h3>Esketamin · VFA 36</h3><p>Erwachsene: 1 mg Midazolam i.v., danach 0,2 mg/kgKG Esketamin langsam i.v. Bei unzureichender Wirkung nach fünf Minuten 0,1 mg/kgKG; weitere Kontrolle und Wiederholung nach Originalalgorithmus.</p></div><div><h3>Morphin · VFA 38</h3><p>Langsam i.v. nach Gewichtstabelle. Nach fünf Minuten bei Bedarf halbe Initialdosis; insgesamt maximal 10 mg. NRS, Atmung, Vigilanz und Kreislauf fortlaufend kontrollieren.</p></div></div><p>Die Medikamentenauswahl richtet sich nach VFA 35 und der Vorgabe des zuständigen ÄLRD. Analgesie, Schlinge, Wärmeerhalt und Transportplanung werden nicht nacheinander, sondern parallel organisiert.</p></>)}

    {section("10", "Thüringer VFA 2026/2027 und Dosierungsanlagen", <><div className="vfa-stack"><Vfa src="/lessons/sht/vfa-trauma-l2.png" alt="Thüringer VFA Leitalgorithmus Trauma L2" caption="L2 · Leitalgorithmus Trauma" /><Vfa src="/lessons/polytrauma/vfa-beckenschlinge-32.png" alt="Thüringer VFA 32 Beckenschlinge" caption="VFA 32 · Beckenschlinge" /><Vfa src="/lessons/sht/vfa-schmerz-basis-35.png" alt="Thüringer VFA 35 starke Schmerzzustände" caption="VFA 35 · Starke Schmerzzustände" /><Vfa src="/lessons/sht/vfa-esketamin-36.png" alt="Thüringer VFA 36 Esketamin Erwachsene" caption="VFA 36 · Esketamin / Ketanest" /><Vfa src="/lessons/sht/vfa-morphin-38.png" alt="Thüringer VFA 38 Morphin" caption="VFA 38 · Morphin" /></div><h3>Anlage B2A · Zubereitung</h3><Vfa src="/lessons/abdominaltrauma/txa-anlage-b2a.png" alt="Anlage B2A Tranexamsäure Zubereitung" caption="B2A · Tranexamsäure" /><Vfa src="/lessons/wirbelsaeulentrauma/anlage-b2a-esketamin.png" alt="Anlage B2A Esketamin Zubereitung" caption="B2A · Esketamin" /><Vfa src="/lessons/sht/medikamentenliste-morphin.png" alt="Anlage B2A Morphin Zubereitung" caption="B2A · Morphin" /><h3>Anlage B2B · Gewichtstabellen</h3><Vfa src="/lessons/wirbelsaeulentrauma/anlage-b2b-esketamin.png" alt="Anlage B2B Gewichtstabelle Esketamin" caption="B2B · Esketamin" /><Vfa src="/lessons/wirbelsaeulentrauma/anlage-b2b-morphin.png" alt="Anlage B2B Gewichtstabelle Morphin" caption="B2B · Morphin" /></>)}

    {children}
    <p className="lesson-source">Grundlage: „21. Beckentrauma.pdf“ und „21. Beckentrauma.docx“ sowie das hinterlegte Anatomie-Skriptum. Therapie und Dosierungen: <a href="https://www.aelrd-thueringen.de/verfahrensanweisungen-fuer-den-thueringer-rettungsdienst-algorithmen/" target="_blank" rel="noreferrer">Thüringer VFA 2026/27</a>, L2, 32, 35, 36, 38 und B2A/B2B. Ergänzend: <a href="https://rd-factsheets.de/beckenschlinge-in-der-praeklinik-s-kips-statt-kiss/" target="_blank" rel="noreferrer">RD-Factsheets · S-KIPS</a>, <a href="https://rd-factsheets.de/fs/schenkelhalsfraktur/" target="_blank" rel="noreferrer">RD-Factsheets · Schenkelhalsfraktur</a> und die geöffnete Notfallguru-Seite „Beckentrauma“. Medikamentendosierungen stammen ausschließlich aus der bereitgestellten Thüringer VFA.</p>
  </article>;
}
