import type { ComponentType, ReactNode } from "react";
import BronchoPreparation from "./broncho-preparation";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function BronchoobstruktionLesson({ Vfa, children }: Props) {
  const section = (number: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>Bronchoobstruktion · Asthma vs. COPD</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;
  const versus = (asthma: ReactNode, copd: ReactNode) => <div className="broncho-vs"><article><small>Asthma bronchiale</small>{asthma}</article><article><small>COPD</small>{copd}</article></div>;
  return <article className="lesson-article rippenfraktur-lesson broncho-lesson">
    <div className="lesson-intro"><p className="lead">Beide Krankheitsbilder erschweren vor allem die Ausatmung. Für die Prüfung werden Ursache, zeitlicher Verlauf und Reversibilität getrennt – die akute Atemnot wird bei beiden nach cABCDE beurteilt.</p></div>
    {section("01", "Definition", versus(<><h3>Asthma bronchiale</h3><p>Chronisch-entzündliche Erkrankung der Atemwege mit bronchialer Überempfindlichkeit und variabler, häufig reversibler Atemwegsverengung.</p></>, <><h3>Chronisch obstruktive Lungenerkrankung</h3><p>Dauerhafte, nicht vollständig reversible Einschränkung des Atemflusses mit entzündlicher Reaktion; meist fortschreitender Verlauf und mögliche Auswirkungen über die Lunge hinaus.</p></>))}
    {section("02", "Anatomie und Physiologie", <><div className="pulmo-anatomy-grid"><div><small>Leitungsweg</small><b>Nase · Rachen · Larynx · Trachea</b><p>Luft wird erwärmt, befeuchtet und zu den Bronchien geleitet. Der Kehlkopf schützt den unteren Atemweg beim Schlucken.</p></div><div><small>Obstruktion</small><b>Bronchien und Bronchiolen</b><p>Glatte Muskulatur verändert den Atemwegsdurchmesser. Schleimhaut und Sekret bestimmen den Strömungswiderstand mit.</p></div><div><small>Gasaustausch</small><b>Alveolen und Kapillaren</b><p>O₂ diffundiert ins Blut, CO₂ in die Alveole. Elastische Rückstellkräfte unterstützen die passive Exspiration.</p></div></div><p>Bei der Inspiration senkt sich das Zwerchfell und der Thorax erweitert sich. Die Exspiration ist in Ruhe überwiegend passiv. Bei verengten Atemwegen verlängert sich die Ausatmung; verbleibende Luft erhöht die Atemarbeit und kann zur Überblähung führen.</p><div className="broncho-gas-card"><div className="broncho-gas-heading"><small>Atemgase · Tabelle aus deinem Skript</small><h3>Einatemluft und Ausatemluft</h3></div><table><thead><tr><th scope="col">Gas</th><th scope="col">Einatem&shy;luft</th><th scope="col">Ausatem&shy;luft</th></tr></thead><tbody><tr><th scope="row">Sauer&shy;stoff (O₂)</th><td>21 %</td><td>17 %</td></tr><tr><th scope="row">Kohlen&shy;dioxid (CO₂)</th><td>0,03 %</td><td>4,03 %</td></tr><tr><th scope="row">Stickstoff (N₂)</th><td>78 %</td><td>78 %</td></tr><tr><th scope="row">Edelgase</th><td>0,97 %</td><td>0,97 %</td></tr></tbody></table><p>Vereinfachte Lehrwerte aus dem PDF, keine individuellen Messwerte oder Blutgaswerte. Der dortige Einatemluftwert für CO₂ ist gerundet und älter; aktuelle Außenluft liegt bei etwa 0,04 %.</p></div></>)}
    {section("03", "Ursachen und Pathophysiologie", <>{versus(<><h3>Variable Obstruktion</h3><p>Allergene, Infekte, Belastung, Kälte oder Reizstoffe können eine hyperreagible Bronchialschleimhaut aktivieren. Bronchospasmus, Schleimhautödem und zäher Schleim verengen gemeinsam das Lumen – die Asthma-Trias.</p></>, <><h3>Chronische Schädigung</h3><p>Langjährige inhalative Noxen, vor allem Tabakrauch, fördern Entzündung, Sekretbildung und Störung des Flimmerepithels. Kleine Atemwege verengen sich; Verlust von Alveolen und elastischer Rückstellkraft begünstigt Air trapping und Emphysem.</p></>)}<div className="pulmo-path"><span>Enges Bronchiallumen</span><i>→</i><span>verlängerte Exspiration</span><i>→</i><span>Luft bleibt zurück</span><i>→</i><span>Überblähung und Erschöpfung</span></div></>)}
    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", <><div className="broncho-comparison" role="table" aria-label="Asthma und COPD im Vergleich"><div role="row"><b role="columnheader">Merkmal</b><b role="columnheader">Asthma</b><b role="columnheader">COPD</b></div>{[["Verlauf","Anfallsartig, oft symptomfreie Intervalle","Chronische Beschwerden, akute Exazerbation möglich"],["Auslöser","Häufig Allergen, Belastung oder Kälte","Häufig Infekt oder inhalative Noxe"],["Husten / Auswurf","Oft trocken, wenig glasiger Schleim","Häufig Husten mit Auswurf (AHA)"],["Auskultation","Exspiratorisches Giemen; bei schwerem Anfall auch sehr leise","Giemen, Pfeifen oder Brummen, verlängertes Exspirium"],["Reversibilität","Meist deutliche Besserung möglich","Obstruktion nicht vollständig reversibel"]].map(([a,b,c]) => <div role="row" key={a}><b role="rowheader">{a}</b><span role="cell">{b}</span><span role="cell">{c}</span></div>)}</div><p><b>Gemeinsam:</b> Dyspnoe, Tachypnoe, Einsatz der Atemhilfsmuskulatur und verlängerte Exspiration. Alter oder Rauchstatus allein sichern keine Diagnose.</p></>)}
    {section("05", "Komplikationen und Gefahren", <><div className="pulmo-risk-grid"><div><b>Asthma</b><p>Status asthmaticus, Erschöpfung, respiratorische Insuffizienz und Atemstillstand.</p></div><div><b>COPD</b><p>Schwere Exazerbation, Hypoxämie, Hyperkapnie, respiratorische Azidose und Dekompensation des rechten Herzens.</p></div></div><aside className="red-flags"><span>!</span><div><small>Red Flags</small><h3>Stille Lunge ist keine Besserung</h3><p>Abnehmendes Atemgeräusch bei zunehmender Erschöpfung, Sprechunfähigkeit, Bewusstseinsänderung, Zyanose oder Bradykardie kann auf lebensbedrohlich geringen Luftstrom hinweisen. Die SpO₂ allein beschreibt weder Atemarbeit noch CO₂-Retention.</p></div></aside><p>Bei COPD darf Sauerstoff aus Sorge vor CO₂-Retention nicht vorenthalten werden. Hypoxie behandeln, Gabe und Beatmungsbedarf anhand von Vitalwerten und Verlauf regelmäßig neu beurteilen.</p></>)}
    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", <div className="material-chips">{["PSA", "Notfallrucksack", "EKG / RR / SpO₂", "O₂-Verneblermaske", "Salbutamol und Ipratropium", "i.v.-Material / Prednisolon", "Absaugung", "Beatmungsgerät mit CPAP/ASB", "Kapnometrie", "Atemwegsmaterial"].map(x=><span key={x}>{x}</span>)}</div>)}
    {section("07", "Erstmaßnahmen und SAMPLERS", <><div className="pulmo-care-grid"><div><span>01</span><b>cABCDE</b><small>Atemweg, Atemarbeit, Atemfrequenz, Auskultation, Kreislauf und Vigilanz im Verlauf prüfen.</small></div><div><span>02</span><b>Atemerleichterung</b><small>Oberkörper hoch, Kutschersitz und Lippenbremse anbieten; beruhigen, Belastung vermeiden.</small></div><div><span>03</span><b>Sauerstoff</b><small>Bei Hypoxie anpassen und Wirkung kontrollieren; nicht wegen möglicher Hyperkapnie unterlassen.</small></div><div><span>04</span><b>Reevaluation</b><small>SpO₂, AF, Sprechen, Auskultation und ggf. Kapnometrie wiederholt zusammenführen.</small></div></div><div className="samplers-grid">{[["S · Symptome","Beginn, Dyspnoe, Husten, Auswurf"],["A · Allergien","Auslöser und Unverträglichkeiten"],["M · Medikamente","Dauertherapie, Bedarfsinhalator, bisherige Gabe"],["P · Vorgeschichte","Asthma/COPD, Exazerbationen, NIV/Intubation"],["L · Letzte Aufnahme","Nahrung, Flüssigkeit"],["E · Ereignis","Infekt, Allergen, Rauch, Belastung"],["R · Risiken","Fieber, Thoraxschmerz, Embolie- oder Herzrisiko"],["S · Sonstiges","Ausgangs-SpO₂, Heim-O₂, Verlauf"]].map(([a,b])=><p key={a}><b>{a}</b>{b}</p>)}</div></>)}
    {section("08", "Differenzialdiagnosen und Entscheidung", <><div className="differential-grid">{["Lungenödem / Herzinsuffizienz", "Lungenarterienembolie", "Pneumonie", "Anaphylaxie", "Fremdkörperaspiration", "Pneumothorax", "Akutes Koronarsyndrom", "Obere Atemwegsverlegung"].map(x=><span key={x}>{x}</span>)}</div><p>Akute Atemnot nicht allein wegen einer bekannten COPD oder eines bekannten Asthmas zuordnen. Fieber, Thoraxschmerz, einseitig fehlendes Atemgeräusch, Kreislaufinstabilität oder Stridor verlangen eine erneute Differenzialdiagnose.</p></>)}
    {section("09", "Weitere Maßnahmen · Thüringer VFA", <><div className="pulmo-vfa-flow"><div><span>21</span><b>Gemeinsam vernebeln</b><small>Über O₂-Verneblermaske mit 6 l/min: 3 mg Salbutamolsulfat plus 0,5 mg Ipratropiumbromid.</small></div><div><span>i.v.</span><b>Einmalig Kortikosteroid</b><small>100 mg Prednisolonäquivalent i.v. nach VFA 21.</small></div><div><span>10′</span><b>Wirkung prüfen</b><small>Bei ausbleibendem Erfolg CPAP/ASB mit Kapnometrie gemäß VFA 06 prüfen; Kontraindikationen beachten.</small></div><div><span>↻</span><b>Nachlassender Effekt</b><small>VFA 21 nennt die gleiche Kombination zur erneuten Verneblung; Monitoring und Transport fortsetzen.</small></div></div><p>Salbutamol stimuliert β₂-Rezeptoren und entspannt die glatte Bronchialmuskulatur. Ipratropium blockiert muskarinische Rezeptoren und vermindert vagal vermittelte Bronchokonstriktion. Prednisolon dämpft die Entzündung, wirkt aber nicht als sofortiger Ersatz für die Bronchodilatation.</p><aside className="knowledge-note"><b>Weitere Wirkstoffe aus den Factsheets</b><p>Magnesium und Theophyllin werden dort als Optionen bei sehr schwerem Asthma genannt. VFA 21 enthält für sie keinen Standard-Dosierungsschritt; deshalb steht hier bewusst keine Dosis oder eigenständige Gabeanleitung.</p></aside></>)}
    {section("10", "VFA Thüringen 2026/2027", <><p>VFA 21 legt die Erwachsenendosis und das Vorgehen bei nachlassendem Effekt fest. Die ergänzende VFA 06 zeigt Indikationen und Grenzen der nicht-invasiven Atemunterstützung.</p><div className="vfa-stack"><Vfa src="/lessons/bronchoobstruktion/vfa-4.png" alt="Thüringer VFA 21 Bronchoobstruktion Erwachsene aus der bereitgestellten PDF" caption="VFA 21 · Bronchoobstruktion Erwachsene · Originalseite" /><Vfa src="/lessons/bronchoobstruktion/vfa-5.png" alt="Thüringer VFA 06 Nicht-invasive CPAP-ASB-Therapie und Kapnometrie aus der bereitgestellten PDF" caption="VFA 06 · CPAP/ASB und Kapnometrie · Originalseite" /></div><BronchoPreparation /></>)}
    {children}
    <p className="lesson-source">Hauptgrundlage: „Bronchoobstruktion-2 2.pdf“. Medikamente und Mengen: Thüringer VFA 21, VFA 06 und Anlage B2A 2026/2027. Ergänzend: <a href="https://rd-factsheets.de/fs/asthma-bronchiale/" target="_blank" rel="noreferrer">Asthma bronchiale</a> und <a href="https://rd-factsheets.de/fs/copd/" target="_blank" rel="noreferrer">COPD</a>. Maßgeblich im Einsatz ist die aktuelle Original-VFA.</p>
  </article>;
}
