import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Answer = [string, boolean];
function q(n: number, prompt: string, answers: Answer[], source: string): ThoraxtraumaChoiceQuestion {
  const offset = n % answers.length;
  return { id: `broncho-q-${String(n).padStart(2, "0")}`, mode: "multiple", prompt, options: [...answers.slice(offset), ...answers.slice(0, offset)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty: 3 };
}

export const bronchoQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1,"Eine Patientin hat anfallsartige Dyspnoe, glasigen Auswurf und nach Inhalation deutlich weniger Giemen. Welche Befunde stützen eher Asthma als eine COPD?",[["Variable Beschwerden mit symptomarmen Intervallen",true],["Deutliche Reversibilität der Obstruktion",true],["Allergen als möglicher Auslöser",true],["Jahrelang täglich produktiver Husten als Leitsymptom",false],["Alter allein beweist die Diagnose",false]],"Asthma zeigt oft variable, reversible Obstruktion; Anamnese und Verlauf sind entscheidend."),
  q(2,"Ein langjähriger Raucher hat chronischen Husten, Auswurf und zunehmende Belastungsdyspnoe. Welche Mechanismen erklären die Exspiration?",[["Entzündung und Sekret engen kleine Atemwege ein",true],["Verlust elastischer Rückstellkraft fördert Air trapping",true],["Alveoläre Zerstörung kann die Austauschfläche vermindern",true],["Bronchiolen besitzen besonders stabile Knorpelspangen",false],["Die Ausatmung wird durch einen dauerhaft vergrößerten Bronchialdurchmesser erschwert",false]],"COPD kann kleine Atemwege und Alveolen betreffen; Überblähung erhöht die Atemarbeit."),
  q(3,"Was bezeichnet die Asthma-Trias bei akuter Bronchoobstruktion?",[["Kontraktion glatter Bronchialmuskulatur",true],["Ödem der Bronchialschleimhaut",true],["Vermehrte Sekretbildung",true],["Pleuraerguss als obligater Bestandteil",false],["Primäre Zerstörung des rechten Ventrikels",false]],"Bronchospasmus, Schleimhautödem und Hypersekretion verengen das Atemwegslumen."),
  q(4,"Ein Patient mit bekanntem Asthma spricht nur noch einzelne Worte; das zuvor laute Giemen ist kaum hörbar. Welche Bewertungen sind richtig?",[["Ein stark verminderter Luftstrom kann das Atemgeräusch leiser machen",true],["Erschöpfung und respiratorische Insuffizienz sind zu befürchten",true],["Atemarbeit, Vigilanz und Sättigung müssen erneut zusammen bewertet werden",true],["Das leisere Geräusch beweist eine erfolgreiche Bronchodilatation",false],["Die Gefahr ist allein durch einen normalen initialen Blutdruck ausgeschlossen",false]],"Die stille Lunge ist ein Warnzeichen, nicht automatisch ein Therapieerfolg."),
  q(5,"Welche Aussagen zur Sauerstoffgabe bei schwerer COPD-Exazerbation sind tragfähig?",[["Eine Hypoxie darf nicht aus Angst vor Hyperkapnie unbehandelt bleiben",true],["Sauerstoffgabe muss anhand von Zustand und Verlauf reevaluiert werden",true],["SpO₂ allein erfasst keine CO₂-Retention",true],["Sauerstoff ist bei COPD grundsätzlich kontraindiziert",false],["Ein einzelner SpO₂-Wert ersetzt die Beurteilung der Atemarbeit",false]],"Hypoxie behandeln und Atemarbeit, Bewusstsein sowie Messwerte wiederholt prüfen."),
  q(6,"Welche Angaben helfen bei Asthma und COPD am meisten, die akute Atemnot einzuordnen?",[["Beginn und zeitlicher Verlauf der Beschwerden",true],["Dauer- und Bedarfsmedikation einschließlich bisheriger Inhalationen",true],["Vorherige NIV oder Intubationen",true],["Allein die Farbe des Auswurfs als sichere Diagnose",false],["Die Vorerkrankung ohne erneutes cABCDE als vollständige Erklärung",false]],"SAMPLERS fokussiert auf Verlauf, bisherige Therapie und frühere schwere Ereignisse."),
  q(7,"Die Thüringer VFA 21 wird beim Erwachsenen angewandt. Welche Angaben gehören zur ersten Verneblung?",[["3 mg Salbutamolsulfat",true],["0,5 mg Ipratropiumbromid",true],["O₂-Verneblermaske mit 6 l/min",true],["5 mg vernebeltes Adrenalin als fester erster Schritt",false],["Ipratropium allein ohne Salbutamol als VFA-Kombination",false]],"VFA 21: 3 mg Salbutamol und 0,5 mg Ipratropium zusammen über O₂-Verneblermaske (6 l/min)."),
  q(8,"Was trifft auf das Kortikosteroid in VFA 21 zu?",[["Einmalig 100 mg Prednisolonäquivalent i.v.",true],["Entzündungshemmung ersetzt keine unmittelbar nötige Bronchodilatation",true],["Die Wirkung ist nicht so unmittelbar wie die der inhalativen Bronchodilatatoren",true],["Die VFA fordert routinemäßig 500 mg für jeden COPD-Anfall",false],["Das Präparat wird in den gleichen Vernebler wie Salbutamol gegeben",false]],"VFA 21 nennt einmalig 100 mg Prednisolonäquivalent i.v.; die Bronchodilatation erfolgt inhalativ."),
  q(9,"Eine 250-mg-Prednisolon-Trockensubstanz wird nach Anlage B2A mit 5 ml Lösungsmittel rekonstituiert. Welche Rechnungen stimmen?",[["Die fertige Konzentration beträgt 50 mg/ml",true],["100 mg entsprechen 2 ml der fertigen Lösung",true],["Die ganze 5-ml-Lösung enthält 250 mg",true],["2 ml entsprechen 250 mg",false],["Die 100-mg-Gabe erfordert zusätzlich 9 ml NaCl in der Spritze",false]],"Anlage B2A: 250 mg/5 ml = 50 mg/ml; 100 mg/50 mg/ml = 2 ml."),
  q(10,"Nach zehn Minuten bleibt bei schwerer Bronchoobstruktion der klinische Erfolg aus. Welche Entscheidung gehört zum VFA-21-Pfad?",[["Nicht-invasive CPAP/ASB-Therapie mit Kapnometrie prüfen",true],["Kontraindikationen der VFA 06 mitbedenken",true],["Atemarbeit und Bewusstsein weiter überwachen",true],["Ohne erneute Beurteilung sofort entlassen",false],["Die gleiche Verneblung unabhängig vom Verlauf unendlich fortsetzen",false]],"VFA 21 verweist bei fehlendem Erfolg nach 10 Minuten auf CPAP/ASB und Kapnometrie; VFA 06 beschreibt Grenzen."),
  q(11,"Welche Situationen sprechen nach VFA 06 gegen eine nicht-invasive CPAP/ASB-Therapie?",[["Fehlende Schutzreflexe",true],["Erbrechen",true],["Bewusstlosigkeit",true],["Wacher, kooperativer Patient mit starker Dyspnoe",false],["Allein bekanntes Asthma bei erhaltener Compliance",false]],"VFA 06 nennt u. a. fehlende Schutzreflexe, Erbrechen, fehlende Compliance und Bewusstlosigkeit als Kontraindikationen."),
  q(12,"Welchen Wirkmechanismus haben die beiden inhalativen Medikamente der VFA 21?",[["Salbutamol stimuliert bronchiale β₂-Rezeptoren",true],["Ipratropium blockiert muskarinische Rezeptoren",true],["Beide Wege können die Bronchien erweitern",true],["Prednisolon ist der inhalative muskarinische Antagonist",false],["Ipratropium löst Sekret mechanisch aus den Alveolen",false]],"β₂-Stimulation und antimuskarinische Wirkung sind unterschiedliche Bronchodilatationswege."),
  q(13,"Bei einem Patienten mit COPD und akuter Dyspnoe treten Thoraxschmerz und Hypotonie auf. Welche Schritte sind begründet?",[["Akutes Koronarsyndrom und Lungenembolie mitbedenken",true],["cABCDE und Kreislauf erneut beurteilen",true],["Eine bekannte COPD nicht als alleinige Erklärung voraussetzen",true],["Ohne weitere Untersuchung ausschließlich die Dauerinhalation wiederholen",false],["Thoraxschmerz als COPD-typisch beweisen",false]],"Eine Vordiagnose ersetzt keine Differenzialdiagnostik bei neuen Warnzeichen."),
  q(14,"Die VFA 21 fordert bei nachlassendem Effekt eine erneute Verneblung. Welche Aussagen sind korrekt?",[["Salbutamol und Ipratropium werden in der genannten Dosis erneut kombiniert",true],["Kontinuierliches Monitoring und Transport bleiben Teil des Pfads",true],["Wirkung und klinischer Zustand werden vor der Wiederholung bewertet",true],["Die erste Gabe wird automatisch durch Prednisolon ersetzt",false],["Die zweite Verneblung bedeutet, dass CPAP grundsätzlich verboten ist",false]],"Bei nachlassendem Effekt nennt VFA 21 die gleiche Verneblerkombination und weitere Überwachung."),
  q(15,"Welche Aussage zur Spritzenübersicht und zur Salbutamol-Ampullenangabe ist fachlich sicher?",[["Die VFA-21-Zieldosis ist 3 mg Salbutamolsulfat",true],["Die Konzentration auf der tatsächlich verwendeten Phiole muss vor dem Befüllen geprüft werden",true],["Die B2A-Packungsangabe ist nicht mit der in VFA 21 genannten Phiolenstärke identisch",true],["Zwei beliebige Phiolen ergeben unabhängig von Konzentration immer 3 mg",false],["Das Volumen der Ipratropiumlösung beweist die Salbutamolkonzentration",false]],"VFA 21 nennt 2 × 1,5 mg; Anlage B2A listet bei Salbutamol eine abweichende Stärke. Die Dosis erfordert Produktprüfung."),
  q(16,"Eine schwere Bronchoobstruktion bessert sich trotz Therapie nicht. Welche Übergabeinformationen sind prüfungsrelevant?",[["Ausgangsbefund und Verlauf von Atemarbeit, Auskultation und SpO₂",true],["Zeit, Dosis und Wirkung jeder Verneblung sowie des Kortikosteroids",true],["Bisherige NIV-Toleranz, Kapnometrie und mögliche Kontraindikationen",true],["Nur der Name der Dauerdiagnose ohne aktuelle Befunde",false],["Die einmalige Sättigung vor Behandlung als alleiniger Verlaufswert",false]],"Verlauf, Wirkungen und Grenzen der Atemunterstützung ermöglichen die sichere Weiterbehandlung."),
  q(17,"Sie vergleichen die Atemgas-Tabelle aus dem Lernkapitel mit einem Patienten mit schwerer Bronchoobstruktion. Welche Schlüsse sind zulässig?",[["Auch Ausatemluft enthält nach der Tabelle noch Sauerstoff",true],["Der CO₂-Anteil ist in der Ausatemluft höher als in der Einatemluft",true],["Der Stickstoffanteil ist in beiden Tabellenspalten gleich angegeben",true],["Aus 4,03 % CO₂ lässt sich der arterielle pCO₂ dieses Patienten direkt ablesen",false],["Der Tabellenwert 17 % O₂ beweist eine normale Oxygenierung dieses Patienten",false]],"Die Tabelle zeigt vereinfachte Gasanteile, keine patientenindividuelle Blutgasanalyse. O₂ sinkt, CO₂ steigt; N₂ bleibt in der Vorlage gleich."),
  q(18,"Ein Auszubildender will aus der Atemgas-Tabelle die CO₂-Retention eines erschöpften COPD-Patienten beurteilen. Welche Einwände sind korrekt?",[["Die Tabellenwerte beschreiben keine individuelle Ausatemluft bei einer akuten Exazerbation",true],["Der CO₂-Anteil der Ausatemluft ist nicht mit dem arteriellen pCO₂ gleichzusetzen",true],["Atemarbeit, Vigilanz und gegebenenfalls Kapnometrie müssen im Verlauf beurteilt werden",true],["Ein normaler Tabellenwert schließt eine Hyperkapnie beim Patienten aus",false],["Die unveränderten 78 % Stickstoff beweisen eine ausreichende Ventilation",false]],"Lehrwerte zur Gaszusammensetzung ersetzen keine klinische Verlaufskontrolle und keine patientenbezogene Messung."),
  q(19,"Welche Veränderungen erklären bei fortgeschrittener COPD die zunehmende Überblähung?",[["Fibrosierung und Sekret verengen die kleinen Atemwege",true],["Verlust elastischer Rückstellkraft begünstigt den exspiratorischen Atemwegskollaps",true],["Air trapping erhöht Residualvolumen und intrathorakales Gasvolumen",true],["Eine verstärkte Knorpelbildung hält alle Bronchiolen während der Ausatmung offen",false],["Die Überblähung entsteht ausschließlich durch eine gesteigerte Inspiration",false]],"Chronische Entzündung, instabile kleine Atemwege und Elastizitätsverlust begrenzen den exspiratorischen Luftstrom."),
  q(20,"Welche Befunde sprechen bei einer COPD eher für eine fortgeschrittene Erkrankung oder Rechtsherzbelastung als für die reine akute Bronchialverengung?",[["Gestaute Halsvenen",true],["Unterschenkelödeme",true],["Fassthorax bei langjähriger Überblähung",true],["Isoliert erhöhte Atemfrequenz als sicherer Beweis einer Rechtsherzinsuffizienz",false],["Ein einzelnes exspiratorisches Giemen als Nachweis eines Cor pulmonale",false]],"Halsvenenstauung und Ödeme können eine Rechtsherzbelastung anzeigen; der Fassthorax passt zur chronischen Überblähung."),
  q(21,"Welche Zuordnungen zu den Arzneimitteln der VFA 21 sind richtig?",[["Salbutamol: β₂-vermittelte Relaxation glatter Bronchialmuskulatur",true],["Ipratropium: Blockade muskarinischer Acetylcholinrezeptoren",true],["Prednisolon: entzündungshemmende, verzögert einsetzende Wirkung",true],["Ipratropium: direkte β₂-Stimulation",false],["Prednisolon: sofortige mechanische Erweiterung des Bronchiallumens",false]],"Die Wirkstoffe greifen an unterschiedlichen Mechanismen an und ergänzen sich; das Kortikosteroid ist kein Akutbronchodilatator."),
  q(22,"Kurz nach der Verneblung treten Tremor, Unruhe, Palpitationen und eine Tachykardie auf. Welche Bewertungen sind sachgerecht?",[["Die Beschwerden passen zu unerwünschten Wirkungen eines β₂-Sympathomimetikums",true],["Rhythmus und Kreislauf müssen im Verlauf weiter überwacht werden",true],["Zusätzliche Sympathomimetika können unerwünschte Wirkungen verstärken",true],["Die Symptome beweisen eine Ipratropium-Allergie",false],["Tachykardie schließt eine Wirkung des Salbutamols aus",false]],"Salbutamol kann Tremor, Unruhe, Palpitationen und Tachykardie verursachen; klinischer Nutzen und Nebenwirkungen werden gemeinsam reevaluiert."),
  q(23,"Welche Aussagen beschreiben CPAP, PEEP und ASB korrekt?",[["CPAP hält während der Spontanatmung ein positives Atemwegsdruckniveau aufrecht",true],["PEEP bezeichnet den positiven Druck am Ende der Ausatmung",true],["ASB unterstützt jeden vom Patienten ausgelösten Atemzug zusätzlich inspiratorisch",true],["ASB ersetzt die eigene Atemaktivität immer vollständig",false],["PEEP wirkt ausschließlich während der Inspiration",false]],"PEEP bildet das positive Grundniveau; ASB ergänzt darauf eine inspiratorische Druckunterstützung bei vorhandener Spontanatmung."),
  q(24,"Ein erschöpfter COPD-Patient toleriert CPAP/ASB. Welche gewünschten Wirkungen und Risiken müssen gemeinsam beurteilt werden?",[["ASB kann die Atemmuskulatur entlasten und die Ventilation verbessern",true],["Ein passender PEEP kann den inspiratorischen Aufwand gegen intrinsischen PEEP vermindern",true],["Zu hoher Druck kann Air-Trapping und Kreislaufbelastung verstärken",true],["Eine ruhigere Atmung macht weitere Vigilanz- und Kreislaufkontrollen überflüssig",false],["CPAP/ASB beseitigt die Ursache jeder COPD-Exazerbation",false]],"Bei COPD kann NIV Atemarbeit und Ventilation verbessern; Druck, Überblähung, Kreislauf und klinischer Verlauf müssen eng reevaluiert werden."),
  q(25,"Während CPAP/ASB wird ein Asthmapatient schläfriger, das Atemgeräusch leiser und die Atmung unregelmäßig. Welche Konsequenzen sind richtig?",[["Die Befunde sprechen für mögliches Therapieversagen und drohende Erschöpfung",true],["Atemwegsschutz und invasive Eskalation müssen unverzüglich neu bewertet werden",true],["Beatmungsdrücke, Maskensitz und vollständiges cABCDE werden kontrolliert",true],["Das leise Atemgeräusch beweist eine erfolgreiche Bronchodilatation",false],["Die NIV wird unabhängig von Vigilanz und Schutzreflexen unverändert fortgeführt",false]],"NIV darf eine notwendige Atemwegssicherung nicht verzögern; sinkende Vigilanz und unregelmäßige Atmung sind Warnzeichen."),
];

export const bronchoFlashcards: ThoraxtraumaFlashcard[] = [
  { id:"broncho-card-01",area:"Definition",question:"Grenzen Sie Asthma und COPD anhand von Entzündung, Verlauf und Reversibilität ab.",answer:"Asthma: chronische Entzündung mit Hyperreagibilität, variabler häufig reversibler Obstruktion und oft Intervallen. COPD: persistierende nicht vollständig reversible Obstruktion, meist progredient nach inhalativen Noxen." },
  { id:"broncho-card-02",area:"Anatomie",question:"Warum erschwert die Bronchiolenverengung besonders die Exspiration?",answer:"Bronchiolen besitzen glatte Muskulatur ohne stützende Knorpelspangen. Bei der Exspiration sinkt der transmural stabilisierende Druck; enge kleine Atemwege begrenzen den Luftstrom und fördern Air trapping." },
  { id:"broncho-card-03",area:"Pathophysiologie",question:"Nennen Sie die Asthma-Trias und erklären Sie deren gemeinsame Wirkung.",answer:"Bronchospasmus, Schleimhautödem und Hypersekretion verkleinern das Bronchiallumen, erhöhen den Strömungswiderstand und verlängern die Ausatmung." },
  { id:"broncho-card-04",area:"COPD",question:"Wie führt ein Emphysem zu Überblähung und höherer Atemarbeit?",answer:"Verlust von Alveolarwänden und elastischer Rückstellkraft begünstigt Kollaps kleiner Atemwege bei der Exspiration; Luft bleibt zurück, die Lunge überbläht und das Zwerchfell arbeitet ungünstiger." },
  { id:"broncho-card-05",area:"Red Flags",question:"Weshalb kann eine stille Lunge bei schwerem Asthma lebensbedrohlich sein?",answer:"Ein extrem geringer Luftstrom erzeugt kaum noch Giemen. Sprechunfähigkeit, Erschöpfung, Bewusstseinsänderung und Hypoxie deuten auf drohende respiratorische Insuffizienz." },
  { id:"broncho-card-06",area:"VFA 21",question:"Nennen Sie die Erwachsenen-Erstgabe der VFA 21 mit Applikationsweg und Sauerstofffluss.",answer:"3 mg Salbutamolsulfat plus 0,5 mg Ipratropiumbromid über O₂-Verneblermaske mit 6 l/min; zusätzlich einmalig 100 mg Prednisolonäquivalent i.v." },
  { id:"broncho-card-07",area:"Zubereitung",question:"Rechnen Sie die Prednisolon-VFA-Dosis aus der B2A-Rekonstitution 250 mg in 5 ml aus.",answer:"50 mg/ml. Für 100 mg werden 2 ml der rekonstituierten Lösung entnommen. Die übrigen 3 ml sind nicht die Patientendosis." },
  { id:"broncho-card-08",area:"VFA 06",question:"Wann ist bei ausbleibender Besserung CPAP/ASB zu prüfen, und welche Grenzen müssen Sie nennen?",answer:"VFA 21 verweist nach 10 Minuten ohne Erfolg auf nicht-invasive CPAP/ASB-Therapie mit Kapnometrie. VFA 06 nennt u. a. fehlende Schutzreflexe, fehlende Compliance, Erbrechen und Bewusstlosigkeit als Kontraindikationen." },
  { id:"broncho-card-09",area:"Medikamente",question:"Erklären Sie den Unterschied zwischen Salbutamol, Ipratropium und Prednisolon.",answer:"Salbutamol: β₂-Agonist, relaxiert Bronchialmuskulatur. Ipratropium: antimuskarinisch, vermindert vagalen Bronchospasmus. Prednisolon: entzündungshemmend, kein sofortiger Ersatz für Inhalation." },
  { id:"broncho-card-10",area:"Entscheidung",question:"Wie gehen Sie bei bekannter COPD mit neuer Hypotonie und Thoraxschmerz vor?",answer:"Nicht automatisch als Exazerbation werten: cABCDE, EKG und Kreislauf prüfen, ACS, LAE und Pneumothorax differenzialdiagnostisch mitbedenken, Verlauf überwachen und Zielklinik/Notarztbedarf anpassen." },
  { id:"broncho-card-11",area:"COPD",question:"Erklären Sie die Kette von inhalativer Noxe bis zum Air trapping.",answer:"Chronische Entzündung und oxidativer Stress schädigen Flimmerepithel und Parenchym. Sekret, Fibrose und Elastizitätsverlust verengen beziehungsweise destabilisieren kleine Atemwege; bei der Exspiration kollabieren sie leichter, Luft bleibt zurück und Residualvolumen sowie Atemarbeit steigen." },
  { id:"broncho-card-12",area:"Medikamente",question:"Welche typischen Nebenwirkungen und Wechselwirkungen müssen Sie bei Salbutamol nennen?",answer:"Möglich sind Tremor, Unruhe, Palpitationen, Tachykardie, Extrasystolen und Angina-pectoris-Beschwerden. β-Blocker können die Wirkung abschwächen; weitere Sympathomimetika können Wirkung und Nebenwirkungen verstärken." },
  { id:"broncho-card-13",area:"Medikamente",question:"Wie wirkt Ipratropium und worauf achten Sie bei der Verneblung?",answer:"Als Anticholinergikum blockiert es muskarinische Acetylcholinrezeptoren und vermindert die vagale Bronchokonstriktion. Mögliche Effekte sind Mundtrockenheit, Mydriasis und Augenschmerz; Verneblernebel soll nicht in die Augen gelangen." },
  { id:"broncho-card-14",area:"CPAP/ASB",question:"Erklären Sie PEEP und ASB so, dass der Unterschied sofort verständlich wird.",answer:"PEEP ist das positive Grunddruckniveau, das auch am Ende der Ausatmung bestehen bleibt und Atemwege beziehungsweise rekrutierbare Alveolen offen hält. ASB ist die zusätzliche Druckhilfe während eines selbst ausgelösten Atemzugs und entlastet die Einatemmuskulatur." },
  { id:"broncho-card-15",area:"CPAP/ASB",question:"Welche Wirkung ist bei COPD erwünscht, und welche Gefahr besteht bei zu hohem Druck?",answer:"Passender PEEP kann die inspiratorische Last durch intrinsischen PEEP vermindern; ASB kann Atemarbeit und Ventilation verbessern. Zu hoher Druck kann Air-Trapping und Überblähung verstärken, den intrathorakalen Druck erhöhen und den venösen Rückstrom beziehungsweise Kreislauf beeinträchtigen." },
];
