export default function BronchoPreparation() {
  return <section className="broncho-preparation" aria-label="Zubereitung nach Thüringer VFA 21 und Anlage B2A">
    <div className="broncho-preparation-heading"><small>VFA 21 · Anlage B2A</small><h3>Vernebler &amp; Spritzenübersicht</h3><p>Inhalation und intravenöse Gabe sind zwei getrennte Zubereitungen. Alle Mengen beziehen sich auf die Erwachsenen-VFA.</p></div>
    <div className="broncho-preparation-grid">
      <article><span className="broncho-preparation-icon">◌</span><small>O₂-Vernebler · 6 l/min</small><h4>Salbutamol + Ipratropium</h4><div className="broncho-nebulizer"><b>3 mg</b><span>Salbutamolsulfat<br/>2 Phiolen à 1,5 mg</span><i>+</i><b>0,5 mg</b><span>Ipratropiumbromid<br/>2 Phiolen à 0,25 mg</span></div><p>Bei nachlassendem Effekt nennt VFA 21 dieselbe Verneblung erneut. Die Phiolenstärke vor dem Befüllen prüfen: Die B2A-Liste führt bei Salbutamol eine abweichende Packungsangabe; aus der VFA-Dosis allein lässt sich daher kein allgemein gültiges Millilitervolumen ableiten.</p></article>
      <article><span className="broncho-preparation-icon">▤</span><small>Einmalig i.v.</small><h4>Prednisolonäquivalent 100 mg</h4><p>Anlage B2A: 250 mg Trockensubstanz mit 5 ml beiliegendem Lösungsmittel rekonstituieren. Das ergibt <b>50 mg/ml</b>; für 100 mg werden <b>2 ml</b> der fertigen Lösung entnommen.</p><div className="broncho-syringe" role="img" aria-label="Schematische 5-Milliliter-Spritze: zwei Milliliter der rekonstituierten Prednisolonlösung entsprechen 100 Milligramm"><span className="broncho-syringe-tip"/><div className="broncho-syringe-bar"><span className="broncho-syringe-fill"/><div className="broncho-syringe-scale" aria-hidden="true">{[0,1,2,3,4,5].map(ml=><span key={ml}>{ml}</span>)}</div><b>2 ml · 100 mg</b></div><span className="broncho-syringe-plunger"/></div><div className="broncho-syringe-dose"><b>2 ml</b> der Lösung = <b>100 mg</b> Prednisolonäquivalent</div><p>Nur das beiliegende Lösungsmittel zur Rekonstitution verwenden; die übrige Lösung nicht als verabreichte Dosis verstehen.</p></article>
    </div>
    <p className="broncho-preparation-caution">Schematische Lernhilfe. Arzneimittel, Konzentration, Indikation und aktuelle Original-VFA vor Anwendung prüfen.</p>
  </section>;
}
