"use client";

import { ReactNode, useRef } from "react";

function DiagnostikSection({ number, kicker, title, children }: { number: string; kicker: string; title: string; children: ReactNode }) {
  return <details className="communication-section qm-section"><summary><span>{number}</span><div><small>{kicker}</small><h2>{title}</h2></div><i>⌄</i></summary><div className="communication-section-content">{children}</div></details>;
}

export default function DiagnostikLesson({ onBack, finale }: { onBack: () => void; finale: ReactNode }) {
  const flowRef = useRef<HTMLDivElement>(null);
  const toggleAll = (open: boolean) => flowRef.current?.querySelectorAll<HTMLDetailsElement>("details").forEach(section => { section.open = open; });
  return <section className="page-section legal-reader communication-reader qm-reader">
    <button className="back-button" onClick={onBack}>← Schriftliche Fachbereiche</button>
    <header className="communication-hero qm-hero"><div><span className="eyebrow light">Schriftliche Prüfung · Medizinische Diagnostik</span><h1>Befunde erkennen.<br />Prioritäten sicher setzen.</h1><p>Neurologie, EKG, Zugänge, Trauma, Reanimation und Notfallnarkose kompakt verbinden.</p></div><div><b>10</b><span>Lernfelder</span><small>NotSan-Prüfung 2027</small></div></header>
    <aside className="communication-focus qm-focus"><span>＋</span><div><b>Prüfungsfokus</b><p>Nicht nur Begriffe aufzählen: Befund erkennen, Aussagegrenzen benennen und daraus die nächste sichere Handlung ableiten.</p></div></aside>
    <div className="communication-toolbar" role="group" aria-label="Leseabschnitte steuern"><button type="button" onClick={() => toggleAll(true)}>Alles ausklappen</button><button type="button" onClick={() => toggleAll(false)}>Alles einklappen</button><small>Zehn kompakte Lernfelder – klar gegliedert und mobil lesbar.</small></div>
    <div className="communication-reading-flow" ref={flowRef}>
      <DiagnostikSection number="01" kicker="Neurologie" title="Fokal, generalisiert und die Cushing-Trias"><div className="communication-copy"><div className="communication-compare"><article><small>Umschriebener Befund</small><h3>Fokale Ursache</h3><p>Hinweis auf eine bestimmte Hirnregion oder Leitungsbahn: einseitige Parese, Aphasie, Gesichtsfeldausfall oder Blickdeviation. Beispiele sind Schlaganfall, intrakranielle Blutung und fokaler Krampfanfall.</p></article><article><small>Diffuse Hirnfunktionsstörung</small><h3>Generalisierte Ursache</h3><p>Bewusstseinsstörung, symmetrischer Krampfanfall oder globale Verwirrtheit. Mögliche Ursachen: Hypoxie, Hypoglykämie, Intoxikation, metabolische Entgleisung oder generalisierter Anfall.</p></article></div><aside className="communication-case"><small>Cushing-Trias · spätes Warnzeichen</small><p><b>Arterielle Hypertonie</b>, häufig mit verbreiterter Blutdruckamplitude, <b>Bradykardie</b> und <b>veränderte Atmung</b> sprechen für fortgeschrittenen Hirndruck mit drohender Einklemmung. Ein mögliches Beispiel ist die <b>Cheyne-Stokes-Atmung</b> mit periodisch tiefer und flacher werdender Atmung und Atempausen.</p></aside><aside className="communication-exam-tip"><b>Prüfungsfalle</b><p>Ein fokales Muster beweist keinen Schlaganfall und das Fehlen der Cushing-Trias schließt erhöhten Hirndruck nicht aus. cABCDE, Blutzucker, Pupillen, BE-FAST und Verlauf gehören zusammen.</p></aside></div></DiagnostikSection>

      <DiagnostikSection number="02" kicker="Bewusstsein" title="Glasgow Coma Scale · deutsche Variante"><div className="communication-copy"><div className="table-scroll diagnostik-table"><table><thead><tr><th scope="col">Bereich</th><th scope="col">Reaktion</th><th scope="col">Punkte</th></tr></thead><tbody><tr><th rowSpan={4} scope="rowgroup">Augen öffnen (E)</th><td>spontan</td><td>4</td></tr><tr><td>auf Ansprache</td><td>3</td></tr><tr><td>auf Schmerzreiz</td><td>2</td></tr><tr><td>keine Reaktion</td><td>1</td></tr><tr><th rowSpan={5} scope="rowgroup">Verbale Reaktion (V)</th><td>orientiert</td><td>5</td></tr><tr><td>desorientiert / verwirrt</td><td>4</td></tr><tr><td>inadäquate Wörter</td><td>3</td></tr><tr><td>unverständliche Laute</td><td>2</td></tr><tr><td>keine Reaktion</td><td>1</td></tr><tr><th rowSpan={6} scope="rowgroup">Motorische Reaktion (M)</th><td>befolgt Aufforderungen</td><td>6</td></tr><tr><td>gezielte Schmerzabwehr</td><td>5</td></tr><tr><td>ungezielte Schmerzabwehr</td><td>4</td></tr><tr><td>Beugesynergismen</td><td>3</td></tr><tr><td>Strecksynergismen</td><td>2</td></tr><tr><td>keine Reaktion</td><td>1</td></tr></tbody></table></div><aside className="communication-case"><small>Dokumentation</small><p>Einzelwerte, Summe und Verlauf angeben: <b>E2 V3 M5 = GCS 10</b>. Intubation oder nicht prüfbare Komponenten ausdrücklich kennzeichnen, statt einen falschen Zahlenwert zu vergeben.</p></aside><p>Die GCS beschreibt den Reaktionszustand, aber nicht dessen Ursache. Sedierung, Intoxikation, Sprachbarriere, Hypoxie und Hypoglykämie können das Ergebnis beeinflussen.</p></div></DiagnostikSection>

      <DiagnostikSection number="03" kicker="Kardiologie" title="12-Kanal-EKG richtig kleben"><div className="communication-copy"><p>Zehn Elektroden erzeugen zwölf Ableitungen. Zuerst die Extremitätenelektroden nach Geräteschema anschließen; im IEC-Farbsystem: rechter Arm rot, linker Arm gelb, linkes Bein grün, rechtes Bein schwarz.</p><div className="table-scroll diagnostik-table"><table><thead><tr><th scope="col">Elektrode</th><th scope="col">Position</th><th scope="col">Merke</th></tr></thead><tbody><tr><th scope="row">V1</th><td>4. Interkostalraum rechts parasternal</td><td>rechts neben dem Sternum</td></tr><tr><th scope="row">V2</th><td>4. Interkostalraum links parasternal</td><td>spiegelbildlich zu V1</td></tr><tr><th scope="row">V3</th><td>zwischen V2 und V4</td><td>erst nach V4 kleben</td></tr><tr><th scope="row">V4</th><td>5. Interkostalraum links, Medioklavikularlinie</td><td>V4 zuerst lokalisieren</td></tr><tr><th scope="row">V5</th><td>gleiche Höhe wie V4, vordere Axillarlinie</td><td>nicht dem Rippenverlauf folgen</td></tr><tr><th scope="row">V6</th><td>gleiche Höhe wie V4/V5, mittlere Axillarlinie</td><td>horizontal ausrichten</td></tr></tbody></table></div><aside className="communication-exam-tip"><b>Häufige Klebefehler</b><p>V1/V2 zu hoch, V4–V6 nicht auf einer Horizontalen, Elektroden auf Brustgewebe statt Thoraxwand, vertauschte Extremitätenkabel oder fehlende Dokumentation einer abweichenden Position. Bei einer Brust werden V4–V6 auf der Thoraxwand unter dem Brustgewebe platziert.</p></aside></div></DiagnostikSection>

      <DiagnostikSection number="04" kicker="Trauma" title="MILS, STU und Immobilisationsentscheidung"><div className="communication-copy"><div className="communication-compare"><article><small>Manual In-Line Stabilization</small><h3>MILS</h3><p>Eine zweite Person stabilisiert Kopf und Halswirbelsäule manuell in vorgefundener beziehungsweise tolerierter Neutralstellung. Unnötige Flexion, Extension und Rotation werden besonders bei Atemwegsmaßnahmen begrenzt.</p></article><article><small>Schnelle Traumauntersuchung</small><h3>STU</h3><p>Strukturierte Untersuchung von Kopf/Gesicht, Hals, Thorax, Abdomen/Flanken, Becken/Perineum, Extremitäten und Rücken; anschließend pDMS, erneutes cABCDE und Verlauf.</p></article></div><div className="communication-compare"><article><small>Vollimmobilisation erwägen</small><h3>Hinweise auf Wirbelsäulenverletzung</h3><p>Neurologisches Defizit, Wirbelsäulenschmerz oder Mittelliniendruckschmerz, Deformität, Hochrisikomechanismus oder unzuverlässige Beurteilbarkeit durch Vigilanzminderung, Intoxikation beziehungsweise stark ablenkende Verletzung.</p></article><article><small>Auf starre Zervikalstütze verzichten/abwägen</small><h3>Wenn Schaden überwiegt</h3><p>Keine Indikation nach validierter lokaler Entscheidungsregel; Atemweg oder Ventilation werden behindert; Neutralstellung verstärkt Schmerz oder neurologisches Defizit; starke Agitation; passendes Modell lässt sich nicht korrekt anlegen; bei SHT und Hirndruckverdacht individuelle Abwägung zugunsten alternativer Kopfstabilisierung.</p></article></div><aside className="communication-case"><small>Was bedeutet Vollimmobilisation?</small><p>Bewegungsarme Rettung und Transport auf der Vakuummatratze mit achsengerechter Lagerung und zusätzlicher Kopfstabilisierung. Ein Halskragen allein immobilisiert die Wirbelsäule nicht; ein Spineboard dient vor allem der Rettung und nicht der längeren Transportlagerung.</p></aside><aside className="communication-exam-tip"><b>Sicherheit</b><p>Atemweg und Oxygenierung haben Vorrang. Eine auffällige Kopfstellung wird nicht erzwungen. Auswahl und Verzicht werden anhand Befund, Risiko, Patientenzustand und lokaler Vorgabe begründet und dokumentiert.</p></aside></div></DiagnostikSection>

      <DiagnostikSection number="05" kicker="Gefäßzugang" title="Intraossärer Zugang: Indikation, Orte und Nadeln"><div className="communication-copy"><aside className="communication-case"><small>Indikation</small><p>Ein i.o.-Zugang ist angezeigt, wenn bei einer vital bedrohten Patientin oder einem vital bedrohten Patienten ein Gefäßzugang <b>dringend benötigt</b> wird und ein i.v.-Zugang nicht rasch beziehungsweise nicht zuverlässig gelingt – zum Beispiel bei Reanimation, schwerem Schock oder Status epilepticus.</p></aside><div className="communication-grid"><article><b>Proximaler Humerus</b><p>Hoher Fluss und kurzer Weg zum zentralen Kreislauf; beim Erwachsenen häufig 45-mm-Nadel nötig. Arm anschließend sichern.</p></article><article><b>Proximale Tibia</b><p>Gut tastbare Landmarken; bei Erwachsenen häufig 25-mm-Nadel, abhängig vom Weichteilmantel.</p></article><article><b>Distale Tibia</b><p>Medial oberhalb des Malleolus; Alternative bei ungeeigneter proximaler Punktionsstelle.</p></article><article><b>Distaler Femur</b><p>Vom EZ-IO-System als pädiatrische Punktionsstelle vorgesehen; Anwendung nach Produkt- und lokaler Vorgabe.</p></article></div><h3>EZ-IO-Nadelwahl · Beispiel des verwendeten Systems</h3><div className="table-scroll diagnostik-table"><table><thead><tr><th scope="col">Farbe / Länge</th><th scope="col">Herstellerangabe</th><th scope="col">Typische Einordnung</th></tr></thead><tbody><tr><th scope="row">Rosa · 15 mm</th><td>3–39 kg</td><td>Neugeborene/kleine Säuglinge, meist Tibia</td></tr><tr><th scope="row">Blau · 25 mm</th><td>ab 3 kg</td><td>viele tibiale Zugänge bei durchschnittlichem Weichteilmantel</td></tr><tr><th scope="row">Gelb · 45 mm</th><td>ab 40 kg</td><td>meist proximaler Humerus beim Erwachsenen oder viel Weichteilgewebe</td></tr></tbody></table></div><aside className="communication-exam-tip"><b>Nicht nur nach Farbe oder Gewicht entscheiden</b><p>Punktionsort, Anatomie und Weichteildicke entscheiden mit. Wenn die Nadelspitze den Knochen berührt, muss vor dem Bohren mindestens eine schwarze Markierung außerhalb der Haut sichtbar sein. Herstelleranweisung und lokale VFA sind verbindlich. Fraktur des Zielknochens, lokale Infektion, Prothese und nicht sicher tastbare Landmarken sprechen gegen diese Punktionsstelle.</p></aside></div></DiagnostikSection>

      <DiagnostikSection number="06" kicker="Point-of-Care" title="Blutzucker messen und Fehler erkennen"><div className="communication-copy"><div className="communication-grid"><article><b>Verunreinigte Finger</b><p>Zuckerhaltige Rückstände können falsch hohe Werte erzeugen. Hände reinigen und vollständig trocknen.</p></article><article><b>Nasse Haut / kleine Probe</b><p>Wasser, Desinfektionsmittel oder Gewebsflüssigkeit können verdünnen; Teststreifen vollständig füllen und Vorgaben beachten.</p></article><article><b>Auspressen des Fingers</b><p>Starkes „Melken“ mischt Gewebsflüssigkeit bei und verfälscht die Probe.</p></article><article><b>Schock und Kälte</b><p>Schlechte periphere Perfusion macht kapilläre Messungen unzuverlässiger. Unplausible Werte wiederholen und alternative Probe nach Vorgabe nutzen.</p></article><article><b>Materialfehler</b><p>Abgelaufene, feuchte oder falsch gelagerte Streifen, ungeeignete Temperatur, verschmutztes Gerät oder falsche Codierung/Kalibrierung.</p></article><article><b>Interpretationsfehler</b><p>mg/dl und mmol/l verwechseln, Einzelwert ohne Klinik bewerten oder nach Glukosegabe den Verlauf nicht kontrollieren.</p></article></div><aside className="communication-exam-tip"><b>Merksatz</b><p>Passt der Messwert nicht zur Klinik: Technik und Einheit prüfen, an Hypoperfusion denken, Messung kontrollieren – eine klinisch manifeste Hypoglykämie aber nicht unnötig unbehandelt lassen.</p></aside></div></DiagnostikSection>

      <DiagnostikSection number="07" kicker="Reanimation" title="Effektivität beurteilen und ROSC erkennen"><div className="communication-copy"><h3>Drei technische Hilfsmittel</h3><div className="communication-grid"><article><b>CPR-Feedback</b><p>Defibrillator/Sensor beurteilt Frequenz, Drucktiefe, vollständige Entlastung und Unterbrechungen.</p></article><article><b>Wellenform-Kapnografie</b><p>Überwacht Tubuslage und Ventilation; der Trend gibt indirekte Hinweise auf den erzeugten pulmonalen Blutfluss.</p></article><article><b>Arterielle Druckkurve</b><p>Wenn bereits invasiv vorhanden, liefert sie unmittelbares physiologisches Feedback zur Perfusion unter Kompressionen.</p></article></div><h3>Zeichen eines ROSC</h3><div className="material-chips"><span>Zielgerichtete Bewegung/Bewusstsein</span><span>Spontanatmung oder Husten</span><span>Zentraler Puls</span><span>Messbarer Blutdruck</span><span>Pulsatile arterielle Kurve</span><span>Abrupter anhaltender ETCO₂-Anstieg</span></div><aside className="communication-exam-tip"><b>Prüfungsfalle</b><p>Ein organisierter EKG-Rhythmus beweist noch keinen Kreislauf. Auch ein einzelner ETCO₂-Wert darf nicht allein zum Unterbrechen oder Beenden der Reanimation führen.</p></aside></div></DiagnostikSection>

      <DiagnostikSection number="08" kicker="Reanimation" title="Reversible Ursachen: 4 H und 4 HITS"><div className="communication-copy"><div className="communication-compare"><article><small>4 H</small><h3>Physiologie wiederherstellen</h3><p><b>Hypoxie:</b> Atemwegsverlegung<br /><b>Hypovolämie:</b> massive Blutung<br /><b>Hypo-/Hyperkaliämie, metabolisch:</b> Dialysepatient mit Hyperkaliämie<br /><b>Hypo-/Hyperthermie:</b> schwere Unterkühlung</p></article><article><small>4 HITS</small><h3>Mechanische oder toxische Ursache</h3><p><b>H · Herzbeuteltamponade:</b> penetrierende Thoraxverletzung<br /><b>I · Intoxikation:</b> Opioidüberdosierung<br /><b>T · Thromboembolie:</b> Herzinfarkt oder massive Lungenarterienembolie<br /><b>S · Spannungspneumothorax:</b> schweres Thoraxtrauma</p></article></div><p>Die Ursachen werden während hochwertiger Thoraxkompressionen anhand von Anamnese, Befund, EKG, Kapnografie und – wenn verfügbar – fokussiertem Ultraschall priorisiert und behandelt.</p></div></DiagnostikSection>

      <DiagnostikSection number="09" kicker="Pharmakologie" title="Applikationswege kurz erklärt"><div className="communication-copy"><div className="table-scroll diagnostik-table"><table><thead><tr><th scope="col">Weg</th><th scope="col">Aufnahme</th><th scope="col">Prüfungsmerkmal</th></tr></thead><tbody><tr><th scope="row">oral (p.o.)</th><td>geschluckt über Magen-Darm-Trakt</td><td>langsamer, variabel; First-Pass-Effekt möglich; nur bei sicherem Schlucken</td></tr><tr><th scope="row">sublingual</th><td>über Schleimhaut unter der Zunge</td><td>rasch, umgeht zunächst Magen-Darm-Trakt und weitgehend den First-Pass-Effekt; nicht sofort schlucken</td></tr><tr><th scope="row">bukkal</th><td>über Wangenschleimhaut</td><td>Schleimhautresorption; Aufnahme kann durch Sekret oder falsche Lage variieren</td></tr><tr><th scope="row">intranasal</th><td>über Nasenschleimhaut</td><td>rasch und nadelfrei; kleine Volumina, Sekret/Blut mindern Aufnahme</td></tr><tr><th scope="row">inhalativ</th><td>über Atemwege und Alveolen</td><td>Wirkung abhängig von Atemtechnik, Ventilation und Partikelablagerung</td></tr><tr><th scope="row">intravenös</th><td>direkt in die Vene</td><td>sofortige systemische Wirkung und vollständige Verfügbarkeit</td></tr><tr><th scope="row">intraossär</th><td>über Markraum in den Kreislauf</td><td>Notfallalternative zum i.v.-Zugang; Medikamente grundsätzlich systemisch wirksam</td></tr><tr><th scope="row">intramuskulär</th><td>in den Muskel</td><td>Resorption perfusionsabhängig; bei Schock verzögert</td></tr><tr><th scope="row">subkutan</th><td>ins Unterhautfettgewebe</td><td>meist langsam; bei Zentralisation unzuverlässiger</td></tr><tr><th scope="row">rektal</th><td>über Rektumschleimhaut</td><td>variable Aufnahme; ein Teil umgeht den First-Pass-Effekt</td></tr><tr><th scope="row">transdermal</th><td>durch die Haut, meist Pflaster</td><td>langsam und lang anhaltend; Depotwirkung nach Entfernen möglich</td></tr></tbody></table></div><aside className="communication-exam-tip"><b>Prüfungsfalle</b><p>Der Applikationsweg verändert Wirkungseintritt und Zuverlässigkeit. „Sublingual“ ist nicht einfach „oral schlucken“, und i.m./s.c. können im Schock deutlich verzögert resorbiert werden.</p></aside></div></DiagnostikSection>

      <DiagnostikSection number="10" kicker="Atemweg" title="Notfallnarkose: Indikation, Zeitpunkt und Komponenten"><div className="communication-copy"><div className="communication-compare"><article><small>Zentrale Indikation 1</small><h3>Atemweg nicht geschützt</h3><p>Fehlende beziehungsweise unmittelbar bedrohte Schutzreflexe oder nicht sicher beherrschbarer Atemweg, etwa bei schwerer Bewusstseinsstörung und Aspirationsgefahr.</p></article><article><small>Zentrale Indikation 2</small><h3>Atmung reicht nicht aus</h3><p>Versagen oder drohendes Versagen von Oxygenierung beziehungsweise Ventilation trotz geeigneter weniger invasiver Maßnahmen, etwa bei Erschöpfung.</p></article></div><aside className="communication-case"><small>Der richtige Zeitpunkt</small><p>Bei klarer Indikation möglichst <b>geplant vor der vollständigen Dekompensation</b>: Teambriefing, Präoxygenierung, Monitoring, Absaugung, Kreislaufvorsorge und Rückfallebene vorbereiten. Schwere Schmerzen, Verletzungsmuster oder unbeherrschbare Agitation können die Gesamtindikation mitbestimmen; starke Schmerzen allein bedeuten zunächst Analgesie, nicht automatisch Narkose.</p></aside><h3>Drei Wirkkomponenten</h3><div className="qm-learning-chain"><span><b>1</b>Analgesie</span><i>＋</i><span><b>2</b>Hypnose</span><i>＋</i><span><b>3</b>neuromuskuläre Blockade</span></div><aside className="communication-exam-tip"><b>Kompetenzgrenze</b><p>Die konkrete Medikamentenwahl und Dosierung richtet sich nach Zustand, Kreislauf, örtlicher Vorgabe, Qualifikation und ärztlicher Entscheidung. Die Notfallnarkose ist ein risikoreicher Teamprozess mit gesicherter Nachbeatmung.</p></aside></div></DiagnostikSection>
    </div>
    {finale}
    <section className="legal-sources communication-sources"><span className="eyebrow">Fachliche Grundlage</span><h2>Abgleich und Grenzen</h2><p>Abgeglichen mit den ERC-Leitlinien 2025, der AWMF-S3-Leitlinie Polytrauma/Schwerverletzten-Behandlung, der DGAI-Handlungsempfehlung zur präklinischen Notfallnarkose, aktuellen Standards zur 12-Kanal-EKG-Anlage, Herstellerangaben des Arrow EZ-IO-Systems und WHO-Hinweisen zur kapillären Glukosemessung. Lokale Thüringer VFA, Geräteeinweisung, ÄLRD-Vorgaben und individuelle Kompetenzgrenzen bleiben maßgeblich.</p></section>
  </section>;
}
