import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct: boolean];

function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  const shift = (number * 2) % options.length;
  return {
    id: `elektrounfall-q-${String(number).padStart(2, "0")}`,
    mode: "multiple",
    prompt,
    options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })),
    source,
    difficulty,
  };
}

export const elektrounfallFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "elektrounfall-card-01", area: "Definition", question: "Wie werden Stromverletzungen grundsätzlich eingeteilt?", answer: "Niederspannung bis 1.000 V, Hochspannung über 1.000 V sowie Blitzverletzungen. Zusätzlich müssen Lichtbogenverletzungen und der Sonderfall Elektroschockpistole getrennt betrachtet werden." },
  { id: "elektrounfall-card-02", area: "Eigenschutz", question: "Was ist die erste Maßnahme beim Elektrounfall?", answer: "Erst abschalten, dann retten: Stromfluss unterbrechen, gegen Wiedereinschalten sichern und den Patienten erst nach bestätigter Spannungsfreiheit beziehungsweise Freigabe durch zuständige Spezialkräfte berühren." },
  { id: "elektrounfall-card-03", area: "Hochspannung", question: "Warum ist Hochspannung bereits ohne Berührung lebensgefährlich?", answer: "Ein Lichtbogen kann die Distanz überbrücken; zusätzlich droht Schrittspannung. Deshalb Abstand halten, Gefahrenbereich absperren und ausschließlich nach Freigabe durch den Netzbetreiber oder qualifizierte Einsatzkräfte vorgehen." },
  { id: "elektrounfall-card-04", area: "Physik", question: "Welche Faktoren bestimmen das Verletzungsausmaß?", answer: "Stromstärke, Spannung, Stromart und Frequenz, Einwirkdauer, Stromweg, Kontaktfläche sowie der elektrische Widerstand von Haut und Gewebe." },
  { id: "elektrounfall-card-05", area: "Ohmsches Gesetz", question: "Was bedeutet Stromstärke = Spannung ÷ Widerstand bei nasser Haut?", answer: "Die Formel lautet Stromstärke (I) = Spannung (U) ÷ Widerstand (R). Sinkt der Hautwiderstand durch Feuchtigkeit, kann bei gleicher Spannung mehr Strom fließen. Das Risiko schwerer innerer Schäden steigt." },
  { id: "elektrounfall-card-06", area: "Wechselstrom", question: "Warum ist haushaltsüblicher Wechselstrom besonders arrhythmogen?", answer: "Wechselstrom um 50 Hz kann anhaltende Muskelkontraktionen und ein Klebenbleiben verursachen. Trifft der Strom das Herz in einer vulnerablen Phase, können Kammerflimmern oder andere Rhythmusstörungen entstehen." },
  { id: "elektrounfall-card-07", area: "Stromweg", question: "Welcher Stromweg ist kardial besonders kritisch?", answer: "Ein Weg durch den Thorax, etwa Hand–Hand oder Hand–Fuß, kann das Herz erfassen. Der vermutete Stromweg muss aus Kontaktstellen und Unfallhergang rekonstruiert werden." },
  { id: "elektrounfall-card-08", area: "Gewebeschaden", question: "Warum kann eine kleine Strommarke eine schwere Verletzung verbergen?", answer: "Elektrische Energie kann entlang gut leitender Strukturen und tief im Muskel wirken. Knochen besitzt hohen Widerstand, wodurch in seiner Umgebung Wärme und tiefe Muskelschäden entstehen können, obwohl die Hautläsion klein bleibt." },
  { id: "elektrounfall-card-09", area: "Herz", question: "Welche kardialen Befunde sind nach Stromkontakt relevant?", answer: "Kammerflimmern, Asystolie, Brady- oder Tachyarrhythmien, AV-Blockierungen, Extrasystolen sowie ST- oder QT-Veränderungen. Monitoring und 12-Kanal-EKG gehören zur rettungsdienstlichen Beurteilung." },
  { id: "elektrounfall-card-10", area: "Muskulatur", question: "Welche Folgekette kann aus einer tiefen Muskelverletzung entstehen?", answer: "Muskelnekrose → Rhabdomyolyse → Myoglobinurie mit dunkel verfärbtem Urin → akute Nierenschädigung. Gleichzeitig droht durch Ödem ein Kompartmentsyndrom." },
  { id: "elektrounfall-card-11", area: "Blitz", question: "Welche Besonderheit gilt bei apnoischen oder pulslosen Blitzopfern?", answer: "Bei mehreren Blitzopfern kann eine umgekehrte Priorisierung sinnvoll sein: Atem- oder Kreislaufstillstand kann primär elektrisch bedingt und bei sofortiger Beatmung beziehungsweise Reanimation reversibel sein." },
  { id: "elektrounfall-card-12", area: "Keraunoparalyse", question: "Was ist eine Keraunoparalyse?", answer: "Eine meist vorübergehende Lähmung mit blassen, kühlen und pulsschwachen Extremitäten nach Blitzschlag. Sie darf eine Gefäß- oder Rückenmarksverletzung nicht ungeprüft ausschließen lassen." },
  { id: "elektrounfall-card-13", area: "Diagnostik", question: "Welche Informationen gehören in die gezielte Stromunfallanamnese?", answer: "Spannung und Stromart, Kontaktzeit, Stromweg, Bewusstlosigkeit, Atem- oder Kreislaufstillstand, Sturz oder Wegschleudern, Beschwerden, Schwangerschaft sowie Herzschrittmacher oder ICD." },
  { id: "elektrounfall-card-14", area: "Niederspannung", question: "Welche Befunde machen eine Überwachung nach Niederspannung besonders erforderlich?", answer: "Initialer Kreislaufstillstand oder Bewusstlosigkeit, Beschwerden, Verbrennungen beziehungsweise Weichteilschäden, pathologisches 12-Kanal-EKG, kardiale Vorerkrankung oder relevantes Begleittrauma." },
  { id: "elektrounfall-card-15", area: "Hochspannung", question: "Welche Konsequenz hat ein Hochspannungsunfall für das Transportziel?", answer: "Hochspannungsverletzungen erfordern eine stationäre Behandlung mit engmaschiger Kontrolle; bei relevanter Verbrennung oder tiefem Gewebeschaden ist früh ein geeignetes Verbrennungs- beziehungsweise Traumazentrum abzustimmen." },
  { id: "elektrounfall-card-16", area: "Verbrennung", question: "Wie werden elektrische Verbrennungswunden präklinisch versorgt?", answer: "Nach cABCDE vollständig entkleiden und untersuchen, Kontaktstellen steril und trocken abdecken, Wärmeverlust vermeiden, Analgesie und Flüssigkeit nach gültiger VFA durchführen und tiefe Schäden nicht aus der sichtbaren Fläche ableiten." },
  { id: "elektrounfall-card-17", area: "Elektroschockpistole", question: "Was unterscheidet eine Elektroschockpistole vom Netzstromunfall?", answer: "Es wirken kurze Impulse bei begrenzter Energie. Rettungsdienstlich stehen Pfeilverletzungen, Sturzfolgen, Erregungszustand, Intoxikation und Begleiterkrankungen im Vordergrund; eine unkritische Gleichsetzung mit dauerhaftem 230-V-Kontakt ist falsch." },
  { id: "elektrounfall-card-18", area: "Prüfungsmerksatz", question: "Wie lautet die kompakte Prioritätenfolge?", answer: "Eigenschutz → Spannungsfreiheit → cABCDE → Herzrhythmus und 12-Kanal-EKG → Ganzkörperinspektion mit Strommarken → Verbrennung, tiefer Gewebeschaden und Begleittrauma → geeignete Zielklinik." },
];

export const elektrounfallQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Maßnahmen haben vor dem Patientenkontakt bei einem Elektrounfall Priorität?", [["Stromkreis unterbrechen und gegen Wiedereinschalten sichern", true], ["Bei Hochspannung die Freigabe durch zuständige Spezialkräfte abwarten", true], ["Gefahrenbereich absperren und Eigenschutz konsequent beachten", true], ["Den Patienten sofort mit bloßen Händen wegziehen", false], ["Bei fehlender Bewegung von Spannungsfreiheit ausgehen", false]], "Erst nach sicherer Stromunterbrechung beginnt die Patientenversorgung.", 1),
  q(2, "Welche Aussagen zum Hochspannungsbereich sind richtig?", [["Lichtbogen und Schrittspannung können ohne direkten Leiterkontakt gefährden", true], ["Die Abschaltung und Freigabe gehören in die Hand zuständiger Fachkräfte", true], ["Je nach Lage kann ein Sicherheitsabstand bis zu 20 Metern erforderlich sein", true], ["Trockene Einsatzkleidung ersetzt die Spannungsfreigabe", false], ["Ein regloser Patient beweist, dass kein Strom mehr fließt", false]], "Hochspannung verlangt Distanz, Absperrung und fachliche Freigabe.", 2),
  q(3, "Welche Faktoren beeinflussen das Ausmaß einer Stromverletzung?", [["Stromstärke und Spannung", true], ["Einwirkdauer und Stromweg", true], ["Stromart, Frequenz, Kontaktfläche und Gewebewiderstand", true], ["Allein die sichtbare Größe der Strommarke", false], ["Ausschließlich das Lebensalter", false]], "Die Verletzung ergibt sich aus mehreren elektrischen und anatomischen Faktoren.", 1),
  q(4, "Welche Folgen hat nasse Haut bei gleicher anliegender Spannung?", [["Der elektrische Widerstand kann sinken", true], ["Die mögliche Stromstärke durch den Körper kann steigen", true], ["Das Risiko innerer Gewebeschäden kann zunehmen", true], ["Der Stromweg wird sicher auf die Haut begrenzt", false], ["Kammerflimmern ist dadurch ausgeschlossen", false]], "Nach I = U/R steigt bei sinkendem Widerstand die mögliche Stromstärke.", 2),
  q(5, "Welche Aussagen zu haushaltsüblichem Wechselstrom treffen zu?", [["Er kann tetanische Muskelkontraktionen und Klebenbleiben verursachen", true], ["Eine längere Kontaktzeit erhöht die Energieeinwirkung", true], ["Bei Beteiligung des Thorax können gefährliche Rhythmusstörungen entstehen", true], ["Wechselstrom kann grundsätzlich kein Kammerflimmern auslösen", false], ["Eine unverletzte Haut schließt kardiale Effekte aus", false]], "Frequenz, Kontaktzeit und Stromweg erklären die besondere Gefährdung.", 2),
  q(6, "Welche Stromwege sind wegen möglicher Herzbeteiligung besonders kritisch?", [["Hand zu Hand", true], ["Hand zu kontralateralem Fuß", true], ["Jeder rekonstruierte Weg durch den Thorax", true], ["Isolierter Kontakt zweier Finger derselben Hand ist stets tödlich", false], ["Der Stromweg ist für die Risikoeinschätzung bedeutungslos", false]], "Ein trans-thorakaler Stromweg kann das Herz erfassen.", 2),
  q(7, "Warum darf die sichtbare Hautverletzung nicht zur alleinigen Schweregradeinschätzung dienen?", [["Tiefe Muskelnekrosen können unter kleinen Kontaktstellen liegen", true], ["Knochenwiderstand kann Wärme in angrenzenden Geweben begünstigen", true], ["Nerven und Gefäße können elektrisch geschädigt sein", true], ["Tiefe Schäden treten nur bei großflächiger Rötung auf", false], ["Eine kleine Strommarke beweist einen Niederspannungsunfall", false]], "Die elektrische Verletzung kann von außen erheblich unterschätzt werden.", 3),
  q(8, "Welche kardialen Befunde müssen nach einem Stromunfall erkannt werden?", [["Kammerflimmern oder Asystolie", true], ["Brady- und Tachyarrhythmien einschließlich AV-Blockierungen", true], ["Neue ST-, QT- oder Schenkelblockveränderungen", true], ["Nur Sinustachykardie über 150/min", false], ["Ein tastbarer Puls schließt EKG-Veränderungen aus", false]], "Monitoring und 12-Kanal-EKG erfassen unterschiedliche Rhythmus- und Leitungsstörungen.", 2),
  q(9, "Welche Befunde sprechen für eine relevante tiefe Muskelverletzung?", [["Starke Muskelschmerzen oder zunehmende Schwellung", true], ["Dunkel verfärbter Urin als Hinweis auf Myoglobinurie", true], ["Spannung, Schmerz und neurologische Ausfälle einer Extremität", true], ["Isolierter Juckreiz ohne Unfallzeichen", false], ["Normale Hautfarbe schließt ein Kompartmentsyndrom sicher aus", false]], "Rhabdomyolyse und Kompartmentsyndrom sind wichtige Hochspannungsfolgen.", 3),
  q(10, "Welche Befunde gehören zum vollständigen Bodycheck nach Stromkontakt?", [["Ein- und mögliche Austrittsstellen", true], ["Verbrennungen, neurologischer Status und Durchblutung der Extremitäten", true], ["Sekundärtrauma durch Sturz, Wegschleudern oder Muskelkontraktion", true], ["Nur die vom Patienten gezeigte Kontaktstelle", false], ["Eine Untersuchung unter Kleidung ist entbehrlich", false]], "Kleine Kontaktstellen und Begleitverletzungen werden leicht übersehen.", 2),
  q(11, "Welche Angaben sind für die SAMPLER-Anamnese besonders entscheidend?", [["Spannung, Stromart, Dauer und vermuteter Stromweg", true], ["Bewusstlosigkeit, Atem- oder Kreislaufstillstand", true], ["Schwangerschaft sowie Schrittmacher oder ICD", true], ["Die Farbe des elektrischen Geräts", false], ["Nur der aktuelle Schmerzscore", false]], "Der Unfallmechanismus steuert Risiko, Überwachung und Zielklinik.", 2),
  q(12, "Welche Maßnahmen gehören zur frühen rettungsdienstlichen Versorgung?", [["cABCDE mit sofortiger Reanimationsbereitschaft", true], ["Kontinuierliches Monitoring und 12-Kanal-EKG", true], ["Wärmeerhalt, vollständige Untersuchung und Behandlung von Begleittrauma", true], ["Analgesie vor Sicherung der Vitalfunktionen", false], ["Entlassungsentscheidung ohne ärztliche Abklärung", false]], "Vitalbedrohungen, Rhythmus und verborgene Verletzungen werden parallel beurteilt.", 2),
  q(13, "Welche Konstellationen sprechen nach Niederspannung für stationäre Rhythmusüberwachung beziehungsweise weitere kardiale Diagnostik?", [["Initiale Bewusstlosigkeit oder Kreislaufstillstand", true], ["Pathologisches 12-Kanal-EKG", true], ["Verbrennungen, Weichteilverletzungen oder kardiopulmonale Beschwerden", true], ["Beschwerdefreiheit und normales EKG beweisen präklinisch absolute Gefahrlosigkeit", false], ["Eine normale Pulsoxymetrie ersetzt das EKG", false]], "Klinische Symptome und EKG entscheiden über die weitere Überwachung; die endgültige Entscheidung erfolgt ärztlich.", 3),
  q(14, "Welche Aussagen gelten für Hochspannungsverletzungen?", [["Eine stationäre Behandlung mit engmaschiger Kontrolle ist erforderlich", true], ["Tiefe Gewebeschäden können die sichtbare Oberfläche übersteigen", true], ["Ein geeignetes Verbrennungs- oder Traumazentrum kann erforderlich sein", true], ["Ein normales erstes EKG erlaubt grundsätzlich den Verzicht auf Klinik", false], ["Nur die Verbrennungsfläche bestimmt die Schwere", false]], "Hochspannung ist unabhängig von einem zunächst ruhigen EKG ein Hochrisikomechanismus.", 3),
  q(15, "Welche Aussagen zur Versorgung elektrischer Verbrennungen sind richtig?", [["Kontaktstellen steril und trocken abdecken", true], ["Wärmeverlust und Hypothermie konsequent vermeiden", true], ["Analgesie und Flüssigkeit nach der gültigen Thüringer VFA durchführen", true], ["Großflächig und anhaltend mit Eis kühlen", false], ["Die sichtbare Verbrennungsfläche bildet den tiefen Schaden zuverlässig ab", false]], "Elektrische Verbrennung verlangt Wärmeerhalt und berücksichtigt verborgene Tiefenschäden.", 2),
  q(16, "Welche Folgen können starke Muskelkontraktionen bei Stromkontakt haben?", [["Frakturen oder Luxationen", true], ["Sturz- oder Absturztrauma", true], ["Atemstillstand durch Beteiligung der Atemmuskulatur", true], ["Sichere Schutzwirkung vor Kammerflimmern", false], ["Ausschließlich oberflächliche Schmerzen", false]], "Elektrische und mechanische Verletzungen können gleichzeitig vorliegen.", 2),
  q(17, "Welche Aussagen zu Blitzverletzungen treffen zu?", [["Direkter Treffer, Seitenüberschlag, Kontakt- und Schrittspannung sind mögliche Mechanismen", true], ["Neurologische und kardiorespiratorische Ausfälle können im Vordergrund stehen", true], ["Ein Lichtenberg-Muster ist ein charakteristischer Hautbefund", true], ["Blitzverletzungen sind lediglich thermische Verbrennungen", false], ["Fehlende Eintrittswunde schließt einen Blitzschlag aus", false]], "Blitzschäden entstehen über mehrere Übertragungsmechanismen und Organsysteme.", 2),
  q(18, "Welche Aussagen zur Keraunoparalyse sind richtig?", [["Sie kann nach Blitzschlag mit vorübergehender Lähmung auftreten", true], ["Extremitäten können kühl, blass und pulsschwach erscheinen", true], ["Gefäß- und Rückenmarksverletzungen müssen dennoch geprüft werden", true], ["Sie beweist eine komplette Rückenmarksdurchtrennung", false], ["Sie macht eine neurologische Untersuchung überflüssig", false]], "Keraunoparalyse ist eine wichtige, aber nicht ausschließende Differenzialdiagnose.", 3),
  q(19, "Was ist bei mehreren Blitzopfern mit Atem- oder Kreislaufstillstand besonders?", [["Eine umgekehrte Priorisierung kann gerechtfertigt sein", true], ["Sofortige Beatmung und Reanimation können eine gute Erfolgschance haben", true], ["Apnoe kann einer sekundären Kreislaufdepression vorausgehen", true], ["Pulslosigkeit bedeutet bei Blitzschlag immer Aussichtslosigkeit", false], ["Nur gehfähige Patienten werden zuerst behandelt", false]], "Elektrisch bedingte Stillstände können bei schneller Therapie reversibel sein.", 3),
  q(20, "Welche Prüfungsfallen beim Stromunfall müssen vermieden werden?", [["Eine kleine Strommarke als Bagatelle zu bewerten", true], ["Ein unauffälliges Monitoring mit einem vollständigen 12-Kanal-EKG gleichzusetzen", true], ["Sekundärtrauma und Kompartmentsyndrom zu übersehen", true], ["Bei Hochspannung auf die Freigabe zu warten", false], ["Den Unfallmechanismus gezielt zu erfragen", false]], "Die größten Fehler entstehen durch unterschätzte Mechanik, Tiefenschäden und unvollständige Diagnostik.", 3),
  q(21, "Welche Aussagen zum Fehlerstrom-Schutzschalter sind korrekt?", [["Er vergleicht hin- und zurückfließende Ströme", true], ["Bei einer relevanten Differenz kann er den Stromkreis abschalten", true], ["Seine Anwesenheit schließt eine Verletzung nicht sicher aus", true], ["Er macht Eigenschutzmaßnahmen überflüssig", false], ["Er verhindert jeden Lichtbogen im Hochspannungsbereich", false]], "Ein RCD reduziert Risiken, ersetzt aber weder Spannungsfreiheit noch medizinische Beurteilung.", 3),
  q(22, "Welche Punkte stehen nach Einsatz einer Elektroschockpistole im Vordergrund?", [["Pfeilverletzungen und deren Lokalisation", true], ["Sturzfolgen, Erregungszustand, Intoxikation und Begleiterkrankungen", true], ["Klinische Untersuchung und 12-Kanal-EKG nach regionalem Vorgehen", true], ["Automatische Gleichsetzung mit langem Haushaltsstromkontakt", false], ["Unkritische Entfernung eines Pfeils aus Auge oder Hals", false]], "Die Impulswaffe ist ein eigener Mechanismus; kritische Pfeillagen benötigen spezielle Versorgung.", 3),
  q(23, "Welche Transportentscheidungen sind fachlich plausibel?", [["Hochspannung in eine Klinik mit engmaschiger Überwachung und passender Fachkompetenz", true], ["Relevante elektrische Verbrennung früh mit einem Verbrennungszentrum abstimmen", true], ["Begleittrauma, kardiale Instabilität und neurologische Befunde bei der Zielwahl berücksichtigen", true], ["Bei normaler Haut grundsätzlich auf einen Transport verzichten", false], ["Klinikwahl ausschließlich nach kürzester Fahrzeit treffen", false]], "Mechanismus, Organbeteiligung und regionale Strukturen bestimmen das Ziel.", 3),
  q(24, "Welche Antwort bildet die vollständige rettungsdienstliche Prioritätenfolge ab?", [["Eigenschutz und bestätigte Spannungsfreiheit vor Patientenkontakt", true], ["cABCDE, Monitoring, 12-Kanal-EKG und Ganzkörperinspektion", true], ["Verbrennung, tiefe Gewebeschäden und Begleittrauma behandeln sowie Zielklinik abstimmen", true], ["Sichtbare Strommarke versorgen und ohne weitere Diagnostik beenden", false], ["Bei Bewusstsein grundsätzlich von fehlender Herzbeteiligung ausgehen", false]], "Eine starke Prüfungsantwort verbindet Einsatzsicherheit, Vitalfunktionen, Rhythmusdiagnostik und Trauma-/Verbrennungsversorgung.", 3),
];
