import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function EugLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, title: string, body: ReactNode) => <section className="lesson-section" key={number}><header className="chapter-heading"><span>{number}</span><div><small>Extrauteringravidität</small><h2>{title}</h2></div></header><div className="lesson-prose script-copy">{body}</div></section>;
  return <article className="lesson-article eug-lesson">
    <div className="lesson-intro"><p className="lead">Unterbauchschmerz in der Frühschwangerschaft verlangt eine rasche Einordnung: Eine extrauterine Schwangerschaft kann bei Ruptur zu einer lebensbedrohlichen inneren Blutung führen.</p></div>
    {section("01", "Definition", <p>Eine Extrauteringravidität (EUG) ist die Einnistung einer befruchteten Eizelle außerhalb der Gebärmutterhöhle. Meist liegt sie im Eileiter; seltener sind Eierstock oder Bauchhöhle betroffen.</p>)}
    {section("02", "Anatomie und Physiologie", <>
      <div className="eug-anatomy-grid"><div className="eug-anatomy-card outer"><small>Violett markiert · äußere Genitale</small><h3>Äußere Geschlechtsorgane</h3><ul className="script-list"><li><b>Große Schamlippen:</b> behaarte, pigmentierte Hautfalten mit Unterhautfett und Hautdrüsen; sie schützen den Vorhof.</li><li><b>Kleine Schamlippen:</b> unbehaarte Falten; sie begrenzen den Scheidenvorhof und bilden vorn die Klitorisvorhaut.</li><li><b>Klitoris:</b> empfindliches Schwellkörperorgan.</li><li><b>Scheidenvorhof:</b> Bereich von Harnröhren- und Scheidenöffnung; hier münden auch die Bartholin-Drüsen.</li><li><b>Schamhügel:</b> gepolsterter Bereich über der Symphyse.</li></ul></div><div className="eug-anatomy-card inner"><small>Rosa markiert · innere Genitale</small><h3>Innere Geschlechtsorgane</h3><ul className="script-list"><li><b>Scheide:</b> Verbindung nach außen; Schleimhaut mit Milchsäurebakterien und saurem Milieu.</li><li><b>Eileiter:</b> Fimbrientrichter, Ampulle und Isthmus transportieren die Eizelle Richtung Uterus; Flimmerepithel unterstützt dies.</li><li><b>Gebärmutter:</b> Fundus, Corpus und Cervix mit Portio; das Endometrium besitzt Basal- und Funktionsschicht.</li><li><b>Eierstöcke:</b> Eizellreifung, Eisprung und Bildung von Geschlechtshormonen.</li><li><b>Adnexe:</b> Eileiter und Eierstöcke mit Haltestrukturen.</li></ul></div></div>
      <div className="figure-grid"><Figure src="/lessons/eug/anatomie-frontal.png" alt="Frontalansicht von Eileitern, Eierstöcken, Uterus und äußeren Genitalstrukturen mit farbigen Beschriftungen" caption="Anatomie · Frontalansicht" /><Figure src="/lessons/eug/anatomie-sagittal.png" alt="Sagittalschnitt des weiblichen Beckens mit rosa markierten inneren und violett markierten äußeren Geschlechtsorganen" caption="Anatomie · Sagittalschnitt" /></div>
      <p>Nach dem Eisprung gelangt die Eizelle in den Eileiter. Dort kann die Befruchtung stattfinden; die befruchtete Eizelle wandert anschließend zur Gebärmutterhöhle und nistet sich normalerweise in der Gebärmutterschleimhaut ein.</p>
    </>)}
    {section("03", "Pathophysiologie und Ursachen", <><p>Eine gestörte Passage durch den Eileiter begünstigt die Einnistung außerhalb der Gebärmutter. Mechanische Hindernisse können angeboren sein oder nach Entzündungen, Operationen und Endometriose entstehen. Auch eine verringerte Flimmerhärchenaktivität oder Tubenbeweglichkeit, unter anderem durch Rauchen, spielt eine Rolle. Eine frühere EUG und Eingriffe an den Eileitern sind für die Anamnese wichtig.</p><p>Wächst eine Schwangerschaft in der engen Tube, kann die Wand einreißen. Die Folge ist eine Blutung in die Bauchhöhle bis hin zum hämorrhagischen Schock. Beschwerden treten häufig im ersten Trimenon auf, besonders um die 6.–8. Schwangerschaftswoche.</p><Figure src="/lessons/eug/lokalisationen.png" alt="Schematische Lokalisationen einer Extrauteringravidität an Eileiter, Eierstock, Gebärmutterhals und Bauchhöhle" caption="Mögliche Einnistungsorte" wide /></>)}
    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", <><p>Einseitiger Unterbauchschmerz, ausbleibende Regelblutung oder Schmierblutung sowie mögliche Schwangerschaftszeichen ergeben zusammen einen wichtigen Verdacht. Druckschmerz und Abwehrspannung können auf ein akutes Abdomen hinweisen.</p><aside className="red-flags"><span>!</span><div><small>Red Flags</small><h3>Kreislaufkollaps oder Zeichen einer inneren Blutung</h3><p>Blässe, Schwäche, Schwindel, Synkope, Tachykardie, Hypotonie und zunehmender Bauchschmerz sind bei möglicher Schwangerschaft zeitkritisch. Die sichtbare vaginale Blutung bildet den inneren Blutverlust nicht zuverlässig ab.</p></div></aside></>)}
    {section("05", "Komplikationen und Gefahren", <><p>Bei Tubarruptur drohen intraabdominelle Blutung und hämorrhagischer Schock. Eine Bauchhöhlenschwangerschaft kann benachbarte Organe und Gefäße gefährden. Die Kreislauflage kann sich rasch verschlechtern; ein zunächst stabiler Befund ist keine Entwarnung.</p></>)}
    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", <div className="material-chips">{["Notfallrucksack", "EKG / Monitoring", "Blutdruck / SpO₂", "i.v.-Material", "Infusion", "Sauerstoff / Beatmung", "Absaugung", "Wärmeerhalt", "Transportmittel"].map(x => <span key={x}>{x}</span>)}</div>)}
    {section("07", "Erstmaßnahmen und Anamnese", <><div className="extremity-action-grid"><div><span>01</span><b>Priorisieren</b><p>Eigenschutz, cABCDE, Kreislauf und Blutungszeichen beurteilen.</p></div><div><span>02</span><b>Einordnen</b><p>OPQRST und SAMPLERS, besonders letzte Regelblutung und Schwangerschaftsmöglichkeit.</p></div><div><span>03</span><b>Untersuchen</b><p>Abdomen schonend beurteilen, Blutung erfragen und beobachten.</p></div><div><span>04</span><b>Organisieren</b><p>Monitoring, Notarztbedarf und frühzeitige Zielklinikplanung.</p></div></div><h3>SAMPLERS · auf EUG fokussiert</h3><div className="samplers-grid"><p><b>S · Symptome</b>Schmerz, Blutung, Schwindel</p><p><b>A · Allergien</b>Für Maßnahmen relevant</p><p><b>M · Medikamente</b>Auch Verhütung</p><p><b>P · Vorgeschichte</b>Frühere EUG, OP, Entzündung</p><p><b>L · Letzte Aufnahme</b>Essen, Trinken</p><p><b>E · Ereignis</b>Beginn und Verlauf</p><p><b>R · Risiken</b>Rauchen, Endometriose</p><p><b>S · Schwangerschaft</b>Test, letzte Regel, SSW</p></div><p><b>OPQRST:</b> Beginn, Auslöser, Schmerzcharakter, Ort/Ausstrahlung, Stärke und Zeitverlauf. Blutungsbeginn, Menge, Farbe sowie Gerinnsel oder Gewebe zusätzlich erfragen.</p></>)}
    {section("08", "Differenzialdiagnosen und Entscheidungsfindung", <><div className="differential-grid">{["Fehlgeburt", "Adnexitis", "Appendizitis", "Harnwegsinfekt", "Andere Ursache des akuten Abdomens"].map(x => <span key={x}>{x}</span>)}</div><p>Die Arbeitsdiagnose wird präklinisch aus Schwangerschaftsmöglichkeit, Beschwerdeverlauf, Abdomen- und Kreislaufbefund gebildet; ein einzelnes Symptom beweist oder widerlegt die EUG nicht. Bei Kreislaufinstabilität hat die Versorgung eines möglichen Blutungsschocks Vorrang vor einer ausgedehnten Diagnostik am Einsatzort.</p></>)}
    {section("09", "Weitere Maßnahmen", <><div className="eug-care-grid"><div><span>01</span><b>Verlauf sichern</b><small>Vitalwerte seriell prüfen · Wärmeerhalt · schonend lagern</small></div><div><span>02</span><b>Bedarfsgerecht handeln</b><small>i.v.-Zugang nach Indikation · O₂ nach Oxygenierung und Klinik</small></div><div><span>03</span><b>Früh eskalieren</b><small>Notarzt bei starken Schmerzen, Schockzeichen oder kritischer Lage</small></div><div><span>04</span><b>Transport priorisieren</b><small>Keine vermeidbare Verzögerung · Verlauf dokumentieren</small></div></div><div className="eug-destination"><span>→</span><div><small>Ziel und Übergabe</small><b>Gynäkologie mit operativer Versorgung</b><p>Verdacht, Schwangerschaftsdaten, Blutung, Kreislaufverlauf und Maßnahmen voranmelden.</p></div></div></>)}
    {section("10", "VFA Thüringen 2026/2027", <><p>Für die präklinische Versorgung sind besonders der Leitpfad zur Notarztnachforderung und der intravenöse Zugang relevant. Die Originalalgorithmen sind vergrößerbar und einklappbar.</p><div className="vfa-stack"><Vfa src="/lessons/lungenarterienembolie/vfa-notarztnachforderung-16.png" alt="Thüringer Leit­algorithmus L5 zur Notarztnachforderung" caption="VFA L5 · Notarztnachforderung" /><Vfa src="/lessons/lungenarterienembolie/vfa-intravenoeser-zugang-19.png" alt="Thüringer Verfahrensanweisung 01 intravenöser Zugang, Leitalgorithmus L7" caption="VFA 01 / L7 · Intravenöser Zugang" /></div></>)}
    {children}
    <p className="lesson-source">Grundlage: deine Unterlage „Print 8.pdf“. Abbildungen originalgetreu aus der Vorlage; präklinische Abläufe mit den Thüringer VFA 2026/2027 abgeglichen. Klinische Red Flags und Zielversorgung mit der <a href="https://www.nice.org.uk/guidance/ng126/chapter/recommendations" target="_blank" rel="noreferrer">NICE-Leitlinie NG126</a> abgeglichen.</p>
  </article>;
}
