import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct: boolean];
function q(n: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3): ThoraxtraumaChoiceQuestion {
  return { id: `eug-q-${String(n).padStart(2, "0")}`, mode: "multiple", prompt, options: options.map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty };
}

export const eugFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "eug-card-01", area: "Definition", question: "Definieren Sie die EUG und grenzen Sie die häufigste von selteneren Lokalisationen ab.", answer: "Einnistung einer befruchteten Eizelle außerhalb der Gebärmutterhöhle; am häufigsten im Eileiter, seltener an Ovar oder in der Bauchhöhle." },
  { id: "eug-card-02", area: "Anatomie außen", question: "Ordnen Sie große und kleine Schamlippen, Klitoris und Scheidenvorhof den äußeren Genitalien zu und erklären Sie deren Lage und Funktion.", answer: "Große Schamlippen schützen den Vorhof, kleine Schamlippen begrenzen ihn und bilden vorn die Klitorisvorhaut; die Klitoris enthält Schwellkörper. Im Vorhof liegen Harnröhren- und Scheidenöffnung sowie die Mündungen der Bartholin-Drüsen." },
  { id: "eug-card-03", area: "Anatomie innen", question: "Benennen Sie die inneren Genitale und erklären Sie, welche Strukturen als Adnexe zusammengefasst werden.", answer: "Vagina, Uterus, Eileiter und Ovarien. Als Adnexe werden Eileiter und Ovarien mit ihren Haltestrukturen zusammengefasst." },
  { id: "eug-card-04", area: "Tubentransport", question: "Welche Abschnitte der Tube sind in der Vorlage dargestellt und weshalb ist ihre Funktion für die EUG entscheidend?", answer: "Fimbrientrichter, Ampulle und Isthmus. Flimmerepithel und Tubenbewegung unterstützen den Weg der Eizelle zur Gebärmutter; eine Transportstörung begünstigt tubare Einnistung." },
  { id: "eug-card-05", area: "Uterus", question: "Ordnen Sie Fundus, Corpus, Cervix, Portio und die beiden Endometriumschichten ein.", answer: "Fundus ist der Gebärmuttergrund, Corpus der Körper, Cervix der Hals und Portio der sichtbare Muttermundanteil. Das Endometrium hat eine Basalschicht und eine zyklisch abgestoßene Funktionsschicht." },
  { id: "eug-card-06", area: "Ursachen", question: "Nennen Sie mechanische und funktionelle Ursachen, die den Tubentransport stören können.", answer: "Angeborene Hindernisse, Narben nach Entzündung oder Operation, Endometriose und verminderte Flimmerhärchen- oder Tubenaktivität, unter anderem bei Rauchen." },
  { id: "eug-card-07", area: "Pathophysiologie", question: "Leiten Sie von tubarer Einnistung bis zum hämorrhagischen Schock die entscheidende Kette her.", answer: "Einnistung in der Tube → Wachstum und Dehnung der Tubenwand → mögliche Ruptur → Blutung in die freie Bauchhöhle → Kreislaufversagen/hämorrhagischer Schock." },
  { id: "eug-card-08", area: "Symptome", question: "Welche Kombination stützt den EUG-Verdacht, und warum schließt geringe vaginale Blutung eine große innere Blutung nicht aus?", answer: "Frühschwangerschaft oder Amenorrhö, einseitiger Unterbauchschmerz, Schmierblutung und Druckschmerz. Bei Ruptur geht Blut in die Bauchhöhle, nicht zwingend sichtbar nach vaginal." },
  { id: "eug-card-09", area: "Red Flags", question: "Welche Befunde machen aus einem EUG-Verdacht einen zeitkritischen Schockverdacht?", answer: "Synkope, Schwindel, Blässe, Tachykardie, Hypotonie, zunehmender Bauchschmerz, Abwehrspannung und Kreislaufkollaps." },
  { id: "eug-card-10", area: "Anamnese", question: "Welche SAMPLERS- und OPQRST-Punkte beeinflussen die präklinische Entscheidung besonders?", answer: "Letzte Regelblutung, Schwangerschaftstest/SSW, frühere EUG, Tuben-OP oder Entzündung, Endometriose, Rauchen und Verhütung; Schmerzbeginn/-seite/-verlauf sowie Blutungsmenge, Farbe, Gerinnsel/Gewebe." },
  { id: "eug-card-11", area: "Differenzialdiagnosen", question: "Nennen Sie mindestens vier wichtige Differenzialdiagnosen und erläutern Sie, wie Sie präklinisch vorgehen.", answer: "Fehlgeburt, Adnexitis, Appendizitis, Harnwegsinfekt und andere Ursachen eines akuten Abdomens. Präklinisch keine sichere Ausschlussdiagnose erzwingen, sondern Schwangerschaftsmöglichkeit, Bauch- und Kreislaufbefund zusammenführen." },
  { id: "eug-card-12", area: "Versorgung", question: "Priorisieren Sie Versorgung und Transport bei vermuteter rupturierter EUG.", answer: "cABCDE und wiederholte Kreislaufkontrolle, Notarztnachforderung, i.v.-Zugang nach Indikation, Wärmeerhalt, bedarfsgerechter Sauerstoff, schonende Lagerung und rascher Transport in eine geeignete gynäkologisch-operativ versorgende Klinik mit Voranmeldung." },
  { id: "eug-card-13", area: "VFA", question: "Welche beiden Thüringer Algorithmen sind hier eingebunden und wofür sind sie relevant?", answer: "L5 Notarztnachforderung bei gefährlicher/instabiler Lage; VFA 01 beziehungsweise Leitalgorithmus L7 für den intravenösen Zugang bei Medikamentengabe, Infusionstherapie oder kritischem Notfall." },
];

export const eugQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Eine Patientin mit möglicher Frühschwangerschaft hat rechtsseitigen Unterbauchschmerz. Welche Aussagen zur EUG treffen zu?", [["Eine Einnistung außerhalb der Gebärmutterhöhle ist möglich",true],["Der Eileiter ist der häufigste Einnistungsort",true],["Eine EUG setzt eine sichtbare vaginale Blutung voraus",false],["Eine Bauchhöhlenlokalisation ist grundsätzlich ausgeschlossen",false],["Die Schwangerschaftsmöglichkeit gehört früh in die Anamnese",true]], "Die Lokalisation liegt außerhalb der Gebärmutterhöhle, meist tubar; fehlende sichtbare Blutung schließt sie nicht aus.", 1),
  q(2, "Welche Zuordnungen der farblich getrennten Anatomie stimmen?", [["Große und kleine Schamlippen gehören zu den äußeren Genitalien",true],["Uterus, Tube und Ovarien zählen zu den inneren Genitalien",true],["Die Klitoris liegt im Inneren der Gebärmutter",false],["Bartholin-Drüsen münden im Scheidenvorhof",true],["Die Cervix ist ein Abschnitt der Tube",false]], "Die Vorlage trennt äußere und innere Strukturen; Bartholin-Drüsen münden am Vorhof.", 1),
  q(3, "Welche Aussagen zur Tube erklären das Risiko einer tubaren Einnistung?", [["Die Ampulle gehört zum Eileiter",true],["Flimmerepithel unterstützt den Transport Richtung Uterus",true],["Narben können den Transportweg beeinträchtigen",true],["Die Tube ist identisch mit der Gebärmutterhöhle",false],["Die Befruchtung findet nur im Endometrium statt",false]], "Eine gestörte Passage nach tubarer Befruchtung begünstigt EUG.", 2),
  q(4, "Welche anatomischen Aussagen sind korrekt?", [["Der Fundus ist der Gebärmuttergrund",true],["Die Cervix bildet den Gebärmutterhals",true],["Die Funktionsschicht des Endometriums wird zyklisch abgestoßen",true],["Der Isthmus ist die Scheidenöffnung",false],["Adnexe bezeichnen allein die äußeren Schamlippen",false]], "Uterusabschnitte und Adnexe sind klar voneinander abzugrenzen.", 2),
  q(5, "Welche anamnestischen Befunde erhöhen bei Unterbauchschmerz die Aufmerksamkeit für eine EUG?", [["Frühere EUG",true],["Operation am Eileiter",true],["Endometriose oder frühere Entzündung",true],["Jede frühere Geburt schließt eine EUG sicher aus",false],["Rauchen ist für den Tubentransport grundsätzlich ohne Bedeutung",false]], "Narben, Entzündung, Endometriose und funktionelle Tubenstörung sind relevant.", 2),
  q(6, "Eine EUG wächst in der Tube. Welche Schritte der Gefährdungskette sind plausibel?", [["Dehnung und mögliche Ruptur der Tubenwand",true],["Blutung in die Bauchhöhle",true],["Hämorrhagischer Schock bei erheblichem Blutverlust",true],["Ruptur ist nur bei starker äußerer Blutung möglich",false],["Eine normale Hautfarbe am Anfang schließt einen späteren Schock aus",false]], "Tubarruptur kann eine zunächst verborgene, lebensbedrohliche Blutung verursachen.", 2),
  q(7, "Welche Kombination stützt die Arbeitsdiagnose bei möglicher Frühschwangerschaft?", [["Einseitiger Unterbauchschmerz",true],["Ausbleibende Regel oder Schmierblutung",true],["Druckschmerz oder Abwehrspannung",true],["Ein negativer Blutungsbefund beweist eine intrauterine Schwangerschaft",false],["Einseitiger Schmerz beweist allein eine Appendizitis",false]], "Kein Einzelzeichen beweist EUG; die Konstellation ist entscheidend.", 2),
  q(8, "Eine Patientin berichtet nur geringe Schmierblutung, ist aber blass und tachykard. Welche Schlüsse sind richtig?", [["Innere Blutung muss trotz geringer sichtbarer Blutung bedacht werden",true],["Der Kreislaufbefund hat hohe Priorität",true],["Zeitkritische Transportplanung ist angezeigt",true],["Die geringe vaginale Blutung quantifiziert den gesamten Blutverlust",false],["Eine ausführliche Untersuchung am Einsatzort muss den Transport immer abwarten lassen",false]], "Vaginale Blutungsmenge bildet eine mögliche Bauchhöhlenblutung nicht zuverlässig ab.", 3),
  q(9, "Welche Befunde sprechen bei möglicher EUG für eine kritische Verschlechterung?", [["Synkope oder Kreislaufkollaps",true],["Zunehmender Schmerz mit Abwehrspannung",true],["Tachykardie und Hypotonie",true],["Allein beschwerdefreie Atmung schließt Blutungsschock aus",false],["Eine frühere stabile Messung macht Re-Evaluation entbehrlich",false]], "Schock- und Akut-Abdomen-Zeichen verlangen sofortige Neubewertung.", 2),
  q(10, "Welche Fragen gehören zur fokussierten Schwangerschaftsanamnese?", [["Wann war die letzte Regelblutung?",true],["Gab es bereits eine EUG oder Tubenoperation?",true],["Ist ein Schwangerschaftstest bekannt?",true],["Die Seite des Schmerzes ist für OPQRST irrelevant",false],["Blutungsbeginn und Gerinnsel dürfen nicht erfragt werden",false]], "Zeitachse, Schwangerschaftsstatus, Vorerkrankungen und Blutungsmerkmale beeinflussen den Verdacht.", 1),
  q(11, "Welche Aussagen zur präklinischen Differenzialdiagnose sind angemessen?", [["Fehlgeburt kann Schmerzen und Blutung auslösen",true],["Appendizitis kann ebenfalls Unterbauchschmerz verursachen",true],["Adnexitis gehört in die Abgrenzung",true],["Ein Schwangerschaftstest allein lokalisiert die Schwangerschaft sicher",false],["Eine EUG kann präklinisch durch einmalige Bauchpalpation sicher ausgeschlossen werden",false]], "Ähnliche Leitsymptome erfordern eine offene Differenzialdiagnose; Lokalisation braucht klinische Abklärung.", 2),
  q(12, "Welche Einsatzmaterialien sind bei EUG-Verdacht mit möglicher Kreislaufgefährdung sinnvoll?", [["Monitoring und Blutdruckmessung",true],["Material für intravenösen Zugang",true],["Sauerstoff- und Beatmungsmöglichkeit",true],["Allein ein Verbandpäckchen ohne Kreislaufausrüstung",false],["Ein Geburtenset ersetzt die Schockausrüstung",false]], "Ausrüstung folgt dem Risiko innerer Blutung und Kreislaufverschlechterung.", 1),
  q(13, "Die Patientin ist zunächst kreislaufstabil. Welche Vorgehensweisen sind richtig?", [["Vitalparameter im Verlauf wiederholt prüfen",true],["Schwangerschaftsmöglichkeit und Beschwerdebeginn dokumentieren",true],["Geeignete gynäkologische Zielversorgung planen",true],["Ein stabiler Erstwert schließt spätere Tubarruptur aus",false],["Den Transport bis zur sicheren Diagnose am Einsatzort verschieben",false]], "Eine mögliche EUG bleibt auch bei initialer Stabilität abklärungsbedürftig.", 3),
  q(14, "Welche Aussagen zum Sauerstoff bei EUG-Verdacht sind tragfähig?", [["Die Oxygenierung und klinische Situation leiten die Gabe",true],["Bei respiratorischer Beeinträchtigung muss die Atmung mitversorgt werden",true],["Sauerstoff ersetzt weder Schockbeurteilung noch Transport",true],["Jede Patientin braucht ungeachtet der SpO₂ automatisch maximalen Flow",false],["Normale SpO₂ schließt eine innere Blutung aus",false]], "Sauerstoff ist bedarfsgerecht; normale Sättigung ist keine Blutungsdiagnostik.", 3),
  q(15, "Welche Schritte passen zur VFA 01 / L7 bei kritischer EUG-Lage?", [["Den intravenösen Zugang indikationsbezogen erwägen",true],["Punktionsstelle auf Kontraindikationen prüfen",true],["Erfolg kontrollieren und Zugang dokumentieren",true],["Unbegrenzt oft ohne Neubewertung punktieren",false],["Der Zugang darf die notwendige Transportentscheidung grundsätzlich verdrängen",false]], "Der VFA-Pfad verbindet Indikationsprüfung, sichere Durchführung und Monitoring.", 3),
  q(16, "Welche Bewertungen zur Notarztnachforderung nach L5 sind bei EUG-Verdacht richtig?", [["Schockzeichen rechtfertigen eine frühe Eskalation",true],["Starke Schmerzen und instabile Lage werden im Gesamtkontext bewertet",true],["Nachforderung und zeitkritische Transportplanung können parallel laufen",true],["Eine Nachforderung ersetzt automatisch die klinische Zielwahl",false],["Bei Kreislaufkollaps wird bis zur sicheren Bildgebung am Einsatzort gewartet",false]], "L5 strukturiert die Nachforderung; sie ergänzt Versorgung und Transport.", 3),
  q(17, "Welche Inhalte gehören in eine qualifizierte Voranmeldung?", [["Verdacht auf EUG und mögliche Schwangerschaftswoche",true],["Schmerzbeginn, Seite und Blutungsverlauf",true],["Kreislaufbefunde mit Entwicklung und bisherige Maßnahmen",true],["Nur die Angabe 'Bauchschmerz' ohne zeitliche Daten",false],["Verzicht auf Synkopenangabe, weil sie unspezifisch ist",false]], "Die Klinik braucht Verdacht, Zeitachse, Kreislaufdynamik und Maßnahmen.", 2),
  q(18, "Eine Patientin mit EUG-Verdacht synkopiert beim Aufstehen, SpO₂ 99 %, nur geringe Schmierblutung. Welche Schritte sind angemessen?", [["cABCDE und Kreislauf nach der Synkope erneut beurteilen",true],["Eine intraabdominelle Blutung unabhängig von der SpO₂ erwägen",true],["Notarzt und gynäkologisch-operative Zielversorgung einplanen",true],["Aus normaler SpO₂ auf ausreichendes zirkulierendes Blutvolumen schließen",false],["Die geringe äußere Blutung als verlässliches Maß des Gesamtverlusts verwenden",false]], "Normale Sauerstoffsättigung und geringe vaginale Blutung schließen einen Blutungsschock nicht aus.", 3),
  q(19, "Die Patientin ist bei EUG-Verdacht noch normotensiv, berichtet aber zunehmenden Schmerz. Welche Zielklinik-Entscheidungen sind richtig?", [["Gynäkologische Diagnostik muss zeitnah erreichbar sein",true],["Bei möglicher Ruptur ist operative Versorgung mitzudenken",true],["Voranmeldung mit Verlaufsdaten hilft der Vorbereitung",true],["Der aktuelle Blutdruck allein macht operative Vorhaltung entbehrlich",false],["Eine Gastroenterologie ohne gynäkologische Versorgung ist unabhängig vom Verlauf gleichwertig",false]], "Ein aktuell erhaltener Blutdruck darf die Wahl einer geeigneten gynäkologisch-operativen Versorgung nicht verhindern.", 3),
  q(20, "Welche gedanklichen Fehler können eine gefährliche EUG übersehen lassen?", [["Geringe vaginale Blutung mit geringem Gesamtblutverlust gleichsetzen",true],["Einen normalen Einzelblutdruck als dauerhafte Entwarnung ansehen",true],["Die Schwangerschaftsmöglichkeit bei Unterbauchschmerz nicht erfragen",true],["Schmerz- und Kreislaufverlauf wiederholt dokumentieren",false],["Die Zielklinik früh über Synkope und EUG-Verdacht informieren",false]], "Innere Blutung, Schwangerschaftsanamnese und Befunddynamik sind die zentralen Prüfungsfallen.", 3),
  q(21, "Linksseitiger Schmerz, Amenorrhö, Schmierblutung und zunehmend kalte Haut: Welche Entscheidungen sind zusammen tragfähig?", [["EUG mit möglicher intraabdomineller Blutung priorisieren",true],["Kreislauf seriell prüfen und den Transport parallel organisieren",true],["L5-Notarztbedarf prüfen und gynäkologisch-operative Versorgung voranmelden",true],["Bei noch normaler SpO₂ die Schockprüfung bis zur Klinikübergabe aussetzen",false],["Erst den genauen Einnistungsort am Einsatzort sichern und dann transportieren",false]], "Schwangerschaftsverdacht plus Schockzeichen verlangt parallele Stabilisierung und Transportorganisation.", 3),
];
