import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct?: boolean];
const q = (number: number, prompt: string, options: Option[], source: string): ThoraxtraumaChoiceQuestion => ({ id: `explosionsverletzung-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: options.map(([text, correct]) => ({ text, correct })), source, difficulty: 3 });

export const explosionsverletzungFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "explosionsverletzung-card-01", area: "Definition", question: "Warum ist eine Explosionsverletzung häufig ein kombiniertes Trauma?", answer: "Druckwelle, Splitter, Verlagerung beziehungsweise Verschüttung sowie Hitze, Rauch und toxische Stoffe können gleichzeitig wirken." },
  { id: "explosionsverletzung-card-02", area: "Klassifikation", question: "Welche Organe sind typisch primär durch die Druckwelle gefährdet?", answer: "Vor allem gasgefüllte beziehungsweise luftangrenzende Strukturen: Ohr, Nasennebenhöhlen, Lunge sowie Magen-Darm-Trakt." },
  { id: "explosionsverletzung-card-03", area: "Klassifikation", question: "Was unterscheidet sekundäre und tertiäre Explosionsverletzungen?", answer: "Sekundär: Fragmente treffen den Körper. Tertiär: Der Körper selbst wird fortgeschleudert, prallt auf oder wird verschüttet." },
  { id: "explosionsverletzung-card-04", area: "Klassifikation", question: "Was umfasst die quartäre Kategorie?", answer: "Andere explosionsassoziierte Schäden wie Verbrennung, Inhalationsverletzung, toxische Exposition, Asphyxie, Crush und Exazerbation bestehender Erkrankungen." },
  { id: "explosionsverletzung-card-05", area: "Prüfungsgrenze", question: "Wie ist die quinäre Kategorie einzuordnen?", answer: "Sie ist nicht einheitlich definiert; oft bezeichnet sie toxische/CBRN-Zusätze oder eine überschießende systemische Reaktion. In der Prüfung diese Unsicherheit nennen." },
  { id: "explosionsverletzung-card-06", area: "Blast Lung", question: "Erkläre die Kette vom Druckimpuls zur Hypoxämie.", answer: "Druck deformiert Alveolen, schädigt Septen und Kapillaren, verursacht Blutung und Ödem und führt dadurch zu V/Q-Störung, Diffusionsstörung und Hypoxämie." },
  { id: "explosionsverletzung-card-07", area: "Gasembolie", question: "Wie entsteht eine arterielle Gasembolie beim Blast Lung?", answer: "Durch eine alveolo-vaskuläre Verbindung gelangt Luft in Lungenvenen, linkes Herz und systemische Arterien; neurologische oder koronare Embolien sind möglich." },
  { id: "explosionsverletzung-card-08", area: "Diagnostik", question: "Warum entwarnt ein intaktes Trommelfell nicht?", answer: "Trommelfell- und Lungenschaden korrelieren nicht zuverlässig. Ein Blast Lung kann trotz intaktem Trommelfell vorliegen." },
  { id: "explosionsverletzung-card-09", area: "Verlauf", question: "Welche zwei Verletzungen können besonders verzögert manifest werden?", answer: "Blast Lung beziehungsweise Atemwegsödem und gastrointestinale Kontusion oder Perforation." },
  { id: "explosionsverletzung-card-10", area: "MANV", question: "Wodurch wird ein MANV definiert?", answer: "Durch ein Missverhältnis zwischen Behandlungsbedarf und regulär verfügbaren Ressourcen, das besondere organisatorische Maßnahmen verlangt – nicht allein durch eine starre Patientenzahl." },
  { id: "explosionsverletzung-card-11", area: "Sichtung", question: "Warum müssen gehfähige Betroffene erneut beurteilt werden?", answer: "Gehfähigkeit schließt Blast Lung, CO-Intoxikation, innere Blutung oder verzögert symptomatische Hohlorganverletzung nicht aus." },
  { id: "explosionsverletzung-card-12", area: "Atmung", question: "Welche Beatmungsgrenze gilt beim vermuteten Blast Lung?", answer: "Notwendige Oxygenierung und Ventilation sicherstellen, dabei Beatmungsdruck möglichst niedrig halten, auf Pneumothorax achten und Entlastungsbereitschaft schaffen." },
  { id: "explosionsverletzung-card-13", area: "Verbrennung", question: "Warum kann eine normale Pulsoxymetrie bei Rauchgasexposition täuschen?", answer: "Konventionelle Pulsoxymetrie unterscheidet Oxyhämoglobin nicht zuverlässig von Carboxyhämoglobin und kann eine CO-Intoxikation übersehen." },
  { id: "explosionsverletzung-card-14", area: "Zielklinik", question: "Welche Hallenser Zentren sind für schwere Verbrennungen relevant?", answer: "Erwachsene: BG Klinikum Bergmannstrost Halle. Kinder/Jugendliche: pädiatrisches Brandverletztenzentrum des Universitätsklinikums Halle; Zuweisung kapazitätsgeprüft und koordiniert." },
  { id: "explosionsverletzung-card-15", area: "VFA", question: "Welche Thüringer Pfade können bei Explosionsverletzten parallel relevant werden?", answer: "Traumaalgorithmus L2, VFA 34 Verbrennung, VFA 07 Entlastungspunktion sowie VFA 35 mit Esketamin- oder Morphinpfad; je nach Befund zusätzlich Blutungs-/TXA-Entscheidung im Traumaalgorithmus." },
];

export const explosionsverletzungQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Befunde oder Verletzungen gehören definitionsgemäß zur primären Explosionswirkung?", [["Alveoläre Blutung nach Druckwelle", true], ["Trommelfellruptur", true], ["Penetrierende Splitterwunde"], ["Stumpfes Trauma nach Fortschleudern"], ["Darmkontusion durch Druckwelle", true]], "Primäre Explosionswirkung"),
  q(2, "Welche Zuordnungen der Explosionsmechanismen sind korrekt?", [["Sekundär – Splitter wirkt als Projektil", true], ["Tertiär – Körper prallt nach Verlagerung auf ein Hindernis", true], ["Quartär – Verbrennung und Inhalationsschaden", true], ["Primär – Quetschung durch Gebäudeeinsturz"], ["Quinär – überall einheitlich definierte Druckwellenfolge"]], "Mechanismen I–V"),
  q(3, "Welche Aussagen erklären das Blast Lung pathophysiologisch?", [["Alveolarsepten und Kapillaren können durch den Druckimpuls geschädigt werden", true], ["Blutung und Ödem verschlechtern Ventilation und Diffusion", true], ["Eine alveolo-vaskuläre Fistel kann eine systemische Luftembolie ermöglichen", true], ["Die Erkrankung beruht primär auf bakterieller Alveolitis"], ["Ein normales Trommelfell schließt die Lungenbeteiligung aus"]], "Blast Lung"),
  q(4, "Ein zunächst ansprechbarer Patient entwickelt nach einer Explosion Dyspnoe, Hämoptyse und fallende Sauerstoffsättigung. Welche Überlegungen sind richtig?", [["Ein Blast Lung ist wahrscheinlich", true], ["Ein Pneumothorax muss wiederholt geprüft werden", true], ["Notwendige Beatmung darf wegen des Barotraumarisikos grundsätzlich nicht erfolgen"], ["Bei Beatmung sind niedrige Drücke und engmaschige Kontrolle sinnvoll", true], ["Der Befund ist durch eine isolierte Stressreaktion ausreichend erklärt"]], "Dynamische Atemwegsschädigung"),
  q(5, "Welche Konstellationen sprechen für eine arterielle Gasembolie nach einer Explosion?", [["Plötzliches fokal-neurologisches Defizit", true], ["Akute Bewusstseinsstörung", true], ["Koronare Ischämiezeichen", true], ["Ausschließlich schleichende Unterschenkelschwellung"], ["Der Befund setzt zwingend einen Tauchunfall voraus"]], "Arterielle Gasembolie"),
  q(6, "Welche Aussagen zum Ohrbefund sind korrekt?", [["Tinnitus und Hörminderung können primäre Explosionsfolgen sein", true], ["Eine Trommelfellruptur beweist ein Blast Lung"], ["Ein intaktes Trommelfell schließt ein Blast Lung nicht aus", true], ["Schwindel kann auf eine Innenohrbeteiligung hinweisen", true], ["Ohrbefunde machen eine erneute ABCDE-Kontrolle entbehrlich"]], "Ohr und Druckwelle"),
  q(7, "Welche Besonderheiten gelten für gastrointestinale Explosionsverletzungen?", [["Gasgefüllte Darmabschnitte sind gegenüber Druckänderungen verletzlich", true], ["Beschwerden und Peritonismus können verzögert auftreten", true], ["Ein initial weiches Abdomen schließt eine spätere Perforation sicher aus"], ["Serielle Untersuchungen und strukturierte Übergabe sind wichtig", true], ["Sie zählen typischerweise zur sekundären Explosionswirkung"]], "Abdomen"),
  q(8, "Welche Bedingungen erhöhen bei gleichem Ereignis das Risiko einer ausgeprägten Druckwellenverletzung?", [["Explosion in einem geschlossenen Raum", true], ["Reflexion der Druckwelle an festen Flächen", true], ["Große Entfernung und freie Ausbreitung ohne Hindernis"], ["Aufenthalt nahe der Detonation", true], ["Das Risiko wird allein durch die sichtbare Flamme bestimmt"]], "Ereignisrekonstruktion"),
  q(9, "Welche Aussagen zum MANV treffen zu?", [["Entscheidend ist das Missverhältnis zwischen Bedarf und verfügbaren Ressourcen", true], ["Ein MANV beginnt bundesweit immer ab exakt zehn Verletzten"], ["Besondere Führungs-, Sichtungs- und Transportmaßnahmen können erforderlich werden", true], ["Nachsichtung ist wegen der einmaligen Kennzeichnung nicht nötig"], ["Kapazitätsgesteuerte Patientenverteilung gehört zur Bewältigung", true]], "MANV"),
  q(10, "Welche Maßnahmen sind in einer unübersichtlichen Explosionslage zuerst richtig?", [["Gefahrenlage und Freigabe beachten", true], ["Mögliche Folgeexplosion und Einsturzgefahr bedenken", true], ["Ohne Rücksprache in den inneren Gefahrenbereich laufen"], ["Lage, Patientenzahl und Ressourcenbedarf früh melden", true], ["Alle Patienten sofort einzeln maximal versorgen, unabhängig von den verfügbaren Mitteln"]], "Einsatzsicherheit"),
  q(11, "Welche Aussagen zu gehfähigen Betroffenen nach einer Explosion sind korrekt?", [["Sie können gesammelt und registriert werden", true], ["Sie benötigen eine strukturierte Erst- und Nachsichtung", true], ["Gehfähigkeit schließt CO-Intoxikation aus"], ["Verzögert auftretende Atemnot muss ernst genommen werden", true], ["Sie dürfen ohne Dokumentation vom Ereignisort gehen"]], "Sichtung"),
  q(12, "Welche cABCDE-Maßnahmen haben bei einem Explosionsverletzten Priorität?", [["Lebensbedrohliche äußere Blutung sofort kontrollieren", true], ["Atemweg auf thermische und inhalative Schädigung prüfen", true], ["Thoraxverletzungen beidseits untersuchen", true], ["Ausführliche SAMPLERS-Anamnese vor Blutungskontrolle"], ["Hypothermie konsequent vermeiden", true]], "cABCDE"),
  q(13, "Ein Patient hat nach der Explosion eine offene Thoraxwunde und zunehmende Atemnot. Welche Aussagen sind richtig?", [["Die Thoraxwunde wird nach lokalem Vorgehen abgedeckt beziehungsweise abgedichtet", true], ["Ein Spannungspneumothorax bleibt eine klinische Verlaufsdiagnose", true], ["Bei hämodynamischer Bedrohung und passendem Befund ist die VFA zur Entlastung relevant", true], ["Eine einmal normale SpO₂ schließt eine Verschlechterung aus"], ["Der Wundkanal soll tief tamponiert werden"]], "Thoraxtrauma"),
  q(14, "Welche Befunde sprechen nach einer Explosion für ein Inhalationstrauma beziehungsweise eine drohende Atemwegsbeteiligung?", [["Heiserkeit oder Stridor", true], ["Ruß im Mund-Nasen-Bereich", true], ["Gesichtsverbrennung mit progredienter Schwellung", true], ["Isolierter Knöchelschmerz"], ["Bronchospasmus und zunehmende Atemarbeit", true]], "Inhalationstrauma"),
  q(15, "Welche Aussagen zur Kohlenmonoxidvergiftung in Verbindung mit Explosion und Brand sind richtig?", [["Eine normale Standard-Pulsoxymetrie kann täuschen", true], ["Neurologische Symptome können Ausdruck der Exposition sein", true], ["Sauerstoffgabe richtet sich bei begründetem Verdacht nicht allein nach der SpO₂", true], ["Kirschrote Haut ist für die präklinische Diagnose erforderlich"], ["CO verursacht primär eine Methämoglobinbildung"]], "CO-Risiko"),
  q(16, "Welche Aussagen zur quartären und quinären Einteilung sind fachlich angemessen?", [["Verbrennung und Rauchgasinhalation werden quartär zugeordnet", true], ["Crush und Asphyxie können quartäre Folgen sein", true], ["Die quinäre Kategorie ist in allen Klassifikationen identisch"], ["Bei quinären Beschreibungen sollte die uneinheitliche Definition genannt werden", true], ["Toxische oder CBRN-Zusätze können unter quinären Effekten beschrieben werden", true]], "Quartär und quinär"),
  q(17, "Welche Gefahren bestehen nach Verschüttung mit ausgeprägtem Muskelschaden?", [["Hyperkaliämie", true], ["Metabolische Azidose", true], ["Kreislaufverschlechterung nach Befreiung", true], ["Rhabdomyolyse", true], ["Isolierte respiratorische Alkalose als einziges relevantes Problem"]], "Crush-Syndrom"),
  q(18, "Welche Aussagen zur Verbrennungsversorgung nach einer Explosion sind korrekt?", [["Kritische Blutung und Atemweg haben Vorrang vor der Flächenberechnung", true], ["Verbrennungstiefe und betroffene Körperoberfläche werden nach Stabilisierung erfasst", true], ["Großflächige langdauernde Kühlung ist wegen Hypothermie unproblematisch"], ["Kritische Regionen und Inhalationstrauma beeinflussen die Zielklinik", true], ["Die Infusion wird nach der hinterlegten Thüringer VFA berechnet", true]], "Verbrennung"),
  q(19, "Welche Aussagen zur Zielklinik in Halle sind richtig?", [["Das BG Klinikum Bergmannstrost ist ein Zentrum für schwerbrandverletzte Erwachsene", true], ["Das Universitätsklinikum Halle hält ein pädiatrisches Brandverletztenzentrum vor", true], ["Jede kleine Verbrennung muss ungeachtet der Kapazität direkt dorthin transportiert werden"], ["Verletzungsschwerpunkt, Transportzeit und bestätigte Kapazität bestimmen die Zielentscheidung", true], ["Bei dominantem Polytrauma ist die Abstimmung mit einem geeigneten Traumazentrum wichtig", true]], "Zielklinik"),
  q(20, "Welche Aussagen zur Analgesie bei Explosionsverletzten sind korrekt?", [["Vor der Medikamentengabe werden vital bedrohliche Probleme priorisiert", true], ["Esketamin oder Morphin werden ausschließlich nach passender Thüringer VFA und Gewichtstabelle dosiert", true], ["Analgesie macht ein Reassessment unnötig"], ["Atmung, Kreislauf, Vigilanz und Wirkung werden überwacht", true], ["Bei starker Schmerzsymptomatik ist jede Kontraindikation bedeutungslos"]], "VFA Schmerz"),
  q(21, "Welche Befunde verlangen nach anfänglich unauffälligem Verlauf eine erneute Priorisierung?", [["Neu aufgetretene Dyspnoe", true], ["Zunehmender Bauchschmerz", true], ["Fokales neurologisches Defizit", true], ["Fallende Vigilanz", true], ["Konstante schmerzfreie kleine Hautabschürfung als alleiniger Befund"]], "Nachsichtung"),
  q(22, "Welche Aussagen vermeiden typische Prüfungsfehler?", [["Der sichtbare Verbrennungsbefund darf die Suche nach Blutungen nicht verdrängen", true], ["Ein intaktes Trommelfell ist kein Ausschlusskriterium für Blast Lung", true], ["Eine normale SpO₂ schließt CO sicher aus"], ["Eine Druckwellenverletzung kann ohne große äußere Wunde bestehen", true], ["Gehfähige Patienten benötigen keine Verlaufskontrolle"]], "Prüfungsfallen"),
  q(23, "Welche Maßnahmen passen zur präklinischen Versorgung einer vermuteten arteriellen Gasembolie nach Blast Lung?", [["Hochkonzentrierte Sauerstoffgabe bei begründetem Verdacht", true], ["Neurologischen und kardialen Verlauf dokumentieren", true], ["Frühzeitige ärztliche/leitstellenseitige Abstimmung einer geeigneten Zielstruktur", true], ["Behandlung allein durch Abwarten am Einsatzort"], ["Notwendige Stabilisierung nach cABCDE fortführen", true]], "Gasembolie"),
  q(24, "Welche Übergabeinformationen verändern nach einer Explosion die klinische Priorität besonders?", [["Explosion in geschlossenem Raum", true], ["Abstand und Position zur Detonation", true], ["Verschüttungsdauer", true], ["Ruß-, Rauch- oder Gefahrstoffexposition", true], ["Nur die Farbe der Einsatzkleidung"]], "Übergabe"),
];
