import type { ComponentType, ReactNode } from "react";
import BurnInfusionCalculator from "./verbrennung-infusion-calculator";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function ExplosionsverletzungLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, kicker: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>{kicker}</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;

  return <article className="lesson-article angina-pectoris-lesson reference-reading-lesson polytrauma-lesson explosionsverletzung-lesson">
    <div className="lesson-intro"><p className="lead">Explosionsverletzte können gleichzeitig Druck-, Splitter-, Sturz-, Quetsch-, Verbrennungs- und Inhalationsschäden erleiden. Ein zunächst unauffälliger äußerer Befund schließt weder ein Blast Lung noch eine verzögert symptomatische Darmverletzung aus.</p></div>

    {section("01", "Druckwelle plus Mehrfachmechanismus", "Definition", <><p>Eine <b>Explosionsverletzung</b> entsteht durch die plötzliche Freisetzung von Energie, Hitze und komprimierten Gasen. Druckwelle, Fragmente, Verlagerung des Körpers und thermisch-chemische Einwirkungen treffen häufig zusammen.</p><div className="pulmo-compare"><div><small>Explosionsereignis</small><h3>Mehrere Verletzungsarten gleichzeitig</h3><p>Der Unfallmechanismus ist ein Hochenergietrauma. Die präklinische Einteilung erklärt den Mechanismus, ersetzt aber niemals die strukturierte Untersuchung nach cABCDE.</p></div><div><small>MANV</small><h3>Kapazität bestimmt die Lage</h3><p>Ein Massenanfall von Verletzten oder Erkrankten liegt vor, wenn Zahl oder Schwere der Betroffenen besondere organisatorische Maßnahmen verlangen, weil die regulär verfügbaren Kräfte und Mittel nicht ausreichen.</p></div></div><aside className="red-flags"><span>!</span><div><small>Einsatzgrundsatz</small><h3>Eigenschutz vor Patientenversorgung</h3><p>Gefahr durch Brand, Einsturz, Strom, Gefahrstoffe, scharfe Gegenstände und mögliche Folgeexplosionen beachten. Erst nach Freigabe des Gefahrenbereichs medizinisch vorgehen.</p></div></aside></>)}

    {section("02", "Luftgefüllte Organe und Barrieren", "Anatomie und Physiologie", <><div className="pulmo-anatomy-grid">{[["Ohr", "Trommelfell und Mittelohr", "Die dünne Membran und der luftgefüllte Raum reagieren empfindlich auf rasche Druckänderungen."], ["L", "Alveolen und Kapillaren", "Die alveolo-kapilläre Membran ermöglicht den Gasaustausch; Rupturen verursachen Blutung, Ödem und Luftübertritt in Gefäße."], ["GI", "Magen und Darm", "Gasgefüllte Hohlorgane können gedehnt, kontusioniert oder perforiert werden; Beschwerden können verzögert auftreten."], ["H", "Haut", "Schützt vor Flüssigkeits- und Wärmeverlust. Thermische Schäden zerstören die Barriere und fördern Hypothermie."], ["ZNS", "Gehirn", "Druckwelle, Beschleunigung, Aufprall und arterielle Gasembolie können neurologische Ausfälle verursachen."], ["A", "Atemweg", "Hitze, Rauch und Reizgase können Schleimhautödem, Bronchospasmus, Intoxikation und Atemwegsverlegung auslösen."]].map(([tag,title,text]) => <div key={title}><small>{tag}</small><b>{title}</b><p>{text}</p></div>)}</div><Figure src="/lessons/lungenarterienembolie/lunge-alveolen.png" alt="Lunge mit Alveolen und Kapillaren" caption="Alveolo-kapilläre Einheit · besonders druckempfindliche Grenzfläche" wide /><Figure src="/lessons/verbrennung/haut-print14.png" alt="Aufbau der Haut" caption="Hautbarriere · relevant bei thermischen Explosionsverletzungen" wide /></>)}

    {section("03", "Fünf Mechanismen sicher unterscheiden", "Ursachen und Pathophysiologie", <><div className="pulmo-vfa-flow"><div><span>I</span><b>Primär</b><small>Druckwelle: Ohr, Nasennebenhöhlen, Lunge und Gastrointestinaltrakt.</small></div><div><span>II</span><b>Sekundär</b><small>Splitter und Trümmer wirken als Projektile: penetrierende Wunden und Blutungen.</small></div><div><span>III</span><b>Tertiär</b><small>Der Körper wird fortgeschleudert oder verschüttet: stumpfes Trauma, Frakturen und Crush.</small></div><div><span>IV</span><b>Quartär</b><small>Übrige Folgen: Verbrennung, Inhalation, toxische Exposition, Asphyxie und Exazerbationen.</small></div><div><span>V</span><b>Quinär</b><small>Nicht einheitlich definiert: zusätzliche toxische/CBRN-Komponenten oder überschießende systemische Reaktion.</small></div></div><h3>Blast Lung · in Schritten</h3><div className="pulmo-path"><span>Druckfront</span><i>→</i><span>Alveolardeformation</span><i>→</i><span>Septen-/Kapillarschaden</span><i>→</i><span>Blutung und Ödem</span><i>→</i><span>V/Q-Störung und Hypoxämie</span></div><p>Bei einer alveolo-vaskulären Verbindung kann Luft in die Lungenvenen und anschließend in den systemischen Kreislauf gelangen. Eine <b>arterielle Gasembolie</b> kann dadurch plötzlich neurologische oder kardiale Symptome auslösen. In geschlossenen Räumen werden Druckwellen reflektiert; die Belastung kann höher und länger anhaltend sein.</p><aside className="diagnostic-boundary"><span>!</span><div><b>Trommelfellbefund ist kein Entwarnungstest</b><p>Ein intaktes Trommelfell schließt ein Blast Lung nicht aus. Umgekehrt beweist eine Trommelfellruptur allein keine schwere Lungenverletzung.</p></div></aside></>)}

    {section("04", "Mechanismus, Verlauf und Organsysteme", "Symptome der Arbeitsdiagnose", <><div className="rib-fracture-grid">{[["Ohr", "Ohrenschmerz, Hörminderung, Tinnitus, Schwindel oder Blutung aus dem Gehörgang."], ["Lunge", "Dyspnoe, Husten, Thoraxschmerz, Hypoxämie, Hämoptyse, Rasselgeräusche oder zunehmende Erschöpfung."], ["Thorax", "Einseitig vermindertes Atemgeräusch, asymmetrische Exkursion, subkutanes Emphysem oder Kreislaufinstabilität."], ["Abdomen", "Schmerz, Übelkeit, Abwehrspannung, Distension oder später zunehmende Peritonismuszeichen."], ["Neurologie", "Kopfschmerz, Vigilanzminderung, Krampfanfall, fokales Defizit oder plötzliche Verwirrtheit."], ["Thermisch/toxisch", "Verbrennungen, Rußspuren, Heiserkeit, Stridor, Bronchospasmus, Kopfschmerz oder Bewusstseinsstörung."]].map(([title,text]) => <div key={title}><b>{title}</b><span>{text}</span></div>)}</div><aside className="knowledge-note"><b>Dynamische Befunde</b><p>Lungenschaden, Atemwegsödem und Hohlorganverletzungen können sich erst im Verlauf deutlich zeigen. Wiederholtes ABCDE und Trendbeobachtung sind entscheidend.</p></aside></>)}

    {section("05", "Zeitkritische Organbedrohungen", "Komplikationen und Gefahren", <><div className="pulmo-risk-grid"><div><b>Blast Lung</b><p>Kontusion, alveoläre Blutung und Ödem führen zu zunehmender Gasaustauschstörung; Überdruckbeatmung kann Barotrauma verstärken.</p></div><div><b>Pneumo-/Spannungspneumothorax</b><p>Rupturierte Alveolen oder Splitterverletzung lassen Luft in den Pleuraspalt treten; Spannung behindert zusätzlich den venösen Rückstrom.</p></div><div><b>Arterielle Gasembolie</b><p>Luft gelangt über verletzte Lungenvenen in den Körperkreislauf und kann Gehirn oder Koronararterien embolisieren.</p></div><div><b>Innere Blutung</b><p>Splitter-, stumpfe und Quetschverletzungen können Thorax, Abdomen, Becken oder große Gefäße betreffen.</p></div><div><b>Hohlorganperforation</b><p>Darmverletzungen können verzögert Peritonitis und Sepsis verursachen; frühe Beschwerden müssen ernst genommen werden.</p></div><div><b>Crush / Rhabdomyolyse</b><p>Verschüttung und Muskelzerstörung bergen nach Befreiung Risiken durch Hyperkaliämie, Azidose und Kreislaufdepression.</p></div><div><b>Inhalation / CO</b><p>Normale Pulsoxymetrie schließt eine Kohlenmonoxidvergiftung nicht aus. Atemwegsödem kann progredient sein.</p></div><div><b>Hypothermie / Koagulopathie</b><p>Entkleidung, Flüssigkeitsverlust und großflächige Verbrennungen verschlechtern Gerinnung und Prognose.</p></div></div></>)}

    {section("06", "MANV-fähig und traumafokussiert", "Einsatzmaterialien", <div className="material-chips">{["Persönliche Schutzausrüstung", "Triage-/Dokumentationsmaterial", "Tourniquets", "Hämostyptika und Packing-Gaze", "Thoraxverbände", "Traumatasche", "Absaugung und Atemweg", "O₂ / Beatmung / Kapnografie", "Thoraxpunktionskanüle", "Verbrennungsauflagen", "Monitoring / 12-Kanal-EKG", "i.v.- / i.o.-Material", "Wärmeerhalt", "Medikamente nach VFA", "Tragen und Rettungsmittel"].map(item => <span key={item}>{item}</span>)}</div>)}

    {section("07", "Sicherheit, Sichtung und cABCDE", "Erstmaßnahmen und Diagnostik", <><aside className="red-flags"><span>!</span><div><small>Gefahrenbereich</small><h3>Hot, warm und cold zone sind Führungsentscheidungen</h3><p>Absperrgrenzen und Zugänge werden durch Einsatzleitung und Gefahrenabwehr festgelegt. Nicht eigenmächtig in unsichere Bereiche vorgehen; Patienten möglichst aus der Gefahrenzone herausführen lassen.</p></div></aside><div className="pulmo-care-grid"><div><span>c</span><b>Kritische Blutung</b><small>Direkter Druck, Packing, Kompressionsverband oder Tourniquet; Anlagezeit dokumentieren.</small></div><div><span>A</span><b>Atemweg</b><small>Ruß, Heiserkeit, Stridor und Gesichtsverbrennung erkennen; frühzeitig Hilfe und Atemwegsstrategie planen.</small></div><div><span>B</span><b>Atmung</b><small>Thorax untersuchen, O₂ nach Befund/Exposition, beidseits auskultieren; offene Wunde abdichten, Spannung klinisch entlasten.</small></div><div><span>C</span><b>Kreislauf</b><small>Blutungsquellen, Schockzeichen und Verbrennungsausmaß erfassen; Zugang, Wärmeerhalt und VFA-gerechte Therapie.</small></div><div><span>D</span><b>Neurologie</b><small>GCS, Pupillen, fokale Zeichen, BZ; an SHT, Hypoxie, CO und arterielle Gasembolie denken.</small></div><div><span>E</span><b>Entkleiden / Erhalten</b><small>Bodycheck einschließlich Rücken, Verbrennungsgrad und KOF; Kontamination beachten und Hypothermie vermeiden.</small></div></div><h3>SAMPLERS · explosionsspezifisch</h3><div className="samplers-grid">{[["S · Symptome", "Atemnot, Hörverlust, Schmerz, Neurologie"], ["A · Allergien", "Medikamente und Materialien"], ["M · Medikamente", "Antikoagulanzien, Inhalativa"], ["P · Vorgeschichte", "Lunge, Ohr, Gerinnung, Schwangerschaft"], ["L · Letzte Aufnahme", "Nahrung, Flüssigkeit, Drogen"], ["E · Ereignis", "Ort, Abstand, geschlossener Raum, Verschüttung"], ["R · Risiken", "Brand, CBRN, Folgeexplosion, Einsturz"], ["S · Schwangerschaft", "Bei passender Patientin beachten"]].map(([label,text]) => <p key={label}><b>{label}</b>{text}</p>)}</div><aside className="knowledge-note"><b>Beatmung mit Augenmaß</b><p>Hypoxie und ventilatorisches Versagen müssen behandelt werden. Bei vermutetem Blast Lung jedoch Beatmungsdruck möglichst niedrig halten, engmaschig auf Pneumothorax achten und Entlastungsbereitschaft herstellen.</p></aside></>)}

    {section("08", "Verletzungsmuster statt Etikett", "Differenzialdiagnosen und Entscheidungsfindung", <><div className="differential-grid">{["Blast Lung", "Inhalationstrauma / CO-Intoxikation", "Pneumothorax / Spannungspneumothorax", "Lungenkontusion", "Hämorrhagischer Schock", "Arterielle Gasembolie", "Schädel-Hirn-Trauma", "Hohlorganverletzung", "Crush-Syndrom", "Akute Belastungsreaktion"].map(item => <span key={item}>{item}</span>)}</div><h3>MANV: medizinische Priorisierung unter begrenzten Ressourcen</h3><div className="pulmo-vfa-flow"><div><span>01</span><b>Lage erkennen</b><small>Patientenzahl, Gefahren, Mechanismus und Ressourcen melden.</small></div><div><span>02</span><b>Führung einhalten</b><small>Bereitstellungsraum, Behandlungsplatz und Transportorganisation nutzen.</small></div><div><span>03</span><b>Sichten</b><small>Lebensbedrohungen erkennen, Prioritäten kennzeichnen und regelmäßig nachsichten.</small></div><div><span>04</span><b>Verteilen</b><small>Geeignete Kliniken kapazitätsgerecht über Leitstelle/medizinische Führung anfahren.</small></div></div><ul className="script-list"><li><b>Gehfähige Betroffene</b> sammeln, registrieren und erneut beurteilen; Gehfähigkeit bedeutet nicht Unverletztheit.</li><li><b>Keine Tunnelperspektive:</b> Die sichtbare Verbrennung darf kritische Blutung oder Thoraxverletzung nicht überdecken.</li><li><b>Keine Scheindiagnostik:</b> Eine gute SpO₂ schließt CO-Intoxikation nicht aus; ein intaktes Trommelfell schließt Blast Lung nicht aus.</li><li><b>Keine unnötige Verzögerung:</b> Zeitkritische definitive Versorgung hat Vorrang vor nicht entscheidenden Maßnahmen vor Ort.</li></ul></>)}

    {section("09", "Trauma, Verbrennung, Thorax und Schmerzen", "Weitere Maßnahmen", <><div className="pulmo-vfa-flow"><div><span>L2</span><b>Traumaalgorithmus</b><small>cABCDE, Blutungskontrolle, Wärmeerhalt und passende Zielklinik.</small></div><div><span>34</span><b>Verbrennung / Verbrühung</b><small>Ausmaß, Tiefe, kritische Regionen, Inhalationsrisiko und VFA-gerechte Infusion.</small></div><div><span>07</span><b>Thoraxentlastung</b><small>Bei klinischem Spannungspneumothorax mit respiratorischer und hämodynamischer Bedrohung.</small></div><div><span>35–38</span><b>Starke Schmerzen</b><small>Esketamin oder Morphin nach Indikation, Kontraindikationen und Gewichtstabelle.</small></div></div><h3>Zielkliniken in Halle</h3><div className="pulmo-compare"><div><small>Erwachsene</small><h3>BG Klinikum Bergmannstrost Halle</h3><p>Überregionales Zentrum für Schwerbrandverletzte. Die Zielentscheidung erfolgt nach Verletzungsmuster, Transportzeit und bestätigter Aufnahmekapazität.</p></div><div><small>Kinder und Jugendliche</small><h3>Universitätsklinikum Halle</h3><p>Das pädiatrische Brandverletztenzentrum versorgt schwer brandverletzte Kinder und Jugendliche. Zuweisung immer koordiniert über Leitstelle und zuständige medizinische Führung.</p></div></div><p><b>Entscheidend:</b> Eine Verbrennungsklinik ersetzt bei dominierendem Polytrauma nicht automatisch das geeignete Traumazentrum. Frühzeitig anmelden, Verletzungsschwerpunkt und Ressourcen gemeinsam abstimmen.</p></>)}

    {section("10", "Thüringen 2026/2027", "Verfahrensanweisungen und Anlagen", <><div className="vfa-stack"><Vfa src="/lessons/sht/vfa-trauma-l2.png" alt="Thüringer VFA Leitalgorithmus Trauma L2" caption="L2 · Leitalgorithmus Trauma" /><Vfa src="/lessons/verbrennung/vfa-34-print14.png" alt="Thüringer VFA Verbrennung und Verbrühung" caption="VFA 34 · Verbrennung / Verbrühung" /><Vfa src="/lessons/thoraxtrauma/vfa-entlastungspunktion-07.png" alt="Thüringer VFA Entlastungspunktion" caption="VFA 07 · Spannungspneumothorax und Entlastung" /><Vfa src="/lessons/sht/vfa-schmerz-basis-35.png" alt="Thüringer VFA starke Schmerzzustände" caption="VFA 35 · Starke Schmerzzustände" /><Vfa src="/lessons/sht/vfa-esketamin-36.png" alt="Thüringer VFA Esketamin" caption="VFA 36 · Esketamin" /><Vfa src="/lessons/sht/vfa-morphin-38.png" alt="Thüringer VFA Morphin" caption="VFA 38 · Morphin" /></div><h3>Zubereitung und Gewichtstabellen</h3><div className="vfa-stack"><Vfa src="/lessons/abdominaltrauma/txa-anlage-b2a.png" alt="Anlage B2A Tranexamsäure" caption="B2A · Tranexamsäure" /><Vfa src="/lessons/wirbelsaeulentrauma/anlage-b2a-esketamin.png" alt="Anlage B2A Esketamin" caption="B2A · Esketamin" /><Vfa src="/lessons/wirbelsaeulentrauma/anlage-b2b-esketamin.png" alt="Anlage B2B Esketamin Gewichtstabelle" caption="B2B · Esketamin" /><Vfa src="/lessons/sht/medikamentenliste-morphin.png" alt="Anlage B2A Morphin" caption="B2A · Morphin" /><Vfa src="/lessons/wirbelsaeulentrauma/anlage-b2b-morphin.png" alt="Anlage B2B Morphin Gewichtstabelle" caption="B2B · Morphin" /></div><BurnInfusionCalculator /></>)}

    {children}
    <p className="lesson-source">Hauptgrundlage: bereitgestellte Unterlagen „44. Explosionsverletzungen“. Fachlich abgeglichen mit der AWMF-Leitlinie zur prähospitalen Katastrophenmedizin, der AWMF-Leitlinie zu thermischen Verletzungen, den MANV-Hinweisen des BBK sowie den offiziellen Angaben der Hallenser Brandverletztenzentren. Therapie, Dosierungen und Zubereitungen richten sich ausschließlich nach den Thüringer VFA 2026/2027.</p>
  </article>;
}
