import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct: boolean];
function q(n: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3): ThoraxtraumaChoiceQuestion {
  return { id: `ext-q-${String(n).padStart(2, "0")}`, mode: "multiple", prompt, options: options.map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty };
}

export const extremitaetentraumaFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "ext-card-01", area: "Definition", question: "Definieren Sie eine Extremitätenfraktur und grenzen Sie sie vom Extremitätentrauma ab.", answer: "Fraktur: Kontinuitätstrennung eines Extremitätenknochens mit mindestens zwei Bruchstücken. Extremitätentrauma umfasst außerdem Gelenk-, Band-, Muskel-, Sehnen-, Nerven- und Gefäßverletzungen." },
  { id: "ext-card-02", area: "Röhrenknochen", question: "Ordnen Sie Epiphyse, Metaphyse, Diaphyse, Periost, Kompakta und Spongiosa funktionell ein.", answer: "Epiphysen bilden die Enden, Metaphysen die Übergänge, Diaphyse den Schaft. Periost umhüllt den Knochen; Kompakta bildet die feste Rinde, Spongiosa das schwammartige Innere mit Markräumen." },
  { id: "ext-card-03", area: "Gelenke", question: "Welche Strukturen besitzt ein echtes Gelenk und weshalb ist Knorpelheilung begrenzt?", answer: "Gelenkflächen mit Knorpel, Gelenkspalt, Kapsel und stabilisierende Bänder. Knorpel ist gefäßlos und wird durch Diffusion ernährt; seine Regeneration ist begrenzt." },
  { id: "ext-card-04", area: "Frakturzeichen", question: "Welche Befunde stützen eine Fraktur und was darf nicht provoziert werden?", answer: "Schmerz, Schwellung, Funktionsverlust sowie Fehlstellung, Stufenbildung, abnorme Beweglichkeit oder sichtbarer Knochen. Krepitation und abnorme Beweglichkeit nicht gezielt auslösen." },
  { id: "ext-card-05", area: "Offene Fraktur", question: "Warum ist eine kleine Wunde über einer vermuteten Fraktur bedeutsam?", answer: "Sie kann eine Verbindung des Frakturbereichs zur Außenwelt anzeigen. Steril abdecken, Blutung kontrollieren, Infektionsrisiko beachten; herausragende Knochen nicht zurückdrücken." },
  { id: "ext-card-06", area: "pDMS", question: "Wie und wann beurteilen Sie die periphere DMS?", answer: "Durchblutung, Motorik und Sensibilität distal der Verletzung im Seitenvergleich prüfen; vor und nach Umlagerung, Manipulation und Schienung wiederholen und dokumentieren." },
  { id: "ext-card-07", area: "Kompartmentsyndrom", question: "Welche Dynamik lässt an ein Kompartmentsyndrom denken?", answer: "Zunehmender, unverhältnismäßiger Schmerz und pralle Schwellung, später Sensibilitäts- und Motorikstörungen. Erhaltene tastbare Pulse schließen eine frühe Perfusionsstörung nicht aus." },
  { id: "ext-card-08", area: "Kreislauf", question: "Weshalb kann ein Extremitätentrauma einen Schock auslösen?", answer: "Bei großen Knochen und ausgedehnten Weichteilverletzungen kann Blut in Gewebe verloren gehen; externe Blutung kommt hinzu. Kreislauf, zusätzliche Blutungsquellen und cABCDE müssen fortlaufend beurteilt werden." },
  { id: "ext-card-09", area: "Erstversorgung", question: "Priorisieren Sie die Maßnahmen bei starker Blutung und schmerzhafter Fehlstellung.", answer: "Eigenschutz, kritische Blutung stoppen, cABCDE, Wunde versorgen, pDMS erheben, Analgesie und schonende Stabilisierung, danach pDMS erneut prüfen. Bei instabilem Patienten Transport priorisieren." },
  { id: "ext-card-10", area: "Reposition", question: "Warum ist eine pauschale Repositionsregel bei Extremitätentrauma falsch?", answer: "Frakturtyp, Gelenkbeteiligung, offene Wunde und pDMS unterscheiden sich. Keine gewaltsame Routine-Reposition; bei bedrohter Perfusion/neurologischem Defizit nach lokalen Vorgaben und ärztlicher Rücksprache entscheiden." },
  { id: "ext-card-11", area: "VFA", question: "Welche Sicherheitsprüfungen gehören vor Morphin oder Esketamin zur Thüringer Schmerz-VFA?", answer: "NRS und Ursache, cABCDE/OPQRST, Indikation und Kontraindikationen, Gewichts- und Konzentrationsprüfung, Monitoring, Beatmungsbereitschaft sowie wiederholte Wirkungskontrolle gemäß jeweiligem VFA-Pfad." },
  { id: "ext-card-12", area: "Verdünnung", question: "Berechnen Sie die Konzentrationen der vorbereiteten Spritzen für Morphin und Esketamin.", answer: "Morphin 10 mg in insgesamt 10 ml = 1 mg/ml. Esketamin 50 mg in insgesamt 10 ml = 5 mg/ml. Ausgangsampulle und Endvolumen mit Anlage B2A abgleichen." },
  { id: "ext-card-13", area: "Übergabe", question: "Welche Informationen sind bei einer gefährdeten Extremität entscheidend?", answer: "Unfallmechanismus, Blutung/Wunde, initiale und aktuelle pDMS einschließlich Zeiten, Verlauf nach Schienung oder Manipulation, Kreislauf, Schmerz/NRS, Medikamente mit Dosis und Wirkung sowie vermutete Begleitverletzungen." },
];

export const extremitaetentraumaQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Nach einem Sturz ist der Unterschenkel schmerzhaft deformiert. Welche Aussagen sind begründet?", [["Eine Fraktur ist möglich, aber auch Gelenk- und Weichteilverletzungen sind zu prüfen",true],["Erhaltene Motorik beweist, dass kein Knochen verletzt ist",false],["Periphere DMS gehört vor der Schienung zum Ausgangsbefund",true],["Krepitation soll gezielt erzeugt werden, um die Diagnose zu sichern",false],["Der Unfallmechanismus gehört in die Übergabe",true]], "Fehlstellung ist verdächtig; die Gesamtbeurteilung umfasst Mechanismus und pDMS, ohne zusätzliche Provokation.", 1),
  q(2, "Welche Zuordnungen zum Röhrenknochen stimmen?", [["Die Diaphyse bildet den Schaft",true],["Die Epiphyse bezeichnet das Knochenende",true],["Die Kompakta ist die feste äußere Knochensubstanz",true],["Die Spongiosa ist die äußere Gelenkkapsel",false],["Das Periost ist eine ausschließlich intraartikuläre Struktur",false]], "Der Röhrenknochen besitzt Enden, Übergang und Schaft sowie Periost, Kompakta und Spongiosa.", 1),
  q(3, "Welche Aussagen zur Gelenkanatomie erklären die Verletzungsfolgen?", [["Ein echtes Gelenk besitzt einen Gelenkspalt und eine Kapsel",true],["Bänder stabilisieren und führen Gelenke",true],["Gelenkknorpel wird direkt durch eigene Blutgefäße versorgt",false],["Eine Luxation kann benachbarte Gefäße und Nerven gefährden",true],["Schmerzfreie Beweglichkeit schließt jede Bandverletzung sicher aus",false]], "Gelenkflächen, Kapsel und Bänder sind verletzbar; Knorpel ist gefäßlos.", 2),
  q(4, "Ein Patient hat eine kleine Wunde über einer deformierten Tibia. Welche Bewertungen sind richtig?", [["Auch eine kleine Wunde kann eine offene Fraktur anzeigen",true],["Die Wunde wird steril abgedeckt",true],["Vorstehende Knochenenden werden routinemäßig zurückgedrückt",false],["Infektions- und Blutungsrisiko sind mitzudenken",true],["Eine unauffällige Hautfarbe schließt Gefäßschäden aus",false]], "Offene Frakturen müssen erkannt, steril abgedeckt und ohne Zurückdrücken versorgt werden.", 2),
  q(5, "Welche Befunde sprechen besonders für eine Fraktur, ohne dass sie provoziert werden dürfen?", [["Sichtbarer Knochen im Wundbereich",true],["Abnorme Beweglichkeit",true],["Krepitation",true],["Schmerz allein ist ein sicherer Frakturnachweis",false],["Eine Rötung beweist eine vollständige Kontinuitätstrennung",false]], "Spezifische Frakturzeichen werden beobachtet, nicht durch Bewegung erzeugt.", 1),
  q(6, "Nach Schienung sind die Finger kühler und taub. Welche Schritte sind fachlich richtig?", [["pDMS im Vergleich zum dokumentierten Ausgangsbefund neu prüfen",true],["Sitz und Druck der Schienung kontrollieren",true],["Den neuen Befund als zeitkritische Verschlechterung behandeln",true],["Die Schiene unverändert belassen, weil Schmerz nach Schienung normal ist",false],["Nur den Puls messen und Sensibilität ignorieren",false]], "pDMS ist vor und nach Schienung zu prüfen; eine Verschlechterung verlangt unmittelbare Re-Evaluation.", 2),
  q(7, "Welche Kombinationen können auf ein Kompartmentsyndrom hinweisen?", [["Zunehmender, unverhältnismäßiger Schmerz",true],["Pralle Schwellung und neue Parästhesien",true],["Erhaltener peripherer Puls schließt einen frühen Verlauf sicher aus",false],["Fortschreitende Motorikstörung ist ein Alarmsignal",true],["Nur eine offene Fraktur kann ein Kompartmentsyndrom verursachen",false]], "Druckanstieg im Kompartiment bedroht Perfusion und Nerven; Pulse können anfangs erhalten sein.", 3),
  q(8, "Ein Oberschenkel ist nach Sturz stark geschwollen, der Blutdruck sinkt. Was ist sinnvoll?", [["Einen relevanten inneren Blutverlust in die Weichteile erwägen",true],["Weitere Blutungsquellen und Begleitverletzungen suchen",true],["Kreislauf und cABCDE wiederholt beurteilen",true],["Ohne sichtbare äußere Blutung einen hämorrhagischen Schock ausschließen",false],["Die Extremität isoliert behandeln und die Transportentscheidung aufschieben",false]], "Große Knochen- und Weichteilverletzungen können erheblichen Blutverlust ohne sichtbare Außenblutung verursachen.", 2),
  q(9, "Welche Reihenfolge ist bei einer aktiv stark blutenden Extremität sinnvoll?", [["Lebensbedrohliche Blutung sofort kontrollieren",true],["cABCDE und Gesamtzustand parallel beurteilen",true],["pDMS nach lebensrettender Blutungskontrolle dokumentieren",true],["Zuerst alle Gelenkbewegungen testen",false],["Schienung vor jeder Blutstillung durchführen",false]], "Kritische Blutung hat Priorität; anschließend strukturiert untersuchen und stabilisieren.", 2),
  q(10, "Welche Angaben machen eine SAMPLERS-Anamnese nach Extremitätentrauma relevant?", [["Antikoagulanzien und weitere Medikamente",true],["Unfallmechanismus und Zeitverlauf",true],["Vorerkrankungen und Allergien",true],["Die letzte Nahrungsaufnahme ist grundsätzlich wertlos",false],["Schmerzbeginn und Schmerzverlauf brauchen nicht erfragt zu werden",false]], "SAMPLERS und OPQRST erfassen Risiken, Mechanismus und Verlauf für Versorgung und Übergabe.", 1),
  q(11, "Eine Fehlstellung besteht am Sprunggelenk, pDMS ist erhalten. Welche Aussagen sind tragfähig?", [["Eine Luxation oder Fraktur-Luxation kommt infrage",true],["pDMS ist vor und nach jeder Maßnahme erneut zu kontrollieren",true],["Eine pauschale Pflicht zur sofortigen Reposition ergibt sich daraus nicht",true],["Erhaltene pDMS beweist, dass keine Gelenkverletzung vorliegt",false],["Eine gewaltsame Korrektur dient immer der Diagnose",false]], "Fehlstellung wird schonend versorgt; Reposition ist keine pauschale Routineentscheidung.", 3),
  q(12, "Welche Maßnahmen schützen bei einer offenen Fraktur vor zusätzlichem Schaden?", [["Wunde steril abdecken",true],["Herausragende Knochen nicht zurückschieben",true],["Extremität möglichst schmerzarm stabilisieren",true],["Wunde zur Beurteilung wiederholt unsteril sondieren",false],["pDMS nach der Schienung nicht mehr kontrollieren",false]], "Sterile Abdeckung, schonende Stabilisierung und serielle pDMS sind zentral.", 2),
  q(13, "Welche Gründe sprechen für eine frühe Notarztnachforderung und zeitkritische Zielklinikplanung?", [["Persistierend fehlende distale Perfusion",true],["Kreislaufinstabilität und Verdacht auf größeren Blutverlust",true],["Ausgedehnte offene Verletzung mit schweren Schmerzen",true],["Allein eine kleine Prellmarke bei sonst stabilem Zustand",false],["Eine unauffällige Erstuntersuchung ohne relevanten Mechanismus",false]], "Gefäßgefährdung, Schock und schwere offene Verletzung erfordern Eskalation und geeignete Klinik.", 3),
  q(14, "Welche Punkte gehören vor Morphin- oder Esketamingabe in die Entscheidung?", [["Schmerzstärke und Verlauf mit NRS",true],["Indikation und Kontraindikationen des gewählten VFA-Pfades",true],["Gewicht und Konzentration der vorbereiteten Spritze",true],["Die Beatmungsbereitschaft ist wegen Analgesie entbehrlich",false],["Nach der Gabe entfällt die Wirkungskontrolle",false]], "VFA 35/36/38 verlangen strukturierte Indikationsprüfung, Überwachung und Re-Evaluation.", 2),
  q(15, "Welche Konzentrationen ergeben die Thüringer B2A-Verdünnungen?", [["10 mg Morphin auf 10 ml ergeben 1 mg/ml",true],["50 mg Esketamin auf 10 ml ergeben 5 mg/ml",true],["10 mg Morphin auf 10 ml ergeben 10 mg/ml",false],["Die Endkonzentration muss bei jeder aufgezogenen Spritze geprüft werden",true],["2 ml Esketamin plus 8 ml NaCl ergeben 2 ml Endvolumen",false]], "Anlage B2A gibt Morphin 1 mg/ml und Esketamin 5 mg/ml nach Verdünnung vor.", 2),
  q(16, "Ein Erwachsener wiegt 75 kg; der VFA-Pfad sieht Esketamin 0,2 mg/kg i.v. vor. Welche Rechnungen stimmen?", [["Die Initialmenge beträgt 15 mg",true],["Bei 5 mg/ml entspricht das 3 ml",true],["Eine halbe Initialdosis entspricht 7,5 mg",true],["Die Initialmenge beträgt 75 mg",false],["Bei 5 mg/ml sind für 15 mg genau 15 ml nötig",false]], "0,2 × 75 = 15 mg; bei 5 mg/ml sind das 3 ml. Halbe Dosis: 7,5 mg.", 3),
  q(17, "Welche Aussagen zum Morphinpfad der Thüringer VFA 38 passen?", [["Die langsame i.v.-Gabe richtet sich nach der Gewichtstabelle",true],["Nach fünf Minuten wird die Wirkung geprüft",true],["Bei Bedarf ist gemäß Algorithmus eine halbe Dosis zur Wiederholung vorgesehen",true],["Die gesamte Menge ist unbegrenzt steigerbar",false],["Kinder unter 40 kg erhalten zwingend denselben Morphinpfad",false]], "VFA 38 enthält Gewichtstabelle, Wirkungskontrolle, begrenzte Wiederholung und Maximalmenge 10 mg.", 3),
  q(18, "Welche Aussagen zur Schienung sind begründet?", [["Benachbarte Gelenke werden nach Verletzungsmuster mit stabilisiert",true],["Der Schmerz und die pDMS werden danach erneut beurteilt",true],["Bei instabilem Patienten darf ausgedehnte Schienung lebensrettende Maßnahmen nicht verzögern",true],["Eine Schiene ersetzt die Kontrolle einer offenen Blutung",false],["Einmal normale pDMS macht jede spätere Kontrolle entbehrlich",false]], "Schienung dient der Schonung, bleibt aber nachrangig gegenüber kritischer Blutung und cABCDE.", 2),
  q(19, "Ein Bein ist schmerzhaft fehlgestellt; distal besteht neue Sensibilitätsstörung. Was ist richtig?", [["Ausgangsbefund, Seitenvergleich und Zeitpunkt dokumentieren",true],["Gefäß- und Nervenverletzung mitbedenken",true],["Früh ärztliche Unterstützung und passende Zielklinik einplanen",true],["Ein tastbarer Puls widerlegt jede Nervenverletzung",false],["Für den Transport reicht die Angabe ‚Bein verletzt‘",false]], "Neurologische Defizite erfordern dokumentierte pDMS, Eskalation und Übergabe.", 3),
  q(20, "Nach Analgesie nimmt der Schmerz ab, aber der Fuß wird blasser. Welche Schlüsse stimmen?", [["Die pDMS-Verschlechterung bleibt trotz besserem Schmerz eine Red Flag",true],["Perfusion und Sitz der Stabilisierung sind unverzüglich erneut zu prüfen",true],["Verlauf und Zeitpunkt gehören in die Übergabe",true],["Schmerzfreiheit beweist ausreichende Gewebeperfusion",false],["Eine erneute Kreislaufkontrolle ist damit überflüssig",false]], "Analgesie kann Schmerz lindern, aber die serielle Perfusionsbeurteilung nicht ersetzen.", 3),
  q(21, "Welche Angaben sind bei Übergabe einer offenen, analgetisch behandelten Unterschenkelfraktur besonders wertvoll?", [["Wund- und Blutungsbefund sowie Versorgungsmaßnahmen",true],["pDMS vor und nach Schienung mit zeitlicher Entwicklung",true],["Medikament, Menge, Zeitpunkt und beobachtete Wirkung",true],["Nur die aktuelle NRS ohne Ausgangswert",false],["Verzicht auf den Unfallmechanismus, wenn die Fehlstellung sichtbar ist",false]], "Die Übergabe verbindet Mechanismus, Befunddynamik und Maßnahmen mit Zeitangaben.", 3),
];
