export type GallensteinkolikChoiceQuestion = {
  id: string;
  mode: "multiple";
  prompt: string;
  options: Array<{ text: string; correct?: boolean }>;
  source: string;
  difficulty: 1 | 2 | 3;
};

export type GallensteinkolikFlashcard = {
  id: string;
  area: string;
  question: string;
  answer: string;
};

export const gallensteinkolikFlashcards: GallensteinkolikFlashcard[] = [
  { id: "galle-card-01", area: "Definition", question: "Definieren Sie die Gallensteinkolik und nennen Sie den unmittelbaren Schmerzauslöser.", answer: "Plötzlich einsetzender, starker, krampfartiger Oberbauchschmerz durch eine vorübergehende Behinderung oder einen Verschluss eines Gallengangs durch einen Stein. Die glatte Muskulatur kontrahiert gegen das Hindernis und erzeugt den wellenförmigen Schmerz." },
  { id: "galle-card-02", area: "Anatomie", question: "Leiten Sie den Galleweg von der Leber bis zum Duodenum her.", answer: "Ductus hepaticus dexter und sinister vereinigen sich zum Ductus hepaticus communis. Über den Ductus cysticus besteht die Verbindung zur Gallenblase. Nach dessen Einmündung verläuft die Galle über den Ductus choledochus zur Papilla duodeni major; häufig besteht dort die enge Beziehung zum Ductus pancreaticus und zum Sphinkter Oddi." },
  { id: "galle-card-03", area: "Physiologie", question: "Welche Aufgabe hat die Gallenblase und wodurch wird ihre Entleerung gesteuert?", answer: "Die Leber bildet die Galle; die Gallenblase speichert und konzentriert sie durch Entzug von Wasser und Natrium. Fettreicher Speisebrei im Duodenum setzt Cholecystokinin frei: Die Gallenblase kontrahiert und der Sphinkter Oddi entspannt. Der Parasympathikus fördert, der Sympathikus hemmt die Kontraktion." },
  { id: "galle-card-04", area: "Begriffe", question: "Grenzen Sie Cholelithiasis, Cholezystolithiasis und Choledocholithiasis voneinander ab.", answer: "Cholelithiasis ist der Oberbegriff für Steine in Gallenblase oder Gallenwegen. Cholezystolithiasis bezeichnet Steine in der Gallenblase. Choledocholithiasis bezeichnet Steine im Ductus choledochus." },
  { id: "galle-card-05", area: "Pathophysiologie", question: "Erklären Sie die Kaskade vom Gallenstein bis zu Cholestase und Ikterus.", answer: "Ein Stein gelangt in einen Gallengang und behindert den Abfluss. Die Muskulatur kontrahiert krampfartig gegen das Hindernis. Bei vollständiger Obstruktion entsteht eine Cholestase; Gallebestandteile stauen sich zurück und können einen Ikterus auslösen. Hält die Störung an, drohen Entzündung und weitere Komplikationen." },
  { id: "galle-card-06", area: "Steinentstehung", question: "Wie entstehen Cholesterin- und Pigmentsteine?", answer: "Gerät das Lösungsverhältnis aus Cholesterin, Gallensäuren, Phospholipiden und Bilirubin aus dem Gleichgewicht, kristallisieren Bestandteile aus. Cholesterin bildet Cholesterinsteine, unkonjugiertes Bilirubin Pigmentsteine; Mischformen sind möglich." },
  { id: "galle-card-07", area: "Symptome", question: "Welche Befundkonstellation stützt die Arbeitsdiagnose Gallensteinkolik?", answer: "Plötzlich einsetzender starker, krampfartiger Schmerz im rechten oder mittleren Oberbauch, mögliche Ausstrahlung in Rücken oder rechte Schulter, Übelkeit/Erbrechen, Unruhe und vegetative Reaktionen. Ikterus und heller Stuhl sprechen für eine relevante Abflussstörung; Fieber weist auf eine entzündliche Komplikation hin." },
  { id: "galle-card-08", area: "Gefahren", question: "Welche Komplikationen können aus einer anhaltenden Abflussstörung entstehen?", answer: "Cholezystitis, Cholangitis, Vergrößerung beziehungsweise eitrige Füllung der Gallenblase, Perforation mit galliger Peritonitis und septischem Schock sowie bei einem Stein an der Papilla Vateri ein Rückstau des Pankreassekrets mit Pankreatitis." },
  { id: "galle-card-09", area: "Erstmaßnahmen", question: "Strukturieren Sie die präklinischen Erstmaßnahmen bei Oberbauchkolik.", answer: "cABCDE, Lagerung nach Patientenwunsch, vollständiges Monitoring, Temperatur, BZ und 12-Kanal-EKG zur Differenzialdiagnostik, venösen Zugang vorbereiten, NRS/OPQRST sowie SAMPLERS erheben, Analgesie und Antiemese nach gültiger VFA, Wirkung und Vitalparameter wiederholt kontrollieren und bei Kritikalität früh den Notarzt nachfordern." },
  { id: "galle-card-10", area: "Differenzialdiagnosen", question: "Welche gefährlichen Differenzialdiagnosen müssen bei rechtsseitigem oder mittlerem Oberbauchschmerz aktiv geprüft werden?", answer: "ACS beziehungsweise Myokardinfarkt, Aortenerkrankung, Lungenarterienembolie, basale Pneumonie, Pankreatitis, Ileus, Ulkus- oder Duodenalerkrankung, Lebererkrankung, Nierenkolik und atypische Appendizitis. Eine Cholangitis oder Cholezystitis lässt sich präklinisch nicht sicher von einer unkomplizierten Kolik abgrenzen." },
  { id: "galle-card-11", area: "VFA 39", question: "Leiten Sie den Thüringer Behandlungspfad bei NRS mindestens 5 her.", answer: "Nach cABCDE Schwangerschaft und Stillzeit als Kontraindikationen prüfen. Bei Schmerz oberhalb des Bauchnabels STEMI-Kriterien im EKG beurteilen und bei positivem Befund den ACS-Basisalgorithmus anwenden. Bei RRsys mindestens 100 mmHg erfolgt nach Risikoaufklärung 1 g Metamizol als Kurzinfusion in 100 ml NaCl 0,9 % über fünf Minuten. Bei kolikartigem Charakter zusätzlich 20 mg Butylscopolamin, in 9 ml NaCl 0,9 % verdünnt, langsam geben. Monitoring und Transport fortführen." },
  { id: "galle-card-12", area: "VFA 18", question: "Welche Maßnahmen nennt VFA 18 bei massiver Übelkeit oder Erbrechen?", answer: "Nach cABCDE 500 ml Kristalloidlösung infundieren und eine Ampulle Dimenhydrinat mit 62 mg langsam intravenös über mindestens zwei Minuten geben. Danach Überwachung, kontinuierliches Monitoring und Transport." },
  { id: "galle-card-13", area: "Entscheidung", question: "Welche Befunde sprechen gegen eine unkomplizierte Kolik und erhöhen die Dringlichkeit?", answer: "Kreislaufinstabilität, Fieber, Ikterus, anhaltender oder nicht mehr klar kolikartiger Schmerz, Abwehrspannung, Vigilanzstörung, pathologisches EKG, Dyspnoe oder fehlende Besserung trotz Maßnahmen. Diese Befunde verlangen eine erneute Differenzialdiagnostik, ärztliche Unterstützung und zeitgerechten Transport." },
  { id: "galle-card-14", area: "Prüfungsfall", question: "Warum darf ein kolikartiger Oberbauchschmerz nach fettreicher Mahlzeit nicht vorschnell als Gallensteinkolik festgelegt werden?", answer: "Mahlzeit, Lokalisation und Schmerzcharakter stützen nur eine Arbeitsdiagnose. ACS, Aortenerkrankung, Pankreatitis, Ileus und weitere gefährliche Ursachen können ähnlich beginnen. Deshalb bleiben cABCDE, EKG, Vitaltrend, Temperatur, strukturierte Anamnese und wiederholte Untersuchung entscheidend." },
];

export const gallensteinkolikQuestions: GallensteinkolikChoiceQuestion[] = [
  { id: "galle-q-01", mode: "multiple", prompt: "Eine Patientin beschreibt plötzlich einsetzende wellenförmige Schmerzen im rechten Oberbauch. Welche Aussagen kennzeichnen die Arbeitsdiagnose Gallensteinkolik korrekt?", options: [{ text: "Ein vorübergehender steinbedingter Verschluss eines Gallengangs kann die Kolik auslösen", correct: true }, { text: "Die krampfartige Kontraktion glatter Gangmuskulatur gegen das Hindernis trägt zum Schmerz bei", correct: true }, { text: "Die Diagnose setzt zwingend bereits einen Ikterus voraus" }, { text: "Ein symptomloser Stein in der Gallenblase ist definitionsgemäß eine akute Kolik" }, { text: "Die Arbeitsdiagnose bleibt präklinisch gegenüber gefährlichen Ursachen abzugrenzen", correct: true }], source: "Kolik bedeutet akuten krampfartigen Schmerz bei passagerer Abflussbehinderung; Begleitbefunde beweisen die Ursache präklinisch nicht.", difficulty: 1 },
  { id: "galle-q-02", mode: "multiple", prompt: "Welche anatomischen Zuordnungen sind korrekt?", options: [{ text: "Der Ductus cysticus verbindet die Gallenblase mit den ableitenden Gallenwegen", correct: true }, { text: "Der Ductus hepaticus dexter und sinister vereinigen sich zum Ductus hepaticus communis", correct: true }, { text: "Der Ductus choledochus mündet im Bereich der Papilla duodeni major in das Duodenum", correct: true }, { text: "Der Ductus pancreaticus transportiert Galle aus der Gallenblase" }, { text: "Fundus, Corpus und Collum bezeichnen Abschnitte der Gallenblase", correct: true }], source: "Gallenblase, Ductus cysticus, Ductus hepaticus communis und Ductus choledochus bilden mit der Papille ein zusammenhängendes Abflusssystem.", difficulty: 1 },
  { id: "galle-q-03", mode: "multiple", prompt: "Welche Aussagen zur Physiologie von Galle und Gallenblase treffen zu?", options: [{ text: "Galle wird in der Leber gebildet", correct: true }, { text: "Die Gallenblase speichert und konzentriert Galle durch Entzug von Wasser und Natrium", correct: true }, { text: "Cholecystokinin fördert nach fettreichem Speisebrei die Kontraktion der Gallenblase", correct: true }, { text: "Der Parasympathikus hemmt grundsätzlich die Entleerung der Gallenblase" }, { text: "Der Sphinkter Oddi entspannt sich im Zusammenhang mit der Gallenabgabe", correct: true }], source: "Die Leber bildet Galle; Speicherung, Eindickung und bedarfsgerechte Abgabe erfolgen über die Gallenblase und den Sphinkter Oddi.", difficulty: 1 },
  { id: "galle-q-04", mode: "multiple", prompt: "Welche Begriffspaare sind richtig zugeordnet?", options: [{ text: "Cholelithiasis – Oberbegriff für Steine in Gallenblase oder Gallenwegen", correct: true }, { text: "Cholezystolithiasis – Steine in der Gallenblase", correct: true }, { text: "Choledocholithiasis – Steine im Ductus choledochus", correct: true }, { text: "Cholestase – ungehinderter Abfluss der Galle in das Duodenum" }, { text: "Pigmentstein – kann durch Auskristallisieren unkonjugierten Bilirubins entstehen", correct: true }], source: "Die Begriffe unterscheiden Lokalisation, Abflussstörung und Entstehung der Gallensteine.", difficulty: 1 },
  { id: "galle-q-05", mode: "multiple", prompt: "Welche Schritte gehören zur pathophysiologischen Kette einer steinbedingten Abflussstörung?", options: [{ text: "Ein Stein behindert den Galleabfluss", correct: true }, { text: "Gangmuskulatur kontrahiert gegen das Hindernis", correct: true }, { text: "Bei vollständiger Obstruktion kann eine Cholestase entstehen", correct: true }, { text: "Rückgestaute Gallebestandteile können einen Ikterus verursachen", correct: true }, { text: "Jede Abflussstörung führt sofort und zwingend zur Gallenblasenperforation" }], source: "Obstruktion, Kontraktion, Cholestase und Rückstau erklären Schmerz und mögliche Folgezeichen.", difficulty: 1 },
  { id: "galle-q-06", mode: "multiple", prompt: "Welche Befunde stützen die Arbeitsdiagnose, ohne sie zu beweisen?", options: [{ text: "Krampfartiger Schmerz im rechten oder mittleren Oberbauch", correct: true }, { text: "Ausstrahlung in Rücken oder rechte Schulter", correct: true }, { text: "Übelkeit, Erbrechen und vegetative Unruhe", correct: true }, { text: "Heller oder lehmfarbener Stuhl bei relevanter Abflussstörung", correct: true }, { text: "Ein einzelner unauffälliger Vitalwert schließt eine Komplikation sicher aus" }], source: "Leit- und Begleitsymptome ergeben gemeinsam eine Arbeitsdiagnose; Einzelbefunde sind nicht beweisend.", difficulty: 2 },
  { id: "galle-q-07", mode: "multiple", prompt: "Bei welchen Befunden muss die Einordnung als unkomplizierte Kolik kritisch überprüft werden?", options: [{ text: "Fieber zusammen mit Oberbauchschmerz", correct: true }, { text: "Ikterus oder auffällig heller Stuhl", correct: true }, { text: "Kreislaufinstabilität oder Vigilanzminderung", correct: true }, { text: "Abwehrspannung oder zunehmender Dauerschmerz", correct: true }, { text: "Kurze Besserung nach einer selbst gewählten Schonhaltung" }], source: "Fieber, Cholestasezeichen, Instabilität und Peritonismus sprechen für mögliche entzündliche oder andere gefährliche Komplikationen.", difficulty: 2 },
  { id: "galle-q-08", mode: "multiple", prompt: "Welche Komplikationen sind mechanistisch richtig zugeordnet?", options: [{ text: "Reizung der Gallenblasenwand kann in eine Cholezystitis übergehen", correct: true }, { text: "Perforation kann eine gallige Peritonitis und einen septischen Schock nach sich ziehen", correct: true }, { text: "Ein Stein im Bereich der Papilla Vateri kann den Pankreasabfluss beeinträchtigen und eine Pankreatitis begünstigen", correct: true }, { text: "Eine Cholangitis ist eine Entzündung der Gallenwege", correct: true }, { text: "Eine Choledocholithiasis verhindert grundsätzlich jede entzündliche Komplikation" }], source: "Eine Abflussstörung kann Entzündung, Eiteransammlung, Perforation und bei Papillenbeteiligung eine Pankreatitis begünstigen.", difficulty: 2 },
  { id: "galle-q-09", mode: "multiple", prompt: "Welche Maßnahmen gehören zur ersten präklinischen Beurteilung einer vermuteten Gallensteinkolik?", options: [{ text: "cABCDE und vollständige Vitalparameter einschließlich Temperatur", correct: true }, { text: "NRS und OPQRST zur strukturierten Schmerzanalyse", correct: true }, { text: "SAMPLERS mit Mahlzeit, bekannten Steinen, Vorerkrankungen und Medikamenten", correct: true }, { text: "12-Kanal-EKG bei Oberbauchschmerz zur ACS-Abgrenzung", correct: true }, { text: "Verzicht auf Verlaufskontrollen, sobald der Schmerz kolikartig erscheint" }], source: "Erstmaßnahmen verbinden Basisbeurteilung, strukturierte Anamnese, EKG-Differenzialdiagnostik und wiederholte Kontrolle.", difficulty: 2 },
  { id: "galle-q-10", mode: "multiple", prompt: "Welche Einsatzmittel sind bei einem relevanten Oberbauchschmerz begründet?", options: [{ text: "Notfallrucksack und Medikamente für die gültigen VFA-Pfade", correct: true }, { text: "EKG/Monitoring einschließlich Möglichkeit zum 12-Kanal-EKG", correct: true }, { text: "Sauerstoff und Absaugung passend zum klinischen Verlauf", correct: true }, { text: "Material für venösen Zugang und Infusion", correct: true }, { text: "Ausschließlich ein Stethoskop, da apparative Diagnostik die Arbeitsdiagnose verfälscht" }], source: "Rucksack, EKG, Medikamente, Sauerstoff und Absaugung werden durch Material für Zugang und Infusion ergänzt.", difficulty: 2 },
  { id: "galle-q-11", mode: "multiple", prompt: "Ein Patient hat rechtsseitigen Oberbauchschmerz. Welche Differenzialdiagnosen bleiben aufgrund möglicher vitaler Gefahr besonders relevant?", options: [{ text: "Akutes Koronarsyndrom beziehungsweise Myokardinfarkt", correct: true }, { text: "Aortenerkrankung", correct: true }, { text: "Lungenarterienembolie oder basale Pneumonie", correct: true }, { text: "Pankreatitis oder Ileus", correct: true }, { text: "Eine unkomplizierte Gallensteinkolik ist allein durch die Schmerzlokalisation bewiesen" }], source: "Kardiale, vaskuläre, pulmonale und abdominale Differenzialdiagnosen können eine ähnliche Schmerzlokalisation verursachen.", difficulty: 2 },
  { id: "galle-q-12", mode: "multiple", prompt: "Ein 58-jähriger Patient hat NRS 8 oberhalb des Bauchnabels. Welche Entscheidungen entsprechen VFA 39?", options: [{ text: "Nach cABCDE werden zunächst Schwangerschaft und Stillzeit als Algorithmus-Kontraindikationen geprüft", correct: true }, { text: "Wegen der Lokalisation werden STEMI-Kriterien im EKG beurteilt", correct: true }, { text: "Bei erfüllten STEMI-Kriterien wird der ACS-Basisalgorithmus angewendet", correct: true }, { text: "Die Oberbauchlokalisation erlaubt, auf ein EKG zu verzichten" }, { text: "Monitoring und Transport bleiben unabhängig vom gewählten Pfad erforderlich", correct: true }], source: "VFA 39 verzweigt bei Schmerzen oberhalb des Bauchnabels zur Prüfung auf STEMI-Kriterien und gegebenenfalls zum ACS-Algorithmus.", difficulty: 3 },
  { id: "galle-q-13", mode: "multiple", prompt: "Der systolische Blutdruck beträgt 96 mmHg. Welche Aussagen folgen aus VFA 39?", options: [{ text: "Der im Algorithmus dargestellte Metamizolpfad wird bei RRsys unter 100 mmHg nicht begonnen", correct: true }, { text: "Kreislaufzustand und Differenzialdiagnosen müssen erneut beurteilt werden", correct: true }, { text: "Überwachung, kontinuierliches Monitoring und Transport werden fortgeführt", correct: true }, { text: "Der niedrige Blutdruck beweist eine harmlose vagale Reaktion" }, { text: "Butylscopolamin wird unabhängig von allen vorherigen Verzweigungen zwingend gegeben" }], source: "Bei RRsys unter 100 mmHg führt VFA 39 an der Metamizolgabe vorbei zur weiteren Versorgung; Instabilität verlangt erneute Einordnung.", difficulty: 3 },
  { id: "galle-q-14", mode: "multiple", prompt: "RRsys liegt bei 128 mmHg, STEMI-Kriterien fehlen und der Schmerz ist kolikartig. Welche Schritte entsprechen VFA 39?", options: [{ text: "Metamizol-Risikoaufklärung vor der Gabe", correct: true }, { text: "1 g Metamizol als Kurzinfusion in 100 ml NaCl 0,9 % über fünf Minuten", correct: true }, { text: "Zusätzlich 20 mg Butylscopolamin, in 9 ml NaCl 0,9 % verdünnt, langsam geben", correct: true }, { text: "Nach Medikamentengabe sind Monitoring und Transport entbehrlich" }, { text: "Schmerz und Vitalparameter werden im Verlauf erneut erhoben", correct: true }], source: "VFA 39 kombiniert bei stabilem Kreislauf Metamizol mit Butylscopolamin bei kolikartigem Schmerz und fordert fortgesetztes Monitoring und Transport.", difficulty: 3 },
  { id: "galle-q-15", mode: "multiple", prompt: "Welche Aussagen grenzen die beiden VFA-Pfade korrekt voneinander ab?", options: [{ text: "VFA 39 behandelt sonstige Schmerzzustände ab NRS 5 beim Erwachsenen", correct: true }, { text: "VFA 18 richtet sich an massive Übelkeit oder Erbrechen beim Erwachsenen", correct: true }, { text: "VFA 18 nennt 500 ml Kristalloidlösung und 62 mg Dimenhydrinat langsam i.v. über mindestens zwei Minuten", correct: true }, { text: "VFA 18 ersetzt bei Oberbauchschmerz die EKG-Differenzialdiagnostik" }, { text: "Beide Pfade enden mit Überwachung, kontinuierlichem Monitoring und Transport", correct: true }], source: "VFA 18 und 39 behandeln unterschiedliche Symptome und können bei passender Indikation innerhalb derselben Versorgung relevant sein.", difficulty: 3 },
  { id: "galle-q-16", mode: "multiple", prompt: "Nach Analgesie sinkt die NRS, gleichzeitig treten Fieber und Ikterus auf. Welche Schlussfolgerungen sind begründet?", options: [{ text: "Die Schmerzreduktion schließt eine entzündliche Komplikation nicht aus", correct: true }, { text: "Eine Abflussstörung mit Beteiligung der Gallenwege bleibt möglich", correct: true }, { text: "Die klinische Dringlichkeit muss anhand des Gesamtbilds neu bewertet werden", correct: true }, { text: "Der Patient ist allein wegen der geringeren NRS sicher ambulant versorgbar" }, { text: "Ärztliche Unterstützung und zeitgerechter Kliniktransport sind zu erwägen", correct: true }], source: "Fieber und Ikterus sind Warnzeichen; Symptomlinderung beseitigt weder Ursache noch Komplikationsgefahr.", difficulty: 3 },
  { id: "galle-q-17", mode: "multiple", prompt: "Welche Befunde helfen, Gallensteinkolik und Pankreatitis im Prüfungsfall zu gewichten, ohne eine sichere präklinische Diagnose vorzutäuschen?", options: [{ text: "Wellenförmiger rechts- oder mitteloberbauchbetonter Schmerz passt eher zur Kolik", correct: true }, { text: "Ein anhaltender gürtelförmiger Schmerz lenkt den Verdacht stärker zur Pankreatitis", correct: true }, { text: "Ein Stein an der Papilla Vateri kann beide Krankheitsbilder pathophysiologisch verbinden", correct: true }, { text: "Übelkeit und Erbrechen unterscheiden beide Erkrankungen sicher voneinander" }, { text: "Verlauf, Abwehrspannung, Vitalwerte und weitere Differenzialdiagnostik bleiben entscheidend", correct: true }], source: "Pankreatitis bleibt eine wichtige Differenzialdiagnose; ein Stein im Papillenbereich kann den Pankreasabfluss behindern.", difficulty: 3 },
  { id: "galle-q-18", mode: "multiple", prompt: "Eine Patientin entwickelt nach fettreicher Mahlzeit Oberbauchkoliken, kalten Schweiß und Übelkeit. Welche Vorgehensweisen zeigen prüfungsreife Entscheidungsfindung?", options: [{ text: "Gallensteinkolik als Arbeitsdiagnose formulieren, ohne sie als bewiesen anzusehen", correct: true }, { text: "cABCDE, EKG und Vitaltrend parallel zur symptombezogenen Anamnese erheben", correct: true }, { text: "Vor Medikamentengabe Indikation, Kontraindikationen und den passenden VFA-Zweig prüfen", correct: true }, { text: "Bei Warnzeichen die Differenzialdiagnose und Transportpriorität neu bewerten", correct: true }, { text: "Eine fettreiche Mahlzeit macht die Prüfung kardialer Ursachen überflüssig" }], source: "Auslöser und typische Symptome stützen die Arbeitsdiagnose; eine sichere Versorgung verbindet Differenzialdiagnostik, VFA-Prüfung und Re-Evaluation.", difficulty: 3 },
];
