import { supplementalQuestions } from "./supplemental-questions";

type TrainingFlashcard = { id: string; area: string; question: string; answer: string };
type ChoiceOption = { text: string; correct?: boolean };
type MultipleChoiceQuestion = { id: string; prompt: string; options: ChoiceOption[]; source: string; difficulty: 1 | 2 | 3; mode: "multiple" };

export const geburtFlashcards: TrainingFlashcard[] = [
  { id: "geburt-card-01", area: "Definition", question: "Welche beiden Versorgungsbereiche umfasst das Prüfungsthema Geburt?", answer: "Den Geburtsvorgang mit Ausstoßung des Kindes unter Wehentätigkeit sowie die unmittelbare Erstversorgung und Zustandsbeurteilung des Neugeborenen." },
  { id: "geburt-card-02", area: "Anatomie", question: "Beschreiben Sie Geburtsweg und Uteruswand mit ihrer funktionellen Bedeutung.", answer: "Der Geburtsweg umfasst Gebärmutterhals, Vagina und äußere Genitale. Die Uteruswand besteht aus Endometrium, kontraktilem Myometrium und Perimetrium; die Kontraktionen des Myometriums erzeugen die Wehen." },
  { id: "geburt-card-03", area: "Geburtsphasen", question: "Grenzen Sie Eröffnungs-, Austritts- und Nachgeburtsphase voneinander ab.", answer: "Eröffnungsphase: regelmäßige wirksame Wehen bis zur vollständigen Muttermundseröffnung. Austrittsphase: vollständige Eröffnung bis zur Geburt des Kindes. Nachgeburtsphase: Geburt des Kindes bis zur vollständigen Geburt von Plazenta, Eihäuten und Nabelschnurresten." },
  { id: "geburt-card-04", area: "Geburtsmechanik", question: "Warum muss sich das Kind während der Austrittsphase mehrfach drehen?", answer: "Kopf und Schultern müssen sich den unterschiedlichen Durchmessern von Beckeneingang, Beckenmitte und Beckenausgang anpassen. Nach Geburt des Kopfes folgt die äußere Drehung zur Schulterentwicklung." },
  { id: "geburt-card-05", area: "Entscheidung", question: "Welche Befunde sprechen nach VFA 41 für eine unmittelbar einsetzende Geburt vor Ort?", answer: "Sichtbarer vorangehender Kindskopf in der Vulva, Presswehen oder Pressdrang, Wehenabstand unter zwei Minuten, klaffender Anus sowie möglicher Blut- oder Flüssigkeitsabgang." },
  { id: "geburt-card-06", area: "Gefahren", question: "Grenzen Sie Placenta praevia und vorzeitige Plazentaablösung klinisch voneinander ab.", answer: "Placenta praevia: typischerweise schmerzlose hellrote vaginale Blutung. Vorzeitige Plazentaablösung: häufig schmerzhafte Blutung, Dauerkontraktion beziehungsweise brettharter Uterus und Gefahr von Schock sowie fetaler Hypoxie." },
  { id: "geburt-card-07", area: "Nabelschnurvorfall", question: "Erklären Sie die Gefahr eines Nabelschnurvorfalls.", answer: "Liegt die Nabelschnur zwischen vorangehendem Kindsteil und Becken, kann sie komprimiert werden. Dadurch wird die fetale Durchblutung und Sauerstoffversorgung akut gefährdet; die Situation ist geburtsunmöglich beziehungsweise zeitkritisch." },
  { id: "geburt-card-08", area: "Erstmaßnahmen", question: "Strukturieren Sie die präklinische Vorbereitung einer Geburt.", answer: "cABCDE, Mutterpass, geburtshilfliche Notfallanamnese, Wehenabstand und Fruchtwasser beurteilen, Kindslage prüfen, i.v. Zugang und Infusion nach VFA, warme zugluftfreie Umgebung, Geburts- und Neugeborenenmaterial, zusätzliche Kräfte und Zielklinik früh organisieren." },
  { id: "geburt-card-09", area: "Neugeborenes", question: "Welche vier Kriterien beurteilt VFA 42 unmittelbar nach der Geburt?", answer: "Atmung, Herzfrequenz, Muskeltonus und Hautfarbe. Die Herzfrequenz wird über Herzspitze, EKG oder Puls am Nabelschnurgrund beurteilt." },
  { id: "geburt-card-10", area: "Wärmemanagement", question: "Welche Maßnahmen und Zielwerte gelten für den Wärmeerhalt?", answer: "Warme, gut beleuchtete und zugluftfreie Umgebung, sorgfältiges Abtrocknen und Einwickeln, Raumtemperatur etwa 25 °C, Ziel-Körpertemperatur 36,5–37,5 °C und Hyperthermie über 38 °C vermeiden." },
  { id: "geburt-card-11", area: "Reanimation", question: "Leiten Sie den Weg von Apnoe bis zu Thoraxkompressionen beim Neugeborenen her.", answer: "Atemweg öffnen, bei Verlegung vorsichtig absaugen, fünf initiale Beatmungen mit 2–3 Sekunden Inspirationszeit, Wirkung über Thoraxbewegung und Herzfrequenz reevaluieren. Bleibt die Herzfrequenz trotz wirksamer Beatmung unter 60/min, Kompressionen im Verhältnis 3:1 beginnen." },
  { id: "geburt-card-12", area: "VFA 43", question: "Welche Voraussetzungen und welche Dosis gelten für Partusisten nach der offiziellen Thüringer VFA 43?", answer: "Wehentätigkeit plus geburtsunmögliche Situation beziehungsweise BEL, Schwangerschaftswoche mindestens 22. Gabe: 10 ml mit 25 µg Partusisten langsam über drei Minuten i.v.; bei wieder einsetzender Wehentätigkeit innerhalb 15 Minuten einmal wiederholbar. Die 25-mg-Angabe in der Themen-PDF ist ein Einheitenfehler." },
];

const geburtBaseQuestions: MultipleChoiceQuestion[] = [
  { id: "geburt-q-01", mode: "multiple", difficulty: 1, prompt: "Welche Strukturen gehören zu den inneren weiblichen Geschlechtsorganen?", options: [{ text: "Ovarien", correct: true }, { text: "Tubae uterinae", correct: true }, { text: "Uterus und Vagina", correct: true }, { text: "Klitoris und große Labien ausschließlich" }], source: "Zu den inneren Organen gehören Ovarien, Eileiter, Uterus und Vagina." },
  { id: "geburt-q-02", mode: "multiple", difficulty: 1, prompt: "Welche Zuordnungen zur Uteruswand sind korrekt?", options: [{ text: "Endometrium: innere Schleimhautschicht", correct: true }, { text: "Myometrium: glatte Muskulatur und Wehenbildung", correct: true }, { text: "Perimetrium: äußerer Bauchfellüberzug", correct: true }, { text: "Myometrium: ausschließlich hormonbildendes Drüsengewebe" }], source: "Die drei Schichten sind Endometrium, kontraktiles Myometrium und Perimetrium." },
  { id: "geburt-q-03", mode: "multiple", difficulty: 1, prompt: "Welche Aussagen zu den Geburtsphasen stimmen?", options: [{ text: "Die Eröffnungsphase endet mit vollständig geöffnetem Muttermund", correct: true }, { text: "Die Austrittsphase endet mit der Geburt des Kindes", correct: true }, { text: "Die Nachgeburtsphase umfasst die Geburt der Plazenta und Eihäute", correct: true }, { text: "Die Nachgeburtsphase endet grundsätzlich vor der Geburt des Kindes" }], source: "Die Geburt gliedert sich in Eröffnungs-, Austritts- und Nachgeburtsphase." },
  { id: "geburt-q-04", mode: "multiple", difficulty: 1, prompt: "Welche Befunde nennt VFA 41 für eine einsetzende Geburt?", options: [{ text: "Kindskopf in der Vulva sichtbar", correct: true }, { text: "Presswehen oder Pressdrang", correct: true }, { text: "Wehentätigkeit in Abständen unter zwei Minuten", correct: true }, { text: "Ein isolierter positiver Schwangerschaftstest ohne Wehen" }], source: "Sichtbarer Kopf, Pressdrang und sehr kurze Wehenabstände sprechen für die Geburt vor Ort." },
  { id: "geburt-q-05", mode: "multiple", difficulty: 1, prompt: "Welche Informationen gehören zur geburtshilflichen Notfallanamnese?", options: [{ text: "Anzahl vorausgegangener Schwangerschaften und Geburten", correct: true }, { text: "Schwangerschaftsverlauf und Kindsentwicklung", correct: true }, { text: "Wehen, Blutung, Blasensprung und Fruchtwasserfarbe", correct: true }, { text: "Nur die aktuelle Schmerzstärke, alle Vorinformationen sind irrelevant" }], source: "VFA 41 fordert eine fokussierte Anamnese einschließlich Verlauf, Vorentbindungen, Komplikationen und aktueller Symptomatik." },
  { id: "geburt-q-06", mode: "multiple", difficulty: 1, prompt: "Welche Vorbereitungen verlangt VFA 42 für die Neugeborenenversorgung?", options: [{ text: "Warme, zugluftfreie und gut beleuchtete Umgebung", correct: true }, { text: "Beatmungshilfen in passenden Größen", correct: true }, { text: "Warme trockene Tücher sowie sterile Abnabelungsinstrumente", correct: true }, { text: "Routinemäßiges tiefes Absaugen jedes Neugeborenen" }], source: "Wärmeerhalt, passende Beatmungshilfen, Tücher, sterile Instrumente und Handschuhe werden vorbereitet." },
  { id: "geburt-q-07", mode: "multiple", difficulty: 2, prompt: "Welche Konstellation passt eher zu einer Placenta praevia?", options: [{ text: "Schmerzlose hellrote vaginale Blutung", correct: true }, { text: "Plazentagewebe vor dem inneren Muttermund", correct: true }, { text: "Mögliche Verlegung des normalen Geburtswegs", correct: true }, { text: "Brettharter Uterus als zwingender Leitsymptombefund" }], source: "Placenta praevia verlegt den inneren Muttermund und zeigt sich typischerweise durch schmerzlose hellrote Blutung." },
  { id: "geburt-q-08", mode: "multiple", difficulty: 2, prompt: "Welche Befunde stützen den Verdacht auf eine vorzeitige Plazentaablösung?", options: [{ text: "Schmerzhafte Blutung", correct: true }, { text: "Dauerkontraktion beziehungsweise brettharter Uterus", correct: true }, { text: "Schockzeichen bei Mutter und Gefährdung des Kindes", correct: true }, { text: "Sicherer Ausschluss bei nur geringer äußerer Blutung" }], source: "Die Blutung kann teilweise verborgen bleiben; Schmerz, harter Uterus und Kreislaufbeeinträchtigung sind Warnzeichen." },
  { id: "geburt-q-09", mode: "multiple", difficulty: 2, prompt: "Welche Aussagen zu Querlage, Beckenendlage und Nabelschnurvorfall sind richtig?", options: [{ text: "Querlage gilt als geburtsunmögliche Situation", correct: true }, { text: "Bei BEL kann die Nabelschnur eingeklemmt werden", correct: true }, { text: "Ein Nabelschnurvorfall gefährdet die fetale Sauerstoffversorgung", correct: true }, { text: "Ein Armvorfall macht den Geburtsweg grundsätzlich regelrecht" }], source: "Fehllagen und Nabelschnurvorfall sind zeitkritisch; VFA 41 leitet bei entsprechenden Situationen zur Tokolyse und Klinik weiter." },
  { id: "geburt-q-10", mode: "multiple", difficulty: 2, prompt: "Ein reifes Neugeborenes schreit, hat guten Tonus und eine Herzfrequenz über 100/min. Welche Maßnahmen passen zu VFA 42?", options: [{ text: "Wärmeerhalt auf dem Bauch der Mutter", correct: true }, { text: "Frühestens nach einer Minute abklemmen", correct: true }, { text: "Mutter und Kind überwacht in den Kreißsaal transportieren", correct: true }, { text: "Sofort Thoraxkompressionen beginnen" }], source: "Das vitale Neugeborene benötigt Wärmeerhalt, verzögertes Abnabeln und überwachten Transport." },
  { id: "geburt-q-11", mode: "multiple", difficulty: 2, prompt: "Welche Aussagen zur initialen Versorgung eines insuffizient atmenden Neugeborenen sind korrekt?", options: [{ text: "Atemweg öffnen und nur bei Verlegung vorsichtig absaugen", correct: true }, { text: "Fünf initiale Beatmungen mit verlängerten Inspirationszeiten durchführen", correct: true }, { text: "Thoraxbewegung und Herzfrequenz zur Wirksamkeitskontrolle nutzen", correct: true }, { text: "Ohne Beatmungsversuch sofort mit Kompressionen beginnen" }], source: "Ventilation steht zunächst im Vordergrund; Absaugung erfolgt nicht routinemäßig." },
  { id: "geburt-q-12", mode: "multiple", difficulty: 2, prompt: "Welche APGAR-Zuordnungen sind korrekt?", options: [{ text: "Appearance beurteilt die Hautfarbe", correct: true }, { text: "Pulse beurteilt die Herzfrequenz", correct: true }, { text: "Grimace, Activity und Respiration beurteilen Reaktion, Tonus und Atmung", correct: true }, { text: "APGAR ersetzt bei Apnoe den sofortigen Beginn notwendiger Maßnahmen" }], source: "APGAR beschreibt den klinischen Zustand, darf aber eine notwendige Stabilisierung nicht verzögern." },
  { id: "geburt-q-13", mode: "multiple", difficulty: 3, prompt: "Eine Schwangere hat Pressdrang, einen sichtbaren Kopf und Wehen alle 90 Sekunden. Welche Entscheidungen sind richtig?", options: [{ text: "Nicht mehr zum Transport zwingen, sondern Geburt vor Ort vorbereiten", correct: true }, { text: "Zusätzliche Kräfte beziehungsweise zweiten RTW erwägen", correct: true }, { text: "Wärme- und Beatmungsplatz für das Neugeborene vorbereiten", correct: true }, { text: "Bis zur vollständigen Dokumentation jede Geburtsbegleitung unterlassen" }], source: "Die Zeichen entsprechen der einsetzenden Geburt nach VFA 41; Mutter und Kind werden parallel vorbereitet." },
  { id: "geburt-q-14", mode: "multiple", difficulty: 3, prompt: "Welche Aussagen zur Partusisten-Gabe entsprechen der offiziellen Thüringer VFA 43?", options: [{ text: "Wehentätigkeit und eine geburtsunmögliche Situation beziehungsweise BEL müssen vorliegen", correct: true }, { text: "Unterhalb der 22. Schwangerschaftswoche wird kein Partusisten gegeben", correct: true }, { text: "10 ml mit 25 µg werden langsam über drei Minuten intravenös gegeben", correct: true }, { text: "Die Dosis beträgt 25 mg, weil dies in einer Lernskript-Grafik steht" }], source: "Die offizielle VFA 43 nennt 25 µg. Die 25-mg-Angabe in der Themenunterlage ist ein Einheitenfehler." },
  { id: "geburt-q-15", mode: "multiple", difficulty: 3, prompt: "Nach fünf Beatmungen steigt die Herzfrequenz nicht und der Thorax bewegt sich nicht. Welche Schritte nennt der ERC-Algorithmus?", options: [{ text: "Maske und Kopfposition prüfen", correct: true }, { text: "Esmarch-Handgriff beziehungsweise andere Atemwegseröffnung versuchen", correct: true }, { text: "Höheren Beatmungsdruck erwägen und erneut fünfmal beatmen", correct: true }, { text: "Die fehlende Thoraxbewegung ignorieren und unverändert komprimieren" }], source: "Ohne Thoraxbewegung muss zunächst die wirksame Ventilation hergestellt werden." },
  { id: "geburt-q-16", mode: "multiple", difficulty: 3, prompt: "Wann werden beim Neugeborenen Thoraxkompressionen begonnen und wie werden sie durchgeführt?", options: [{ text: "Wenn die Herzfrequenz trotz wirksamer Beatmung unter 60/min bleibt", correct: true }, { text: "Im Verhältnis drei Kompressionen zu einer Beatmung", correct: true }, { text: "Unter 100 % Sauerstoff gemäß dargestelltem ERC-Algorithmus", correct: true }, { text: "Bei jeder Akrozyanose unabhängig von Atmung und Herzfrequenz" }], source: "Nach effektiver Beatmung und fortbestehender HF <60/min folgen Kompressionen 3:1 und Re-Evaluation." },
  { id: "geburt-q-17", mode: "multiple", difficulty: 3, prompt: "Welche Befunde sprechen bei einer Gebärenden für eine unmittelbare mütterliche und fetale Gefährdung?", options: [{ text: "Zerreißschmerz mit Schockzeichen bei möglicher Uterusruptur", correct: true }, { text: "Brettharter Uterus und Blutung bei möglicher Plazentaablösung", correct: true }, { text: "Nabelschnurvorfall nach Blasensprung", correct: true }, { text: "Regelmäßige Kindsbewegung ohne Beschwerden als alleinige Red Flag" }], source: "Uterusruptur, Plazentaablösung und Nabelschnurvorfall sind zeitkritische Gefahren für Mutter und Kind." },
  { id: "geburt-q-18", mode: "multiple", difficulty: 3, prompt: "Welche Angaben gehören in eine belastbare Übergabe nach präklinischer Geburt?", options: [{ text: "Geburtszeit, Schwangerschaftswoche, Lage und Geburtsverlauf", correct: true }, { text: "Mütterliche Vitalwerte, Blutverlust, Plazentastatus und Maßnahmen", correct: true }, { text: "Atmung, Herzfrequenz, Tonus, Hautfarbe, Temperatur und Verlauf des Neugeborenen", correct: true }, { text: "Nur der APGAR-Gesamtwert ohne Einzelbefunde oder Zeitpunkte" }], source: "Mutter und Kind benötigen getrennte, zeitbezogene Befund- und Maßnahmenverläufe einschließlich Geburts- und Abnabelungszeit." },
];

export const geburtQuestions: MultipleChoiceQuestion[] = [...geburtBaseQuestions, ...supplementalQuestions.geburt];
