import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct?: boolean];
function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  return { id: `herzbeuteltamponade-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: options.map(([text, correct]) => ({ text, correct })), source, difficulty };
}

export const herzbeuteltamponadeFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "herzbeuteltamponade-card-01", area: "Definition", question: "Definieren Sie die Herzbeuteltamponade und ordnen Sie die Schockform ein.", answer: "Flüssigkeit im Perikardraum erhöht den äußeren Druck auf das Herz und behindert die diastolische Füllung. Schlagvolumen und Herzzeitvolumen fallen ab. Es handelt sich um einen obstruktiven Schock." },
  { id: "herzbeuteltamponade-card-02", area: "Abgrenzung", question: "Worin unterscheiden sich Perikarderguss und Perikardtamponade?", answer: "Der Perikarderguss beschreibt Flüssigkeit im Perikardraum. Eine Tamponade liegt erst vor, wenn der intraperikardiale Druck die Herzfüllung hämodynamisch relevant behindert." },
  { id: "herzbeuteltamponade-card-03", area: "Anatomie", question: "Welche Schichten begrenzen den Perikardraum?", answer: "Das viszerale Blatt des serösen Perikards liegt dem Herzen als Epikard auf; gegenüber liegt das parietale Blatt. Das fibröse Perikard bildet die äußere, wenig dehnbare Hülle." },
  { id: "herzbeuteltamponade-card-04", area: "Pathophysiologie", question: "Warum werden rechter Vorhof und rechter Ventrikel zuerst komprimiert?", answer: "Ihre Füllungsdrücke sind niedriger und ihre Wände dünner. Der steigende intraperikardiale Druck überschreitet daher zuerst die rechtsseitigen Drücke." },
  { id: "herzbeuteltamponade-card-05", area: "Pathophysiologie", question: "Leiten Sie die Kausalkette von der Einblutung bis zur PEA her.", answer: "Perikardvolumen steigt → intraperikardialer Druck steigt → rechtsseitige Füllung sinkt → linksventrikuläre Vorlast sinkt → Schlagvolumen und Herzzeitvolumen fallen → Schock → elektrische Aktivität ohne ausreichenden mechanischen Auswurf, also PEA." },
  { id: "herzbeuteltamponade-card-06", area: "Dynamik", question: "Warum ist die Geschwindigkeit der Flüssigkeitsansammlung wichtiger als eine starre Milliliterzahl?", answer: "Bei rascher Ansammlung kann sich das wenig dehnbare Perikard nicht anpassen; schon relativ wenig Volumen wird kritisch. Bei langsamem Erguss kann sich das Perikard ausdehnen und größere Mengen vorübergehend tolerieren." },
  { id: "herzbeuteltamponade-card-07", area: "Ursachen", question: "Nennen Sie vier wichtige Ursachen einer Tamponade.", answer: "Penetrierendes oder stumpfes Thoraxtrauma, Aortendissektion, freie Herzwandruptur nach Myokardinfarkt sowie Perikarditis oder maligner Erguss." },
  { id: "herzbeuteltamponade-card-08", area: "Trauma", question: "Was bezeichnet die Cardiac Box und warum ist sie relevant?", answer: "Sie beschreibt die vordere Thoraxregion über dem Herzen. Eine penetrierende Verletzung dort erhöht den Verdacht auf Herz- und Perikardverletzung, ohne andere Eintrittsstellen als ungefährlich auszuschließen." },
  { id: "herzbeuteltamponade-card-09", area: "Klinik", question: "Nennen Sie die Beck-Trias und ihre Grenze im Trauma.", answer: "Hypotonie, gestaute Halsvenen und gedämpfte Herztöne. Beim Trauma ist sie oft unvollständig: Hypovolämie kann die Halsvenen entleeren, und Lärm erschwert die Auskultation." },
  { id: "herzbeuteltamponade-card-10", area: "Klinik", question: "Was ist ein Pulsus paradoxus?", answer: "Ein übermäßiger inspiratorischer Abfall des systolischen Blutdrucks um mehr als 10 mmHg mit Pulsabschwächung. Er kann die Diagnose stützen, ist präklinisch aber schwer zuverlässig zu erfassen." },
  { id: "herzbeuteltamponade-card-11", area: "EKG", question: "Welche EKG-Befunde können vorkommen und wie sind sie zu bewerten?", answer: "Sinustachykardie, Niedervoltage und elektrische Alternans sind möglich, aber weder sensitiv noch spezifisch genug, um die Tamponade zu beweisen oder auszuschließen." },
  { id: "herzbeuteltamponade-card-12", area: "POCUS", question: "Welche sonografischen Befunde sprechen für hämodynamische Relevanz?", answer: "Perikardflüssigkeit im passenden klinischen Kontext sowie ein systolischer Kollaps des rechten Vorhofs und später ein diastolischer Kollaps des rechten Ventrikels." },
  { id: "herzbeuteltamponade-card-13", area: "Differenzialdiagnose", question: "Wie grenzt man Tamponade und Spannungspneumothorax präklinisch ab?", answer: "Beide verursachen obstruktiven Schock. Für Spannungspneumothorax sprechen einseitig fehlendes Atemgeräusch, Thoraxasymmetrie und steigender Beatmungsdruck; POCUS kann Perikardflüssigkeit zeigen. Bei Instabilität darf die Thoraxentlastung nicht verzögert werden." },
  { id: "herzbeuteltamponade-card-14", area: "Beatmung", question: "Warum ist positive Druckbeatmung gefährlich?", answer: "Sie erhöht den intrathorakalen Druck, vermindert den venösen Rückstrom und kann die ohnehin reduzierte Vorlast weiter senken. Zwingend notwendige Beatmung erfolgt kreislaufschonend und eng überwacht." },
  { id: "herzbeuteltamponade-card-15", area: "Volumen", question: "Welche Rolle hat Volumentherapie bei Tamponade?", answer: "Eine vorsichtige zielgerichtete Gabe kann bei Hypotonie vorübergehend den Füllungsdruck stützen. Sie ist nur eine Brücke und beseitigt die mechanische Obstruktion nicht." },
  { id: "herzbeuteltamponade-card-16", area: "Erstmaßnahmen", question: "Was sind die wichtigsten präklinischen Prioritäten?", answer: "cABCDE, Blutungskontrolle, frühe Notarztnachforderung, Monitoring, Zugang, bedarfsgerechte Oxygenierung, Kreislaufbrücke, kurze Szenenzeit, Voranmeldung und rascher Transport in eine Klinik mit operativer Interventionsmöglichkeit." },
  { id: "herzbeuteltamponade-card-17", area: "Perikardpunktion", question: "Warum kann eine Perikardpunktion beim traumatischen Hämatoperikard scheitern?", answer: "Blut im Herzbeutel gerinnt häufig und kann durch eine kleinlumige Nadel oder Drainage nicht sicher aspiriert werden. Fehlende Aspiration schließt die Tamponade nicht aus." },
  { id: "herzbeuteltamponade-card-18", area: "Definitive Therapie", question: "Warum ersetzt die Perikardpunktion die Operation nicht?", answer: "Sie kann höchstens vorübergehend Druck senken, kontrolliert aber die Blutungsquelle nicht und ist bei Koaguloperikard unzuverlässig. Definitiv sind chirurgische Entlastung und Blutstillung." },
  { id: "herzbeuteltamponade-card-19", area: "Reanimation", question: "Welche Bedeutung hat die Tamponade beim traumatischen Kreislaufstillstand?", answer: "Sie ist eine potenziell reversible Ursache, besonders nach penetrierendem Thoraxtrauma. Die mechanische Entlastung muss durch ein kompetentes, ausgerüstetes Team ohne vermeidbare Verzögerung erfolgen." },
  { id: "herzbeuteltamponade-card-20", area: "Rollenabgrenzung", question: "Was ist die Kernaufgabe des Notfallsanitäters bei vermuteter Tamponade?", answer: "Erkennen und priorisieren, reversible Ursachen differenzieren, Basismaßnahmen und Kreislaufbrücke durchführen, Notarzt und Zielklinik früh organisieren, invasive Therapie vorbereiten und assistieren sowie schnell transportieren." },
];

export const herzbeuteltamponadeQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen definieren die Herzbeuteltamponade korrekt?", [["Der intraperikardiale Druck behindert die diastolische Herzfüllung", true], ["Sie führt pathophysiologisch zu einem obstruktiven Schock", true], ["Jeder sonografisch sichtbare Perikarderguss ist bereits eine Tamponade"], ["Das Primärproblem ist zwingend eine verminderte Myokardkontraktilität"]], "Tamponade bezeichnet die hämodynamisch relevante Füllungsbehinderung, nicht nur vorhandene Flüssigkeit."),
  q(2, "Warum kann eine akute Einblutung rascher kritisch werden als ein langsam wachsender Erguss?", [["Das Perikard kann sich an eine schnelle Volumenzunahme kaum anpassen", true], ["Der Druck steigt bei schneller Ansammlung früh an", true], ["Die Geschwindigkeit ist bedeutungslos, solange das Volumen unter einem Liter liegt"], ["Langsame Ergüsse verursachen grundsätzlich niemals eine Tamponade"]], "Geschwindigkeit, Volumen und Dehnbarkeit bestimmen gemeinsam die Kreislaufwirkung."),
  q(3, "Welche Strukturen sind bei steigendem Perikarddruck typischerweise früh betroffen?", [["Rechter Vorhof", true], ["Rechter Ventrikel", true], ["Aorta descendens als erste kollabierende Herzhöhle"], ["Linker Ventrikel ausschließlich während der Austreibungsphase"]], "Die niedrigen rechtsseitigen Füllungsdrücke werden zuerst vom Perikarddruck überschritten."),
  q(4, "Welche Kausalkette erklärt den obstruktiven Schock bei Tamponade?", [["Rechtsherzfüllung sinkt → linksventrikuläre Vorlast sinkt → Schlagvolumen fällt", true], ["Herzzeitvolumen sinkt → Organperfusion nimmt ab", true], ["Perikarddruck steigt → venöser Rückstrom in die Kammern verbessert sich"], ["Tachykardie beseitigt die mechanische Füllungsbehinderung"]], "Die mechanische Füllungsblockade reduziert Vorlast, Schlagvolumen und Herzzeitvolumen."),
  q(5, "Welche Ursachen können eine Herzbeuteltamponade auslösen?", [["Penetrierendes Thoraxtrauma", true], ["Aortendissektion mit Einblutung", true], ["Freie Herzwandruptur nach Myokardinfarkt", true], ["Perikarditis mit relevantem Erguss", true], ["Isolierte Hyperventilation ohne strukturelle Erkrankung"]], "Traumatische Blutung, Ruptur und entzündliche oder maligne Ergüsse sind wichtige Ursachen."),
  q(6, "Ein Patient ist nach Messerstich im präkordialen Thorax hypotensiv und tachykard. Welche Überlegungen sind richtig?", [["Eine Tamponade muss als reversible Ursache früh bedacht werden", true], ["Eine gleichzeitig bestehende Hypovolämie ist möglich", true], ["Flache Halsvenen schließen eine Tamponade sicher aus"], ["Ein unauffälliges Monitor-EKG beendet die weitere Suche"]], "Penetrierendes Trauma und Schock verlangen die parallele Suche nach Tamponade, Blutung und Spannungspneumothorax."),
  q(7, "Welche Befunde bilden die klassische Beck-Trias?", [["Hypotonie", true], ["Gestaute Halsvenen", true], ["Gedämpfte Herztöne", true], ["Einseitig fehlendes Atemgeräusch"], ["Hypertonie mit Bradykardie"]], "Die Trias kann die Diagnose stützen, ist besonders im Trauma aber häufig unvollständig."),
  q(8, "Warum darf die Beck-Trias beim Trauma nicht als Ausschlusstest verwendet werden?", [["Hypovolämie kann eine Halsvenenstauung verdecken", true], ["Gedämpfte Herztöne sind in lauter Umgebung schwer zu beurteilen", true], ["Hypotonie besitzt mehrere mögliche traumatische Ursachen", true], ["Die Trias tritt bei jeder Tamponade vollständig auf"]], "Die drei Befunde sind klinisch störanfällig und wenig sensitiv."),
  q(9, "Welche Aussagen zum Pulsus paradoxus sind richtig?", [["Der systolische Blutdruck fällt während der Inspiration übermäßig ab", true], ["Ein Abfall um mehr als 10 mmHg gilt als suggestiv", true], ["Er ist präklinisch oft schwer zuverlässig zu messen", true], ["Er beweist allein eine traumatische Tamponade"], ["Er bezeichnet eine Pulssteigerung bei Exspiration um exakt 10/min"]], "Der Pulsus paradoxus ist ein unterstützender, kein beweisender Befund."),
  q(10, "Welche EKG-Befunde können bei Tamponade vorkommen?", [["Sinustachykardie", true], ["Niedervoltage", true], ["Elektrische Alternans", true], ["Ein zwingend normales EKG schließt die Tamponade aus"], ["ST-Hebungen beweisen immer eine traumatische Tamponade"]], "Das EKG kann Hinweise geben, besitzt aber keine ausreichende diagnostische Sicherheit."),
  q(11, "Welche POCUS-Befunde sprechen im passenden Kontext für eine hämodynamisch relevante Tamponade?", [["Perikardiale Flüssigkeit", true], ["Kollaps des rechten Vorhofs", true], ["Diastolischer Kollaps des rechten Ventrikels", true], ["Isolierter Pleuraerguss ohne Perikardbefund"], ["Normale freie Beweglichkeit aller Herzhöhlen beweist eine Tamponade"]], "Rechtsseitige Kollapszeichen verbinden den Erguss mit der Kreislaufwirkung."),
  q(12, "Welche Aussage zur Sonografie ist prüfungsrelevant?", [["Sie unterstützt die rasche Diagnose, wenn Gerät und Kompetenz verfügbar sind", true], ["Bei instabilem Thoraxtrauma gehört der Perikardblick zur eFAST-Fragestellung", true], ["Ein Erguss muss mit Klinik und Hämodynamik zusammen bewertet werden", true], ["Die Untersuchung darf den zeitkritischen Transport beliebig verlängern"]], "POCUS ist stark, ersetzt aber weder klinische Einordnung noch zeitkritische Organisation."),
  q(13, "Welche Befunde sprechen eher für einen Spannungspneumothorax als für eine isolierte Tamponade?", [["Einseitig deutlich vermindertes Atemgeräusch", true], ["Zunehmende Thoraxasymmetrie", true], ["Steigender Beatmungsdruck", true], ["Perikardflüssigkeit mit rechtsventrikulärem Kollaps"], ["Gedämpfte Herztöne bei beidseits gleichem Atemgeräusch"]], "Der Spannungspneumothorax zeigt primär eine einseitige ventilatorische und thorakale Konstellation."),
  q(14, "Welche Differenzialdiagnosen können ebenfalls obstruktiven Schock oder PEA verursachen?", [["Spannungspneumothorax", true], ["Massive Lungenarterienembolie", true], ["Ausgeprägte Hypovolämie als andere reversible Ursache", true], ["Unkomplizierte stabile Angina ohne Kreislaufwirkung"], ["Isolierte Tendovaginitis"]], "Beim Kreislaufstillstand werden reversible Ursachen parallel geprüft und priorisiert."),
  q(15, "Warum kann eine positive Druckbeatmung bei Tamponade problematisch sein?", [["Der intrathorakale Druck steigt", true], ["Der venöse Rückstrom kann weiter sinken", true], ["Die rechts- und linksventrikuläre Vorlast kann zusätzlich abnehmen", true], ["Sie entlastet das Perikard zuverlässig"], ["Sie steigert immer das Herzzeitvolumen"]], "Positive Druckbeatmung kann die Vorlastabhängigkeit verschärfen."),
  q(16, "Welche Konsequenzen folgen daraus für das Atemwegsmanagement?", [["Eine zwingend notwendige Atemwegssicherung wird nicht unterlassen", true], ["Beatmungsdruck und PEEP werden so niedrig wie klinisch vertretbar gehalten", true], ["Kreislauf und Kapnografie werden eng überwacht", true], ["Jeder wache Patient wird prophylaktisch invasiv beatmet"], ["Nach Intubation ist keine Re-Evaluation des Kreislaufs erforderlich"]], "Die Indikation bleibt klinisch; die Durchführung muss kreislaufschonend sein."),
  q(17, "Welche Rolle hat eine vorsichtige Volumengabe bei hypotensiver Tamponade?", [["Sie kann den Füllungsdruck vorübergehend stützen", true], ["Sie ist eine Überbrückung bis zur Entlastung", true], ["Ihre Wirkung muss klinisch re-evaluiert werden", true], ["Sie beseitigt die mechanische Obstruktion dauerhaft"], ["Sie ersetzt den schnellen Transport"]], "Volumen ist eine zeitlich begrenzte Kreislaufbrücke, keine definitive Therapie."),
  q(18, "Welche Maßnahmen gehören bei vermuteter traumatischer Tamponade zur frühen Versorgung?", [["cABCDE und äußere Blutungskontrolle", true], ["Frühe Notarztnachforderung", true], ["Kontinuierliches Monitoring und Defibrillationsbereitschaft", true], ["Zeitnahe Voranmeldung in einer geeigneten Zielklinik", true], ["Lange Diagnostik am Einsatzort trotz Instabilität"]], "Erkennen, stabilisieren, eskalieren und ohne vermeidbare Verzögerung zur definitiven Versorgung transportieren."),
  q(19, "Welche Informationen gehören in die fokussierte Anamnese?", [["Traumamechanismus und Zeitpunkt", true], ["Antikoagulanzien oder Thrombozytenhemmer", true], ["Aortenerkrankung, Herzinfarkt, Herzoperation oder Perikarditis", true], ["Dynamik von Dyspnoe, Schmerz und Synkope", true], ["Nur die letzte Mahlzeit"]], "Mechanismus, Blutungsrisiko, Vorerkrankung und Verlauf verändern die Wahrscheinlichkeit und Planung."),
  q(20, "Welche Aussagen zur Perikardpunktion bei traumatischer Tamponade sind richtig?", [["Geronnenes Blut kann die Aspiration verhindern", true], ["Fehlende Aspiration schließt die Tamponade nicht aus", true], ["Sie kann höchstens eine vorübergehende Entlastung sein", true], ["Sie kontrolliert sicher die zugrunde liegende Herzverletzung"], ["Sie ist die reguläre eigenständige Standardmaßnahme jedes Notfallsanitäters"]], "Beim Hämatoperikard ist die Punktion unzuverlässig und ersetzt keine Operation."),
  q(21, "Warum ist die chirurgische Entlastung bei traumatischem Hämatoperikard entscheidend?", [["Das Perikard kann direkt eröffnet werden", true], ["Geronnenes Blut kann entfernt werden", true], ["Eine sichtbare Blutungsquelle kann kontrolliert werden", true], ["Sie wird durch ein entsprechend qualifiziertes Team durchgeführt", true], ["Sie ist durch eine normale Infusion gleichwertig ersetzbar"]], "Definitive Therapie verbindet Druckentlastung und Blutstillung."),
  q(22, "Welche Befunde sprechen für eine drohende oder eingetretene Kreislaufdekompensation?", [["Zunehmende Hypotonie", true], ["Vigilanzminderung", true], ["Schwächer werdende Pulse", true], ["PEA", true], ["Stabile Vitalwerte ohne Dynamik und ohne Beschwerden"]], "Fortschreitende Minderperfusion bis zur PEA markiert die Verschlechterung."),
  q(23, "Ein Patient mit vermuteter Tamponade wird nach Einleitung positiver Druckbeatmung abrupt hypotensiver. Welche Schlussfolgerungen sind sinnvoll?", [["Der verminderte venöse Rückstrom kann die Dekompensation ausgelöst haben", true], ["Beatmungsdruck und PEEP müssen kritisch überprüft werden", true], ["Andere reversible Ursachen wie Spannungspneumothorax müssen erneut gesucht werden", true], ["Die Verschlechterung beweist, dass keine Tamponade vorliegt"], ["Die Kreislaufänderung ist für die weitere Therapie bedeutungslos"]], "Nach Atemwegsinterventionen werden Kreislauf, Ventilation und Differenzialdiagnosen sofort neu bewertet."),
  q(24, "Welche Befunde können bei Tamponade und hämorrhagischem Schock gleichzeitig vorkommen?", [["Tachykardie", true], ["Hypotonie", true], ["Blässe und Kaltschweißigkeit", true], ["Vigilanzminderung", true], ["Gestaute Halsvenen müssen bei beiden zwingend vorhanden sein"]], "Unspezifische Schockzeichen überschneiden sich; Mechanismus, Thoraxbefund, Blutungsquellen und POCUS helfen."),
  q(25, "Welche Aussagen zur Zielklinik und Transportentscheidung sind richtig?", [["Die Klinik muss eine rasche operative oder interventionelle Versorgung ermöglichen", true], ["Instabilität verlangt minimale Szenenzeit", true], ["Eine strukturierte Voranmeldung beschleunigt die definitive Therapie", true], ["Ein langes Beobachtungsintervall am Einsatzort verbessert die Tamponade"], ["Eine kleine Klinik ohne Entlastungsmöglichkeit ist grundsätzlich immer das beste Ziel"]], "Die Transportstrategie orientiert sich an Zeitkritik und definitiver Versorgungsmöglichkeit."),
  q(26, "Welche Aussagen beschreiben eine gute Re-Evaluation?", [["Blutdruck, Pulsqualität und Bewusstsein werden als Trend beurteilt", true], ["Nach Volumen oder Beatmungsänderung wird die Wirkung geprüft", true], ["Thoraxbefund und Atemgeräusche werden wiederholt kontrolliert", true], ["Ein einmal normaler Blutdruck beendet die Überwachung"], ["Nur die Herzfrequenz wird dokumentiert"]], "Tamponade ist dynamisch; jede Intervention verlangt eine erneute cABCDE-Beurteilung."),
  q(27, "Welche Fehler gefährden den Patienten besonders?", [["Auf die vollständige Beck-Trias warten", true], ["Die Sonografie bei Instabilität zum Selbstzweck verlängern", true], ["Aggressive positive Druckbeatmung ohne Kreislaufbezug", true], ["Perikardpunktion als sichere definitive Therapie ansehen", true], ["Frühe Zielklinikkommunikation"]], "Verzögerung, falsche diagnostische Sicherheit und vorlastsenkende Maßnahmen können die Dekompensation beschleunigen."),
  q(28, "Welche Befunde machen eine traumatische Tamponade bei PEA besonders plausibel?", [["Penetrierende Verletzung der präkordialen Region", true], ["Vorherige Schockzeichen mit abruptem Kreislaufstillstand", true], ["Perikardflüssigkeit im POCUS", true], ["Rechtsseitige Kollapszeichen im passenden Kontext", true], ["Isolierte Knöcheldistorsion ohne Thoraxmechanismus"]], "Mechanismus, Verlauf und Ultraschallbefund werden gemeinsam bewertet."),
  q(29, "Welche Aussagen zur Rollenabgrenzung sind richtig?", [["Der Notfallsanitäter erkennt und priorisiert die reversible Ursache", true], ["Er organisiert früh Notarzt und geeignete Klinik", true], ["Er bereitet invasive Maßnahmen vor und assistiert im zulässigen Rahmen", true], ["Perikardpunktion und Thorakotomie gehören regulär zur eigenständigen Standardtherapie des Notfallsanitäters"], ["Ohne invasive Kompetenz sind Basismaßnahmen und Zeitmanagement bedeutungslos"]], "Die präklinische Kernleistung ist frühzeitiges Erkennen, Stabilisieren, Eskalieren und Transportieren."),
  q(30, "Welche vollständige Prüfungsantwort ist bei instabilem Patienten nach Thoraxpenetration am überzeugendsten?", [["cABCDE mit paralleler Blutungs- und Thoraxbeurteilung", true], ["Tamponade, Spannungspneumothorax und Hypovolämie gleichzeitig differenzieren", true], ["Notarzt, POCUS wenn verfügbar, Kreislaufbrücke und unmittelbare Zielklinikorganisation", true], ["Definitive operative Entlastung als zeitkritisches Ziel benennen", true], ["Die Diagnose erst nach vollständiger Beck-Trias erwägen"]], "Eine starke Antwort verbindet Mechanismus, Schockform, parallele Differenzialdiagnostik und definitive Therapie."),
];
