import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function HerzbeuteltamponadeLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>Herzbeuteltamponade</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;

  return <article className="lesson-article rippenfraktur-lesson schock-lesson herzbeuteltamponade-lesson">
    <div className="lesson-intro"><p className="lead">Füllungsbehinderung erkennen, obstruktiven Schock verstehen und die definitive Versorgung beschleunigen.</p></div>

    {section("01", "Definition", <><p>Bei der <b>Herzbeuteltamponade</b> erhöht Flüssigkeit, meist Blut, den Druck im Perikardraum so stark, dass sich das Herz in der Diastole nicht mehr ausreichend füllen kann. Schlagvolumen und Herzzeitvolumen fallen ab. Es entsteht ein <b>obstruktiver Schock</b>.</p><div className="pulmo-compare"><div><small>Perikarderguss</small><h3>Flüssigkeit vorhanden</h3><p>Flüssigkeit liegt zwischen viszeralem und parietalem Blatt des serösen Perikards. Sie muss noch keine relevante Kreislaufstörung verursachen.</p></div><div><small>Perikardtamponade</small><h3>Füllung behindert</h3><p>Der intraperikardiale Druck beeinträchtigt die diastolische Füllung und damit die Auswurfleistung des Herzens.</p></div></div><aside className="red-flags"><span>!</span><div><small>Prüfungsfalle</small><h3>Obstruktiv, nicht kardiogen</h3><p>Das Myokard kann grundsätzlich kontraktionsfähig sein. Das Problem ist die mechanische Behinderung der Herzfüllung. Deshalb behebt reine Kreislaufunterstützung die Ursache nicht.</p></div></aside></>)}

    {section("02", "Anatomie und Physiologie", <><Figure src="/lessons/acs/herz-anatomie.png" alt="Beschriftete Anatomie des Herzens" caption="Herzanatomie · Vorhöfe, Kammern und große Gefäße" /><div className="reading-columns"><div><h3>Herzbeutel</h3><p>Das Herz liegt im Perikard. Das fibröse Perikard begrenzt eine schnelle Ausdehnung; das seröse Perikard besitzt ein parietales und ein viszerales Blatt. Dazwischen liegt normalerweise nur wenig Gleitflüssigkeit.</p></div><div><h3>Warum rechts zuerst?</h3><p>Rechter Vorhof und rechter Ventrikel arbeiten mit niedrigeren Drücken als die linke Herzhälfte. Steigt der Druck im Herzbeutel, werden diese dünnwandigen Strukturen deshalb früher komprimiert.</p></div></div><h3>Herzzyklus und Angriffspunkt</h3><div className="pulmo-vfa-flow"><div><span>1</span><b>Diastole</b><small>Die Kammern entspannen sich und nehmen Blut auf.</small></div><div><span>2</span><b>Vorlast</b><small>Venöser Rückstrom dehnt die Kammern vor der Kontraktion.</small></div><div><span>3</span><b>Systole</b><small>Das gefüllte Herz wirft Blut in Lungen- und Körperkreislauf aus.</small></div><div><span>!</span><b>Tamponade</b><small>Äußerer Druck verhindert die Füllung – die Vorlast und das Schlagvolumen sinken.</small></div></div><p><b>Entscheidend ist nicht nur die Flüssigkeitsmenge.</b> Eine rasche Einblutung kann bereits bei vergleichsweise geringem Volumen kritisch werden; eine langsam entstehende Flüssigkeitsansammlung kann das Perikard länger kompensieren.</p></>)}

    {section("03", "Ursachen, Entstehung und Pathophysiologie", <><h3>Typische Ursachen</h3><div className="shock-type-grid"><div><small>Traumatisch</small><h3>Penetrierend</h3><p>Stich-, Schuss- oder Pfählungsverletzung im Bereich des Thorax, besonders innerhalb der „Cardiac Box“.</p></div><div><small>Traumatisch</small><h3>Stumpf</h3><p>Herz- oder Koronargefäßverletzung nach erheblicher stumpfer Gewalteinwirkung.</p></div><div><small>Spontan</small><h3>Blutung oder Ruptur</h3><p>Aortendissektion, freie Herzwandruptur nach Myokardinfarkt oder Einblutung unter Antikoagulation.</p></div><div><small>Nicht traumatisch</small><h3>Erguss</h3><p>Perikarditis, Malignom, Urämie, Autoimmunerkrankung oder postoperative Komplikation.</p></div></div><h3>Pathophysiologie in sechs Schritten</h3><div className="pulmo-vfa-flow"><div><span>01</span><b>Flüssigkeit sammelt sich</b><small>Blut oder Erguss erhöht das Volumen im kaum dehnbaren Perikardraum.</small></div><div><span>02</span><b>Druck steigt</b><small>Der intraperikardiale Druck nähert sich den Füllungsdrücken des Herzens.</small></div><div><span>03</span><b>Rechtsherz kollabiert</b><small>Zuerst werden rechter Vorhof und rechter Ventrikel in ihrer Füllung behindert.</small></div><div><span>04</span><b>Vorlast fällt</b><small>Weniger Blut gelangt durch die Lunge in den linken Ventrikel.</small></div><div><span>05</span><b>HZV fällt</b><small>Schlagvolumen, Blutdruck und Organperfusion sinken; Tachykardie und Vasokonstriktion kompensieren.</small></div><div><span>06</span><b>PEA droht</b><small>Elektrische Aktivität kann fortbestehen, obwohl mechanisch kaum noch Auswurf möglich ist.</small></div></div><aside className="diagnostic-boundary"><span>!</span><div><b>Positive Druckbeatmung kann die Lage verschlechtern</b><p>Sie erhöht den intrathorakalen Druck und vermindert den venösen Rückstrom zusätzlich. Eine zwingend notwendige Atemwegssicherung darf nicht unterlassen werden, muss aber mit enger Kreislaufkontrolle und möglichst zurückhaltendem Beatmungsdruck erfolgen.</p></div></aside></>)}

    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", <><h3>Beck-Trias · Hinweis, kein Pflichtbefund</h3><div className="pulmo-care-grid"><div><span>1</span><b>Hypotonie</b><small>Folge des sinkenden Schlagvolumens.</small></div><div><span>2</span><b>Gestaute Halsvenen</b><small>Venöser Rückstau vor dem komprimierten rechten Herzen.</small></div><div><span>3</span><b>Gedämpfte Herztöne</b><small>Können vorhanden, im Einsatz aber schwer beurteilbar sein.</small></div></div><p>Beim Traumapatienten kann eine begleitende Hypovolämie die Halsvenen trotz Tamponade flach erscheinen lassen. Lärm erschwert die Auskultation. Das Fehlen der Trias schließt die Tamponade deshalb <b>nicht</b> aus.</p><div className="rib-fracture-grid">{[["Kreislauf", "Tachykardie, Hypotonie, enge Pulsdruckamplitude, schwache periphere Pulse, verlängerte Rekapillarisierung."], ["Atmung", "Dyspnoe, Tachypnoe, Zyanose oder zunehmende Erschöpfung."], ["Allgemein", "Angst, Unruhe, Blässe, Kaltschweißigkeit, Schwindel und Vigilanzminderung."], ["Thorax", "Druckgefühl oder Schmerz; bei Trauma können andere Verletzungen den Befund überlagern."], ["Pulsus paradoxus", "Inspiratorischer Abfall des systolischen Blutdrucks um mehr als 10 mmHg; präklinisch oft schwer zuverlässig zu erfassen."], ["EKG", "Sinustachykardie, Niedervoltage oder elektrische Alternans möglich – kein Befund beweist oder widerlegt die Tamponade allein."]].map(([title,text])=><div key={title}><b>{title}</b><span>{text}</span></div>)}</div><h3>POCUS / eFAST</h3><p>Der Perikardblick kann Flüssigkeit im Herzbeutel zeigen. Zeichen hämodynamischer Relevanz sind insbesondere ein Kollaps des rechten Vorhofs und später des rechten Ventrikels. Befund, Mechanismus und Kreislauf müssen gemeinsam bewertet werden; die Untersuchung darf die zeitkritische Versorgung nicht verzögern.</p></>)}

    {section("05", "Komplikationen und Gefahren", <><div className="pulmo-risk-grid"><div><b>Obstruktiver Schock</b><p>Sinkendes Herzzeitvolumen verursacht fortschreitende Organminderperfusion.</p></div><div><b>Myokardischämie</b><p>Hypotonie und verminderte Koronarperfusion verschlechtern die Herzleistung weiter.</p></div><div><b>Bewusstlosigkeit</b><p>Zerebrale Minderperfusion erhöht zusätzlich Aspirations- und Atemwegsrisiko.</p></div><div><b>Traumatischer Kreislaufstillstand</b><p>Typisch kann eine PEA entstehen; die mechanische Ursache muss umgehend behoben werden.</p></div></div><aside className="red-flags"><span>!</span><div><small>Zeitkritisch</small><h3>Definitive Entlastung rettet den Kreislauf</h3><p>Volumen oder Katecholamine können nur überbrücken. Ohne Entlastung bleibt die mechanische Füllungsbehinderung bestehen.</p></div></aside></>)}

    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", <div className="material-chips">{["Persönliche Schutzausrüstung", "Traumatasche und Blutungskontrolle", "Atemweg und Absaugung", "Sauerstoff und Beatmungsbeutel", "Monitoring und Defibrillationselektroden", "12-Kanal-EKG", "Kapnografie bei Beatmung", "i.v.- und i.o.-Material", "Infusionslösung nach Lage", "POCUS, wenn verfügbar und beherrscht", "Wärmeerhalt", "Trage- und Rettungsmittel"].map(item=><span key={item}>{item}</span>)}</div>)}

    {section("07", "Erstmaßnahmen, Diagnostik und Anamnese", <><div className="pulmo-care-grid"><div><span>c</span><b>Kritische Blutung</b><small>Äußere Blutung sofort kontrollieren; penetrierenden Fremdkörper belassen und stabilisieren.</small></div><div><span>A</span><b>Atemweg</b><small>Freihalten, absaugen und Schutzreflexe beurteilen.</small></div><div><span>B</span><b>Atmung</b><small>Thorax untersuchen, Spannungspneumothorax differenzieren, Oxygenierung bedarfsgerecht sichern.</small></div><div><span>C</span><b>Kreislauf</b><small>Pulse, Rekap, RR-Trend, EKG, Zugang und Schockzeichen; Tamponade als reversible Ursache denken.</small></div><div><span>D</span><b>Neurologie</b><small>Bewusstsein, Pupillen und Blutzucker kontrollieren.</small></div><div><span>E</span><b>Exposure</b><small>Verletzungsmuster und Cardiac Box inspizieren, vollständig untersuchen, Wärme erhalten.</small></div></div><h3>SAMPLERS · fokussiert</h3><div className="samplers-grid">{[["S · Symptome", "Beginn, Dyspnoe, Thoraxschmerz, Schwindel, Synkope"], ["A · Allergien", "Relevanz für Analgesie und weitere Therapie"], ["M · Medikamente", "Antikoagulanzien, Thrombozytenhemmer, Herzmedikamente"], ["P · Vorgeschichte", "Perikarditis, Tumor, Urämie, Aortenerkrankung, Herzinfarkt oder Herzoperation"], ["L · Letzte Aufnahme", "Für Narkose- und OP-Planung erfassen"], ["E · Ereignis", "Mechanismus, Zeitpunkt, Cardiac Box, Dynamik"], ["R · Risiken", "Blutung, Gerinnungshemmung, invasive Eingriffe"], ["S · Schwangerschaft", "Schwangerschaft erfragen und Lagerung anpassen"]].map(([label,text])=><p key={label}><b>{label}</b>{text}</p>)}</div><p><b>Früh handeln:</b> Notarzt und geeignete Zielklinik sofort disponieren, kontinuierlich re-evaluieren und bei Instabilität Load-go-and-treat. Ein unauffälliges Einzel-EKG schließt die Tamponade nicht aus.</p></>)}

    {section("08", "Differenzialdiagnosen und Entscheidungsfindung", <><div className="shock-differential-table"><div className="head"><b>Diagnose</b><b>Gemeinsamkeit</b><b>Hinweis zur Abgrenzung</b><b>Konsequenz</b></div><div><b>Spannungspneumothorax</b><span data-label="Gemeinsamkeit">Obstruktiver Schock, Dyspnoe, Halsvenenstau möglich</span><span data-label="Abgrenzung">Einseitig fehlendes Atemgeräusch, Thoraxasymmetrie, zunehmender Beatmungsdruck</span><span data-label="Konsequenz">Bei Instabilität nach VFA sofort Thorax entlasten</span></div><div><b>Hämorrhagischer Schock</b><span data-label="Gemeinsamkeit">Hypotonie, Tachykardie, Blässe</span><span data-label="Abgrenzung">Blutungsquelle, eher flache Halsvenen; kann gleichzeitig bestehen</span><span data-label="Konsequenz">Blutungskontrolle und Traumapfad</span></div><div><b>Massive Lungenarterienembolie</b><span data-label="Gemeinsamkeit">Obstruktiver Schock, Rechtsherzbelastung, PEA</span><span data-label="Abgrenzung">Risikoprofil, keine perikardiale Flüssigkeit, sonografisch andere Konstellation</span><span data-label="Konsequenz">Emboliepfad und rasche ärztliche Therapie</span></div><div><b>ACS / Pumpversagen</b><span data-label="Gemeinsamkeit">Thoraxschmerz, Schock, EKG-Veränderung</span><span data-label="Abgrenzung">Koronare Ischämie oder Lungenstauung ohne mechanische Perikardkompression</span><span data-label="Konsequenz">ACS- oder Herzinsuffizienzpfad</span></div></div><h3>Prüfungsfallen</h3><ul className="script-list"><li><b>Beck-Trias:</b> klassisch, aber beim Trauma unzuverlässig und häufig unvollständig.</li><li><b>Volumen:</b> kann die Vorlast kurzfristig stützen, beseitigt die Obstruktion aber nicht.</li><li><b>Beatmung:</b> Intubation und positiver Druck können den venösen Rückstrom weiter senken.</li><li><b>POCUS:</b> ein Erguss allein ist nicht automatisch eine Tamponade; Kreislaufwirkung und Rechtsherzkollaps entscheiden.</li><li><b>Perikardpunktion:</b> fehlende Aspiration schließt die Diagnose nicht aus – traumatisches Blut kann gerinnen.</li><li><b>Gleichzeitige Ursachen:</b> Tamponade, Hypovolämie und Spannungspneumothorax können gemeinsam vorliegen.</li></ul></>)}

    {section("09", "Weitere Maßnahmen und definitive Versorgung", <><div className="pulmo-vfa-flow"><div><span>1</span><b>Ressourcen</b><small>Notarzt, Schockraum und bei Bedarf RTH früh alarmieren.</small></div><div><span>2</span><b>Kreislaufbrücke</b><small>Zugang, vorsichtige zielgerichtete Volumengabe bei Hypotonie und engmaschige Re-Evaluation.</small></div><div><span>3</span><b>Transport</b><small>Minimale Szenenzeit, Voranmeldung und Klinik mit sofortiger operativer Interventionsmöglichkeit.</small></div><div><span>4</span><b>Definitive Therapie</b><small>Perikardentlastung und Blutungskontrolle durch ein qualifiziertes ärztlich-chirurgisches Team.</small></div></div><div className="reading-columns"><div><h3>Perikardpunktion</h3><p>Kann bei ausgewählten instabilen Patienten vorübergehend entlasten. Beim traumatischen Hämatoperikard ist sie wegen geronnenen Blutes unsicher und ersetzt die operative Versorgung nicht.</p></div><div><h3>Resuscitative Thorakotomie</h3><p>Bei traumatischem Kreislaufstillstand durch penetrierende Verletzung kann sie die Tamponade direkt entlasten und eine Blutung kontrollieren – aber ausschließlich bei passender Indikation, Kompetenz, Ausrüstung und Umgebung.</p></div></div><aside className="diagnostic-boundary"><span>!</span><div><b>Rollenabgrenzung Notfallsanitäter</b><p>Perikardpunktion und Thorakotomie sind keine regulären eigenständigen Maßnahmen des Notfallsanitäters. Entscheidend sind Erkennen, frühe Eskalation, Vorbereitung, Assistenz, sichere Basistherapie und unverzüglicher Transport.</p></div></aside><h3>Traumaalgorithmus Thüringen</h3><Vfa src="/lessons/sht/vfa-trauma-l2.png" alt="Thüringer VFA L2 Leitalgorithmus Trauma" caption="L2 · Leitalgorithmus Trauma 2026/2027" /></>)}

    {children}
    <p className="lesson-source">Grundlage: „48. Herzbeuteltamponade.pdf“ und „48.Perikardtamponade.docx“. Fachlich ergänzt und geprüft anhand der <a href="https://register.awmf.org/assets/guidelines/187-023l_S3_Polytrauma-Schwerverletzten-Behandlung_2023-06.pdf" target="_blank" rel="noreferrer">S3-Leitlinie Polytrauma/Schwerverletzten-Behandlung</a>, der <a href="https://www.erc.edu/media/wwufbysp/gl2025-06-spec-circ-e.pdf" target="_blank" rel="noreferrer">ERC-Leitlinie 2025 zu besonderen Reanimationssituationen</a> sowie der bereitgestellten <a href="https://nerdfallmedizin.de/2020/05/04/04-2020-traumatische-perikardtamponade/" target="_blank" rel="noreferrer">Fachseite zur traumatischen Perikardtamponade</a>. Für den Einsatz gelten die aktuellen Thüringer VFA und örtlichen Vorgaben.</p>
  </article>;
}
