import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function HerzrhythmusstoerungenLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, title: string, kicker: string, body: ReactNode) => (
    <details open className="rib-section" key={number}>
      <summary><header className="chapter-heading"><span>{number}</span><div><small>{kicker}</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary>
      <div className="lesson-prose script-copy">{body}</div>
    </details>
  );

  return <article className="lesson-article rippenfraktur-lesson herzrhythmusstoerungen-lesson">
    <div className="lesson-intro"><p className="lead">Zuerst Puls und Stabilität, danach das EKG: So führt die Rhythmusanalyse sicher zum passenden Behandlungsweg.</p></div>

    {section("01", "Definition und Einteilung", "Was ist gestört?", <>
      <p>Eine <b>Herzrhythmusstörung</b> ist eine Abweichung der normalen Erregungsbildung oder Erregungsleitung. Dadurch verändern sich Frequenz, Regelmäßigkeit, Ursprungsort oder zeitliche Abfolge der Herzaktionen. Nicht jedes abweichende EKG ist vital bedrohlich; entscheidend ist, ob der Rhythmus eine ausreichende Organperfusion ermöglicht.</p>
      <div className="pulmo-anatomy-grid"><div><small>Frequenz</small><b>Bradykard oder tachykard</b><p>Zu langsam oder zu schnell im Verhältnis zur klinischen Situation.</p></div><div><small>Ursprung</small><b>Supraventrikulär oder ventrikulär</b><p>Oberhalb oder innerhalb des ventrikulären Leitungssystems und Myokards entstanden.</p></div><div><small>Mechanismus</small><b>Bildung oder Leitung</b><p>Der Impuls entsteht falsch, zu häufig, zu selten oder wird verzögert beziehungsweise blockiert.</p></div></div>
      <div className="pulmo-compare"><div><small>Rhythmisch</small><h3>Regelmäßige Abstände</h3><p>Beispielsweise Sinusbradykardie, regelmäßige SVT oder monomorphe VT.</p></div><div><small>Arrhythmisch</small><h3>Unregelmäßige Abstände</h3><p>Beispielsweise Vorhofflimmern, wechselnde Extrasystolen oder polymorphe VT.</p></div></div>
      <aside className="diagnostic-boundary"><span>1→6</span><div><b>Zuerst Klinik, danach EKG-Systematik</b><p><b>Klinik:</b> Puls vorhanden? Stabil oder instabil? <b>EKG:</b> Frequenz → Regelmäßigkeit → P-Welle → PQ-Zeit → QRS-Breite und -Form → ST-Strecke, T-Welle und QT-Zeit.</p></div></aside>
    </>)}

    {section("02", "Anatomie, Reizleitung und EKG", "Anatomie und Physiologie", <>
      <p>Das Herz besteht aus zwei Vorhöfen und zwei Kammern. Rechte Herzhälfte und Lungenkreislauf übernehmen die Oxygenierung, linke Herzhälfte und Körperkreislauf die Organversorgung. Herzklappen lenken den Blutstrom; das Myokard erzeugt die mechanische Pumparbeit.</p>
      <Figure src="/lessons/acs/herz-anatomie.png" alt="Beschriftete Anatomie des Herzens mit Vorhöfen, Kammern, Klappen und großen Gefäßen" caption="Anatomie des Herzens" wide />
      <h3>Vom Taktgeber zur Kammerkontraktion</h3>
      <div className="pulmo-path"><span>Sinusknoten</span><i>→</i><span>Vorhöfe</span><i>→</i><span>AV-Knoten</span><i>→</i><span>His-Bündel</span><i>→</i><span>Tawara / Purkinje</span></div>
      <div className="pulmo-risk-grid"><div><b>Sinusknoten</b><p>Primärer Schrittmacher im rechten Vorhof. Seine spontane Depolarisation bestimmt normalerweise den Grundrhythmus.</p></div><div><b>AV-Knoten</b><p>Verzögert die Überleitung. Dadurch kontrahieren die Vorhöfe vor den Kammern und die Ventrikelfüllung wird unterstützt.</p></div><div><b>His-Tawara-Purkinje</b><p>Leitet die Erregung schnell durch das Septum in beide Kammern und ermöglicht eine koordinierte Ventrikelkontraktion.</p></div><div><b>Ersatzschrittmacher</b><p>Fällt ein höheres Zentrum aus, können tiefere Zentren übernehmen. Je distaler der Ursprung, desto langsamer und häufig breiter ist der Ersatzrhythmus.</p></div></div>
      <Figure src="/lessons/vorhofflimmern/erregungsbildung-skript.png" alt="Reizleitungssystem des Herzens mit Sinusknoten, AV-Knoten, His-Bündel, Tawara-Schenkeln und Purkinje-Fasern" caption="Erregungsbildung und Reizleitung" wide />
      <h3>Elektrik der Herzmuskelzelle</h3>
      <p>Die Zellmembran trennt unterschiedliche Konzentrationen von Natrium, Kalium und Calcium. Ionenströme erzeugen <b>Depolarisation</b> und <b>Repolarisation</b>. Die Na⁺/K⁺-ATPase erhält unter ATP-Verbrauch die Ionengradienten. Während der absoluten Refraktärzeit kann kein neuer wirksamer Impuls ausgelöst werden; unterschiedliche Leitungs- und Erholungszeiten können jedoch Reentry begünstigen.</p>
      <div className="pulmo-anatomy-grid"><div><small>P-Welle</small><b>Vorhofdepolarisation</b><p>Geordnete Ausbreitung vom Sinusknoten über beide Vorhöfe.</p></div><div><small>PQ-Zeit</small><b>AV-Überleitung</b><p>Von Beginn der Vorhoferregung bis zum Beginn der Kammererregung.</p></div><div><small>QRS / T</small><b>Kammererregung</b><p>QRS: Depolarisation. T-Welle: Repolarisation der Ventrikel.</p></div></div>
      <Figure src="/lessons/acs/ekg-grundlagen.png" alt="EKG-Grundlagen mit P-Welle, PQ-Zeit, QRS-Komplex, ST-Strecke und T-Welle" caption="EKG-Grundlagen" wide />
      <h3>EKG in sechs Schritten beschreiben</h3>
      <div className="pulmo-care-grid"><div><span>1</span><b>Frequenz</b><small>Bradykard, normofrequent oder tachykard?</small></div><div><span>2</span><b>Regelmäßigkeit</b><small>R-R-Abstände regelmäßig oder unregelmäßig? Bei Vorhofaktivität zusätzlich P-P-Abstände prüfen.</small></div><div><span>3</span><b>P-Welle</b><small>Vorhanden? Gleichförmig? Vor jedem QRS? Folgt auf jede P-Welle ein QRS?</small></div><div><span>4</span><b>PQ-Zeit</b><small>Konstant, über 200 ms, zunehmend länger oder ohne feste Beziehung zum QRS?</small></div><div><span>5</span><b>QRS-Breite</b><small>Schmal unter 120 ms oder breit ab 120 ms? Form gleichbleibend oder wechselnd?</small></div><div><span>6</span><b>ST, T und QT</b><small>Ischämiezeichen, Repolarisationsstörung oder auffällig verlängerte QT-Zeit?</small></div></div>
      <aside className="diagnostic-boundary"><span>P↔QRS</span><div><b>Die entscheidende Beziehungsfrage</b><p>Nicht nur nach einer P-Welle suchen: Prüfen, ob vor jedem QRS eine P-Welle steht, ob jede P-Welle übergeleitet wird und ob die PQ-Zeit gleich bleibt. Genau damit werden AV-Blöcke unterschieden.</p></div></aside>
    </>)}

    {section("03", "Pathophysiologie bradykarder Rhythmusstörungen", "Zu langsam", <>
      <h3>Vier Wege zur Bradykardie</h3>
      <div className="pulmo-care-grid"><div><span>01</span><b>Impuls entsteht zu langsam</b><small>Sinusbradykardie, Sick-Sinus-Syndrom oder ausgeprägter Vaguseinfluss vermindern die Frequenz des primären Schrittmachers.</small></div><div><span>02</span><b>Impuls verlässt den Sinusknoten nicht</b><small>Beim sinuatrialen Block erreicht ein erzeugter Impuls das Vorhofmyokard verzögert oder gar nicht.</small></div><div><span>03</span><b>AV-Überleitung ist gestört</b><small>Beim AV-Block wird die Erregung vom Vorhof zur Kammer verzögert, teilweise oder vollständig unterbrochen.</small></div><div><span>04</span><b>Ersatzrhythmus ist zu langsam</b><small>Ein junktionales oder ventrikuläres Zentrum übernimmt. Distale Zentren erzeugen häufig langsamere und breitere QRS-Komplexe.</small></div></div>
      <div className="pulmo-path"><span>Frequenz ↓</span><i>→</i><span>HZV = HF × SV ↓</span><i>→</i><span>Organperfusion ↓</span><i>→</i><span>Synkope / Schock</span></div>
      <p>Das Schlagvolumen kann eine langsamere Frequenz zunächst teilweise kompensieren. Reicht dies nicht mehr aus, sinkt das Herzzeitvolumen. Hirn und Koronarien reagieren besonders empfindlich: Schwindel, Synkope, Ischämie, Herzinsuffizienz und im Extremfall Asystolie können folgen.</p>
      <h3>AV-Blöcke sicher unterscheiden</h3>
      <p>Beim AV-Block ist die Überleitung <b>vom Vorhof über den AV-Knoten und das His-Purkinje-System zu den Kammern</b> verzögert oder unterbrochen. Für die Prüfung wird immer die Beziehung zwischen P-Wellen und QRS-Komplexen beschrieben.</p>
      <div className="pulmo-risk-grid"><div><b>AV-Block I</b><p>Jede P-Welle wird übergeleitet, aber die PQ-Zeit ist konstant länger als 200 ms. Es fällt kein QRS aus.</p></div><div><b>AV-Block II · Mobitz I</b><p>Die PQ-Zeit verlängert sich von Schlag zu Schlag, bis eine P-Welle nicht übergeleitet wird und der QRS ausfällt. Danach beginnt die Folge erneut.</p></div><div><b>AV-Block II · Mobitz II</b><p>Die PQ-Zeit der übergeleiteten Schläge bleibt konstant. Plötzlich wird eine P-Welle nicht übergeleitet; ein QRS fällt ohne vorherige PQ-Verlängerung aus.</p></div><div><b>2:1-AV-Block</b><p>Nur jede zweite P-Welle wird übergeleitet. Aus dem kurzen Streifen ist Mobitz I gegen Mobitz II oft nicht sicher unterscheidbar.</p></div><div><b>Höhergradiger AV-Block</b><p>Mindestens zwei aufeinanderfolgende P-Wellen werden nicht übergeleitet, einzelne Vorhoferregungen erreichen die Kammer aber noch.</p></div><div><b>AV-Block III</b><p>Keine Vorhoferregung wird regelhaft übergeleitet. P-Wellen und QRS-Komplexe laufen unabhängig: vollständige AV-Dissoziation.</p></div></div>
      <div className="pulmo-compare"><div><small>Eher proximal / nodal</small><h3>Meist schmaler QRS</h3><p>Ein junktionaler Ersatzrhythmus liegt häufig ungefähr bei 40–60/min. Atropin kann eher wirken; das Risiko muss trotzdem klinisch bewertet werden.</p></div><div><small>Eher distal / infra-Hisär</small><h3>Häufig breiter QRS</h3><p>Ein ventrikulärer Ersatzrhythmus ist oft nur ungefähr 20–40/min. Höheres Asystolierisiko, Atropin häufig unzureichend: Pacing früh vorbereiten.</p></div></div>
      <aside className="diagnostic-boundary"><span>III°</span><div><b>So erkennt man die AV-Dissoziation</b><p>Die P-P-Abstände sind regelmäßig und die R-R-Abstände ebenfalls regelmäßig, aber beide Rhythmen besitzen keine feste Beziehung zueinander. Die Vorhoffrequenz ist meist höher als die Kammerfrequenz.</p></div></aside>
      <Figure src="/lessons/instabile-bradykardie/av-block-vergleich.svg" alt="Lernvergleich der AV-Blöcke ersten, zweiten und dritten Grades" caption="AV-Block-Vergleich" wide />
      <aside className="red-flags"><span>!</span><div><small>Erhöhtes Asystolierisiko</small><h3>Früh an Pacing und Eskalation denken</h3><p>Kürzlich dokumentierte Asystolie, Mobitz-II-Block, kompletter AV-Block mit breitem QRS oder ventrikuläre Pausen über drei Sekunden sprechen für ein höheres Risiko.</p></div></aside>
      <h3>Wichtige Ursachen</h3>
      <p>Ischämie, besonders inferiorer Myokardinfarkt, Hypoxie, Hypothermie, Hyperkaliämie, Azidose, Hypothyreose, Hirndruck, starker Vagusreiz sowie Betablocker-, Calciumantagonisten-, Digitalis- oder Organophosphatwirkung.</p>
    </>)}

    {section("04", "Pathophysiologie tachykarder Rhythmusstörungen", "Zu schnell", <>
      <h3>Wie eine Tachykardie entsteht</h3>
      <div className="pulmo-care-grid"><div><span>01</span><b>Gesteigerte Automatizität</b><small>Schrittmacher- oder Myokardzellen depolarisieren schneller, etwa bei Sympathikusaktivierung, Fieber, Hypovolämie oder Ischämie.</small></div><div><span>02</span><b>Getriggerte Aktivität</b><small>Nachdepolarisationen während oder nach der Repolarisation können zusätzliche Impulse auslösen, beispielsweise bei QT-Verlängerung oder Digitaliswirkung.</small></div><div><span>03</span><b>Reentry</b><small>Unterschiedliche Leitung und Refraktärzeit ermöglichen eine kreisende Erregung, die sich selbst unterhält.</small></div><div><span>04</span><b>Vorhof- oder Kammerchaos</b><small>Viele ungeordnete Wellen führen zu Flimmern; bei Kammerflimmern fehlt eine wirksame Pumpfunktion.</small></div></div>
      <div className="pulmo-path"><span>Frequenz ↑</span><i>→</i><span>Diastole ↓</span><i>→</i><span>Füllung &amp; Koronarfluss ↓</span><i>+</i><span>O₂-Bedarf ↑</span></div>
      <p>Mit zunehmender Frequenz verkürzt sich vor allem die Diastole. Ventrikelfüllung und Schlagvolumen können fallen, während die Koronarperfusion kürzer und der Sauerstoffverbrauch höher wird. Das vorgeschädigte Herz dekompensiert besonders früh: Ischämie, Lungenödem und Schock können entstehen.</p>
      <aside className="diagnostic-boundary"><span>↗</span><div><b>Sinustachykardie ist häufig eine Kompensation</b><p>Bei Hypovolämie, Hypoxie, Fieber, Schmerz oder Schock versucht der Körper, das Herzzeitvolumen zu erhalten. Dann wird vorrangig die Ursache behandelt; eine unkritische Frequenzsenkung kann die Perfusion verschlechtern.</p></div></aside>
      <h3>Supraventrikulär und ventrikulär</h3>
      <div className="pulmo-compare"><div><small>Meist schmal</small><h3>Supraventrikulär</h3><p>Ursprung oberhalb der Kammern, etwa Sinustachykardie, AVNRT, Vorhofflattern oder Vorhofflimmern. Ein aberranter Schenkelblock oder Präexzitation kann den QRS trotzdem verbreitern.</p></div><div><small>Meist breit</small><h3>Ventrikulär</h3><p>Ursprung im ventrikulären Leitungssystem oder Myokard. Monomorphe VT ist oft Reentry um eine Narbe; polymorphe VT zeigt wechselnde QRS-Formen.</p></div></div>
      <aside className="red-flags"><span>VT</span><div><small>Prüfungsfalle</small><h3>Unklare regelmäßige Breitkomplextachykardie</h3><p>Bis zur sicheren Klärung als ventrikuläre Tachykardie betrachten, besonders bei struktureller Herzerkrankung oder früherem Infarkt.</p><b>Ein vorhandener Puls schließt eine VT nicht aus.</b></div></aside>
      <h3>Vier-Felder-Einordnung einer Tachykardie</h3>
      <div className="pulmo-risk-grid"><div><b>Schmal + regelmäßig</b><p>Sinustachykardie, AVNRT oder Vorhofflattern mit fester Überleitung.</p></div><div><b>Schmal + unregelmäßig</b><p>Vorhofflimmern, Vorhofflattern mit wechselnder Überleitung oder multifokale atriale Tachykardie.</p></div><div><b>Breit + regelmäßig</b><p>VT bis zum Beweis des Gegenteils; möglich sind auch SVT mit Schenkelblock oder Präexzitation.</p></div><div><b>Breit + unregelmäßig</b><p>Polymorphe VT oder Vorhofflimmern mit Schenkelblock beziehungsweise Präexzitation; besonders gefährliche Konstellation.</p></div></div>
      <div className="pulmo-risk-grid"><div><b>Monomorphe VT</b><p>QRS-Form bleibt weitgehend gleich; oft stabiler Reentry-Kreis bei Infarktnarbe oder struktureller Herzerkrankung.</p></div><div><b>Polymorphe VT</b><p>QRS-Form und Achse wechseln. Torsade de pointes ist eine Sonderform im Zusammenhang mit verlängerter QT-Zeit.</p></div><div><b>Kammerflattern</b><p>Sehr schnelle, breitkomplexe und kaum abgrenzbare Kammeraktivität; kann in Kammerflimmern übergehen.</p></div><div><b>Kammerflimmern</b><p>Ungeordnete elektrische Aktivität ohne wirksamen Auswurf: defibrillierbarer Kreislaufstillstand.</p></div></div>
      <h3>Extrasystolen richtig benennen</h3>
      <div className="pulmo-anatomy-grid"><div><small>Bigeminus</small><b>Jeder zweite Schlag</b><p>Regelmäßiger Wechsel aus Normalschlag und Extrasystole.</p></div><div><small>Trigeminus</small><b>Jeder dritte Schlag</b><p>Auf zwei Normalschläge folgt regelmäßig eine Extrasystole.</p></div><div><small>Couplet / Triplet</small><b>Zwei / drei Extrasystolen</b><p>Direkt aufeinanderfolgende Extrasystolen; Kontext, Ursprung und Klinik entscheiden über die Bedeutung.</p></div></div>
    </>)}

    {section("05", "Symptome und EKG-Entscheidung", "Was stützt die Arbeitsdiagnose?", <>
      <div className="pulmo-symptoms">{["Palpitationen oder Herzstolpern", "Thoraxdruck oder Myokardischämie", "Dyspnoe oder Lungenödem", "Schwindel, Präsynkope oder Synkope", "Schwäche, Unruhe oder Verwirrtheit", "Hypotonie oder Schock", "Unregelmäßiger oder sehr langsamer Puls", "Herz-Kreislauf-Stillstand"].map(x => <span key={x}>{x}</span>)}</div>
      <p>Rhythmusstörungen können auch asymptomatisch sein. Die Arbeitsdiagnose entsteht aus <b>klinischer Wirkung, Pulsbefund, Monitoring und 12-Kanal-EKG</b>. Ein Monitorstreifen allein reicht nicht.</p>
      <div className="pulmo-care-grid"><div><span>1</span><b>Puls?</b><small>Kein sicherer Kreislauf: Reanimationsalgorithmus.</small></div><div><span>2</span><b>Stabil?</b><small>Schock, Synkope, Ischämie oder akute Herzinsuffizienz?</small></div><div><span>3</span><b>Regelmäßig?</b><small>R-R-Abstände und P-Wellen systematisch prüfen.</small></div><div><span>4</span><b>QRS breit?</b><small>Über oder unter 120 ms und Vor-EKG vergleichen.</small></div></div>
      <div className="pulmo-compare"><div><small>Klinisch instabil</small><h3>Vier Warnzeichen</h3><p>Schock, Synkope oder schwere Bewusstseinsstörung, Myokardischämie sowie akute Herzinsuffizienz beziehungsweise Lungenödem.</p></div><div><small>EKG mit Kontext</small><h3>Nicht nur den Monitor behandeln</h3><p>Rhythmus, Puls, Blutdruck, Haut, Vigilanz und Beschwerden müssen zeitlich zusammenpassen.</p></div></div>
      <aside className="diagnostic-boundary"><span>!</span><div><b>Artefakt ausschließen</b><p>Patient ansehen, Puls tasten, Elektroden prüfen, mehrere Ableitungen und die SpO₂-Pulswelle vergleichen. Eine scheinbare VT bei ruhigem Patienten mit regelmäßigem 78er-Puls ist bis zur Klärung ein technisches Problem.</p></div></aside>
    </>)}

    {section("06", "Komplikationen und Gefahren", "Warum ist das zeitkritisch?", <>
      <div className="pulmo-risk-grid"><div><b>Zerebrale Minderperfusion</b><p>Schwindel, Synkope, Krampfanfallähnliche Bewegungen und sekundäres Trauma.</p></div><div><b>Myokardischämie</b><p>Ungünstiges Verhältnis aus Koronarangebot und Sauerstoffbedarf; mögliche Infarktauslösung oder -verschlechterung.</p></div><div><b>Akute Herzinsuffizienz</b><p>Reduziertes Schlagvolumen und Füllungsdruckanstieg können ein Lungenödem auslösen.</p></div><div><b>Schock</b><p>Unzureichendes Herzzeitvolumen verursacht kalte Haut, Vigilanzabfall, Hypotonie und Organversagen.</p></div><div><b>Thromboembolie</b><p>Besonders bei Vorhofflimmern können Vorhofthromben entstehen und systemisch embolisieren.</p></div><div><b>Kreislaufstillstand</b><p>VT kann pulslos werden; Kammerflimmern und Asystolie benötigen sofortige Reanimation.</p></div></div>
    </>)}

    {section("07", "Einsatzmaterialien", "Was nehmen Sie mit?", <div className="material-chips">{["Notfallrucksack", "Monitoring und 12-Kanal-EKG", "Defibrillator mit Sync- und Pacing-Funktion", "Klebeelektroden", "Sauerstoff und Beatmungsgerät", "Absaugung", "i.v./i.o.-Material", "Atropin, Epinephrin, Amiodaron nach VFA", "Trage oder Tragestuhl", "Reanimationsmaterial"].map(x => <span key={x}>{x}</span>)}</div>)}

    {section("08", "Erstmaßnahmen und Anamnese", "cABCDE und SAMPLERS", <>
      <div className="pulmo-care-grid"><div><span>01</span><b>cABCDE</b><small>Bewusstsein, Atmung, Haut, Pulse und Perfusion beurteilen; Kreislaufstillstand sofort erkennen.</small></div><div><span>02</span><b>Monitoring</b><small>SpO₂, Blutdruck, EKG und 12-Kanal-EKG; Verlauf statt Einzelwert.</small></div><div><span>03</span><b>Vorbereiten</b><small>Defibrillationselektroden, i.v.-Zugang, Reanimationsbereitschaft und bei Instabilität früh Notarzt.</small></div><div><span>04</span><b>Ursache behandeln</b><small>Hypoxie, Hypovolämie, Temperatur, Glukose, Ischämie, Elektrolyte und Intoxikation mitdenken.</small></div><div><span>05</span><b>Verlauf sichern</b><small>12-Kanal-EKG möglichst vor und nach einer Rhythmusänderung schreiben, ohne eine dringliche Therapie zu verzögern.</small></div><div><span>06</span><b>Übergabe</b><small>Beginn, Rhythmus, Instabilitätszeichen, Maßnahmen, Energien, Medikamente und Reaktion strukturiert übergeben.</small></div></div>
      <h3>SAMPLERS gezielt</h3>
      <div className="samplers-grid">{[["S · Symptome", "Beginn, Palpitation, Synkope, Dyspnoe, Thoraxschmerz"],["A · Allergien", "Medikamentenunverträglichkeiten"],["M · Medikamente", "Betablocker, Calciumantagonisten, Digitalis, Antiarrhythmika, Antikoagulation"],["P · Vorgeschichte", "KHK, Infarkt, Herzinsuffizienz, bekannte Rhythmusstörung, Schrittmacher"],["L · Letzte Aufnahme", "Flüssigkeit, Alkohol, Stimulanzien"],["E · Ereignis", "Plötzlicher Beginn, Belastung, Infekt, Schmerz, Intoxikation"],["R · Risiken", "Elektrolytverlust, Endokrinologie, Drogen, familiärer Herztod"],["S · Sonstiges", "Vor-EKG, letzte normale Frequenz, Verlauf" ]].map(([a,b]) => <p key={a}><b>{a}</b>{b}</p>)}</div>
      <p>Sauerstoff wird nach Oxygenierung und gültiger Vorgabe eingesetzt. Eine kardiale Oberkörperhochlagerung passt bei Dyspnoe und ausreichendem Blutdruck; bei Schockzeichen wird die Lagerung an Kreislauf und Atmung angepasst.</p>
    </>)}

    {section("09", "Differenzialdiagnosen und Entscheidung", "Präklinische Einordnung", <>
      <div className="differential-grid">{["ACS oder Myokardinfarkt", "Lungenarterienembolie", "Hypoxie oder respiratorische Ursache", "Hypovolämie, Fieber oder Schmerz", "Kalium-/Magnesiumstörung", "Hypo- oder Hyperthyreose", "Medikamenten- oder Drogenwirkung", "Hypothermie", "Schrittmacherfehlfunktion", "Bewegungs- oder Elektrodenartefakt"].map(x => <span key={x}>{x}</span>)}</div>
      <div className="pulmo-compare"><div><small>Stabil</small><h3>Rhythmus sichern und Ursache suchen</h3><p>12-Kanal-EKG, Verlaufskontrolle, fokussierte Anamnese und zielgerichteter Transport. Stabil bedeutet nicht harmlos.</p></div><div><small>Instabil</small><h3>Rhythmus verursacht Minderperfusion</h3><p>Schock, Synkope, Ischämie oder akute Herzinsuffizienz: passenden VFA-Pfad unverzüglich vorbereiten und Reanimationsbereitschaft herstellen.</p></div></div>
      <aside className="diagnostic-boundary"><span>0?</span><div><b>Pulslose VT ist kein Kardioversionsfall</b><p>Fehlt der Kreislauf, gelten Reanimation und unsynchronisierte Defibrillation. Der Algorithmus für instabile Tachykardie setzt einen vorhandenen Puls voraus.</p></div></aside>
    </>)}

    {section("10", "VFA Bradykardie und Tachykardie", "Thüringen 2026/2027", <>
      <h3>Instabile Bradykardie</h3>
      <div className="pulmo-vfa-flow"><div><span>1</span><b>Atropin</b><small>Initial 1 mg i.v.; Erfolg nach zwei Minuten prüfen. Bei nachlassendem Effekt 0,5 mg bis maximal 3 mg.</small></div><div><span>2</span><b>Epinephrin</b><small>Nach VFA als Übergangsinfusion beziehungsweise Perfusor, sobald verfügbar.</small></div><div><span>3</span><b>Pacing</b><small>DEMAND, 70/min, ab 70 mA in 5-mA-Schritten bis zur 1:1-Ankopplung.</small></div><div><span>4</span><b>Capture</b><small>QRS nach Spike und synchronen zentralen sowie peripheren Puls prüfen.</small></div></div>
      <Vfa src="/lessons/instabile-bradykardie/vfa-19-bradykardie.png" alt="Thüringer VFA zur instabilen Bradykardie und transthorakalen Schrittmachertherapie" caption="VFA 19 · Instabile Bradykardie" wide />
      <Figure src="/lessons/instabile-bradykardie/b2a-atropin-epinephrin.png" alt="Anlage B2A mit Atropin und Epinephrin für die instabile Bradykardie" caption="Anlage B2A · Atropin und Epinephrin" wide />
      <h3>Instabile Tachykardie mit Puls</h3>
      <div className="pulmo-vfa-flow"><div><span>1</span><b>Synchronisieren</b><small>R-Zacken-Markierung kontrollieren und Defibrillationselektroden anlegen.</small></div><div><span>2</span><b>Kardiovertieren</b><small>Biphasisch 120 J, 150 J und 200 J nach VFA; nach jedem Versuch sofort neu beurteilen.</small></div><div><span>3</span><b>Amiodaron</b><small>Bei Misserfolg einmalig 300 mg als Kurzinfusion nach VFA und B2A.</small></div><div><span>4</span><b>Erneut prüfen</b><small>Anschließend gegebenenfalls einmalige Wiederholung mit 200 J; cABCDE und Puls kontrollieren.</small></div></div>
      <aside className="diagnostic-boundary"><span>SYNC</span><div><b>Vor jedem Schock erneut kontrollieren</b><p>Der Synchronisationsmodus und die R-Zacken-Markierungen müssen vor jeder Kardioversion sichtbar geprüft werden. Nach einer Schockabgabe können Geräte den Sync-Modus zurücksetzen.</p></div></aside>
      <Vfa src="/lessons/vorhofflimmern/vfa-20.png" alt="Thüringer VFA zur instabilen Tachykardie und Notfallkardioversion" caption="VFA 20 · Instabile Tachykardie / Notfallkardioversion" wide />
      <Figure src="/lessons/vorhofflimmern/b2a-amiodaron.png" alt="Anlage B2A zur Zubereitung von Amiodaron als Kurzinfusion" caption="Anlage B2A · Amiodaron" wide />
      <div className="pulmo-risk-grid"><div><b>Atropin</b><p>Parasympatholytisch: muskarinische Rezeptorblockade steigert Sinusknotenfrequenz und AV-Überleitung; bei distalem Block möglicherweise unwirksam.</p></div><div><b>Epinephrin</b><p>β₁ steigert Frequenz und Kontraktilität, α₁ stützt den Gefäßtonus. Risiken: Ischämie, Hypertonie und weitere Arrhythmien.</p></div><div><b>Amiodaron</b><p>Vor allem Kaliumkanalblockade mit verlängerter Repolarisation und Refraktärzeit; zusätzlich Natrium-, Calciumkanal- und β-Effekte.</p></div><div><b>Amiodaron · Risiken</b><p>Hypotonie, Bradykardie, QT-Verlängerung und proarrhythmische Wirkung; kontinuierliches Monitoring.</p></div></div>
      <aside className="red-flags"><span>⚡</span><div><small>Sicherheitsgrenze</small><h3>Polymorphe VT und fehlende Synchronisation</h3><p>Ist keine zuverlässige R-Zacken-Synchronisation möglich oder fehlt der Puls, gilt nicht der gewöhnliche synchronisierte Kardioversionspfad. Dann nach Reanimations- beziehungsweise Defibrillationsalgorithmus handeln.</p></div></aside>
    </>)}

    {children}
    <p className="lesson-source">Grundlagen: bereitgestellte Unterlagen „46. Herzrhythmusstörungen“, bestehende Anatomie- und EKG-Abbildungen sowie Thüringer Verfahrensanweisungen 2026/27, VFA 19 und VFA 20 mit Anlage B2A. Zur fachlichen Einordnung ergänzend: European Resuscitation Council Guidelines 2025 und ESC-Leitlinien zu supraventrikulären und ventrikulären Arrhythmien. Maßgeblich für Maßnahmen und Dosierungen sind die Thüringer VFA.</p>
  </article>;
}
