import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

function VesselComparison() {
  return <div className="htn-vessels" aria-label="Schematischer Vergleich von Arterie und Vene">
    <figure><svg viewBox="0 0 320 205" role="img" aria-label="Arterie mit kleinerem rundem Lumen und kräftiger Muskelschicht"><circle cx="160" cy="102" r="87" fill="#e7a5a0" stroke="#a34a4b" strokeWidth="3"/><circle cx="160" cy="102" r="58" fill="#cf6263" stroke="#9f4446" strokeWidth="2"/><circle cx="160" cy="102" r="31" fill="#fff5ef" stroke="#ad5752" strokeWidth="3"/><path d="M160 58v19m-9-10 9 10 9-10" fill="none" stroke="#9a4a45" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg><figcaption><b>Arterie · Hochdrucksystem</b><span>Kräftige Media, kleineres rundes Lumen. Herzschlag und elastischer Rückstoß treiben das Blut vorwärts.</span></figcaption></figure>
    <figure><svg viewBox="0 0 320 205" role="img" aria-label="Vene mit weiterem Lumen, dünnerer Muskelschicht und zwei Venenklappen"><ellipse cx="160" cy="102" rx="108" ry="82" fill="#a9c9dd" stroke="#4b7898" strokeWidth="3"/><ellipse cx="160" cy="102" rx="91" ry="68" fill="#d7eafa" stroke="#598cad" strokeWidth="2"/><path d="M160 42v22m-9-9 9 9 9-9" fill="none" stroke="#3f7598" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/><path d="M95 91q32 5 50 35M225 91q-32 5-50 35" fill="none" stroke="#407ba0" strokeWidth="5" strokeLinecap="round"/></svg><figcaption><b>Vene · Niederdrucksystem</b><span>Dünnere Media, weites Lumen. Klappen verhindern besonders in den Gliedmaßen den Rückfluss.</span></figcaption></figure>
  </div>;
}

function UrapidilSyringe() {
  return <div className="htn-syringe">
    <div className="htn-syringe-title"><div><small>Anlage B2A · VFA 16</small><h3>Urapidil in der Spritze</h3></div><b>unverdünnt</b></div>
    <div className="htn-syringe-facts"><div><small>Ampulle</small><b>25 mg in 5 ml</b></div><div><small>Konzentration</small><b>5 mg/ml</b></div><div><small>Eine VFA-Gabe</small><b>10 mg = 2 ml</b></div><div><small>NaCl 0,9 %</small><b>0 ml</b></div></div>
    <div className="htn-syringe-drawing" role="img" aria-label="Schematische Fünf-Milliliter-Spritze: zwei Milliliter Urapidil, entsprechend zehn Milligramm, ohne NaCl">
      <svg viewBox="0 0 650 175" xmlns="http://www.w3.org/2000/svg">
        <path d="M35 70H78V108H35Z" fill="#d8e7e8" stroke="#8ca6a9" strokeWidth="2"/><path d="M31 66V112M78 58V120" stroke="#657b83" strokeWidth="4"/>
        <rect x="88" y="58" width="470" height="55" rx="8" fill="#fbffff" stroke="#9ab2b7" strokeWidth="3"/>
        <rect x="90" y="61" width="185" height="49" fill="#3d9d90"/>
        <path d="M276 55V117" stroke="#214950" strokeWidth="6"/><path d="M276 85H605M605 65V107" stroke="#8b9da1" strokeWidth="5"/>
        {Array.from({ length: 11 }, (_, i) => <g key={i}><path d={`M${88 + i * 47} 58V${i % 2 === 0 ? 78 : 69}`} stroke="#244a54" strokeWidth={i % 2 === 0 ? 2 : 1.5}/>{i % 2 === 0 && <text x={88 + i * 47} y="43" textAnchor="middle" fontSize="15" fontWeight="700" fill="#244a54">{i / 2}</text>}</g>)}
        <text x="557" y="145" textAnchor="end" fontSize="14" fontWeight="700" fill="#496a70">5-ml-Skala · Kolben bei 2 ml</text>
      </svg>
    </div>
    <p><b>Rechnung:</b> 10 mg ÷ 5 mg/ml = <b>2 ml</b>. Nach VFA 16 langsam i.v.; nach 5 Minuten RR kontrollieren. Bei fehlendem Erfolg sind höchstens zwei weitere Gaben von jeweils 10 mg vorgesehen – <b>maximal 30 mg insgesamt</b>. Die Grafik zeigt eine einzelne Gabe, keine Mischung und keine gleichzeitige Gabe aller drei Dosen.</p>
    <small className="htn-syringe-caution">Schematische Lernansicht. Ampulle, Konzentration, Indikation, Wirkung und aktuelle Original-VFA vor jeder Anwendung prüfen.</small>
  </div>;
}

export default function HypertensiverNotfallLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>Hypertensiver Notfall · Herz &amp; Kreislauf</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;
  return <article className="lesson-article rippenfraktur-lesson hypertensiver-notfall-lesson">
    <div className="lesson-intro"><p className="lead">Nicht nur die Höhe des Blutdrucks entscheidet: Entscheidend sind Beschwerden und Hinweise auf eine akute Schädigung von Gehirn, Herz, Lunge, Aorta oder Niere. Für die präklinische Medikation gelten die Thüringer VFA 16 und 17.</p></div>

    {section("01", "Definition", <><p>Beim <b>hypertensiven Notfall</b> steigt der Blutdruck innerhalb kurzer Zeit stark an, nach der Unterlage meist auf <b>über 180 mmHg systolisch oder über 110 mmHg diastolisch</b>. Gleichzeitig bestehen klinische Beschwerden und es kann zu einer akuten, teils lebensbedrohlichen Organschädigung kommen.</p><div className="pulmo-compare"><div><small>Hoher Wert allein</small><h3>Noch keine sichere Notfalldiagnose</h3><p>Ein einzelner hoher Messwert beweist keinen akuten Organschaden. Messung, Symptome und Verlauf müssen zusammen beurteilt werden.</p></div><div><small>Hoher Wert plus Zeichen</small><h3>Zeitkritisch abklären</h3><p>Neurologische Ausfälle, Bewusstseinsstörung, Thoraxschmerz oder Dyspnoe können auf akute Organbeteiligung hinweisen.</p></div></div><p><b>VFA-Entscheidungsgrenze:</b> RR<sub>sys</sub> &gt; 180 mmHg <b>oder</b> RR<sub>dia</sub> &gt; 110 mmHg <b>und</b> klinische Beschwerden (Red Flags, Epistaxis). Das ist die Einsatzgrenze der VFA 16/17; sie ersetzt nicht die Einordnung eines Organschadens.</p></>)}

    {section("02", "Anatomie und Physiologie", <>
      <p>Das Herz liegt hinter dem Brustbein, überwiegend im linken Thorax. Es pumpt Blut in das arterielle Hochdrucksystem; die Venen führen es über das Niederdrucksystem zurück. Die Gefäßwand besteht von innen nach außen aus Endothel (Tunica interna), Muskelschicht (Tunica media) und äußerer Bindegewebsschicht (Tunica externa).</p>
      <h3>Arterie und Vene im Querschnitt</h3>
      <VesselComparison />
      <div className="pulmo-anatomy-grid"><div><small>Herznah</small><b>Elastische Arterien</b><p>Die Aorta dehnt sich in der Systole und gibt in der Diastole gespeicherte Energie ab. So fließt Blut auch zwischen zwei Herzschlägen weiter (Windkessel).</p></div><div><small>Herzfern</small><b>Muskuläre Arterien</b><p>Ihre glatte Muskulatur verändert den Gefäßdurchmesser und verteilt den Blutstrom auf die Organe.</p></div><div><small>Vor Kapillaren</small><b>Arteriolen</b><p>Sie sind die wichtigsten veränderlichen Widerstandsgefäße: Engstellung erhöht, Weitstellung senkt den Widerstand.</p></div></div>
      <h3>Herzzeitvolumen, Widerstand und Druck – was hängt wie zusammen?</h3>
      <div className="htn-hemodynamics"><div><small>01 · Pumpleistung</small><b>Herzzeitvolumen (HZV)</b><p>Die Blutmenge, die das Herz in einer Minute auswirft: <strong>Herzfrequenz × Schlagvolumen</strong>. Beispiel: 70 Schläge/min × 70 ml/Schlag = 4,9 l/min. Das ist ein Rechenbeispiel, kein Zielwert.</p></div><div><small>02 · Strombremse</small><b>Peripherer Widerstand</b><p>Der Widerstand, gegen den das Blut im Körperkreislauf fließt. Vor allem der Durchmesser der Arteriolen verändert ihn: ein engeres Lumen erschwert den Durchfluss. Auch Blutviskosität und Gefäßlänge beeinflussen ihn.</p></div><div><small>03 · Druckniveau</small><b>Mittlerer arterieller Druck</b><p>Das über den Herzzyklus gemittelte Druckniveau. Näherungsweise gilt: <strong>MAP ≈ HZV × systemischer Gefäßwiderstand</strong>; der kleine zentrale Venendruck wird hier vernachlässigt.</p></div></div>
      <div className="pulmo-path"><span>Herzfrequenz × Schlagvolumen = HZV</span><i>×</i><span>Widerstand der Körpergefäße</span><i>≈</i><span>Mittlerer arterieller Druck</span></div>
      <p><b>Warum?</b> Um dieselbe Blutmenge pro Minute durch enger gestellte Gefäße zu bewegen, muss das Herz einen höheren Druckunterschied erzeugen. Steigt bei ungefähr gleichem HZV der systemische Widerstand, steigt daher meist der mittlere arterielle Druck. Umgekehrt kann auch ein höheres HZV den Druck anheben. Diese Beziehung beschreibt <em>nicht</em> direkt den systolischen oder diastolischen Einzelwert der Manschettenmessung; Pulsdruck, Gefäßelastizität und Herzzyklus beeinflussen beide Werte zusätzlich.</p>
      <aside className="diagnostic-boundary"><span>↔</span><div><b>Druck ist nicht gleich Durchblutung</b><p>Blutfluss entsteht durch einen Druckunterschied und wird vom Widerstand gebremst: <b>Fluss = Druckgefälle ÷ Widerstand</b>. Eine Arteriolenverengung kann den allgemeinen Druck erhöhen, während der lokale Blutfluss hinter der Engstelle abnimmt.</p></div></aside>
      <h3>Wie gelangt das Blut vorwärts und wieder zurück?</h3>
      <div className="htn-transport"><div><small>Hinweg · Arterien</small><b>Herz → Aorta → Arteriolen → Kapillaren</b><ul><li><strong>Herz:</strong> Der linke Ventrikel erzeugt den Druck.</li><li><strong>Windkessel:</strong> Die elastische Aorta hält den Fluss zwischen den Herzschlägen aufrecht.</li><li><strong>Verteilung:</strong> Muskuläre Arterien leiten Blut zu den Organen.</li><li><strong>Feinsteuerung:</strong> Arteriolen dosieren den Zufluss; in Kapillaren findet der Stoffaustausch statt.</li></ul></div><div><small>Rückweg · Venen</small><b>Venolen → Venen → rechtes Herz</b><ul><li><strong>Druckgefälle:</strong> Blut fließt zum rechten Vorhof zurück.</li><li><strong>Muskelpumpe:</strong> Skelettmuskeln drücken Venen zusammen.</li><li><strong>Venenklappen:</strong> Sie verhindern besonders in den Gliedmaßen den Rückstrom.</li><li><strong>Atempumpe:</strong> Druckänderungen in Brust- und Bauchraum fördern den Rückstrom.</li><li><strong>Zusätzlich:</strong> Benachbarte Arterienpulsationen können helfen; Perforansvenen verbinden oberflächliche und tiefe Beinvenen.</li></ul></div></div>
      <p>Ein sehr hoher Druck kann Endothel und Mikrozirkulation schädigen. Gleichzeitig brauchen besonders Gehirn, Herz und Niere eine ausreichende Durchblutung. Deshalb ist eine abrupte, unkontrollierte Blutdrucksenkung gefährlich.</p>
      <h3>Wie reguliert der Körper den Druck?</h3>
      <div className="htn-regulation-grid">
        <div><small>Sekunden bis Minuten</small><b>Kurzfristig · Baroreflex</b><ul><li><strong>Sensoren:</strong> Karotissinus und Aortenbogen messen die Gefäßwanddehnung.</li><li><strong>Schaltstelle:</strong> Signale erreichen den Hirnstamm.</li><li><strong>Antwort:</strong> Sympathikus und Parasympathikus verändern Herzfrequenz, Kontraktionskraft und Gefäßweite.</li></ul></div>
        <div><small>Minuten bis Stunden</small><b>Mittelfristig · Hormone und Flüssigkeit</b><ul><li><strong>Angiotensin II:</strong> RAAS-bedingte Gefäßverengung kann den Widerstand erhöhen.</li><li><strong>ADH:</strong> Fördert die Rückhaltung von Wasser.</li><li><strong>Kapillaren:</strong> Flüssigkeit kann sich zwischen Blutbahn und Gewebe verschieben.</li></ul></div>
        <div><small>Stunden bis Tage und länger</small><b>Langfristig · Niere und Blutvolumen</b><ul><li><strong>Niere:</strong> Steuert, wie viel Natrium und Wasser ausgeschieden wird.</li><li><strong>Aldosteron:</strong> Fördert Natriumrückresorption; Wasser folgt.</li><li><strong>Ergebnis:</strong> Das zirkulierende Volumen prägt das längerfristige Druckniveau.</li></ul></div>
      </div>
      <h3>Was bewirkt der Baroreflex an den Gefäßen?</h3>
      <div className="htn-autonomic-grid"><div><small>Bei Druckabfall</small><b>Mehr Sympathikus</b><ul><li><strong>Herz:</strong> Frequenz und Kontraktionskraft steigen.</li><li><strong>Arteriolen:</strong> In vielen Gefäßgebieten Engstellung → Widerstand steigt.</li><li><strong>Nachgeschaltetes Kapillarbett:</strong> Durch die Engstellung kann dort weniger Blut ankommen.</li><li><strong>Venen:</strong> Engstellung verkleinert den Blutspeicher → venöser Rückstrom und Vorlast steigen.</li></ul></div><div><small>Bei Druckanstieg</small><b>Mehr Vagus · weniger Sympathikus</b><ul><li><strong>Herz:</strong> Der Parasympathikus senkt vor allem die Frequenz.</li><li><strong>Arteriolen:</strong> Weniger sympathischer Tonus → häufig Weitstellung und geringerer Widerstand.</li><li><strong>Nachgeschaltetes Kapillarbett:</strong> Der Widerstand vor ihm sinkt; der tatsächliche Blutfluss hängt auch vom Druck und der lokalen Autoregulation ab.</li><li><strong>Venen:</strong> Weniger sympathischer Tonus → größere Speicherkapazität, tendenziell weniger Rückstrom.</li></ul></div></div>
      <p className="htn-regulation-note"><b>Prüfungsfalle:</b> Die meisten Körpergefäße werden nicht direkt parasympathisch innerviert. Ihre Weitstellung im Baroreflex entsteht überwiegend durch nachlassenden Sympathikustonus; einzelne Gefäßgebiete sind Ausnahmen.</p>
      <p className="htn-regulation-note">Die Zeitfenster sind eine Lernhilfe, keine scharfen Grenzen: Das RAAS wirkt über Angiotensin II auch früher und über Aldosteron und Volumen längerfristig.</p>
      <div className="pulmo-path"><span>Renin</span><i>→</i><span>Angiotensin I</span><i>ACE →</i><span>Angiotensin II</span><i>→</i><span>Gefäßengstellung + Aldosteron</span></div>
      <p>Sinkende Nierendurchblutung, weniger NaCl am distalen Tubulus oder Sympathikusaktivierung fördern die Reninfreisetzung. Angiotensin II verengt Gefäße und stimuliert die Freisetzung von Aldosteron aus der Nebennierenrinde. Aldosteron fördert die Rückresorption von Natrium und damit Wasser. Diese Mechanismen stützen Blutvolumen und Druck; sie sind kein alleiniger Auslöser jedes hypertensiven Notfalls.</p>
    </>)}

    {section("03", "Pathophysiologie und Ursachen", <><h3>Vom erhöhten Widerstand zum Organschaden</h3><div className="pulmo-care-grid"><div><span>01</span><b>Druck steigt</b><small>Vasokonstriktion, erhöhtes Herzzeitvolumen oder Volumenbelastung können den arteriellen Druck steigern.</small></div><div><span>02</span><b>Autoregulation versagt</b><small>Bei einem raschen starken Anstieg können Schutzmechanismen der Organmikrozirkulation überfordert werden.</small></div><div><span>03</span><b>Endothel leidet</b><small>Gefäßschaden und gestörter Flüssigkeitsaustausch fördern Ödeme und weitere Durchblutungsstörungen.</small></div><div><span>04</span><b>Organe reagieren</b><small>Gehirn, Herz, Lunge, Aorta und Niere zeigen je nach betroffenem Gebiet unterschiedliche Warnzeichen.</small></div></div><div className="pulmo-compare"><div><small>Häufiger Hintergrund</small><h3>Bekannte Hypertonie</h3><p>Unterbrochene oder unzureichende antihypertensive Therapie, Nierenerkrankung oder Volumenbelastung können beitragen.</p></div><div><small>Weitere Auslöser</small><h3>Akute Belastung</h3><p>Schmerz, Stress, sympathomimetische Substanzen, Schwangerschaftskomplikationen oder selten ein Phäochromozytom gehören in die Anamnese und Differenzialdiagnose.</p></div></div><aside className="diagnostic-boundary"><span>!</span><div><b>Warum nicht „auf Normalwert“ senken?</b><p>Bei länger bestehender Hypertonie kann die Autoregulation der Organe auf höhere Drücke eingestellt sein. Ein zu rascher Abfall kann die Perfusion von Gehirn, Herz und Niere gefährden. Die VFA 16 beurteilt den Erfolg an einer <b>Senkung des systolischen Ausgangswerts um 25 %</b>, nicht an einem sofortigen Normalwert; besondere Organbilder haben eigene Pfade.</p></div></aside></>)}

    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", <><div className="pulmo-symptoms">{["Starke Kopfschmerzen", "Übelkeit und Erbrechen", "Sehstörung", "Vigilanzminderung", "Fokal-neurologisches Defizit", "Thoraxschmerz", "Dyspnoe", "Epistaxis"].map(x => <span key={x}>{x}</span>)}</div><p>Bei RR<sub>sys</sub> &gt; 180 oder RR<sub>dia</sub> &gt; 110 mmHg werden diese Beschwerden zu Warnsignalen. Kopfschmerz oder ein gerötetes Gesicht allein beweisen jedoch noch keine akute Organschädigung. Beschwerden, cABCDE, Messqualität und Verlauf zusammenführen.</p><aside className="red-flags"><span>!</span><div><small>Red Flags nach VFA 16/17</small><h3>Organbeteiligung aktiv suchen</h3><p>Vigilanzänderung, neurologisches Defizit, akuter Thoraxschmerz oder Dyspnoe verlangen eine sofortige Prüfung des spezifischen Notfallbildes – auch wenn bereits „Hypertonie“ bekannt ist.</p></div></aside></>)}

    {section("05", "Komplikationen und Gefahren", <><div className="pulmo-risk-grid"><div><b>Gehirn</b><p>Hypertensive Enzephalopathie, Krampfanfall oder intrazerebrale Blutung; ein Schlaganfall kann zugleich Ursache oder Folge der Druckentgleisung sein.</p></div><div><b>Herz und Lunge</b><p>Akutes Koronarsyndrom oder akute Linksherzinsuffizienz mit Lungenödem.</p></div><div><b>Aorta</b><p>Aortendissektion bei plötzlichem, starkem Thorax- oder Rückenschmerz bedenken; Blutdruck an beiden Armen vergleichen, ohne Transport zu verzögern.</p></div><div><b>Niere</b><p>Akute Nierenschädigung kann sich durch verminderte Urinausscheidung zeigen; präklinisch ist der Befund häufig nicht sicher zuzuordnen.</p></div></div></>)}

    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", <div className="material-chips">{["Notfallrucksack", "Manuelle RR-Messung", "Monitoring / 12-Kanal-EKG", "SpO₂", "i.v.-Zugang", "Urapidil nach VFA", "Nifedipin nach VFA", "O₂ / Beatmung", "Absaugung", "Dokumentation"].map(x => <span key={x}>{x}</span>)}</div>)}

    {section("07", "Erstmaßnahmen und Anamnese", <><div className="pulmo-care-grid"><div><span>01</span><b>cABCDE</b><small>Bewusstsein, Atmung, Perfusion und akute Gefahren priorisieren.</small></div><div><span>02</span><b>RR prüfen</b><small>Passende Manschette, bei Verdacht auf Aortenproblem an beiden Armen; Verlauf dokumentieren.</small></div><div><span>03</span><b>Organe prüfen</b><small>Neurologie, Thoraxschmerz, Lungenbefund, 12-Kanal-EKG und SpO₂.</small></div><div><span>04</span><b>Unterstützen</b><small>Patient beruhigen, passend lagern, Notarzt und Zielklinik nach Lage einbeziehen.</small></div></div><h3>SAMPLERS · kurz und gezielt</h3><div className="samplers-grid">{[["S · Symptome","Beginn, Kopfschmerz, Neurologie, Schmerz, Atemnot"],["A · Allergien","Vor allem vor einer Medikamentengabe"],["M · Medikamente","Antihypertensiva, letzte Einnahme, Wechselwirkungen"],["P · Vorgeschichte","Hypertonie, KHK, Schlaganfall, Nierenleiden"],["L · Letzte Aufnahme","Nahrung, Alkohol, Drogen"],["E · Ereignis","Akuter Beginn, Belastung, Therapiepause"],["R · Risiken","ACS, Aortendissektion, Schwangerschaft"],["S · Sonstiges","Vorwerte, Verlauf, Angehörige"]].map(([a,b]) => <p key={a}><b>{a}</b>{b}</p>)}</div></>)}

    {section("08", "Differenzialdiagnosen und Entscheidung", <><div className="pulmo-compare"><div><small>Thoraxschmerz / Atemnot</small><h3>ACS oder Lungenödem?</h3><p>12-Kanal-EKG und Atmung beurteilen. Bei entsprechendem Befund führen VFA 16/17 zuerst in die spezifischen ACS- oder Lungenödem-Pfade.</p></div><div><small>Neurologische Auffälligkeit</small><h3>Schlaganfall oder Blutung?</h3><p>Neurologische Defizite, Bewusstsein und Beginn sichern. Bei Schlaganfallverdacht gilt VFA 44 mit eigenem Blutdruckpfad – nicht schematisch die 25-%-Regel aus VFA 16 anwenden.</p></div></div><div className="differential-grid">{["Aortendissektion", "Hypertensive Enzephalopathie", "Intrazerebrale Blutung", "Präeklampsie / Eklampsie", "Akute Nierenschädigung", "Schmerz oder Angst als Mitursache", "Sympathomimetika / Intoxikation", "Phäochromozytom"].map(x => <span key={x}>{x}</span>)}</div><p><b>Merksatz:</b> Akuter Organschaden und dominierendes Leitsymptom bestimmen den Algorithmus. Ein hoher Blutdruck darf ACS, Dissektion oder Schlaganfall nicht verdecken.</p></>)}

    {section("09", "Weitere Maßnahmen · Thüringer VFA 16/17", <><h3>Erst die Abzweigung, dann das Medikament</h3><div className="pulmo-path"><span>Lungenödem?</span><i>→</i><span>ACS?</span><i>→</i><span>Schlaganfall?</span><i>→</i><span>VFA 16 oder 17</span></div><div className="pulmo-compare"><div><small>VFA 16 · Urapidil</small><h3>10 mg langsam i.v.</h3><p>Nach <b>5 Minuten</b> RR-Kontrolle. Ist die Senkung des systolischen Ausgangswerts um <b>25 %</b> nicht erreicht, erlaubt die VFA höchstens <b>zwei Wiederholungen</b>. Insgesamt maximal <b>30 mg</b> im VFA-Pfad; kontinuierlich überwachen und transportieren.</p></div><div><small>VFA 17 · Nifedipin</small><h3>10 mg Zerbeißkapsel</h3><p>Erst nach Ausschluss der vorgeschalteten Lungenödem-, ACS- und Schlaganfall-Pfade. Bei Myokardinfarkt in den letzten <b>4 Wochen</b> oder Schwangerschaft/Stillzeit verweist VFA 17 auf den Urapidil-Pfad. Nifedipin ist eine orale Kapsel, keine Spritze.</p></div></div><div className="pulmo-risk-grid"><div><b>Urapidil · Wirkung</b><p>Blockade peripherer α1-Rezeptoren senkt den Gefäßwiderstand; zentrale 5-HT1A-Wirkung dämpft die reflektorische Sympathikusreaktion. Schwindel und Hypotonie im Verlauf beachten.</p></div><div><b>Nifedipin · Wirkung</b><p>Als Dihydropyridin-Calciumantagonist erweitert es Gefäße durch Hemmung von Calciumkanälen der glatten Muskulatur. Ein rascher Druckabfall und Reflextachykardie sind relevante Risiken.</p></div></div><aside className="diagnostic-boundary"><span>!</span><div><b>Keine Dosis aus dem Factsheet übertragen</b><p>Die gezeigten Mengen und Zeiten stammen ausschließlich aus VFA 16/17 und Anlage B2A. Bei Sonderlagen – besonders neurologischem Defizit, Dissektion oder Schwangerschaft – den jeweiligen Algorithmus und ärztliche Unterstützung priorisieren.</p></div></aside></>)}

    {section("10", "VFA Thüringen 2026/2027 und Spritze", <><p>Die Originalalgorithmen lassen sich einklappen und im Vollbild betrachten. VFA 16 und 17 haben unterschiedliche Auswahlbedingungen; bei Lungenödem, ACS oder Schlaganfall zuerst den jeweils abzweigenden Algorithmus beachten.</p><div className="vfa-stack"><Vfa src="/lessons/hypertensiver-notfall/vfa-34.png" alt="Thüringer VFA 16 hypertensiver Notfall Urapidil mit 180/110-Grenze, Abzweigungen und Wiederholungen" caption="VFA 16 · Hypertensiver Notfall – Urapidil" /><Vfa src="/lessons/hypertensiver-notfall/vfa-35.png" alt="Thüringer VFA 17 hypertensiver Notfall Nifedipin mit 180/110-Grenze, Ausschlüssen und 10-Milligramm-Zerbeißkapsel" caption="VFA 17 · Hypertensiver Notfall – Nifedipin" /></div><Figure src="/lessons/hypertensiver-notfall/b2a-urapidil-71.png" alt="Anlage B2A: Urapidil 25 mg in 5 ml, unverdünnt, ein Milliliter entspricht fünf Milligramm" caption="Anlage B2A · Urapidil, relevante Zeile" wide /><UrapidilSyringe /></>)}

    {children}
    <p className="lesson-source">Grundlage: „Hypertesiver Notfall 2.pdf“. Grenzwerte aus der Unterlage; Dosierungen und Zubereitung aus der <a href="https://www.aelrd-thueringen.de/verfahrensanweisungen-fuer-den-thueringer-rettungsdienst-algorithmen/" target="_blank" rel="noreferrer">Thüringer VFA 2026/27</a>, Nr. 16, 17 und B2A. Ergänzend zu Kreislauf und Gefäßen: <a href="https://openstax.org/books/anatomy-and-physiology-2e/pages/20-1-structure-and-function-of-blood-vessels" target="_blank" rel="noreferrer">Gefäßaufbau</a> und <a href="https://openstax.org/books/anatomy-and-physiology-2e/pages/20-2-blood-flow-blood-pressure-and-resistance" target="_blank" rel="noreferrer">Blutfluss und Rückstrom</a> sowie <a href="https://openstax.org/books/anatomy-and-physiology-2e/pages/15-2-autonomic-reflexes-and-homeostasis" target="_blank" rel="noreferrer">Baroreflex</a> und <a href="https://openstax.org/books/anatomy-and-physiology-2e/pages/25-9-regulation-of-fluid-volume-and-composition" target="_blank" rel="noreferrer">renale Volumenregulation</a>; zu Physiologie und Wirkung: <a href="https://rd-factsheets.de/fs/raas/" target="_blank" rel="noreferrer">RAAS</a>, <a href="https://rd-factsheets.de/fs/urapidil/" target="_blank" rel="noreferrer">Urapidil</a> und <a href="https://rd-factsheets.de/fs/nifedipin/" target="_blank" rel="noreferrer">Nifedipin</a>. Für die Entscheidung im Einsatz gilt die aktuelle VFA.</p>
  </article>;
}
