type TrainingFlashcard = { id: string; area: string; question: string; answer: string };
type ChoiceOption = { text: string; correct?: boolean };
type MultipleChoiceQuestion = { id: string; prompt: string; options: ChoiceOption[]; source: string; difficulty: 1 | 2 | 3; mode: "multiple" };

export const hyperventilationFlashcards: TrainingFlashcard[] = [
  { id: "hyper-card-01", area: "Definition", question: "Definieren Sie Hyperventilation über den Bedarf des Organismus und grenzen Sie sie von bloßer Tachypnoe ab.", answer: "Hyperventilation ist eine im Verhältnis zur CO₂-Produktion zu hohe alveoläre Ventilation. Entscheidend ist der CO₂-Abfall, nicht allein eine hohe Atemfrequenz; auch vertiefte Atmung kann hyperventilatorisch sein." },
  { id: "hyper-card-02", area: "Ventilation", question: "Leiten Sie her, wie Atemfrequenz und Atemzugvolumen das Atemminutenvolumen beeinflussen.", answer: "Atemminutenvolumen = Atemfrequenz × Atemzugvolumen. Steigen Frequenz und/oder Tiefe über den Stoffwechselbedarf, wird mehr CO₂ abgeatmet als gebildet und der arterielle CO₂-Partialdruck sinkt." },
  { id: "hyper-card-03", area: "Puffersystem", question: "Erklären Sie die Verschiebung des Bikarbonatpuffers bei verstärkter CO₂-Abatmung.", answer: "CO₂ + H₂O ↔ H₂CO₃ ↔ H⁺ + HCO₃⁻. Durch CO₂-Verlust verschiebt sich das Gleichgewicht nach links, die H⁺-Konzentration sinkt und der pH-Wert steigt: respiratorische Alkalose." },
  { id: "hyper-card-04", area: "Tetanie", question: "Warum können bei respiratorischer Alkalose Parästhesien und eine Pfötchenstellung auftreten, obwohl das Gesamtkalzium kaum verändert sein muss?", answer: "Der höhere pH steigert die Bindung von Kalzium an Plasmaproteine. Dadurch sinkt vorübergehend das biologisch wirksame ionisierte Kalzium; die neuromuskuläre Erregbarkeit steigt bis zur Tetanie." },
  { id: "hyper-card-05", area: "Zerebrale Wirkung", question: "Erklären Sie Schwindel, Benommenheit und mögliche Synkope bei ausgeprägter Hyperventilation.", answer: "Hypokapnie führt zur zerebralen Vasokonstriktion. Die Hirndurchblutung nimmt ab; daraus können Schwindel, Benommenheit, Sehstörung und im Extremfall eine Synkope entstehen." },
  { id: "hyper-card-06", area: "Symptome", question: "Welche Befundkonstellation stützt eine psychogen ausgelöste Hyperventilation, ohne eine Ausschlussdiagnostik zu ersetzen?", answer: "Plausibler Angst- oder Stressauslöser, rasche tiefe Atmung, subjektive Luftnot, periorale und akrale Parästhesien, Pfötchenstellung, Palpitationen und rasche Besserung durch ruhige Atemführung. Normale SpO₂ kann passen, beweist die Ursache aber nicht." },
  { id: "hyper-card-07", area: "Red Flags", question: "Welche Befunde sprechen gegen die vorschnelle Annahme einer rein psychogenen Hyperventilation?", answer: "Zyanose oder auffällige SpO₂, Hypotonie, Fieber, Stridor/Wheezing, einseitig fehlendes Atemgeräusch, persistierender Thoraxschmerz, pathologisches EKG, metabolische Zeichen, fehlender plausibler Auslöser oder unvollständige Besserung." },
  { id: "hyper-card-08", area: "Differenzialdiagnosen", question: "Nennen Sie zeitkritische organische Ursachen einer Hyperventilation und ordnen Sie die Kussmaul-Atmung ein.", answer: "Unter anderem Lungenarterienembolie, ACS, Pneumothorax, Asthma, Sepsis, Hypoxie und metabolische Azidose. Bei der diabetischen Ketoazidose ist die tiefe Kussmaul-Atmung eine kompensatorische CO₂-Abatmung und darf nicht unterdrückt werden." },
  { id: "hyper-card-09", area: "Erstmaßnahmen", question: "Strukturieren Sie die ersten präklinischen Maßnahmen bei vermutetem Hyperventilationssyndrom.", answer: "Eigenschutz, cABCDE, kritische Einordnung, ruhige reizreduzierte Umgebung, aufrechte bequeme Position, kurze klare Kommunikation, angeleitete langsame Atmung, Monitoring nach Befund, SAMPLERS/OPQRST und gezielte Suche nach organischen Ursachen." },
  { id: "hyper-card-10", area: "Kapnographie", question: "Wie bewerten Sie einen niedrigen EtCO₂-Wert bei tachypnoischem Patienten?", answer: "Er stützt eine gesteigerte CO₂-Abatmung, beweist aber keine psychogene Ursache. Auch Lungenarterienembolie, Schock, Sepsis oder andere Ventilations-Perfusions-Störungen können EtCO₂ senken; Klinik und Verlauf entscheiden." },
  { id: "hyper-card-11", area: "Rückatmung", question: "Warum ist die unkritische Rückatmung in eine Papier- oder Plastiktüte gefährlich?", answer: "Eine organische Ursache oder Hypoxie kann übersehen und durch sauerstoffarme Rückatmung verschlechtert werden. Sicherer sind Talk-down und angeleitete Atemverlangsamung; spezielle Systeme nur nach örtlicher Vorgabe und nach Ausschluss einer organischen Ursache." },
  { id: "hyper-card-12", area: "Entscheidung", question: "Welche Kriterien sind vor einem möglichen ambulanten Belassen zu prüfen?", answer: "Plausible psychogene Situation, vollständige und anhaltende Besserung, unauffällige strukturierte Untersuchung und Vitalparameter, keine Red Flags, nachvollziehbare Betreuung sowie Rücksprache und Übereinstimmung mit lokalen Vorgaben. Bei Unsicherheit erfolgt Transport." },
];

export const hyperventilationQuestions: MultipleChoiceQuestion[] = [
  { id: "hyper-q-01", mode: "multiple", difficulty: 1, prompt: "Welche Aussagen beschreiben eine Hyperventilation physiologisch korrekt?", options: [{ text: "Die alveoläre Ventilation übersteigt den aktuellen CO₂-Anfall", correct: true }, { text: "Der arterielle CO₂-Partialdruck sinkt typischerweise", correct: true }, { text: "Eine hohe Atemfrequenz allein beweist sie unabhängig vom Atemzugvolumen" }, { text: "Auch eine vertiefte Atmung kann zur Hyperventilation beitragen", correct: true }], source: "Hyperventilation bedeutet eine gegenüber dem Stoffwechselbedarf gesteigerte alveoläre Ventilation mit vermehrter CO₂-Abatmung." },
  { id: "hyper-q-02", mode: "multiple", difficulty: 1, prompt: "Welche Veränderungen folgen unmittelbar aus einer ausgeprägten CO₂-Abatmung?", options: [{ text: "Verschiebung des Bikarbonatgleichgewichts nach links", correct: true }, { text: "Abnahme freier H⁺-Ionen und Anstieg des pH-Werts", correct: true }, { text: "Primäre respiratorische Alkalose", correct: true }, { text: "Primäre metabolische Azidose durch Anstieg des paCO₂" }], source: "CO₂-Verlust senkt die Kohlensäure- und H⁺-Konzentration; der pH steigt." },
  { id: "hyper-q-03", mode: "multiple", difficulty: 1, prompt: "Welche Befunde passen zum Hyperventilationssyndrom?", options: [{ text: "Periorale und akrale Parästhesien", correct: true }, { text: "Pfötchenstellung oder Tetanie", correct: true }, { text: "Schwindel, Palpitationen und thorakales Engegefühl", correct: true }, { text: "Eine Zyanose als beruhigender Beweis der psychogenen Ursache" }], source: "Typisch sind subjektive Dyspnoe, Parästhesien, tetanische Zeichen, Schwindel, Angst und vegetative Symptome; Zyanose ist eine Red Flag." },
  { id: "hyper-q-04", mode: "multiple", difficulty: 1, prompt: "Welche Aussagen zur Atemmechanik und zum Gasaustausch sind richtig?", options: [{ text: "Bei der Inspiration senkt sich das kontrahierende Zwerchfell", correct: true }, { text: "Die Exspiration erfolgt in Ruhe überwiegend passiv", correct: true }, { text: "Der Gasaustausch erfolgt an der dünnen alveolokapillären Membran", correct: true }, { text: "Große Bronchien besitzen ausschließlich glatte Muskulatur und keinen Knorpel" }], source: "Inspiration vergrößert aktiv den Thorax; die Ruheatmung exspiriert überwiegend passiv. Alveolen ermöglichen den Diffusionsaustausch." },
  { id: "hyper-q-05", mode: "multiple", difficulty: 1, prompt: "Welche Elemente gehören zur sicheren Erstbeurteilung?", options: [{ text: "cABCDE und kritische Einordnung", correct: true }, { text: "SAMPLERS und situationsbezogen OPQRST", correct: true }, { text: "Gezielte Prüfung auf organische Ursachen", correct: true }, { text: "Die Diagnose allein aus einem erkennbaren Angstzustand ableiten" }], source: "Psychogener Auslöser und organische Erkrankung können gleichzeitig bestehen; die strukturierte Beurteilung bleibt notwendig." },
  { id: "hyper-q-06", mode: "multiple", difficulty: 1, prompt: "Welche Maßnahmen können bei plausibler psychogener Hyperventilation unmittelbar helfen?", options: [{ text: "Ruhige, kurze Erklärung und reizreduzierte Umgebung", correct: true }, { text: "Langsames Ausatmen und einen geführten Atemrhythmus anleiten", correct: true }, { text: "Eine bequeme aufrechte Position anbieten", correct: true }, { text: "Den Patienten ohne Untersuchung in eine luftdichte Plastiktüte atmen lassen" }], source: "Talk-down, Atemführung und eine ruhige Position unter fortgesetzter Beobachtung sind zentrale Maßnahmen." },
  { id: "hyper-q-07", mode: "multiple", difficulty: 2, prompt: "Warum führt eine respiratorische Alkalose zu neuromuskulärer Übererregbarkeit?", options: [{ text: "Die Proteinbindung von Kalzium nimmt mit steigendem pH zu", correct: true }, { text: "Das ionisierte Kalzium sinkt vorübergehend", correct: true }, { text: "Parästhesien und Karpopedalspasmen können daraus folgen", correct: true }, { text: "Das Gesamtkalzium muss dabei zwingend massiv abfallen" }], source: "Alkalose senkt das freie ionisierte Kalzium durch vermehrte Proteinbindung, auch ohne ausgeprägte Änderung des Gesamtkalziums." },
  { id: "hyper-q-08", mode: "multiple", difficulty: 2, prompt: "Ein Patient atmet tief und schnell, ist ängstlich und hat SpO₂ 99 %. Welche Bewertungen sind korrekt?", options: [{ text: "Die gute Sättigung schließt eine Lungenarterienembolie nicht sicher aus", correct: true }, { text: "Anamnese, Auskultation, Kreislauf und EKG bleiben relevant", correct: true }, { text: "Psychogene Hyperventilation ist möglich, aber eine Ausschlussdiagnose", correct: true }, { text: "Die SpO₂ beweist, dass keine organische Ursache vorliegt" }], source: "Eine normale Sättigung kann beim Hyperventilationssyndrom vorkommen, ersetzt aber nicht die Differenzialdiagnostik." },
  { id: "hyper-q-09", mode: "multiple", difficulty: 2, prompt: "Welche Konstellationen sind Red Flags gegen eine rein psychogene Erklärung?", options: [{ text: "Hypotonie oder Zyanose", correct: true }, { text: "Einseitig fehlendes Atemgeräusch oder Stridor", correct: true }, { text: "Persistierender Thoraxschmerz oder pathologisches EKG", correct: true }, { text: "Rasche vollständige Besserung unter ruhiger Atemführung ohne Auffälligkeiten" }], source: "Kreislauf-, Oxygenierungs-, Atemwegs- und kardiale Auffälligkeiten verlangen die Suche nach organischen Ursachen." },
  { id: "hyper-q-10", mode: "multiple", difficulty: 2, prompt: "Welche Aussagen zu einem erniedrigten EtCO₂ sind fachlich belastbar?", options: [{ text: "Er kann eine gesteigerte CO₂-Abatmung abbilden", correct: true }, { text: "Er ist allein nicht spezifisch für eine psychogene Ursache", correct: true }, { text: "Er kann auch bei Lungenarterienembolie oder Schock erniedrigt sein", correct: true }, { text: "Er schließt bei normaler SpO₂ eine metabolische Azidose sicher aus" }], source: "EtCO₂ muss im klinischen Kontext interpretiert werden; mehrere organische Zustände können niedrige Werte verursachen." },
  { id: "hyper-q-11", mode: "multiple", difficulty: 2, prompt: "Welche Aussagen zur Kussmaul-Atmung bei diabetischer Ketoazidose treffen zu?", options: [{ text: "Sie dient der respiratorischen Kompensation einer metabolischen Azidose", correct: true }, { text: "Die CO₂-Abatmung hilft, den pH-Wert anzuheben", correct: true }, { text: "Ein erzwungenes Unterdrücken der Atmung kann die Azidämie verschlechtern", correct: true }, { text: "Sie beweist eine primär psychogene Hyperventilation" }], source: "Tiefe Kussmaul-Atmung ist eine sinnvolle Kompensation der metabolischen Azidose und keine primäre Angststörung." },
  { id: "hyper-q-12", mode: "multiple", difficulty: 2, prompt: "Welche Zusammenhänge erklären Schwindel und mögliche Synkope?", options: [{ text: "Hypokapnie verengt zerebrale Gefäße", correct: true }, { text: "Die zerebrale Durchblutung kann abnehmen", correct: true }, { text: "Der Effekt kann trotz guter peripherer Sauerstoffsättigung auftreten", correct: true }, { text: "Hyperkapnie ist der zwingende Mechanismus einer psychogenen Hyperventilation" }], source: "Der CO₂-Abfall verursacht zerebrale Vasokonstriktion und kann die Hirndurchblutung vermindern." },
  { id: "hyper-q-13", mode: "multiple", difficulty: 3, prompt: "Eine 24-Jährige entwickelt nach einem Streit Tachypnoe, periorales Kribbeln und Pfötchenstellung. Welche Schritte sind trotz plausibler Angstreaktion erforderlich?", options: [{ text: "Strukturierte Vital- und cABCDE-Beurteilung", correct: true }, { text: "Organische Red Flags aktiv erfragen und untersuchen", correct: true }, { text: "Unter Anleitung Atemfrequenz und Atemtiefe reduzieren", correct: true }, { text: "Wegen des Auslösers auf jede kardiale oder pulmonale Prüfung verzichten" }], source: "Ein psychischer Trigger erhöht die Plausibilität, ersetzt aber weder Untersuchung noch Ausschluss zeitkritischer Ursachen." },
  { id: "hyper-q-14", mode: "multiple", difficulty: 3, prompt: "Warum ist routinemäßige Tütenrückatmung keine sichere Standardmaßnahme?", options: [{ text: "Eine nicht erkannte Hypoxie kann verschlechtert werden", correct: true }, { text: "Eine organische Ursache kann fälschlich als Angststörung behandelt werden", correct: true }, { text: "Talk-down und kontrollierte Atemführung sind risikoärmere erste Schritte", correct: true }, { text: "Sie normalisiert bei jeder Ursache zuverlässig Ventilation und Oxygenierung" }], source: "Unkritische Rückatmung kann bei organischer Erkrankung gefährlich sein und gehört nicht zur routinemäßigen Erstmaßnahme." },
  { id: "hyper-q-15", mode: "multiple", difficulty: 3, prompt: "Welche Patientenkonstellationen verlangen eher Transport und weitere Abklärung als ambulantes Belassen?", options: [{ text: "Unvollständige Besserung oder wiederkehrende Beschwerden", correct: true }, { text: "Erstmanifestation mit unklarer Ursache", correct: true }, { text: "Thoraxschmerz, auffälliges EKG oder relevante Risikofaktoren", correct: true }, { text: "Vollständige stabile Besserung, keine Red Flags und regelkonforme Rücksprache" }], source: "Bei Unsicherheit, Red Flags, fehlender nachhaltiger Besserung oder unklarer Erstmanifestation ist eine weitere Abklärung erforderlich." },
  { id: "hyper-q-16", mode: "multiple", difficulty: 3, prompt: "Welche physiologischen Aussagen verbinden Atemregulation und Säure-Basen-Haushalt korrekt?", options: [{ text: "Ein CO₂-Anstieg stimuliert unter anderem zentrale Chemorezeptoren und steigert den Atemantrieb", correct: true }, { text: "Ein ausgeprägter CO₂-Abfall vermindert den zentralen Atemantrieb", correct: true }, { text: "Die Niere kompensiert eine anhaltende respiratorische Alkalose verzögert durch vermehrte Bikarbonatausscheidung", correct: true }, { text: "Die vollständige renale Kompensation erfolgt innerhalb weniger Atemzüge" }], source: "CO₂/H⁺ beeinflussen die Atemregulation unmittelbar; die renale Kompensation entwickelt sich erst verzögert." },
  { id: "hyper-q-17", mode: "multiple", difficulty: 3, prompt: "Welche Befunde helfen, Asthma oder Pneumothorax von einem isolierten Hyperventilationssyndrom abzugrenzen?", options: [{ text: "Obstruktives Atemgeräusch und verlängertes Exspirium sprechen für Asthma", correct: true }, { text: "Einseitig fehlendes Atemgeräusch und Thoraxschmerz sprechen für Pneumothorax", correct: true }, { text: "Normale SpO₂ und Angst schließen beide Diagnosen sicher aus" }, { text: "Auskultation, Atemarbeit und Verlauf müssen gemeinsam bewertet werden", correct: true }], source: "Auskultations- und Seitenbefunde sowie Atemarbeit und Verlauf sind wichtig; psychische Anspannung kann organische Erkrankungen begleiten." },
  { id: "hyper-q-18", mode: "multiple", difficulty: 3, prompt: "Welche Übergabe dokumentiert ein fachlich belastbares Vorgehen bei Hyperventilation?", options: [{ text: "Beginn, Auslöser, Verlauf und relevante SAMPLERS-/OPQRST-Angaben", correct: true }, { text: "Serielle Vitalwerte, Atemfrequenz, SpO₂, EtCO₂ sofern erhoben und EKG-Befund", correct: true }, { text: "Organische Differenzialdiagnosen, Red Flags, Maßnahmen und Reaktion darauf", correct: true }, { text: "Nur die Aussage ‚Panikattacke‘ ohne objektive Befunde" }], source: "Eine belastbare Übergabe trennt Arbeitshypothese, objektive Befunde, Ausschlusskriterien, Maßnahmen und Verlauf." },
];
