import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [string, boolean];
function q(n: number, prompt: string, options: Option[], source: string): ThoraxtraumaChoiceQuestion {
  const shift = n % options.length;
  return { id: `hypertensiver-notfall-q-${String(n).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty: 3 };
}

export const hypertensiverNotfallQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Ein Patient hat RR 198/104 mmHg und starke neue Kopfschmerzen. Welche Aussagen zur VFA-Entscheidung sind richtig?", [["Der systolische Grenzwert der VFA 16/17 ist überschritten", true], ["Klinische Beschwerden müssen zusätzlich beurteilt werden", true], ["Neurologische Auffälligkeiten sind gezielt zu suchen", true], ["Der diastolische Wert muss ebenfalls über 110 mmHg liegen", false], ["Die erste Zahl allein beweist eine akute Hirnblutung", false]], "VFA 16/17: systolisch >180 oder diastolisch >110 mmHg und klinische Beschwerden."),
  q(2, "RR 184/112 mmHg, Patient wach und ohne Beschwerden. Welche Einordnung ist korrekt?", [["Der hohe Wert allein beweist keinen akuten Organschaden", true], ["Eine korrekte Wiederholungsmessung und klinische Beurteilung sind sinnvoll", true], ["Die VFA-Indikation verlangt zusätzlich klinische Beschwerden", true], ["Der Wert allein rechtfertigt automatisch eine schnelle 25-prozentige Senkung", false], ["Eine unauffällige Erstmessung des EKG ersetzt die Symptomanamnese", false]], "Der hypertensive Notfall hängt von Beschwerden bzw. Organbeteiligung ab, nicht nur vom Messwert."),
  q(3, "Welche physiologischen Strukturen beeinflussen den arteriellen Druck besonders?", [["Arteriolen verändern als Widerstandsgefäße den peripheren Widerstand", true], ["Die elastische Aorta glättet durch ihre Windkesselfunktion den Blutfluss", true], ["Das Herzzeitvolumen trägt neben dem Widerstand zum Druck bei", true], ["Taschenklappen der Beinvenen erzeugen primär den systolischen Aortendruck", false], ["Eine Vasokonstriktion der Arteriolen senkt zwangsläufig den Widerstand", false]], "Das Skript unterscheidet elastische Arterien, muskuläre Arterien und Arteriolen."),
  q(4, "Die Nierendurchblutung sinkt. Welche Schritte des RAAS sind korrekt geordnet?", [["Renin fördert die Bildung von Angiotensin I aus Angiotensinogen", true], ["ACE wandelt Angiotensin I in Angiotensin II um", true], ["Angiotensin II bewirkt Vasokonstriktion und stimuliert Aldosteron", true], ["Aldosteron wandelt unmittelbar Angiotensinogen in Renin um", false], ["ACE wird erst durch ADH zur Umwandlung von Angiotensin II in I benötigt", false]], "Renin → Angiotensin I → ACE → Angiotensin II; Aldosteron fördert Natrium- und Wasserrückresorption."),
  q(5, "Welche Folgen können aus einer raschen schweren Blutdruckentgleisung entstehen?", [["Gestörte zerebrale Autoregulation und neurologische Symptome", true], ["Akute Linksherzbelastung mit Lungenödem", true], ["Schädigung von Endothel und Mikrozirkulation", true], ["Eine sichere Verbesserung der Hirnperfusion durch sofortige Normotonie", false], ["Ausschließliche Beteiligung der peripheren Venen ohne Organrisiko", false]], "Überforderung der Autoregulation kann Gehirn, Herz, Lunge, Aorta und Niere betreffen."),
  q(6, "Warum ist eine unkontrolliert rasche Blutdrucksenkung gefährlich?", [["Bei chronischer Hypertonie kann die Organ-Autoregulation auf höhere Drücke eingestellt sein", true], ["Ein zu großer Abfall kann die Perfusion von Gehirn und Niere mindern", true], ["Die VFA 16 fordert eine kontrollierte Verlaufsmessung statt einen sofortigen Normwert", true], ["Je tiefer der Blutdruck nach der ersten Gabe, desto sicherer ist die Hirnperfusion", false], ["Ein Blutdruckabfall ist bei jedem Schlaganfall immer ohne eigene Zielvorgabe anzustreben", false]], "VFA 16: systolischen Ausgangswert kontrolliert um 25 % senken; Sonderbilder haben eigene Pfade."),
  q(7, "RRsys 240 mmHg ohne Lungenödem-, ACS- oder Schlaganfallverdacht: Welche VFA-16-Aussagen stimmen?", [["Die Erfolgskontrolle bezieht sich auf etwa 25 % Senkung vom systolischen Ausgangswert", true], ["Eine Senkung um 25 % entspricht hier rechnerisch 60 mmHg", true], ["Der daraus berechnete Kontrollwert beträgt 180 mmHg", true], ["Das Therapieziel lautet unabhängig vom Ausgangswert immer sofort 120 mmHg systolisch", false], ["Ein einzelner 25-%-Wert ersetzt die klinische Re-Evaluation", false]], "240 × 0,25 = 60; 240 − 60 = 180 mmHg. VFA-Pfad und Organlage beachten."),
  q(8, "Bei RR 210/116 mmHg und fokal-neurologischem Defizit: Was folgt aus der Thüringer VFA?", [["Zuerst den Schlaganfallpfad VFA 44 prüfen", true], ["Neurologische Symptome und Beginn dokumentieren", true], ["Eine schematische Anwendung des allgemeinen 25-%-Ziels vermeiden", true], ["Ohne weitere Diagnostik sofort den Nifedipin-Pfad wählen", false], ["Das Defizit als harmlose Begleiterscheinung des hohen Drucks abtun", false]], "VFA 16/17 verzweigen bei Schlaganfallverdacht in VFA 44."),
  q(9, "Ein Patient mit hohem RR hat akuten Thoraxschmerz. Welche Gedanken sind prüfungsrelevant?", [["ACS mittels 12-Kanal-EKG und Klinik abklären", true], ["Bei plötzlichem starkem Thorax- oder Rückenschmerz an Aortendissektion denken", true], ["Der spezifische Pfad geht vor einer schematischen isolierten Hypertoniebehandlung", true], ["Nifedipin ist der erste Schritt vor jeder ACS-Abklärung", false], ["Ein hoher RR schließt eine gleichzeitig bestehende Koronarischämie aus", false]], "VFA 16/17 verzweigen bei ACS; das Skript nennt Aortendissektion als wichtige Differenzialdiagnose."),
  q(10, "Welche Zeichen aus VFA 16/17 gelten als Red Flags?", [["Sehstörung oder Vigilanzminderung", true], ["Fokal-neurologische Defizite", true], ["Thoraxschmerzen oder Dyspnoe", true], ["Eine asymptomatische Langzeit-Hypertonie ohne aktuelle Beschwerden", false], ["Allein eine frühere Hypertoniediagnose", false]], "VFA 16/17 nennen Kopfschmerz, Übelkeit/Erbrechen, Seh- und Vigilanzstörung, fokale Defizite, Thoraxschmerz und Dyspnoe."),
  q(11, "Welche Maßnahmen gehören vor einer antihypertensiven Gabe zum präklinischen Vorgehen?", [["cABCDE und dominierendes Leitsymptom beurteilen", true], ["RR zuverlässig messen und Verlauf sichern", true], ["Lungenödem, ACS und Schlaganfall als VFA-Abzweigungen prüfen", true], ["Zuerst nur das Medikament aufziehen und erst danach die Atmung beurteilen", false], ["Jeden hohen RR unabhängig vom Kreislauf mit gleicher Dosis behandeln", false]], "VFA 16/17 beginnen mit cABCDE und leiten bei spezifischen Notfallbildern in andere Algorithmen."),
  q(12, "Was ist laut VFA 16 bei geeignetem hypertensivem Notfall vorgesehen?", [["10 mg Urapidil langsam i.v.", true], ["Nach 5 Minuten RR-Kontrolle", true], ["Bei fehlendem Erfolg höchstens zwei Wiederholungen des Schritts", true], ["Eine sofortige unkontrollierte Wiederholung ohne Messung", false], ["Eine Standard-Erstgabe von 50 mg allein nach dem Factsheet", false]], "VFA 16 nennt 10 mg langsam i.v., RR-Kontrolle nach 5 Minuten und maximal zwei Wiederholungen."),
  q(13, "Eine 25-mg/5-ml-Ampulle Urapidil liegt vor. Welche Rechnungen und Vorbereitungen stimmen mit B2A überein?", [["Die Lösung enthält 5 mg/ml", true], ["Für eine VFA-16-Gabe von 10 mg werden 2 ml aufgezogen", true], ["B2A empfiehlt für Urapidil keine NaCl-Verdünnung", true], ["Für 10 mg sind wegen der Ampullengröße 5 ml nötig", false], ["2 ml Wirkstoff plus 8 ml NaCl sind die vorgegebene B2A-Zubereitung", false]], "B2A: 25 mg/5 ml = 5 mg/ml, unverdünnt. 10 mg / 5 mg/ml = 2 ml."),
  q(14, "Nach 10 mg Urapidil bleibt die RR-Senkung aus. Was muss vor einer weiteren Gabe beachtet werden?", [["Die VFA sieht zunächst eine Kontrolle nach 5 Minuten vor", true], ["Wirkung und Symptome müssen erneut beurteilt werden", true], ["Im VFA-16-Pfad sind höchstens zwei Wiederholungen vorgesehen", true], ["Ein guter peripherer Puls macht jede erneute RR-Messung entbehrlich", false], ["Die maximale Anzahl von Wiederholungen ist unbegrenzt, wenn der Wert hoch bleibt", false]], "Jede Wiederholung folgt auf kontrollierte Beurteilung; maximal drei 10-mg-Gaben im Pfad."),
  q(15, "Welche Aussage zur Nifedipin-Abzweigung nach VFA 17 trifft zu?", [["Lungenödem, ACS und Schlaganfall werden zuvor in eigene Pfade geleitet", true], ["Ein Myokardinfarkt innerhalb der letzten vier Wochen führt zum Urapidil-Pfad", true], ["Schwangerschaft oder Stillzeit führen ebenfalls zum Urapidil-Pfad", true], ["Bei akutem ACS wird der Nifedipin-Zweig ohne Abklärung bevorzugt", false], ["Nifedipin wird in dieser VFA als i.v.-Spritze aufgezogen", false]], "VFA 17: nach den Abzweigungen und bei fehlenden Ausschlusskonstellationen 10 mg Nifedipin als Zerbeißkapsel."),
  q(16, "Welche pharmakologischen Wirkungen sind richtig zugeordnet?", [["Urapidil blockiert periphere α1-Rezeptoren", true], ["Eine zentrale 5-HT1A-Wirkung von Urapidil dämpft die reflektorische Sympathikusreaktion", true], ["Nifedipin hemmt Calciumkanäle der glatten Gefäßmuskulatur", true], ["Nifedipin aktiviert α1-Rezeptoren zur Vasokonstriktion", false], ["Urapidil wirkt ausschließlich über die Natriumrückresorption der Niere", false]], "Mechanismen aus den ergänzenden Factsheets; Dosierungen stammen allein aus der VFA."),
  q(17, "Welche möglichen Folgen einer antihypertensiven Behandlung müssen überwacht werden?", [["Schwindel oder Hypotonie nach Urapidil", true], ["Rascher Druckabfall nach Nifedipin", true], ["Reflextachykardie als mögliches Risiko bei Nifedipin", true], ["Sichere Normalisierung der Organperfusion allein durch sinkende Zahlen", false], ["Wirkungskontrolle nur nach Ende des Transports", false]], "Wirkung, Kreislauf und Symptome müssen im Verlauf kontrolliert werden."),
  q(18, "Eine Patientin hat RR 194/114 mmHg und Rasselgeräusche mit schwerer Dyspnoe. Welche Priorisierung stimmt?", [["Akutes kardiales Lungenödem prüfen", true], ["cABCDE, Oxygenierung und Monitoring priorisieren", true], ["Den speziellen Lungenödem-Algorithmus der VFA einbeziehen", true], ["Zuerst allein die 25-%-Rechnung durchführen und Atemarbeit ignorieren", false], ["Nifedipin unabhängig vom Lungenbefund als erste Maßnahme geben", false]], "Bei Lungenödem verzweigt VFA 16/17 in den Basisalgorithmus kardiales Lungenödem."),
  q(19, "Welche Angaben sind bei Übergabe eines hypertensiven Notfalls besonders wertvoll?", [["Ausgangs-RR und Verlaufsmessungen", true], ["Zeitlicher Beginn und Entwicklung der Organzeichen", true], ["Gegebene Medikamente mit Dosis, Uhrzeit und Wirkung", true], ["Nur der letzte RR-Wert ohne vorherige Messungen", false], ["Die Annahme einer Hirnblutung allein aufgrund roten Gesichts", false]], "Eine nachvollziehbare Übergabe trennt Messwert, Symptom, Entscheidung und Wirkung."),
  q(20, "Welche Aussage trennt einen hohen Messwert vom hypertensiven Notfall fachlich sauber?", [["Akute oder sich verschlechternde Organschädigung ist klinisch entscheidend", true], ["Die VFA benutzt >180 systolisch oder >110 diastolisch plus Beschwerden als Einsatzindikation", true], ["Auch bei passender Zahl müssen ACS, Schlaganfall und Lungenödem geprüft werden", true], ["Jeder Blutdruck über 180 systolisch bedeutet automatisch eine Aortendissektion", false], ["Epistaxis beweist allein bereits eine intrazerebrale Blutung", false]], "Die VFA-Grenze ist eine operative Entscheidungshilfe; die klinische Organlage bestimmt die Einordnung."),
  q(21, "Was ist beim Verdacht auf Schlaganfall und zugleich hohem RR besonders zu beachten?", [["Der Schlaganfallpfad VFA 44 nennt eine eigene Schwelle über 220 systolisch oder über 120 diastolisch", true], ["Ein rascher Druckabfall kann die Hirnperfusion beeinträchtigen", true], ["Neurologischer Befund und Symptombeginn gehören in die Übergabe", true], ["Die 25-%-Regel aus VFA 16 ersetzt die Ziele der VFA 44", false], ["Jeder Blutdruck über 180 systolisch muss bei Schlaganfallverdacht sofort normalisiert werden", false]], "VFA 44 hat eigene Schwellen und Ziele; nicht den allgemeinen Pfad übertragen."),
  q(22, "Ein Patient hatte vor zwei Wochen einen Myokardinfarkt und erfüllt sonst die VFA-17-Eingangsbedingungen. Welche Entscheidungen sind richtig?", [["Der frühere Infarkt liegt innerhalb der Vier-Wochen-Abzweigung", true], ["VFA 17 verweist in dieser Konstellation auf Urapidil", true], ["Aktuelle Ischämie und ACS-Pfad müssen dennoch geprüft werden", true], ["Die Vier-Wochen-Frage darf ignoriert werden, sobald Nifedipin verfügbar ist", false], ["Eine alte Infarktdiagnose allein ersetzt die aktuelle cABCDE-Beurteilung", false]], "VFA 17 fragt nach Myokardinfarkt in den letzten vier Wochen und leitet dann zu VFA 16."),
];

export const hypertensiverNotfallFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "hypertensiver-notfall-card-01", area: "Definition", question: "Welche Grenzwerte stehen in Unterlage und VFA 16/17, und warum ist ein hoher Wert allein noch keine vollständige Notfalldiagnose?", answer: "RRsys >180 oder RRdia >110 mmHg plus klinische Beschwerden. Die Gefährdung ergibt sich aus möglicher akuter Organbeteiligung; Messwert, Symptome und Verlauf zusammen beurteilen." },
  { id: "hypertensiver-notfall-card-02", area: "Gefäße", question: "Erklären Sie elastische Arterien, muskuläre Arterien und Arteriolen mit ihrem Beitrag zur Druckregulation.", answer: "Aorta/elastische Arterien glätten den Auswurf durch Windkesselfunktion; muskuläre Arterien verteilen den Blutfluss; Arteriolen ändern als Widerstandsgefäße den peripheren Widerstand besonders stark." },
  { id: "hypertensiver-notfall-card-03", area: "RAAS", question: "Leiten Sie die RAAS-Kaskade von verminderter Nierendurchblutung bis zur Druck- und Volumenwirkung ab.", answer: "Renin fördert Angiotensinogen → Angiotensin I; ACE bildet Angiotensin II. Angiotensin II verengt Gefäße und fördert Aldosteron; Aldosteron steigert Natrium- und Wasserrückresorption." },
  { id: "hypertensiver-notfall-card-04", area: "Pathophysiologie", question: "Wie kann ein rascher Druckanstieg Gehirn, Herz und Mikrozirkulation schädigen?", answer: "Überforderte Autoregulation und Endothelschaden stören die Mikrozirkulation, fördern Ödeme und Minderperfusion. Klinische Folgen können Enzephalopathie, Ischämie und Linksherzdekompensation sein." },
  { id: "hypertensiver-notfall-card-05", area: "Red Flags", question: "Welche Symptome lassen Sie bei >180/110 mmHg aktiv nach akutem Organschaden suchen?", answer: "Vigilanzänderung, fokale Neurologie, Sehstörung, starke Kopfschmerzen/Erbrechen, Thoraxschmerz, Dyspnoe. Epistaxis ist ebenfalls in der VFA-Indikation genannt." },
  { id: "hypertensiver-notfall-card-06", area: "Differenzialdiagnose", question: "Wie priorisieren Sie Thoraxschmerz, Rasseln und fokale Neurologie bei hohem Blutdruck?", answer: "Thoraxschmerz: ACS und Aortendissektion prüfen; Rasseln/Dyspnoe: Lungenödem; fokale Neurologie: Schlaganfall oder Blutung. Die VFA verzweigt in die spezifischen Pfade." },
  { id: "hypertensiver-notfall-card-07", area: "VFA 16", question: "Nennen Sie Urapidil-Gabe, Kontrollzeit, Erfolgskriterium und maximale Zahl von Wiederholungen in VFA 16.", answer: "10 mg langsam i.v.; nach 5 Minuten RR-Kontrolle; Erfolg ist systolische Senkung um 25 % vom Ausgangswert. Bei fehlendem Erfolg maximal zwei Wiederholungen, also maximal 30 mg im Pfad." },
  { id: "hypertensiver-notfall-card-08", area: "Spritze", question: "Berechnen Sie das Aufziehvolumen für 10 mg Urapidil aus 25 mg/5 ml nach B2A.", answer: "25 mg/5 ml = 5 mg/ml. 10 mg ÷ 5 mg/ml = 2 ml; Urapidil wird nach B2A unverdünnt aufgezogen, 0 ml NaCl." },
  { id: "hypertensiver-notfall-card-09", area: "VFA 17", question: "Wann leitet VFA 17 vom Nifedipin-Pfad zum Urapidil-Pfad ab, und was ist die Nifedipin-Form?", answer: "Bei Myokardinfarkt innerhalb der letzten vier Wochen sowie Schwangerschaft oder Stillzeit zum Urapidil-Pfad. Sonst bei passenden Bedingungen 10 mg Nifedipin als orale Zerbeißkapsel; keine i.v.-Spritze." },
  { id: "hypertensiver-notfall-card-10", area: "Wirkmechanismus", question: "Vergleichen Sie Urapidil und Nifedipin ohne Dosierungen.", answer: "Urapidil senkt den peripheren Widerstand durch α1-Blockade und dämpft zentral über 5-HT1A reflektorischen Sympathikustonus. Nifedipin blockiert L-Typ-Calciumkanäle der glatten Gefäßmuskulatur; rascher Druckabfall/Reflextachykardie möglich." },
  { id: "hypertensiver-notfall-card-11", area: "Sonderfall", question: "Warum dürfen die allgemeine 25-%-Regel und der Nifedipin-Pfad nicht schematisch auf Schlaganfallverdacht übertragen werden?", answer: "VFA 16/17 verzweigen bei Schlaganfall in VFA 44. Diese hat eigene Schwellen (>220 systolisch oder >120 diastolisch) und Ziele; die Hirnperfusion darf nicht durch unkontrollierte Senkung gefährdet werden." },
  { id: "hypertensiver-notfall-card-12", area: "Übergabe", question: "Welche Informationen übergeben Sie, damit eine Klinik Ihren Entscheidungsweg nachvollziehen kann?", answer: "Ausgangs-RR und Verlauf, Messmethode, Organzeichen samt Beginn, neurologischer/Thorax-/Lungenbefund, 12-Kanal-EKG, Vorerkrankungen und Medikation sowie jede Maßnahme mit Zeit, Dosis und Wirkung." },
];
