import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function InstabileBradykardieLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, kicker: string, title: string, body: ReactNode) => <details open className="lesson-section rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>{kicker}</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;

  return <article className="lesson-article angina-pectoris-lesson reference-reading-lesson instabile-bradykardie-lesson">
    <div className="lesson-intro"><p className="lead">Eine langsame Herzfrequenz wird erst durch Organminderperfusion oder ein hohes Asystolierisiko zum zeitkritischen Notfall. In der Prüfung müssen klinische Instabilität, EKG-Muster, Blockhöhe und die Thüringer Therapieabfolge gemeinsam beurteilt werden.</p></div>

    {section("01", "Frequenz plus Perfusion", "Definition", <><p>Eine Bradykardie ist beim Erwachsenen eine Herzfrequenz unter 60/min. Eine <b>instabile Bradykardie</b> liegt vor, wenn die niedrige Frequenz zu einer hämodynamisch relevanten Minderperfusion führt. Die Thüringer VFA 19 behandelt die instabile Bradykardie unter 40/min; entscheidend bleiben Synkope, Schock, Herzinsuffizienz oder Myokardischämie.</p><div className="pulmo-compare"><div><small>Kompensiert</small><h3>Langsam, aber perfundiert</h3><p>Beschwerdefreier Patient, stabiler Blutdruck und unauffällige Organperfusion – beispielsweise bei trainierten Sportlern.</p></div><div><small>Instabil</small><h3>Langsam und minderversorgt</h3><p>Synkope, Schock, Ischämie oder akute Herzinsuffizienz zeigen, dass das Herzzeitvolumen nicht mehr ausreicht.</p></div></div></>)}

    {section("02", "Reizbildung und Reizleitung", "Anatomie und Physiologie", <><Figure src="/lessons/myokardinfarkt/herz-innenraeume.jpg" alt="Beschriftete Herzanatomie mit Vorhöfen, Kammern und Herzklappen" caption="Herzanatomie aus dem hinterlegten Anatomie-Skript · Vorhöfe und Kammern als Grundlage der Rhythmusinterpretation" wide /><Figure src="/lessons/instabile-bradykardie/erregungsleitung-av-block.png" alt="Beschriftetes Erregungsleitungssystem des Herzens mit Sinusknoten, AV-Knoten, His-Bündel, Tawara-Schenkeln und Purkinje-Fasern" caption="Erregungsleitungssystem · anatomische Zuordnung der AV-Blockierungen" wide /><div className="pulmo-path"><span>Sinusknoten</span><i>→</i><span>Vorhof</span><i>→</i><span>AV-Knoten</span><i>→</i><span>His-Bündel</span><i>→</i><span>Tawara / Purkinje</span></div><p>Der Sinusknoten erzeugt den primären Impuls. Im AV-Knoten wird die Überleitung physiologisch verzögert, damit die Vorhöfe ihre Füllung in die Kammern abschließen können. His-Bündel, Tawara-Schenkel und Purkinje-Fasern verteilen die Erregung schnell über das Ventrikelmyokard.</p><aside className="knowledge-note"><b>Na⁺/K⁺-Pumpe kurz erklärt</b><p>Die Na⁺/K⁺-ATPase transportiert unter ATP-Verbrauch drei Natriumionen aus und zwei Kaliumionen in die Zelle. Sie erhält damit die Ionengradienten für Ruhe- und Aktionspotenzial. Sie erzeugt nicht direkt jeden Herzschlag, sondern hält die elektrische Erregbarkeit der Herzmuskelzellen aufrecht.</p></aside></>)}

    {section("03", "Reizbildung oder Leitung gestört", "Pathophysiologie und Ursachen", <><div className="pulmo-risk-grid"><div><b>Reizbildungsstörung</b><p>Sinusbradykardie, Sick-Sinus-Syndrom oder Sinusarrest vermindern die primäre Impulsfrequenz.</p></div><div><b>Überleitungsstörung</b><p>SA-Block, AV-Block oder Schenkelblock verzögern oder unterbrechen die Weiterleitung.</p></div><div><b>Ischämie</b><p>Besonders ein inferiorer Myokardinfarkt kann Sinus- oder AV-Knoten und vagale Regulation betreffen.</p></div><div><b>Stoffwechsel</b><p>Hypoxie, Hypothermie, Azidose und Hyperkaliämie verändern Erregungsbildung und Leitung.</p></div><div><b>Medikamente / Gifte</b><p>Betablocker, Verapamil/Diltiazem, Digitalis, Clonidin oder Organophosphate können Bradykardien auslösen.</p></div><div><b>Neurovegetativ</b><p>Starker Vagusreiz, Karotissinus-Syndrom oder Hirndruck mit Cushing-Trias sind wichtige Alternativen.</p></div></div><p>Sinkt die Herzfrequenz, kann das Herzzeitvolumen trotz höherem Schlagvolumen nicht ausreichend kompensiert werden. Zerebrale und koronare Perfusion nehmen ab; Synkope, Ischämie, Schock und schließlich Asystolie können folgen.</p></>)}

    {section("04", "Die AV-Blöcke sicher unterscheiden", "EKG-Muster", <><Figure src="/lessons/instabile-bradykardie/av-block-vergleich.svg" alt="Schematischer EKG-Vergleich von Sinusbradykardie, AV-Block I, Wenckebach, Mobitz II und AV-Block III" caption="EKG-Lernvergleich · beim AV-Block III sind Vorhof- und Kammerrhythmus zur Verdeutlichung getrennt dargestellt" wide /><div className="pulmo-anatomy-grid"><div><small>AV-Block I</small><b>PQ &gt; 200 ms</b><p>Konstant verlängerte PQ-Zeit; jede P-Welle wird auf die Kammer übergeleitet.</p></div><div><small>AV-Block II Typ I</small><b>Wenckebach</b><p>PQ wird zunehmend länger, bis nach einer P-Welle ein QRS-Komplex ausfällt.</p></div><div><small>AV-Block II Typ II</small><b>Mobitz</b><p>Plötzlicher QRS-Ausfall bei zuvor konstanter PQ-Zeit; häufig infra-Hisär und mit breitem QRS.</p></div><div><small>AV-Block III</small><b>AV-Dissoziation</b><p>P-Wellen und QRS-Komplexe laufen regelmäßig, aber unabhängig voneinander.</p></div></div><Figure src="/lessons/instabile-bradykardie/av-block-ekg-uebersicht.png" alt="Handgezeichnete EKG-Übersicht der AV-Blöcke Grad I bis III" caption="Bereitgestellte EKG-Übersicht · typische Merkmale der drei AV-Blockgrade" wide /><aside className="diagnostic-boundary"><span>!</span><div><b>Prüfungsfalle 2:1-Block</b><p>Bei einer 2:1-Überleitung lässt sich oft nicht sicher zwischen Wenckebach und Mobitz II unterscheiden, weil nur eine PQ-Zeit vor dem Ausfall sichtbar ist. QRS-Breite, klinischer Kontext und Asystolierisiko werden dann besonders wichtig.</p></div></aside></>)}

    {section("05", "Arbeitsdiagnose stützen", "Symptome und Instabilitätszeichen", <><div className="pulmo-symptoms"><span>Synkope / Präsynkope</span><span>Schwindel</span><span>Vigilanzminderung</span><span>Hypotonie</span><span>Kaltschweißigkeit</span><span>Thoraxschmerz</span><span>Dyspnoe</span><span>Lungenödem</span><span>Schwäche</span><span>Oligurie</span></div><aside className="red-flags"><span>!</span><div><small>VFA 19 · Instabilität</small><h3>Synkope · Schock · Herzinsuffizienz · Myokardischämie</h3><p>Zusätzlich besteht Asystolierisiko bei kürzlicher Asystolie, AV-Block II Mobitz oder AV-Block III mit breitem QRS sowie einer ventrikulären Pause über drei Sekunden.</p></div></aside></>)}

    {section("06", "Peri-Arrest vorbereitet", "Komplikationen, Gefahren und Material", <><div className="pulmo-risk-grid"><div><b>Asystolie</b><p>Höhergradige distale Blöcke können in einen vollständigen Kreislaufstillstand übergehen.</p></div><div><b>Adams-Stokes-Anfall</b><p>Plötzliche zerebrale Minderperfusion verursacht Bewusstlosigkeit, gegebenenfalls Krampf und Sturzverletzung.</p></div><div><b>Myokardischämie</b><p>Niedriges Herzzeitvolumen verschlechtert die Koronarperfusion; eine Ischämie kann zugleich Ursache sein.</p></div><div><b>Herzinsuffizienz</b><p>Rückstau und Lungenödem entstehen, wenn die Pumpfunktion die Kreislaufanforderung nicht deckt.</p></div></div><div className="material-chips">{["Defibrillator mit Pacing-Funktion", "Klebeelektroden", "12-Kanal-EKG", "O₂ und Atemwegsmaterial", "Absaugung", "i.v.- / i.o.-Material", "Atropin", "Epinephrin", "Perfusor und VEL", "BZ / Temperatur", "Reanimationsmaterial"].map(item => <span key={item}>{item}</span>)}</div></>)}

    {section("07", "Parallel diagnostizieren und stabilisieren", "Erstmaßnahmen und SAMPLERS", <><div className="pulmo-care-grid"><div><span>01</span><b>cABCDE</b><small>Perfusion, Bewusstsein, Atmung und reversible vitale Störungen unmittelbar erfassen.</small></div><div><span>02</span><b>Monitoring</b><small>Defibrillatorpads, 4-Kanal- und 12-Kanal-EKG, SpO₂, Blutdruck und Kapnografie nach Befund.</small></div><div><span>03</span><b>Zugang</b><small>i.v.-Zugang, Medikamente und Schrittmacher vorbereiten; Notarzt nachfordern.</small></div><div><span>04</span><b>Ursache</b><small>Hypoxie, Hypothermie, Elektrolyte, Infarkt, Medikamente und Intoxikation mitdenken.</small></div></div><h3>SAMPLERS · fokussiert</h3><div className="samplers-grid">{[["S · Symptome", "Synkope, Thoraxschmerz, Dyspnoe, Beginn"], ["A · Allergien", "Arzneimittelreaktionen"], ["M · Medikamente", "Betablocker, Digitalis, Verapamil, Diltiazem"], ["P · Vorgeschichte", "Infarkt, Rhythmusstörung, Schrittmacher"], ["L · Letzte Aufnahme", "Dosis, Zeitpunkt, mögliche Überdosierung"], ["E · Ereignis", "Belastung, Vagusreiz, Kälte, Intoxikation"], ["R · Risiken", "Ischämie, Elektrolyte, Hypothyreose"], ["S · Schwangerschaft", "Schwangerschaft möglich?"]].map(([label, text]) => <p key={label}><b>{label}</b>{text}</p>)}</div></>)}

    {section("08", "Ursache und Rhythmus nicht verwechseln", "Differenzialdiagnosen und Entscheidungen", <><div className="differential-grid">{["Physiologische Sportlerbradykardie", "Inferiorer Myokardinfarkt", "Hypoxie", "Hypothermie", "Hyperkaliämie", "Betablocker- / Kalziumantagonistenintoxikation", "Digitalisintoxikation", "Organophosphatintoxikation", "Hypothyreose", "Cushing-Trias", "Schrittmacherfehlfunktion"].map(item => <span key={item}>{item}</span>)}</div><aside className="knowledge-note"><b>Entscheidungslogik</b><p>Stabiler Patient: überwachen, 12-Kanal-EKG, Ursache klären und transportieren. Instabilität oder Asystolierisiko: ohne Verzögerung nach VFA 19 behandeln und parallel reversible Ursachen korrigieren.</p></aside></>)}

    {section("09", "Pharmakologie verstehen", "Atropin und Epinephrin", <><div className="pulmo-compare"><div><small>Atropin</small><h3>Vagusbremse lösen</h3><p>Kompetitive Blockade muskarinischer Acetylcholinrezeptoren. Herzfrequenz und AV-Überleitung können steigen; distale Blöcke sprechen möglicherweise nicht an.</p></div><div><small>Epinephrin</small><h3>Sympathikus stimulieren</h3><p>β₁ steigert Frequenz und Kontraktilität; α erhöht Gefäßtonus und Blutdruck. Die Wirkung kann Ischämie und Arrhythmien verstärken.</p></div></div><div className="pulmo-risk-grid"><div><b>Atropin · Nebenwirkungen</b><p>Tachykardie, Mydriasis, Akkommodationsstörung, Mund-/Hauttrockenheit, Wärmestau und Glaukomanfall.</p></div><div><b>Atropin · Kontraindikationen</b><p>Im vitalen Notfall keine absoluten. Außerhalb dessen sind Tachykardie, Koronarstenose, paralytischer Ileus, Engwinkelglaukom und Überempfindlichkeit relevant.</p></div><div><b>Atropin · Wechselwirkungen</b><p>Anticholinergika, trizyklische Antidepressiva, Antihistaminika, Neuroleptika und manche Antiarrhythmika können die Wirkung verstärken.</p></div><div><b>Epinephrin · Nebenwirkungen</b><p>Tachykardie, Hypertonie, Myokardischämie, Hyperglykämie und Herzrhythmusstörungen.</p></div><div><b>Epinephrin · Wechselwirkungen</b><p>Andere Sympathomimetika verstärken, Betablocker schwächen kardiale Effekte; mehrere Arzneimittel erhöhen das Arrhythmierisiko.</p></div><div><b>Cave Leitungsblock</b><p>Mobitz II oder kompletter AV-Block mit breitem QRS: Pacing früh vorbereiten, weil die Atropinwirkung unzuverlässig sein kann.</p></div></div></>)}

    {section("10", "Thüringen 2026/2027", "VFA 19 und transthorakale Schrittmachertherapie", <><Vfa src="/lessons/instabile-bradykardie/vfa-19-bradykardie.png" alt="Thüringer VFA 19 zur instabilen Bradykardie und transthorakalen Schrittmachertherapie" caption="VFA 19 · Instabile Bradykardie und transthorakale Schrittmachertherapie · Version 2026/27" wide /><div className="pulmo-vfa-flow"><div><span>1</span><b>Atropin</b><small>1 mg i.v.; Erfolg nach zwei Minuten prüfen. Bei nachlassendem Effekt 0,5 mg bis maximal 3 mg.</small></div><div><span>2</span><b>Epinephrin</b><small>1 mg in 500 ml VEL, ein Tropfen pro Sekunde; sobald verfügbar 1 mg in 50 ml NaCl mit 18 ml/h.</small></div><div><span>3</span><b>Schrittmacher</b><small>DEMAND, 70/min, Start 70 mA; in 5-mA-Schritten bis zur 1:1-Ankopplung steigern.</small></div><div><span>4</span><b>Capture sichern</b><small>Zentrale und periphere Pulse synchron prüfen; anschließend 5–10 mA Sicherheitsüberschuss.</small></div></div><div className="brady-med-table" aria-label="Lesetabelle zur Zubereitung von Atropin und Epinephrin"><div className="brady-med-table-head"><span>Medikament</span><span>Ausgangslösung</span><span>Zubereitung</span><span>Ergebnis</span></div><article className="brady-med-row atropine"><header><small>VFA 19 · initial</small><h3>Atropinsulfat</h3><b>1 mg i.v.</b></header><div><small>Ausgangslösung</small><strong>0,5 mg / 1 ml</strong><p>Zwei Ampullen ergeben die Initialdosis.</p></div><div><small>Aufziehen</small><strong>2 ml pur</strong><p>Unverdünnt – kein NaCl hinzufügen.</p></div><div><small>Konzentration</small><strong>0,5 mg/ml</strong><p>Nach zwei Minuten Wirkung prüfen.</p></div></article><article className="brady-med-row epinephrine"><header><small>VFA 19 · bei fehlendem Erfolg</small><h3>Epinephrin</h3><b>1 mg / 1 ml</b></header><div><small>Übergangsinfusion</small><strong>1 ml + 499 ml VEL</strong><p>2 µg/ml · ein Tropfen pro Sekunde.</p></div><div><small>Perfusor</small><strong>1 ml + 49 ml NaCl</strong><p>Gesamtvolumen 50 ml.</p></div><div><small>Perfusorkonzentration</small><strong>20 µg/ml</strong><p>Laufrate nach VFA: 18 ml/h.</p></div></article><p className="brady-med-source"><span>B2A</span>Originalwerte der Anlage B2A · übersichtlich für das Lernen dargestellt.</p></div><aside className="diagnostic-boundary"><span>!</span><div><b>Elektrisches Capture ist nicht genug</b><p>Auf jeden Schrittmacherspike muss ein QRS-Komplex folgen und dazu ein synchroner tastbarer Puls entstehen. Pulslosigkeit wird nach Reanimationsalgorithmus behandelt.</p></div></aside></>)}

    {children}
    <p className="lesson-source">Grundlagen: bereitgestellte Unterlagen „17. instabile Bradykardie“, „Herzrhythmusstörungen“, Anatomie-Skriptum und Thüringer Verfahrensanweisungen 2026/27. Sämtliche Dosierungen und Zubereitungen stammen ausschließlich aus VFA 19 und Anlage B2A.</p>
  </article>;
}
