import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct: boolean];
function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  const shift = (number * 3) % options.length;
  return { id: `instabile-bradykardie-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty };
}

export const instabileBradykardieFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "instabile-bradykardie-card-01", area: "Definition", question: "Wann wird eine Bradykardie zum Notfall?", answer: "Nicht die Frequenz allein, sondern die daraus entstehende hämodynamische Instabilität entscheidet. Thüringen nennt Synkope, Schock, Herzinsuffizienz oder Myokardischämie; die VFA 19 beginnt beim Erwachsenen bei instabiler Bradykardie unter 40/min." },
  { id: "instabile-bradykardie-card-02", area: "Erregungsleitung", question: "Beschreiben Sie den normalen Weg der Erregung.", answer: "Sinusknoten → Vorhofmyokard → AV-Knoten mit physiologischer Verzögerung → His-Bündel → rechte und linke Tawara-Schenkel → Purkinje-Fasern → Ventrikelmyokard." },
  { id: "instabile-bradykardie-card-03", area: "Ionenpumpe", question: "Welche Bedeutung hat die Na⁺/K⁺-ATPase für die elektrische Erregbarkeit?", answer: "Sie transportiert unter ATP-Verbrauch drei Na⁺ aus und zwei K⁺ in die Zelle. So erhält sie die Ionengradienten, auf denen Ruhepotenzial und Aktionspotenzial beruhen. Sie erzeugt nicht jeden Herzschlag, sondern hält dessen elektrische Voraussetzungen aufrecht." },
  { id: "instabile-bradykardie-card-04", area: "AV-Block I", question: "Woran erkennen Sie einen AV-Block I?", answer: "Konstante PQ-Zeit über 200 ms; auf jede P-Welle folgt ein QRS-Komplex. Es besteht eine verzögerte, aber vollständige Überleitung." },
  { id: "instabile-bradykardie-card-05", area: "AV-Block II Wenckebach", question: "Was ist die typische Wenckebach-Periodik?", answer: "Die PQ-Zeit wird schrittweise länger, bis eine P-Welle nicht übergeleitet wird und der QRS-Komplex ausfällt. Danach beginnt die Periodik erneut." },
  { id: "instabile-bradykardie-card-06", area: "AV-Block II Mobitz", question: "Was unterscheidet Mobitz II vom Wenckebach-Block?", answer: "Bei Mobitz II fallen QRS-Komplexe plötzlich aus, ohne vorangehende progressive PQ-Verlängerung. Die Störung liegt häufig im oder unterhalb des His-Bündels, ist oft mit breitem QRS verbunden und besitzt ein höheres Asystolierisiko." },
  { id: "instabile-bradykardie-card-07", area: "AV-Block III", question: "Welche EKG-Logik beweist die AV-Dissoziation?", answer: "P-Wellen und QRS-Komplexe sind jeweils regelmäßig, laufen aber unabhängig voneinander. Es besteht keine feste PQ-Beziehung; die Vorhoffrequenz ist meist höher als die langsame Kammerfrequenz." },
  { id: "instabile-bradykardie-card-08", area: "Ersatzrhythmus", question: "Was verrät die QRS-Breite beim AV-Block III?", answer: "Ein schmaler QRS spricht eher für einen höheren junktionalen Ersatzrhythmus. Ein breiter, deformierter QRS weist eher auf einen distaleren ventrikulären Ersatzrhythmus mit niedrigerer Frequenz und ungünstigerer Prognose hin." },
  { id: "instabile-bradykardie-card-09", area: "Ursachen", question: "Nennen Sie wichtige reversible oder gefährliche Ursachen.", answer: "Hypoxie, Hypothermie, Hyperkaliämie, Azidose, inferiorer Myokardinfarkt, Vagusreiz, Betablocker- oder Kalziumantagonistenintoxikation, Hypothyreose, Hirndruck/Cushing-Trias sowie Erkrankungen des Reizbildungs- oder Reizleitungssystems." },
  { id: "instabile-bradykardie-card-10", area: "Instabilität", question: "Welche Instabilitätskriterien nennt die Thüringer VFA 19?", answer: "Synkope, Schock, Herzinsuffizienz und Myokardischämie." },
  { id: "instabile-bradykardie-card-11", area: "Asystolierisiko", question: "Welche Asystolierisiken nennt die VFA 19?", answer: "Kürzliche Asystolie, AV-Block II Mobitz oder AV-Block III mit breitem QRS-Komplex sowie eine ventrikuläre Pause über drei Sekunden." },
  { id: "instabile-bradykardie-card-12", area: "Atropin", question: "Wie wirkt Atropin bei Bradykardie und wo liegt seine Grenze?", answer: "Atropin blockiert kompetitiv muskarinische Acetylcholinrezeptoren und vermindert den Vaguseinfluss auf Sinus- und AV-Knoten. Bei distalen Leitungsblöcken, besonders Mobitz II und AV-Block III mit breitem QRS, kann es wirkungslos bleiben." },
  { id: "instabile-bradykardie-card-13", area: "Atropin Risiken", question: "Nennen Sie wichtige Nebenwirkungen, Kontraindikationen und Wechselwirkungen von Atropin.", answer: "Möglich sind Tachykardie, Mydriasis, Akkommodationsstörung, Mund-/Hauttrockenheit und Glaukomanfall. Im vitalen Notfall bestehen keine absoluten Kontraindikationen; außerhalb dessen sind unter anderem Tachykardie, Koronarstenose, paralytischer Ileus und Engwinkelglaukom relevant. Anticholinerge Arzneimittel können die Wirkung verstärken." },
  { id: "instabile-bradykardie-card-14", area: "Epinephrin", question: "Warum kann Epinephrin die instabile Bradykardie stabilisieren?", answer: "β₁-Stimulation steigert Herzfrequenz und Kontraktilität; α-Wirkung erhöht den peripheren Widerstand und Blutdruck. Gleichzeitig drohen Tachykardie, Hypertonie, Ischämie und weitere Rhythmusstörungen." },
  { id: "instabile-bradykardie-card-15", area: "Schrittmacher", question: "Was bedeutet elektrische und mechanische 1:1-Ankopplung?", answer: "Elektrisch folgt jedem Schrittmacherspike ein QRS-Komplex. Mechanisch ist dazu ein synchroner zentraler und peripherer Puls nachweisbar. Monitorbild allein beweist keine wirksame Perfusion." },
  { id: "instabile-bradykardie-card-16", area: "VFA", question: "Wie wird die transthorakale Schrittmachertherapie nach VFA 19 eingestellt?", answer: "DEMAND-Modus, Frequenz 70/min, Intensität ab 70 mA in 5-mA-Schritten bis zur 1:1-Ankopplung; danach 5–10 mA Sicherheitsüberschuss und Kontrolle synchroner zentraler und peripherer Pulse." },
  { id: "instabile-bradykardie-card-17", area: "Differenzialdiagnosen", question: "Welche Befunde müssen parallel zur Rhythmusdiagnose gesucht werden?", answer: "ACS, besonders inferiorer Infarkt, Hypoxie, Hypothermie, Hyperkaliämie, Medikamenten- oder Organophosphatintoxikation, Hypothyreose, Hirndruckzeichen, Schrittmacherfehlfunktion und physiologische Sportlerbradykardie." },
  { id: "instabile-bradykardie-card-18", area: "Prüfungsfalle", question: "Warum ist eine Herzfrequenz von 38/min nicht automatisch gleich zu behandeln?", answer: "Ein trainierter, beschwerdefreier Patient kann kompensiert sein; ein Patient mit Synkope, Schock, Ischämie oder Lungenödem ist instabil. Rhythmusform, QRS-Breite, Asystolierisiko und klinische Perfusion entscheiden gemeinsam." },
];

export const instabileBradykardieQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Befunde machen aus einer Bradykardie eine hämodynamisch instabile Situation?", [["Synkope oder akute Bewusstseinsstörung", true], ["Schockzeichen mit Organminderperfusion", true], ["Akute Herzinsuffizienz oder Myokardischämie", true], ["Herzfrequenz 58/min bei beschwerdefreiem Ausdauersportler", false], ["Isoliert verlängerte PQ-Zeit ohne Beschwerden", false]], "Die Thüringer VFA bewertet Instabilität klinisch, nicht allein numerisch.", 1),
  q(2, "Welche Strukturen gehören in korrekter Reihenfolge zum kardialen Erregungsleitungssystem?", [["Sinusknoten vor AV-Knoten", true], ["His-Bündel vor Tawara-Schenkeln", true], ["Purkinje-Fasern leiten in das Ventrikelmyokard", true], ["AV-Knoten erregt zuerst die Vorhöfe", false], ["Tawara-Schenkel liegen vor dem Sinusknoten", false]], "Der normale Leitungsweg erklärt Ort und EKG-Muster eines Blocks.", 2),
  q(3, "Welche Aussagen zur Na⁺/K⁺-ATPase sind korrekt?", [["Sie transportiert drei Na⁺ nach außen und zwei K⁺ nach innen", true], ["Sie verbraucht ATP", true], ["Sie erhält die für Ruhe- und Aktionspotenziale nötigen Ionengradienten", true], ["Sie erzeugt mechanisch den QRS-Komplex", false], ["Sie öffnet ausschließlich während der P-Welle", false]], "Die Pumpe schafft die elektrochemische Grundlage, nicht den einzelnen Impuls.", 2),
  q(4, "Welche EKG-Kriterien sprechen für einen AV-Block I?", [["PQ-Zeit konstant über 200 ms", true], ["Jeder P-Welle folgt ein QRS-Komplex", true], ["Die Überleitung ist verzögert, aber vollständig", true], ["Regelmäßige Ausfälle ohne PQ-Verlängerung", false], ["P-Wellen und QRS-Komplexe laufen unabhängig", false]], "AV-Block I ist eine reine Leitungsverzögerung.", 1),
  q(5, "Welche Beobachtungen kennzeichnen einen AV-Block II Typ Wenckebach?", [["Die PQ-Zeit verlängert sich schrittweise", true], ["Schließlich bleibt ein QRS-Komplex nach einer P-Welle aus", true], ["Nach der Pause beginnt die Periodik erneut", true], ["Die PQ-Zeit bleibt vor jedem Ausfall unverändert", false], ["Es besteht vollständige AV-Dissoziation", false]], "Wenckebach zeigt eine progressive Ermüdung der Überleitung.", 2),
  q(6, "Welche Befunde passen zum AV-Block II Typ Mobitz?", [["Plötzlicher QRS-Ausfall ohne progressive PQ-Verlängerung", true], ["Mögliche 2:1- oder 3:1-Überleitung", true], ["Häufig infra-Hisäre Störung und breiter QRS", true], ["Jede P-Welle wird sicher übergeleitet", false], ["Der Rhythmus ist definitionsgemäß physiologisch", false]], "Mobitz II ist wegen möglicher distaler Leitungsschädigung und Progression gefährlich.", 2),
  q(7, "Welche Aussagen beschreiben einen AV-Block III korrekt?", [["Vorhof- und Kammererregung sind voneinander unabhängig", true], ["P-P- und R-R-Abstände können jeweils regelmäßig sein", true], ["Die Kammerfrequenz ist meist langsamer als die Vorhoffrequenz", true], ["Jede P-Welle besitzt dieselbe PQ-Zeit", false], ["Ein breiter QRS beweist eine normale AV-Überleitung", false]], "Die fehlende feste Beziehung zwischen P und QRS ist entscheidend.", 2),
  q(8, "Welche Schlüsse sind bei einem kompletten AV-Block mit breitem QRS plausibel?", [["Der Ersatzrhythmus kann distal im ventrikulären Leitungssystem entstehen", true], ["Das Asystolierisiko ist erhöht", true], ["Atropin kann unzureichend wirken", true], ["Ein breiter QRS beweist einen harmlosen junktionalen Rhythmus", false], ["Eine Schrittmacherbereitschaft ist unnötig", false]], "Je distaler das Ersatzzentrum, desto breiter und langsamer ist häufig der Rhythmus.", 3),
  q(9, "Welche Ursachen einer Bradykardie müssen aktiv gesucht werden?", [["Inferiorer Myokardinfarkt", true], ["Hypoxie, Hypothermie oder Hyperkaliämie", true], ["Betablocker- oder Kalziumantagonistenintoxikation", true], ["Ausschließlich psychogener Stress", false], ["Jede Bradykardie ist primär ein AV-Block", false]], "Bradykardie ist häufig Ausdruck einer anderen Erkrankung oder Intoxikation.", 2),
  q(10, "Welche Befunde nennt die VFA 19 als Asystolierisiko?", [["Kürzlich dokumentierte Asystolie", true], ["AV-Block II Mobitz oder III mit breitem QRS", true], ["Ventrikuläre Pause über drei Sekunden", true], ["Stabiler Sinusrhythmus mit 55/min", false], ["AV-Block I mit konstanter Überleitung", false]], "Asystolierisiko und Instabilitätskriterien führen in den Therapiepfad.", 2),
  q(11, "Welche Aussagen zur Atropinwirkung sind korrekt?", [["Atropin blockiert muskarinische Acetylcholinrezeptoren", true], ["Der vagale Einfluss auf Sinus- und AV-Knoten nimmt ab", true], ["Herzfrequenz und AV-Überleitung können zunehmen", true], ["Atropin stimuliert direkt ventrikuläre β₁-Rezeptoren", false], ["Atropin beseitigt zuverlässig jeden infra-Hisären Block", false]], "Atropin ist ein Parasympatholytikum, kein direkter Sympathomimetikum-Ersatz.", 2),
  q(12, "Bei welchen Konstellationen ist eine geringe oder fehlende Atropinwirkung besonders plausibel?", [["AV-Block II Mobitz mit breitem QRS", true], ["Kompletter AV-Block mit distal vermutetem Ersatzrhythmus", true], ["Leitungsstörung unterhalb des AV-Knotens", true], ["Vagale Sinusbradykardie", false], ["Karotissinusreaktion ohne strukturellen Block", false]], "Atropin wirkt vor allem am Sinus- und AV-Knoten.", 3),
  q(13, "Welche Angaben zu Atropin sind fachlich stimmig?", [["Tachykardie und Mydriasis sind mögliche Nebenwirkungen", true], ["Mundtrockenheit und Akkommodationsstörung können auftreten", true], ["Anticholinergika können die Wirkung verstärken", true], ["Ein Engwinkelglaukom ist im vitalen Notfall stets ein absolutes Behandlungsverbot", false], ["Atropin senkt regelhaft die Herzfrequenz", false]], "Im vitalen Notfall bestehen keine absoluten Kontraindikationen; Risiken bleiben dennoch prüfungsrelevant.", 3),
  q(14, "Welche Wirkungen von Epinephrin helfen bei instabiler Bradykardie?", [["β₁-vermittelte Steigerung der Herzfrequenz", true], ["β₁-vermittelte Zunahme der Kontraktilität", true], ["α-vermittelte Vasokonstriktion und Blutdruckstützung", true], ["Selektive Blockade muskarinischer Rezeptoren", false], ["Sichere Unterdrückung aller ventrikulären Arrhythmien", false]], "Epinephrin erhöht Chronotropie, Inotropie und Gefäßtonus, kann aber Arrhythmien fördern.", 2),
  q(15, "Welche Risiken und Wechselwirkungen sind bei Epinephrin relevant?", [["Tachykardie, Hypertonie und Herzrhythmusstörungen", true], ["Betablocker können kardiale Wirkungen abschwächen", true], ["Andere Sympathomimetika können die Wirkung verstärken", true], ["Epinephrin verhindert zuverlässig Myokardischämie", false], ["Atropin schließt arrhythmogene Nebenwirkungen aus", false]], "Wirkung und Nebenwirkung entstehen aus derselben sympathomimetischen Stimulation.", 3),
  q(16, "Welche Schritte der VFA 19 sind richtig zugeordnet?", [["Initial 1 mg Atropin i.v.", true], ["Nach zwei Minuten wird der Erfolg beurteilt", true], ["Bei nachlassendem Effekt 0,5 mg Atropin bis maximal 3 mg", true], ["Epinephrin wird als unverdünnter 1-mg-Bolus gegeben", false], ["Schrittmacherbeginn erfolgt grundsätzlich im FIX-Modus", false]], "Dosierungen und Zeitabstände stammen ausschließlich aus der Thüringer VFA 19.", 3),
  q(17, "Welche Aussagen zur Epinephrinzubereitung nach VFA 19 und B2A treffen zu?", [["1 mg in 500 ml VEL ergibt 2 µg/ml", true], ["1 mg in 50 ml NaCl 0,9 % ergibt 20 µg/ml", true], ["Der Perfusor läuft laut VFA mit 18 ml/h", true], ["Die Bradykardieinfusion enthält 1 mg in 10 ml", false], ["Die Tropfgeschwindigkeit beträgt zehn Tropfen pro Sekunde", false]], "Die VFA unterscheidet Übergangsinfusion und Perfusorzubereitung.", 3),
  q(18, "Welche Einstellungen gehören zur transthorakalen Schrittmachertherapie nach VFA 19?", [["DEMAND-Modus", true], ["Frequenz 70/min", true], ["Beginn bei 70 mA und Steigerung in 5-mA-Schritten", true], ["Abbruch unmittelbar nach dem ersten Spike", false], ["Feste Intensität von 20 mA unabhängig vom Capture", false]], "Die Intensität wird bis zur 1:1-Ankopplung titriert.", 2),
  q(19, "Woran erkennen Sie eine wirksame Schrittmachertherapie?", [["Jedem Spike folgt ein QRS-Komplex", true], ["Zentraler und peripherer Puls sind synchron", true], ["Nach Capture wird ein Sicherheitsüberschuss eingestellt", true], ["Spikes ohne QRS beweisen mechanisches Capture", false], ["Ein QRS ohne tastbaren Puls genügt als Erfolg", false]], "Elektrisches und mechanisches Capture müssen getrennt geprüft werden.", 3),
  q(20, "Welche Maßnahmen gehören zur frühen Versorgung einer instabilen Bradykardie?", [["cABCDE und vollständiges Monitoring einschließlich 12-Kanal-EKG", true], ["i.v.-Zugang und Reanimationsbereitschaft", true], ["Reversible Ursachen parallel behandeln", true], ["EKG-Auswertung erst nach vollständiger medikamentöser Therapie", false], ["Bei Synkope ohne weitere Prüfung abwarten", false]], "Rhythmustherapie und Ursachenbehandlung laufen parallel.", 2),
  q(21, "Welche Befunde sprechen eher für eine physiologische als für eine instabile Bradykardie?", [["Trainierter Patient ohne Beschwerden", true], ["Normale Organperfusion und stabiler Blutdruck", true], ["Adäquater Frequenzanstieg unter Belastung", true], ["Synkope mit kaltschweißigem Schockbild", false], ["Lungenödem und Thoraxschmerz", false]], "Frequenz und klinische Wirkung müssen zusammen beurteilt werden.", 2),
  q(22, "Ein EKG zeigt regelmäßige P-Wellen, regelmäßige langsame QRS-Komplexe und wechselnde PQ-Abstände. Welche Schlüsse sind richtig?", [["Eine AV-Dissoziation ist wahrscheinlich", true], ["Ein AV-Block III muss erwogen werden", true], ["QRS-Breite hilft bei der Lokalisation des Ersatzrhythmus", true], ["Das Muster entspricht sicher einem AV-Block I", false], ["Die regelmäßigen P-Wellen schließen einen kompletten Block aus", false]], "Zwei unabhängige regelmäßige Rhythmen sind typisch für den kompletten AV-Block.", 3),
  q(23, "Ein EKG zeigt gleichbleibende PQ-Zeiten, dann plötzlich eine nicht übergeleitete P-Welle. Welche Aussagen sind richtig?", [["Das Muster passt zu Mobitz II", true], ["Ein infra-Hisärer Block ist möglich", true], ["Breiter QRS und Synkope erhöhen die Dringlichkeit", true], ["Eine progressive PQ-Verlängerung ist zwingend", false], ["Das Muster beweist Wenckebach", false]], "Der unvermittelte Ausfall unterscheidet Mobitz II von Wenckebach.", 3),
  q(24, "Welche vollständige Prüfungsantwort verbindet Befund und Therapie korrekt?", [["Instabilität und Asystolierisiko werden vor der Therapieentscheidung geprüft", true], ["AV-Block-Typ und QRS-Breite beeinflussen die Erwartung an Atropin", true], ["Bei fehlendem Erfolg folgen Epinephrin und transthorakales Pacing nach VFA", true], ["Eine niedrige Herzfrequenz ersetzt die Suche nach reversiblen Ursachen", false], ["Elektrisches Capture macht die Pulskontrolle überflüssig", false]], "Eine starke Antwort verbindet Klinik, EKG-Lokalisation, VFA und mechanische Erfolgskontrolle.", 3),
];
