import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [string, boolean];
function q(n: number, prompt: string, options: Option[], source: string): ThoraxtraumaChoiceQuestion {
  const shift = n % options.length;
  return { id: `krampfanfall-kind-q-${String(n).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty: 3 };
}

export const krampfanfallKindQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Ein 20 Monate altes Kind mit Fieber krampft seit sechs Minuten generalisiert. Welche Einschätzungen sind richtig?", [["Ein anhaltender konvulsiver Anfall ist zeitkritisch", true], ["Atemweg und Beatmungsbereitschaft sind wichtig", true], ["Das Körpergewicht muss für VFA 30 geklärt werden", true], ["Die Fieberhöhe allein ersetzt die Anfallsbehandlung", false], ["Ein Fieberkrampf beweist bereits Epilepsie", false]], "VFA 30 behandelt den laufenden Anfall gewichtsbasiert; Fieber erklärt ihn nicht abschließend."),
  q(2, "Welche Befunde sprechen gegen die vorschnelle Einordnung als unkomplizierten Fieberkrampf?", [["Einseitiger Anfallsbeginn", true], ["Wiederholung innerhalb von 24 Stunden", true], ["Anhaltende Vigilanzstörung nach dem Anfall", true], ["Kurzer generalisierter Einzelanfall mit vollständiger Erholung", false], ["Eine bekannte erhöhte Temperatur allein", false]], "Fokalität, Wiederholung und fehlende Erholung verlangen erweiterte Ursachenabklärung."),
  q(3, "Ein fieberndes Kind hatte einen kurzen Anfall, ist nun wach. Welche Aussagen treffen zu?", [["BZ und Temperatur gehören zur Beurteilung", true], ["Die Erholung muss im Verlauf dokumentiert werden", true], ["Fieber senkt die Krampfschwelle, schließt andere Ursachen aber nicht aus", true], ["Nach sistiertem Anfall ist Midazolam routinemäßig vorbeugend angezeigt", false], ["Antipyretika verhindern ein Rezidiv sicher", false]], "Bei sistiertem Anfall stehen cABCDE, Ursache und Erholungsverlauf im Vordergrund."),
  q(4, "Welche Angaben von Bezugspersonen sind für eine kindliche Anfallsübergabe besonders wertvoll?", [["Beobachteter Beginn und Dauer", true], ["Fokale Zeichen oder Blickwendung", true], ["Gewicht und bereits gegebene Medikamente", true], ["Nur die aktuell gemessene Temperatur", false], ["Ausschließlich die frühere Diagnose Fieberkrampf", false]], "Zeitachse, Semiologie, Gewicht und Medikation entscheiden über Einordnung und sichere Behandlung."),
  q(5, "Ein Kind unter 30 kg krampft noch. Welche Wege sieht VFA 30 situativ vor?", [["Diazepam rektal", true], ["Midazolam intranasal mit MAD", true], ["Wahl nach situativer Eignung", true], ["Beide Benzodiazepine gleichzeitig als Standard", false], ["Midazolam 3 mg i.v. nach Erwachsenen-VFA 29 als Routine", false]], "VFA 30 wählt rektal oder alternativ nasal; Erwachsenen-VFA 29 ist nicht der pädiatrische Standardweg."),
  q(6, "Ein 2-jähriges Kind wiegt 12 kg. Der rektale Weg ist situativ günstig. Was passt zur Thüringer VFA 30?", [["Diazepam-Rectiole 5 mg", true], ["Wirkstoff, Dosis und Applikationsweg vor Gabe prüfen", true], ["Nach der Gabe Atmung und Verlauf überwachen", true], ["Diazepam-Rectiole 10 mg wegen jeder Fiebererhöhung", false], ["Die Dosis ohne Gewichtskontrolle aus dem Erwachsenenpfad übernehmen", false]], "VFA 30: bis 3 Jahre und <15 kg rektal 5 mg; engmaschige Re-Evaluation bleibt erforderlich."),
  q(7, "Ein 4-jähriges Kind wiegt 20 kg. Der rektale Weg wird gewählt. Welche Aussagen sind korrekt?", [["Die VFA nennt 10 mg Diazepam rektal", true], ["Der Verlauf wird nach 10 Minuten neu beurteilt", true], ["Eine zweite Gabe ist nur bei andauerndem oder erneutem Anfall vorgesehen", true], ["Sofort zwei Rectiolen gleichzeitig verabreichen", false], ["Die Fiebersenkung ersetzt die Antikonvulsion", false]], "VFA 30: ab 3 Jahren und >15 kg 10 mg rektal; Wiederholung höchstens einmal nach 10 Minuten bei Bedarf."),
  q(8, "Was ist bei genau 15 kg oder an der unklaren Alters-/Gewichtsgrenze der rektalen VFA-Zeilen wichtig?", [["Die VFA benennt <15 kg und >15 kg, aber nicht exakt 15 kg", true], ["Grenzfälle erfordern Abgleich mit Original-VFA und ärztliche Rücksprache", true], ["Ein numerischer Grenzfall rechtfertigt keine erfundene Standarddosis", true], ["Die 10-mg-Dosis ist aus dem Wortlaut zwingend für exakt 15 kg", false]], "Die Grenzformulierung der VFA 30 enthält keine explizite 15-kg-Zuordnung."),
  q(9, "Welche Aussagen zur intranasalen Midazolam-Zubereitung der VFA 30 stimmen?", [["Die Ampulle enthält 15 mg in 3 ml", true], ["Die Konzentration beträgt 5 mg/ml", true], ["B2A führt sie unverdünnt", true], ["Die Kinder-VFA nutzt routinemäßig die i.v.-Ampulle 5 mg/5 ml für MAD", false], ["Mit 9 ml NaCl wird für i.n. verdünnt", false]], "VFA 30/B2A: 15 mg/3 ml = 5 mg/ml, unverdünnt, intranasal über MAD."),
  q(10, "Ein 20-kg-Kind benötigt Midazolam i.n. Welche Volumenangaben sind bei der VFA-Tabelle richtig?", [["Die Tabelle nennt 0,9 ml Aufziehvolumen", true], ["Das Volumen enthält 0,1 ml MAD-Totraum", true], ["Die Tabelle ist gerundet und altersangepasst", true], ["0,9 ml sind zwingend gleich der tatsächlich applizierten Wirkstoffmenge ohne Totraum", false], ["Die Erwachsenendosis von 2 ml gilt unabhängig vom Gewicht", false]], "VFA 30: 20 kg → 0,9 ml Tabellenvolumen; 0,1 ml Totraum wurde mitgerechnet."),
  q(11, "Ein 10-kg-Kind soll nach VFA 30 Midazolam i.n. erhalten. Welche Aussagen passen?", [["Die Gewichtstabelle nennt 0,4 ml", true], ["Das Tabellenvolumen ist nicht einfach die rechnerische Nettowirkstoffmenge", true], ["Bei kleiner Dosis kann ein Nasenloch genügen", true], ["Es sind 4 ml aufzuziehen, weil 0,4 ml zu wenig erscheinen", false]], "Die VFA-Tabelle enthält 0,1 ml MAD-Totraum und nennt für 10 kg 0,4 ml."),
  q(12, "Ein Kind krampft nach erster VFA-30-Gabe weiter. Welche Schritte sind nach Ablauf von 10 Minuten sachgerecht?", [["Anfall und Atmung erneut beurteilen", true], ["Bei andauerndem oder wiederholtem Anfall maximal eine Wiederholung nach VFA prüfen", true], ["Fortbestehende Ursache und Transportpriorität neu bewerten", true], ["Ohne Re-Evaluation beliebig oft Benzodiazepine geben", false], ["Nur fiebersenkende Maßnahmen als Ersatz durchführen", false]], "VFA 30 verbindet die 10-Minuten-Kontrolle mit maximal einer Wiederholung bei weiterem/erneutem Anfall."),
  q(13, "Welche Kombinationen aus Fiebermanagement und Anfallsbehandlung sind fachlich richtig?", [["Fiebersenkung erfolgt im VFA-Pfad nach Kontrolle des Anfalls", true], ["Antipyretika dienen der Fieber-/Beschwerdebehandlung, nicht als sichere Rezidivprophylaxe", true], ["Bei >38,5 °C sieht VFA 30 nichtmedikamentöse Maßnahmen vor", true], ["Ein Suppositorium beendet einen laufenden tonisch-klonischen Anfall zuverlässig", false]], "VFA 30 trennt akute Anfallsbehandlung und Fiebersenkung; Leitlinien belegen keinen verlässlichen Rezidivschutz durch Antipyretika."),
  q(14, "Welche Paracetamol-Zuordnungen stehen im Fieberzweig der VFA 30?", [["Bis 1 Jahr: 125 mg Suppositorium", true], ["1 bis 6 Jahre: 250 mg Suppositorium", true], [">6 Jahre: 500 mg Suppositorium", true], ["Alle Altersgruppen erhalten routinemäßig 500 mg", false], ["Paracetamol ist der erste Schritt bei laufendem Krampf", false]], "Die VFA 30 gibt im Fieberzweig drei altersbezogene Paracetamol-Suppositorien an."),
  q(15, "Welche Ibuprofen-Zuordnungen stehen im Fieberzweig der VFA 30?", [["3 Monate bis 2 Jahre: 60 mg Suppositorium", true], ["Ab 2 Jahren: 125 mg Suppositorium", true], ["Ibuprofen ist eine Alternative zu Paracetamol, nicht die parallele Standardkombination", true], ["Jedes Kind unter 30 kg erhält automatisch 125 mg", false]], "Die VFA nennt altersabhängig 60 oder 125 mg und stellt Paracetamol und Ibuprofen als Alternativen dar."),
  q(16, "Ein Kind mit Fieber ist nach dem Anfall schwer weckbar und hat Nackensteife. Welche Entscheidungen sind angemessen?", [["ZNS-Infektion muss mitgedacht werden", true], ["Vitalfunktionen und Vigilanz wiederholt prüfen", true], ["Zeitkritische klinische Abklärung und geeigneter Transport sind erforderlich", true], ["Die Diagnose unkomplizierter Fieberkrampf ist bereits sicher", false], ["Ein einmaliger normaler BZ schließt Meningitis aus", false]], "Fieber mit fehlender Erholung oder Meningismus ist ein Warnmuster für schwere Infektion."),
  q(17, "Welche Ursachen sind bei einem kindlichen Krampfanfall ohne klare Fiebererklärung präklinisch relevant?", [["Hypoglykämie oder andere Stoffwechselstörung", true], ["Intoxikation", true], ["SHT oder intrakranielle Blutung", true], ["ZNS-Infektion", true], ["Eine Epilepsie ist bei jedem Erstereignis bewiesen", false]], "Ein erster oder atypischer Anfall verlangt breite, rettungsdienstlich relevante Ursachensuche."),
  q(18, "Ein 28-kg-Kind erhält intranasales Midazolam nach VFA 30. Was ist richtig?", [["Die Tabelle nennt 1,3 ml aufzuziehendes Volumen", true], ["Die i.n.-Konzentration ist 5 mg/ml", true], ["Gewicht und MAD-Totraum sind in der Tabellenanwendung zu beachten", true], ["1,3 ml entsprechen ohne weiteres exakt der applizierten Netto-Wirkstoffmenge", false]], "VFA 30 nennt für 28 kg 1,3 ml einschließlich 0,1 ml MAD-Totraum."),
  q(19, "Welche Sicherheitsaspekte sind nach Diazepam oder Midazolam beim Kind zu beachten?", [["Atemdepression oder Hypoventilation ist möglich", true], ["Beatmungsbereitschaft und passendes Material bleiben nötig", true], ["Anfallsende beweist keine ausreichend stabile Ventilation", true], ["Eine Besserung der Zuckungen erlaubt den Verzicht auf Monitoring", false]], "Benzodiazepine und postiktaler Zustand können Atmung und Vigilanz beeinträchtigen; VFA 30 fordert Überwachung und Transport."),
  q(20, "Welche Aussagen zur Einordnung kindlicher Fieberkrämpfe sind belastbar?", [["Ein Fieberkrampf tritt typischerweise im Kleinkindalter auf", true], ["Ein einzelner Fieberkrampf ist nicht automatisch Epilepsie", true], ["Fokalität oder Wiederholung verändert die Risikoeinschätzung", true], ["Ein rascher Temperaturanstieg ist immer die alleinige gesicherte Ursache", false], ["Fiebersenkung verhindert jeden weiteren Anfall", false]], "Altersbereich, Anfallsmuster und Differenzialdiagnosen zählen; Auslösung und Rezidivprophylaxe dürfen nicht vereinfacht werden."),
  q(21, "Ein Säugling atmet nach einem Anfall flach und die Sättigung fällt. Welche Folgerungen sind richtig?", [["Die Atmung muss unmittelbar erneut beurteilt und bei Bedarf unterstützt werden", true], ["Eine altersgerechte Neutralposition kann einer Atemwegsverlegung durch Halsbeugung entgegenwirken", true], ["Säuglinge können wegen geringerer Sauerstoffreserve schneller desaturieren", true], ["Mit dem Ende der Zuckungen ist die Ventilation ausreichend gesichert", false], ["Der Kopf sollte routinemäßig maximal überstreckt werden", false]], "Kindliche Atemwegsanatomie und Sauerstoffreserve erfordern frühe Atemwegskontrolle; ein sistierter Anfall ersetzt kein cABCDE."),
  q(22, "Welche kindlichen Besonderheiten verändern die präklinische Beurteilung nach einem Krampfanfall?", [["Herz- und Atemfrequenz müssen altersbezogen interpretiert werden", true], ["Bezugspersonen können Abweichungen vom üblichen Verhalten besonders gut benennen", true], ["Anfallsbeginn, fokale Zeichen und bereits gegebene Notfallmedikamente gehören zur Fremdanamnese", true], ["Ein einzelner Erwachsenen-Grenzwert für Atemfrequenz gilt für jedes Kindesalter", false], ["Die Anfallsdauer beginnt erst mit dem Eintreffen des Rettungsdienstes", false]], "Altersabhängige Vitalwerte und eine genaue Fremdanamnese sind entscheidend; die gesamte Anfallsdauer einschließlich der Zeit vor Eintreffen zählt."),
  q(23, "Bei einem weiter krampfenden Kind ist das Gewicht unbekannt. Welche Vorgehensweisen erhöhen die Arzneimittelsicherheit?", [["Gewicht bei Bezugspersonen erfragen oder mit einer pädiatrischen Hilfe schätzen", true], ["Den ermittelten Wert mit der Kinder-VFA und dem vorgesehenen Applikationsweg abgleichen", true], ["Eine bereits erfolgte Benzodiazepin-Gabe in die weitere Entscheidung einbeziehen", true], ["Die Erwachsenendosis unabhängig vom Gewicht übernehmen", false], ["Eine unklare Gewichtsangabe ohne Gegenprüfung als exakt behandeln", false]], "Kindliche Dosierung ist gewichts- und VFA-bezogen; bereits verabreichte Benzodiazepine müssen mitgezählt werden."),
  q(24, "Ein vierjähriges Kind hat nach einem Anfall Puls 140/min, Atemfrequenz 29/min und systolisch 85 mmHg. Welche Aussagen sind fachlich tragfähig?", [["Die Werte liegen innerhalb der breiten altersbezogenen RCH-Orientierungsbereiche", true], ["Ein einzelner altersüblicher Blutdruck schließt eine beginnende Kreislaufstörung nicht sicher aus", true], ["Atemarbeit, Hautdurchblutung, Vigilanz und der Verlauf müssen mitbeurteilt werden", true], ["Puls 140/min ist allein wegen des Erwachsenen-Ruhebereichs zwingend pathologisch", false], ["Nach einmaliger Messung ist eine erneute Vitalzeichenkontrolle entbehrlich", false]], "Für vier Jahre nennt RCH breite Bereiche; wichtiger als isolierte Grenzwerte sind klinischer Zustand und Messverlauf."),
  q(25, "Welche anatomisch-physiologischen Unterschiede zum Erwachsenen sind beim krampfenden Säugling besonders relevant?", [["Eine relativ größere Zunge kann den Atemweg leichter verlegen", true], ["Der größere Hinterkopf kann in Rückenlage eine ungünstige Halsbeugung fördern", true], ["Höherer Sauerstoffbedarf und geringere Reserve begünstigen rasche Desaturation", true], ["Der kleine Atemweg toleriert eine gleich starke Schleimhautschwellung besser als beim Erwachsenen", false], ["Ein maximal überstreckter Kopf ist unabhängig vom Alter die Standardposition", false]], "Die kindliche Atemwegsanatomie und Sauerstoffreserve verlangen altersgerechte Lagerung und wiederholte Atemkontrolle."),
];

export const krampfanfallKindFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "krampfanfall-kind-card-01", area: "Definition", question: "Definieren Sie einen epileptischen Anfall beim Kind und erklären Sie, warum ein Fieberkrampf nicht automatisch Epilepsie bedeutet.", answer: "Vorübergehende Funktionsstörung durch überschießende oder synchronisierte neuronale Aktivität. Fieber kann einen akut symptomatischen Anfall begünstigen; ein Einzelereignis beweist keine chronische Epilepsie." },
  { id: "krampfanfall-kind-card-02", area: "Neurophysiologie", question: "Leiten Sie die Reizweiterleitung von Axon über Synapse zur nächsten Nervenzelle her und benennen Sie die Rolle von Glutamat und GABA.", answer: "Das Aktionspotenzial läuft elektrisch am Axon entlang; am Endknöpfchen werden Transmitter freigesetzt, die postsynaptische Rezeptoren beeinflussen. Glutamat wirkt überwiegend erregend, GABA hemmend. Eine veränderte Balance erhöht die Erregbarkeit." },
  { id: "krampfanfall-kind-card-03", area: "Fieberkrampf", question: "Welche Merkmale sprechen für einen einfachen Fieberkrampf und welche Befunde verlangen erweiterte Abklärung?", answer: "Typisch: Alter 6 Monate bis 5 Jahre, generalisierter Anfall unter 15 Minuten, einmal in 24 Stunden, vollständige Erholung. Fokalität, Wiederholung, anhaltende Vigilanzstörung oder Meningitiszeichen sind Warnbefunde." },
  { id: "krampfanfall-kind-card-04", area: "Erstmaßnahmen", question: "Priorisieren Sie die ersten rettungsdienstlichen Schritte bei einem fortdauernden Anfall im Kleinkindalter.", answer: "Beginn und Dauer erfassen, Verletzungsschutz ohne Fixieren, cABCDE, Atemwegs-/Beatmungsbereitschaft, BZ und Temperatur, Gewicht mit kognitiver Hilfe bestimmen, Monitoring; bei fortdauerndem Anfall VFA 30 und situativen Applikationsweg wählen." },
  { id: "krampfanfall-kind-card-05", area: "VFA 30", question: "Ein 2-jähriges Kind wiegt 12 kg. Welches rektale Arzneimittel und welche Dosis nennt VFA 30?", answer: "Diazepam 5 mg rektal als Rectiole, weil es in der VFA-Gruppe bis 3 Jahre und <15 kg liegt. Gabe nur bei andauerndem Anfall und situativ geeignetem rektalem Weg; Atmung überwachen." },
  { id: "krampfanfall-kind-card-06", area: "VFA 30", question: "Ein 4-jähriges Kind wiegt 20 kg. Wie lautet der rektale Pfad und wann darf erneut behandelt werden?", answer: "Diazepam 10 mg rektal nach VFA 30. Nach 10 Minuten Anfall und Atmung erneut beurteilen; bei anhaltendem oder erneutem Anfall maximal eine Wiederholung gemäß VFA." },
  { id: "krampfanfall-kind-card-07", area: "B2A / MAD", question: "Warum ist das Midazolam-Tabellenvolumen bei 20 kg nicht einfach 0,2 mg/kg geteilt durch 5 mg/ml?", answer: "VFA 30 nennt 0,9 ml Aufziehvolumen für 20 kg und rechnet bereits 0,1 ml MAD-Totraum ein; die Tabelle ist zusätzlich gerundet und altersangepasst. B2A: 15 mg/3 ml = 5 mg/ml, unverdünnt." },
  { id: "krampfanfall-kind-card-08", area: "VFA 30", question: "Welche intranasalen Tabellenvolumina gelten bei 10 kg und 28 kg und was wird dabei jeweils berücksichtigt?", answer: "10 kg: 0,4 ml; 28 kg: 1,3 ml. Beide sind aufzuziehende Volumina aus der VFA-Tabelle mit 0,1 ml zusätzlichem MAD-Totraum; Konzentration 5 mg/ml, unverdünnt." },
  { id: "krampfanfall-kind-card-09", area: "Fieber", question: "Trennen Sie Anfallsbehandlung und Fiebersenkung nach VFA 30. Welche Prüfungsfalle besteht bei Antipyretika?", answer: "Zuerst laufenden Anfall und Vitalfunktionen behandeln. Bei >38,5 °C nach Anfallskontrolle nichtmedikamentöse Fiebersenkung und Paracetamol- oder Ibuprofen-Suppositorium nach VFA. Antipyretika verhindern weitere Fieberkrämpfe nicht zuverlässig." },
  { id: "krampfanfall-kind-card-10", area: "Fieber", question: "Nennen Sie die Paracetamol- und Ibuprofen-Suppositorien aus dem Fieberzweig der VFA 30 altersbezogen.", answer: "Paracetamol: bis 1 Jahr 125 mg, 1–6 Jahre 250 mg, >6 Jahre 500 mg. Ibuprofen alternativ: 3 Monate–2 Jahre 60 mg, ab 2 Jahren 125 mg. Original-VFA, Präparat und Kontraindikationen vor Gabe prüfen." },
  { id: "krampfanfall-kind-card-11", area: "Differenzialdiagnose", question: "Ein fieberndes Kind ist nach dem Krampf nicht wach und zeigt Nackensteife. Begründen Sie die weitere Entscheidung.", answer: "Nicht vorschnell unkomplizierter Fieberkrampf: ZNS-Infektion/Sepsis und andere Ursachen bedenken. cABCDE, BZ, Vital-/Vigilanzverlauf, ärztliche Unterstützung, zeitkritische klinische Abklärung und Monitoring/Transport." },
  { id: "krampfanfall-kind-card-12", area: "Übergabe", question: "Welche Angaben müssen nach zwei kindlichen Anfällen und einer Midazolamgabe in die strukturierte Übergabe?", answer: "Zeitpunkte, Dauer, fokaler oder bilateraler Beginn, Vigilanz zwischen den Anfällen, Gewicht, BZ, Temperatur, Vitalverlauf, Midazolam-Ampulle/Konzentration, Tabellenvolumen inklusive MAD-Totraum, Applikationsweg und Uhrzeit, Wirkung und Atemwegssituation." },
  { id: "krampfanfall-kind-card-13", area: "Kindliche Besonderheiten", question: "Warum kann ein Säugling nach einem Krampfanfall rascher desaturieren und was folgt daraus für die Atemwegssicherung?", answer: "Relativ hoher Sauerstoffverbrauch und geringere Reserve begünstigen rasche Desaturation. Der größere Hinterkopf kann in Rückenlage den Hals beugen. Atemweg altersgerecht neutral lagern, Atmung und Sättigung wiederholt prüfen und passende Beatmung bereithalten." },
  { id: "krampfanfall-kind-card-14", area: "Kindliche Besonderheiten", question: "Welche drei Informationen aus der Fremdanamnese beeinflussen die Entscheidung beim krampfenden Kind besonders und warum?", answer: "Beginn und gesamte Dauer bestimmen die Zeitkritik; fokale Zeichen verändern die Differenzialdiagnose; bereits verabreichte Benzodiazepine beeinflussen die weitere Arzneimittelentscheidung. Eltern können außerdem Normalzustand und Gewicht beschreiben." },
  { id: "krampfanfall-kind-card-15", area: "Vitalzeichen", question: "Vergleichen Sie Herz- und Atemfrequenz eines einjährigen mit denen eines älteren Jugendlichen. Warum darf ein Einzelwert nach Krampfanfall nicht isoliert interpretiert werden?", answer: "RCH-Orientierungsbereiche bei kranken Kindern: 1 Jahr Herzfrequenz 105–150/min, Atemfrequenz 20–45/min; ab 17 Jahren 60–115/min und 14–25/min. Fieber, Schmerz, Angst und postiktaler Zustand beeinflussen Werte. Atemarbeit, Perfusion, Bewusstsein und wiederholte Messungen sind entscheidend." },
  { id: "krampfanfall-kind-card-16", area: "Körpervergleich", question: "Nennen Sie vier Unterschiede des kindlichen Körpers zum Erwachsenen, die die Versorgung nach einem Krampfanfall beeinflussen.", answer: "Kleinerer Atemweg mit relativ größerer Zunge und beim Säugling größerem Hinterkopf; höherer Sauerstoffverbrauch bei geringerer Reserve; Herzzeitvolumen besonders bei Säuglingen stark frequenzabhängig und Hypotonie als spätes Warnzeichen; größere relative Oberfläche und kleinere Glykogenspeicher mit Wärmeverlust- und Hypoglykämierisiko." },
];
