import { useState, type ComponentType, type ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

const midazolamTable = [
  [3, 0.2], [6, 0.3], [10, 0.4], [14, 0.6], [16, 0.7], [18, 0.8],
  [20, 0.9], [22, 1.0], [24, 1.1], [26, 1.2], [28, 1.3],
] as const;

function MidazolamChildSyringe() {
  const [selected, setSelected] = useState<number>(20);
  const volume = midazolamTable.find(([weight]) => weight === selected)?.[1] ?? 0.9;
  const fluidWidth = volume / 2 * 470;
  return <div className="syringe-panel child-syringe-panel">
    <div className="syringe-panel-heading"><div><small>Gewichtstabelle der VFA 30</small><h3>Midazolam i.n. · Aufziehvolumen</h3></div><span>15 mg / 3 ml · unverdünnt</span></div>
    <p>Das Tabellenvolumen enthält bereits <b>0,1 ml für den Totraum des MAD</b> und ist gerundet. Es ist deshalb nicht identisch mit dem rechnerischen Wirkstoffvolumen von 0,2 mg/kgKG.</p>
    <div className="child-weight-picker" role="group" aria-label="Körpergewicht aus VFA-Tabelle wählen">{midazolamTable.map(([weight]) => <button type="button" key={weight} aria-pressed={selected === weight} className={selected === weight ? "active" : ""} onClick={() => setSelected(weight)}>{weight} kg</button>)}</div>
    <div className="syringe-readout"><div><small>Körpergewicht</small><b>{selected} kg</b></div><div><small>Aus VFA-Tabelle aufziehen</small><b>{volume.toFixed(1).replace(".", ",")} ml</b></div><div><small>NaCl 0,9 %</small><b>0 ml · pur</b></div></div>
    <div className="syringe-drawing" role="img" aria-label={`Schematische 2-ml-Spritze mit ${volume.toFixed(1).replace(".", ",")} ml unverdünntem Midazolam als Aufziehvolumen einschließlich MAD-Totraum`}>
      <svg viewBox="0 0 650 175" xmlns="http://www.w3.org/2000/svg">
        <path d="M29 73H78V103H29Z" fill="#c5dee0" stroke="#6d9297" strokeWidth="2"/><circle cx="17" cy="88" r="4" fill="#80bec0"/><text x="11" y="128" fontSize="11" fontWeight="700" fill="#496a70">MAD</text>
        <rect x="88" y="63" width="470" height="50" rx="8" fill="#fbffff" stroke="#9ab2b7" strokeWidth="3"/>
        <rect x="90" y="65" width={Math.max(0, fluidWidth - 3)} height="46" rx="4" fill="#3d9d90"/>
        <path d={`M${88 + fluidWidth} 61V115`} stroke="#214950" strokeWidth="6"/><path d={`M${88 + fluidWidth} 88H604M604 67V109`} stroke="#8b9da1" strokeWidth="5"/>
        {Array.from({ length: 21 }, (_, index) => { const x = 88 + index * 23.5; const major = index % 5 === 0; return <g key={index}><path d={`M${x} 63V${major ? 80 : 72}`} stroke="#244a54" strokeWidth={major ? 2 : 1.2}/>{major && <text x={x} y="48" textAnchor="middle" fontSize="15" fontWeight="700" fill="#244a54">{(index / 10).toFixed(1).replace(".", ",")}</text>}</g>; })}
        <text x="560" y="145" textAnchor="end" fontSize="15" fontWeight="700" fill="#496a70">ml-Skala · 0–2 ml</text>
      </svg>
    </div>
    <p className="syringe-caution">Schematische Lernansicht, keine Vorgabe für eine bestimmte Spritzengröße. Situativen Applikationsweg wählen; bei kleiner Dosis kann nach VFA 30 ein Nasenloch genügen. Die Tabelle zeigt auch 30 kg, obwohl die Überschrift „&lt; 30 kg“ lautet; bei exakt 30 kg Rücksprache halten. Medikament, Gewicht, Konzentration und Originaltabelle vor Anwendung prüfen.</p>
  </div>;
}

export default function KrampfanfallKindLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>Krampfanfall · Kind unter 30 kg</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;
  return <article className="lesson-article rippenfraktur-lesson krampfanfall-lesson krampfanfall-kind-lesson">
    <div className="lesson-intro"><p className="lead">Beim Kind sind Anfallsdauer, Atmung, Gewicht und mögliche Ursachen entscheidend. Ein Fieberkrampf ist häufig, aber Fieber erklärt nicht automatisch jeden Krampfanfall.</p></div>
    {section("01", "Definition", <><p>Ein epileptischer Anfall ist eine vorübergehende Funktionsstörung des Gehirns durch überschießende oder ungewöhnlich stark synchronisierte elektrische Aktivität. Sie kann umschrieben oder in beidseitigen Netzwerken beginnen und motorische, sensible oder vegetative Auffälligkeiten auslösen.</p><div className="pulmo-compare"><div><small>Einzelner Anfall</small><h3>Nicht automatisch Epilepsie</h3><p>Auch Fieber, Hypoglykämie, Infektion, Intoxikation oder eine Hirnverletzung können einen Anfall auslösen.</p></div><div><small>Zeitkritisch</small><h3>Konvulsiver Status</h3><p>Ab etwa <b>5 Minuten</b> anhaltender tonisch-klonischer Aktivität oder bei Anfallsserien ohne Erholung ist sofortige Behandlung erforderlich.</p></div></div></>)}
    {section("02", "Anatomie und Physiologie", <>
      <p>Das zentrale Nervensystem umfasst Gehirn und Rückenmark. Neuronen leiten elektrische Impulse über das Axon; an Synapsen übertragen Neurotransmitter das Signal chemisch an die nächste Zelle.</p>
      <div className="pulmo-anatomy-grid"><div><small>Großhirn</small><b>Rinde und Netzwerke</b><p>Wahrnehmung, Bewegung und Bewusstsein; der Anfallsbeginn kann fokal oder von Beginn an beidseitig sein.</p></div><div><small>Zwischenhirn</small><b>Thalamus und Hypothalamus</b><p>Verschaltung sowie vegetative und hormonelle Regulation.</p></div><div><small>Hirnstamm / Kleinhirn</small><b>Vitalfunktionen und Koordination</b><p>Atmung und Kreislaufregulation beziehungsweise Bewegungsabstimmung.</p></div></div>
      <h3>Kindliche Besonderheiten im Einsatz</h3>
      <div className="pulmo-compare">
        <div><small>01 · Atemweg</small><h3>Enger und leichter verlegbar</h3><p><b>Kind:</b> Relativ größere Zunge, kleinerer Atemweg und beim Säugling größerer Hinterkopf. Schwellung oder Halsbeugung stören rascher.<br/><b>Erwachsene:</b> Größerer Atemweg mit mehr Platz.</p></div>
        <div><small>02 · Atmung</small><h3>Weniger Sauerstoffreserve</h3><p><b>Kind:</b> Höherer Sauerstoffbedarf; bei Atemstörung raschere Desaturation. Säuglinge atmen stärker mit dem Zwerchfell.<br/><b>Erwachsene:</b> Mehr Reserve und geringere Atemfrequenz.</p></div>
        <div><small>03 · Kreislauf</small><h3>Frequenz ist wichtiger</h3><p><b>Kind:</b> Besonders Säuglinge steigern das Herzzeitvolumen vor allem über die Herzfrequenz. Hypotonie kann spät auftreten.<br/><b>Erwachsene:</b> Schlagvolumen lässt sich stärker steigern.</p></div>
        <div><small>04 · Stoffwechsel</small><h3>Wärme und Glukose</h3><p><b>Kind:</b> Relativ größere Körperoberfläche fördert Wärmeverlust; Säuglinge haben kleinere Glykogenspeicher.<br/><b>Erwachsene:</b> Relativ geringerer Wärmeverlust und größere Reserven.</p></div>
      </div>
      <h3>Vitalzeichen im Altersvergleich</h3>
      <div className="pulmo-compare">
        <div><small>Säugling</small><h3>1 Jahr</h3><p><b>Puls</b> 105–150/min<br/><b>Atmung</b> 20–45/min<br/><b>RR syst.</b> 70–105 mmHg</p></div>
        <div><small>Kleinkind</small><h3>4 Jahre</h3><p><b>Puls</b> 80–150/min<br/><b>Atmung</b> 17–30/min<br/><b>RR syst.</b> 75–110 mmHg</p></div>
        <div><small>Schulkind</small><h3>10 Jahre</h3><p><b>Puls</b> 60–130/min<br/><b>Atmung</b> 15–25/min<br/><b>RR syst.</b> 85–120 mmHg</p></div>
        <div><small>Vergleich</small><h3>17+ Jahre</h3><p><b>Puls</b> 60–115/min<br/><b>Atmung</b> 14–25/min<br/><b>RR syst.</b> 90–135 mmHg</p></div>
      </div>
      <aside className="diagnostic-boundary"><span>i</span><div><b>Orientierungsbereiche, keine starren Grenzwerte</b><p>Die RCH-Werte gelten als akzeptable Bereiche für kranke Kinder und Jugendliche. Fieber, Schmerz und Angst können Werte verändern. Atemarbeit, Durchblutung, Bewusstsein und Verlauf wiederholter Messungen bleiben entscheidend.</p></div></aside>
      <Figure src="/lessons/krampfanfall/neuron-axon-synapse.jpg" alt="Beschriftete Nervenzelle mit Dendriten, Zellkern, Axon, Myelinscheide, Endknöpfchen und Synapse" caption="Nervenzelle und Synapse · Abbildung aus dem bereitgestellten Skript" wide />
    </>)}
    {section("03", "Pathophysiologie und Ursachen", <><div className="pulmo-path"><span>Erregbarkeit erhöht</span><i>→</i><span>Synchronisierte Entladung</span><i>→</i><span>Anfall im Netzwerk</span></div><p>Im Gehirn wirkt <b>Glutamat</b> überwiegend erregend und <b>GABA</b> überwiegend hemmend. Eine gestörte Balance kann die Anfallsschwelle senken. Fieber, Hypoglykämie, Schlafmangel oder ein Infekt können Anfälle begünstigen; beim einzelnen Kind ist die genaue Ursache gesondert zu klären.</p><Figure src="/lessons/krampfanfall/aktionspotenzial.jpg" alt="Verlauf eines Aktionspotenzials mit Natriumeinstrom, Kaliumausstrom und Hyperpolarisation" caption="Elektrische Reizweiterleitung · Abbildung aus dem bereitgestellten Skript" wide /><div className="child-fact-grid"><div><small>Fieberkrampf</small><b>Typischer Altersbereich</b><p>Vor allem zwischen 6 Monaten und 5 Jahren. Ein Fieberkrampf ist keine automatische Epilepsiediagnose.</p></div><div><small>Wichtiges Detail</small><b>Fieberanstieg ist nicht alles</b><p>Ob die absolute Temperatur oder der rasche Anstieg entscheidender ist, lässt sich nicht pauschal festlegen.</p></div><div><small>Prüfungsfalle</small><b>Fiebersenkung ≠ Anfallsschutz</b><p>Antipyretika können Beschwerden lindern, verhindern einen erneuten Fieberkrampf aber nicht zuverlässig.</p></div></div><p>Ein „einfacher“ Fieberkrampf ist generalisiert, dauert unter 15 Minuten und tritt nur einmal innerhalb von 24 Stunden auf. Ein fokaler, längerer oder wiederholter Anfall ist abklärungsbedürftiger; eine ZNS-Infektion muss bei passenden Zeichen bedacht werden.</p></>)}
    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", <><div className="pulmo-compare"><div><small>Fokaler Beginn</small><h3>Umschriebene Zeichen</h3><p>Einseitige Zuckungen, Blickwendung, Missempfindung oder Sprach-/Bewusstseinsänderung. Er kann sich bilateral ausbreiten.</p></div><div><small>Von Beginn an bilateral</small><h3>Generalisierter Beginn</h3><p>Beidseitige tonische oder klonische Aktivität; auch myoklonische oder atonische Formen sind möglich.</p></div></div><div className="pulmo-symptoms">{["Beginn und Dauer beobachtet", "Fokale Zeichen / Blickwendung", "Tonus und Zuckungen", "Bewusstseinsänderung", "Zyanose / Atemstörung", "Postiktale Erholung"].map(item => <span key={item}>{item}</span>)}</div><aside className="red-flags"><span>!</span><div><small>Red Flags</small><h3>Fieber ist keine Entwarnung</h3><p>Alter außerhalb des typischen Fieberkrampfbereichs, anhaltender oder wiederholter Anfall, fokale Zeichen, fehlende Vigilanzbesserung, Atemstörung oder Hinweise auf Meningitis/Sepsis verlangen eine erweiterte Ursachensuche.</p></div></aside></>)}
    {section("05", "Komplikationen und Gefahren", <div className="rib-fracture-grid">{[["Status epilepticus", "Andauernde oder wiederholte Konvulsionen ohne Erholung sind zeitkritisch."], ["Atemweg", "Hypoventilation, Hypoxie und Aspiration; nach Benzodiazepin weiter überwachen."], ["Verletzung", "Sturz, Kopftrauma und Zungenverletzung aktiv suchen."], ["Ursache übersehen", "Hypoglykämie, ZNS-Infektion, Intoxikation oder intrakranielle Verletzung können parallel vorliegen."]].map(([a,b]) => <div key={a}><b>{a}</b><span>{b}</span></div>)}</div>)}
    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", <div className="material-chips">{["Kindernotfall-Lineal / App", "BZ und Thermometer", "EKG / RR / SpO₂", "O₂ und passende Beatmung", "Absaugung / Atemweg", "Diazepam-Rectiole", "Midazolam 15 mg / 3 ml", "MAD für i.n.-Gabe", "Transport und Dokumentation"].map(item => <span key={item}>{item}</span>)}</div>)}
    {section("07", "Erstmaßnahmen und Anamnese", <><div className="pulmo-care-grid"><div><span>01</span><b>Schützen &amp; Zeit messen</b><small>Gefahren entfernen, Kopf schützen, nichts in den Mund stecken, nicht gewaltsam festhalten.</small></div><div><span>02</span><b>cABCDE</b><small>Atemweg, Atmung und Kreislauf wiederholt prüfen; Absaugung und altersgerechte Beatmung bereithalten.</small></div><div><span>03</span><b>Gewicht, BZ, Temperatur</b><small>Gewicht erfragen oder kognitive Hilfe nutzen; Glukose und Temperatur früh erfassen.</small></div><div><span>04</span><b>Nach dem Anfall</b><small>Erholung, Verletzung und fokale Ausfälle prüfen; Kind und Bezugspersonen beruhigen.</small></div></div><h3>SAMPLERS · fokussiert</h3><div className="samplers-grid">{[["S · Symptome", "Beginn, Dauer, Seite, Erholung"], ["A · Allergien", "Bekannte Unverträglichkeiten"], ["M · Medikamente", "Antikonvulsiva, bereits gegebene Mittel"], ["P · Vorgeschichte", "Fieberkrampf, Epilepsie, Entwicklung"], ["L · Letzte Aufnahme", "Nahrung, Flüssigkeit, mögliche Substanzen"], ["E · Ereignis", "Fieber, Sturz, Infektbeginn"], ["R · Risiken", "Meningitiszeichen, Stoffwechselstörung"], ["S · Sonstiges", "Gewicht, Elternbericht, Zeitachse"]].map(([a,b]) => <p key={a}><b>{a}</b>{b}</p>)}</div></>)}
    {section("08", "Differenzialdiagnosen und Entscheidung", <><div className="differential-grid">{["Hypoglykämie", "Meningitis / Enzephalitis", "SHT / intrakranielle Blutung", "Intoxikation", "Synkope / Rhythmusstörung", "Metabolische Störung", "Epilepsie", "Sepsis / schwerer Infekt"].map(item => <span key={item}>{item}</span>)}</div><aside className="diagnostic-boundary"><span>!</span><div><b>Beendeter Anfall und laufender Anfall sind zwei Wege</b><p>Bei sistiertem Anfall Atemweg, Ursache und Erholungsverlauf prüfen. Bei andauerndem Krampf nach VFA 30 behandeln; Gewicht und geeigneten Applikationsweg bestimmen. Zuckungen schließen einen Kreislaufstillstand nicht aus.</p></div></aside></>)}
    {section("09", "Weitere Maßnahmen · Thüringer VFA 30", <><div className="pulmo-compare"><div><small>Rektal · situativ günstig</small><h3>Diazepam-Rectiole</h3><p><b>Bis 3 Jahre und &lt; 15 kg: 5 mg.</b><br/><b>Ab 3 Jahren und &gt; 15 kg: 10 mg.</b> Bei Grenzfällen, die die VFA nicht eindeutig zuordnet, ärztliche Rücksprache halten.</p></div><div><small>Intranasal · Alternative</small><h3>Midazolam mit MAD</h3><p><b>0,2 mg/kgKG</b> aus 15 mg/3 ml (5 mg/ml), unverdünnt. Die VFA-Tabelle gibt das aufzuziehende Volumen einschließlich 0,1 ml MAD-Totraum an.</p></div></div><MidazolamChildSyringe /><div className="child-timeline"><span><b>0 min</b> Anfall und Behandlung</span><i>→</i><span><b>10 min</b> Erneut beurteilen</span><i>→</i><span><b>Max. 1×</b> Wiederholung bei anhaltendem / erneutem Anfall</span></div><p><b>Erst nach Kontrolle des Anfalls:</b> Bei Körpertemperatur &gt; 38,5 °C sieht VFA 30 nichtmedikamentöse Fiebersenkung und Paracetamol- oder Ibuprofen-Suppositorien vor. Die genaue altersbezogene Auswahl steht im Originalalgorithmus unten. Fiebersenkung ersetzt keine Anfallsbehandlung.</p><p>Nach jeder sedierenden Gabe Atmung und Bewusstsein kontrollieren. Überwachung, kontinuierliches Monitoring und Transport fortsetzen; Notarzt nach klinischer Lage und lokalen Vorgaben frühzeitig einbeziehen.</p></>)}
    {section("10", "VFA Thüringen 2026/2027 · Original und B2A", <><p>Die Originalabbildungen lassen sich einklappen und für Dosierungsdetails im Vollbild öffnen. Bei der Kinder-VFA hat die Tabelle Vorrang vor einer eigenen Rundung.</p><div className="vfa-stack"><Vfa src="/lessons/krampfanfall-kind/vfa-30-kind.png" alt="Originalalgorithmus Thüringer VFA 30 für Krampfanfall bei Kindern unter 30 kg mit Diazepam rektal, Midazolam intranasal, Gewichtstabelle, Wiederholung und Fiebersenkung" caption="VFA 30 · Krampfanfall Kind unter 30 kg" /></div><Figure src="/lessons/krampfanfall-kind/b2a-midazolam-kind.png" alt="Anlage B2A: Midazolam intranasal 15 mg in 3 ml, unverdünnt, entsprechend 5 mg pro ml" caption="B2A · Midazolam i.n., relevante Zeile" wide /><Figure src="/lessons/krampfanfall-kind/b2a-diazepam.png" alt="Anlage B2A: Diazepam-Rectiolen mit 5 mg und 10 mg für VFA 30" caption="B2A · Diazepam rektal, relevante Zeilen" wide /></>)}
    {children}
    <p className="lesson-source">Grundlage: Krampfanfall u 31.pdf und <a href="https://www.aelrd-thueringen.de/verfahrensanweisungen-fuer-den-thueringer-rettungsdienst-algorithmen/" target="_blank" rel="noreferrer">Thüringer VFA 2026/27, Nr. 30 und Anlage B2A</a>. Ergänzende Fakten zu Fieberkrämpfen: <a href="https://www.rch.org.au/clinicalguide/guideline_index/Febrile_seizure/" target="_blank" rel="noreferrer">Royal Children's Hospital Clinical Practice Guideline</a> und <a href="https://rd-factsheets.de/fs/fieberkrampf/" target="_blank" rel="noreferrer">RD-Factsheets</a>. Körpervergleich und Vitalwerte: <a href="https://www.rch.org.au/trauma-service/manual/how-are-children-different/" target="_blank" rel="noreferrer">RCH, How are children different</a> und <a href="https://www.rch.org.au/clinicalguide/guideline_index/Acceptable_ranges_for_physiological_variables/" target="_blank" rel="noreferrer">RCH, Acceptable ranges</a>. Medikamentendosen richten sich ausschließlich nach der Thüringer VFA.</p>
  </article>;
}
