import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [string, boolean];
function q(n: number, prompt: string, options: Option[], source: string): ThoraxtraumaChoiceQuestion {
  const shift = n % options.length;
  return { id: `krampfanfall-q-${String(n).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty: 3 };
}

export const krampfanfallQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Ein 32-Jähriger zeigt plötzlich einseitige Zuckungen und kann zunächst antworten. Welche Bewertungen passen?", [["Ein fokaler Anfallsbeginn ist möglich", true], ["Erhaltenes Bewusstsein schließt einen epileptischen Anfall aus", false], ["Die Ausbreitung und Dauer sollten beobachtet werden", true], ["Ein generalisierter Beginn ist bereits bewiesen", false], ["Ein Schlaganfall darf allein wegen Zuckungen ausgeschlossen werden", false]], "Fokale Anfälle können bei erhaltenem Bewusstsein beginnen; Verlauf und Differenzialdiagnosen dokumentieren."),
  q(2, "Was beschreibt den Kern eines epileptischen Anfalls fachlich richtig?", [["Vorübergehende abnorme elektrische Aktivität neuronaler Netzwerke", true], ["Die Erscheinung hängt vom beteiligten Netzwerk ab", true], ["Jeder Einzelanfall beweist eine chronische Epilepsie", false], ["Der Anfall entsteht zwingend ausschließlich im Hirnstamm", false]], "Ein Anfall ist eine zeitlich begrenzte neuronale Funktionsstörung, keine automatische Epilepsiediagnose."),
  q(3, "Welche Zuordnungen zur Neurophysiologie stimmen?", [["Glutamat ist im Gehirn überwiegend erregend", true], ["GABA vermittelt überwiegend Hemmung", true], ["Ionenströme beeinflussen die Erregbarkeit von Neuronen", true], ["Myelin ist der wichtigste erregende Transmitter", false], ["Acetylcholin ist der alleinige Auslöser aller epileptischen Entladungen", false]], "Erregung, Hemmung und Membranleitfähigkeit bestimmen die neuronale Erregbarkeit."),
  q(4, "Welche Angaben helfen bei der Einordnung eines beobachteten Anfalls besonders?", [["Zeitpunkt und Dauer", true], ["Einseitiger Beginn oder Blickwendung", true], ["Rückkehr zum vorherigen Bewusstseinszustand", true], ["Farbe der Einsatzkleidung", false], ["Allein die spätere Erinnerung an den Notruf", false]], "Zeugenbericht zu Beginn, Ausbreitung, Dauer und Erholungsphase ist oft diagnostisch wertvoll."),
  q(5, "Die Konvulsionen halten seit sechs Minuten an. Welche Aussagen sind angemessen?", [["Ein konvulsiver Status epilepticus ist anzunehmen", true], ["Atemweg und Beatmungsbereitschaft haben hohe Priorität", true], ["Die Thüringer VFA 29 ist für einen fortbestehenden Krampfanfall relevant", true], ["Zunächst weitere 20 Minuten ohne Intervention beobachten", false], ["Ein normaler Zwischenwert der SpO₂ beendet die Gefahreneinschätzung", false]], "Ab fünf Minuten wird ein anhaltender tonisch-klonischer Anfall als Status behandelt; Versorgung nach VFA."),
  q(6, "Zwei tonisch-klonische Anfälle folgen unmittelbar aufeinander. Dazwischen ist der Patient nicht wieder bewusstseinsklar. Was folgt daraus?", [["Eine Anfallsserie ohne Erholung ist zeitkritisch", true], ["Die fehlende Erholung ist für die Statusdefinition relevant", true], ["Atmung und Kreislauf müssen fortlaufend kontrolliert werden", true], ["Jeder kurze Abstand zwischen Anfällen schließt einen Status aus", false]], "Wiederholte Anfälle ohne Bewusstseinsrückkehr können einen Status epilepticus darstellen."),
  q(7, "Welche präklinischen Handlungen während der Konvulsion sind geeignet?", [["Beginn und Dauer erfassen", true], ["Umgebung und Kopf vor Verletzung schützen", true], ["BZ und Monitoring organisieren, sobald durchführbar", true], ["Einen Gegenstand zwischen die Zähne drücken", false], ["Extremitäten mit Kraft fixieren, damit Zuckungen aufhören", false]], "Sicherheit, Zeit und cABCDE; keine forcierte Fixierung und keine Gegenstände im Mund."),
  q(8, "Ein Anfall ist beendet, der Patient atmet spontan und wird langsam wacher. Welche Entscheidungen passen?", [["Atemweg und Atmung erneut beurteilen", true], ["BZ erheben und nach Ursache sowie Verletzungen suchen", true], ["Neurologische Erholung im Verlauf dokumentieren", true], ["Midazolam routinemäßig zur Vorbeugung nachgeben", false], ["Postiktale Verwirrtheit beweist eine harmlose Ursache", false]], "Bei sistiertem Einzelanfall keine routinemäßige Benzodiazepingabe; Ursache und Verlauf klären."),
  q(9, "Nach einem beendeten Anfall bleibt eine einseitige Armparese bestehen. Welche Aussagen stimmen?", [["Eine Todd-Parese ist möglich", true], ["Ein Schlaganfall bleibt differenzialdiagnostisch relevant", true], ["Neurologische Befunde müssen wiederholt und zeitlich dokumentiert werden", true], ["Die Parese beweist eine strukturell folgenlose Epilepsie", false]], "Postiktale fokale Defizite können vorübergehen, schließen einen akuten Schlaganfall aber nicht aus."),
  q(10, "Ein Patient wird mit Zuckungen gefunden. Wann ist statt der Anfallsbehandlung vorrangig Reanimation zu prüfen?", [["Bei fehlender normaler Atmung und fehlenden Lebenszeichen", true], ["Bei möglicher konvulsiver Synkope durch Kreislaufstillstand", true], ["Nach cABCDE und rascher Kreislaufbeurteilung", true], ["Allein wegen eines Zungenbisses", false], ["Erst nach erfolgloser Midazolamgabe", false]], "Zuckungen können einen Kreislaufstillstand begleiten; fehlende Lebenszeichen haben Vorrang."),
  q(11, "Welche Ursachen eines ersten Anfalls beim Erwachsenen gehören in die präklinische Suche?", [["Hypoglykämie", true], ["Intoxikation oder Entzug", true], ["Intrakranielle Blutung oder SHT", true], ["Fieberhafte ZNS-Infektion", true], ["Eine Epilepsie ist definitionsgemäß immer die einzige Ursache", false]], "Der erste Anfall erfordert differenzialdiagnostisches Denken und klinische Abklärung."),
  q(12, "Was stimmt zum Midazolam-Erstschritt der Thüringer VFA 29 bei laufendem Anfall?", [["i.v. 3 mg langsam aus 1 mg/ml entsprechen 3 ml", true], ["i.n. 10 mg aus 5 mg/ml entsprechen 2 ml und werden verteilt", true], ["i.m. bei über 40 kg: 10 mg aus 5 mg/ml entsprechen 2 ml", true], ["i.v. 10 mg aus 5 mg/ml sind die allgemeine Erstgabe", false], ["Alle drei Wege werden gleichzeitig als Routine kombiniert", false]], "VFA 29 unterscheidet situativ Applikationswege und Konzentrationen."),
  q(13, "Nach der ersten intranasalen Gabe krampft ein Erwachsener weiter. Nach fünf Minuten: Welche Aussagen passen zur VFA 29?", [["Erneute Beurteilung ist erforderlich", true], ["Die intranasale Folgedosis beträgt 5 mg", true], ["Bei 5 mg/ml sind das 1 ml insgesamt", true], ["Das Volumen soll auf beide Nasenlöcher verteilt werden", true], ["Die intranasale Folgedosis beträgt erneut zwingend 10 mg", false]], "Bei weiterem/erneutem Anfall nach fünf Minuten i.n. 5 mg, verteilt über beide Nasenlöcher."),
  q(14, "Bei liegendem i.v.-Zugang krampft ein Patient nach 3 mg Midazolam i.v. weiter. Welche Folgeschritte sind VFA-konform?", [["Nach fünf Minuten Zustand und Anfall erneut beurteilen", true], ["Bei Fortbestehen 2 mg langsam i.v. erwägen", true], ["Bei 1 mg/ml entsprechen 2 mg einem Volumen von 2 ml", true], ["Ohne Zwischenbeurteilung 10 mg i.v. injizieren", false]], "VFA 29: nach fünf Minuten und anhaltendem/erneutem Anfall 2 mg langsam i.v."),
  q(15, "Ein Erwachsener über 40 kg benötigt den i.m.-Pfad der VFA 29. Welche Aussagen sind korrekt?", [["Erstgabe 10 mg i.m.", true], ["Bei 5 mg/ml sind 10 mg gleich 2 ml", true], ["Bei anhaltendem Anfall nach fünf Minuten beträgt die i.m.-Folgedosis 5 mg", true], ["Die i.m.-Konzentration beträgt laut B2A 1 mg/ml", false], ["Die Folgedosis muss ohne Zeitintervall gleichzeitig erfolgen", false]], "VFA 29 und B2A: >40 kg i.m. 10 mg, nach fünf Minuten bei Bedarf 5 mg; 5 mg/ml."),
  q(16, "Welche Interpretation der B2A-Midazolamzeilen ist richtig?", [["5 mg/5 ml liefern 1 mg/ml für i.v.", true], ["15 mg/3 ml liefern 5 mg/ml für i.n. oder i.m.", true], ["Beide aufgeführten Zubereitungen werden dort unverdünnt angegeben", true], ["Beide Ampullen haben dieselbe Konzentration", false], ["Die i.n.-Zubereitung ist zehnfach verdünnt", false]], "Die Konzentrationen sind unterschiedlich; Volumen vor Verabreichung neu berechnen."),
  q(17, "Warum ist nach Midazolamgabe besonders engmaschiges Monitoring wichtig?", [["Atemdepression ist möglich", true], ["Atemweg und Beatmung müssen verfügbar sein", true], ["Anfallskontrolle allein beweist keine ausreichende Ventilation", true], ["Midazolam verhindert grundsätzlich jede Aspiration", false], ["Nur die Pupillenweite muss überwacht werden", false]], "Benzodiazepinwirkung, postiktaler Zustand und Aspiration können die Atmung gefährden."),
  q(18, "Ein 68-Jähriger fällt um, zeigt kurze Zuckungen und wird rasch wieder klar. Was muss bei der Entscheidung berücksichtigt werden?", [["Eine konvulsive Synkope ist möglich", true], ["EKG und Kreislaufbefund sind wichtig", true], ["Dauer und posteventuelle Erholung helfen bei der Einordnung", true], ["Kurze Zuckungen beweisen Epilepsie", false], ["Herzrhythmusstörungen sind nach Zuckungen ausgeschlossen", false]], "Synkope und Arrhythmie können mit kurzen Konvulsionen einhergehen; kardialen Befund erheben."),
  q(19, "Welche Befunde nach einem scheinbar beendeten Anfall erfordern eine erneute kritische Beurteilung?", [["Ausbleibende Bewusstseinsbesserung", true], ["Neue Atemstörung", true], ["Anhaltendes fokales Defizit", true], ["Erneute Krampfaktivität", true], ["Einmaliges Müdigkeitsgefühl bei sonst normaler Erholung als alleiniger Statusbeweis", false]], "Verlauf, Atmung und Neurologie bestimmen die Eskalation; nicht jede Müdigkeit ist ein Status."),
  q(20, "Welche Angaben gehören in eine hochwertige Übergabe nach Erwachsenenkrampfanfall?", [["Beobachteter Beginn, Dauer und Anfallssemiologie", true], ["BZ, EKG und Vitalverlauf", true], ["Midazolam: Weg, Konzentration, Dosis und Uhrzeit", true], ["Rückkehr des Bewusstseins und fokale Befunde", true], ["Nur die Zahl der Einsatzkräfte", false]], "Die Übergabe muss Zeitachse, neurologischen Verlauf, mögliche Ursache und Interventionen nachvollziehbar machen."),
];

export const krampfanfallFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "krampfanfall-card-01", area: "Definition", question: "Definieren Sie einen epileptischen Anfall und grenzen Sie ihn von der Diagnose Epilepsie ab.", answer: "Vorübergehende Hirnfunktionsstörung durch abnorme übermäßige oder synchronisierte neuronale Aktivität. Ein Einzelanfall kann akut symptomatisch sein und beweist keine chronische Epilepsie." },
  { id: "krampfanfall-card-02", area: "Neurophysiologie", question: "Wie tragen Glutamat, GABA und Membran-Ionenströme zur Anfallsschwelle bei?", answer: "Glutamat wirkt überwiegend erregend, GABA hemmend. Verschobenes Gleichgewicht und veränderte Ionenleitfähigkeit erhöhen die Erregbarkeit und erleichtern synchrone Entladungen." },
  { id: "krampfanfall-card-03", area: "Symptome", question: "Welche Beobachtungen ermöglichen die Unterscheidung eines fokalen Beginns von einem beidseitig tonisch-klonischen Verlauf?", answer: "Beginn in einer Körperregion, Blickwendung, Aura oder Sprachstörung sprechen für fokalen Beginn; später können Bewusstseinsverlust, tonische Phase und beidseitige rhythmische Zuckungen folgen. Zeit und Ausbreitung durch Zeugen erfragen." },
  { id: "krampfanfall-card-04", area: "Status", question: "Wann nehmen Sie einen konvulsiven Status epilepticus an und warum ist er zeitkritisch?", answer: "Tonisch-klonische Konvulsionen ab ungefähr fünf Minuten oder wiederholte Anfälle ohne Bewusstseinsrückkehr. Risiken sind unter anderem Hypoxie, Aspiration und fortbestehende Anfallsaktivität; Atemweg und Therapie nach VFA priorisieren." },
  { id: "krampfanfall-card-05", area: "Differenzialdiagnose", question: "Warum schließen beobachtete Zuckungen eine kardiale Ursache oder einen Kreislaufstillstand nicht aus?", answer: "Eine konvulsive Synkope oder ein Kreislaufstillstand kann kurze Zuckungen auslösen. Deshalb Atmung, Kreislauf und EKG sofort prüfen und bei fehlenden Lebenszeichen Reanimation priorisieren." },
  { id: "krampfanfall-card-06", area: "Erstmaßnahmen", question: "Welche Maßnahmen erfolgen während des Anfalls – und welche zwei verbreiteten Handlungen unterlassen Sie?", answer: "Zeit erfassen, Umgebung/Kopf schützen, cABCDE, BZ, Monitoring, Atemwegs- und Beatmungsbereitschaft. Weder gewaltsam fixieren noch Gegenstände in den Mund stecken." },
  { id: "krampfanfall-card-07", area: "Postiktal", question: "Wie beurteilen Sie eine anhaltende einseitige Lähmung nach einem beendeten Anfall?", answer: "Todd-Parese ist möglich, aber Schlaganfall oder Blutung sind nicht ausgeschlossen. Neurologischen Befund und Zeitverlauf dokumentieren, BZ und weitere Ursachen prüfen, geeignete Klinik einbeziehen." },
  { id: "krampfanfall-card-08", area: "VFA 29", question: "Nennen und berechnen Sie die drei Midazolam-Erstdosen für einen Erwachsenen über 40 kg mit laufendem Anfall.", answer: "i.v. 3 mg langsam aus 1 mg/ml = 3 ml; i.n. 10 mg aus 5 mg/ml = 2 ml verteilt auf beide Nasenlöcher; i.m. >40 kg 10 mg aus 5 mg/ml = 2 ml. Situativen Applikationsweg auswählen." },
  { id: "krampfanfall-card-09", area: "VFA 29", question: "Welche Folgedosen gelten nach fünf Minuten bei weiterem oder erneutem Anfall über 40 kg?", answer: "i.v. 2 mg langsam (2 ml bei 1 mg/ml), i.n. 5 mg (1 ml bei 5 mg/ml, auf beide Nasenlöcher verteilt) oder i.m. 5 mg (1 ml bei 5 mg/ml). Danach erneut prüfen und bei weiterem Anfall andere Ursachen suchen." },
  { id: "krampfanfall-card-10", area: "Medikamentensicherheit", question: "Warum dürfen die i.v.- und i.n./i.m.-Midazolamampullen nicht nach derselben Volumenrechnung verwendet werden?", answer: "B2A nennt i.v. 5 mg/5 ml = 1 mg/ml und i.n./i.m. 15 mg/3 ml = 5 mg/ml. Gleiche mg-Dosis entspricht daher unterschiedlichem Volumen; Weg, Konzentration und Menge kontrollieren." },
  { id: "krampfanfall-card-11", area: "Ursachen", question: "Welche vier behandelbaren oder zeitkritischen Ursachen eines erstmaligen Erwachsenenkrampfanfalls suchen Sie aktiv?", answer: "Zum Beispiel Hypoglykämie, Intoxikation/Entzug, intrakranielle Blutung oder SHT und ZNS-Infektion; zudem EKG/Kreislauf wegen konvulsiver Synkope prüfen." },
  { id: "krampfanfall-card-12", area: "Entscheidung", question: "Warum geben Sie nach einem einzelnen, bereits sistierten Anfall nicht routinemäßig Midazolam?", answer: "Die akute Konvulsion ist beendet, ein Benzodiazepin bringt dann keine Anfallskontrolle, kann aber Atmung und Vigilanz beeinträchtigen. Monitoring, Ursache, Verletzung und Erholungsverlauf haben Priorität; bei erneutem Anfall VFA 29." },
  { id: "krampfanfall-card-13", area: "Anamnese", question: "Welche fünf Details erfragen Sie vom Augenzeugen zur Anfallssemiologie und zum Verlauf?", answer: "Beginn/Uhrzeit, Dauer, fokale Zeichen/Seitenbetonung und Blickwendung, Bewusstseinsverlauf, Rückkehr zum Ausgangszustand; dazu mögliche Auslöser, Trauma und vorherige Anfälle." },
  { id: "krampfanfall-card-14", area: "Übergabe", question: "Wie übergeben Sie einen mit Midazolam behandelten Anfall so, dass die Klinik die Zeitachse rekonstruieren kann?", answer: "Beginn, Art und Dauer jeder Episode, Vigilanz dazwischen, BZ/EKG/Vitalverlauf, Medikament mit Weg/Konzentration/mg/ml/Uhrzeit, Wirkung, Atemwegssituation, Verletzungen und fokale neurologische Befunde." },
];
