import { useState, type ComponentType, type ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

function SeizureTypeComparison() {
  return <><div className="pulmo-compare seizure-onset-grid"><div><small>Fokaler Anfall</small><h3>Beginn in einem begrenzten Netzwerk</h3><p>Die Aktivität beginnt in einer Hirnhälfte. Mögliche Zeichen sind einseitige Zuckungen, Missempfindung, Blickwendung oder Sprachstörung. Das Bewusstsein kann erhalten oder beeinträchtigt sein.</p></div><div><small>Generalisierter Anfall</small><h3>Von Beginn an beidseitige Netzwerke</h3><p>Die Aktivität erfasst von Beginn an beidseitige Netzwerke. Mögliche Formen sind tonisch-klonische, myoklonische oder Absence-Anfälle; nicht jeder generalisierte Anfall ist tonisch-klonisch.</p></div></div><div className="seizure-onset-note"><b>Wichtige Abgrenzung</b><span>Ein fokaler Anfall kann in einen <strong>fokal zu bilateral tonisch-klonischen Anfall</strong> übergehen. Ist der Beginn nicht beobachtet, bleibt er zunächst <strong>unklar</strong> – beidseitige Zuckungen beweisen keinen generalisierten Beginn.</span></div><p>Bei einem beidseitig tonisch-klonischen Verlauf können Bewusstseinsverlust, tonische Anspannung und rhythmische Zuckungen folgen; möglich sind Initialschrei, Zyanose, Zungenbiss und postiktale Verwirrtheit. Für die Einordnung den <b>Beginn</b> und die Ausbreitung durch Zeugen beschreiben lassen.</p></>;
}

type SyringeRoute = "iv" | "in" | "im-over" | "im-under";
type SyringePhase = "first" | "repeat";
type SyringeExample = { dose: number; volume: number; concentration: number; description: string };
const syringeExamples: Record<SyringeRoute, Record<SyringePhase, SyringeExample>> = {
  iv: {
    first: { dose: 3, volume: 3, concentration: 1, description: "3 mg langsam i.v. aus 5 mg/5 ml" },
    repeat: { dose: 2, volume: 2, concentration: 1, description: "2 mg langsam i.v. nach 5 Minuten bei anhaltendem oder erneutem Anfall" },
  },
  in: {
    first: { dose: 10, volume: 2, concentration: 5, description: "10 mg i.n. aus 15 mg/3 ml über MAD, auf beide Nasenlöcher verteilt" },
    repeat: { dose: 5, volume: 1, concentration: 5, description: "5 mg i.n. nach 5 Minuten bei anhaltendem oder erneutem Anfall, auf beide Nasenlöcher verteilt" },
  },
  "im-over": {
    first: { dose: 10, volume: 2, concentration: 5, description: "10 mg i.m. aus 15 mg/3 ml bei Körpergewicht > 40 kg" },
    repeat: { dose: 5, volume: 1, concentration: 5, description: "5 mg i.m. nach 5 Minuten bei anhaltendem oder erneutem Anfall und > 40 kg" },
  },
  "im-under": {
    first: { dose: 5, volume: 1, concentration: 5, description: "5 mg i.m. aus 15 mg/3 ml bei Körpergewicht < 40 kg" },
    repeat: { dose: 2.5, volume: 0.5, concentration: 5, description: "2,5 mg i.m. nach 5 Minuten bei anhaltendem oder erneutem Anfall und < 40 kg" },
  },
};
const syringeRouteLabels: Record<SyringeRoute, string> = {
  iv: "i.v.", in: "i.n. · MAD", "im-over": "i.m. > 40 kg", "im-under": "i.m. < 40 kg",
};

function MidazolamSyringe() {
  const [route, setRoute] = useState<SyringeRoute>("iv");
  const [phase, setPhase] = useState<SyringePhase>("first");
  const example = syringeExamples[route][phase];
  const capacity = route === "iv" ? 5 : route === "im-under" && phase === "repeat" ? 1 : 3;
  const marks = Array.from({ length: capacity === 1 ? 11 : capacity * 2 + 1 }, (_, index) => index * (capacity === 1 ? 0.1 : 0.5));
  const barrelStart = 88;
  const barrelWidth = 470;
  const fluidWidth = example.volume / capacity * barrelWidth;
  const isIntranasal = route === "in";
  const isIntramuscular = route.startsWith("im");
  return <div className="syringe-panel">
    <div className="syringe-panel-heading"><div><small>VFA-Volumen anschaulich</small><h3>Midazolam · aufgezogenes Volumen</h3></div><span>VFA 29 · Anlage B2A</span></div>
    <div className="syringe-controls" role="group" aria-label="Applikationsweg und Gewicht wählen">{(Object.keys(syringeRouteLabels) as SyringeRoute[]).map(value => <button type="button" key={value} className={route === value ? "active" : ""} aria-pressed={route === value} onClick={() => setRoute(value)}>{syringeRouteLabels[value]}</button>)}</div>
    <div className="syringe-controls phase" role="group" aria-label="Gabe wählen"><button type="button" className={phase === "first" ? "active" : ""} aria-pressed={phase === "first"} onClick={() => setPhase("first")}>Erstgabe</button><button type="button" className={phase === "repeat" ? "active" : ""} aria-pressed={phase === "repeat"} onClick={() => setPhase("repeat")}>Folgedosis · nach 5 Min.</button></div>
    <div className="syringe-readout"><div><small>Midazolam</small><b>{String(example.dose).replace(".", ",")} mg</b></div><div><small>Aufgezogen gesamt</small><b>{String(example.volume).replace(".", ",")} ml</b></div><div><small>NaCl 0,9 %</small><b>0 ml · unverdünnt</b></div></div>
    <div className="syringe-drawing" role="img" aria-label={`Schematische ${capacity}-Milliliter-Spritze, aufgezogen bis ${String(example.volume).replace(".", ",")} Milliliter Midazolam, unverdünnt`}>
      <svg viewBox="0 0 650 175" xmlns="http://www.w3.org/2000/svg">
        <defs><linearGradient id="syringe-fluid" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#6ac5b6"/><stop offset="1" stopColor="#2c9385"/></linearGradient></defs>
        {isIntranasal ? <g><rect x="29" y="73" width="49" height="30" rx="8" fill="#c5dee0" stroke="#6d9297" strokeWidth="2"/><path d="M29 79H20M29 97H20" stroke="#6d9297" strokeWidth="3"/><circle cx="13" cy="77" r="3" fill="#80bec0"/><circle cx="8" cy="89" r="3" fill="#80bec0"/><circle cx="13" cy="101" r="3" fill="#80bec0"/><text x="12" y="127" fontSize="11" fontWeight="700" fill="#496a70">MAD</text></g> : isIntramuscular ? <g><path d="M10 88H76" stroke="#81949a" strokeWidth="3"/><path d="M10 88L27 84V92Z" fill="#81949a"/></g> : <g><path d="M37 76H76V100H37Z" fill="#d8e7e8" stroke="#8ca6a9" strokeWidth="2"/><path d="M34 71V105" stroke="#8ca6a9" strokeWidth="3"/></g>}
        <path d="M78 64V112" stroke="#657b83" strokeWidth="5"/>
        <rect x={barrelStart} y="63" width={barrelWidth} height="50" rx="8" fill="#fbffff" stroke="#9ab2b7" strokeWidth="3"/>
        <rect x={barrelStart + 2} y="65" width={Math.max(0, fluidWidth - 4)} height="46" rx="4" fill="url(#syringe-fluid)"/>
        <path d={`M${barrelStart + fluidWidth} 61V115`} stroke="#214950" strokeWidth="6"/>
        <path d={`M${barrelStart + fluidWidth} 88H604`} stroke="#8b9da1" strokeWidth="5"/>
        <path d="M604 67V109" stroke="#657b83" strokeWidth="6"/>
        {marks.map(value => { const x = barrelStart + value / capacity * barrelWidth; const major = Number.isInteger(value) || capacity === 1 && value === 0.5; return <g key={value}><path d={`M${x} 63V${major ? 80 : 72}`} stroke="#244a54" strokeWidth={major ? 2 : 1.5}/>{major && <text x={x} y="48" textAnchor="middle" fontSize="15" fontWeight="700" fill="#244a54">{Number(value.toFixed(1)).toString().replace(".", ",")}</text>}</g>; })}
        <text x="560" y="145" textAnchor="end" fontSize="15" fontWeight="700" fill="#496a70">ml-Skala · 0–{capacity} ml</text>
      </svg>
    </div>
    <p className="syringe-explanation">{example.description}. <b>{String(example.dose).replace(".", ",")} mg ÷ {example.concentration} mg/ml = {String(example.volume).replace(".", ",")} ml.</b></p>
    <p className="syringe-caution">Schematische Lernansicht, keine Vorgabe für eine bestimmte Spritzengröße. i.n. bedeutet Applikation mit MAD auf beide Nasenlöcher, nicht Injektion mit Nadel. Bei genau 40 kg legt VFA 29 für i.m. keine der beiden Gewichtskategorien fest; hier ist Rücksprache erforderlich. B2A nennt für beide Midazolam-Zubereitungen <b>unverdünnt</b>.</p>
  </div>;
}

export default function KrampfanfallLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>Krampfanfall · Erwachsene</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;
  return <article className="lesson-article rippenfraktur-lesson krampfanfall-lesson">
    <div className="lesson-intro"><p className="lead">Beobachten, schützen, Zeit messen: Ein beendeter Anfall und ein anhaltender Krampfanfall verlangen unterschiedliche Entscheidungen. Ursachen und Verletzungen bleiben auch nach dem Sistieren wichtig.</p></div>
    {section("01", "Definition", <><p>Ein epileptischer Anfall ist eine vorübergehende Funktionsstörung des Gehirns durch übermäßige oder synchronisierte elektrische Aktivität von Nervenzellen. Sie kann umschrieben beginnen oder weite Teile des Gehirns erfassen.</p><div className="pulmo-compare"><div><small>Ereignis</small><h3>Einzelner Anfall</h3><p>Ein Krampfanfall allein beweist noch keine Epilepsie. Auch eine akute Störung kann einen Anfall auslösen.</p></div><div><small>Zeitkritisch</small><h3>Konvulsiver Status</h3><p>Ein anhaltender tonisch-klonischer Anfall ab etwa <b>5 Minuten</b> oder wiederholte Anfälle ohne Wiedererlangen des Bewusstseins gelten als Status epilepticus.</p></div></div></>)}
    {section("02", "Anatomie und Physiologie", <><p>Das zentrale Nervensystem umfasst Gehirn und Rückenmark; das periphere Nervensystem verbindet es mit Körper und Organen. Neuronen empfangen, verarbeiten und übertragen Signale elektrisch entlang ihrer Fortsätze und chemisch an Synapsen.</p><div className="pulmo-anatomy-grid"><div><small>Großhirn</small><b>Rinde und Netzwerke</b><p>Wahrnehmung, Bewegung, Sprache und Bewusstsein; fokale Anfälle können von umschriebenen kortikalen Netzwerken ausgehen.</p></div><div><small>Zwischenhirn</small><b>Thalamus und Hypothalamus</b><p>Schalt- und Regulationsfunktionen; der Thalamus ist mit kortikalen Netzwerken verbunden.</p></div><div><small>Hirnstamm / Kleinhirn</small><b>Vitalfunktion und Koordination</b><p>Hirnstamm: unter anderem Atmungs- und Kreislaufregulation. Kleinhirn: Bewegungskoordination.</p></div></div><Figure src="/lessons/krampfanfall/gehirnlappen.jpg" alt="Beschriftete seitliche Gehirnansicht mit Frontallappen, Parietallappen, Okzipitallappen, Temporallappen, Hirnstamm und Kleinhirn" caption="Großhirnlappen · Abbildung aus Print 12" wide /><Figure src="/lessons/krampfanfall/gehirn-sagittal.jpg" alt="Beschrifteter Sagittalschnitt des Gehirns mit Großhirn, Thalamus, Hypothalamus, Hirnstamm und Kleinhirn" caption="Gehirn im Sagittalschnitt · Abbildung aus Print 12" wide /><p>Graue Substanz enthält überwiegend Nervenzellkörper und Synapsen, weiße Substanz vor allem myelinisierte Nervenfasern. Das Gleichgewicht erregender und hemmender Signale begrenzt normalerweise eine unkontrollierte Ausbreitung von Aktivität.</p><Figure src="/lessons/krampfanfall/neuron-axon-synapse.jpg" alt="Beschriftete Nervenzelle mit Dendriten, Zellkern, Zellkörper, Axon, Myelinscheide, Axonendknöpfchen und Synapse sowie der Richtung des Aktionspotenzials" caption="Nervenzelle und Synapse · Abbildung aus Print 12" wide /></>)}
    {section("03", "Pathophysiologie und Ursachen", <><div className="pulmo-path"><span>Erregung / Hemmung gestört</span><i>→</i><span>Synchronisierte Entladung</span><i>→</i><span>Fokaler oder generalisierter Anfall</span></div><p><b>Glutamat</b> wirkt im Gehirn vorwiegend erregend, <b>GABA</b> vorwiegend hemmend. Veränderte Ionenströme und ein erniedrigter Schwellenwert können epileptische Entladungen begünstigen. Die klinische Erscheinung hängt vom betroffenen Netzwerk ab.</p><Figure src="/lessons/krampfanfall/aktionspotenzial.jpg" alt="Schematischer Verlauf des Aktionspotenzials: Depolarisation durch Natriumeinstrom, Repolarisation durch Kaliumausstrom und anschließende Hyperpolarisation" caption="Elektrische Reizweiterleitung · Aktionspotenzial aus Print 12" wide /><p>Die Abbildung zeigt den elektrischen Impuls an einer Nervenzelle. An der Synapse wird das Signal über Neurotransmitter an die nächste Zelle weitergegeben; beim Anfall kann sich übermäßige Aktivität in Netzwerken ausbreiten.</p><div className="pulmo-risk-grid"><div><b>Epilepsie / strukturelle Ursache</b><p>Bekannte Epilepsie, ausgelassene antikonvulsive Medikamente, Narben oder Hirnläsionen können einen Anfall begünstigen.</p></div><div><b>Akut symptomatisch</b><p>Hypoglykämie, andere Stoffwechselstörung, Intoxikation oder Entzug, Infektion, SHT und intrakranielle Blutung müssen präklinisch mitgedacht werden.</p></div></div><p>Schlafmangel und Fieber können die Anfallsschwelle senken. Ein erstmaliger Anfall verlangt besonders sorgfältige Ursachen- und Verletzungssuche.</p></>)}
    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", <><SeizureTypeComparison /><div className="pulmo-symptoms">{["Beginn und Dauer beobachtet", "Tonus / rhythmische Zuckungen", "Blickwendung oder fokaler Beginn", "Bewusstseinsänderung", "Zungenbiss / Verletzung", "Postiktale Müdigkeit / Verwirrtheit"].map(x => <span key={x}>{x}</span>)}</div><p>Auch myoklonische oder atonische Phänomene sind möglich. Nach dem Anfall können vorübergehend Sprachstörung oder Lähmung auftreten (<b>Todd-Parese</b>); ein Schlaganfall ist damit nicht ausgeschlossen. Augenzeugenbericht und – falls vorhanden – ein sicher aufgenommenes Video helfen bei der Einordnung.</p><aside className="red-flags"><span>!</span><div><small>Red Flags</small><h3>Verlauf statt Einzelzeichen</h3><p>Über 5 Minuten anhaltende Konvulsionen, Anfallsserie ohne Erholung, fehlende Vigilanzbesserung, persistierende fokale Ausfälle, Trauma, Fieber oder Atemstörung erfordern sofortige Neubewertung.</p></div></aside></>)}
    {section("05", "Komplikationen und Gefahren", <div className="rib-fracture-grid">{[["Status epilepticus", "Fortgesetzte Entladungen und wiederholte Anfälle ohne Erholung sind zeitkritisch."], ["Atemweg und Atmung", "Hypoventilation, Hypoxie, Sekret und Aspiration können auftreten – auch nach einem Medikament."], ["Trauma", "Sturz, Kopfverletzung, Zungenbiss und weitere Begleitverletzungen prüfen."], ["Ursache übersehen", "Hypoglykämie, kardiale Rhythmusstörung, Blutung oder Infektion können entscheidend sein."]].map(([a,b]) => <div key={a}><b>{a}</b><span>{b}</span></div>)}</div>)}
    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", <div className="material-chips">{["EKG / RR / SpO₂", "BZ-Messgerät", "O₂ / Beatmungsbeutel", "Absaugung / Atemweg", "i.v.-Zugangsmaterial", "Midazolam nach VFA", "MAD für intranasale Gabe", "i.m.-Material", "Schutz / Transport"].map(x => <span key={x}>{x}</span>)}</div>)}
    {section("07", "Erstmaßnahmen und Anamnese", <><div className="pulmo-care-grid"><div><span>01</span><b>Zeit &amp; Schutz</b><small>Beginn notieren, Umgebung sichern, Kopf vor Verletzung schützen. Nicht gewaltsam festhalten und nichts in den Mund stecken.</small></div><div><span>02</span><b>cABCDE</b><small>Atmung, Atemweg, Kreislauf und Verletzungen fortlaufend prüfen; Absaugung und Beatmung bereithalten.</small></div><div><span>03</span><b>BZ &amp; Monitoring</b><small>Blutzucker früh messen, EKG, SpO₂, RR und Vitalverlauf dokumentieren.</small></div><div><span>04</span><b>Nach dem Anfall</b><small>Atemweg sichern, bei erhaltener Atmung nach Situation seitlich lagern, reorientieren und neurologischen Verlauf kontrollieren.</small></div></div><h3>SAMPLERS · fokussiert</h3><div className="samplers-grid">{[["S · Symptome", "Beginn, Dauer, fokale Zeichen, Erholung"], ["A · Allergien", "Bekannte Unverträglichkeiten"], ["M · Medikamente", "Antikonvulsiva, Einnahmefehler, Sedativa"], ["P · Vorgeschichte", "Epilepsie, Diabetes, früherer Anfall"], ["L · Letzte Aufnahme", "Nahrung, Alkohol, Substanzen"], ["E · Ereignis", "Sturz, Trauma, Fieber, Schlafentzug"], ["R · Risiken", "Schwangerschaft, Entzug, Infektion"], ["S · Schwangerschaft", "Falls möglich gezielt erfragen" ]].map(([a,b]) => <p key={a}><b>{a}</b>{b}</p>)}</div><p>Zeugen konkret nach Anfallsbeginn, Seitenbetonung, Dauer und Rückkehr zum Ausgangszustand fragen. Eine Zungenverletzung oder Inkontinenz allein beweist den epileptischen Ursprung nicht.</p></>)}
    {section("08", "Differenzialdiagnosen und Entscheidungsfindung", <><div className="differential-grid">{["Konvulsive Synkope / Arrhythmie", "Herz-Kreislauf-Stillstand", "Hypoglykämie", "Schlaganfall / Hirnblutung", "Schädel-Hirn-Trauma", "Intoxikation / Entzug", "Meningitis / Enzephalitis", "Dissoziativer Anfall"].map(x => <span key={x}>{x}</span>)}</div><aside className="diagnostic-boundary"><span>!</span><div><b>Zuckungen schließen einen Kreislaufstillstand nicht aus</b><p>Bei fehlenden Lebenszeichen Reanimation priorisieren. BZ und EKG früh erfassen; nach dem Anfall Bewusstsein und fokale Neurologie erneut beurteilen.</p></div></aside><p>Ein <b>bereits beendeter</b> Einzelanfall ohne erneute Krampfaktivität ist keine Routineindikation für Midazolam. Bei erstem Anfall oder anhaltendem Defizit klinische Abklärung organisieren.</p></>)}
    {section("09", "Weitere Maßnahmen · Thüringer VFA 29", <><div className="pulmo-compare"><div><small>Anfall beendet</small><h3>Überwachen und Ursache suchen</h3><p>Atemweg, BZ, Trauma und neurologische Erholung prüfen. Nicht routinemäßig ein Benzodiazepin nachgeben.</p></div><div><small>Anfall läuft / beginnt erneut</small><h3>VFA 29 anwenden</h3><p>Atemwegs- und Beatmungsbereitschaft, i.v. / i.n. / i.m. je nach Situation; nach jeder Gabe Atmung, Kreislauf und Anfallsaktivität prüfen.</p></div></div><h3>Midazolam · erste Gabe bei laufendem Krampfanfall</h3><div className="pulmo-medicine-grid"><div><small>i.v. · 1 mg/ml</small><b>3 mg langsam i.v. = 3 ml</b><p>Bei liegendem, sicherem Zugang.</p></div><div><small>i.n. · 5 mg/ml</small><b>10 mg = 2 ml</b><p>Mit MAD auf beide Nasenlöcher verteilen.</p></div><div><small>i.m. · 5 mg/ml</small><b>&gt; 40 kg: 10 mg = 2 ml</b><p>&lt; 40 kg: 5 mg = 1 ml, jeweils aus 5 mg/ml.</p></div></div><h3>Nach 5 Minuten · falls anhaltend oder erneut</h3><div className="pulmo-care-grid"><div><span>i.v.</span><b>2 mg = 2 ml</b><small>Langsam i.v., Konzentration 1 mg/ml.</small></div><div><span>i.n.</span><b>5 mg = 1 ml</b><small>Auf beide Nasenlöcher verteilen, Konzentration 5 mg/ml.</small></div><div><span>i.m.</span><b>&gt; 40 kg: 5 mg = 1 ml</b><small>&lt; 40 kg: 2,5 mg = 0,5 ml, jeweils aus 5 mg/ml.</small></div><div><span>↻</span><b>Erneut nach 5 Minuten</b><small>Bei weiterem Anfall nach anderen Ursachen suchen und eskalieren.</small></div></div><p>Die VFA unterscheidet i.m. die Gewichtskategorien <b>&gt; 40 kg</b> und <b>&lt; 40 kg</b>. Für genau 40 kg ist in VFA 29 keiner der beiden i.m.-Pfade angegeben; bei dieser Grenze Rücksprache halten. Notarzt nach Lage und lokalen Vorgaben früh nachfordern, Transport und lückenloses Monitoring fortsetzen.</p></>)}
    {section("10", "VFA Thüringen 2026/2027 und Anlage B2A", <><p>Originalseiten in guter Auflösung. Die Bilder lassen sich einklappen und zur genauen Ansicht öffnen.</p><div className="vfa-stack"><Vfa src="/lessons/krampfanfall/vfa-29-krampfanfall.png" alt="Originalalgorithmus VFA 29 Krampfanfall mit Midazolam-Dosierungen und Wiederbeurteilung" caption="VFA 29 · Krampfanfall" /></div><h3>Anlage B2A · Konzentrationen</h3><p><b>i.v.:</b> 5 mg/5 ml = 1 mg/ml, unverdünnt. <b>i.n./i.m.:</b> 15 mg/3 ml = 5 mg/ml, unverdünnt. Vor Gabe Wirkstoff, Konzentration, Applikationsweg und Volumen abgleichen.</p><Figure src="/lessons/krampfanfall/b2a-midazolam.png" alt="Anlage B2A mit den zwei Midazolam-Zeilen: intravenös 1 mg/ml und intranasal beziehungsweise intramuskulär 5 mg/ml" caption="B2A · Midazolam, relevante Zeilen" wide /><MidazolamSyringe /></>)}
    {children}
    <p className="lesson-source">Grundlage: Print 12.pdf. Anfallsklassifikation: <a href="https://www.ilae.org/guidelines/guidelines-and-reports/updated-classification-of-epileptic-seizures-position-paper-of-the-international-league-against-epilepsy/updated-classification-of-epileptic-seizures-position-paper-of-the-international-league-against-epilepsy" target="_blank" rel="noreferrer">ILAE-Klassifikation</a>. Rettungsdienstliche Ergänzung: <a href="https://rd-factsheets.de/fs/krampfanfall/" target="_blank" rel="noreferrer">RD-Factsheets · Krampfanfall</a>. Medikamentengaben und Dosierungen: <a href="https://www.aelrd-thueringen.de/verfahrensanweisungen-fuer-den-thueringer-rettungsdienst-algorithmen/" target="_blank" rel="noreferrer">Thüringer VFA 2026/27, Nr. 29 und B2A</a>. Abgleich Erstereignis: <a href="https://www.dgn.org/leitlinie/erster-epileptischer-anfall-und-epilepsien-im-erwachsenenalter" target="_blank" rel="noreferrer">DGN-Leitlinie</a>.</p>
  </article>;
}
