import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function LungenoedemLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, title: string, body: ReactNode) => <section className="lesson-section" key={number}><header className="chapter-heading"><span>{number}</span><div><small>Kardiales Lungenödem</small><h2>{title}</h2></div></header><div className="lesson-prose script-copy">{body}</div></section>;

  return <article className="lesson-article lungenoedem-lesson">
    <div className="lesson-intro"><p className="lead">Flüssigkeit in Interstitium und Alveolen behindert den Gasaustausch. Präklinisch zählen Atemarbeit, Oxygenierung, Kreislauf und die rasche Suche nach der auslösenden Ursache.</p></div>

    {section("01", "Definition", <><p>Ein Lungenödem ist der Austritt von Flüssigkeit aus der Lungenstrombahn in das Zwischenzellgewebe und später in die Alveolen. Häufig entsteht es durch eine Dekompensation der Linksherzinsuffizienz.</p><div className="pulmo-compare"><div><small>Druckproblem</small><h3>Kardiales Lungenödem</h3><p>Linksherzversagen erhöht den Druck im Lungenvenen- und Kapillarbett.</p><span>Linksherzinsuffizienz · ACS · Rhythmusstörung · hypertensiver Notfall</span></div><div><small>Schranken- oder Druckproblem</small><h3>Nichtkardiales Lungenödem</h3><p>Eine geschädigte Blut-Luft-Schranke oder verringerter onkotischer Druck begünstigt den Flüssigkeitsaustritt.</p><span>Rauch-/Reizgase · Anaphylaxie · Höhenaufenthalt · Proteinmangel</span></div></div></>)}

    {section("02", "Anatomie und Physiologie", <><p>Die Luft gelangt über Nase oder Mund, Rachen, Kehlkopf und Luftröhre in Bronchien, Bronchiolen und schließlich die Alveolen. Die Nase erwärmt, befeuchtet und reinigt sie. Die rechte Lunge besitzt drei, die linke zwei Lappen.</p><div className="pulmo-anatomy-grid"><div><small>Luftweg</small><b>Obere Atemwege</b><p>Nasenhöhle und Rachen; der Kehlkopf schützt mit der Epiglottis den Eingang der unteren Atemwege.</p></div><div><small>Verteilung</small><b>Untere Atemwege</b><p>Trachea mit Knorpelspangen, Bronchien und knorpelfreie Bronchiolen.</p></div><div><small>Austausch</small><b>Alveolen</b><p>Dünne Blut-Luft-Schranke: O₂ diffundiert ins Blut, CO₂ in die Ausatemluft.</p></div></div><Figure src="/lessons/lungenoedem/atemwege-alveolen.jpg" alt="Beschriftete Übersicht von oberen und unteren Atemwegen, Lungenlappen, Bronchien und Alveolen" caption="Atemwege, Lunge und Alveolen" wide /><p>Beim Einatmen kontrahiert das Zwerchfell, das Thoraxvolumen nimmt zu und Luft strömt ein. Die Ausatmung erfolgt in Ruhe überwiegend passiv. O₂ wird vorwiegend an Hämoglobin gebunden transportiert; CO₂ überwiegend als Bikarbonat.</p><div className="reading-columns"><div><h3>Blutversorgung</h3><p>Die Pulmonalarterien und -venen bilden die <b>Vasa publica</b> für den Gasaustausch. Bronchialgefäße aus dem Körperkreislauf versorgen das Lungengewebe als <b>Vasa privata</b>.</p></div><div><h3>Brustfell und Surfactant</h3><p>Der Flüssigkeitsfilm im Pleuraspalt ermöglicht reibungsarmes Gleiten und koppelt Lunge und Thorax. Surfactant senkt die Oberflächenspannung der Alveolen und wirkt ihrem Kollaps entgegen.</p></div></div><Figure src="/lessons/lungenoedem/alveolen-surfactant.jpg" alt="Originalgrafik zu Pneumozyten Typ 1 und 2 sowie Bildung und Funktion des Surfactants" caption="Alveolen, Pneumozyten und Surfactant" wide /></>)}

    {section("03", "Pathophysiologie und Ursachen", <><p>Im Kapillarbett stehen hydrostatischer Druck, onkotischer Druck, Gefäßdurchlässigkeit und Lymphabfluss im Gleichgewicht. Bei Linksherzversagen staut sich Blut über den linken Vorhof in die Lungenvenen zurück. Der hydrostatische Druck steigt; Flüssigkeit gelangt zunächst ins Interstitium und später in die Alveolen.</p><div className="pulmo-path"><span>Linksherzversagen</span><i>→</i><span>Lungenvenöser Rückstau</span><i>→</i><span>Kapillardruck steigt</span><i>→</i><span>Interstitium / Alveolen</span><i>→</i><span>Hypoxämie</span></div><p>Alveoläre Flüssigkeit beeinträchtigt den Gasaustausch und die Surfactant-Wirkung; Atelektasen können folgen. Der Verlauf reicht von interstitieller Einlagerung über alveoläre Überflutung und Schaumbildung bis zur Asphyxie.</p><aside className="diagnostic-boundary"><span>≠</span><div><b>Nichtkardiale Entstehung unterscheiden</b><p>Rauch- und Reizgase oder Anaphylaxie erhöhen vor allem die Gefäßdurchlässigkeit. Bei ausgeprägtem Proteinmangel sinkt der onkotische Druck. Diese Ursachen werden nicht einfach mit dem kardialen Medikamentenpfad gleichgesetzt.</p></div></aside></>)}

    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", <><div className="pulmo-symptoms"><span>Akute Dyspnoe / Orthopnoe</span><span>Tachypnoe und erhöhte Atemarbeit</span><span>Feuchte Rasselgeräusche</span><span>Angst, Unruhe, Kaltschweißigkeit</span><span>Tachykardie, ggf. Zyanose</span><span>Schaumiger Auswurf möglich</span></div><p>Ein bekannter Linksherzbefund oder ein akuter Auslöser wie ACS, Rhythmusstörung oder hypertensiver Notfall stützt die kardiale Ursache. Schaumiger Auswurf ist möglich, aber für die Arbeitsdiagnose nicht erforderlich.</p><aside className="red-flags"><span>!</span><div><small>Red Flags</small><h3>Erschöpfung oder Kreislaufinstabilität</h3><p>Sinkende Vigilanz, zunehmende Atemnot trotz Unterstützung, Hypoxämie, Hypotonie oder drohender Atem-/Kreislaufstillstand verlangen sofortige Re-Evaluation. Inspiratorischer Stridor spricht eher für ein oberes Atemwegsproblem und muss gesondert abgeklärt werden.</p></div></aside></>)}

    {section("05", "Komplikationen und Gefahren", <><div className="pulmo-risk-grid"><div><b>Respiratorisch</b><p>Hypoxämie, Atemmuskelerschöpfung, respiratorisches Versagen und Aspiration.</p></div><div><b>Kardiozirkulatorisch</b><p>Rhythmusstörungen, Schock und hypoxischer Herz-Kreislauf-Stillstand.</p></div></div><p>Eine CO₂-Retention kann bei Erschöpfung oder zusätzlicher ventilatorischer Störung auftreten. Anaphylaxie ist vor allem eine mögliche Ursache eines nichtkardialen Ödems, keine typische Folge des kardialen Lungenödems.</p></>)}

    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", <div className="material-chips">{["Notfallrucksack", "Monitoring / 12-Kanal-EKG", "Pulsoxymeter / RR", "CPAP/ASB + Kapnometrie", "O₂ / Beatmungsgerät", "Absaugung", "i.v.-Material", "Glyceroltrinitrat", "Furosemid", "Wärmeerhalt"].map(x => <span key={x}>{x}</span>)}</div>)}

    {section("07", "Erstmaßnahmen und Anamnese", <><div className="pulmo-care-grid"><div><span>01</span><b>cABCDE</b><small>Atemarbeit, SpO₂, AF, Vigilanz und Kreislauf zuerst.</small></div><div><span>02</span><b>Position & Ruhe</b><small>Wache Patientin oder Patienten atemerleichternd aufrecht lagern und beruhigen.</small></div><div><span>03</span><b>Monitoring</b><small>EKG, RR, SpO₂, Kapnometrie bei CPAP/ASB; Verlauf kontrollieren.</small></div><div><span>04</span><b>Ursache suchen</b><small>12-Kanal-EKG nach VFA innerhalb von 10 Minuten mit 50 mm/s.</small></div></div><h3>SAMPLERS und OPQRST · kurz und gezielt</h3><div className="samplers-grid"><p><b>S · Symptome</b>Beginn, Atemnot, Husten, Thoraxschmerz</p><p><b>A · Allergien</b>Relevante Unverträglichkeiten</p><p><b>M · Medikamente</b>Diuretika, Herzmittel, PDE-5-Hemmer</p><p><b>P · Patientengeschichte</b>Herzinsuffizienz, Klappenfehler, COPD</p><p><b>L · Letzte Aufnahme</b>Essen, Trinken</p><p><b>E · Ereignis</b>Belastung, Infekt, Auslöser</p><p><b>R · Risiken</b>ACS, Hypertonie, Rhythmusstörung</p><p><b>S · Schwangerschaft</b>Falls relevant</p></div><p>Sauerstoff an der Oxygenierung ausrichten; ein pauschaler Zielwert passt nicht zu allen Patienten, besonders bei Hyperkapnierisiko. Ein i.v.-Zugang und die Notarztnachforderung werden nach Zustand und VFA vorbereitet.</p></>)}

    {section("08", "Differenzialdiagnosen und Entscheidungsfindung", <><div className="differential-grid">{["Asthma / COPD", "Pneumonie", "Pneumothorax", "Lungenarterienembolie", "Anaphylaxie", "Rauchgas- oder Reizgasexposition", "Hyperventilation"].map(x => <span key={x}>{x}</span>)}</div><p>Feuchte Rasselgeräusche, Orthopnoe und passende Herzvorgeschichte stützen ein kardiales Lungenödem, beweisen es aber nicht allein. ACS kann die Ursache des Ödems sein und muss mit dem EKG aktiv gesucht werden. Stridor, einseitig fehlendes Atemgeräusch oder allergische Zeichen lenken zu anderen akuten Pfaden.</p></>)}

    {section("09", "Weitere Maßnahmen nach Thüringer VFA", <><div className="pulmo-vfa-flow"><div><span>06</span><b>CPAP/ASB früh prüfen</b><small>Bei Indikation und ohne Kontraindikation; Kapnometrie und engmaschige Kontrolle.</small></div><div><span>15</span><b>12-Kanal-EKG</b><small>Innerhalb von 10 Minuten mit 50 mm/s; Ursache mitbehandeln.</small></div><div><span>RR</span><b>Nitrat-Schranke</b><small>0,4 mg Glyceroltrinitrat nur bei RR<sub>sys</sub> ≥ 120 mmHg und keinen PDE-5-Hemmern in 48 h.</small></div><div><span>i.v.</span><b>Furosemid</b><small>40 mg langsam i.v. gemäß VFA 15; Wirkung, Kreislauf und Transport überwachen.</small></div></div><div className="pulmo-medicine-grid"><div><small>Glyceroltrinitrat</small><b>0,4 mg · 1 Hub</b><p>NO-vermittelte Vasodilatation senkt vor allem die Vorlast. Vorher RR und PDE-5-Hemmer prüfen.</p></div><div><small>Furosemid</small><b>40 mg · langsam i.v.</b><p>Schleifendiuretikum; die Anlage B2A führt 40 mg/4 ml unverdünnt auf.</p></div></div><aside className="pulmo-morphine-note"><b>Morphin ist kein pauschaler Lungenödem-Schritt.</b><span>VFA 06 nennt 2 mg i.v. im Zweig „CPAP-Therapie nicht toleriert“. Bei fehlenden Schutzreflexen, Erbrechen, Bewusstlosigkeit oder anderen Kontraindikationen darf CPAP nicht unkritisch fortgesetzt werden.</span></aside><div className="eug-destination"><span>→</span><div><small>Transport und Übergabe</small><b>Geeignete kardiologische / intensivmedizinische Versorgung</b><p>Auslöser, EKG, Atem- und Kreislaufverlauf, CPAP-Eignung sowie Medikamente mit Zeitpunkt und Wirkung voranmelden.</p></div></div></>)}

    {section("10", "VFA Thüringen 2026/2027 und Anlage", <><p>Die hochauflösenden Originalseiten sind einklappbar und im Vollbild lesbar. Bei der Durchführung gelten die VFA, die lokale Freigabe sowie die individuelle Indikations- und Kontraindikationsprüfung.</p><div className="vfa-stack"><Vfa src="/lessons/lungenoedem/vfa-06-cpap.png" alt="Original-VFA 06 zur nicht-invasiven CPAP/ASB-Therapie und Kapnometrie" caption="VFA 06 · CPAP/ASB und Kapnometrie" /><Vfa src="/lessons/lungenoedem/vfa-15-kardiales-lungenoedem.png" alt="Original-VFA 15 Basisalgorithmus kardiales Lungenödem Thüringen 2026/27" caption="VFA 15 · Kardiales Lungenödem" /></div><h3>Anlage B2A · relevante Wirkstoffe</h3><div className="figure-grid"><Figure src="/lessons/lungenoedem/b2a-glycerolnitrat.png" alt="Originalausschnitt der Thüringer Anlage B2A zur Glycerolnitrat-Dosierung" caption="B2A · Glycerolnitrat" wide /><Figure src="/lessons/lungenoedem/b2a-furosemid.png" alt="Originalausschnitt der Thüringer Anlage B2A zur Furosemid-Dosierung und Konzentration" caption="B2A · Furosemid" wide /></div></>)}

    {children}
    <p className="lesson-source">Grundlage: „Print 9.pdf“. Therapie und Dosierungen: <a href="https://www.aelrd-thueringen.de/verfahrensanweisungen-fuer-den-thueringer-rettungsdienst-algorithmen/" target="_blank" rel="noreferrer">Thüringer Verfahrensanweisungen 2026/27</a>, VFA 06 und 15 sowie Anlage B2A. Klinische Einordnung und Verzicht auf routinemäßiges Morphin: <a href="https://academic.oup.com/eurheartj/article/42/36/3599/6358045" target="_blank" rel="noreferrer">ESC-Leitlinie Herzinsuffizienz</a>; Sauerstoffziel individuell gemäß <a href="https://www.brit-thoracic.org.uk/clinical-resources/guidelines/emergency-oxygen/" target="_blank" rel="noreferrer">BTS-Sauerstoffleitlinie</a>.</p>
  </article>;
}
