import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct: boolean];
function q(n: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3): ThoraxtraumaChoiceQuestion {
  const shift = (n * 2) % options.length;
  const mixed = [...options.slice(shift), ...options.slice(0, shift)];
  return { id: `lungenoedem-q-${String(n).padStart(2, "0")}`, mode: "multiple", prompt, options: mixed.map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty };
}

export const lungenoedemFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "lungenoedem-card-01", area: "Definition", question: "Definieren Sie das Lungenödem und grenzen Sie kardiale von nichtkardialen Mechanismen ab.", answer: "Flüssigkeit gelangt aus dem Kapillarbett ins Interstitium und später in Alveolen. Kardial dominiert der erhöhte hydrostatische Druck bei linksseitigem Rückstau; nichtkardial können Permeabilität oder onkotischer Druck verändert sein." },
  { id: "lungenoedem-card-02", area: "Anatomie", question: "Verfolgen Sie den Luftweg bis zum Ort des Gasaustauschs und nennen Sie die Lungenlappen.", answer: "Nase/Mund → Rachen → Kehlkopf → Trachea → Bronchien → Bronchiolen → Alveolen. Rechts drei, links zwei Lappen. Der Gasaustausch findet an der dünnen Blut-Luft-Schranke statt." },
  { id: "lungenoedem-card-03", area: "Physiologie", question: "Welche Rolle spielen Surfactant, Pleura und Zwerchfell für die Atmung?", answer: "Surfactant senkt die Oberflächenspannung und hält Alveolen offen. Die Pleura koppelt Lunge und Thorax bei reibungsarmem Gleiten. Zwerchfellkontraktion vergrößert bei der Inspiration das Thoraxvolumen." },
  { id: "lungenoedem-card-04", area: "Pathophysiologie", question: "Leiten Sie aus Linksherzversagen die Hypoxämie beim Lungenödem her.", answer: "Linksherzversagen → pulmonalvenöser Rückstau → erhöhter Kapillardruck → interstitielle, dann alveoläre Flüssigkeit → gestörter Gasaustausch und Hypoxämie." },
  { id: "lungenoedem-card-05", area: "Ursachen", question: "Nennen Sie drei mögliche kardiale Auslöser und zwei nichtkardiale Mechanismen.", answer: "Kardial: ACS, Rhythmusstörung, hypertensiver Notfall. Nichtkardial: erhöhte Gefäßpermeabilität etwa durch Reizgase oder Anaphylaxie; erniedrigter onkotischer Druck bei starkem Proteinmangel." },
  { id: "lungenoedem-card-06", area: "Arbeitsdiagnose", question: "Welche Befundkombination stützt das kardiale Lungenödem und welche Zeichen zeigen eine drohende Dekompensation?", answer: "Akute Dyspnoe/Orthopnoe, Tachypnoe, feuchte Rasselgeräusche und passender Herzbefund. Sinkende Vigilanz, zunehmende Atemarbeit, Hypoxämie oder Hypotonie sind Warnzeichen." },
  { id: "lungenoedem-card-07", area: "Differenzialdiagnose", question: "Warum sind Stridor und einseitig fehlendes Atemgeräusch nicht einfach als kardiales Lungenödem zu deuten?", answer: "Stridor spricht eher für ein oberes Atemwegsproblem, einseitig fehlendes Atemgeräusch unter anderem für Pneumothorax. Beide Befunde verlangen eine andere Gefährdungs- und Therapieprüfung." },
  { id: "lungenoedem-card-08", area: "Erstmaßnahmen", question: "Priorisieren Sie die ersten präklinischen Maßnahmen bei wachem Patienten mit schwerer Atemnot.", answer: "cABCDE, atemerleichternde aufrechte Position, Beruhigung, SpO₂/RR/AF/Vigilanz und EKG überwachen, Ursache suchen, CPAP/ASB-Eignung prüfen, Notarzt/Transport planen." },
  { id: "lungenoedem-card-09", area: "Anamnese", question: "Welche gezielten Fragen sind vor Glyceroltrinitrat besonders entscheidend?", answer: "Aktueller systolischer Blutdruck und Einnahme eines PDE-5-Hemmers in den letzten 48 Stunden; außerdem Beschwerdebeginn, Thoraxschmerz, Herzvorgeschichte und Dauermedikation." },
  { id: "lungenoedem-card-10", area: "VFA 06", question: "Beschreiben Sie Indikation, wichtige Gegenanzeigen und Überwachung der CPAP/ASB-Therapie.", answer: "Bei schwerer Dyspnoe/Lungenödem mit unzureichender Oxygenierung trotz O₂ und erhöhter Atemarbeit prüfen. Fehlende Schutzreflexe, Erbrechen, Bewusstlosigkeit, Gesichtsverletzung oder fehlende Kooperation sprechen dagegen. Kapnometrie, SpO₂, Atemarbeit und Kreislauf fortlaufend prüfen." },
  { id: "lungenoedem-card-11", area: "VFA 15", question: "Welche diagnostische Zeitvorgabe und welche beiden Medikamente enthält die Thüringer VFA 15?", answer: "12-Kanal-EKG innerhalb von 10 Minuten bei 50 mm/s. Glyceroltrinitrat 0,4 mg (ein Hub) nur bei RRsys ≥ 120 mmHg und ohne PDE-5-Hemmer in 48 h; Furosemid 40 mg langsam i.v." },
  { id: "lungenoedem-card-12", area: "Morphin", question: "Ist Morphin beim kardialen Lungenödem ein Routinebaustein der VFA?", answer: "Nein. VFA 06 nennt 2 mg i.v. im Zweig bei nicht tolerierter CPAP-Therapie; eine pauschale Morphingabe ist daraus nicht abzuleiten." },
  { id: "lungenoedem-card-13", area: "Entscheidung", question: "Ein Patient hat Orthopnoe, feuchte Rasselgeräusche, RRsys 108 mmHg und vor 24 Stunden einen PDE-5-Hemmer eingenommen. Welche Konsequenz folgt?", answer: "Glyceroltrinitrat nach VFA 15 nicht geben: RRsys unter 120 mmHg und PDE-5-Hemmer innerhalb 48 Stunden. Atem-/Kreislaufversorgung, CPAP-Eignung und Auslöser weiter prüfen; zeitkritisch transportieren." },
];

export const lungenoedemQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen erklären die Entstehung eines kardialen Lungenödems?", [["Linksherzversagen erhöht den Druck im pulmonalvenösen Stromgebiet", true], ["Der erhöhte Kapillardruck begünstigt interstitielle Flüssigkeit", true], ["Alveoläre Flüssigkeit kann den Gasaustausch behindern", true], ["Ein pulmonalarterieller Embolus ist definitionsgemäß die häufigste kardiale Ursache", false], ["Ein erniedrigter onkotischer Druck ist der zwingende Mechanismus jedes kardialen Ödems", false]], "Linksseitiger Rückstau erhöht den hydrostatischen Druck; Flüssigkeit erreicht Interstitium und Alveolen.", 2),
  q(2, "Welche Zuordnungen der Atemwege sind korrekt?", [["Bronchiolen liegen distal der Bronchien", true], ["Alveolen sind der wesentliche Ort des Gasaustauschs", true], ["Der rechte Lungenflügel hat zwei Lappen", false], ["Die Trachea führt direkt in die Pleura", false], ["Die Epiglottis schützt den Kehlkopfeingang beim Schlucken", true]], "Der Luftweg verzweigt sich bis zu den Alveolen; rechts liegen drei Lungenlappen.", 1),
  q(3, "Welche Aussagen zur Atemphysiologie sind richtig?", [["Surfactant senkt die alveoläre Oberflächenspannung", true], ["Zwerchfellkontraktion vergrößert das Thoraxvolumen", true], ["CO₂ wird ausschließlich an Hämoglobin gebunden transportiert", false], ["O₂ wird überwiegend an Hämoglobin gebunden transportiert", true], ["Der Pleuraspalt ist normalerweise luftgefüllt", false]], "Surfactant stabilisiert Alveolen; Inspiration erfolgt durch Thoraxexpansion.", 2),
  q(4, "Welche Befunde stützen ein kardiales Lungenödem, ohne es für sich allein zu beweisen?", [["Orthopnoe", true], ["Feuchte Rasselgeräusche", true], ["Bekannte Linksherzinsuffizienz", true], ["Isolierter inspiratorischer Stridor", false], ["Einseitig fehlendes Atemgeräusch", false]], "Klinische Konstellation und Herzvorgeschichte sind entscheidend; Stridor/Pneumothoraxzeichen lenken anders.", 2),
  q(5, "Welche Situationen sind mögliche Auslöser oder Begleitursachen einer akuten Linksherzdekompensation?", [["Akutes Koronarsyndrom", true], ["Hypertensiver Notfall", true], ["Relevante Rhythmusstörung", true], ["Isolierte Gesichtsverletzung", false], ["Allein eine normale Körpertemperatur", false]], "Ischämie, Druckbelastung und Rhythmusstörungen können die linksventrikuläre Funktion akut verschlechtern.", 2),
  q(6, "Welche Aussagen grenzen nichtkardiale Mechanismen sinnvoll ab?", [["Rauch-/Reizgase können die alveolokapilläre Schranke schädigen", true], ["Anaphylaxie kann die Gefäßpermeabilität erhöhen", true], ["Starker Proteinmangel kann den onkotischen Druck verringern", true], ["Jedes nichtkardiale Ödem beruht zwingend auf Linksherzversagen", false], ["Die Ursache ist präklinisch für die Therapieauswahl unerheblich", false]], "Permeabilitäts- und onkotische Mechanismen sind vom linksseitigen Druckrückstau zu unterscheiden.", 2),
  q(7, "Ein Patient mit zunehmender Atemnot wird somnolent. Welche Bewertungen sind zutreffend?", [["Die Vigilanzänderung ist ein Warnzeichen drohenden Atemversagens", true], ["Atemarbeit und Ventilation müssen erneut geprüft werden", true], ["Eine zuvor normale SpO₂ macht die Verschlechterung bedeutungslos", false], ["CO₂-Retention kann bei Erschöpfung mitwirken", true], ["CPAP darf ohne Prüfung der Schutzreflexe unverändert fortgesetzt werden", false]], "Sinkende Vigilanz verlangt Re-Evaluation; Schutzreflexe und Beatmungsstrategie sind neu zu beurteilen.", 3),
  q(8, "Welche Ausrüstung ist bei schwerem kardialem Lungenödem unmittelbar sinnvoll?", [["Monitoring mit RR, SpO₂ und 12-Kanal-EKG", true], ["CPAP/ASB-System mit Kapnometrie", true], ["Absaugung und alternative Beatmungsmöglichkeit", true], ["Nur ein Pulsoxymeter ohne Kreislaufüberwachung", false], ["Ausschließlich Verbandmaterial", false]], "Atemwegsunterstützung, Monitoring, Absaugung und EKG gehören zur Vorbereitung.", 1),
  q(9, "Welche Erstmaßnahmen sind bei wachem Patienten mit ausgeprägter Orthopnoe passend?", [["Atemerleichternde aufrechte Position", true], ["cABCDE und wiederholte Verlaufskontrollen", true], ["Rasche Suche nach kardialem Auslöser mittels EKG", true], ["Routinehaftes Flachlagern ungeachtet der Atemnot", false], ["Aufschub des Transports bis zum Verschwinden aller Rasselgeräusche", false]], "Lagerung, Beurteilung, Monitoring und Ursachenklärung laufen parallel zur Transportplanung.", 2),
  q(10, "Welche Angaben der gezielten SAMPLERS-Anamnese können die Therapieentscheidung unmittelbar verändern?", [["Einnahme eines PDE-5-Hemmers in den letzten 48 Stunden", true], ["Aktuelle Medikation und Herzvorgeschichte", true], ["Begleitender Thoraxschmerz und zeitlicher Beginn", true], ["Allein die Schuhgröße", false], ["Nur die letzte Mahlzeit ohne weitere Atem- oder Kreislaufdaten", false]], "PDE-5-Hemmer beeinflussen GTN; Herz-/Ischämiehinweise und Zeitachse helfen bei der Ursache.", 2),
  q(11, "Welche Befunde verlangen eine kritische Überprüfung von CPAP/ASB?", [["Erbrechen", true], ["Fehlende Schutzreflexe", true], ["Gesichtsverletzung mit unzureichendem Maskensitz", true], ["Wacher, kooperativer Patient mit schwerer Atemarbeit", false], ["SpO₂ unter 90 % trotz Sauerstoff als alleiniger Ausschlussgrund", false]], "VFA 06 nennt Bewusstseins- und Aspirationsrisiken sowie Verletzungen/fehlende Kooperation als Kontraindikationen.", 3),
  q(12, "Welche Aussagen zur Thüringer VFA 06 treffen zu?", [["Kapnometrie gehört zur Überwachung bei CPAP/ASB", true], ["PEEP und PASB beginnen gemäß Algorithmus jeweils bei 5", true], ["PEEP/PASB können nach Algorithmus bis 10 gesteigert werden", true], ["CPAP wird ohne Beachtung von Kontraindikationen begonnen", false], ["Morphin wird grundsätzlich vor jedem CPAP-Versuch gegeben", false]], "VFA 06 beschreibt Startwerte, Steigerung, Überwachung und Kontraindikationen.", 3),
  q(13, "Welcher EKG-Pfad gehört zur Thüringer VFA 15?", [["12-Kanal-EKG innerhalb von 10 Minuten", true], ["Schreibgeschwindigkeit 50 mm/s", true], ["Möglichen ACS-Auslöser mitbeurteilen", true], ["EKG erst nach vollständiger Rückbildung der Atemnot", false], ["Ein einzelner Pulsoxymeterwert ersetzt das EKG", false]], "Die VFA fordert früh ein 12-Kanal-EKG mit 50 mm/s.", 2),
  q(14, "Ein Patient hat RRsys 116 mmHg und nahm vor 36 Stunden Sildenafil. Was folgt für Glyceroltrinitrat nach VFA 15?", [["GTN wegen RRsys unter 120 mmHg nicht geben", true], ["Die PDE-5-Einnahme liegt innerhalb der 48-Stunden-Sperre", true], ["Atmung und Kreislauf trotzdem weiter behandeln und überwachen", true], ["GTN ist erlaubt, weil RRsys über 90 mmHg liegt", false], ["Die Kontraindikation entfällt durch normale SpO₂", false]], "Die Thüringer VFA nutzt RRsys 120 mmHg und 48 Stunden PDE-5-Sperre; beides ist hier nicht erfüllt.", 3),
  q(15, "Welche Aussagen zu Glyceroltrinitrat in der VFA 15 sind korrekt?", [["Ein Hub enthält 0,4 mg", true], ["Der systolische Druck muss mindestens 120 mmHg betragen", true], ["PDE-5-Hemmer in den letzten 48 Stunden sprechen dagegen", true], ["Die Dosis beträgt 40 mg langsam i.v.", false], ["GTN ersetzt die Prüfung des Kreislaufs nach Gabe", false]], "VFA 15 und B2A: 0,4 mg als ein Hub; RR und PDE-5-Anamnese beachten.", 3),
  q(16, "Welche Aussagen zu Furosemid im Thüringer Lungenödem-Algorithmus stimmen?", [["Die VFA nennt 40 mg langsam i.v.", true], ["B2A führt 40 mg in 4 ml unverdünnt auf", true], ["Kreislauf und klinische Reaktion müssen weiter beobachtet werden", true], ["Die 40 mg werden als ein GTN-Sprühstoß verabreicht", false], ["Furosemid behebt jede nichtkardiale Ödemursache gleichermaßen", false]], "Furosemid ist der in VFA 15 angegebene i.v.-Wirkstoff; nichtkardiale Ursachen sind abzugrenzen.", 3),
  q(17, "Welche Aussagen zur Morphingabe beim kardialen Lungenödem treffen nach VFA 06 zu?", [["Sie ist bei jedem Patienten vor CPAP obligatorisch", false], ["Die VFA nennt 2 mg i.v. bei nicht tolerierter CPAP-Therapie", true], ["Vigilanz und Atmung müssen nach einer Gabe weiter kontrolliert werden", true], ["Sie ist Teil der B2A-GTN-Dosierung", false], ["CPAP-Kontraindikationen werden durch Morphin aufgehoben", false]], "Morphin ist in der VFA auf den Nichttoleranz-Zweig begrenzt; der Patient bleibt überwachungspflichtig.", 3),
  q(18, "Ein Patient hat Orthopnoe, feuchte Rasselgeräusche und stechenden Brustschmerz. Welche Schlussfolgerungen sind angemessen?", [["ACS kann Auslöser des Ödems sein", true], ["Ein 12-Kanal-EKG ist früh erforderlich", true], ["Die Atem- und Kreislaufsituation muss parallel stabilisiert werden", true], ["Feuchte Rasselgeräusche schließen eine Ischämie sicher aus", false], ["Nur der Schmerzcharakter entscheidet über GTN", false]], "Kardiales Lungenödem und ACS können gleichzeitig vorliegen; VFA 15 fordert EKG und Basisversorgung.", 3),
  q(19, "Welche differenzialdiagnostischen Hinweise verändern den ersten Verdacht?", [["Einseitig fehlendes Atemgeräusch lenkt zum Pneumothorax", true], ["Stridor lenkt zu einer oberen Atemwegsobstruktion", true], ["Urtikaria und Exposition lenken zur Anaphylaxie", true], ["Orthopnoe beweist eine COPD-Exazerbation", false], ["Normale Körpertemperatur schließt Lungenarterienembolie aus", false]], "Die Befundkonstellation bestimmt den Pfad; einzelne unspezifische Zeichen beweisen nichts.", 3),
  q(20, "Welche Aussagen zur Sauerstoffgabe sind fachlich tragfähig?", [["Oxygenierung und klinischer Verlauf leiten die Gabe", true], ["Ein Hyperkapnierisiko kann die Zielwahl beeinflussen", true], ["Sauerstoff ersetzt weder Ventilationsbeurteilung noch Ursachenklärung", true], ["Alle Patienten brauchen ungeachtet ihrer Situation denselben Maximalflow", false], ["Eine normale SpO₂ schließt ein drohendes Atemversagen sicher aus", false]], "Sauerstoff wird titriert; Vigilanz, Ventilation und Grunderkrankung müssen mitbeurteilt werden.", 3),
  q(21, "Schwere Dyspnoe, RRsys 132 mmHg, SpO₂ 86 % trotz O₂, Patient wach und kooperativ. Welche Schritte passen zur Thüringer Versorgung?", [["CPAP/ASB nach Kontraindikationsprüfung mit Kapnometrie erwägen", true], ["12-Kanal-EKG zeitnah ableiten und Auslöser suchen", true], ["GTN nur nach zusätzlicher PDE-5-Anamnese prüfen", true], ["Wegen SpO₂ 86 % sofort auf Monitoring verzichten", false], ["Morphin obligatorisch vor Beginn der CPAP-Therapie geben", false]], "VFA 06/15 kombinieren Atemunterstützung, EKG und medikamentöse Sicherheitsprüfung; Morphin ist nicht Routine.", 3),
];
