"use client";

import { useState } from "react";

type MedicationEffect = {
  name: string;
  group: string;
  effect: string;
  interactions: string;
  contraindications: string;
  sideEffects: string;
};

const medications: MedicationEffect[] = [
  { name: "Acetylsalicylsäure (ASS)", group: "Thrombozytenaggregationshemmer", effect: "Hemmt irreversibel COX-1 und COX-2. Über COX-1 sinkt in den Thrombozyten die Thromboxanbildung und damit die Aggregation; zugleich werden protektive Prostaglandine der Magenschleimhaut vermindert. Über COX-2 werden Entzündung, Schmerz und Fieber beeinflusst.", interactions: "Antikoagulanzien, andere Thrombozytenhemmer und NSAR können Blutungs- beziehungsweise Magen-Darm-Risiken erhöhen.", contraindications: "ASS-Asthma oder bekannte ASS-Unverträglichkeit, erhöhte Blutungsneigung sowie aktives Magen- oder Darmulkus.", sideEffects: "Bronchospasmus, Blutungen, Magen-Darm-Beschwerden, Kopfschmerzen und Schwindel." },
  { name: "Heparin", group: "Antikoagulanz", effect: "Verstärkt die Wirkung von Antithrombin III. Dadurch werden vor allem Thrombin (Faktor IIa), Faktor Xa und weitere Gerinnungsfaktoren indirekt gehemmt.", interactions: "Andere Antikoagulanzien, Thrombozytenhemmer und NSAR können die Blutungsgefahr erhöhen. Bei Heparin-induzierter Thrombozytopenie darf Heparin nicht erneut gegeben werden.", contraindications: "Akute zerebrale Blutung, relevante Blutungsneigung, Heparinallergie, aktive Blutung und aktives Magen- oder Darmulkus.", sideEffects: "Blutungen, besonders an Haut, Schleimhäuten und Wunden; außerdem Thrombozytopenie und Überempfindlichkeitsreaktionen." },
  { name: "Atrovent (Ipratropium)", group: "Anticholinerges Bronchodilatans", effect: "Blockiert muskarinische Rezeptoren an der Bronchialmuskulatur und vermindert die vagal vermittelte Bronchokonstriktion.", interactions: "Andere anticholinerge Wirkstoffe können Mundtrockenheit, Tachykardie und Harnverhalt verstärken.", contraindications: "Überempfindlichkeit gegen Ipratropium oder Atropin-Derivate; Aerosolkontakt mit den Augen bei Engwinkelglaukom vermeiden.", sideEffects: "Mundtrockenheit, Husten, Kopfschmerz, Tachykardie und selten paradoxer Bronchospasmus." },
  { name: "Histakut (Dimetinden)", group: "H₁-Antihistaminikum", effect: "Blockiert H₁-Rezeptoren und dämpft histaminvermittelte Symptome wie Juckreiz, Urtikaria und Schleimhautschwellung.", interactions: "Alkohol, Opioide, Benzodiazepine und andere Sedativa können die zentrale Dämpfung verstärken.", contraindications: "Überempfindlichkeit; bei Engwinkelglaukom, Harnverhalt und Epilepsie besondere Vorsicht.", sideEffects: "Müdigkeit, Schläfrigkeit, Schwindel, Mundtrockenheit und gelegentlich Blutdruckabfall." },
  { name: "Vomex (Dimenhydrinat)", group: "Antiemetikum / H₁-Antihistaminikum", effect: "Dämpft Übelkeit und Erbrechen über H₁-Rezeptorblockade und anticholinerge Effekte im Brechzentrum und Vestibularsystem.", interactions: "Sedativa, Alkohol und Opioide verstärken die ZNS-Dämpfung; anticholinerge Arzneimittel können Nebenwirkungen addieren.", contraindications: "Überempfindlichkeit, Engwinkelglaukom, Harnverhalt und bestimmte Krampfneigungen berücksichtigen.", sideEffects: "Müdigkeit, Schwindel, Mundtrockenheit, Sehstörungen, Tachykardie und selten paradoxe Unruhe." },
  { name: "Midazolam", group: "Benzodiazepin", effect: "Verstärkt die GABA-A-vermittelte Hemmung und wirkt anxiolytisch, sedierend, amnestisch, muskelrelaxierend und antikonvulsiv.", interactions: "Opioide, Alkohol und andere Sedativa verstärken Atemdepression, Sedierung und Hypotonie.", contraindications: "Schwere Ateminsuffizienz, ungesicherter Atemweg, Schock und bekannte Überempfindlichkeit erfordern besondere Vorsicht.", sideEffects: "Atemdepression, Hypotonie, Sedierung, paradoxe Reaktionen und bei älteren Menschen verlängerte Wirkung." },
  { name: "Tranexamsäure", group: "Antifibrinolytikum", effect: "Hemmt die Aktivierung von Plasminogen zu Plasmin und stabilisiert dadurch bestehende Fibringerinnsel.", interactions: "Andere prothrombotische Wirkstoffe können das Thromboserisiko erhöhen; die Gerinnungssituation muss im Gesamtkontext bewertet werden.", contraindications: "Aktive thromboembolische Erkrankung, schwere Nierenfunktionsstörung und relevante Überempfindlichkeit beachten.", sideEffects: "Übelkeit, Erbrechen, Durchfall, Blutdruckabfall bei zu schneller Gabe, Sehstörungen und selten Krampfanfälle." },
  { name: "Furosemid", group: "Schleifendiuretikum", effect: "Hemmt den Na⁺-K⁺-2Cl⁻-Cotransporter im aufsteigenden Teil der Henle-Schleife und steigert die Natrium- und Wasserausscheidung.", interactions: "Andere Antihypertensiva oder ototoxische Arzneimittel können Risiken verstärken; NSAR können die Diurese abschwächen.", contraindications: "Anurie, schwere Hypovolämie, ausgeprägte Elektrolytstörungen und unbehandelter Harnabflussstau.", sideEffects: "Hypotonie, Dehydratation, Hypokaliämie, Hyponatriämie, metabolische Alkalose und selten Ototoxizität." },
  { name: "Urapidil", group: "α₁-Blocker / zentral wirksames Antihypertensivum", effect: "Senkt den peripheren Gefäßwiderstand über α₁-Blockade und vermindert zentral den sympathischen Blutdruckreflex.", interactions: "Andere Antihypertensiva, Nitrate, PDE-5-Hemmer und Alkohol können die Blutdrucksenkung verstärken.", contraindications: "Überempfindlichkeit, ausgeprägte Hypotonie und hämodynamisch relevante Aortenisthmus- oder Klappenstenose berücksichtigen.", sideEffects: "Schwindel, Kopfschmerz, Übelkeit, Hypotonie und gelegentlich Bradykardie oder Palpitationen." },
  { name: "Nifedipin", group: "Dihydropyridin-Calciumantagonist", effect: "Blockiert L-Typ-Calciumkanäle in der Gefäßmuskulatur und führt vor allem zu arterieller Vasodilatation und Nachlastsenkung.", interactions: "CYP3A4-Hemmer, andere Antihypertensiva und Grapefruitsaft können die Wirkung verändern oder verstärken.", contraindications: "Kardiogener Schock, schwere Hypotonie und relevante akute Kreislaufinstabilität.", sideEffects: "Kopfschmerz, Flush, Schwindel, Knöchelödeme, Hypotonie und reflektorische Tachykardie." },
  { name: "Amiodaron", group: "Antiarrhythmikum Klasse III", effect: "Verlängert über Kaliumkanalblockade die Repolarisation und Refraktärzeit; zusätzlich werden Natrium- und Calciumkanäle sowie β-Rezeptoren beeinflusst.", interactions: "QT-verlängernde Arzneimittel, Digoxin, bestimmte Statine und orale Antikoagulanzien können relevante Wechselwirkungen zeigen.", contraindications: "Ausgeprägte Bradykardie oder höhergradiger AV-Block ohne Schrittmacher sowie bekannte Überempfindlichkeit.", sideEffects: "Bradykardie, Hypotonie, QT-Verlängerung, Übelkeit und bei Langzeitgabe Schilddrüsen-, Lungen- oder Lebertoxizität." },
  { name: "Partusisten (Fenoterol)", group: "β₂-Sympathomimetikum / Tokolytikum", effect: "Stimuliert β₂-Rezeptoren der Uterusmuskulatur und vermindert dadurch vorübergehend die Wehentätigkeit.", interactions: "Andere Sympathomimetika können Tachykardie und Hypokaliämie verstärken; Betablocker können die Wirkung abschwächen.", contraindications: "Relevante maternale Tachyarrhythmie, schwere kardiale Erkrankung und Situationen, in denen eine Wehenhemmung nicht vertretbar ist.", sideEffects: "Tachykardie, Palpitationen, Tremor, Unruhe, Hyperglykämie und Hypokaliämie." },
  { name: "Atropin", group: "Anticholinergikum", effect: "Blockiert muskarinische Acetylcholinrezeptoren und hebt vagale Bremsen am Herzen auf.", interactions: "Andere anticholinerge Wirkstoffe können Mundtrockenheit, Tachykardie und Verwirrtheit verstärken.", contraindications: "Relevante Tachykardie, Engwinkelglaukom und höhergradiger infra-Hisärer AV-Block erfordern besondere Vorsicht.", sideEffects: "Tachykardie, Mundtrockenheit, Mydriasis, Akkommodationsstörung und Harnverhalt." },
  { name: "Epinephrin / Adrenalin", group: "Sympathomimetikum", effect: "β₁ steigert Herzfrequenz und Kontraktilität, α₁ erhöht Gefäßtonus und Blutdruck.", interactions: "Andere Sympathomimetika verstärken die Wirkung; Betablocker können kardiale Effekte verändern.", contraindications: "Bei tachykarden Rhythmusstörungen, schwerer Hypertonie oder Ischämie nur im passenden vitalen VFA-Kontext.", sideEffects: "Tachykardie, Herzrhythmusstörungen, Blutdruckanstieg, Tremor und Unruhe." },
  { name: "Morphin", group: "Opioidanalgetikum", effect: "Wirkt überwiegend am μ-Rezeptor analgetisch und sedierend; zusätzlich kann es Atemantrieb und Kreislauf beeinflussen.", interactions: "Alkohol, Benzodiazepine und andere Sedativa verstärken Atemdepression und Bewusstseinsminderung.", contraindications: "Relevante Atemdepression, ungesicherter Atemweg und schwere Hypotonie sprechen gegen eine unkritische Gabe.", sideEffects: "Atemdepression, Sedierung, Hypotonie, Übelkeit, Erbrechen und Juckreiz." },
  { name: "Esketamin", group: "Dissoziatives Analgetikum", effect: "Antagonisiert NMDA-Rezeptoren und reduziert die Schmerzverarbeitung bei meist erhaltener Spontanatmung.", interactions: "Sympathomimetika und weitere zentral wirksame Substanzen können Blutdruck, Herzfrequenz und Sedierung beeinflussen.", contraindications: "Unkontrollierte Hypertonie, relevante Ischämie oder fehlende Überwachungs- und Atemwegsbereitschaft beachten.", sideEffects: "Blutdruck- und Herzfrequenzanstieg, Übelkeit, Hypersalivation und belastende Aufwachreaktionen." },
  { name: "Naloxon", group: "Opioidantagonist", effect: "Verdrängt Opioide kompetitiv von μ-Rezeptoren und kann die opioidbedingte Atemdepression aufheben.", interactions: "Die Wirkung kann kürzer als die des Opioids sein; nach anfänglicher Besserung ist eine erneute Atemdepression möglich.", contraindications: "Keine absolute Kontraindikation im vitalen Notfall; Entzug, Schmerz und Agitation nach Aufhebung einplanen.", sideEffects: "Akutes Entzugssyndrom, Schmerzen, Agitation, Übelkeit, Erbrechen und Blutdruckanstieg." },
  { name: "Metamizol (Novalgin)", group: "Nichtopioidanalgetikum", effect: "Wirkt analgetisch, antipyretisch und spasmolytisch durch zentrale und periphere Mechanismen.", interactions: "Andere blutdrucksenkende oder überempfindlichkeitsauslösende Arzneien können Hypotonie beziehungsweise Reaktionen begünstigen.", contraindications: "Frühere Agranulozytose, Pyrazolon-Überempfindlichkeit und relevante Kreislaufinstabilität beachten.", sideEffects: "Hypotonie, Überempfindlichkeitsreaktionen und selten Agranulozytose." },
  { name: "Butylscopolamin (Buscopan)", group: "Spasmolytikum", effect: "Entspannt glatte Muskulatur über eine periphere anticholinerge Wirkung.", interactions: "Andere anticholinerge Medikamente können Tachykardie, Harnverhalt und Mundtrockenheit verstärken.", contraindications: "Engwinkelglaukom, Harnverhalt, mechanische Stenosen und relevante Tachyarrhythmien berücksichtigen.", sideEffects: "Mundtrockenheit, Tachykardie, Sehstörungen und Harnverhalt." },
  { name: "Glyceroltrinitrat (Nitro)", group: "Vasodilatator", effect: "Setzt Stickstoffmonoxid frei und erweitert vor allem venöse Gefäße; dadurch sinkt die Vorlast.", interactions: "PDE-5-Hemmer können einen gefährlichen Blutdruckabfall auslösen; andere Vasodilatatoren verstärken ihn.", contraindications: "Hypotonie, Rechtsherzinfarkt, ausgeprägte Aortenstenose und PDE-5-Einnahme ausschließen.", sideEffects: "Kopfschmerzen, Hypotonie, Schwindel, Flush und reflektorische Tachykardie." },
  { name: "Salbutamol", group: "β₂-Sympathomimetikum", effect: "Entspannt die glatte Bronchialmuskulatur und erweitert die Atemwege.", interactions: "Andere Sympathomimetika können Tachykardie und Tremor verstärken; Diuretika können Hypokaliämie begünstigen.", contraindications: "Unkontrollierte Tachyarrhythmie und schwere kardiale Instabilität erfordern besondere Vorsicht.", sideEffects: "Tremor, Tachykardie, Palpitationen, Unruhe und mögliche Hypokaliämie." },
  { name: "Prednisolon", group: "Glukokortikoid", effect: "Dämpft entzündliche Prozesse und Schleimhautödem; der Wirkungseintritt ist verzögert.", interactions: "Blutzucker und Infektionszeichen können beeinflusst werden; die Wirkung ersetzt keine Akutbronchodilatation.", contraindications: "Schwere unbehandelte Infektionen und bekannte Überempfindlichkeit im jeweiligen VFA-Kontext beachten.", sideEffects: "Hyperglykämie, Dyspepsie, Schlaf- oder Stimmungsschwankungen und erhöhte Infektanfälligkeit." },
];

export default function MedicationEffectsLibrary() {
  const [search, setSearch] = useState("");
  const query = search.trim().toLocaleLowerCase("de-DE");
  const filtered = medications.filter((item) => `${item.name} ${item.group} ${item.effect}`.toLocaleLowerCase("de-DE").includes(query));
  return <section className="page-section medication-effects-page">
    <div className="section-heading"><div><span className="eyebrow">Pharmakologie · Lernübersicht</span><h1>Wirkung der Medikamente</h1><p>Rettungsdienstliche Wirkprofile zum Wiederholen. Dosierungen bleiben an die gültige Thüringer VFA gebunden.</p></div><div className="source-badge"><b>{filtered.length}</b><span>Treffer</span></div></div>
    <label className="medication-search"><span aria-hidden="true">⌕</span><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Medikament suchen …" aria-label="Medikament suchen" />{search && <button type="button" onClick={() => setSearch("")} aria-label="Suche löschen">×</button>}</label>
    <div className="medication-effects-grid">{filtered.map((item) => <article key={item.name} className="medication-effect-card"><header><span className="medication-effect-icon">✦</span><div><small>{item.group}</small><h2>{item.name}</h2></div></header><div><b>Wirkung</b><p>{item.effect}</p><b className="medication-side-effect-label">Nebenwirkungen</b><p>{item.sideEffects}</p></div><div><b>Wechselwirkungen</b><p>{item.interactions}</p></div><aside><b>Kontraindikationen</b><p>{item.contraindications}</p></aside></article>)}</div>
    {!filtered.length && <div className="medication-search-empty"><b>Kein Medikament gefunden.</b><span>Prüfe die Schreibweise oder suche nach einem Wirkstoff.</span></div>}
  </section>;
}
