import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct: boolean];
function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  const shift = (number * 2) % options.length;
  return { id: `myokardinfarkt-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty };
}

export const myokardinfarktFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "myokardinfarkt-card-01", area: "Definition", question: "Definieren Sie den Myokardinfarkt und grenzen Sie ihn von Angina pectoris ab.", answer: "Der Myokardinfarkt ist der irreversible Untergang von Herzmuskelzellen infolge anhaltender Ischämie. Angina pectoris beschreibt eine vorübergehende Ischämie ohne nachgewiesene Nekrose. Präklinisch ist die sichere Trennung allein über Beschwerden oder ein Einzel-EKG nicht möglich." },
  { id: "myokardinfarkt-card-02", area: "Koronarphysiologie", question: "Warum erfolgt ein großer Teil der Koronarperfusion in der Diastole?", answer: "Während der Systole komprimiert das kontrahierende Myokard besonders die intramuralen Gefäße des linken Ventrikels. In der Diastole lässt diese Kompression nach, sodass der Druck aus der Aortenwurzel den Koronarfluss ermöglicht. Tachykardie verkürzt die Diastole und kann die Ischämie verstärken." },
  { id: "myokardinfarkt-card-03", area: "Koronaranatomie", question: "Ordnen Sie RIVA, RCX und RCA ihren wichtigen Versorgungsgebieten zu.", answer: "RIVA versorgt vor allem Vorderwand und vordere Septumanteile; RCX vor allem laterale und je nach Dominanz posteriore Anteile; RCA häufig rechtes Herz, inferiore Wand und Anteile des Erregungsleitungssystems. Die individuelle Koronardominanz variiert." },
  { id: "myokardinfarkt-card-04", area: "Pathophysiologie", question: "Leiten Sie den Weg von der Plaqueruptur bis zur Myokardnekrose her.", answer: "Plaqueruptur oder -erosion legt thrombogenes Material frei. Thrombozyten haften an, werden aktiviert und aggregieren; die Gerinnung stabilisiert den Thrombus mit Fibrin. Der Koronarfluss fällt ab, ATP-Mangel und Azidose stören Elektrik und Kontraktion, anhaltende Ischämie führt zur Nekrose." },
  { id: "myokardinfarkt-card-05", area: "STEMI/NSTEMI", question: "Wie unterscheiden sich STEMI und NSTEMI, und welche Fehlannahme ist zu vermeiden?", answer: "STEMI zeigt eine charakteristische persistierende ST-Hebung in zusammengehörigen Ableitungen und verlangt die sofortige Reperfusionsstrategie. NSTEMI zeigt keine persistierende ST-Hebung, kann aber ST-Senkung, T-Negativierung oder zunächst ein unauffälliges EKG aufweisen. Ein einzelnes unauffälliges EKG schließt einen Infarkt nicht aus." },
  { id: "myokardinfarkt-card-06", area: "EKG-Lokalisation", question: "Ordnen Sie die wichtigsten Ableitungsgruppen den Infarktregionen zu.", answer: "II, III und aVF betrachten die inferiore Wand; I, aVL, V5 und V6 die laterale Wand; V1 bis V4 septale und anteriore Bereiche. Bei inferiorem STEMI wird eine rechtsventrikuläre Beteiligung insbesondere mit V4R geprüft." },
  { id: "myokardinfarkt-card-07", area: "Arbeitsdiagnose", question: "Welche typische und welche atypische Symptomkonstellation stützen den Infarktverdacht?", answer: "Typisch sind anhaltender retrosternaler Druck mit Ausstrahlung, Dyspnoe, Kaltschweißigkeit, Blässe, Übelkeit und Angst. Bei älteren Menschen, Frauen oder Diabetes können Dyspnoe, Schwäche, Übelkeit oder Leistungsknick ohne klassischen Schmerz dominieren." },
  { id: "myokardinfarkt-card-08", area: "Gefahren", question: "Leiten Sie elektrische und hämodynamische Infarktkomplikationen her.", answer: "Ischämische Zellen werden elektrisch instabil: VT, Kammerflimmern, Bradyarrhythmie oder Asystolie sind möglich. Verlust kontraktiler Masse vermindert Schlagvolumen und kann Linksherzversagen, Lungenödem und kardiogenen Schock auslösen." },
  { id: "myokardinfarkt-card-09", area: "Anamnese", question: "Welche Angaben aus SAMPLERS und OPQRST verändern Ihre präklinische Entscheidung besonders?", answer: "Beginn, Dauer, Dynamik, Ausstrahlung, Belastungsbezug, Synkope und Dyspnoe; bekannte KHK, Stent oder Infarkt; Antikoagulation und Allergien; PDE-5-Hemmer mit Zeitpunkt; Blutungs- oder Schlaganfallanamnese sowie Hinweise auf Aortendissektion." },
  { id: "myokardinfarkt-card-10", area: "Differenzialdiagnose", question: "Welche Befunde zwingen vor ASS und Heparin zur besonderen Prüfung einer Aortendissektion?", answer: "Plötzlicher maximaler oder reißender Schmerz, Ausstrahlung zwischen die Schulterblätter, Pulsdefizit, relevante Blutdruckdifferenz, neurologischer Ausfall oder bekanntes Aortenaneurysma. Eine akute Aortendissektion ist eine Kontraindikation nach VFA 14." },
  { id: "myokardinfarkt-card-11", area: "VFA 12", question: "Strukturieren Sie die ersten zehn Minuten bei ACS-Verdacht.", answer: "cABCDE, Ruhe und angepasste Lagerung, kontinuierliches Monitoring und Defibrillationsbereitschaft, Sauerstoff zielgerichtet mit Ziel-SpO₂ über 90 %, 12-Kanal-EKG mit 50 mm/s innerhalb von zehn Minuten, Prüfung des Nitro-Pfads sowie frühe Zielklinik- und Reperfusionsentscheidung." },
  { id: "myokardinfarkt-card-12", area: "VFA 13", question: "Nennen Sie Dosis, Kontrolle, Wiederholung und Kontraindikationen von Glyceroltrinitrat.", answer: "0,4 mg als ein Hub sublingual; nach fünf Minuten Wirkung und Blutdruck prüfen; maximal zwei Wiederholungen. Nicht bei PDE-5-Hemmern innerhalb 48 Stunden, systolischem Blutdruck unter 120 mmHg oder Verdacht auf inferioren/Hinterwandinfarkt." },
  { id: "myokardinfarkt-card-13", area: "VFA 14", question: "Nennen Sie Indikation, Kontraindikationen und Dosierungen für ASS und Heparin.", answer: "Indikation: STEMI oder neu aufgetretener Linksschenkelblock. Kontraindikationen: aktive Blutung, frischer Schlaganfall, akute Aortendissektion. ASS 250 mg i.v. oder orale Äquivalenzdosis; Heparin 100 I.E./kgKG i.v., maximal 5.000 I.E." },
  { id: "myokardinfarkt-card-14", area: "Pharmakologie", question: "Vergleichen Sie die Wirkprinzipien von ASS, Heparin und Nitro.", answer: "ASS hemmt COX-1 irreversibel und vermindert Thromboxan A₂ sowie Thrombozytenaggregation. Heparin verstärkt Antithrombin und hemmt Gerinnungsfaktoren. Nitro setzt NO frei, steigert cGMP und relaxiert Gefäßmuskulatur, wodurch vor allem Vorlast und Wandspannung sinken." },
  { id: "myokardinfarkt-card-15", area: "Transport", question: "Was bedeutet präklinische Reperfusionsstrategie bei STEMI?", answer: "EKG früh sichern und digital übermitteln, PCI-Zentrum beziehungsweise Herzkatheterlabor voranmelden, den Patienten unter Monitoring und Reanimationsbereitschaft direkt in die geeignete Struktur transportieren und vermeidbare Verzögerungen verhindern." },
];

export const myokardinfarktQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen definieren einen Myokardinfarkt fachlich korrekt?", [["Anhaltende Ischämie führt zum irreversiblen Untergang von Herzmuskelzellen", true], ["Die Diagnose verbindet klinischen Kontext mit EKG und Biomarkern", true], ["Jeder retrosternale Schmerz beweist bereits eine Myokardnekrose", false], ["Eine Besserung nach Nitro schließt einen Infarkt zuverlässig aus", false], ["Ein akuter Koronarthrombus ist ein häufiger, aber nicht der einzige Infarktmechanismus", true]], "Myokardinfarkt bedeutet ischämisch bedingte Myokardnekrose; Beschwerden allein sind weder Beweis noch Ausschluss.", 1),
  q(2, "Welche anatomisch-physiologischen Aussagen zur Koronarversorgung treffen zu?", [["Die Koronararterien entspringen aus der Aortenwurzel", true], ["Der linke Ventrikel wird überwiegend während der Diastole perfundiert", true], ["Tachykardie kann durch Verkürzung der Diastole eine Ischämie verstärken", true], ["Die Koronarvenen münden überwiegend direkt in den linken Vorhof", false], ["Koronargefäße bleiben während der Systole vollständig unkomprimiert", false]], "Systolische Myokardkompression begrenzt den Koronarfluss; die Diastole ist besonders für die linksventrikuläre Perfusion wichtig.", 1),
  q(3, "Welche Zuordnungen der Koronararterien sind angemessen?", [["RIVA versorgt wesentliche Anteile von Vorderwand und vorderem Septum", true], ["RCX versorgt vor allem laterale und abhängig von der Dominanz posteriore Bereiche", true], ["RCA kann inferiore Wand, rechtes Herz und Teile des Reizleitungssystems versorgen", true], ["RCA versorgt bei jedem Menschen ausschließlich die Vorderwand", false], ["Die individuelle Koronardominanz ist klinisch bedeutungslos", false]], "Versorgungsgebiete überlappen und variieren mit der Koronardominanz; starre absolute Zuordnungen sind fehleranfällig.", 2),
  q(4, "Welche Schritte fördern nach Plaqueruptur einen akuten Koronarverschluss?", [["Freilegung thrombogenen Materials", true], ["Thrombozytenadhäsion und -aktivierung", true], ["Fibrinbildung durch die plasmatische Gerinnung", true], ["Sofortige dauerhafte Vasodilatation als Schutzreaktion", false], ["Vollständige Auflösung des Thrombus allein durch den Blutstrom", false]], "Thrombozytenpfropf und Fibrinnetz stabilisieren den wachsenden Koronarthrombus.", 1),
  q(5, "Welche Folgen entstehen früh durch die myokardiale Ischämie?", [["ATP-Mangel beeinträchtigt Ionenpumpen", true], ["Anaerober Stoffwechsel fördert die intrazelluläre Azidose", true], ["Elektrische Instabilität und Kontraktionsstörung können vor Nekrosezeichen auftreten", true], ["Die Kontraktilität steigt dauerhaft kompensatorisch im Ischämiegebiet", false], ["Rhythmusstörungen sind erst Tage nach dem Infarkt möglich", false]], "Energiemangel stört Membranpotenziale und Kontraktion früh und begründet die unmittelbare Reanimationsbereitschaft.", 2),
  q(6, "Welche Aussagen grenzen STEMI und NSTEMI korrekt ab?", [["Ein STEMI zeigt persistierende ST-Hebungen in zusammengehörigen Ableitungen", true], ["Ein NSTEMI kann ST-Senkungen oder T-Negativierungen zeigen", true], ["Ein unauffälliges Erst-EKG schließt einen NSTEMI nicht aus", true], ["NSTEMI bedeutet immer einen harmlosen, kleinen Infarkt", false], ["STEMI und NSTEMI lassen sich allein über die Schmerzstärke unterscheiden", false]], "Die EKG-Morphologie steuert den Akutpfad; sie erlaubt keine Bewertung allein nach Schmerzintensität oder Infarktgröße.", 2),
  q(7, "Welche Ableitungsgruppen sind korrekt zugeordnet?", [["II, III und aVF betrachten die inferiore Wand", true], ["I, aVL, V5 und V6 betrachten die laterale Wand", true], ["V1 bis V4 erfassen septale beziehungsweise anteriore Bereiche", true], ["V3 und V4 sind spezifische Standardableitungen des rechten Ventrikels", false], ["V4R gehört zu den regulären linkspräkordialen Ableitungen", false]], "Bei Verdacht auf rechtsventrikuläre Beteiligung wird rechtspräkordial ergänzt; V3/V4 sind keine rechten Standardableitungen.", 2),
  q(8, "Bei inferiorer ST-Hebung: Welche Überlegungen sind besonders wichtig?", [["Eine rechtsventrikuläre Beteiligung soll mit rechten Ableitungen geprüft werden", true], ["V4R kann die rechtsventrikuläre Beteiligung stützen", true], ["Vorlastsenkende Therapie kann bei Rechtsherzbeteiligung problematisch sein", true], ["Nitro ist nach VFA 13 bei Verdacht auf Hinterwandinfarkt grundsätzlich freigegeben", false], ["Inferiore Veränderungen beweisen eine isolierte Linksherzerkrankung", false]], "Inferiorer Infarkt und Rechtsherzbeteiligung erfordern besondere Vorsicht mit Vorlastsenkung; VFA 13 führt den Hinterwandverdacht als Kontraindikation.", 3),
  q(9, "Welche Befunde stützen die Arbeitsdiagnose Myokardinfarkt?", [["Anhaltender retrosternaler Druck mit typischer Ausstrahlung", true], ["Dyspnoe zusammen mit Kaltschweißigkeit und Blässe", true], ["Übelkeit, Angst oder Leistungsknick können Teil der Präsentation sein", true], ["Reproduzierbarer lokaler Druckschmerz beweist einen Infarkt", false], ["Fehlende Ausstrahlung schließt eine koronare Ursache aus", false]], "Die Diagnose stützt sich auf eine Konstellation; einzelne Symptome sind weder beweisend noch ausschließend.", 1),
  q(10, "Welche Präsentationen müssen als mögliches atypisches ACS ernst genommen werden?", [["Akute Dyspnoe ohne ausgeprägten Thoraxschmerz bei Diabetes", true], ["Unklare Schwäche und Übelkeit bei einer älteren Patientin", true], ["Synkope mit vegetativen Zeichen und neuem Leistungsabfall", true], ["Nur maximaler Vernichtungsschmerz erfüllt den ACS-Verdacht", false], ["Ein atypischer Verlauf ist ausschließlich bei Kindern zu erwarten", false]], "Ältere Menschen, Frauen und Menschen mit Diabetes können ohne klassischen Thoraxschmerz präsentieren.", 2),
  q(11, "Welche Komplikationen können unmittelbar aus einem größeren Myokardinfarkt entstehen?", [["Kammerflimmern oder ventrikuläre Tachykardie", true], ["Akutes Linksherzversagen mit Lungenödem", true], ["Kardiogener Schock durch Verlust kontraktiler Masse", true], ["Garantierte stabile Sinusrhythmik in den ersten Stunden", false], ["Ausschließlich eine vorübergehende Blutdrucksteigerung", false]], "Elektrische Instabilität und Pumpversagen sind die zentralen frühen Todesursachen.", 2),
  q(12, "Welche Befunde sprechen für einen kardiogenen Schock nach Infarkt?", [["Hypotonie mit kalter, blasser oder marmorierter Haut", true], ["Bewusstseinsstörung und verminderte periphere Perfusion", true], ["Dyspnoe oder Lungenödem bei niedriger Auswurfleistung", true], ["Warme trockene Haut bei ausgeprägter peripherer Vasodilatation als Leitsymptom", false], ["Ein normaler Schmerzscore schließt den Schock sicher aus", false]], "Die Kombination aus Pumpversagen, Minderperfusion und häufig pulmonaler Stauung stützt den kardiogenen Schock.", 2),
  q(13, "Welche Maßnahmen gehören in die ersten zehn Minuten bei ACS-Verdacht?", [["cABCDE und kontinuierliches Monitoring", true], ["12-Kanal-EKG mit 50 mm/s", true], ["Defibrillationsbereitschaft und wiederholte Vitalzeichenkontrolle", true], ["Belastungsprovokation bis typische Beschwerden auftreten", false], ["Routinemäßige Sauerstoffgabe unabhängig von Oxygenierung und Klinik", false]], "VFA 12 fordert frühes EKG und zielgerichtete Stabilisierung; unnötige Belastung und unkritische Sauerstoffroutine sind nicht angezeigt.", 2),
  q(14, "Welche Informationen aus der Anamnese beeinflussen eine mögliche Nitro-, ASS- oder Heparingabe?", [["PDE-5-Hemmer und Einnahmezeitpunkt", true], ["Aktive Blutung oder frischer Schlaganfall", true], ["Hinweise auf akute Aortendissektion", true], ["Die bevorzugte Hausapotheke", false], ["Eine unauffällige Tetanusimpfung", false]], "PDE-5-Hemmer betreffen die Nitro-Sicherheit; Blutung, frischer Schlaganfall und Aortendissektion die VFA 14.", 2),
  q(15, "Welche Befunde machen eine akute Aortendissektion als Alternative besonders relevant?", [["Plötzlich maximaler oder reißender Schmerz", true], ["Pulsdefizit oder relevante Blutdruckdifferenz", true], ["Neurologischer Ausfall zusammen mit Thorax- oder Rückenschmerz", true], ["Langjährig unveränderte Belastungsangina ohne aktuelle Beschwerden", false], ["Besserung nach Nitro als sicherer Ausschluss der Dissektion", false]], "Vor antithrombotischer Therapie muss die gefährliche Alternative aktiv geprüft werden.", 3),
  q(16, "Welche Aussagen zur Sauerstoffgabe bei Myokardinfarktverdacht sind angemessen?", [["Sie wird an Oxygenierung und klinischen Zustand angepasst", true], ["VFA 12 nennt eine Ziel-SpO₂ über 90 Prozent", true], ["Hypoxämie oder relevante respiratorische Insuffizienz sprechen für Sauerstoff", true], ["Jeder normoxämische Patient benötigt zwingend maximalen Sauerstofffluss", false], ["Sauerstoff ersetzt Monitoring und Reperfusionsstrategie", false]], "Sauerstoff ist eine zielgerichtete Maßnahme, kein Ersatz für Diagnostik oder Reperfusion.", 2),
  q(17, "Welche Aussagen beschreiben Acetylsalicylsäure im STEMI-Pfad korrekt?", [["ASS hemmt COX-1 irreversibel", true], ["Die Thromboxan-A₂-Bildung und Thrombozytenaggregation nehmen ab", true], ["VFA 14 nennt 250 mg i.v. oder eine orale Äquivalenzdosis", true], ["ASS löst einen Koronarthrombus unmittelbar vollständig auf", false], ["Eine aktive Blutung ist für die Gabe unerheblich", false]], "ASS hemmt Plättchen, ist aber kein sofort thrombusauflösendes Medikament; die VFA-Kontraindikationen bleiben verbindlich.", 3),
  q(18, "Welche Aussagen beschreiben Heparin im STEMI-Pfad korrekt?", [["Heparin verstärkt die Wirkung von Antithrombin", true], ["Es hemmt dadurch mehrere aktivierte Gerinnungsfaktoren", true], ["VFA 14 dosiert 100 I.E./kgKG i.v. bis maximal 5.000 I.E.", true], ["Heparin hemmt primär COX-1 in Thrombozyten", false], ["Bei Verdacht auf akute Aortendissektion wird es routinemäßig gegeben", false]], "Heparin greift in die plasmatische Gerinnung ein; Aortendissektion ist eine Kontraindikation des Pfads.", 3),
  q(19, "Welche Voraussetzungen und Grenzen gelten nach VFA 14?", [["STEMI oder neu aufgetretener Linksschenkelblock bilden die Indikation", true], ["Aktive Blutung muss ausgeschlossen werden", true], ["Frischer Schlaganfall und akute Aortendissektion sind Kontraindikationen", true], ["Jeder Thoraxschmerz führt automatisch zu ASS und Heparin", false], ["Ein isoliert erhöhtes Troponin im Labor wäre präklinisch für den Pfad zwingend erforderlich", false]], "VFA 14 ist ein enger algorithmischer Pfad und keine pauschale Thoraxschmerzmedikation.", 3),
  q(20, "Welche Aussagen zum Glyceroltrinitrat-Pfad treffen zu?", [["0,4 mg werden als ein Hub sublingual gegeben", true], ["Nach fünf Minuten werden Wirkung und Blutdruck kontrolliert", true], ["Nach erneuter Prüfung sind höchstens zwei Wiederholungen vorgesehen", true], ["Ein systolischer Blutdruck von 112 mmHg erfüllt die VFA-Voraussetzung", false], ["PDE-5-Hemmer vor 24 Stunden sind ohne Bedeutung", false]], "VFA 13 verlangt RRsys mindestens 120 mmHg und schließt PDE-5-Hemmer innerhalb 48 Stunden aus.", 3),
  q(21, "Ein Patient mit inferioren ST-Hebungen hat RRsys 132 mmHg und nahm keinen PDE-5-Hemmer. Welche Entscheidungen sind richtig?", [["Der Verdacht auf Hinterwandinfarkt spricht nach VFA 13 gegen Nitro", true], ["Rechtspräkordiale Ableitungen können eine Rechtsherzbeteiligung prüfen", true], ["Monitoring und Reperfusionsstrategie werden unverzüglich fortgeführt", true], ["Der ausreichende Blutdruck hebt jede andere Nitro-Kontraindikation auf", false], ["ASS und Heparin werden allein wegen eines normalen Blutdrucks verworfen", false]], "Beim inferioren STEMI bleibt Nitro trotz ausreichendem RR kontraindiziert; VFA 14 und PCI-Strategie werden getrennt geprüft.", 3),
  q(22, "STEMI, 68 kg, keine Kontraindikationen: Welche Dosierungen entsprechen VFA 14?", [["ASS 250 mg i.v. oder orale Äquivalenzdosis", true], ["Heparin 5.000 I.E. i.v. wegen der Maximalgrenze", true], ["Die rechnerischen 6.800 I.E. Heparin werden auf 5.000 I.E. begrenzt", true], ["ASS 500 mg i.v. ist die festgelegte Patientendosis", false], ["Heparin 6.800 I.E. wird trotz Maximalgrenze vollständig gegeben", false]], "100 I.E./kg ergeben rechnerisch 6.800 I.E.; VFA 14 begrenzt die Einzelgabe auf 5.000 I.E.", 3),
  q(23, "Welche Maßnahmen verkürzen bei STEMI sinnvoll die Zeit bis zur Reperfusion?", [["EKG früh ableiten und digital übermitteln", true], ["PCI-Zentrum beziehungsweise Herzkatheterlabor voranmelden", true], ["Direkt in die geeignete Übergabestruktur transportieren", true], ["Den Transport bis zur vollständigen Schmerzfreiheit verzögern", false], ["Vor Anmeldung mehrere ungezielte Diagnostikschleifen abwarten", false]], "Die Behandlung des Verschlusses erfolgt durch rasche Reperfusion; präklinisch werden Diagnoseweg, Anmeldung und Transport optimiert.", 3),
  q(24, "Anhaltender Thoraxdruck, zunächst unauffälliges EKG, später ST-Senkungen, kaltschweißig und dyspnoisch: Welche Bewertungen sind richtig?", [["Ein NSTEMI bleibt trotz fehlender ST-Hebung möglich", true], ["Dynamische EKG-Veränderungen erhöhen die Dringlichkeit", true], ["Monitoring, wiederholte Beurteilung und geeigneter Kliniktransport sind erforderlich", true], ["Ohne ST-Hebung ist eine koronare Ursache ausgeschlossen", false], ["Beschwerdebeginn und Verlauf sind für die Entscheidung bedeutungslos", false]], "NSTEMI kann ohne ST-Hebung auftreten; Dynamik, Klinik und Verlauf bestimmen die Dringlichkeit.", 3),
];
