import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function MyokardinfarktLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, kicker: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>{kicker}</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;

  return <article className="lesson-article angina-pectoris-lesson myokardinfarkt-lesson">
    <div className="lesson-intro myokardinfarkt-intro"><aside className="knowledge-note"><b>Kernidee</b><p>Beim Myokardinfarkt führt eine anhaltende koronare Minderdurchblutung zum Untergang von Herzmuskelzellen. Präklinisch zählen frühes Erkennen, ein 12-Kanal-EKG innerhalb von zehn Minuten, Reanimationsbereitschaft und der direkte Weg zur Reperfusion.</p></aside></div>

    {section("01", "Grundverständnis", "Definition", <><p>Ein <b>Myokardinfarkt</b> ist eine irreversible Schädigung von Herzmuskelgewebe durch eine anhaltende Ischämie. Meist verschließt ein auf einer instabilen atherosklerotischen Plaque entstandener Thrombus eine Koronararterie so weit, dass das nachgeschaltete Myokard nicht mehr ausreichend mit Sauerstoff versorgt wird.</p><div className="pulmo-compare"><div><small>Ischämie ohne nachgewiesene Nekrose</small><h3>Angina pectoris</h3><p>Vorübergehendes Missverhältnis zwischen Sauerstoffangebot und -bedarf. Die Beschwerden allein erlauben präklinisch keine sichere Abgrenzung.</p></div><div><small>Ischämie mit Nekrose</small><h3>Myokardinfarkt</h3><p>Herzmuskelzellen gehen zugrunde. Die klinische Diagnose stützt sich auf Verlauf, EKG und Biomarker; präklinisch wird der ACS-Verdacht zeitkritisch behandelt.</p></div></div></>)}

    {section("02", "Herz und Koronarkreislauf", "Anatomie und Physiologie", <><p>Das Herz liegt im Mediastinum und arbeitet als zwei in Reihe geschaltete Pumpen. Das rechte Herz fördert venöses Blut in den Lungenkreislauf, das linke Herz oxygeniertes Blut in den Körperkreislauf. Klappen sichern den gerichteten Blutfluss.</p><Figure src="/lessons/myokardinfarkt/herz-innenraeume.jpg" alt="Beschriftete Innenräume und Klappen des Herzens" caption="Herzinnenräume, große Gefäße und Herzklappen · zugeschnitten aus dem Anatomieskript" wide /><div className="pulmo-risk-grid"><div><b>Endokard</b><p>Kleidet Herzhöhlen und Klappen aus.</p></div><div><b>Myokard</b><p>Erzeugt die Pumpleistung und ist beim Infarkt betroffen.</p></div><div><b>Epikard und Perikard</b><p>Begrenzen das Herz nach außen und ermöglichen seine reibungsarme Bewegung.</p></div></div><Figure src="/lessons/myokardinfarkt/herzwand.jpg" alt="Schichten der Herzwand mit Myokard, Endokard und Perikard" caption="Herzwand mit der beim Infarkt entscheidenden Muskelschicht" /><p>Die Koronararterien entspringen unmittelbar oberhalb der Aortenklappe. Die linke Koronararterie teilt sich vor allem in RIVA und RCX; die rechte Koronararterie versorgt abhängig vom Versorgungstyp unter anderem rechtes Herz und inferiore Abschnitte. Der überwiegende Koronarfluss erfolgt in der <b>Diastole</b>, weil die intramuralen Gefäße in der Systole komprimiert werden.</p><Figure src="/lessons/myokardinfarkt/koronargefaesse.jpg" alt="Beschriftete Herzkranzgefäße" caption="Koronargefäße und großer venöser Abfluss über den Sinus coronarius" wide /></>)}

    {section("03", "Von der Plaque zur Nekrose", "Ursachen und Pathophysiologie", <><div className="pulmo-path"><span>Endothelschaden</span><i>→</i><span>Atherosklerotische Plaque</span><i>→</i><span>Ruptur oder Erosion</span><i>→</i><span>Thrombozyten + Fibrin</span><i>→</i><span>Ischämie</span><i>→</i><span>Nekrose</span></div><p>Die Ischämie vermindert die aerobe ATP-Produktion. Ionenpumpen versagen, Zellen übersäuern und die elektrische Stabilität nimmt ab. Gleichzeitig sinken Kontraktilität und Schlagvolumen. Je größer das betroffene Areal und je länger der Verschluss besteht, desto höher sind das Risiko für Rhythmusstörungen, Pumpversagen und kardiogenen Schock.</p><div className="pulmo-risk-grid"><div><b>Beeinflussbare Risiken</b><p>Rauchen, Hypertonie, Diabetes mellitus, Fettstoffwechselstörung, Adipositas und Bewegungsmangel.</p></div><div><b>Nicht beeinflussbar</b><p>Alter, familiäre Belastung und bereits bekannte kardiovaskuläre Erkrankung.</p></div><div><b>Steigender Sauerstoffbedarf</b><p>Tachykardie, Hypertonie, Fieber, Stress und hohe kardiale Wandspannung.</p></div></div></>)}

    {section("04", "Arbeitsdiagnose begründen", "Symptome und EKG", <><div className="pulmo-symptoms"><span>Retrosternaler Druck, Enge oder Brennen</span><span>Ausstrahlung in Arm, Schulter, Rücken, Oberbauch oder Kiefer</span><span>Kaltschweißigkeit, fahle Haut, Übelkeit oder Erbrechen</span><span>Dyspnoe, Leistungsknick, Rhythmusstörung, Hypotonie oder Synkope</span><span>Angst und Unruhe</span><span>Atypisch: Schwäche, Übelkeit oder Dyspnoe ohne typischen Schmerz</span></div><p><b>STEMI:</b> persistierende ST-Hebungen in zusammengehörigen Ableitungen sprechen für eine akute transmurale Ischämie und verlangen die sofortige Reperfusionsstrategie. <b>NSTEMI:</b> kann ST-Senkungen, T-Negativierungen oder zunächst kein eindeutiges Ischämiezeichen zeigen; ein unauffälliges Erst-EKG schließt den Infarkt nicht aus.</p><div className="pulmo-symptoms"><span>II, III, aVF · inferior</span><span>I, aVL, V5–V6 · lateral</span><span>V1–V4 · septal/anterior</span><span>V4R · rechtsventrikuläre Beteiligung prüfen</span></div><aside className="knowledge-note"><b>EKG-Zuordnung korrekt lernen</b><p>Bei inferioren Veränderungen wird eine rechtsventrikuläre Beteiligung mit rechtspräkordialen Ableitungen, besonders V4R, gesucht. V3–V4 betrachten primär die Vorderwand und sind keine rechten Standardableitungen.</p></aside></>)}

    {section("05", "Zeitkritische Gefahren", "Komplikationen", <><div className="pulmo-risk-grid"><div><b>Elektrische Instabilität</b><p>Ventrikuläre Tachykardie, Kammerflimmern, Bradyarrhythmie oder Asystolie.</p></div><div><b>Pumpversagen</b><p>Linksherzinsuffizienz, Lungenödem, niedriges Herzzeitvolumen und kardiogener Schock.</p></div><div><b>Mechanische Schäden</b><p>Papillarmuskel-, Septum- oder freie Wandruptur können akut dekompensieren.</p></div><div><b>Folgeereignisse</b><p>Synkope, Sturz, Aspiration und hypoxische Folgeschäden bei Kreislaufstillstand.</p></div></div><aside className="red-flags"><span>!</span><div><small>Prüfungsfalle</small><h3>Ein Einzelbefund schließt den Infarkt nicht aus</h3><p>Schmerzstärke, ein einzelnes EKG und eine Besserung nach Nitro beweisen oder widerlegen einen Infarkt nicht. Entscheidend sind Gesamtkonstellation, Dynamik und wiederholte Beurteilung.</p></div></aside></>)}

    {section("06", "Vorbereitet eintreffen", "Einsatzmaterialien", <><div className="material-chips">{["Monitor / Defibrillator", "12-Kanal-EKG", "Notfallrucksack", "i.v.-Zugangsset", "Sauerstoff und Beatmung", "Absaugung", "ASS, Heparin und Nitro", "Trage / Tragestuhl", "Reanimationsbereitschaft"].map((item) => <span key={item}>{item}</span>)}</div><p>Defibrillationselektroden werden bei instabilem Verlauf früh vorbereitet. Sauerstoff wird nicht routinemäßig, sondern zielgerichtet nach Oxygenierung und klinischem Zustand eingesetzt.</p></>)}

    {section("07", "cABCDE und Anamnese", "Erstmaßnahmen und Diagnostik", <><div className="pulmo-care-grid"><div><span>01</span><b>cABCDE</b><small>Lebensbedrohliche Störungen erkennen und parallel behandeln.</small></div><div><span>02</span><b>Monitoring</b><small>Rhythmus, Blutdruck, SpO₂ und klinischen Verlauf fortlaufend erfassen.</small></div><div><span>03</span><b>12-Kanal-EKG</b><small>Innerhalb von zehn Minuten mit 50 mm/s ableiten und bei Bedarf ergänzen.</small></div><div><span>04</span><b>Transportweg</b><small>PCI-Zentrum und Herzkatheterlabor früh voranmelden.</small></div></div><h3>SAMPLERS und OPQRST gezielt</h3><div className="samplers-grid">{[["S · Symptome", "Beginn, Dauer, Dynamik und Begleitzeichen"], ["A · Allergien", "Arzneimittelallergien und Unverträglichkeiten"], ["M · Medikamente", "Antikoagulation, Nitrate und PDE-5-Hemmer"], ["P · Vorgeschichte", "KHK, Stent, Infarkt und Herzinsuffizienz"], ["L · Letzte Aufnahme", "Nahrung, Flüssigkeit und Zeitpunkt"], ["E · Ereignis", "Belastung, Auslöser und Verlauf"], ["R · Risiken", "Rauchen, Hypertonie, Diabetes und Dyslipidämie"], ["S · Schwangerschaft", "Falls relevant"]].map(([name, text]) => <p key={name}><b>{name}</b>{text}</p>)}</div><p><b>OPQRST:</b> Beginn, Provokation, Qualität, Ausstrahlung, Stärke und Zeitverlauf. Parallel Hinweise auf eine Aortendissektion erheben und die Zielklinik früh festlegen.</p></>)}

    {section("08", "Gefährliche Alternativen", "Differenzialdiagnosen und Entscheidungen", <><div className="differential-grid">{["Aortendissektion", "Lungenarterienembolie", "Pneumothorax", "Perikarditis / Myokarditis", "Angina pectoris", "Hypertensiver Notfall", "Rhythmusstörung", "Akute Klappenerkrankung", "Pankreatitis / Ulkus / Gallenkolik"].map((item) => <span key={item}>{item}</span>)}</div><aside className="diagnostic-boundary"><span>!</span><div><b>Aortendissektion vor antithrombotischer Therapie bedenken</b><p>Plötzlicher reißender Schmerz, Pulsdefizit, relevante Blutdruckdifferenz oder neurologischer Ausfall verändern die Therapieentscheidung.</p></div></aside></>)}

    {section("09", "Reperfusion vorbereiten", "Weitere Maßnahmen und Medikamente", <><div className="pulmo-medicine-grid"><div><small>Thrombozytenhemmung</small><b>Acetylsalicylsäure</b><p>Hemmt COX-1 irreversibel und vermindert Thromboxan A₂ sowie die Thrombozytenaggregation. VFA 14: <strong>250 mg i.v.</strong> oder orale Äquivalenzdosis.</p></div><div><small>Gerinnungshemmung</small><b>Heparin</b><p>Verstärkt Antithrombin und hemmt Gerinnungsfaktoren. VFA 14: <strong>100 I.E./kgKG i.v., maximal 5.000 I.E.</strong></p></div><div><small>Vasodilatation</small><b>Glyceroltrinitrat</b><p>Senkt durch NO-vermittelte Gefäßrelaxation vor allem Vorlast und Wandspannung. VFA 13: <strong>0,4 mg sublingual</strong>, Kontrolle nach fünf Minuten.</p></div></div><div className="myokardinfarkt-decision-grid"><aside className="myokardinfarkt-contra"><span>×</span><div><small>Vor Medikamentengabe prüfen</small><h3>Kontraindikationen getrennt beachten</h3><p><b>Nitro:</b> PDE-5-Hemmer, RRsys unter 120 mmHg und Hinterwandverdacht.</p><p><b>ASS / Heparin:</b> aktive Blutung, frischer Schlaganfall und akute Aortendissektion.</p></div></aside><div className="myokardinfarkt-pci"><span>→</span><div><small>Reperfusionsstrategie</small><h3>Direkt in die geeignete PCI-Struktur</h3><p>Bei STEMI oder neuem LSB EKG digital übermitteln, Herzkatheterlabor voranmelden und vermeidbare Verzögerungen verhindern.</p></div></div></div></>)}

    {section("10", "Originale Handlungsgrundlage", "Verfahrensanweisungen Thüringen 2026/2027", <><p>Die folgenden Originalseiten verbinden Basisalgorithmus, Nitro sowie ASS und Heparin. Maßgeblich bleiben Indikation, Kontraindikationen, Dosierung und Re-Evaluation der abgebildeten VFA.</p><div className="vfa-stack"><Vfa src="/lessons/acs/vfa-acs-basis-12.png" alt="VFA 12 Basisalgorithmus akutes Koronarsyndrom" caption="VFA 12 · Akutes Koronarsyndrom" wide /><Vfa src="/lessons/acs/vfa-glyceroltrinitrat-13.png" alt="VFA 13 Glyceroltrinitrat" caption="VFA 13 · Glyceroltrinitrat" wide /><Vfa src="/lessons/acs/vfa-ass-heparin-14.png" alt="VFA 14 Acetylsalicylsäure und Heparin" caption="VFA 14 · Acetylsalicylsäure und Heparin" wide /></div></>)}

    {children}
    <p className="lesson-source">Hauptgrundlage: bereitgestellte Unterlagen zum Myokardinfarkt und das hinterlegte Anatomieskript. Medikamentendosierungen, Kontraindikationen und Wiederholungsintervalle richten sich ausschließlich nach den Thüringer Verfahrensanweisungen 2026/2027.</p>
  </article>;
}
