import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function OpiatintoxikationLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, kicker: string, title: string, body: ReactNode) => <details open className="lesson-section rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>{kicker}</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;

  return <article className="lesson-article angina-pectoris-lesson reference-reading-lesson opiatintoxikation-lesson">
    <div className="lesson-intro"><p className="lead">Bei der Opiatintoxikation entscheidet nicht das Erreichen vollständiger Wachheit, sondern die rasche Sicherung einer ausreichenden Ventilation. Beatmung, Eigenschutz und strukturierte Differenzialdiagnostik bleiben auch nach Naloxon unverzichtbar.</p></div>

    {section("01", "Begriff und Einordnung", "Definition", <><p>Eine Opiatintoxikation ist eine akute Vergiftung durch eine Substanz mit Wirkung an Opioidrezeptoren. Führend sind Bewusstseinsminderung und Atemdepression; eine ausgeprägte Vergiftung kann innerhalb kurzer Zeit zu Hypoxie, Aspiration und Kreislaufstillstand führen.</p><div className="pulmo-compare"><div><small>Opiate</small><h3>Natürlich aus Opium</h3><p>Natürliche Alkaloide wie Morphin und Codein. Morphin gehört damit nicht zu den synthetischen Opioiden.</p></div><div><small>Opioide</small><h3>Der weitere Oberbegriff</h3><p>Alle natürlichen, halbsynthetischen und synthetischen Stoffe mit Opioidrezeptorwirkung, etwa Heroin, Oxycodon, Fentanyl oder Methadon.</p></div></div><aside className="knowledge-note"><b>Prüfungspräzision</b><p>Das Prüfungsthema heißt „Opiatintoxikation“. Pharmakologisch ist „Opioidintoxikation“ der umfassendere Begriff.</p></aside></>)}

    {section("02", "Zielstrukturen der Intoxikation", "Anatomie und Physiologie", <><Figure src="/lessons/opiatintoxikation/gehirn-hirnstamm.jpg" alt="Sagittaler Schnitt des Gehirns mit beschriftetem Pons und verlängerter Medulla oblongata" caption="Gehirn und Hirnstamm · Medulla oblongata und Pons steuern lebenswichtige Funktionen" wide /><p>Im Hirnstamm erzeugen und modulieren neuronale Netzwerke den Atemrhythmus. Chemorezeptorische Signale passen die Ventilation besonders an den CO₂-Anstieg an. Die Formatio reticularis trägt zur Wachheit bei; limbische Strukturen beeinflussen Belohnung und Affekt.</p><Figure src="/lessons/opiatintoxikation/neuron-beschriftet.jpg" alt="Beschriftetes Neuron mit Dendriten, Zellkörper, Axon und synaptischen Endknöpfchen" caption="Neuron und Synapse · Opioidrezeptoren vermindern die neuronale Erregbarkeit und Transmitterfreisetzung" wide /><div className="pulmo-anatomy-grid"><div><small>μ-Rezeptor</small><b>Klinisch führend</b><p>Analgesie, Sedierung und Euphorie; zugleich Atemdepression, Miosis und verminderte Darmmotilität.</p></div><div><small>κ-Rezeptor</small><b>Analgesie und Sedierung</b><p>Trägt zur spinalen Analgesie und Bewusstseinsdämpfung bei; kann dysphorische Effekte vermitteln.</p></div><div><small>δ-Rezeptor</small><b>Modulierende Funktion</b><p>Beteiligt an Analgesie und neuronaler Regulation; für das akute rettungsdienstliche Leitsyndrom weniger prägend als μ.</p></div></div></>)}

    {section("03", "Vom Rezeptor zur Hypoxie", "Pathophysiologie und Ursachen", <><div className="pulmo-path"><span>Opioidrezeptor aktiviert</span><i>→</i><span>Neuronale Aktivität sinkt</span><i>→</i><span>CO₂-Antwort nimmt ab</span><i>→</i><span>Bradypnoe / Apnoe</span><i>→</i><span>Hypoxie</span></div><p>Opioidrezeptoren sind G-Protein-gekoppelte inhibitorische Rezeptoren. Ihre Aktivierung vermindert präsynaptisch die Transmitterfreisetzung und hyperpolarisiert postsynaptische Zellen. Im Hirnstamm wird dadurch der Atemantrieb gegenüber einem steigenden CO₂ abgeschwächt: Atemfrequenz und Atemzugvolumen sinken, Hyperkapnie und Hypoxämie folgen.</p><div className="pulmo-risk-grid"><div><b>Unbeabsichtigte Überdosierung</b><p>Dosierungsfehler, Kumulation, eingeschränkte Elimination oder Kombination verschiedener Präparate.</p></div><div><b>Opiatpflaster</b><p>Mehrere Pflaster, unbemerkter Altbestand oder verstärkte Wirkstoffaufnahme durch Wärme und Fieber.</p></div><div><b>Drogenkonsum</b><p>Unbekannter Wirkstoffgehalt, hochpotente Beimengungen und schwankende Toleranz.</p></div><div><b>Mischintoxikation</b><p>Alkohol, Benzodiazepine oder weitere sedierende Substanzen verstärken die Atem- und Bewusstseinsdepression.</p></div></div></>)}

    {section("04", "Arbeitsdiagnose stützen", "Symptome und Befunde", <><aside className="red-flags"><span>!</span><div><small>Klassisches Toxidrom</small><h3>Atemdepression · Bewusstseinsstörung · Miosis</h3><p>Die Trias stützt den Verdacht stark. Sie ist weder vollständig beweisend noch muss sie bei jeder Intoxikation komplett vorliegen.</p></div></aside><div className="pulmo-symptoms"><span>Bradypnoe bis Apnoe</span><span>Flache Atmung</span><span>Somnolenz bis Koma</span><span>Stecknadelkopfgroße Pupillen</span><span>Zyanose</span><span>Bradykardie / Hypotonie</span><span>Reduzierte Schutzreflexe</span><span>Opiatpflaster / Einstichstellen</span></div><p>Schwere Hypoxie, Mischintoxikationen oder einzelne Wirkstoffe können das Pupillenbild verändern. Normale oder weite Pupillen schließen die Diagnose deshalb nicht sicher aus. Atemfrequenz, Atemtiefe, Thoraxexkursion, SpO₂ und – wenn verfügbar – Kapnografie werden gemeinsam bewertet.</p></>)}

    {section("05", "Zeitkritische Folgen", "Komplikationen und Gefahren", <div className="pulmo-risk-grid"><div><b>Atemwegsverlust</b><p>Zunge, Sekret oder Erbrochenes verlegen bei fehlenden Schutzreflexen den Atemweg.</p></div><div><b>Hypoxischer Schaden</b><p>Apnoe führt über Hypoxämie und Azidose zu Hirnschaden, Arrhythmie und Kreislaufstillstand.</p></div><div><b>Aspiration</b><p>Bewusstseinsstörung und Erbrechen erhöhen das Risiko einer Aspirationspneumonitis.</p></div><div><b>Re-Narkotisierung</b><p>Die Opioidwirkung kann länger anhalten als die Antagonisierung; erneute Atemdepression ist möglich.</p></div><div><b>Entzug nach Naloxon</b><p>Agitation, Schmerzen, Übelkeit, Erbrechen, Schwitzen, Tremor, Tachykardie und Blutdruckanstieg können abrupt auftreten.</p></div><div><b>Langes Liegen</b><p>Hypothermie, Druckschäden und Rhabdomyolyse sind bei verzögerter Auffindung möglich.</p></div></div>)}

    {section("06", "Vorbereitet zum Patienten", "Einsatzmaterialien", <div className="material-chips">{["PSA / stichsichere Entsorgung", "Absaugung", "O₂ und Beatmungsbeutel", "Atemwegshilfen", "Kapnografie / Monitoring", "BZ-Messung", "i.v.- / i.o.-Material", "Naloxon und MAD", "Wärmeerhalt", "Reanimationsbereitschaft"].map(item => <span key={item}>{item}</span>)}</div>)}

    {section("07", "Ventilation hat Vorrang", "Erstmaßnahmen und SAMPLERS", <><div className="pulmo-care-grid"><div><span>01</span><b>Eigenschutz</b><small>Nadeln, Pulver, Pflaster und unklare Substanzen nicht ungeschützt anfassen; Umgebung sichern.</small></div><div><span>02</span><b>cABCDE</b><small>Atemweg öffnen, Sekret entfernen und bei unzureichender Eigenatmung sofort assistiert beatmen.</small></div><div><span>03</span><b>Überwachen</b><small>AF, Atemtiefe, SpO₂, EtCO₂, ECG, RR, BZ, Temperatur und neurologischen Verlauf erfassen.</small></div><div><span>04</span><b>Exposition stoppen</b><small>Opiatpflaster mit Handschuhen entfernen, Haut kontrollieren und Zeitpunkt dokumentieren.</small></div></div><h3>SAMPLERS · fokussiert</h3><div className="samplers-grid">{[["S · Symptome", "Beginn, Atmung, Bewusstsein, Erbrechen"], ["A · Allergien", "Bekannte Arzneimittelreaktionen"], ["M · Medikamente", "Opioide, Pflaster, Benzodiazepine, Alkohol"], ["P · Vorgeschichte", "Abhängigkeit, Schmerztherapie, Leber / Niere"], ["L · Letzte Aufnahme", "Substanz, Menge, Zeitpunkt, Applikationsweg"], ["E · Ereignis", "Auffindeort, Fremdanamnese, Suizidabsicht"], ["R · Risiken", "Mischkonsum, lange Liegezeit, Aspiration"], ["S · Schwangerschaft", "Schwangerschaft möglich?"]].map(([label, text]) => <p key={label}><b>{label}</b>{text}</p>)}</div><aside className="diagnostic-boundary"><span>!</span><div><b>Naloxon ersetzt keine Beatmung</b><p>Bei Bradypnoe oder Apnoe werden Atemweg und Ventilation unverzüglich gesichert. Auf den Wirkungseintritt des Antidots darf nicht gewartet werden.</p></div></aside></>)}

    {section("08", "Bewusstsein ist kein Beweis", "Differenzialdiagnosen und Entscheidungen", <><div className="differential-grid">{["Hypoglykämie", "Apoplex / Hirnblutung", "Schädel-Hirn-Trauma", "Postiktaler Zustand", "Alkohol- / Benzodiazepinintoxikation", "Hyperkapnisches Atemversagen", "Sepsis", "Hypothermie"].map(item => <span key={item}>{item}</span>)}</div><p>Ein Ansprechen auf Naloxon stützt die opioidbedingte Komponente, schließt aber Begleitverletzungen, Hypoglykämie oder eine Mischintoxikation nicht aus. Bleibt die Wirkung aus, werden Beatmung und Oxygenierung überprüft und andere Ursachen der Bewusstseinsstörung konsequent gesucht.</p><aside className="knowledge-note"><b>Prüfungsfalle</b><p>Der gewünschte Endpunkt ist eine ausreichende Spontanatmung bei gesichertem Atemweg – nicht zwingend völlige Wachheit. Ein abrupt vollständig wacher, entzügiger Patient kann erbrechen, aspirieren, aggressiv werden oder den Einsatzort verlassen wollen.</p></aside></>)}

    {section("09", "Antidot mit begrenzter Wirkdauer", "Naloxon: Wirkung und Nebenwirkungen", <><div className="pulmo-path"><span>Naloxon</span><i>→</i><span>kompetitive Rezeptorblockade</span><i>→</i><span>Opioid wird verdrängt</span><i>→</i><span>Atemantrieb kann zurückkehren</span></div><p>Naloxon ist ein kompetitiver Opioidantagonist mit besonders hoher Affinität zum μ-Rezeptor; es antagonisiert auch κ- und δ-Rezeptoren. Ohne Opioide zeigt es kaum agonistische Eigenwirkung. Es kann Atemdepression, Sedierung und opioidbedingte Hypotonie aufheben, beseitigt aber weder Hypoxiefolgen noch eine zusätzliche Intoxikation.</p><div className="pulmo-compare"><div><small>Erwünschte Wirkung</small><h3>Ventilation wiederherstellen</h3><p>Atemfrequenz und Atemtiefe verbessern, Atemweg sichern und den Verlauf engmaschig kontrollieren.</p></div><div><small>Wesentliche Risiken</small><h3>Entzug und Wiederkehr</h3><p>Akuter Entzug mit Schmerz, Unruhe, Erbrechen, Tachykardie oder Hypertonie; später erneute Atemdepression durch länger wirksame Opioide.</p></div></div><p>Weitere mögliche Reaktionen sind Schwindel, Kopfschmerz, Tremor sowie Übelkeit und Erbrechen. Nach jeder erfolgreichen Antagonisierung bleiben kontinuierliches Monitoring und Transport erforderlich.</p></>)}

    {section("10", "Thüringen 2026/2027", "VFA 40 und Anlage B2A", <><Vfa src="/lessons/opiatintoxikation/vfa-40-naloxon.png" alt="Thüringer VFA 40 Opiatintoxikation und Naloxon" caption="VFA 40 · Opiatintoxikation – Naloxon · Version 2026/27" wide /><div className="pulmo-vfa-flow"><div><span>1</span><b>Indikation</b><small>Klinische Hinweise auf Opiatintoxikation und vitale Bedrohung.</small></div><div><span>2</span><b>Vitalfunktionen</b><small>O₂ 15 l/min; bei Bedarf Maskenbeatmung. Eigenschutz beachten.</small></div><div><span>3</span><b>Naloxon</b><small>0,4 mg i.v.; alternativ 0,4 mg intranasal über MAD.</small></div><div><span>4</span><b>Nach 3 Minuten</b><small>Erfolg beurteilen; bei fehlender Wirkung andere Ursachen suchen.</small></div></div><Vfa src="/lessons/opiatintoxikation/b2a-naloxon-row.png" alt="Exakt zugeschnittener Ausschnitt der Thüringer Anlage B2A mit ausschließlich Naloxon" caption="Anlage B2A · ausschließlich Naloxon 0,4 mg/1 ml und Zubereitung" wide /><aside className="knowledge-note"><b>i.v.-Zubereitung</b><p>1 ml Naloxon mit 0,4 mg plus 3 ml NaCl 0,9 % ergibt 4 ml Gesamtvolumen. In dieser Spritze enthält 1 ml genau 0,1 mg. Intranasal wird laut Anlage 1 ml unverdünnt über MAD gegeben.</p></aside></>)}

    {children}
    <p className="lesson-source">Grundlagen: bereitgestellte Unterlagen „38. Opiatintoxikation“, Anatomie-Skriptum und Thüringer Verfahrensanweisungen 2026/27. Ergänzende rettungsdienstliche Einordnung: RD-Factsheets Opiatintoxikation und Naloxon. Sämtliche Dosierungsangaben stammen ausschließlich aus der Thüringer VFA 40 und Anlage B2A.</p>
  </article>;
}
