import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct: boolean];
function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  const shift = (number * 3) % options.length;
  return { id: `opiatintoxikation-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty };
}

export const opiatintoxikationFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "opiatintoxikation-card-01", area: "Definition", question: "Grenzen Sie Opiat und Opioid voneinander ab.", answer: "Opiate sind natürliche Opiumalkaloide wie Morphin und Codein. Opioid ist der umfassende Begriff für natürliche, halbsynthetische und synthetische Substanzen mit Wirkung an Opioidrezeptoren. Das Prüfungsbild betrifft praktisch den gesamten Opioidbereich." },
  { id: "opiatintoxikation-card-02", area: "Anatomie", question: "Welche Strukturen erklären Atemdepression und Bewusstseinsminderung?", answer: "Medulla oblongata und Pons enthalten Netzwerke der Atemrhythmik und CO₂-Antwort. Die Formatio reticularis trägt zur Wachheit bei. Ihre opioidbedingte Hemmung führt zu vermindertem Atemantrieb und Vigilanz." },
  { id: "opiatintoxikation-card-03", area: "Rezeptoren", question: "Welche klinisch wichtigen Effekte vermittelt der My-(μ)-Opioidrezeptor?", answer: "Analgesie, Sedierung und Euphorie, aber auch Atemdepression, Miosis, reduzierte Darmmotilität sowie bei schwerer Wirkung Bradykardie und Hypotonie. Für die vitale Gefährdung ist vor allem die Atemdepression entscheidend." },
  { id: "opiatintoxikation-card-04", area: "Pathophysiologie", question: "Leiten Sie von der Rezeptoraktivierung bis zur Hypoxie her.", answer: "Inhibitorische Opioidrezeptoren vermindern Transmitterfreisetzung und neuronale Erregbarkeit. Die CO₂-Antwort im Hirnstamm sinkt, Atemfrequenz und Atemzugvolumen nehmen ab. Hyperkapnie, Hypoxämie, Azidose und schließlich Kreislaufstillstand können folgen." },
  { id: "opiatintoxikation-card-05", area: "Toxidrom", question: "Nennen Sie die klassische Trias und ihre diagnostische Grenze.", answer: "Atemdepression, Bewusstseinsstörung und Miosis. Sie stützt die Diagnose stark, beweist sie aber nicht. Hypoxie, Mischintoxikation oder einzelne Wirkstoffe können das Pupillenbild verändern; fehlende Miosis schließt die Intoxikation nicht aus." },
  { id: "opiatintoxikation-card-06", area: "Ursachen", question: "Welche Ursachen müssen in der Anamnese gezielt gesucht werden?", answer: "Dosierungsfehler oder Kumulation, mehrere beziehungsweise alte und neue Pflaster, Wärme/Fieber, Drogenkonsum mit unbekanntem Gehalt, reduzierte Toleranz sowie Mischkonsum mit Alkohol, Benzodiazepinen oder weiteren Sedativa." },
  { id: "opiatintoxikation-card-07", area: "Priorität", question: "Warum hat Beatmung Vorrang vor dem Abwarten auf Naloxon?", answer: "Naloxon benötigt Zeit bis zum Wirkungseintritt und wirkt nicht gegen mechanische Atemwegsverlegung, Aspiration oder andere Intoxikationen. Hypoxie wird unmittelbar durch Atemwegsmanagement, Sauerstoff und ausreichende Ventilation verhindert." },
  { id: "opiatintoxikation-card-08", area: "Eigenschutz", question: "Welche Gefahren sind am Einsatzort besonders zu beachten?", answer: "Ungesicherte Nadeln, unbekannte Pulver, kontaminierte Pflaster, aggressive Reaktion nach Antagonisierung und eine mögliche suizidale Lage. PSA, sichere Entsorgung, Handschuhe und kontrolliertes Umfeld sind erforderlich." },
  { id: "opiatintoxikation-card-09", area: "Naloxon", question: "Wo und wie wirkt Naloxon?", answer: "Naloxon konkurriert an Opioidrezeptoren, mit besonders hoher Affinität zum My-(μ)-Opioidrezeptor, und verdrängt Opioidagonisten. Es blockiert außerdem Kappa-(κ)- und Delta-(δ)-Opioidrezeptoren. Dadurch können Atemdepression, Sedierung und opioidbedingte Hypotonie zurückgehen. Hypoxiefolgen oder Ko-Intoxikationen beseitigt es nicht." },
  { id: "opiatintoxikation-card-10", area: "VFA", question: "Nennen Sie Indikation, Dosis, Wege und Kontrollzeit der Thüringer VFA 40.", answer: "Indikation sind klinische Hinweise auf Opiatintoxikation und vitale Bedrohung. Naloxon 0,4 mg i.v., alternativ 0,4 mg intranasal über MAD; Erfolgskontrolle nach 3 Minuten." },
  { id: "opiatintoxikation-card-11", area: "Zubereitung", question: "Erklären Sie die i.v.-Spritze und die resultierende Konzentration.", answer: "1 ml Naloxon enthält 0,4 mg und wird mit 3 ml NaCl 0,9 % auf 4 ml ergänzt. Die Konzentration beträgt 0,1 mg/ml. Intranasal wird 1 ml mit 0,4 mg unverdünnt verwendet." },
  { id: "opiatintoxikation-card-12", area: "Nebenwirkungen", question: "Welche Folgen kann eine abrupte Antagonisierung auslösen?", answer: "Akuter Entzug mit Schmerz, Unruhe oder Aggression, Übelkeit/Erbrechen, Schwitzen, Tremor, Tachykardie und Blutdruckanstieg. Dadurch steigen Aspirations-, Eigen- und Fremdgefährdungsrisiko." },
  { id: "opiatintoxikation-card-13", area: "Re-Narkotisierung", question: "Warum ist eine erneute Atemdepression nach anfänglicher Besserung möglich?", answer: "Naloxon kann kürzer wirken als das verursachende Opioid, besonders bei Retardpräparaten, Pflastern oder lang wirksamen Substanzen. Nachlassende Antagonisierung lässt die Opioidwirkung erneut hervortreten; deshalb sind Monitoring und Transport nötig." },
  { id: "opiatintoxikation-card-14", area: "Differenzialdiagnosen", question: "Welche wichtigen Ursachen einer Bewusstseinsstörung bleiben parallel zu prüfen?", answer: "Hypoglykämie, Schlaganfall oder Hirnblutung, SHT, postiktaler Zustand, Alkohol-/Benzodiazepin- oder Mischintoxikation, hyperkapnisches Atemversagen, Sepsis und Hypothermie." },
  { id: "opiatintoxikation-card-15", area: "Entscheidung", question: "Was ist der sinnvolle therapeutische Endpunkt der Antagonisierung?", answer: "Eine ausreichende Spontanatmung bei sicherem Atemweg und stabilisierbaren Vitalfunktionen. Vollständige Wachheit ist nicht zwingend nötig und kann einen heftigen Entzug mit Erbrechen, Schmerz und Aggression provozieren." },
  { id: "opiatintoxikation-card-16", area: "Übergabe", question: "Welche Informationen gehören in die Klinikübergabe?", answer: "Substanz/Präparat, Stärke, Menge, Zeitpunkt und Applikationsweg; Pflaster und Mischkonsum; initiale Atmung, Bewusstsein und Pupillen; Beatmung; Naloxonweg und Dosis; Reaktion, erneute Verschlechterung, Begleitverletzungen und Suizidverdacht." },
];

export const opiatintoxikationQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen verwenden die Begriffe Opiat und Opioid korrekt?", [["Morphin und Codein zählen zu den natürlichen Opiaten", true], ["Opioid umfasst auch halbsynthetische und synthetische Wirkstoffe", true], ["Fentanyl ist ein synthetisches Opioid", true], ["Morphin ist ausschließlich ein synthetisches Opioid", false], ["Nur Opiate können eine relevante Atemdepression verursachen", false]], "Opiat ist die engere Stoffgruppe; Opioid der pharmakologische Oberbegriff.", 1),
  q(2, "Welche Strukturen sind für das klinische Bild besonders relevant?", [["Medulla oblongata und Pons für die Atemregulation", true], ["Formatio reticularis für Wachheit und Vigilanz", true], ["Synapsen mit inhibitorischen Opioidrezeptoren", true], ["Kleinhirn als alleiniger Generator des Atemrhythmus", false], ["Rückenmark ohne Beteiligung an opioidvermittelter Analgesie", false]], "Hirnstamm, Wachheitsnetzwerke und synaptische Opioidrezeptoren erklären Atem- und Vigilanzstörung.", 2),
  q(3, "Welche Wirkungen sind überwiegend mit einer Aktivierung des My-(μ)-Opioidrezeptors vereinbar?", [["Atemdepression", true], ["Analgesie und Sedierung", true], ["Miosis und reduzierte Darmmotilität", true], ["Ausgeprägte Steigerung der CO₂-Atemantwort", false], ["Obligate Mydriasis bei jeder Dosis", false]], "Der My-(μ)-Opioidrezeptor vermittelt sowohl gewünschte Analgesie als auch die lebensbedrohliche Atemdepression.", 1),
  q(4, "Welche Schritte bilden die Pathophysiologie der Atemdepression korrekt ab?", [["Die neuronale Antwort auf steigendes CO₂ wird abgeschwächt", true], ["Atemfrequenz und Atemzugvolumen können sinken", true], ["Hyperkapnie und Hypoxämie können eine Azidose verursachen", true], ["Die Sauerstoffsättigung muss vor der Ventilationsstörung sofort abfallen", false], ["Eine normale SpO₂ unter Sauerstoff schließt Hypoventilation sicher aus", false]], "Hypoventilation kann unter Sauerstoff durch SpO₂ allein verschleiert werden; Atemtiefe und Kapnografie sind wichtig.", 3),
  q(5, "Welche Befunde bilden das klassische opioidbedingte Toxidrom?", [["Bradypnoe bis Apnoe", true], ["Bewusstseinsminderung bis Koma", true], ["Miosis", true], ["Obligate Hyperthermie und trockene Haut", false], ["Ausgeprägte motorische Unruhe als führender Initialbefund", false]], "Atemdepression, Bewusstseinsstörung und Miosis sind die klassische Trias.", 1),
  q(6, "Welche Aussagen zur Pupillenbeurteilung sind fachlich tragfähig?", [["Miosis stützt den Verdacht, beweist ihn aber nicht", true], ["Schwere Hypoxie kann das typische Pupillenbild verändern", true], ["Mischintoxikationen können atypische Pupillen verursachen", true], ["Normale Pupillen schließen eine Opioidintoxikation sicher aus", false], ["Miosis erlaubt den Verzicht auf eine BZ-Messung", false]], "Pupillen sind ein Baustein, aber kein alleiniger Beweis und kein Ersatz für Differenzialdiagnostik.", 2),
  q(7, "Welche Situationen erhöhen das Risiko einer unbeabsichtigten Überdosierung?", [["Mehrere gleichzeitig belassene Opioidpflaster", true], ["Wärmezufuhr oder Fieber bei transdermaler Anwendung", true], ["Mischkonsum mit Benzodiazepinen oder Alkohol", true], ["Sichere Entfernung alter Pflaster vor jeder Neuanlage", false], ["Unveränderte Dosis nach vollständigem Toleranzverlust ohne Relevanz", false]], "Pflasterkumulation, erhöhte Hautaufnahme, Ko-Sedativa und verlorene Toleranz sind wichtige Risiken.", 2),
  q(8, "Welche Maßnahmen haben bei Apnoe und vermuteter Opiatintoxikation unmittelbar Priorität?", [["Atemweg öffnen und bei Bedarf absaugen", true], ["Mit Sauerstoff wirksam maskenbeatmen", true], ["Ventilation anhand Thoraxexkursion und Kapnografie kontrollieren", true], ["Zuerst drei Minuten ausschließlich auf Naloxon warten", false], ["Eine vorhandene Miosis macht Atemwegsmanagement entbehrlich", false]], "Atemweg und Ventilation werden sofort gesichert; das Antidot ergänzt die Basismaßnahmen.", 2),
  q(9, "Welche Aussagen zum Eigenschutz treffen zu?", [["Ungesicherte Nadeln werden nicht blind ertastet", true], ["Pflaster und unbekannte Substanzen werden mit Handschuhen gehandhabt", true], ["Ein möglicher Entzug kann die Einsatzdynamik abrupt verändern", true], ["Unbekanntes Pulver wird zur Identifikation direkt gerochen", false], ["Nach Naloxon besteht grundsätzlich keine Eigengefährdung mehr", false]], "Stichverletzung, Kontamination und plötzliche Agitation bleiben relevante Risiken.", 2),
  q(10, "Welche Parameter beurteilen die Ventilation besser als die SpO₂ allein?", [["Atemfrequenz und Atemtiefe", true], ["Thoraxexkursion und klinische Atemarbeit", true], ["Endtidales CO₂ und Verlauf", true], ["Ein einzelner Blutdruckwert", false], ["Pupillengröße ohne Atembeobachtung", false]], "Sauerstoff kann die Entsättigung verzögern; die Ventilation muss direkt beurteilt werden.", 3),
  q(11, "Welche Aussagen beschreiben Naloxon korrekt?", [["Es konkurriert an Opioidrezeptoren mit Opioidagonisten", true], ["Die hohe Affinität zum My-(μ)-Opioidrezeptor ist klinisch besonders relevant", true], ["Es kann opioidbedingte Atemdepression und Sedierung aufheben", true], ["Es bindet Opioide dauerhaft chemisch im Blut", false], ["Es beseitigt jede Form einer gemischten Intoxikation", false]], "Naloxon ist ein kompetitiver Antagonist, kein universelles Entgiftungsmittel.", 2),
  q(12, "Wann ist Naloxon im Thüringer Algorithmus 40 angezeigt?", [["Bei klinischen Hinweisen auf Opiatintoxikation", true], ["Wenn zugleich eine vitale Bedrohung besteht", true], ["Nach beziehungsweise parallel zur Sicherung der Vitalfunktionen", true], ["Bei jedem bekannten Opioidgebrauch ohne klinische Beeinträchtigung", false], ["Als Ersatz für Maskenbeatmung bei bestehender Apnoe", false]], "Die VFA verbindet klinischen Verdacht und vitale Bedrohung; Vitalfunktionen werden zuerst gesichert.", 2),
  q(13, "Welche Naloxonangaben entsprechen der Thüringer VFA 40?", [["0,4 mg i.v.", true], ["Alternativ 0,4 mg intranasal über MAD", true], ["Beurteilung des Erfolgs nach 3 Minuten", true], ["Intranasal grundsätzlich 0,1 mg verdünnt", false], ["Erfolgskontrolle erst nach 30 Minuten", false]], "Dosis, alternativer MAD-Weg und Drei-Minuten-Kontrolle stammen aus VFA 40.", 2),
  q(14, "Welche Aussagen zur i.v.-Zubereitung nach Anlage B2A sind korrekt?", [["Die Ampulle enthält 0,4 mg in 1 ml", true], ["Zu 1 ml Wirkstoff werden 3 ml NaCl 0,9 % gegeben", true], ["Die fertige 4-ml-Spritze enthält 0,1 mg/ml", true], ["1 ml der fertigen Lösung enthält weiterhin 0,4 mg", false], ["Das Gesamtvolumen nach Verdünnung beträgt 10 ml", false]], "0,4 mg verteilt auf 4 ml ergeben 0,1 mg/ml.", 2),
  q(15, "Welche Aussagen gelten für die intranasale Anwendung nach Anlage B2A?", [["Verwendet wird ein MAD", true], ["1 ml enthält unverdünnt 0,4 mg Naloxon", true], ["Der intranasale Weg ist die Alternative zum i.v.-Weg der VFA", true], ["Vor der Gabe wird die Ampulle mit 3 ml NaCl verdünnt", false], ["Die intranasale Dosis beträgt nach VFA 0,04 mg", false]], "Für MAD wird die 1-ml-Ampulle unverdünnt mit 0,4 mg verwendet.", 2),
  q(16, "Welche Veränderungen zeigen einen sinnvollen Behandlungserfolg?", [["Atemfrequenz und Atemtiefe werden ausreichend", true], ["Der Atemweg bleibt sicher beherrschbar", true], ["Die Oxygenierung und Ventilation stabilisieren sich", true], ["Der Patient muss zwingend maximal wach und schmerzfrei sein", false], ["Eine einzelne verbale Reaktion ersetzt die Atemkontrolle", false]], "Ziel ist ausreichende Ventilation, nicht eine maximale Antagonisierung bis zur vollständigen Wachheit.", 3),
  q(17, "Welche Reaktionen können durch einen abrupt ausgelösten Entzug entstehen?", [["Agitation und Wiederkehr starker Schmerzen", true], ["Übelkeit, Erbrechen und Schwitzen", true], ["Tachykardie und Blutdruckanstieg", true], ["Zuverlässige, dauerhafte Sedierung", false], ["Sicherer Schutz vor Aspiration", false]], "Naloxon kann bei Abhängigkeit einen akuten Entzug mit vegetativen und verhaltensbezogenen Risiken auslösen.", 2),
  q(18, "Warum bleiben Monitoring und Transport nach erfolgreicher Antagonisierung erforderlich?", [["Das auslösende Opioid kann länger wirken als Naloxon", true], ["Eine erneute Atemdepression kann nach anfänglicher Besserung auftreten", true], ["Begleitverletzungen oder Mischintoxikationen können fortbestehen", true], ["Eine normale Pupille garantiert eine dauerhafte Entgiftung", false], ["Die einmalige Besserung schließt Aspiration aus", false]], "Re-Narkotisierung und fortbestehende Begleitprobleme erfordern Überwachung und Transport.", 3),
  q(19, "Welche Differenzialdiagnosen müssen bei bewusstlosem Patienten aktiv geprüft werden?", [["Hypoglykämie", true], ["Schlaganfall, Hirnblutung oder Schädel-Hirn-Trauma", true], ["Postiktaler Zustand oder weitere Intoxikation", true], ["Miosis als eigenständige sichere Diagnose", false], ["Ein Opioidpflaster als Ausschluss aller anderen Ursachen", false]], "Eine plausible Exposition beendet nicht die strukturierte Suche nach reversiblen und gefährlichen Ursachen.", 2),
  q(20, "Naloxon zeigt nach drei Minuten keine erkennbare Wirkung. Welche Schritte sind begründet?", [["Wirksamkeit der Beatmung und Atemwegslage erneut prüfen", true], ["BZ sowie neurologische und traumatische Ursachen weiter abklären", true], ["Mischintoxikation und nichtopioide Ursachen erwägen", true], ["Alle Maßnahmen beenden, weil eine Intoxikation ausgeschlossen ist", false], ["Die fehlende Reaktion beweist einen ischämischen Schlaganfall", false]], "Fehlendes Ansprechen verlangt erneute ABCDE-Beurteilung und breite Differenzialdiagnostik.", 3),
  q(21, "Ein Patient wird mit mehreren Fentanylpflastern, Bradypnoe und Somnolenz gefunden. Welche Handlungen sind sinnvoll?", [["Pflaster mit Handschuhen entfernen und Anzahl dokumentieren", true], ["Unzureichende Ventilation sofort unterstützen", true], ["Mit länger anhaltender Wirkstoffaufnahme und Re-Narkotisierung rechnen", true], ["Wärmedecke direkt über belassenen Pflastern stark erhitzen", false], ["Nach erster Besserung auf Transport und Monitoring verzichten", false]], "Transdermale Depots können weiter Wirkstoff abgeben; Entfernung, Beatmung und Überwachung sind zentral.", 3),
  q(22, "Welche Befunde sprechen eher für eine zusätzliche oder alternative Ursache?", [["Fokales neurologisches Defizit", true], ["Traumazeichen am Kopf", true], ["Fehlende Besserung trotz suffizienter Ventilation und Antagonisierung", true], ["Bradypnoe, Bewusstseinsminderung und Miosis in Kombination", false], ["Dokumentierte Opioideinnahme mit typischem Verlauf als alleiniger Gegenbeweis", false]], "Fokalneurologie, Trauma und fehlendes Ansprechen erweitern die Differenzialdiagnose.", 3),
  q(23, "Welche Angaben machen die präklinische Übergabe besonders aussagekräftig?", [["Substanz, Stärke, Menge, Zeitpunkt und Applikationsweg", true], ["Initiale Atem- und Bewusstseinslage sowie Beatmungsmaßnahmen", true], ["Naloxondosis, Zugangsweg, Reaktion und erneute Verschlechterung", true], ["Nur die Bezeichnung ‚Intoxikation‘ ohne Verlauf", false], ["Das Verschweigen eines möglichen Suizidversuchs", false]], "Exposition, Vitalverlauf, Behandlung und psychosozialer Kontext steuern die weitere Versorgung.", 2),
  q(24, "Welche vollständige Prüfungsantwort ist inhaltlich schlüssig?", [["Die über den My-(μ)-Opioidrezeptor vermittelte Hemmung der CO₂-Antwort erklärt die vitale Atemdepression", true], ["Beatmung behandelt die unmittelbare Hypoxiegefahr, Naloxon die Rezeptorwirkung", true], ["Kurze Antagonistenwirkung und lang wirksames Opioid erklären eine Re-Narkotisierung", true], ["Miosis allein erlaubt die sichere Diagnose und beendet cABCDE", false], ["Vollständige Wachheit ist wichtiger als ausreichende Ventilation", false]], "Eine starke Antwort verbindet Rezeptorwirkung, Prioritäten, Antidotgrenze und Verlaufsrisiko.", 3),
];
