export type OrganisationFlashcard = { id: string; area: string; question: string; answer: string };

export type OrganisationQuestion = {
  id: string;
  prompt: string;
  options: { text: string; correct?: boolean }[];
  source: string;
  difficulty: 1 | 2 | 3;
  mode: "multiple";
};

export const organisationFlashcards: OrganisationFlashcard[] = [
  { id: "orga-card-01", area: "Thüringer Rettungsdienst", question: "Wer trägt in Thüringen welche Kernaufgabe des Rettungsdienstes?", answer: "Landkreise und kreisfreie Städte tragen den bodengebundenen Rettungsdienst einschließlich Berg- und Wasserrettung. Die Kassenärztliche Vereinigung Thüringen stellt die notärztliche Versorgung einschließlich Telenotarzt sicher. Das Land ist Träger der Luftrettung." },
  { id: "orga-card-02", area: "Hilfsfrist", question: "Wie setzt sich die planungsrelevante Hilfsfrist in Thüringen zusammen?", answer: "Regelhaft aus einer Minute Alarmierungs- und Dispositionszeit, einer Minute Ausrückzeit und zwölf Minuten Fahrzeit im dicht besiedelten beziehungsweise fünfzehn Minuten im dünn besiedelten Gebiet. Daraus ergeben sich 14 beziehungsweise 17 Minuten. Der Landesrettungsdienstplan nutzt hierfür einen Erreichungsgrad von 95 Prozent; Sonderlagen und Luftrettung sind gesondert geregelt." },
  { id: "orga-card-03", area: "Lageerkundung", question: "Wofür stehen die vier S der ersten Lageübersicht?", answer: "Scene: Einsatzstelle und Ausdehnung. Safety: Gefahren und Eigenschutz. Situation: Art, Umfang und Dynamik der Lage. Support: benötigte Kräfte, Führungsmittel und Spezialressourcen." },
  { id: "orga-card-04", area: "Gefahren", question: "Wie wird eine Gefahr mit Ursache, Wirkung und bedrohtem Objekt beschrieben?", answer: "Die Gefahrenursache löst eine schädigende Wirkung aus, die ein bedrohtes Objekt erreicht. Taktisch wird an Ursache, Ausbreitungsweg/Wirkung oder Schutz des bedrohten Objekts angesetzt. Diese Dreiteilung verhindert unspezifische Meldungen wie nur ‚es ist gefährlich‘." },
  { id: "orga-card-05", area: "Gefahren", question: "Nennen Sie 4A–1C–4E.", answer: "Atemgifte, Angstreaktion, Ausbreitung und atomare Strahlung; chemische Stoffe; Erkrankung/Verletzung, Explosion, Elektrizität und Einsturz. Das Schema ist eine Merkhilfe zur systematischen Gefahrenerkennung, keine starre Reihenfolge." },
  { id: "orga-card-06", area: "CBRN", question: "Wofür steht GAMS und welche Konsequenz folgt für den Rettungsdienst?", answer: "Gefahr erkennen, Absperren, Menschenrettung unter Eigenschutz, Spezialkräfte anfordern. Der Rettungsdienst betritt einen nicht freigegebenen Gefahrenbereich nicht ohne geeignete Schutzausrüstung und Auftrag; Patientenübergabe und Dekontamination werden mit Feuerwehr und Spezialkräften abgestimmt." },
  { id: "orga-card-07", area: "Erstes Rettungsmittel", question: "Welche Führungsaufgaben übernimmt das erste geeignete Rettungsmittel beim MANV zunächst?", answer: "Sichere Annäherung, Lageüberblick, qualifizierte Lagemeldung, Nachforderung, vorläufige Führungs- und Raumordnung, Vorsichtung nach örtlicher Vorgabe, Kennzeichnung/Dokumentation, lebensrettende Sofortmaßnahmen im verfügbaren Rahmen und geordnete Übergabe an die reguläre Einsatzleitung." },
  { id: "orga-card-08", area: "Lagemeldung", question: "Welche Inhalte muss eine prüfungstaugliche erste MANV-Lagemeldung enthalten?", answer: "Einsatzort und sichere Anfahrt, Ereignis und Ausdehnung, erkannte Gefahren, grobe Zahl und Art Betroffener, bereits eingesetzte Kräfte, zusätzlich benötigte Mittel/Spezialkräfte sowie ein klarer Melder und Rückkanal. Früh melden, Unsicherheiten kennzeichnen und nach Erkundung aktualisieren." },
  { id: "orga-card-09", area: "MANV", question: "Grenzen Sie MANV und überörtlichen MANV fachlich ab.", answer: "Beim MANV besteht ein Missverhältnis zwischen Patientenaufkommen und zunächst verfügbaren Mitteln, das mit den vorgesehenen örtlichen Strukturen beherrscht werden soll. Reichen die örtlichen Kapazitäten nicht, werden überörtliche Einheiten und Führungsstrukturen nach Landes- beziehungsweise Alarm- und Einsatzplanung aktiviert. Die konkrete Stufe richtet sich nach dem örtlichen Plan, nicht allein nach einer Patientenzahl." },
  { id: "orga-card-10", area: "Raumordnung", question: "Unterscheiden Sie Patientenablage, Behandlungsplatz, Bereitstellungsraum und Rettungsmittelhalteplatz.", answer: "Patientenablage: erste geordnete Sammel- und Versorgungsstelle nahe der Schadensstelle. Behandlungsplatz: strukturierte Behandlung und Vorbereitung zum Transport. Bereitstellungsraum: geordneter Raum für angeforderte, noch nicht eingesetzte Kräfte/Mittel. Rettungsmittelhalteplatz: taktisch geführte Aufstellung verfügbarer Transportmittel mit Zu- und Abfahrt." },
  { id: "orga-card-11", area: "Raumordnung", question: "Welche Kriterien bestimmen die Lage eines Behandlungsplatzes?", answer: "Außerhalb des Gefahrenbereichs, möglichst wind- beziehungsweise ausbreitungsseitig sicher, gut erreichbar, ausreichend groß, beleuchtbar, mit getrennten Zu- und Abfahrten, tragfähigem Untergrund sowie sinnvoller Verbindung zu Patientenablage und Transportorganisation." },
  { id: "orga-card-12", area: "Sichtung", question: "Grenzen Sie Vorsichtung und ärztliche Sichtung ab.", answer: "Vorsichtung ist die schnelle erste Priorisierung nach festgelegtem Algorithmus, häufig durch entsprechend qualifiziertes nichtärztliches Personal. Sichtung ist die ärztliche Entscheidung über Behandlungs- und Transportpriorität. Beide sind Momentaufnahmen und müssen bei Zustandsänderung wiederholt werden." },
  { id: "orga-card-13", area: "Sichtung", question: "Nennen Sie die Sichtungskategorien I bis IV und EX.", answer: "I Rot: akute vitale Bedrohung, sofortige Behandlung. II Gelb: schwer verletzt/erkrankt, dringliche Behandlung. III Grün: leicht verletzt/erkrankt, nicht dringlich. IV Blau: ohne Überlebenschance unter den gegebenen Bedingungen, palliative Versorgung; ärztliche Zuordnung. EX Schwarz: verstorben; ärztliche Feststellung. Planungsanteile sind keine Quoten." },
  { id: "orga-card-14", area: "Vorsichtung", question: "Welche Logik prüft mSTaRT bei Erwachsenen typischerweise?", answer: "Gehfähigkeit, lebensbedrohliche Blutung, Atmung nach Atemwegsöffnung, Atemfrequenz, Kreislauf über Radialispuls sowie Befolgen einfacher Aufforderungen; besondere lokale Kriterien können hinzukommen. Der konkrete Algorithmus und die Kennzeichnung richten sich nach dem verbindlichen örtlichen Konzept." },
  { id: "orga-card-15", area: "Führung", question: "Wie unterscheiden sich OrgL und LNA?", answer: "Der Organisatorische Leiter Rettungsdienst koordiniert Personal, Material, Räume, Rettungsmittel und Transportlogistik. Der Leitende Notarzt verantwortet die medizinische Lagebeurteilung, Sichtungs- und Behandlungsgrundsätze sowie medizinische Prioritäten. Beide arbeiten abgestimmt innerhalb der übergeordneten Einsatzleitung." },
  { id: "orga-card-16", area: "Führung", question: "Was unterscheidet Führung und Leitung im Sinne der FwDV 100?", answer: "Führung umfasst das zielgerichtete Einwirken auf Kräfte zur Auftragserfüllung einschließlich Führungsorganisation, -vorgang und -mitteln. Leitung bezeichnet die gesamtverantwortliche Führungstätigkeit der zuständigen Führungskraft beziehungsweise Einsatzleitung." },
  { id: "orga-card-17", area: "Führungsprozess", question: "Wie läuft der Führungsvorgang ab?", answer: "Lagefeststellung durch Erkundung und Kontrolle, Planung mit Beurteilung und Entschluss, Befehlsgebung sowie erneute Kontrolle. Der Vorgang ist ein Regelkreis: Neue Lageinformationen können jederzeit eine neue Beurteilung und Anpassung auslösen." },
  { id: "orga-card-18", area: "Führungsstil", question: "Wann sind autoritärer und kooperativer Führungsstil sinnvoll?", answer: "Bei unmittelbarer Gefahr, Zeitdruck oder unerfahrenen Kräften ist klare, enge Führung erforderlich. Bei stabilerer Lage und kompetentem Team kann kooperatives Führen Wissen und Eigenständigkeit nutzen. Lage, Auftrag und Team bestimmen den Stil; weder Starrheit noch Beliebigkeit sind fachgerecht." },
  { id: "orga-card-19", area: "Zusammenarbeit", question: "Welche Grundregel gilt bei der Zusammenarbeit von Rettungsdienst, Feuerwehr und Polizei?", answer: "Jede Organisation arbeitet in ihrem gesetzlichen Aufgaben- und Führungsbereich. Gemeinsame Lage, klare Schnittstellen, abgestimmte Ziele, Funkwege und Übergaben verhindern Parallelstrukturen. Medizinische, technische und polizeiliche Entscheidungen müssen koordiniert, aber nicht vermischt werden." },
  { id: "orga-card-20", area: "Taktik", question: "Unterscheiden Sie Algorithmus, Richtlinie, Leitlinie und dienstliche Anweisung.", answer: "Ein Algorithmus bildet einen festgelegten Entscheidungsablauf ab. Leitlinien geben evidenzbasierte Handlungsempfehlungen mit begründbaren Abweichungen. Richtlinien beziehungsweise verbindliche Regelungen setzen einen normativen Rahmen. Dienstliche Anweisungen/SOP/VFA regeln organisationsbezogenes Handeln und sind im jeweiligen Geltungsbereich zu beachten." },
  { id: "orga-card-21", area: "Ü-MANV", question: "Wann wird aus der örtlichen MANV-Bewältigung ein Ü-MANV?", answer: "Wenn die planmäßig verfügbaren örtlichen Kräfte und Strukturen zur zeitgerechten Bewältigung nicht ausreichen oder absehbar nicht ausreichen werden, fordert die zuständige Führung überörtliche Hilfe nach Landesrettungsdienstplan und örtlichem Alarm- und Einsatzplan an. Nicht die Bezeichnung oder eine starre Patientenzahl, sondern das Ressourcenmissverhältnis und die Prognose sind entscheidend." },
  { id: "orga-card-22", area: "Ü-MANV", question: "Welche überörtlichen Einheiten beziehungsweise Funktionen sieht das Thüringer Konzept vor?", answer: "Prüfungsrelevant sind die Einheiten Sofort, Behandlung, Transport, Führungsunterstützung sowie Betreuung/PSNV. Sie ergänzen die örtliche Gefahrenabwehr mit unterschiedlichen Fähigkeiten und werden lageabhängig einzeln oder kombiniert angefordert." },
  { id: "orga-card-23", area: "Ü-MANV", question: "Welche Aufgabe hat die Einheit Sofort?", answer: "Sie bringt kurzfristig rettungsdienstliche Behandlungskapazität für zeitkritische Patienten in den Einsatz. Sie unterstützt insbesondere lebensrettende Sofortmaßnahmen und die erste Stabilisierung, bis weitere Behandlungs- und Transportstrukturen wirksam werden. Die genaue Fahrzeug- und Personalzusammensetzung richtet sich nach dem geltenden Plan." },
  { id: "orga-card-24", area: "Ü-MANV", question: "Wie unterscheiden sich die Einheiten Behandlung und Transport?", answer: "Die Einheit Behandlung erweitert die geordnete medizinische Versorgung und Behandlungsplatzkapazität. Die Einheit Transport erhöht die Fähigkeit, priorisierte Patienten koordiniert in geeignete Zielkliniken zu verbringen. Behandlung schafft nicht automatisch Transportkapazität; beides muss getrennt geplant und anschließend verzahnt werden." },
  { id: "orga-card-25", area: "Ü-MANV", question: "Warum ist Führungsunterstützung beim Ü-MANV ein eigenes Modul?", answer: "Mit Zahl der Kräfte, Abschnitte, Funkgruppen, Kliniken und Transportbewegungen steigt der Koordinations- und Dokumentationsbedarf. Führungsunterstützung entlastet die Einsatzleitung durch Lagekarte, Kräfteübersicht, Kommunikation, Dokumentation und Informationsmanagement; sie übernimmt nicht automatisch die Einsatzleitung." },
  { id: "orga-card-26", area: "Ü-MANV", question: "Welche Aufgaben erfüllen Betreuung und PSNV?", answer: "Betreuung versorgt unverletzte oder leicht betroffene Personen mit Schutz, Registrierung, Information und Grundbedürfnissen. Psychosoziale Notfallversorgung unterstützt Betroffene, Angehörige und bei Bedarf Einsatzkräfte. Beide Funktionen entlasten medizinische Strukturen, ersetzen aber keine erneute medizinische Beurteilung bei Zustandsänderung." },
  { id: "orga-card-27", area: "Ü-MANV", question: "Wie werden überörtliche Einheiten an der Einsatzstelle geführt?", answer: "Sie melden sich am festgelegten Melde- oder Bereitstellungsraum, erhalten einen klaren Auftrag und werden in die bestehende Abschnitts- und Führungsstruktur eingegliedert. Eigenständiges Zufahren oder Arbeiten ohne Auftrag gefährdet Raumordnung, Kommunikation und Kräfteübersicht." },
  { id: "orga-card-28", area: "Ü-MANV", question: "Welche Informationen gehören in eine qualifizierte überörtliche Nachforderung?", answer: "Lage und Dynamik, erkannte Gefahren, geschätzte Zahl und Kategorien Betroffener, bereits vorhandene Kapazitäten, konkrete Fähigkeitslücke, benötigte Einheit/Funktion, sicherer Anfahrtsweg, Meldepunkt, Ansprechpartner, Funkweg und erwartete Einsatzdauer. Nachforderungen werden bei Lageänderung aktualisiert oder reduziert." },
  { id: "orga-card-29", area: "Luftrettung", question: "Welche Vor- und Nachteile hat der RTH im Rettungsdienst?", answer: "Vorteile sind schnelle Notarztzuführung in abgelegene Gebiete, zeitsparender Transport über große Distanzen und direkter Zugang zu überregionalen Zentren unabhängig vom Straßenverkehr. Grenzen sind Wetter, Sicht, Verfügbarkeit, notwendige Landezone, Zeit für Anflug und Umlagerung, begrenzter Arbeitsraum sowie Lärm, Rotor- und Fremdkörpergefahr. Entscheidend ist die Gesamtzeit bis zur definitiven Versorgung, nicht allein die Flugzeit." },
  { id: "orga-card-30", area: "Luftrettung", question: "Welche Mindestanforderungen gelten prüfungsbezogen für eine provisorische RTH-Landefläche?", answer: "Als Lernwert gilt eine freie, möglichst ebene und tragfähige Fläche von mindestens 30 mal 30 Metern. Sie muss von Personen und Fahrzeugen gesichert, frei von Hindernissen und losen Gegenständen sowie aus der Luft erkennbar sein. Leitungen, Masten, Gefälle und Wind werden gemeldet. Landung und Annäherungsweg bestimmt ausschließlich die Besatzung." },
  { id: "orga-card-31", area: "Autobahn", question: "Welche besonderen Gefahren müssen bei einem Rettungseinsatz auf der Autobahn in die erste Lagebeurteilung?", answer: "Fließender Hochgeschwindigkeitsverkehr und Folgeunfälle, unklare Fahrtrichtung oder falsche Anfahrt, fehlende Rettungsgasse, Trümmer, scharfe Fahrzeugteile, auslaufende Betriebsstoffe oder Gefahrgut, instabile Fahrzeuge, schlechte Sicht und Witterung sowie Behinderung durch Schaulustige. Warnkleidung, sichere Fahrzeugaufstellung und abgestimmte Verkehrsabsicherung mit Polizei und Feuerwehr haben Priorität." },
];

export const organisationQuestions: OrganisationQuestion[] = [
  { id: "orga-q-01", prompt: "Welche Aussagen zur Thüringer Hilfsfrist und ihrer Planung sind zutreffend?", options: [
    { text: "Alarmierungs- und Dispositionszeit sowie Ausrückzeit werden mit jeweils einer Minute berücksichtigt.", correct: true },
    { text: "Die reguläre Fahrzeit wird planungsbezogen mit zwölf beziehungsweise fünfzehn Minuten angesetzt.", correct: true },
    { text: "Der Landesrettungsdienstplan verlangt, dass jeder einzelne Einsatz zwingend innerhalb der Frist erreicht wird." },
    { text: "Die Planung orientiert sich grundsätzlich an einem Erreichungsgrad von 95 Prozent.", correct: true },
    { text: "Für Luftrettungsmittel gilt automatisch dieselbe Hilfsfrist wie für bodengebundene Rettungsmittel." },
  ], source: "Die planungsrelevante Frist ergibt sich regelmäßig aus 1 + 1 + 12 beziehungsweise 15 Minuten. Der 95-Prozent-Wert ist ein Planungsmaßstab und keine Garantie für jeden Einzelfall; Luftrettung und Sonderrettung sind gesondert geregelt.", difficulty: 2, mode: "multiple" },
  { id: "orga-q-02", prompt: "Das erste Rettungsmittel trifft bei einem Busunfall ein. Welche Maßnahmen gehören zur unmittelbaren Lagearbeit?", options: [
    { text: "Sichere Aufstellung und Eigenschutz vor Patientenkontakt prüfen.", correct: true },
    { text: "Frühe Lagemeldung mit grober Betroffenenzahl und erkannten Gefahren absetzen.", correct: true },
    { text: "Alle Kräfte ohne Raumordnung direkt bis an den Bus heranfahren lassen." },
    { text: "Benötigte Führungs-, Rettungs- und Spezialmittel gezielt nachfordern.", correct: true },
    { text: "Vorläufige Strukturen schaffen und später geordnet an die Einsatzleitung übergeben.", correct: true },
  ], source: "Das erste geeignete Rettungsmittel verbindet Eigenschutz, Lagefeststellung, Meldung, Nachforderung und vorläufige Ordnung. Unkontrolliertes Zufahren blockiert Wege und erhöht Risiken.", difficulty: 2, mode: "multiple" },
  { id: "orga-q-03", prompt: "Welche Zuordnungen zur 4-S-Matrix sind fachlich richtig?", options: [
    { text: "Scene beschreibt Einsatzort, Ausdehnung und räumliche Besonderheiten.", correct: true },
    { text: "Safety erfasst Gefahren, Schutzmaßnahmen und sichere Zugänge.", correct: true },
    { text: "Situation beschreibt ausschließlich die endgültige ärztliche Diagnose aller Patienten." },
    { text: "Support umfasst benötigte Verstärkung, Spezialkräfte und Führungsmittel.", correct: true },
    { text: "Die Matrix ersetzt die erneute Erkundung nach Lageänderung." },
  ], source: "Die 4-S-Matrix unterstützt eine erste strukturierte Lageübersicht. Situation betrifft Art, Umfang und Dynamik; die Lage muss fortlaufend neu bewertet werden.", difficulty: 1, mode: "multiple" },
  { id: "orga-q-04", prompt: "Bei einem Gefahrstoffaustritt liegen zwei Personen in einem nicht freigegebenen Bereich. Welche Aussagen sind taktisch korrekt?", options: [
    { text: "Die Gefahr ist zu erkennen und der Bereich gegen unkontrollierten Zutritt abzusperren.", correct: true },
    { text: "Menschenrettung bedeutet, dass Rettungsdienstpersonal unabhängig von Schutzausrüstung sofort hineingehen muss." },
    { text: "Geeignete Spezialkräfte und die erforderliche Dekontaminationsstruktur sind frühzeitig anzufordern.", correct: true },
    { text: "Patientenversorgung und Übergabepunkt müssen außerhalb des Gefahrenbereichs abgestimmt werden.", correct: true },
    { text: "Ein fehlender Eigengeruch schließt eine Atemgiftgefahr zuverlässig aus." },
  ], source: "GAMS verlangt Menschenrettung unter Eigenschutz. Ein nicht freigegebener Bereich wird nur mit geeigneter Schutzausrüstung, Auftrag und abgestimmter Taktik betreten; Wahrnehmbarkeit schließt Gefahren nicht aus.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-05", prompt: "Welche Aussagen beschreiben MANV und überörtliche Unterstützung treffend?", options: [
    { text: "Entscheidend ist ein zeitweiliges Missverhältnis zwischen Bedarf und verfügbaren Ressourcen.", correct: true },
    { text: "Eine feste bundesweit identische Patientenzahl definiert jede MANV-Stufe." },
    { text: "Die Aktivierung richtet sich nach dem örtlichen Alarm- und Einsatzplan.", correct: true },
    { text: "In der Frühphase kann eine ressourcenorientierte Priorisierung erforderlich werden.", correct: true },
    { text: "Überörtliche Hilfe macht eine örtliche Führungs- und Raumordnung entbehrlich." },
  ], source: "MANV ist eine Ressourcen- und Organisationslage. Schwellen, Module und Bezeichnungen sind planabhängig; überörtliche Kräfte werden in eine klare Führungsstruktur eingebunden.", difficulty: 2, mode: "multiple" },
  { id: "orga-q-06", prompt: "Welche Zuordnungen der Raumordnung sind korrekt?", options: [
    { text: "Die Patientenablage bündelt Betroffene zunächst nahe, aber sicher außerhalb der unmittelbaren Gefahrenzone.", correct: true },
    { text: "Der Behandlungsplatz dient strukturierter Behandlung und Transportvorbereitung.", correct: true },
    { text: "Im Bereitstellungsraum warten bereits angeforderte Kräfte geordnet auf ihren Einsatzauftrag.", correct: true },
    { text: "Der Rettungsmittelhalteplatz soll Zu- und Abfahrten möglichst kreuzen lassen, damit Wege kurz bleiben." },
    { text: "Ein Hubschrauberlandeplatz wird ohne Abstimmung direkt neben der Patientenablage gewählt." },
  ], source: "Raumordnung trennt Gefahren-, Behandlungs-, Bereitstellungs- und Transportfunktionen. Verkehrswege und Luftrettungsbetrieb benötigen sichere, abgestimmte Flächen.", difficulty: 2, mode: "multiple" },
  { id: "orga-q-07", prompt: "Welche Aussagen zu Vorsichtung und Sichtung sind richtig?", options: [
    { text: "Vorsichtung ist eine schnelle erste Priorisierung nach einem vorgegebenen Algorithmus.", correct: true },
    { text: "Die ärztliche Sichtung legt Behandlungs- und Transportprioritäten fest.", correct: true },
    { text: "Eine einmal vergebene Kategorie bleibt unabhängig vom klinischen Verlauf bestehen." },
    { text: "Nach Behandlung oder Zustandsänderung ist eine erneute Bewertung erforderlich.", correct: true },
    { text: "Dokumentation und eindeutige Kennzeichnung gehören zum Prozess.", correct: true },
  ], source: "Priorisierung ist dynamisch. Vorsichtung und ärztliche Sichtung haben unterschiedliche Rollen; Re-Sichtung und nachvollziehbare Kennzeichnung sind sicherheitsrelevant.", difficulty: 2, mode: "multiple" },
  { id: "orga-q-08", prompt: "Welche Aussagen zu den Sichtungskategorien sind fachlich korrekt?", options: [
    { text: "Kategorie I/Rot bedeutet akute vitale Bedrohung mit sofortigem Behandlungsbedarf.", correct: true },
    { text: "Kategorie II/Gelb kennzeichnet schwere, dringlich zu behandelnde Verletzungen oder Erkrankungen.", correct: true },
    { text: "Kategorie III/Grün schließt eine spätere Verschlechterung aus." },
    { text: "Kategorie IV/Blau und EX/Schwarz erfordern eine ärztliche Entscheidung beziehungsweise Feststellung.", correct: true },
    { text: "Planungsanteile von 20/30/50 Prozent sind anzustrebende Quoten für jede Einsatzstelle." },
  ], source: "Kategorien beschreiben aktuelle Prioritäten. Grün bleibt re-sichtungspflichtig; Planungsanteile dienen der Ressourcenplanung und dürfen die klinische Einordnung nicht steuern.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-09", prompt: "Welche Befunde führen in einem typischen Erwachsenen-mSTaRT zu höchster Priorität?", options: [
    { text: "Eine unkontrollierte spritzende Blutung.", correct: true },
    { text: "Nach Atemwegsöffnung wieder einsetzende Atmung.", correct: true },
    { text: "Atemfrequenz im vorgesehenen Normalbereich bei tastbarem Radialispuls und befolgten Aufforderungen." },
    { text: "Fehlender Radialispuls.", correct: true },
    { text: "Unfähigkeit, einfache Aufforderungen zu befolgen.", correct: true },
  ], source: "mSTaRT priorisiert vitale Störungen von Blutung, Atmung, Kreislauf und Bewusstsein. Der konkret eingesetzte Algorithmus kann lokal ergänzt oder abweichend geregelt sein.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-10", prompt: "Welche Aufgabenteilung zwischen OrgL und LNA ist zutreffend?", options: [
    { text: "Der OrgL koordiniert rettungsdienstliche Kräfte, Räume, Material und Transportmittel.", correct: true },
    { text: "Der LNA setzt medizinische Sichtungs-, Behandlungs- und Transportgrundsätze.", correct: true },
    { text: "Der OrgL entscheidet allein über jede ärztliche Therapie am Einzelpatienten." },
    { text: "OrgL und LNA stimmen ihre Entscheidungen innerhalb der Einsatzleitung miteinander ab.", correct: true },
    { text: "Mit Eintreffen des LNA entfallen Dokumentation und Nachforderung durch die Führungsorganisation." },
  ], source: "Organisation und medizinische Führung sind getrennte, eng verzahnte Verantwortungsbereiche. Beide bleiben Teil einer gemeinsamen Führungsstruktur.", difficulty: 2, mode: "multiple" },
  { id: "orga-q-11", prompt: "Welche Aussagen zum Führungsvorgang nach FwDV 100 sind richtig?", options: [
    { text: "Lagefeststellung umfasst Erkundung und fortlaufende Kontrolle.", correct: true },
    { text: "Planung verbindet Beurteilung der Lage mit einem Entschluss.", correct: true },
    { text: "Nach der Befehlsgebung ist eine erneute Lagekontrolle nicht mehr vorgesehen." },
    { text: "Neue Informationen können den Regelkreis erneut auslösen.", correct: true },
    { text: "Führungsmittel unterstützen Darstellung, Kommunikation und Dokumentation.", correct: true },
  ], source: "Der Führungsvorgang ist ein dynamischer Regelkreis aus Lagefeststellung, Planung, Befehl und Kontrolle; Führungsmittel machen die Lage bearbeitbar und nachvollziehbar.", difficulty: 2, mode: "multiple" },
  { id: "orga-q-12", prompt: "Ein Team arbeitet an einer instabilen Einsatzstelle unter hohem Zeitdruck. Welche Führungsentscheidungen sind plausibel?", options: [
    { text: "Aufträge eindeutig, kurz und an benannte Personen erteilen.", correct: true },
    { text: "Sicherheitskritische Rückmeldungen trotz klarer Führung ausdrücklich zulassen.", correct: true },
    { text: "Alle taktischen Entscheidungen zunächst im vollständigen Teamkonsens treffen." },
    { text: "Nach Stabilisierung der Lage stärker kooperativ führen und Fachwissen einbeziehen.", correct: true },
    { text: "Die Wirkung erteilter Aufträge kontrollieren.", correct: true },
  ], source: "Zeitkritik erfordert klare Führung, schließt Speak-up und Rückmeldung aber nicht aus. Der Führungsstil wird der Lage angepasst und bleibt kontrolliert.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-13", prompt: "Welche Aussagen zur organisationsübergreifenden Zusammenarbeit sind korrekt?", options: [
    { text: "Feuerwehr, Rettungsdienst und Polizei behalten ihre gesetzlichen Aufgabenbereiche.", correct: true },
    { text: "Gemeinsame Lagebilder und eindeutig benannte Schnittstellen reduzieren widersprüchliche Aufträge.", correct: true },
    { text: "Medizinische Prioritäten ersetzen automatisch polizeiliche Gefahrenabwehrentscheidungen." },
    { text: "Übergabepunkte, Funkwege und Transportachsen sollten gemeinsam abgestimmt werden.", correct: true },
    { text: "Technische Rettung und medizinische Versorgung müssen zeitlich und räumlich koordiniert werden.", correct: true },
  ], source: "Zusammenarbeit bedeutet Koordination bei getrennter Fachverantwortung. Gemeinsame Ziele, Schnittstellen und Kommunikationswege sind zentral.", difficulty: 2, mode: "multiple" },
  { id: "orga-q-14", prompt: "Welche Aussagen zu Regelwerken und Entscheidungshilfen treffen zu?", options: [
    { text: "Ein Algorithmus bildet einen vorgegebenen Entscheidungsweg ab.", correct: true },
    { text: "Eine Leitlinie ist stets identisch mit einer zwingenden dienstlichen Anweisung." },
    { text: "SOP und VFA gelten im festgelegten organisatorischen Geltungsbereich.", correct: true },
    { text: "Begründete Abweichungen von Empfehlungen können bei atypischer Lage erforderlich sein und sind zu dokumentieren.", correct: true },
    { text: "Örtliche Alarm- und Einsatzpläne konkretisieren übergeordnete Vorgaben für die Praxis.", correct: true },
  ], source: "Normativer Rang, Bindungswirkung und Geltungsbereich unterscheiden sich. Prüfungssicher ist die begründete Zuordnung statt der pauschalen Behauptung, alles sei gleich verbindlich.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-15", prompt: "Welche Kriterien sprechen für einen geeigneten Behandlungsplatz?", options: [
    { text: "Lage außerhalb vorhersehbarer Gefahren- und Ausbreitungsbereiche.", correct: true },
    { text: "Ausreichende Fläche, tragfähiger Untergrund und Beleuchtbarkeit.", correct: true },
    { text: "Möglichst nur eine gemeinsame enge Zu- und Abfahrt für alle Fahrzeuge." },
    { text: "Gute Verbindung zu Patientenablage und Transportorganisation.", correct: true },
    { text: "Erreichbarkeit, ohne die technische Rettung oder Feuerwehrzufahrt zu blockieren.", correct: true },
  ], source: "Ein Behandlungsplatz muss sicher, erreichbar, groß genug und in die Gesamtlogistik eingebunden sein. Verkehrsströme werden möglichst getrennt und konfliktarm geführt.", difficulty: 2, mode: "multiple" },
  { id: "orga-q-16", prompt: "Nach einer Explosion gehen zahlreiche gehfähige Betroffene selbstständig auf Rettungsmittel zu. Welche Maßnahmen sind sinnvoll?", options: [
    { text: "Gehfähige Betroffene an einen klar benannten, sicheren Sammelpunkt lenken.", correct: true },
    { text: "Auch zunächst grün Eingestufte registrieren und erneut beurteilen.", correct: true },
    { text: "Alle gehfähigen Personen ohne Erfassung sofort entlassen." },
    { text: "Kontamination und mögliche Inhalationsverletzung trotz Gehfähigkeit mitdenken.", correct: true },
    { text: "Die Bewegungsrichtung so steuern, dass Rettungs- und Transportwege frei bleiben.", correct: true },
  ], source: "Gehfähigkeit ist nur ein frühes Priorisierungskriterium. Sammlung, Registrierung, Re-Sichtung, Gefahrenerkennung und geordnete Wege bleiben notwendig.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-17", prompt: "Welche Befunde sprechen dafür, frühzeitig überörtliche MANV-Kräfte anzufordern?", options: [
    { text: "Die Zahl zeitkritischer Patienten übersteigt absehbar die örtliche Behandlungs- und Transportkapazität.", correct: true },
    { text: "Die technische Rettung wird voraussichtlich lange dauern und bindet zahlreiche örtliche Kräfte.", correct: true },
    { text: "Eine exakte Patientenzahl liegt noch nicht vor; deshalb ist jede Nachforderung unzulässig." },
    { text: "Örtliche Klinikkapazitäten und Transportmittel werden voraussichtlich zum Engpass.", correct: true },
    { text: "Die Lage ist dynamisch und eine spätere Nachforderung würde den Wirkeintritt wesentlich verzögern.", correct: true },
  ], source: "Überörtliche Hilfe wird prognostisch angefordert. Eine begründete Schätzung und die erkannte Fähigkeitslücke reichen für eine frühe Nachforderung; exakte Zahlen werden später nachgemeldet.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-18", prompt: "Welche Zuordnungen der Thüringer Ü-MANV-Funktionen sind korrekt?", options: [
    { text: "Sofort: rasche zusätzliche Kapazität für zeitkritische Erstversorgung und Stabilisierung.", correct: true },
    { text: "Behandlung: Erweiterung der geordneten medizinischen Behandlungskapazität.", correct: true },
    { text: "Transport: ausschließlich Aufbau einer Patientenablage ohne Abtransport." },
    { text: "Führungsunterstützung: Lageführung, Kommunikation und Dokumentation unterstützen.", correct: true },
    { text: "Betreuung/PSNV: unverletzte Betroffene, Angehörige und psychosoziale Bedarfe strukturiert versorgen.", correct: true },
  ], source: "Die Einheiten ergänzen unterschiedliche Fähigkeitslücken. Transport stellt Abtransportkapazität bereit; Führungsunterstützung unterstützt, übernimmt aber nicht automatisch die Gesamteinsatzleitung.", difficulty: 2, mode: "multiple" },
  { id: "orga-q-19", prompt: "Eine überörtliche Behandlungseinheit trifft ein. Welche Schritte sind vor ihrem Einsatz erforderlich?", options: [
    { text: "Meldung am festgelegten Meldepunkt oder Bereitstellungsraum.", correct: true },
    { text: "Einordnung in die bestehende Führungs- und Abschnittsstruktur.", correct: true },
    { text: "Eigenständige Standortwahl direkt an der Schadensstelle, um Zeit zu sparen." },
    { text: "Auftrag, Kommunikationsweg und Ansprechpartner eindeutig festlegen.", correct: true },
    { text: "Raumbedarf, Zufahrt und Schnittstelle zur Transportorganisation abstimmen.", correct: true },
  ], source: "Überörtliche Kräfte werden geordnet eingegliedert. Unkoordiniertes Zufahren erzeugt neue Gefahren, blockiert Verkehrswege und zerstört die Kräfteübersicht.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-20", prompt: "Welche Aussagen zur Einheit Führungsunterstützung treffen zu?", options: [
    { text: "Sie kann Lagekarte, Einsatztagebuch und Kräfteübersicht führen.", correct: true },
    { text: "Sie kann Kommunikations- und Informationswege organisatorisch unterstützen.", correct: true },
    { text: "Mit ihrem Eintreffen endet automatisch die Führungsverantwortung der örtlichen Einsatzleitung." },
    { text: "Sie gewinnt besonders bei mehreren Einsatzabschnitten und vielen Transportbewegungen an Bedeutung.", correct: true },
    { text: "Sie ersetzt OrgL und LNA bei allen medizinischen und organisatorischen Entscheidungen." },
  ], source: "Führungsunterstützung schafft Arbeitsfähigkeit und Nachvollziehbarkeit. Verantwortliche Führungsfunktionen bleiben bestehen, solange die Führungsorganisation nicht ausdrücklich geändert wird.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-21", prompt: "Welche Aussagen zur Einheit Betreuung/PSNV sind in einer Großlage richtig?", options: [
    { text: "Unverletzte Betroffene benötigen einen getrennten, registrierten und betreuten Aufenthaltsbereich.", correct: true },
    { text: "Psychosoziale Akuthilfe kann Angehörige und unmittelbar Betroffene unterstützen.", correct: true },
    { text: "Wer einmal als unverletzt gilt, braucht bei neuen Beschwerden keine medizinische Re-Evaluation." },
    { text: "Eine funktionierende Betreuung kann Behandlungs- und Führungsbereiche entlasten.", correct: true },
    { text: "Information, Schutz, Grundversorgung und Familienzusammenführung können Teil des Auftrags sein.", correct: true },
  ], source: "Betreuung und PSNV bearbeiten nichtmedizinische und psychosoziale Bedarfe, ohne die Möglichkeit einer klinischen Verschlechterung auszuschließen.", difficulty: 2, mode: "multiple" },
  { id: "orga-q-22", prompt: "Der Behandlungsplatz arbeitet, doch priorisierte Patienten warten lange auf Transport. Welche Folgerungen sind fachlich?", options: [
    { text: "Es liegt wahrscheinlich eine eigenständige Fähigkeitslücke in der Transportkomponente vor.", correct: true },
    { text: "Eine zusätzliche Behandlungseinheit löst den Transportengpass automatisch vollständig." },
    { text: "Transportpriorität, Zielklinik und verfügbare Rettungsmittel müssen gemeinsam koordiniert werden.", correct: true },
    { text: "Die Leitstelle beziehungsweise Transportorganisation benötigt ein aktuelles Lage- und Kapazitätsbild.", correct: true },
    { text: "Eine überörtliche Transporteinheit kann lagegerecht nachgefordert werden.", correct: true },
  ], source: "Behandlung und Transport sind getrennte, aber gekoppelte Prozesse. Mehr Behandlungskapazität ersetzt keine Fahrzeuge, Zielkliniken oder Transportkoordination.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-23", prompt: "Welche Inhalte machen eine Ü-MANV-Nachforderung qualifiziert?", options: [
    { text: "Konkrete Fähigkeitslücke statt nur des Rufes nach ‚mehr Kräften‘.", correct: true },
    { text: "Sicherer Anfahrtsweg, Meldepunkt und Ansprechpartner.", correct: true },
    { text: "Lagedynamik, Gefahren sowie geschätzte Betroffenen- und Prioritätenverteilung.", correct: true },
    { text: "Ausschließlich die endgültige Zahl ärztlich gesichteter Patienten; vorher darf nicht alarmiert werden." },
    { text: "Bereits eingesetzte Mittel und erwartete Einsatzdauer.", correct: true },
  ], source: "Eine gute Nachforderung beschreibt Bedarf, Kontext und Eingliederung. Frühe Schätzungen sind zulässig, müssen aber kenntlich gemacht und fortgeschrieben werden.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-24", prompt: "Welche Aussagen zur Rücknahme oder Anpassung überörtlicher Kräfte sind korrekt?", options: [
    { text: "Ändert sich die Lage, dürfen Umfang und Art der Nachforderung angepasst werden.", correct: true },
    { text: "Nicht mehr benötigte Kräfte werden geordnet über die Führungsstruktur freigegeben.", correct: true },
    { text: "Einmal alarmierte Einheiten müssen unabhängig vom Bedarf vollständig bis zur Einsatzstelle fahren." },
    { text: "Eine Reduzierung erfordert ein fortgeschriebenes Lagebild und Abstimmung mit der Leitstelle.", correct: true },
    { text: "Reservebildung und mögliche Lagedynamik sind vor einer Reduzierung zu berücksichtigen.", correct: true },
  ], source: "Ressourcen werden der Lage angepasst. Unkoordinierte Abbestellung ist ebenso problematisch wie unnötige Bindung; die Entscheidung läuft über die festgelegten Führungs- und Kommunikationswege.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-25", prompt: "Ein Nachbarlandkreis entsendet eine Ü-MANV-Einheit. Welche Aussagen zur Führung gelten?", options: [
    { text: "Die Einheit behält ihre interne Gliederung, wird aber in die Einsatzstruktur vor Ort eingebunden.", correct: true },
    { text: "Ihr Einheitsführer benötigt einen eindeutigen Auftrag und eine definierte übergeordnete Führung.", correct: true },
    { text: "Herkunft aus einem anderen Landkreis begründet eine unabhängige parallele Einsatzleitung." },
    { text: "Abweichende Funk- oder Dokumentationsverfahren müssen an der Schnittstelle geklärt werden.", correct: true },
    { text: "Der Meldepunkt verhindert unkontrolliertes Einfahren und unterstützt die Kräfteübersicht.", correct: true },
  ], source: "Überörtliche Einheiten werden auftragsbezogen eingegliedert. Interne Führung bleibt möglich, die taktische Einbindung erfolgt jedoch über die Einsatzleitung vor Ort.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-26", prompt: "Welche Aussagen sind typische Prüfungsfallen beim Ü-MANV?", options: [
    { text: "Ü-MANV darf nicht allein über eine bundesweit starre Patientenzahl definiert werden.", correct: true },
    { text: "Überörtliche Hilfe kann schon bei absehbarem, nicht erst bei eingetretenem Ressourcenversagen angefordert werden.", correct: true },
    { text: "Jede angeforderte Einheit übernimmt automatisch die Gesamteinsatzleitung." },
    { text: "Die Module Behandlung und Transport erfüllen unterschiedliche Kernaufgaben.", correct: true },
    { text: "Lokale Alarm- und Einsatzpläne konkretisieren Auslösung und Zusammensetzung.", correct: true },
  ], source: "Prüfungssicher ist die funktionsbezogene Begründung: Bedarf erkennen, passende Fähigkeit anfordern und geordnet eingliedern. Starre Zahlen oder automatische Führungswechsel sind falsch.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-27", prompt: "Bei einem Zugunglück werden überörtlich Sofort-, Behandlungs- und Transporteinheiten alarmiert. Welche Prioritäten sind sinnvoll?", options: [
    { text: "Die Sofort-Komponente gezielt dort einsetzen, wo zeitkritische Versorgungskapazität fehlt.", correct: true },
    { text: "Behandlungsplatz und Transportorganisation räumlich und kommunikativ miteinander verbinden.", correct: true },
    { text: "Alle eintreffenden Fahrzeuge unmittelbar bis an die Patientenablage fahren lassen." },
    { text: "Transportkapazität nach Sichtungs- und Transportpriorität einsetzen.", correct: true },
    { text: "Führungsunterstützung früh nutzen, bevor Kräfte- und Patientenbewegungen unübersichtlich werden.", correct: true },
  ], source: "Mehr Ressourcen verbessern die Lage nur bei klarer Raum-, Führungs- und Transportordnung. Ein unkontrollierter Kräftezufluss verschärft das Organisationsproblem.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-28", prompt: "Welche Angaben müssen bei einer Führungsübergabe im laufenden Ü-MANV zwingend nachvollziehbar sein?", options: [
    { text: "Aktuelles Lagebild, Gefahren und erwartete Dynamik.", correct: true },
    { text: "Eingesetzte und anfahrende Einheiten einschließlich Auftrag und Standort.", correct: true },
    { text: "Patientenzahlen, Prioritäten, Behandlungs- und Transportstatus.", correct: true },
    { text: "Nur mündliche Schätzungen; schriftliche oder elektronische Dokumentation ist entbehrlich." },
    { text: "Offene Entscheidungen, Engpässe, Kommunikationswege und Ansprechpartner.", correct: true },
  ], source: "Eine Führungsübergabe muss Lage, Kräfte, Patienten, Räume, Aufträge und offene Probleme abbilden. Dokumentation sichert Kontinuität und Nachvollziehbarkeit.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-29", prompt: "Ein zeitkritischer Patient befindet sich 25 Straßenkilometer von einem geeigneten Zentrum entfernt. Welche Aspekte gehören in die Entscheidung für oder gegen einen RTH?", options: [
    { text: "Die gesamte Zeit von Alarmierung bis Übergabe im Zielzentrum.", correct: true },
    { text: "Wetter, Sicht, Verfügbarkeit und sichere Landemöglichkeit.", correct: true },
    { text: "Die medizinische Eignung des Patienten und die erforderliche Zielklinik.", correct: true },
    { text: "Allein die höhere Reisegeschwindigkeit des Hubschraubers; Übergabe- und Umlagerungszeit sind unerheblich." },
    { text: "Ob ein bodengebundener Transport parallel vorbereitet werden muss.", correct: true },
  ], source: "Die RTH-Entscheidung ist eine Systemzeit- und Nutzenentscheidung. Fluggeschwindigkeit allein reicht nicht; Verfügbarkeit, Landung, Übergaben, Zielklinik und Patientenzustand müssen gemeinsam beurteilt werden.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-30", prompt: "Welche Aussagen zur Vorbereitung einer provisorischen RTH-Landezone sind richtig?", options: [
    { text: "Als prüfungsbezogener Lernwert wird eine freie Fläche von mindestens 30 × 30 Metern angesetzt.", correct: true },
    { text: "Lose Gegenstände und Rettungsdecken müssen vor dem Anflug gesichert werden.", correct: true },
    { text: "Stromleitungen, Masten, Gefälle und weitere Hindernisse werden der Besatzung früh gemeldet.", correct: true },
    { text: "Einsatzkräfte dürfen sich dem Hubschrauber jederzeit selbstständig von hinten nähern." },
    { text: "Die Besatzung entscheidet abschließend über Landung und sicheren Annäherungsweg.", correct: true },
  ], source: "Eine geeignete Landefläche ist eben, tragfähig, abgesperrt und frei von Hindernissen beziehungsweise Fremdkörpern. Eigenmächtige Annäherung, besonders von hinten, ist gefährlich; die Besatzung gibt den Weg frei.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-31", prompt: "Beim Verkehrsunfall auf einer Autobahn steht der RTW vor der Unfallstelle. Welche taktischen Aussagen sind zutreffend?", options: [
    { text: "Fließender Verkehr und mögliche Folgeunfälle bleiben auch nach dem Eintreffen eine dynamische Gefahr.", correct: true },
    { text: "Warnkleidung, sichere Aufstellung und abgestimmte Verkehrsabsicherung gehen einem ungeschützten Patientenzugang voraus.", correct: true },
    { text: "Fahrtrichtung, Kilometer, Fahrstreifen und sichere Anfahrt gehören in die Lagemeldung.", correct: true },
    { text: "Eine vorhandene Rettungsgasse schließt Gegenverkehr oder falsch fahrende Fahrzeuge sicher aus." },
    { text: "Trümmer, Kraftstoff und Gefahrgutkennzeichnung müssen in die Erkundung einbezogen werden.", correct: true },
  ], source: "Autobahnen verbinden Hochgeschwindigkeitsverkehr mit begrenzten Zugängen und hoher Folgeunfallgefahr. Eigensicherung, eindeutige Ortsangabe und gemeinsame Verkehrsabsicherung sind deshalb zentrale erste Maßnahmen.", difficulty: 3, mode: "multiple" },
  { id: "orga-q-32", prompt: "Ein RTH soll auf einer gesperrten Autobahn landen. Welche zusätzlichen organisatorischen Punkte sind sinnvoll?", options: [
    { text: "Landezone vollständig gegen Verkehr und unbefugte Personen sichern.", correct: true },
    { text: "Zu- und Abfahrtswege der Bodenrettungsmittel trotz Sperrung freihalten.", correct: true },
    { text: "Lose Fahrzeugteile, Folien und Rettungsmaterial im Rotorbereich sichern.", correct: true },
    { text: "Die Patientenablage grundsätzlich unmittelbar an den Rand des Rotorkreises verlegen." },
    { text: "Ansprechpartner und Übergabeweg zwischen RTH, Einsatzführung und Bodenrettung festlegen.", correct: true },
  ], source: "RTH-Betrieb ist Teil der Raumordnung. Absperrung, Fremdkörperschutz, getrennte Verkehrswege und eine abgestimmte Übergabeschnittstelle verhindern, dass die Luftrettung neue Gefahren oder logistische Blockaden erzeugt.", difficulty: 3, mode: "multiple" },
];
