import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct: boolean];
function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  const shift = (number * 2) % options.length;
  return { id: `pankreatitis-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty };
}

export const pankreatitisFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "pankreatitis-card-01", area: "Definition", question: "Definieren Sie die akute Pankreatitis und nennen Sie die präklinische Grenze.", answer: "Sie ist eine plötzlich einsetzende Entzündung des Pankreas mit möglichem Übergang von lokaler Organschädigung zu systemischer Entzündung und Organversagen. Präklinisch bleibt es eine Arbeitsdiagnose; Labor und Bildgebung sichern sie klinisch." },
  { id: "pankreatitis-card-02", area: "Anatomie", question: "Beschreiben Sie Lage und Abschnitte des Pankreas.", answer: "Das Pankreas liegt überwiegend retroperitoneal quer im Oberbauch hinter dem Magen. Der Kopf liegt im Duodenalbogen, der Körper zieht vor der Wirbelsäule nach links, der Schwanz reicht zur Milz." },
  { id: "pankreatitis-card-03", area: "Gangsystem", question: "Warum können Gallensteine eine Pankreatitis auslösen?", answer: "Ductus choledochus und Ductus pancreaticus münden häufig gemeinsam oder eng benachbart an der Papilla duodeni major. Ein Stein kann den Abfluss behindern und die intrapankreatische Enzymaktivierung fördern." },
  { id: "pankreatitis-card-04", area: "Exokrin", question: "Welche Schutzmechanismen verhindern physiologisch die Selbstverdauung?", answer: "Proteasen werden als inaktive Zymogene gespeichert und sezerniert, räumlich von Aktivatoren getrennt und erst im Duodenum aktiviert. Bikarbonat neutralisiert den sauren Chymus; intrapankreatische Inhibitoren begrenzen vorzeitige Aktivierung." },
  { id: "pankreatitis-card-05", area: "Endokrin", question: "Welche Inselzellen sind für Insulin und Glukagon zuständig?", answer: "β-Zellen bilden Insulin und senken den Blutzucker; α-Zellen bilden Glukagon und erhöhen ihn. Schwere Pankreasentzündung kann die Glukoseregulation beeinträchtigen." },
  { id: "pankreatitis-card-06", area: "Pathophysiologie", question: "Leiten Sie die Autodigestion und systemische Reaktion her.", answer: "Vorzeitige Trypsinaktivierung aktiviert weitere Enzyme. Proteasen und Lipasen schädigen Pankreas, Fettgewebe und Gefäße. Mediatoren verursachen Kapillarleck, Third Spacing und SIRS; daraus können Schock und Multiorganversagen entstehen." },
  { id: "pankreatitis-card-07", area: "Arbeitsdiagnose", question: "Welche Konstellation stützt die akute Pankreatitis?", answer: "Starker konstanter epigastrischer Schmerz mit gürtelförmiger Rückenstrahlung, Übelkeit, Erbrechen, geblähtes Abdomen und Entlastung in vorgebeugter Haltung bei passender Gallenstein- oder Alkoholanamnese." },
  { id: "pankreatitis-card-08", area: "Hautzeichen", question: "Was bedeuten Cullen- und Grey-Turner-Zeichen?", answer: "Cullen bezeichnet periumbilikale, Grey-Turner flankenseitige Einblutungen. Sie sind seltene, späte Hinweise auf einen schweren hämorrhagischen beziehungsweise nekrotisierenden Verlauf; ihr Fehlen schließt diesen nicht aus." },
  { id: "pankreatitis-card-09", area: "Komplikation", question: "Warum kann eine Pankreatitis zum Schock führen?", answer: "Kapillarleck und Third Spacing vermindern das zirkulierende Volumen; Erbrechen verstärkt den Verlust. Vasodilatation durch SIRS und bei hämorrhagischem Verlauf Blutung erzeugen hypovolämische und distributive Komponenten." },
  { id: "pankreatitis-card-10", area: "Differenzialdiagnosen", question: "Welche zeitkritischen Alternativen müssen bei Oberbauchschmerz ausgeschlossen werden?", answer: "ACS/Hinterwandinfarkt, Aortendissektion oder rupturiertes Aneurysma, Mesenterialischämie, perforiertes Ulkus, Ileus, biliärer Notfall, Lungenembolie und basale Pneumonie; je nach Situation EUG und DKA." },
  { id: "pankreatitis-card-11", area: "Metamizol", question: "Ordnen Sie Metamizol, Novalgin und Novaminsulfon ein und nennen Sie die VFA-Zubereitung.", answer: "Novalgin und Novaminsulfon sind Bezeichnungen für Metamizol, also kein zusätzlicher Wirkstoff. VFA 39: 1 g in 2 ml plus 98 ml NaCl 0,9 % auf 100 ml, Kurzinfusion über fünf Minuten." },
  { id: "pankreatitis-card-12", area: "Metamizol-Risiken", question: "Welche Risiken und Grenzen gelten für Metamizol?", answer: "Hypotonie, besonders bei Volumenmangel oder rascher Gabe, Überempfindlichkeit und selten Agranulozytose. VFA: nicht bei Schwangerschaft/Stillzeit und im Pfad nicht bei RRsys unter 100 mmHg; Allergie und frühere Agranulozytose beachten." },
  { id: "pankreatitis-card-13", area: "Buscopan", question: "Wann gehört Butylscopolamin zum Pankreatitis-Verdacht und wann nicht?", answer: "Nur wenn der Schmerz tatsächlich kolikartig ist und keine Kontraindikation besteht. Der typische Pankreatitisschmerz ist konstant. Mechanischer Ileus, Megakolon, Tachyarrhythmie, Engwinkelglaukom und Myasthenia gravis sprechen dagegen." },
  { id: "pankreatitis-card-14", area: "Buscopan-Zubereitung", question: "Wie wird Butylscopolamin nach B2A zubereitet?", answer: "20 mg in 1 ml werden mit 9 ml NaCl 0,9 % auf 10 ml Gesamtvolumen verdünnt. Die Konzentration beträgt 2 mg/ml; Gabe langsam intravenös." },
  { id: "pankreatitis-card-15", area: "Entscheidung", question: "Welche Zeichen machen den Transport besonders zeitkritisch?", answer: "Hypotonie, Vigilanzminderung, Hypoxämie, zunehmende Atemarbeit, Marmorierung, Anurie, Peritonismus, Blutungszeichen, persistierendes Erbrechen oder rasche Verschlechterung. Stabilisierung und Transport laufen parallel." },
];

export const pankreatitisQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen definieren die akute Pankreatitis korrekt?", [["Sie ist eine plötzlich einsetzende Entzündung des Pankreas", true], ["Sie kann lokal ödematös oder systemisch schwer verlaufen", true], ["Die präklinische Einordnung bleibt eine Arbeitsdiagnose", true], ["Sie ist definitionsgemäß immer infektiös", false], ["Ein normaler Hautbefund schließt sie sicher aus", false]], "Die Erkrankung reicht von lokaler Entzündung bis zum Multiorganversagen.", 1),
  q(2, "Welche anatomischen Zuordnungen sind richtig?", [["Der Pankreaskopf liegt im Duodenalbogen", true], ["Der Pankreaskörper liegt retroperitoneal hinter dem Magen", true], ["Der Pankreasschwanz zieht in Richtung Milz", true], ["Das Pankreas liegt vollständig intrathorakal", false], ["Der Pankreasgang mündet regelhaft in die Harnblase", false]], "Die retroperitoneale Oberbauchlage erklärt Schmerz und Rückenstrahlung.", 1),
  q(3, "Welche Aussagen zum exokrinen Pankreas stimmen?", [["Es produziert Verdauungsenzyme", true], ["Bikarbonat neutralisiert sauren Chymus im Duodenum", true], ["Proteasen werden überwiegend als inaktive Vorstufen sezerniert", true], ["Insulin ist das wichtigste exokrine Verdauungsenzym", false], ["Trypsin soll physiologisch bereits im Pankreas alle Zymogene aktivieren", false]], "Zymogenspeicherung und Aktivierung im Duodenum schützen vor Autodigestion.", 2),
  q(4, "Welche Aussagen zum endokrinen Pankreas treffen zu?", [["β-Zellen bilden Insulin", true], ["α-Zellen bilden Glukagon", true], ["Die Inselzellen geben Hormone in die Blutbahn ab", true], ["Glukagon senkt den Blutzucker durch vermehrte Glukoseaufnahme", false], ["Endokrine Zellen bilden ausschließlich Gallensäuren", false]], "Das Inselorgan reguliert vor allem den Glukosestoffwechsel.", 2),
  q(5, "Wie kann ein Gallenstein eine akute Pankreatitis auslösen?", [["Er kann den gemeinsamen beziehungsweise benachbarten Ausfluss an der Papille blockieren", true], ["Pankreassekret kann sich zurückstauen", true], ["Vorzeitige Enzymaktivierung und Zellschaden werden begünstigt", true], ["Er verschließt zwingend die Vena portae als ersten Schritt", false], ["Er steigert ausschließlich die Insulinfreisetzung ohne Entzündung", false]], "Die enge Gangbeziehung verbindet biliäre Obstruktion und Pankreasentzündung.", 2),
  q(6, "Welche Ursachen einer akuten Pankreatitis sind plausibel?", [["Gallenwegserkrankung", true], ["Alkoholassoziierte Pankreasschädigung", true], ["Hypertriglyzeridämie, Medikamente oder ERCP", true], ["Abdominaltrauma", true], ["Eine intakte Venenklappe als typische Hauptursache", false]], "Neben biliärer und alkoholassoziierter Ursache existieren metabolische, iatrogene und traumatische Auslöser.", 2),
  q(7, "Welche Schritte kennzeichnen die Pathophysiologie?", [["Vorzeitige Aktivierung von Trypsinogen", true], ["Aktivierung weiterer Verdauungsenzyme", true], ["Autodigestion und lokale Entzündungsreaktion", true], ["Kapillarleck und Third Spacing bei schwerem Verlauf", true], ["Obligate sofortige bakterielle Infektion zu Beginn", false]], "Enzymaktivierung und sterile Entzündung können systemische Organschäden auslösen.", 3),
  q(8, "Welche Befunde stützen die Arbeitsdiagnose Pankreatitis?", [["Konstanter starker Oberbauchschmerz mit Rückenstrahlung", true], ["Übelkeit und wiederholtes Erbrechen", true], ["Geblähtes Abdomen und schwache Darmgeräusche", true], ["Besserung in vorgebeugter Haltung", true], ["Obligate schmerzfreie Bauchdecke", false]], "Die typische Konstellation ist richtungsweisend, aber nicht beweisend.", 2),
  q(9, "Welche Aussagen zu Cullen- und Grey-Turner-Zeichen sind korrekt?", [["Cullen beschreibt eine periumbilikale Einblutung", true], ["Grey-Turner beschreibt flankenseitige Einblutungen", true], ["Beide können auf einen schweren hämorrhagischen Verlauf hinweisen", true], ["Ihr Fehlen schließt Nekrose oder Blutung sicher aus", false], ["Sie sind obligate Frühzeichen jeder milden Pankreatitis", false]], "Die Hautzeichen sind selten, spät und prognostisch ungünstig.", 3),
  q(10, "Welche Mechanismen können bei schwerer Pankreatitis zum Schock beitragen?", [["Kapillarleck und Flüssigkeitsverschiebung in den dritten Raum", true], ["Flüssigkeitsverlust durch Erbrechen", true], ["Vasodilatation bei systemischer Entzündungsreaktion", true], ["Blutung bei Gefäßdestruktion", true], ["Ausschließlich eine vagale Bradykardie ohne Volumenproblem", false]], "Hypovolämische, distributive und bei Blutung hämorrhagische Komponenten können zusammentreffen.", 3),
  q(11, "Welche Komplikationen können auftreten?", [["Nekrose, Pseudozyste oder Abszess", true], ["Paralytischer Ileus", true], ["Pleuraerguss oder ARDS", true], ["Akute Nierenschädigung und Gerinnungsstörung", true], ["Sichere dauerhafte Verbesserung der Glukoseregulation", false]], "Lokale und systemische Komplikationen bestimmen den Schweregrad.", 3),
  q(12, "Welche Aussage trennt SIRS und Sepsis bei Pankreatitis korrekt?", [["Eine frühe schwere Pankreatitis kann ein steriles SIRS auslösen", true], ["Sepsis erfordert eine Infektion mit Organdysfunktion", true], ["Eine infizierte Nekrose kann später zum Sepsisfokus werden", true], ["Fieber beweist sofort eine bakterielle Pankreasinfektion", false], ["SIRS und Sepsis sind definitionsgleich", false]], "Sterile Entzündung und infektiöse Organdysfunktion müssen unterschieden werden.", 3),
  q(13, "Welche präklinische Diagnostik ist sinnvoll?", [["cABCDE und wiederholte Kreislaufbeurteilung", true], ["12-Kanal-EKG bei Oberbauchschmerz", true], ["BZ, Temperatur und kontinuierliches Monitoring", true], ["Fokussierte OPQRST- und SAMPLERS-Anamnese", true], ["Abwarten auf einen Hautbefund vor Transportbeginn", false]], "Gefährdung und Differenzialdiagnosen stehen vor einer endgültigen Organdiagnose.", 2),
  q(14, "Welche Differenzialdiagnosen sind besonders zeitkritisch?", [["Akutes Koronarsyndrom", true], ["Aortendissektion oder rupturiertes Aneurysma", true], ["Mesenterialischämie", true], ["Perforiertes Ulkus", true], ["Chronischer Muskelkater als einzige lebensbedrohliche Alternative", false]], "Oberbauchschmerz kann kardiale, vaskuläre oder perforative Ursachen haben.", 2),
  q(15, "Welche Erstmaßnahmen sind angemessen?", [["Schmerzadaptierte Lagerung und Wärmeerhalt", true], ["Nüchternheit und Absaugbereitschaft bei Erbrechen", true], ["i.v.-Zugang und bedarfsgerechte, titrierte Flüssigkeit bei Hypoperfusion", true], ["Zügiger Transport in eine geeignete Klinik", true], ["Routinemäßige orale Flüssigkeitsgabe trotz Erbrechen und möglichem Ileus", false]], "Symptomkontrolle, Kreislaufstützung und Transport werden parallel organisiert.", 2),
  q(16, "Welche Aussagen zu Metamizol, Novalgin und Novaminsulfon stimmen?", [["Novalgin und Novaminsulfon sind Bezeichnungen für Metamizol", true], ["Es wirkt analgetisch und antipyretisch", true], ["Es besitzt einen spasmolytischen Wirkanteil", true], ["Es handelt sich um drei voneinander unabhängige Analgetika", false], ["Es verursacht obligat eine Opioid-typische Atemdepression", false]], "Die Namen bezeichnen denselben nichtopioiden Wirkstoff.", 2),
  q(17, "Welche Risiken von Metamizol müssen bedacht werden?", [["Hypotonie, besonders bei Volumenmangel oder rascher Gabe", true], ["Überempfindlichkeitsreaktion", true], ["Agranulozytose", true], ["Sichere Verhinderung jeder Infektion", false], ["Obligate Hypertonie nach langsamer Kurzinfusion", false]], "Kreislauf, Allergie und seltene schwere Blutbildveränderung sind zentral.", 2),
  q(18, "Welche Metamizol-Zubereitung entspricht VFA 39 und B2A?", [["1 g Metamizol entspricht 2 ml Wirkstoff", true], ["98 ml NaCl 0,9 % ergänzen auf 100 ml", true], ["Die Konzentration beträgt 10 mg/ml", true], ["Die Gabe erfolgt als Kurzinfusion über fünf Minuten", true], ["Die VFA verlangt einen unverdünnten 2-ml-Schnellbolus", false]], "1.000 mg in 100 ml ergeben 10 mg/ml; langsame Gabe reduziert das Hypotonierisiko.", 3),
  q(19, "Welche Grenzen enthält der Metamizolpfad der VFA 39?", [["Keine Gabe bei Schwangerschaft oder Stillzeit", true], ["Keine Metamizolgabe im Pfad bei RRsys unter 100 mmHg", true], ["Risikoaufklärung vor der Gabe", true], ["Oberbauchschmerz erfordert die Prüfung auf STEMI-Kriterien", true], ["Eine frühere Agranulozytose ist ohne Bedeutung", false]], "VFA-Verzweigungen und individuelle Kontraindikationen müssen gemeinsam geprüft werden.", 3),
  q(20, "Welche Aussagen zu Butylscopolamin sind korrekt?", [["Buscopan ist ein Handelsname für Butylscopolamin", true], ["Es blockiert peripher muskarinische Acetylcholinrezeptoren", true], ["Es entspannt glatte Muskulatur", true], ["Es gehört in VFA 39 nur zum kolikartigen Schmerzzweig", true], ["Es ist ein Opioidagonist", false]], "Butylscopolamin ist ein peripheres Antimuskarinikum und Spasmolytikum.", 2),
  q(21, "Welche Butylscopolamin-Zubereitung entspricht B2A?", [["20 mg befinden sich in 1 ml Wirkstoff", true], ["9 ml NaCl ergänzen auf 10 ml", true], ["Die Konzentration beträgt 2 mg/ml", true], ["Die Gabe erfolgt langsam i.v.", true], ["20 mg werden mit 99 ml NaCl auf 100 ml verdünnt", false]], "20 mg in 10 ml ergeben 2 mg/ml.", 3),
  q(22, "Ein Patient mit Pankreatitisverdacht hat konstanten gürtelförmigen Schmerz, RRsys 92 mmHg und Tachykardie. Welche Entscheidungen sind richtig?", [["Die Kreislaufinstabilität hat Vorrang vor dem Medikamentenschema", true], ["Der Metamizolzweig der VFA wird bei RRsys unter 100 mmHg nicht begonnen", true], ["Buscopan ist bei konstantem, nicht kolikartigem Schmerz nicht automatisch angezeigt", true], ["Schockbeurteilung, ärztliche Unterstützung und zügiger Transport sind erforderlich", true], ["Die Hypotonie wird ignoriert, weil Oberbauchschmerz typisch ist", false]], "Instabilität verändert die Priorität; VFA-Grenzen gelten auch bei starker Symptomatik.", 3),
  q(23, "Welche Befunde sprechen gegen eine automatische Buscopan-Gabe?", [["Konstanter statt kolikartiger Schmerz", true], ["Verdacht auf mechanischen Ileus", true], ["Relevante Tachyarrhythmie", true], ["Engwinkelglaukom oder Myasthenia gravis", true], ["Normofrequenter Sinusrhythmus ohne weitere Kontraindikation", false]], "Schmerzcharakter und Kontraindikationen müssen vor der Spasmolyse geprüft werden.", 3),
  q(24, "Welche Übergabe zeigt eine prüfungssichere Priorisierung?", [["Zeitverlauf, Schmerzcharakter und Rückenstrahlung", true], ["Vitaltrend, Kreislaufantwort und Atemstatus", true], ["Erbrechen, Bilanzhinweise, BZ und Temperatur", true], ["Gallensteine, Alkohol, ERCP, Medikamente und frühere Pankreatitis", true], ["Nur die Verdachtsdiagnose ohne Differenzialdiagnosen oder Maßnahmen", false]], "Eine strukturierte Übergabe verbindet Arbeitsdiagnose, Gefährdung, Verlauf und Behandlung.", 3),
];
