import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; children: ReactNode };

export default function PavkLesson({ Figure, children }: Props) {
  const section = (number: string, kicker: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>{kicker}</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;

  return <article className="lesson-article angina-pectoris-lesson venenthrombose-lesson pavk-lesson">
    <div className="lesson-intro"><p className="lead">Belastungsabhängiger Muskelschmerz ist das klassische Warnsignal der chronischen pAVK. Plötzlicher Schmerz, Kälte, Pulslosigkeit oder ein neurologisches Defizit bedeuten dagegen: akute Extremitätenischämie – Zeit ist Gewebe.</p></div>

    {section("01", "Begriff und zeitkritische Grenze", "Definition", <><p>Die <b>periphere arterielle Verschlusskrankheit (pAVK)</b> ist eine chronische Stenosierung oder Okklusion von Extremitätenarterien, überwiegend der Beine. Häufigste Ursache ist die Atherosklerose. Die Durchblutungsreserve distal der Engstelle nimmt ab und kann den Sauerstoffbedarf der Muskulatur zunächst nur unter Belastung, später auch in Ruhe nicht mehr decken.</p><aside className="knowledge-note"><b>Prüfungspräzision</b><p>Die chronische pAVK ist nicht mit dem akuten arteriellen Extremitätenverschluss gleichzusetzen. Eine Plaqueruptur, lokale Thrombose oder Embolie kann jedoch eine akute Extremitätenischämie auslösen.</p></aside></>)}

    {section("02", "Gefäßwand und Perfusion", "Anatomie und Physiologie", <><Figure src="/lessons/venenthrombose/vene-arterie-beschriftet.png" alt="Beschrifteter Vergleich von Arterie und Vene mit Gefäßwandschichten" caption="Arterie und Vene · Aufbau und funktioneller Unterschied" wide /><div className="pulmo-compare"><div><small>Arterie</small><h3>Druck- und Verteilungsgefäß</h3><p>Führt Blut vom Herzen weg. Die kräftige Tunica media hält dem höheren Druck stand; Arteriolen regulieren Widerstand und Organdurchblutung.</p></div><div><small>Vene</small><h3>Kapazitäts- und Rückstromgefäß</h3><p>Führt Blut zum Herzen zurück. Dünnere Media, größeres kollabierbares Lumen und – besonders an den Beinen – Klappen für den gerichteten Rückstrom.</p></div></div><div className="pulmo-anatomy-grid"><div><small>Innen</small><b>Tunica intima</b><p>Endothel und subendotheliale Schicht. Hier beginnt die atherosklerotische Gefäßwandveränderung.</p></div><div><small>Mitte</small><b>Tunica media</b><p>Glatte Muskulatur und elastische Fasern regulieren Gefäßweite und Verteilung des Blutstroms.</p></div><div><small>Außen</small><b>Tunica adventitia</b><p>Bindegewebige Stabilisierung mit Nervenfasern und bei großen Gefäßen Vasa vasorum.</p></div></div><h3>Wichtige arterielle Strombahn des Beines</h3><div className="pulmo-path"><span>Aorta abdominalis</span><i>→</i><span>A. iliaca</span><i>→</i><span>A. femoralis</span><i>→</i><span>A. poplitea</span><i>→</i><span>Unterschenkelarterien</span></div><p>Eine Stenose begrenzt die maximale Durchblutung. Kollateralen können den Ruhebedarf lange decken, unter Belastung reicht die Sauerstoffzufuhr jedoch nicht mehr aus.</p></>)}

    {section("03", "Von der Endothelschädigung zur Ischämie", "Ursachen und Pathophysiologie", <><div className="pulmo-path"><span>Endotheldysfunktion</span><i>→</i><span>LDL-Einlagerung</span><i>→</i><span>Entzündung</span><i>→</i><span>Plaque</span><i>→</i><span>Stenose</span></div><div className="pulmo-risk-grid"><div><b>Endothel und Lipide</b><p>LDL gelangt in die Intima, wird verändert und fördert die Anlagerung von Monozyten. Makrophagen nehmen Lipide auf und werden zu Schaumzellen.</p></div><div><b>Plaquewachstum</b><p>Glatte Muskelzellen und Bindegewebe bilden eine fibröse Kappe. Das Lumen wird enger, die Gefäßwand steifer und die Strömungsreserve kleiner.</p></div><div><b>Akute Eskalation</b><p>Plaqueruptur und Thrombusbildung oder ein eingeschwemmter Embolus können die Restperfusion abrupt unterbrechen.</p></div></div><h3>Risikofaktoren</h3><div className="material-chips">{["Rauchen", "Diabetes mellitus", "Arterielle Hypertonie", "Dyslipidämie", "Höheres Lebensalter", "Adipositas", "Bewegungsmangel", "Bekannte Atherosklerose"].map(item => <span key={item}>{item}</span>)}</div><aside className="knowledge-note"><b>Warum tut Gehen weh?</b><p>Arbeitende Muskulatur benötigt mehr Sauerstoff. Hinter der Stenose kann der Blutfluss nicht ausreichend steigen: Es entsteht eine belastungsabhängige Ischämie mit krampfartigem Muskelschmerz. In Ruhe sinkt der Bedarf und der Schmerz lässt nach.</p></aside></>)}

    {section("04", "Stadium und Lokalisation herleiten", "Symptome und Befunde", <><div className="pulmo-care-grid"><div><span>I</span><b>Asymptomatisch</b><small>Gefäßveränderung nachweisbar, noch keine Beschwerden.</small></div><div><span>II</span><b>Claudicatio intermittens</b><small>Belastungsschmerz mit reproduzierbarer Gehstrecke; IIa über 200 m, IIb unter 200 m.</small></div><div><span>III</span><b>Ischämischer Ruheschmerz</b><small>Besonders distal und nachts; Tieflagerung kann vorübergehend entlasten.</small></div><div><span>IV</span><b>Gewebeschaden</b><small>Ulkus, Nekrose oder Gangrän als Zeichen schwerer Minderperfusion.</small></div></div><div className="pulmo-symptoms"><span>Belastungsabhängiger Muskelschmerz</span><span>Kältegefühl</span><span>Blasse oder livide Haut</span><span>Verzögerte Rekapillarisierung</span><span>Abgeschwächte Pulse</span><span>Schlecht heilende Wunden</span></div><p>Die Schmerzlokalisation liegt typischerweise <b>distal der Stenose</b>: Aortoiliakale Läsionen verursachen eher Gesäß-/Oberschenkelbeschwerden, femoropopliteale Läsionen häufig Wadenschmerz. Bei diabetischer Polyneuropathie kann der Warnschmerz fehlen.</p><aside className="diagnostic-boundary"><span>!</span><div><b>6 P nach Pratt: akuter Verschluss</b><p><b>Pain, Pulselessness, Pallor, Paresthesia, Paralysis, Prostration.</b> Nicht alle Zeichen müssen gleichzeitig vorliegen. Sensibilitätsstörung und Lähmung sprechen für eine fortgeschrittene Ischämie und erhöhen die Dringlichkeit.</p></div></aside></>)}

    {section("05", "Extremität und Gesamtgefäßsystem", "Komplikationen und Gefahren", <><div className="pulmo-risk-grid"><div><b>Chronisch gliedmaßenbedrohend</b><p>Ruheschmerz, nicht heilende Wunde oder Gangrän können Amputation, Infektion und Sepsis nach sich ziehen.</p></div><div><b>Akute Extremitätenischämie</b><p>Plötzlicher Perfusionsverlust bedroht Nerven und Muskulatur. Neurologische Ausfälle sind späte Warnzeichen.</p></div><div><b>Systemische Atherosklerose</b><p>pAVK zeigt ein hohes kardiovaskuläres Risiko an; Myokardinfarkt und Schlaganfall sind wichtige Begleiterkrankungen.</p></div></div><aside className="red-flags"><span>!</span><div><small>Nach Wiedereröffnung</small><h3>Reperfusions- und Kompartmentsyndrom</h3><p>Rückstrom von Kalium, Säuren und Zellabbauprodukten kann Arrhythmien, Azidose, Kreislaufversagen und Nierenschädigung auslösen. Gewebsödem kann den Kompartmentdruck steigern.</p></div></aside></>)}

    {section("06", "Vorbereitet zum Patienten", "Einsatzmaterialien", <div className="material-chips">{["Notfallrucksack", "Monitoring / 12-Kanal-EKG", "Blutdruck und SpO₂", "i.v.-Material", "Sauerstoff bei Indikation", "Absaugung / Beatmung", "Analgesie nach Vorgabe", "Trage oder Tragestuhl"].map(item => <span key={item}>{item}</span>)}</div>)}

    {section("07", "cABCDE, pDMS und SAMPLERS", "Erstmaßnahmen und Diagnostik", <><div className="pulmo-care-grid"><div><span>01</span><b>cABCDE</b><small>Vitalbedrohung, Begleiterkrankungen und Hinweise auf systemische Ischämie priorisieren.</small></div><div><span>02</span><b>Seitenvergleich</b><small>Farbe, Temperatur, Rekapillarisierung, Pulse und pDMS wiederholt dokumentieren.</small></div><div><span>03</span><b>Lagerung</b><small>Betroffene Extremität druckfrei und eher tief lagern; nicht hochlagern, komprimieren, massieren oder aktiv erwärmen.</small></div><div><span>04</span><b>Transport</b><small>Nicht laufen lassen; bei akutem Verschluss zeitkritisch in eine Klinik mit Gefäßkompetenz transportieren.</small></div></div><h3>SAMPLERS · fokussiert</h3><div className="samplers-grid">{[["S · Symptome", "Plötzlich oder chronisch, Ruhe-/Belastungsschmerz, Gehstrecke"], ["A · Allergien", "Arznei- und Kontrastmittelallergien"], ["M · Medikamente", "Antikoagulation, Thrombozytenhemmung, Diabetesmedikation"], ["P · Vorgeschichte", "pAVK, Vorhofflimmern, Aneurysma, Gefäßeingriff"], ["L · Letzte Aufnahme", "Nahrung und Flüssigkeit"], ["E · Ereignis", "Belastung, Immobilisation, Eingriff, plötzlicher Beginn"], ["R · Risiken", "Rauchen, Diabetes, Hypertonie, Dyslipidämie"], ["S · Schwangerschaft", "Falls relevant"]].map(([label, text]) => <p key={label}><b>{label}</b>{text}</p>)}</div><p>Blutdruckmessung und Gefäßzugang möglichst nicht an der akut betroffenen oberen Extremität. Sauerstoff wird nach klinischer Indikation und Zielwert gegeben, nicht allein aufgrund der Diagnose pAVK.</p></>)}

    {section("08", "Nicht verwechseln", "Differenzialdiagnosen und Entscheidungen", <><div className="pulmo-compare"><div><small>Arterielle Ischämie</small><h3>Eher kalt, blass und pulsschwach</h3><p>Belastungs- oder Ruheschmerz; beim akuten Verschluss plötzlicher Beginn und mögliche neurologische Ausfälle.</p></div><div><small>Venöse Thrombose</small><h3>Eher warm, geschwollen und gespannt</h3><p>Venöse Abflussstörung mit meist erhaltenen arteriellen Pulsen; Gefahr der Lungenarterienembolie.</p></div></div><div className="differential-grid">{["Tiefe Venenthrombose", "Kompartment- oder Crush-Syndrom", "Claudicatio spinalis", "Polyneuropathie", "Muskuloskelettaler Schmerz", "Erysipel / Zellulitis", "Akute Aortendissektion", "Traumatische Gefäßverletzung"].map(item => <span key={item}>{item}</span>)}</div><aside className="knowledge-note"><b>Prüfungsfalle Claudicatio spinalis</b><p>Bei einer Spinalkanalstenose hängt die Besserung oft stärker von Flexion oder Sitzen als vom bloßen Stehenbleiben ab. Periphere Pulse und Hautperfusion können normal sein.</p></aside></>)}

    {section("09", "Zeitkritik vor Aktionismus", "Weitere Maßnahmen", <><div className="pulmo-vfa-flow"><div><span>IV</span><b>Zugang</b><small>i.v.-Zugang an einer nicht betroffenen Extremität, ohne den Transport unnötig zu verzögern.</small></div><div><span>Rx</span><b>Analgesie</b><small>Nach Schmerzintensität, Kreislaufstatus und geltender Thüringer VFA; Wirkung und Nebenwirkungen überwachen.</small></div><div><span>NA</span><b>Ärztliche Unterstützung</b><small>Bei vitaler Bedrohung, starkem Schmerz, fortgeschrittener Ischämie oder erforderlicher Therapie früh nachfordern.</small></div><div><span>→</span><b>Gefäßzentrum</b><small>Beginn, Verlauf, 6-P-Befund, pDMS, Pulse, Medikamente und Antikoagulation strukturiert übergeben.</small></div></div><aside className="diagnostic-boundary"><span>!</span><div><b>Antikoagulation nicht pauschal</b><p>Heparin gehört zur klinisch-ärztlichen Therapie der akuten Extremitätenischämie, ist aber präklinisch nicht automatisch bei jedem pAVK-Verdacht zu geben. Maßgeblich sind Indikation, Kontraindikationen und die geltende ärztliche bzw. lokale Vorgabe.</p></div></aside></>)}

    {section("10", "Mündliche Prüfung", "Entscheidungsübersicht", <><div className="pulmo-path"><span>Chronische Belastungsbeschwerden?</span><i>→</i><span>pDMS und Pulse</span><i>→</i><span>Akute 6-P-Zeichen?</span><i>→</i><span>Zeitkritischer Gefäßtransport</span></div><p>Eine starke Prüfungsantwort erklärt zuerst die chronische atherosklerotische Durchblutungsbegrenzung, ordnet Fontaine-Stadien und Läsionshöhe zu und wechselt bei plötzlichem Beginn oder neurologischem Defizit konsequent zur akuten Extremitätenischämie.</p></>)}

    {children}
    <p className="lesson-source">Hauptgrundlage: bereitgestellte Unterlagen „41. pAVK“ und „41. Periphere arterielle Verschlusskrankheit“. Fachlich präzisiert für die rettungsdienstliche Differenzierung von chronischer pAVK und akuter Extremitätenischämie.</p>
  </article>;
}
