import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct: boolean];
function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  const shift = (number * 3) % options.length;
  return { id: `pavk-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty };
}

export const pavkFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "pavk-card-01", area: "Definition", question: "Definieren Sie die pAVK und grenzen Sie sie von der akuten Extremitätenischämie ab.", answer: "Die pAVK ist eine meist atherosklerotisch bedingte chronische Stenosierung oder Okklusion von Extremitätenarterien. Die akute Extremitätenischämie ist ein plötzlicher Perfusionsverlust, etwa durch Embolie, Plaqueruptur oder lokale Thrombose, und unmittelbar zeitkritisch." },
  { id: "pavk-card-02", area: "Gefäßwand", question: "Welche Gefäßwandschicht ist Ausgangspunkt der Atherosklerose und welche Schicht ist in Arterien besonders kräftig?", answer: "Die Atherosklerose beginnt an der Intima beziehungsweise mit einer Endotheldysfunktion. Die Tunica media ist in Arterien wegen Druckbelastung und Gefäßweitenregulation deutlich kräftiger als in Venen." },
  { id: "pavk-card-03", area: "Pathophysiologie", question: "Leiten Sie von LDL-Einlagerung bis zur hämodynamisch relevanten Plaque her.", answer: "Endotheldysfunktion ermöglicht LDL-Einlagerung und -Veränderung in der Intima. Entzündung rekrutiert Monozyten; Makrophagen werden zu Schaumzellen. Glatte Muskelzellen und Matrix bilden eine fibröse Plaque, die das Lumen einengt und die Durchblutungsreserve reduziert." },
  { id: "pavk-card-04", area: "Claudicatio", question: "Warum tritt der Schmerz zunächst nur beim Gehen auf und verschwindet in Ruhe?", answer: "Belastung steigert den Sauerstoffbedarf der Muskulatur. Hinter der Stenose lässt sich der Blutfluss nicht ausreichend erhöhen. In Ruhe fällt der Bedarf wieder ab, sodass die vorhandene Perfusion genügt und der Ischämieschmerz nachlässt." },
  { id: "pavk-card-05", area: "Stadien", question: "Nennen Sie die Fontaine-Stadien I bis IV einschließlich IIa und IIb.", answer: "I asymptomatisch; II Claudicatio, IIa schmerzfreie Gehstrecke über 200 m, IIb unter 200 m; III ischämischer Ruheschmerz; IV Ulkus, Nekrose oder Gangrän." },
  { id: "pavk-card-06", area: "Lokalisation", question: "Wie lässt die Schmerzlokalisation auf die Höhe der arteriellen Läsion schließen?", answer: "Beschwerden treten distal der Stenose auf: Aortoiliakale Läsionen verursachen eher Gesäß- oder Oberschenkelschmerz, femoropopliteale Läsionen häufig Wadenschmerz, distale Läsionen eher Fußbeschwerden und akrale Gewebeschäden." },
  { id: "pavk-card-07", area: "6 P", question: "Nennen und bewerten Sie die 6 P nach Pratt.", answer: "Pain, Pulselessness, Pallor, Paresthesia, Paralysis und Prostration. Sie kennzeichnen den akuten arteriellen Verschluss; nicht alle müssen vorliegen. Sensibilitäts- und Motorikausfälle weisen auf eine fortgeschrittene, gliedmaßenbedrohende Ischämie hin." },
  { id: "pavk-card-08", area: "Diabetes", question: "Warum kann eine schwere pAVK bei Diabetes lange wenig schmerzhaft sein?", answer: "Eine diabetische Polyneuropathie vermindert die Schmerzwahrnehmung. Dadurch können Ulzera, Nekrosen oder eine kritische Minderperfusion trotz fehlender typischer Claudicatio fortgeschritten sein." },
  { id: "pavk-card-09", area: "Untersuchung", question: "Welche Befunde müssen im präklinischen Seitenvergleich dokumentiert werden?", answer: "Farbe, Temperatur, Rekapillarisierungszeit, tastbare Pulse sowie periphere Durchblutung, Motorik und Sensibilität. Verlaufskontrollen zeigen eine Verschlechterung zuverlässiger als ein Einzelbefund." },
  { id: "pavk-card-10", area: "Differenzialdiagnose", question: "Grenzen Sie akute arterielle Ischämie und tiefe Venenthrombose klinisch ab.", answer: "Arteriell eher plötzlich, kalt, blass, pulsschwach oder pulslos, später mit Sensibilitäts- und Motorikdefizit. Venös eher warm, geschwollen und gespannt bei meist erhaltenen arteriellen Pulsen. Ausnahmen erfordern cABCDE und Seitenvergleich." },
  { id: "pavk-card-11", area: "Lagerung", question: "Wie wird eine akut ischämische Extremität präklinisch gelagert und was ist zu vermeiden?", answer: "Druckfrei und eher tief, um die schwerkraftabhängige Perfusion nicht zu vermindern. Hochlagerung, Kompression, Massage sowie direkte aktive Wärme- oder Kälteanwendung sind zu vermeiden." },
  { id: "pavk-card-12", area: "Reperfusion", question: "Welche systemischen Gefahren können nach Wiedereröffnung eines länger ischämischen Gefäßes auftreten?", answer: "Kalium, Säuren, Myoglobin und Entzündungsmediatoren gelangen in den Kreislauf. Möglich sind Hyperkaliämie, Azidose, Arrhythmien, Kreislaufversagen, akute Nierenschädigung und ein Reperfusionsödem bis zum Kompartmentsyndrom." },
  { id: "pavk-card-13", area: "Transport", question: "Welche Befunde machen die gefäßchirurgische Versorgung besonders zeitkritisch?", answer: "Plötzlicher Beginn, fehlende Pulse, zunehmender Schmerz, Marmorierung oder Blässe, verzögerte Rekapillarisierung sowie insbesondere neue Sensibilitäts- oder Motorikdefizite." },
  { id: "pavk-card-14", area: "Präklinische Grenze", question: "Warum wird Heparin nicht automatisch bei jedem pAVK-Verdacht gegeben?", answer: "Chronische pAVK allein ist keine pauschale präklinische Heparinindikation. Bei akuter Extremitätenischämie muss die Antikoagulation anhand von Indikation, Blutungsrisiko, Kontraindikationen und geltender ärztlicher oder lokaler Vorgabe entschieden werden." },
];

export const pavkQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen beschreiben die pAVK korrekt?", [["Sie betrifft überwiegend Extremitätenarterien und beruht meist auf Atherosklerose", true], ["Sie reduziert die Durchblutungsreserve distal einer Stenose", true], ["Sie kann lange asymptomatisch bleiben", true], ["Sie ist definitionsgemäß immer ein plötzliches embolisches Ereignis", false], ["Erhaltene Pulse schließen jedes Stadium sicher aus", false]], "pAVK ist meist chronisch-atherosklerotisch; akute Ischämie ist eine mögliche Eskalation.", 1),
  q(2, "Welche Zuordnungen zum Gefäßwandaufbau sind richtig?", [["Die Tunica intima umfasst die endotheliale Oberfläche", true], ["Arterien besitzen typischerweise eine kräftigere Tunica media als Venen", true], ["Die Adventitia stabilisiert das Gefäß im umgebenden Gewebe", true], ["Atherosklerose beginnt regelhaft an den Venenklappen", false], ["Arterien werden durch ihren Sauerstoffgehalt definiert", false]], "Arterien werden durch die Flussrichtung vom Herzen weg definiert; die Atherosklerose beginnt an der Intima.", 1),
  q(3, "Welche Schritte gehören zur atherosklerotischen Plaqueentstehung?", [["Endotheldysfunktion und Einlagerung veränderter LDL-Partikel", true], ["Monozyteneinwanderung und Bildung von Schaumzellen", true], ["Migration glatter Muskelzellen und Bildung einer fibrösen Kappe", true], ["Primär vollständige Auflösung der Tunica adventitia", false], ["Obligate bakterielle Besiedlung der Gefäßwand", false]], "Die Plaque entsteht als chronisch-entzündlicher Prozess der Intima mit Lipiden, Schaumzellen, Muskelzellen und Matrix.", 2),
  q(4, "Warum entsteht eine Claudicatio intermittens typischerweise unter Belastung?", [["Der Sauerstoffbedarf der arbeitenden Muskulatur steigt", true], ["Die Stenose begrenzt die mögliche Flusssteigerung", true], ["In Ruhe sinkt der Bedarf und der Schmerz kann nachlassen", true], ["Gehen führt regelhaft zum vollständigen Verschluss der Vene", false], ["Der Schmerz beruht ausschließlich auf Gelenküberlastung", false]], "Angebot und Bedarf klaffen unter Belastung auseinander; in Ruhe genügt die eingeschränkte Perfusion zunächst wieder.", 2),
  q(5, "Welche Aussagen zur Fontaine-Klassifikation sind korrekt?", [["Stadium I ist klinisch asymptomatisch", true], ["Stadium II beschreibt die belastungsabhängige Claudicatio", true], ["Stadium III umfasst ischämischen Ruheschmerz", true], ["Stadium IV umfasst Ulkus, Nekrose oder Gangrän", true], ["Stadium IIb bedeutet eine schmerzfreie Gehstrecke über 500 Meter", false]], "IIa liegt über 200 m, IIb unter 200 m; III und IV kennzeichnen fortgeschrittene Ischämie.", 2),
  q(6, "Welche Befunde passen eher zur chronischen pAVK als zur akuten Extremitätenischämie?", [["Reproduzierbarer Wadenschmerz nach ähnlicher Gehstrecke", true], ["Beschwerdebesserung nach kurzer Gehpause", true], ["Chronisch schlecht heilende distale Wunde", true], ["Plötzlich neu aufgetretene Lähmung seit 20 Minuten", false], ["Abrupte Pulslosigkeit mit kalter marmorierter Extremität", false]], "Chronische Belastungsabhängigkeit und trophische Störungen unterscheiden sich vom plötzlichen akuten Perfusionsverlust.", 2),
  q(7, "Welche 6-P-Befunde stützen einen akuten arteriellen Extremitätenverschluss?", [["Pain und Pallor", true], ["Pulselessness", true], ["Paresthesia und Paralysis", true], ["Prostration", true], ["Pitting edema als obligates Frühzeichen", false]], "Die 6 P nach Pratt gelten dem akuten arteriellen Verschluss; einzelne Zeichen können fehlen.", 2),
  q(8, "Welche Befunde weisen auf eine fortgeschrittene akute Extremitätenischämie hin?", [["Neu aufgetretene Sensibilitätsstörung", true], ["Muskelschwäche oder Lähmung", true], ["Marmorierung und fehlende periphere Pulse", true], ["Allein ein seit Jahren unveränderter belastungsabhängiger Wadenschmerz", false], ["Warme geschwollene Extremität mit erhaltenen Pulsen als eindeutiger arterieller Befund", false]], "Neurologische Ausfälle zeigen eine bedrohte neuromuskuläre Funktion und erhöhen die Zeitkritik.", 3),
  q(9, "Welche Untersuchungen sind präklinisch bei Verdacht auf arterielle Minderperfusion sinnvoll?", [["Pulse und Rekapillarisierung im Seitenvergleich", true], ["Farbe und Temperatur beider Extremitäten", true], ["Periphere Motorik und Sensibilität mit Verlaufskontrolle", true], ["Kräftige Massage zur Prüfung der Kollateralreserve", false], ["Ein einmaliger Normalbefund ohne erneute Kontrolle", false]], "pDMS, Pulse, Hautbefund und Verlauf müssen seitenvergleichend dokumentiert werden.", 2),
  q(10, "Welche Maßnahmen passen zur akut ischämischen Extremität?", [["Druckfreie, eher tiefe Lagerung", true], ["Schonender Transport ohne Gehbelastung", true], ["Frühe Zielklinik mit Gefäßkompetenz", true], ["Kompressionsverband zur Steigerung des arteriellen Einstroms", false], ["Direkte intensive Wärmeanwendung auf die gefühllose Extremität", false]], "Hochlagerung und Kompression verschlechtern den Perfusionsdruck; direkte Wärme birgt bei Sensibilitätsstörung Verletzungsgefahr.", 2),
  q(11, "Welche Konstellationen sprechen eher für eine tiefe Venenthrombose als für einen akuten arteriellen Verschluss?", [["Warme, geschwollene und gespannte Extremität", true], ["Meist erhaltene arterielle Pulse", true], ["Rötlich-livide Verfärbung bei venösem Risikoprofil", true], ["Plötzliche Pulslosigkeit mit Lähmung", false], ["Kalte blasse Extremität mit rascher Rekapillarisierungsverschlechterung", false]], "Venöse Abflussstörung erzeugt Stauung; arterielle Ischämie erzeugt Minderperfusion.", 2),
  q(12, "Welche Aussagen zur Läsionshöhe und Schmerzlokalisation sind plausibel?", [["Aortoiliakale Stenosen können Gesäß- und Oberschenkelschmerz verursachen", true], ["Femoropopliteale Läsionen äußern sich häufig durch Wadenschmerz", true], ["Beschwerden treten grundsätzlich distal der hämodynamisch relevanten Stenose auf", true], ["Wadenschmerz beweist immer eine Läsion der Zehenarterien", false], ["Die Lokalisation erlaubt ohne weitere Diagnostik eine sichere Zentimeterangabe", false]], "Die Schmerzregion hilft bei der groben topografischen Zuordnung, ersetzt aber keine Gefäßdiagnostik.", 3),
  q(13, "Welche Aussagen erklären die besondere Gefahr bei Diabetes mellitus?", [["Polyneuropathie kann den Ischämieschmerz abschwächen", true], ["Distale pAVK und Wundheilungsstörungen können unbemerkt fortschreiten", true], ["Fehlender Schmerz schließt eine schwere Ischämie nicht aus", true], ["Diabetes schützt durch Kollateralbildung vor Gangrän", false], ["Bei Diabetes sind Haut- und pDMS-Befunde entbehrlich", false]], "Neuropathie kann Warnsymptome maskieren; Untersuchung und Wundkontrolle sind deshalb besonders wichtig.", 3),
  q(14, "Welche Komplikationen können mit einer fortgeschrittenen pAVK verbunden sein?", [["Chronische gliedmaßenbedrohende Ischämie", true], ["Ulkus, Nekrose oder Gangrän", true], ["Wundinfektion bis zur Sepsis", true], ["Erhöhtes Risiko für Myokardinfarkt und Schlaganfall", true], ["Zuverlässige dauerhafte Schmerzfreiheit trotz Gewebeuntergang", false]], "pAVK ist eine lokale Durchblutungsstörung und zugleich Marker einer systemischen Atherosklerose.", 3),
  q(15, "Welche Mechanismen können eine chronische pAVK akut verschlechtern?", [["Plaqueruptur mit lokaler Thrombusbildung", true], ["Kardiale Embolie bei Vorhofflimmern", true], ["Thrombose im Bereich eines Aneurysmas", true], ["Allein eine intakte Venenklappe", false], ["Isolierte venöse Stase ohne arterielles Ereignis als zwingende Ursache", false]], "Akuter Verschluss kann thrombotisch oder embolisch entstehen; Vorhofflimmern und Aneurysmen sind wichtige Hinweise.", 3),
  q(16, "Welche Aussagen zum Reperfusionssyndrom sind richtig?", [["Kalium und Säuren können aus dem ischämischen Gewebe eingeschwemmt werden", true], ["Arrhythmien und Azidose sind mögliche systemische Folgen", true], ["Myoglobin kann die Nieren schädigen", true], ["Reperfusionsödem kann ein Kompartmentsyndrom fördern", true], ["Die Wiedereröffnung beendet jedes Risiko sofort und vollständig", false]], "Reperfusion rettet Gewebe, kann aber lokale und systemische Folgeschäden auslösen.", 3),
  q(17, "Welche Punkte gehören zur fokussierten SAMPLERS-Anamnese?", [["Beginn: plötzlich oder schleichend sowie Ruhe- oder Belastungsabhängigkeit", true], ["Vorhofflimmern, Aneurysma und frühere Gefäßeingriffe", true], ["Rauchen, Diabetes, Hypertonie und Dyslipidämie", true], ["Antikoagulation und Thrombozytenhemmung", true], ["Die Familien- und Medikamentenanamnese ist grundsätzlich bedeutungslos", false]], "Zeitverlauf, embolische Quellen, Atheroskleroserisiken und gerinnungswirksame Medikamente steuern die Entscheidung.", 2),
  q(18, "Welche Entscheidungen sind bei plötzlichem Beinschmerz mit fehlendem Puls und Taubheit angemessen?", [["Akute Extremitätenischämie priorisieren", true], ["pDMS dokumentieren und engmaschig kontrollieren", true], ["Zeitkritisch eine Klinik mit Gefäßkompetenz anfahren", true], ["Die Person zur Prüfung der Gehstrecke laufen lassen", false], ["Bis zum Auftreten einer Lähmung ohne Transport abwarten", false]], "Pulslosigkeit plus Sensibilitätsdefizit spricht für bedrohtes Gewebe; die Versorgung darf nicht verzögert werden.", 3),
  q(19, "Welche Aussagen zur Sauerstoffgabe und zum Monitoring treffen zu?", [["Sauerstoff wird nach klinischer Indikation und Zielwert gegeben", true], ["Ein 12-Kanal-EKG kann relevante kardiale Begleiterkrankungen oder Emboliequellen erfassen", true], ["Verlaufskontrollen der Extremitätenperfusion bleiben trotz Monitoring erforderlich", true], ["Die Diagnose pAVK verlangt unabhängig von der Sättigung immer maximalen Sauerstofffluss", false], ["Normale Herzfrequenz schließt eine akute Ischämie aus", false]], "Oxygenierung wird zielgerichtet behandelt; Monitoring ersetzt die lokale Perfusionskontrolle nicht.", 3),
  q(20, "Welche Aussagen zur Antikoagulation sind prüfungssicher?", [["Akute Extremitätenischämie kann eine ärztlich geführte Antikoagulation erfordern", true], ["Blutungsrisiko und Kontraindikationen müssen berücksichtigt werden", true], ["Lokale beziehungsweise ärztliche Vorgaben bestimmen die präklinische Durchführung", true], ["Jeder chronische Claudicatio-Verdacht verlangt sofort Heparin", false], ["Eine unklare Extremitätensymptomatik hebt alle Kontraindikationen auf", false]], "Heparin ist keine automatische Maßnahme bei jeder pAVK, sondern eine indikationsgebundene Therapieentscheidung.", 3),
  q(21, "Welche Befunde passen eher zu einer Claudicatio spinalis?", [["Besserung besonders durch Sitzen oder Vorbeugen", true], ["Normale periphere Pulse trotz belastungsabhängiger Beschwerden", true], ["Rückenschmerz oder neurologische Begleitsymptome", true], ["Sicher fehlende Pulse distal einer arteriellen Stenose", false], ["Obligate Gangrän der Zehen", false]], "Bei spinaler Claudicatio sind Haltung und Wirbelsäulenposition oft entscheidender als das reine Stehenbleiben.", 3),
  q(22, "Welche Übergabeinformationen sind bei akuter Extremitätenischämie besonders relevant?", [["Exakter oder letztbekannt symptomfreier Zeitpunkt", true], ["Seitenvergleich von Pulsen, pDMS, Farbe und Temperatur", true], ["Verlauf und Dynamik neurologischer Ausfälle", true], ["Vorhofflimmern, Aneurysmen, Eingriffe und gerinnungswirksame Medikamente", true], ["Nur die numerische Schmerzstärke ohne Untersuchungsbefund", false]], "Zeitpunkt, Perfusionsstatus, Neurologie und mögliche Ursache bestimmen Dringlichkeit und Therapieplanung.", 3),
];
