import type { ComponentType, ReactNode } from "react";
import BronchoPreparation from "./broncho-preparation";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function PneumonieLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>Pneumonie · mündliche Prüfung</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;
  return <article className="lesson-article rippenfraktur-lesson broncho-lesson pneumonia-lesson">
    <div className="lesson-intro"><p className="lead">Pneumonie ist mehr als „Fieber und Husten“: Entscheidend sind gestörter Gasaustausch, respiratorische Erschöpfung, Sepsiszeichen und gefährliche Differenzialdiagnosen. Präklinisch wird das Muster erkannt und die Vitalbedrohung behandelt – nicht der Erreger bewiesen.</p></div>

    {section("01", "Definition", <><p>Eine Pneumonie ist eine <b>infektiös bedingte Entzündung des Lungengewebes</b>. Sie kann ambulant erworben oder im Zusammenhang mit einem Krankenhausaufenthalt entstehen. Auslöser sind vor allem Bakterien und Viren, seltener Pilze. Davon abzugrenzen ist die zunächst nicht infektiöse, chemische Pneumonitis nach Aspiration; eine bakterielle Pneumonie kann sich anschließen.</p><div className="pulmo-risk-grid"><div><b>Primäre Pneumonie</b><p>Entsteht ohne vorausgehende schwere Grund- oder Begleiterkrankung.</p></div><div><b>Sekundäre Pneumonie</b><p>Wird durch Risikofaktoren wie Sekretretention, Aspiration, COPD, Herzinsuffizienz, Immobilität oder Immunsuppression begünstigt.</p></div></div></>)}

    {section("02", "Anatomie und Physiologie", <><div className="pulmo-anatomy-grid"><div><small>Luftleitung</small><b>Trachea · Bronchien · Bronchiolen</b><p>Sie transportieren die Atemluft. Flimmerepithel und Schleim befördern gebundene Partikel nach kranial.</p></div><div><small>Gasaustausch</small><b>Alveole · Interstitium · Kapillare</b><p>O₂ und CO₂ überwinden eine sehr dünne alveolokapilläre Membran. Kurze Diffusionswege sind dafür entscheidend.</p></div><div><small>Abwehr</small><b>Husten · mukoziliäre Clearance · Makrophagen</b><p>Nasenfilter, Hustenreflex, Flimmerepithel und alveoläre Makrophagen begrenzen das Eindringen von Erregern.</p></div></div><div className="figure-grid"><Figure src="/lessons/anatomie/anatomie-39.jpg" alt="Beschriftete Übersicht der oberen und unteren Atemwege" caption="Atemwege · Nase, Rachen, Trachea, Bronchien, Lunge und Zwerchfell" /><Figure src="/lessons/anatomie/anatomie-42.jpg" alt="Beschriftete Darstellung von Lunge, Alveolen und Zellen der Atemwege" caption="Alveolen und Atemwegsepithel · Gasaustausch und mukoziliäre Abwehr" /></div><p><b>Prüfungszusammenhang:</b> In den Alveolen ersetzt entzündliches Sekret Luft. Gleichzeitig verdickt ein interstitielles Ödem den Diffusionsweg. Belüftung und Durchblutung passen dadurch nicht mehr zusammen.</p></>)}

    {section("03", "Ursachen und Pathophysiologie", <><div className="pulmo-path"><span>Erreger oder Aspirat erreicht tiefe Atemwege</span><i>→</i><span>lokale Immunreaktion</span><i>→</i><span>Kapillarleck und Exsudat</span><i>→</i><span>Diffusions- und Ventilationsstörung</span></div><p>Erreger vermehren sich im Lungengewebe. Entzündungsmediatoren erhöhen die Gefäßdurchlässigkeit; Flüssigkeit, Abwehrzellen und Zelltrümmer füllen Alveolen oder verbreitern das Interstitium. Die Folge sind Minderbelüftung, vergrößerte Diffusionsstrecke, Ventilations-Perfusions-Missverhältnis und steigende Atemarbeit.</p><div className="broncho-vs"><article><small>Häufig bakterielles Muster</small><h3>Eher alveolär und fokal</h3><p>Oft plötzlicher Beginn, höheres Fieber, produktiver Husten, fokale Rasselgeräusche und pleuritischer Schmerz. Dieses Muster ist <b>kein Erregernachweis</b>.</p></article><article><small>Häufig virales Muster</small><h3>Eher diffus und interstitiell</h3><p>Oft schleichender Beginn, trockener Husten, Myalgien und diffuse Befunde. Auch Viren können schwere alveoläre Verläufe verursachen.</p></article></div><aside className="knowledge-note"><b>Aspiration als eigener Mechanismus</b><p>Bei Bewusstseinsstörung, Alkoholintoxikation, Schlaganfall, Schädel-Hirn-Trauma, neurologischer Erkrankung oder Dysphagie können Sekret, Nahrung oder Mageninhalt in die Lunge gelangen. Saure Mageninhalte können zunächst eine chemische Pneumonitis bis hin zum ARDS auslösen; eine bakterielle Pneumonie kann folgen.</p></aside></>)}

    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", <><div className="broncho-comparison" role="table" aria-label="Befunde bei Pneumonie"><div role="row"><b role="columnheader">Bereich</b><b role="columnheader">Mögliche Befunde</b><b role="columnheader">Einordnung</b></div>{[["Atmung","Dyspnoe, Tachypnoe, Hypoxämie","Schweregrad über Atemarbeit, SpO₂, Sprechen und Verlauf beurteilen"],["Allgemein","Fieber, Schüttelfrost, Abgeschlagenheit","Bei älteren oder immunsupprimierten Menschen kann Fieber fehlen"],["Husten","Trocken oder produktiv, Auswurf möglich","Farbe des Auswurfs beweist keinen Erreger"],["Thorax","Atemabhängiger Schmerz","Pleurabeteiligung und Differenzialdiagnosen beachten"],["Untersuchung","Feuchte Rasselgeräusche, abgeschwächtes Atemgeräusch, gedämpfter Klopfschall","Fokale Befunde stützen, ein unauffälliger Befund schließt nicht sicher aus"]].map(([a,b,c])=><div role="row" key={a}><b role="rowheader">{a}</b><span role="cell">{b}</span><span role="cell">{c}</span></div>)}</div><aside className="red-flags"><span>!</span><div><small>Red Flags</small><h3>Respiratorische Erschöpfung oder Sepsis</h3><p>Vigilanzminderung, Zyanose, Sprechdyspnoe, stark erhöhte oder abfallende Atemfrequenz, Hypotonie, schlechte Rekapillarisierung, neue Verwirrtheit oder rasche Verschlechterung erfordern eine zeitkritische Eskalation.</p></div></aside></>)}

    {section("05", "Komplikationen und Gefahren", <><div className="pulmo-risk-grid"><div><b>Respiratorische Insuffizienz</b><p>Zunehmender Shunt, Hypoxämie, Erschöpfung und gegebenenfalls Hyperkapnie.</p></div><div><b>Sepsis und Schock</b><p>Dysregulierte Infektionsantwort mit Organdysfunktion und möglicher Kreislaufinstabilität.</p></div><div><b>ARDS</b><p>Diffuse entzündliche Lungenschädigung mit schwerer Oxygenierungsstörung.</p></div><div><b>Lokale Ausbreitung</b><p>Pleuritis, Pleuraerguss, Empyem oder Lungenabszess.</p></div></div><p>Eine Pneumonie kann eine Herzinsuffizienz oder chronische Lungenerkrankung dekompensieren. Bei Aspiration drohen unmittelbare Atemwegsverlegung, chemische Schädigung und eine verzögert zunehmende respiratorische Insuffizienz.</p></>)}

    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", <div className="material-chips">{["PSA", "Notfallrucksack", "EKG / RR / SpO₂", "Temperaturmessung", "Sauerstoff", "Absaugung", "Beatmungsbeutel", "Kapnometrie", "Beatmungsgerät mit CPAP/ASB", "i.v.-Material", "Bronchodilatatoren nur bei Obstruktion", "Atemwegsmaterial"].map(item=><span key={item}>{item}</span>)}</div>)}

    {section("07", "Erstmaßnahmen und SAMPLERS", <><div className="pulmo-care-grid"><div><span>01</span><b>cABCDE</b><small>Atemweg, Atemarbeit, Atemfrequenz, Auskultation, Oxygenierung, Kreislauf und Vigilanz erfassen.</small></div><div><span>02</span><b>Position und O₂</b><small>Oberkörper hoch, atemerleichternde Position; Sauerstoff bedarfsgerecht mit Verlaufskontrolle.</small></div><div><span>03</span><b>Diagnostik</b><small>Monitoring, Temperatur, Blutzucker, Auskultation und bei schwerem Verlauf Kapnometrie; EKG bei entsprechender Lage.</small></div><div><span>04</span><b>Eskalation</b><small>Bei Erschöpfung Beatmung vorbereiten, Notarzt früh nachfordern und geeignete Zielklinik wählen.</small></div></div><div className="samplers-grid">{[["S · Symptome","Beginn, Fieber, Husten, Auswurf, Dyspnoe, Thoraxschmerz"],["A · Allergien","Antibiotika- und Medikamentenallergien"],["M · Medikamente","Immunsuppression, Inhalativa, Antibiotika, Antikoagulation"],["P · Vorgeschichte","COPD/Asthma, Herzinsuffizienz, Dysphagie, Pflegebedürftigkeit"],["L · Letzte Aufnahme","Nahrung, Flüssigkeit, Erbrechen, Aspirationsereignis"],["E · Ereignis","Infektkontakt, Krankenhausaufenthalt, Aspiration, Immobilität"],["R · Risiken","Alter, Immunsuppression, Multimorbidität, resistente Erreger"],["S · Sonstiges","Ausgangszustand, Vorausverfügung, Verlauf und Vorbehandlung"]].map(([a,b])=><p key={a}><b>{a}</b>{b}</p>)}</div><aside className="knowledge-note"><b>Aspirationsschutz</b><p>Bei akuter Dysphagie nichts essen oder trinken lassen. Absaugung und Atemwegsmanagement vorbereiten; nach Aspiration nicht auf einen zunächst unauffälligen Einzelwert verlassen.</p></aside></>)}

    {section("08", "Differenzialdiagnosen und Entscheidungsfindung", <><div className="differential-grid">{["Kardiales Lungenödem", "Lungenarterienembolie", "COPD-/Asthma-Exazerbation", "Pneumothorax", "Akutes Koronarsyndrom", "Pleuritis", "Atelektase", "Aspiration/Fremdkörper", "Sepsis anderer Ursache"].map(item=><span key={item}>{item}</span>)}</div><div className="pulmo-risk-grid"><div><b>Für Pneumonie</b><p>Infektzeichen, Husten, fokale oder diffuse Rasselgeräusche, pleuritischer Schmerz und passender Verlauf ergeben zusammen ein plausibles Muster.</p></div><div><b>Gegen vorschnelle Festlegung</b><p>Plötzlicher Beginn, einseitig fehlendes Atemgeräusch, deutliche Beinzeichen, grobblasiges Brodeln oder Ischämiehinweise verlangen eine alternative Arbeitsdiagnose.</p></div></div><p>Präklinisch ist die Diagnose klinisch begründet, aber nicht endgültig gesichert. Verlauf und Therapieresponse werden wiederholt mit dem Ausgangsbefund verglichen.</p></>)}

    {section("09", "Weitere Maßnahmen · VFA richtig einordnen", <><div className="pulmo-vfa-flow"><div><span>O₂</span><b>Oxygenierung sichern</b><small>Bedarfsgerecht titrieren und klinische Wirkung fortlaufend kontrollieren.</small></div><div><span>21</span><b>Nur bei Bronchoobstruktion</b><small>Giemen und verlängerte Exspiration können einen zusätzlichen obstruktiven Anteil anzeigen. Dann VFA 21 prüfen.</small></div><div><span>06</span><b>CPAP/ASB erwägen</b><small>Bei schwerer Ateminsuffizienz und erhaltener Kooperation nach Indikation und Kontraindikationen der VFA 06.</small></div><div><span>→</span><b>Zeitkritischer Transport</b><small>Sepsis, zunehmende Hypoxämie oder Erschöpfung früh kommunizieren und Zielklinik voranmelden.</small></div></div><aside className="legal-warning"><b>Prüfungsfalle: Pneumonie ist keine automatische Bronchodilatator-Indikation</b><p>Salbutamol, Ipratropium und Prednisolon behandeln eine relevante Bronchoobstruktion – nicht den alveolären Infekt selbst. Präklinische Antibiotikadosierungen sind in den hier verwendeten VFA-Seiten nicht vorgesehen und werden deshalb nicht ergänzt.</p></aside><p><b>CPAP-Wirkprinzip:</b> Der positive Atemwegsdruck kann rekrutierbare Alveolen offen halten, die funktionelle Residualkapazität erhöhen und die Atemarbeit vermindern. Fehlende Schutzreflexe, Erbrechen, Bewusstlosigkeit oder fehlende Kooperation sprechen gegen eine nicht invasive Anwendung.</p></>)}

    {section("10", "VFA Thüringen 2026/2027 und Medikamentenvorbereitung", <><p>Die Originalseiten werden zur Prüfung der Indikation eingeblendet. VFA 21 gilt nur bei vorhandener Bronchoobstruktion; VFA 06 regelt die nicht invasive Atemunterstützung. Konzentration, Arzneimittel und aktuelle Original-VFA sind vor jeder Anwendung zu kontrollieren.</p><div className="vfa-stack"><Vfa src="/lessons/bronchoobstruktion/vfa-4.png" alt="Thüringer VFA 21 Bronchoobstruktion Erwachsene" caption="VFA 21 · Bronchoobstruktion Erwachsene · nur bei passendem obstruktivem Befund" /><Vfa src="/lessons/bronchoobstruktion/vfa-5.png" alt="Thüringer VFA 06 nicht invasive CPAP-ASB-Therapie und Kapnometrie" caption="VFA 06 · CPAP/ASB und Kapnometrie · Indikation und Kontraindikationen prüfen" /></div><BronchoPreparation /></>)}

    {children}
    <p className="lesson-source">Hauptgrundlagen: „6. Pneumonie.docx“ und „6. Pneumonie.pdf“. Anatomie: hinterlegtes Anatomie-Skriptum. Medikamente und Mengen ausschließlich nach Thüringer VFA 21, VFA 06 und Anlage B2A 2026/2027. Ergänzend: <a href="https://www.rescuelearn.de/wissen/aspirationspneumonie/" target="_blank" rel="noreferrer">RescueLearn · Aspirationspneumonie</a>. Maßgeblich im Einsatz ist die aktuelle Original-VFA.</p>
  </article>;
}
