import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Answer = [string, boolean];
function q(n: number, prompt: string, answers: Answer[], source: string): ThoraxtraumaChoiceQuestion {
  const offset = n % answers.length;
  return { id: `pneumonie-q-${String(n).padStart(2, "0")}`, mode: "multiple", prompt, options: [...answers.slice(offset), ...answers.slice(0, offset)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty: 3 };
}

export const pneumonieQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1,"Welche Vorgänge erklären die Hypoxämie bei einer ausgeprägten Pneumonie?",[["Alveoläres Exsudat vermindert die Belüftung betroffener Abschnitte",true],["Interstitielles Ödem vergrößert den Diffusionsweg",true],["Ein Ventilations-Perfusions-Missverhältnis kann entstehen",true],["Die pulmonale Durchblutung kommt regelhaft vollständig zum Stillstand",false],["Eine Pneumonie erhöht immer die alveoläre Austauschfläche",false]],"Exsudat, Ödem und Minderbelüftung verschlechtern Diffusion und Ventilations-Perfusions-Verhältnis."),
  q(2,"Welche Strukturen oder Mechanismen gehören zur natürlichen Abwehr der tiefen Atemwege?",[["Mukoziliäre Clearance",true],["Hustenreflex",true],["Alveoläre Makrophagen",true],["Dauerhafte Öffnung der Epiglottis beim Schlucken",false],["Vollständige Sterilisation der Atemluft in der Trachea",false]],"Flimmerepithel, Schleim, Hustenreflex und Makrophagen begrenzen das Eindringen und die Vermehrung von Erregern."),
  q(3,"Welche Aussagen zur Unterscheidung bakterieller und viraler Pneumonien sind fachlich tragfähig?",[["Ein plötzlicher Beginn mit hohem Fieber kann eher zu einem bakteriellen Muster passen",true],["Trockener Husten und Myalgien können eher ein virales Muster stützen",true],["Klinische Muster erlauben präklinisch keinen sicheren Erregernachweis",true],["Gelber Auswurf beweist eine bakterielle Ursache",false],["Eine virale Pneumonie betrifft niemals Alveolen",false]],"Typische und atypische Muster helfen bei der Einordnung, sind aber weder beweisend noch strikt an einen Erregertyp gebunden."),
  q(4,"Eine ältere Patientin ist neu verwirrt, tachypnoisch und kreislauflabil, hat aber nur 37,4 °C. Welche Bewertungen sind richtig?",[["Eine schwere Pneumonie oder Sepsis bleibt möglich",true],["Fehlendes hohes Fieber schließt bei älteren Menschen einen schweren Infekt nicht aus",true],["Vigilanz, Atemarbeit und Perfusion sind für die Dringlichkeit entscheidend",true],["Eine Pneumonie ist bei Körpertemperatur unter 38 °C ausgeschlossen",false],["Die Verwirrtheit darf allein dem Alter zugeschrieben werden",false]],"Ältere oder immunsupprimierte Menschen können ohne ausgeprägtes Fieber schwer erkranken; Organdysfunktion und Verlauf bestimmen die Dringlichkeit."),
  q(5,"Welche Befunde können die Arbeitsdiagnose Pneumonie stützen, ohne sie einzeln zu beweisen?",[["Husten mit oder ohne Auswurf",true],["Fokale feuchte Rasselgeräusche",true],["Atemabhängiger Thoraxschmerz",true],["Einseitige Beinschwellung als pneumoniespezifischer Befund",false],["Jede Form von Giemen als sicherer Pneumonienachweis",false]],"Die Diagnose entsteht aus Anamnese, Infektzeichen, Atembefund und Verlauf; kein Einzelbefund ist beweisend."),
  q(6,"Welche Konstellationen sprechen für einen komplizierten oder vital bedrohlichen Verlauf?",[["Zunehmende Sprechdyspnoe und Erschöpfung",true],["Hypotonie mit verlängerter Rekapillarisierungszeit",true],["Neue Vigilanzminderung",true],["Stabiler Allgemeinzustand bei leichtem Husten ohne Dyspnoe",false],["Ein unveränderter Einzelwert ohne klinische Verschlechterung beweist ein ARDS",false]],"Respiratorische Erschöpfung, Perfusionsstörung und Bewusstseinsänderung sind Red Flags für Atemversagen oder Sepsis."),
  q(7,"Welche Folgekomplikationen einer Pneumonie sind prüfungsrelevant?",[["Pleuraerguss oder Empyem",true],["Lungenabszess",true],["ARDS und Sepsis",true],["Obligate Lungenarterienembolie",false],["Sichere spontane Ausheilung bei jeder immunsupprimierten Person",false]],"Die Entzündung kann sich lokal ausbreiten oder eine systemische Organdysfunktion verursachen."),
  q(8,"Welche Aussagen zur Aspirationspneumonie beziehungsweise chemischen Pneumonitis treffen zu?",[["Dysphagie und Bewusstseinsstörung erhöhen das Aspirationsrisiko",true],["Saurer Mageninhalt kann zunächst eine chemische Lungenschädigung auslösen",true],["Eine bakterielle Pneumonie kann sich zeitlich nach der Aspiration entwickeln",true],["Ein normaler erster SpO₂-Wert schließt eine spätere Verschlechterung sicher aus",false],["Nach akuter Dysphagie soll zur Funktionsprüfung routinemäßig Wasser gegeben werden",false]],"Aspiration kann Atemwegsverlegung, chemische Pneumonitis, ARDS und später eine Infektion verursachen; bei akuter Dysphagie nichts oral geben."),
  q(9,"Welche Anamnesepunkte verändern bei Verdacht auf Pneumonie die Risikoeinschätzung?",[["Immunsuppression oder relevante Begleiterkrankungen",true],["Kürzlicher Krankenhausaufenthalt oder Antibiotikatherapie",true],["Erbrechen, Dysphagie oder beobachtete Aspiration",true],["Allein die Lieblingsspeise des Patienten",false],["Die Haarfarbe als Hinweis auf resistente Erreger",false]],"Vorerkrankungen, Versorgungskontext, Vorbehandlung und Aspirationsrisiko beeinflussen Schweregrad und Erregerspektrum."),
  q(10,"Ein Patient mit Fieber und Dyspnoe hat einseitig aufgehobenes Atemgeräusch und plötzlich einsetzenden Schmerz. Welche Entscheidungen sind korrekt?",[["Pneumothorax aktiv als Differenzialdiagnose prüfen",true],["Den plötzlichen Beginn stärker gewichten als die bloße Anwesenheit von Fieber",true],["cABCDE und Kreislaufdynamik erneut beurteilen",true],["Die Pneumonie allein wegen Fieber als gesichert ansehen",false],["Auf eine Seitenuntersuchung der Lunge verzichten",false]],"Plötzlicher Beginn und einseitig fehlendes Atemgeräusch sind Warnhinweise für eine alternative oder zusätzliche Ursache."),
  q(11,"Welche präklinischen Erstmaßnahmen sind bei einer hypoxämischen Pneumonie sinnvoll?",[["Atemerleichternde Position",true],["Bedarfsgerechte Sauerstoffgabe mit Reevaluation",true],["Frühe Beatmungs- und Absaugbereitschaft bei Erschöpfung",true],["Routinemäßige Flachlagerung trotz ausgeprägter Atemnot",false],["Verzicht auf Verlaufskontrollen nach einmal normalem Blutdruck",false]],"Positionierung, Oxygenierung, Monitoring und rechtzeitige Eskalationsbereitschaft richten sich nach dem klinischen Verlauf."),
  q(12,"Welche Aussagen zur VFA Bronchoobstruktion bei Pneumonie sind richtig?",[["Sie wird nur bei einem tatsächlich vorhandenen obstruktiven Befund geprüft",true],["Giemen und verlängerte Exspiration können einen zusätzlichen obstruktiven Anteil anzeigen",true],["Bronchodilatatoren behandeln die Obstruktion, nicht den alveolären Infekt",true],["Jede Pneumonie erhält automatisch Salbutamol und Ipratropium",false],["Feuchte Rasselgeräusche allein sind gleichbedeutend mit Bronchospasmus",false]],"VFA 21 ist an die Bronchoobstruktion gebunden; eine Pneumonie allein ist keine automatische Indikation."),
  q(13,"Bei zusätzlicher Bronchoobstruktion wird die Erwachsenen-VFA angewandt. Welche Angaben zur ersten Verneblung stimmen?",[["3 mg Salbutamolsulfat",true],["0,5 mg Ipratropiumbromid",true],["Gemeinsame Verneblung über O₂-Verneblermaske mit 6 l/min",true],["100 mg Prednisolon werden in den Vernebler gegeben",false],["Die Menge wird unabhängig von der tatsächlichen Phiolenstärke in Millilitern geschätzt",false]],"VFA 21 nennt 3 mg Salbutamol plus 0,5 mg Ipratropium über die O₂-Verneblermaske mit 6 l/min."),
  q(14,"Welche Aussagen zum Kortikosteroid im VFA-21-Pfad sind korrekt?",[["Einmalig 100 mg Prednisolonäquivalent i.v.",true],["Es dämpft die Entzündungsreaktion, wirkt aber nicht so unmittelbar wie die inhalative Bronchodilatation",true],["Es ist an den obstruktiven Behandlungspfad gebunden und keine Antibiotikatherapie",true],["Es löst alveoläres Exsudat innerhalb weniger Sekunden auf",false],["Es wird grundsätzlich jeder Pneumonie ohne Obstruktion gegeben",false]],"Das Kortikosteroid ergänzt die Therapie der Bronchoobstruktion; es behandelt weder den Erreger noch ersetzt es die Bronchodilatation."),
  q(15,"250 mg Prednisolon-Trockensubstanz werden mit 5 ml Lösungsmittel rekonstituiert. Welche Aussagen stimmen?",[["Die Konzentration beträgt 50 mg/ml",true],["Für 100 mg werden 2 ml entnommen",true],["Die gesamte rekonstituierte Lösung enthält 250 mg",true],["1 ml enthält 100 mg",false],["Die 100-mg-Dosis entspricht der gesamten 5-ml-Spritze",false]],"250 mg geteilt durch 5 ml ergeben 50 mg/ml; 100 mg entsprechen 2 ml."),
  q(16,"Welche Wirkmechanismen und Nebenwirkungen passen zu den Medikamenten der Bronchoobstruktions-VFA?",[["Salbutamol stimuliert β₂-Rezeptoren und kann Tremor oder Tachykardie auslösen",true],["Ipratropium blockiert muskarinische Rezeptoren und kann Mundtrockenheit verursachen",true],["Prednisolon wirkt entzündungshemmend und kann den Blutzucker erhöhen",true],["Ipratropium ist ein Antibiotikum gegen Pneumokokken",false],["Salbutamol hemmt primär die bakterielle Zellwandsynthese",false]],"Die Medikamente wirken bronchodilatierend beziehungsweise antiinflammatorisch; sie sind keine antiinfektive Therapie."),
  q(17,"Welche Voraussetzungen sprechen für einen Versuch mit CPAP/ASB bei schwerer respiratorischer Beeinträchtigung?",[["Wacher, ausreichend kooperativer Patient",true],["Fortbestehende relevante Atemarbeit trotz Basismaßnahmen",true],["Engmaschiges Monitoring und Möglichkeit zur sofortigen Eskalation",true],["Aktives Erbrechen",false],["Fehlende Schutzreflexe",false]],"Nicht invasive Unterstützung setzt eine geeignete Indikation, Kooperation, Schutzreflexe und sichere Überwachung voraus."),
  q(18,"Welche Mechanismen können den Nutzen von CPAP bei geeigneter Pneumonie erklären?",[["Rekrutierbare Alveolen können offengehalten werden",true],["Die funktionelle Residualkapazität kann zunehmen",true],["Die Atemarbeit kann sinken",true],["CPAP entfernt den Erreger aus dem Lungengewebe",false],["CPAP ersetzt bei Erschöpfung immer eine invasive Atemwegssicherung",false]],"Positiver Atemwegsdruck kann Oxygenierung und Atemmechanik verbessern, beseitigt aber weder Ursache noch jede Eskalationsnotwendigkeit."),
  q(19,"Welche Befunde sprechen gegen eine Fortsetzung der nicht invasiven Atemunterstützung?",[["Zunehmende Vigilanzminderung",true],["Erbrechen oder Verlust der Schutzreflexe",true],["Fortschreitende Erschöpfung ohne klinische Besserung",true],["Gute Maskentoleranz bei sinkender Atemarbeit",false],["Verbesserte Oxygenierung bei stabilem Kreislauf",false]],"Verschlechterung, fehlender Atemwegsschutz oder Therapieversagen verlangen eine sofortige Neubewertung und Eskalation."),
  q(20,"Welche Punkte gehören in eine hochwertige Übergabe bei schwerer Pneumonie?",[["Beginn, Dynamik und Aspirationshinweise",true],["Verlauf von Atemarbeit, SpO₂, Kreislauf und Vigilanz",true],["Zeit, Dosis und Wirkung aller Maßnahmen sowie VFA-Indikation",true],["Nur die Arbeitsdiagnose ohne Befundbegründung",false],["Eine vermutete Erregerart als gesicherter Laborbefund",false]],"Eine strukturierte Übergabe verbindet Ausgangsbefund, Verlauf, Risikofaktoren, Therapie und Reaktion darauf."),
  q(21,"Welche Aussagen helfen, Pneumonie und kardiales Lungenödem präklinisch zu differenzieren?",[["Infektzeichen und ein fokaler Befund stützen eher eine Pneumonie",true],["Orthopnoe, kardiale Vorgeschichte und diffuses grobblasiges Brodeln stützen eher ein Lungenödem",true],["Beide Krankheitsbilder können Hypoxämie und Rasselgeräusche verursachen",true],["Rosiger Auswurf beweist in jedem Fall eine Pneumonie",false],["Fieber schließt ein gleichzeitiges kardiales Problem aus",false]],"Die Differenzierung beruht auf Anamnese, Muster, Begleiterkrankungen und Verlauf; Mischbilder sind möglich."),
  q(22,"Ein COPD-Patient mit Pneumonie zeigt Giemen, Fieber, hohe Atemarbeit und fallende Vigilanz. Welche Prioritäten sind schlüssig?",[["Pneumonie und Bronchoobstruktion parallel als Arbeitsprobleme behandeln",true],["VFA 21 bei erfüllter obstruktiver Indikation anwenden und Wirkung kontrollieren",true],["Wegen der Vigilanzverschlechterung Atemwegsschutz und invasive Eskalation vorbereiten",true],["CPAP trotz fehlender Schutzreflexe unverändert fortsetzen",false],["Die fallende Vigilanz ausschließlich als Müdigkeit deuten",false]],"Bei mehreren Problemen werden Ursache, Obstruktion und drohendes Atemversagen parallel bearbeitet; fehlender Atemwegsschutz begrenzt NIV."),
];

export const pneumonieFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "pneumonie-card-01", area: "Definition", question: "Definieren Sie die Pneumonie und grenzen Sie primäre und sekundäre Formen ab.", answer: "Pneumonie ist eine infektiös bedingte Entzündung des Lungengewebes. Primär entsteht sie ohne schwere begünstigende Grunderkrankung; sekundär wird sie etwa durch Sekretretention, Aspiration, COPD, Herzinsuffizienz, Immobilität oder Immunsuppression begünstigt." },
  { id: "pneumonie-card-02", area: "Anatomie", question: "Beschreiben Sie den Weg der Atemluft bis zum Gasaustausch.", answer: "Nase und Rachen führen über Larynx und Trachea zu Haupt-, Lappen- und Segmentbronchien, weiter zu Bronchiolen und Alveolen. Dort liegen Luft und Kapillarblut an der dünnen alveolokapillären Membran eng beieinander." },
  { id: "pneumonie-card-03", area: "Abwehr", question: "Welche Schutzmechanismen verhindern normalerweise eine Infektion der tiefen Atemwege?", answer: "Filterung und Befeuchtung in der Nase, Epiglottis und Schluckkoordination, Hustenreflex, Schleim mit Flimmerepithel als mukoziliäre Clearance sowie alveoläre Makrophagen." },
  { id: "pneumonie-card-04", area: "Pathophysiologie", question: "Leiten Sie die Hypoxämie bei Pneumonie von der Entzündungsreaktion her.", answer: "Entzündungsmediatoren erhöhen die Kapillarpermeabilität. Exsudat füllt Alveolen und Ödem verbreitert das Interstitium. Minderbelüftete, weiterhin perfundierte Areale erzeugen ein Ventilations-Perfusions-Missverhältnis bis zum Shunt; zugleich steigt die Diffusionsstrecke und Atemarbeit." },
  { id: "pneumonie-card-05", area: "Erreger", question: "Wie unterscheiden sich typische bakterielle und virale Muster – und wo liegt die Prüfungsfalle?", answer: "Bakteriell eher plötzlich, hohes Fieber, produktiver Husten und fokale Befunde; viral eher schleichend, trocken, Myalgien und diffus. Das sind nur Muster: Auswurf, Auskultation oder Verlauf beweisen präklinisch keinen Erreger." },
  { id: "pneumonie-card-06", area: "Symptome", question: "Welche Befunde stützen die Arbeitsdiagnose Pneumonie?", answer: "Fieber oder Schüttelfrost, Husten trocken oder produktiv, Dyspnoe, Tachypnoe, Hypoxämie, pleuritischer Schmerz, Abgeschlagenheit sowie fokale oder diffuse Rasselgeräusche, abgeschwächtes Atemgeräusch oder Dämpfung." },
  { id: "pneumonie-card-07", area: "Red Flags", question: "Welche Zeichen machen eine Pneumonie präklinisch zeitkritisch?", answer: "Sprechdyspnoe, Zyanose, schwere oder erschöpfende Atemarbeit, zunehmende Hypoxämie, fallende Atemfrequenz bei Erschöpfung, Vigilanzminderung, Hypotonie, schlechte Rekapillarisierung und rasche Verschlechterung." },
  { id: "pneumonie-card-08", area: "Aspiration", question: "Erklären Sie Aspirationspneumonie und chemische Pneumonitis.", answer: "Sekret, Nahrung oder Mageninhalt gelangen in die Lunge. Saurer Mageninhalt verursacht zunächst eine sterile chemische Schädigung bis zum ARDS; eine bakterielle Pneumonie kann folgen. Risiken sind unter anderem Dysphagie, Bewusstseinsstörung, Alkohol, Schlaganfall und SHT." },
  { id: "pneumonie-card-09", area: "Komplikationen", question: "Welche lokalen und systemischen Komplikationen müssen Sie nennen?", answer: "Lokal Pleuritis, Pleuraerguss, Empyem und Lungenabszess; systemisch respiratorische Insuffizienz, ARDS, Sepsis und septischer Schock sowie mögliche Dekompensation von COPD oder Herzinsuffizienz." },
  { id: "pneumonie-card-10", area: "Differenzialdiagnosen", question: "Welche gefährlichen Differenzialdiagnosen prüfen Sie und wodurch werden Sie aufmerksam?", answer: "Lungenödem, LAE, Pneumothorax, ACS, Asthma/COPD, Atelektase und Fremdkörper/Aspiration. Plötzlicher Beginn, einseitig fehlendes Atemgeräusch, Beinzeichen, kardiales Muster, Stridor oder Ischämiehinweise verlangen eine Neubewertung." },
  { id: "pneumonie-card-11", area: "Erstmaßnahmen", question: "Strukturieren Sie die ersten präklinischen Maßnahmen.", answer: "cABCDE, atemerleichternde Position, bedarfsgerechter Sauerstoff, Monitoring, Temperatur, Blutzucker, Auskultation, gegebenenfalls Kapnometrie, Absaug- und Beatmungsbereitschaft, i.v.-Zugang nach Lage, frühe Notarztnachforderung und geeignete Zielklinik mit Reevaluation." },
  { id: "pneumonie-card-12", area: "VFA 21", question: "Wann ist die Bronchoobstruktions-VFA bei Pneumonie relevant und wie lautet die erste Verneblung?", answer: "Nur bei tatsächlichem obstruktivem Anteil, etwa Giemen und verlängertem Exspirium. Erwachsene: 3 mg Salbutamolsulfat plus 0,5 mg Ipratropiumbromid gemeinsam über O₂-Verneblermaske mit 6 l/min; Wirkung und klinischer Verlauf kontrollieren." },
  { id: "pneumonie-card-13", area: "Medikamente", question: "Erklären Sie Wirkung und wichtige Nebenwirkungen von Salbutamol, Ipratropium und Prednisolon.", answer: "Salbutamol stimuliert β₂-Rezeptoren und bronchodilatiert; möglich sind Tremor, Tachykardie und Hypokaliämie. Ipratropium blockiert muskarinische Rezeptoren; möglich sind Mundtrockenheit und Tachykardie. Prednisolon wirkt antiinflammatorisch, jedoch verzögert; möglich ist unter anderem Hyperglykämie." },
  { id: "pneumonie-card-14", area: "Zubereitung", question: "Wie bereiten Sie 100 mg Prednisolonäquivalent aus 250 mg Trockensubstanz nach B2A vor?", answer: "Mit 5 ml beiliegendem Lösungsmittel rekonstituieren. Konzentration 50 mg/ml; 100 mg entsprechen 2 ml. Präparat, Konzentration, Indikation und Original-VFA vor Anwendung prüfen." },
  { id: "pneumonie-card-15", area: "CPAP", question: "Begründen Sie CPAP bei geeigneter Pneumonie und nennen Sie Grenzen.", answer: "Positiver Druck kann Alveolen rekrutieren, die funktionelle Residualkapazität erhöhen und Atemarbeit senken. Erforderlich sind Kooperation, Schutzreflexe und Überwachung. Erbrechen, Bewusstlosigkeit, fehlende Schutzreflexe, fehlende Compliance oder Therapieversagen verlangen Verzicht beziehungsweise Eskalation." },
  { id: "pneumonie-card-16", area: "Übergabe", question: "Welche Informationen gehören in die Übergabe eines kritisch kranken Pneumoniepatienten?", answer: "Beginn und Dynamik, Risikofaktoren und Aspiration, Ausgangs- und Verlaufswerte, Atemarbeit, Auskultation, Oxygenierung, Kreislauf und Vigilanz, alle Maßnahmen mit Zeit/Dosis/Wirkung, NIV-Verlauf sowie Verdacht auf Sepsis oder Atemversagen." },
];
