import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct?: boolean];

function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  return { id: `polytrauma-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: options.map(([text, correct]) => ({ text, correct })), source, difficulty };
}

export const polytraumaFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "polytrauma-card-01", area: "Definition", question: "Definieren Sie ein Polytrauma präzise.", answer: "Mehrfachverletzung nach einem Unfallereignis, bei der bereits eine einzelne Verletzung oder die Kombination mehrerer Verletzungen lebensbedrohlich ist." },
  { id: "polytrauma-card-02", area: "Anatomie", question: "Welche großen Körperregionen müssen beim Polytrauma systematisch betrachtet werden?", answer: "Schädel und Gehirn, Thorax, Abdomen, Becken, Wirbelsäule und Extremitäten. Die Untersuchung folgt cABCDE und sucht parallel nach großen Blutungsräumen und unmittelbar lebensbedrohlichen Funktionsstörungen." },
  { id: "polytrauma-card-03", area: "Pathophysiologie", question: "Erklären Sie die letale Trias und ihre gegenseitige Verstärkung.", answer: "Blutverlust verursacht Minderperfusion und anaeroben Stoffwechsel mit Azidose. Exposition, kalte Umgebung und Infusionen begünstigen Hypothermie. Azidose und Hypothermie hemmen die Gerinnung; die Koagulopathie verstärkt die Blutung und damit Schock, Auskühlung und Azidose." },
  { id: "polytrauma-card-04", area: "Schock", question: "Warum kann ein normaler Einzelblutdruck eine relevante Blutung nicht sicher ausschließen?", answer: "Sympathische Kompensation kann den Blutdruck zunächst erhalten. Entscheidend sind Mechanismus, Bewusstsein, Haut, Rekapillarisierung, Pulsqualität, Herzfrequenz, Blutdrucktrend und Befunde großer Blutungsräume." },
  { id: "polytrauma-card-05", area: "Red Flags", question: "Welche Verletzungsmuster können auf ein relevantes Hochrasanztrauma hinweisen?", answer: "Unter anderem Clavicula-, Sternum- oder Rippenserienfraktur, Beckenringverletzung, Wirbelsäulenverletzung, penetrierende Rumpf-/Halsverletzung und posttraumatische Makrohämaturie. Sie verlangen eine konsequente Suche nach Begleitverletzungen." },
  { id: "polytrauma-card-06", area: "cABCDE", question: "Wie priorisieren Sie die ersten Minuten bei Polytrauma?", answer: "Zuerst kritische äußere Blutung stoppen, dann Atemweg mit HWS-Bezug, Atmung, Kreislauf und große Blutungsräume, Neurologie und vollständige Exploration mit Wärmeerhalt. Lebensbedrohliche Probleme werden sofort behandelt und anschließend re-evaluiert." },
  { id: "polytrauma-card-07", area: "Beckenschlinge", question: "Wann ist die Beckenschlinge nach Thüringer VFA 32 angezeigt und was ist danach zu prüfen?", answer: "Bei Anhaltspunkten für Beckenfraktur nach KISS und hämodynamischer Instabilität. Neurologie und Gefäßstatus vor und nach der Anlage sowie im Verlauf prüfen, sichere und feste Anlage kontrollieren und die Schlinge präklinisch nicht öffnen." },
  { id: "polytrauma-card-08", area: "Entlastung", question: "Welche klinische Kombination fordert VFA 07 für eine Thoraxentlastung?", answer: "Thoraxtrauma mit mindestens einseitig abgeschwächtem Atemgeräusch UND hämodynamischer Instabilität. Nach der Punktion müssen respiratorische und hämodynamische Wirkung getrennt beurteilt werden." },
  { id: "polytrauma-card-09", area: "Volumentherapie", question: "Nennen Sie die Blutdruckziele des Leitalgorithmus Trauma.", answer: "Nicht beherrschbare Blutung: systolisch etwa 80 mmHg. Führendes oder isoliertes SHT: mindestens 90 mmHg. Schwangere ab dem fünften Monat: 120 mmHg. Kinder: etwa 70 + 2 × Alter in Jahren." },
  { id: "polytrauma-card-10", area: "Tranexamsäure", question: "Erklären Sie Indikation, Wirkung und Zubereitung der Tranexamsäure im Traumaalgorithmus.", answer: "Bei Erwachsenen mit lebensbedrohlicher Blutung und/oder hämorrhagischem Schock. Tranexamsäure hemmt die Aktivierung von Plasminogen zu Plasmin und bremst dadurch die Fibrinolyse. Nach VFA: 1 g = 10 ml plus 90 ml NaCl 0,9 %, als Kurzinfusion über 10 Minuten." },
  { id: "polytrauma-card-11", area: "Analgesie", question: "Wie unterscheiden sich Esketamin- und Morphinpfad nach den Thüringer VFA?", answer: "VFA 36: Erwachsene erhalten nach 1 mg Midazolam i.v. Esketamin langsam 0,2 mg/kgKG i.v.; Kontrolle nach 5 Minuten, bei Bedarf 0,1 mg/kgKG, erneute Kontrolle und gegebenenfalls gleiche Repetition. VFA 38: Morphin langsam nach Gewichtstabelle, nach 5 Minuten bei Bedarf halbe Initialdosis, insgesamt maximal 10 mg. Beide Pfade verlangen Monitoring und Beatmungsbereitschaft." },
  { id: "polytrauma-card-12", area: "Einsatzstrategie", question: "Was bedeutet Load-go-and-treat beim Polytrauma?", answer: "Lebensrettende Sofortmaßnahmen werden parallel zur Transportvorbereitung durchgeführt. Nicht notwendige Maßnahmen am Einsatzort dürfen die definitive Versorgung im geeigneten Traumazentrum nicht verzögern; Ziel der VFA ist eine Prähospitalzeit unter 60 Minuten inklusive Anfahrt und Transport." },
  { id: "polytrauma-card-13", area: "Anamnese", question: "Welche Angaben sind im SAMPLERS bei Polytrauma besonders entscheidend?", answer: "Symptome und Verlauf, Allergien, Medikamente insbesondere Antikoagulanzien, relevante Vorerkrankungen, letzte Nahrungsaufnahme, Ereignis/Mechanismus/Zeitpunkt, Risikofaktoren und Schwangerschaft. Fremdanamnese und Einsatzstellenbefunde können entscheidend sein." },
  { id: "polytrauma-card-14", area: "Komplikationen", question: "Welche Organfolgen kann ein prolongierter Schock auslösen?", answer: "Schocklunge bis ARDS, Schockniere mit akutem Nierenversagen, gestörte Darmperfusion mit Schädigung der Mukosabarriere sowie zunehmende Azidose und Koagulopathie. Diese Folgen verstärken die kritische Situation." },
  { id: "polytrauma-card-15", area: "Übergabe", question: "Welche Kerndaten gehören in Voranmeldung und Übergabe?", answer: "Unfallmechanismus und Zeitpunkt, vermutete Körperregionen, cABCDE-Probleme und Verlauf, Vitaltrend, Bewusstsein/GCS, Blutungsquellen, Maßnahmen mit Zeit und Wirkung, Zugänge/Volumen/Tranexamsäure/Analgesie, Immobilisation sowie Transport- und Zielklinikentscheidung." },
  { id: "polytrauma-card-16", area: "Schockformen", question: "Welche Schockformen müssen beim instabilen Traumapatienten unterschieden werden?", answer: "Primär hämorrhagisch/hypovoläm durch Blutverlust; obstruktiv durch Spannungspneumothorax oder Tamponade; neurogen bei hoher Rückenmarkschädigung; kardiogen durch Myokardkontusion oder ein medizinisches Ereignis. Blutung muss auch bei vermuteter anderer Ursache konsequent ausgeschlossen werden." },
  { id: "polytrauma-card-17", area: "Traumauntersuchung", question: "Wie läuft eine schnelle Traumauntersuchung nach den ersten cABCDE-Maßnahmen ab?", answer: "Standardisierter Bodycheck von Kopf/Gesicht über Hals/Thorax, Abdomen/Flanken, Becken/Perineum und Extremitäten bis zum situationsgerechten Rückencheck. Ansehen, vorsichtig tasten, vergleichen, pDMS prüfen, Instabilität nicht provozieren und danach cABCDE erneut beginnen." },
  { id: "polytrauma-card-18", area: "Thorax", question: "Wodurch unterscheidet sich ein Spannungspneumothorax vom einfachen Pneumothorax?", answer: "Beim Spannungspneumothorax verursacht der steigende intrathorakale Druck zusätzlich eine Behinderung des venösen Rückstroms mit hämodynamischer Instabilität. Halsvenenstauung und Trachealverlagerung können fehlen; entscheidend sind passender Thoraxbefund plus respiratorische und/oder zirkulatorische Bedrohung." },
  { id: "polytrauma-card-19", area: "Entlastung", question: "Nennen Sie die beiden Punktionsorte und die wichtigsten technischen Regeln der VFA 07.", answer: "2. ICR medioklavikular oder 4./5. ICR vordere Axillarlinie; mindestens 6,5 cm lange Kanüle, 90 Grad zur Thoraxwand und über dem Rippenoberrand. Nach Luftentweichen Stahlmandrin entfernen, Kanüle fixieren und respiratorisch sowie hämodynamisch re-evaluieren." },
];

export const polytraumaQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen grenzen ein Polytrauma fachlich korrekt ab?", [["Eine einzelne Verletzung innerhalb einer Mehrfachverletzung kann bereits lebensbedrohlich sein", true], ["Auch die Kombination mehrerer Verletzungen kann die Lebensbedrohung begründen", true], ["Ein Polytrauma setzt zwingend Verletzungen in mindestens drei Körperregionen voraus"], ["Die Definition richtet sich nicht allein nach der äußerlich sichtbaren Verletzungszahl", true], ["Ein Hochrasanzmechanismus ohne Verletzungsnachweis ist definitionsgemäß immer ein Polytrauma"]], "Entscheidend ist die lebensbedrohliche Mehrfachverletzung, nicht eine starre Mindestzahl betroffener Regionen.", 2),
  q(2, "Ein eingeklemmter Patient wirkt zunächst kreislaufstabil. Welche Bewertungen sind richtig?", [["Der Unfallmechanismus kann relevante innere Verletzungen trotz stabilen Einzelwerts wahrscheinlich machen", true], ["Vitalparameter müssen als Verlauf und nicht nur einmalig beurteilt werden", true], ["Ein normaler systolischer Blutdruck schließt eine kompensierte Blutung sicher aus"], ["Kritische Blutungen und große Blutungsräume werden parallel gesucht", true], ["Die vollständige Untersuchung darf bis zum Eintreffen in der Klinik entfallen"]], "Kompensation kann kritische Blutungen zunächst verdecken; Mechanismus, klinischer Befund und Trend gehören zusammen.", 3),
  q(3, "Welche Ketten gehören zur letalen Trias des Polytraumas?", [["Minderperfusion fördert anaeroben Stoffwechsel und Azidose", true], ["Hypothermie verschlechtert die Gerinnungsfunktion", true], ["Koagulopathie kann Blutverlust und Schock vertiefen", true], ["Azidose steigert zuverlässig die Wirkung der Gerinnungsenzyme"], ["Wärmeerhalt ist nur eine Komfortmaßnahme ohne Einfluss auf die Blutung"]], "Hypothermie, Azidose und Koagulopathie verstärken sich gegenseitig und erhöhen das Blutungs- und Schockrisiko.", 3),
  q(4, "Welche Maßnahmen unterbrechen die schädliche Spirale aus Blutung, Auskühlung und Gerinnungsstörung?", [["Kritische äußere Blutungen konsequent kontrollieren", true], ["Patienten und Rettungsraum frühzeitig warm halten", true], ["Infusionstherapie am klinischen Volumenmangel und Zielblutdruck ausrichten", true], ["Unkontrollierbare Blutung mit großen kalten Flüssigkeitsmengen normotensiv behandeln"], ["Definitive Blutungskontrolle durch unnötige Maßnahmen am Einsatzort verzögern"]], "Blutungskontrolle, Wärmeerhalt, zielgerichtete Kreislauftherapie und schneller Transport wirken der Trias entgegen.", 3),
  q(5, "Welche Befunde können auf ein relevantes Hochrasanztrauma hinweisen?", [["Sternumfraktur", true], ["Beckenringverletzung", true], ["Posttraumatische Makrohämaturie", true], ["Claviculafraktur", true], ["Isolierter kleiner Hautkratzer ohne passenden Mechanismus"]], "Bestimmte Verletzungsmuster sind Marker einer erheblichen Krafteinwirkung und verlangen die Suche nach Begleitverletzungen.", 2),
  q(6, "Welche Reihenfolge entspricht der Versorgung nach cABCDE?", [["Zuerst unmittelbar lebensbedrohliche äußere Blutung kontrollieren", true], ["Atemweg und möglicher HWS-Bezug werden anschließend beurteilt", true], ["Atmung und Kreislauf werden vor der detaillierten Extremitätenuntersuchung priorisiert", true], ["Die vollständige Exploration erfolgt mit konsequentem Wärmeerhalt", true], ["Schmerzerfassung ersetzt die neurologische Untersuchung"]], "cABCDE priorisiert reversible Todesursachen; Detaildiagnostik folgt, ohne Wärmeerhalt und Re-Evaluation zu vernachlässigen.", 3),
  q(7, "Welche Aufgaben gehören bei C zur Polytraumaversorgung?", [["Rekapillarisierung, Pulse und Vitaltrend beurteilen", true], ["Große Blutungsräume einschließlich Thorax, Abdomen, Becken und Oberschenkel mitdenken", true], ["i.v.-Zugang, bei Versagen i.o.-Zugang, situationsgerecht vorbereiten", true], ["Eine innere Blutung erst bei manifester Hypotonie berücksichtigen"], ["Ein Dreiwegehahn verbessert grundsätzlich die maximal mögliche Durchflussrate"]], "Der Traumaalgorithmus verbindet Kreislaufbeurteilung, Blutungssuche, Monitoring und geeigneten Gefäßzugang.", 3),
  q(8, "Welche Aussagen zur Beckenschlinge entsprechen VFA 32?", [["Anhaltspunkte für Beckenfraktur und hämodynamische Instabilität bilden die Indikationskonstellation", true], ["Neurologie und Gefäßstatus werden vor und nach Anlage sowie im Verlauf geprüft", true], ["Die sichere und feste Anlage muss kontrolliert werden", true], ["Die Schlinge wird zur wiederholten Beckenprüfung präklinisch geöffnet"], ["Allein ein Hochrasanzmechanismus ohne weitere Anhaltspunkte und ohne Instabilität erfüllt die vollständige Indikation"]], "VFA 32 fordert KISS-Anhaltspunkte plus Instabilität, neurovaskuläre Kontrollen, sichere Anlage und keine präklinische Öffnung.", 3),
  q(9, "Welche Aussagen vermeiden typische Fehler bei vermuteter Beckenverletzung?", [["Wiederholte provozierende Stabilitätsprüfungen sind zu vermeiden", true], ["Die Schlinge ersetzt weder cABCDE noch die Suche nach weiteren Blutungsquellen", true], ["Nach Anlage bleiben Kreislauf und pDMS im Verlauf kontrollpflichtig", true], ["Ein unauffälliger äußerer Befund schließt eine innere Beckenblutung aus"], ["Nach Kreislaufbesserung darf die Schlinge präklinisch routinemäßig entfernt werden"]], "Bei möglicher instabiler Beckenverletzung zählen schonende Untersuchung, korrekte Anlage und fortlaufende Gesamtbeurteilung.", 3),
  q(10, "Welche Befundkombination erfüllt die VFA-Indikation zur Entlastungspunktion?", [["Thoraxtrauma", true], ["Mindestens einseitig abgeschwächtes Atemgeräusch", true], ["Hämodynamische Instabilität", true], ["Isolierter Thoraxschmerz bei stabiler Hämodynamik"], ["Radiologische Bestätigung als zwingende präklinische Voraussetzung"]], "VFA 07 verlangt Thoraxtrauma, mindestens einseitig abgeschwächtes Atemgeräusch UND hämodynamische Instabilität.", 3),
  q(11, "Welche Aussagen zur Entlastungspunktion nach VFA 07 sind richtig?", [["Mögliche Orte sind der 2. ICR medioklavikular oder der 4./5. ICR vordere Axillarlinie", true], ["Die Kanüle soll mindestens 6,5 cm lang sein", true], ["Die Punktion erfolgt im 90-Grad-Winkel über den Rippenoberrand", true], ["Nach Luftentweichen wird der Stahlmandrin entfernt und die Kanüle fixiert", true], ["Nur eine respiratorische Besserung beweist die vollständige Stabilisierung"]], "Technik und anschließende respiratorische sowie hämodynamische Re-Evaluation sind Bestandteil der VFA.", 3),
  q(12, "Nach Entlastung bleibt der Patient instabil. Welche Reaktionen sind angemessen?", [["Respiratorische und hämodynamische Wirkung getrennt erneut prüfen", true], ["Eine erneute Spannung oder technische Fehlfunktion mitdenken", true], ["Weitere Differenzialdiagnosen und Blutungsquellen prüfen", true], ["Monitoring und zeitkritischen Transport fortführen", true], ["Das hörbare Entweichen von Luft beendet jede weitere Diagnostik"]], "Eine technische Entlastung ersetzt nicht die klinische Wirkungskontrolle und die Suche nach parallelen Ursachen.", 3),
  q(13, "Welche Zielwerte nennt der Thüringer Leitalgorithmus Trauma?", [["Bei nicht beherrschbarer Blutung RRsys etwa 80 mmHg", true], ["Bei führendem oder isoliertem SHT RRsys mindestens 90 mmHg", true], ["Bei Schwangeren ab dem fünften Monat RRsys 120 mmHg", true], ["Bei Kindern RRsys etwa 70 + 2 × Alter", true], ["Für jedes Polytrauma unabhängig vom Verletzungsmuster RRsys exakt 120 mmHg"]], "Die Zielwerte unterscheiden Blutung, SHT, Schwangerschaft und Kind; eine pauschale Normotonie ist nicht vorgegeben.", 3),
  q(14, "Welche Aussagen zur Flüssigkeitstherapie passen zu L2?", [["Ohne Hinweis auf Volumenmangel wird keine routinemäßige Volumentherapie durchgeführt", true], ["Bei nicht beherrschbarer Blutung erfolgt sie reduziert mit Ziel RRsys etwa 80 mmHg", true], ["Beim führenden SHT hat die zerebrale Perfusion mit mindestens 90 mmHg Vorrang", true], ["Ein Dreiwegehahn kann die Durchflussrate verringern", true], ["Bei jeder Verletzung wird unabhängig vom Kreislauf sofort ein Liter kristalloide Lösung gegeben"]], "L2 fordert eine zielgerichtete, nicht pauschale Volumentherapie und berücksichtigt das führende Verletzungsmuster.", 3),
  q(15, "Welche Aussagen zur Tranexamsäure sind für dieses Kapitel korrekt?", [["Die VFA-Indikation ist eine lebensbedrohliche Blutung und/oder ein hämorrhagischer Schock beim Erwachsenen", true], ["Sie hemmt die Aktivierung von Plasminogen zu Plasmin und bremst damit die Fibrinolyse", true], ["Nach B2A werden 1 g in insgesamt 100 ml als Kurzinfusion über 10 Minuten gegeben", true], ["Sie ersetzt die mechanische und operative Blutungskontrolle"], ["Sie löst bestehende Fibrinnetze gezielt auf"]], "Tranexamsäure stabilisiert die körpereigene Gerinnselbildung; Dosis und Zubereitung stammen aus L2/B2A.", 3),
  q(16, "Welche Risiken oder Kontrollen sind bei Tranexamsäure relevant?", [["Akute arterielle oder venöse Thrombose ist als relevantes Risiko zu beachten", true], ["Schwere Nierenfunktionsstörung ist zu berücksichtigen", true], ["Übelkeit, Hypotonie, Farbsehstörung oder Krampfanfälle sind mögliche Nebenwirkungen", true], ["Die Gabe darf die Transport- und Blutungskontrollstrategie nicht verzögern", true], ["Eine schnelle unkontrollierte Bolusgabe ist der im Thüringer Traumaalgorithmus vorgesehene Weg"]], "Wirkung und Nebenwirkungen ergänzen die VFA; vorgesehen ist die Kurzinfusion über 10 Minuten.", 3),
  q(17, "Welche Aussagen zum Esketaminpfad für Erwachsene entsprechen VFA 36?", [["Indikation kann traumabedingter starker Schmerz sein", true], ["Vor Esketamin nennt der Algorithmus 1 mg Midazolam i.v.", true], ["Initial werden 0,2 mg/kgKG Esketamin langsam i.v. gegeben", true], ["Bei unzureichender Wirkung ist eine halbe Initialdosis vorgesehen", true], ["Monitoring und Beatmungsbereitschaft entfallen wegen erhaltener Schutzreflexe grundsätzlich"]], "VFA 36 verbindet gewichtsbezogene langsame Gabe, Re-Evaluation, mögliche Repetition und vollständige Überwachung.", 3),
  q(18, "Welche Aussagen zum Morphinpfad entsprechen VFA 38?", [["Morphin wird langsam i.v. nach Gewichtstabelle gegeben", true], ["Nach fünf Minuten wird die Wirkung beurteilt", true], ["Bei Bedarf wird die halbe Initialdosis wiederholt", true], ["Die Gesamtdosis ist auf maximal 10 mg begrenzt", true], ["Vorbestehende Übelkeit und Atemfunktion sind für den Pfad ohne Bedeutung"]], "VFA 38 verlangt Gewichtstabelle, langsame Gabe, Re-Evaluation, begrenzte Repetition und Monitoring.", 3),
  q(19, "Welche Aussagen zur Analgesie im Polytrauma sind begründet?", [["Eine Analgesie folgt der Stabilisierung unmittelbar lebensbedrohlicher cABCDE-Probleme", true], ["Schmerz, Atmung, Kreislauf und Vigilanz werden nach jeder Gabe neu beurteilt", true], ["Immobilisation und Behandlung der Verletzungsursache bleiben notwendig", true], ["NRS und Wirkung gehören in die fortlaufende Dokumentation", true], ["Eine sinkende NRS macht den zeitkritischen Transport entbehrlich"]], "Analgesie ist Teil der Gesamtversorgung, ersetzt aber weder Ursachenbehandlung noch Re-Evaluation und Transport.", 3),
  q(20, "Welche Aussagen kennzeichnen Load-go-and-treat korrekt?", [["Lebensrettende Sofortmaßnahmen laufen parallel zur Transportvorbereitung", true], ["Eine geeignete Zielklinik wird früh ausgewählt und vorangemeldet", true], ["Nicht zwingende Maßnahmen am Einsatzort werden zugunsten der definitiven Versorgung begrenzt", true], ["Die VFA nennt als Ziel eine Prähospitalzeit unter 60 Minuten inklusive Anfahrt und Transport", true], ["Jede Diagnostik muss vor Abfahrt vollständig abgeschlossen sein"]], "Zeitkritische Patienten werden nach Behandlung unmittelbar tödlicher Probleme zügig in ein geeignetes Traumazentrum transportiert.", 3),
  q(21, "Welche Inhalte gehören zu einer fokussierten SAMPLERS-Anamnese beim Polytrauma?", [["Antikoagulanzien und weitere Medikamente", true], ["Mechanismus, Zeitpunkt und Energie des Ereignisses", true], ["Vorerkrankungen, Allergien und Schwangerschaft", true], ["Symptome, Schmerzverlauf und letzte Nahrungsaufnahme", true], ["Die Fremdanamnese ist bei Bewusstseinsstörung grundsätzlich wertlos"]], "SAMPLERS ergänzt den Befund; bei eingeschränkter Auskunft sind Zeugen, Angehörige und Einsatzstellenbefunde besonders wichtig.", 2),
  q(22, "Welche Komplikationen lassen sich aus prolongiertem Schock ableiten?", [["ARDS beziehungsweise Schocklunge", true], ["Akute Nierenschädigung durch Minderperfusion", true], ["Schädigung der intestinalen Mukosabarriere", true], ["Fortschreitende Azidose und Gerinnungsstörung", true], ["Zwingend sofortige Polyurie als Zeichen verbesserter Nierenperfusion"]], "Anhaltende Minderperfusion kann Lunge, Niere, Darm und Gerinnung gleichzeitig schädigen.", 3),
  q(23, "Welche Materialgruppen sind bei erwartbarem Polytrauma sinnvoll?", [["Material zur Blutungskontrolle einschließlich Tourniquet und Hämostyptika", true], ["Atemwegs-, Sauerstoff-, Beatmungs- und Absaugmaterial", true], ["Monitoring, Kapnografie, Gefäßzugang und Medikamente nach VFA", true], ["Beckenschlinge, Schienen-/Immobilisations- und Wärmeerhaltmaterial", true], ["Nur ein Verbandpäckchen, da Spezialmaterial erst nach Diagnosesicherung geholt wird"]], "L2 fordert, Material und PSA vor Betreten der Einsatzstelle mitzunehmen; die Ausstattung muss cABCDE-Probleme abdecken.", 2),
  q(24, "Welche Entscheidungsfehler gefährden einen polytraumatisierten Patienten?", [["Sich durch einen einzelnen normalen Vitalwert beruhigen lassen", true], ["Nach einer erfolgreichen Einzelmaßnahme auf Re-Evaluation verzichten", true], ["Die Suche nach Blutung wegen einer möglichen neurogenen Ursache beenden", true], ["Zeitkritischen Transport bis zur vollständigen Schmerzfreiheit verzögern", true], ["Mechanismus, Befunde und Vitaltrend gemeinsam bewerten"]], "Polytrauma erfordert dynamische Gesamtbeurteilung; parallele Verletzungen und wechselnde Kritikalität sind typisch.", 3),
  q(25, "Welche Angaben machen eine Schockraumvoranmeldung fachlich aussagekräftig?", [["Unfallmechanismus, Zeitpunkt und betroffene Körperregionen", true], ["cABCDE-Probleme und Vitaltrend", true], ["Bewusstsein, Pupillen/GCS und relevante neurologische Befunde", true], ["Maßnahmen mit Dosis, Zeitpunkt und beobachteter Wirkung", true], ["Nur die Aussage 'Polytrauma kommt', ohne Befunde und Verlauf"]], "Die Voranmeldung muss Mechanismus, Befunddynamik, Maßnahmen und erwartbaren Ressourcenbedarf strukturiert vermitteln.", 3),
  q(26, "Ein Patient ist nach einem Sturz hypoton und tachykard. Welche Überlegungen zu den Schockformen sind fachlich richtig?", [["Ein hämorrhagischer Schock bleibt bis zum Ausschluss eine führende Annahme", true], ["Ein Spannungspneumothorax kann über verminderten venösen Rückstrom einen obstruktiven Schock verursachen", true], ["Eine relative Bradykardie kann bei hoher Rückenmarkschädigung zu einem neurogenen Schock passen", true], ["Eine warme Haut beweist einen neurogenen Schock und beendet die Blutungssuche"], ["Ein kardiales Ereignis kann Unfallursache statt Unfallfolge sein", true]], "Mehrere Schockmechanismen können gleichzeitig oder alternativ vorliegen; der klinische Kontext entscheidet, Blutung bleibt konsequent zu suchen.", 3),
  q(27, "Welche Bestandteile gehören zur schnellen Traumauntersuchung nach Behandlung der unmittelbaren cABCDE-Probleme?", [["Kopf und Gesicht auf Wunden, Stufen, Blutung und Pupillenbefund untersuchen", true], ["Thoraxbewegung und Atemgeräusche im Seitenvergleich beurteilen", true], ["Abdomen, Flanken, Beckenregion und Perineum berücksichtigen", true], ["Extremitäten einschließlich pDMS untersuchen", true], ["Jede Körperregion so lange untersuchen, bis eine definitive Diagnose feststeht"]], "Die schnelle Traumauntersuchung ist ein standardisierter, zeitsparender Bodycheck und keine vollständige definitive Diagnostik.", 3),
  q(28, "Welche Aussagen unterscheiden Pneumothorax und Spannungspneumothorax korrekt?", [["Ein einfacher Pneumothorax kann bei zunächst stabilem Kreislauf vorliegen", true], ["Beim Spannungspneumothorax beeinträchtigt steigender intrathorakaler Druck den venösen Rückstrom", true], ["Hämodynamische Instabilität macht aus dem passenden Thoraxbefund eine unmittelbar lebensbedrohliche Konstellation", true], ["Fehlende Halsvenenstauung schließt einen Spannungspneumothorax sicher aus"], ["Überdruckbeatmung kann die Progression eines Pneumothorax begünstigen", true]], "Die Spannungskomponente zeigt sich an der zusätzlichen respiratorischen und vor allem zirkulatorischen Bedrohung; klassische Spätzeichen müssen nicht vorhanden sein.", 3),
  q(29, "Welche Kombinationen aus Punktionsort und Technik entsprechen der Thüringer Entlastungs-VFA?", [["2. ICR in der Medioklavikularlinie", true], ["4./5. ICR in der vorderen Axillarlinie", true], ["Punktion unmittelbar über dem Rippenoberrand", true], ["Kanüle mindestens 6,5 cm und Einführung im 90-Grad-Winkel", true], ["Punktion am Rippenunterrand zum Schutz des Interkostalraums"]], "VFA 07 erlaubt den ventralen oder vorderen lateralen Zugang und schützt das neurovaskuläre Bündel durch die Punktion über dem Rippenoberrand.", 3),
  q(30, "Welche Aussagen sind typische Prüfungsfallen beim Polytrauma?", [["Ein normaler Einzelblutdruck kann eine kompensierte Blutung verdecken", true], ["Neurogener Schock ist eine Ausschlussdiagnose gegenüber Blutung und obstruktiven Ursachen", true], ["Nach Atemwegssicherung müssen bei einseitig fehlendem Atemgeräusch auch Tubuslage und Beatmung geprüft werden", true], ["Eine bereits angelegte Beckenschlinge wird zur Verlaufskontrolle routinemäßig geöffnet"], ["Eine erfolgreiche Einzelmaßnahme ersetzt nicht die erneute cABCDE-Beurteilung", true]], "Prüfungsentscheidungen sollen Befund, Verlauf und VFA-Kriterien verbinden; einzelne Zeichen oder Maßnahmen beenden die Gesamtbeurteilung nicht.", 3),
  q(31, "Welche Befunde sprechen beim Thoraxtrauma für eine sofortige Dekompression statt bloßer Beobachtung?", [["Einseitig deutlich vermindertes Atemgeräusch bei passendem Trauma", true], ["Hypotonie oder andere Zeichen hämodynamischer Instabilität", true], ["Akute Verschlechterung unter Überdruckbeatmung", true], ["Isolierter lokaler Thoraxschmerz bei stabilen Vitalparametern"], ["Eine klinisch eindeutige lebensbedrohliche Konstellation auch ohne radiologische Bestätigung", true]], "Der Spannungspneumothorax ist eine klinische Diagnose; bei vitaler Bedrohung darf die Behandlung nicht auf Bildgebung warten.", 3),
];
