import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [string, boolean];
function q(n: number, prompt: string, options: Option[], source: string): ThoraxtraumaChoiceQuestion {
  const shift = n % options.length;
  return { id: `pseudokrupp-epiglottitis-q-${String(n).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty: 3 };
}

export const pseudokruppEpiglottitisQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Ein dreijähriges Kind hat plötzlich hohes Fieber, Speichelfluss und inspiratorischen Stridor. Welche Schlüsse tragen?", [["Epiglottitis muss priorisiert werden", true], ["Racheninspektion kann eine Verschlechterung auslösen", true], ["Ein bellender Husten ist für diese Verdachtsdiagnose nicht erforderlich", true], ["Ein erhaltener Impfpass schließt Epiglottitis sicher aus", false], ["Der Stridor beweist eine bronchiale Obstruktion", false]], "Hohes Fieber, Dysphagie/Speichelfluss und schwerer Eindruck sind Red Flags für eine supraglottische Erkrankung."),
  q(2, "Ein Kleinkind erwacht nachts mit bellendem Husten, Heiserkeit und Stridor; es kann schlucken. Welche Befunde sprechen eher für Pseudokrupp?", [["Bellender Husten und Heiserkeit", true], ["Subglottische Schleimhautschwellung", true], ["Inspiratorischer Stridor bei zunächst wenig beeinträchtigtem Allgemeinzustand", true], ["Kloßige Stimme mit Speichelfluss", false], ["Sehr hohes Fieber mit toxischem Eindruck", false]], "Pseudokrupp betrifft den subglottischen Bereich; bellender Husten und Heiserkeit unterscheiden ihn von der klassischen Epiglottitis."),
  q(3, "Warum kann eine geringe Schwellung beim Kleinkind erhebliche Atemnot auslösen?", [["Der Ausgangsdurchmesser des Atemwegs ist klein", true], ["Weniger Lumen steigert den Strömungswiderstand stark", true], ["Erschöpfung kann die Ventilation weiter verschlechtern", true], ["Die Schwellung vergrößert den Luftweg und senkt den Widerstand", false], ["Ein normaler Einzelwert der SpO₂ schließt eine relevante Obstruktion sicher aus", false]], "Der kleine kindliche Atemweg hat wenig Reserve; Klinik und Verlauf sind wichtiger als ein Einzelwert."),
  q(4, "Welche Aussagen lokalisieren die beiden Erkrankungen korrekt?", [["Epiglottitis: supraglottischer Kehlkopfeingang", true], ["Pseudokrupp: subglottischer Bereich unter den Stimmlippen", true], ["Beide können inspiratorischen Stridor auslösen", true], ["Pseudokrupp ist primär eine Obstruktion der kleinen Bronchien", false], ["Epiglottitis ist stets eine isolierte Erkrankung der Alveolen", false]], "Die Lokalisation am Kehlkopfeingang versus darunter erklärt die Differenzialdiagnose."),
  q(5, "Bei vermuteter Epiglottitis sitzt das Kind vornübergebeugt auf dem Schoß der Mutter. Was ist sinnvoll?", [["Wunschposition belassen und Bezugsperson einbinden", true], ["Keine erzwungene Racheninspektion", true], ["Notarzt und geeignete Kinderklinik früh koordinieren", true], ["Für eine Standarduntersuchung zuerst flach lagern", false], ["Einen i.v.-Zugang gegen deutlichen Widerstand erzwingen", false]], "Stress und Manipulation können den bedrohten Atemweg verschlechtern; VFA 24 priorisiert Beruhigung, Überwachung und Transport."),
  q(6, "Welche Zeichen sprechen beim stridorösen Kind für Erschöpfung statt Entwarnung?", [["Bewusstseinsminderung", true], ["Nachlassender Stridor bei schlechter werdender Atemarbeit", true], ["Bradykardie oder Zyanose", true], ["Allein eine ruhigere Geräuschkulisse bei sonst unbekanntem Verlauf", false], ["Bellender Husten bei wachem Kind ohne Atemnot beweist Atemstillstand", false]], "Leiser Stridor kann durch sinkenden Luftstrom entstehen; Bradykardie ist beim hypoxischen Kind ein spätes Zeichen."),
  q(7, "Ein Kind mit Stridor soll nach Thüringer VFA 24 mit Adrenalin vernebelt werden. Welche Angaben stimmen?", [["4 mg in 4 ml", true], ["Unverdünnt über Kinderverneblermaske", true], ["6 l/min O₂ als Verneblerfluss", true], ["0,5 mg/kgKG plus 5 ml NaCl ist die VFA-24-Standardzubereitung", false], ["Eine i.v.-Bolusgabe ersetzt die Inhalation", false]], "VFA 24: Adrenalin 4 mg/4 ml unverdünnt mit 6 l/min O₂; die abweichende Skriptmischung wurde nicht übernommen."),
  q(8, "Welche Aussagen zur weiteren VFA-24-Medikation bei Epiglottitis und Pseudokrupp sind richtig?", [["100 mg Prednisolon rektal sind im gemeinsamen VFA-Pfad genannt", true], ["Die Adrenalinverneblung soll durchlaufen", true], ["Ein Prednisolon-Suppositorium ersetzt nicht die Atemwegsüberwachung", true], ["Stadium 3 erzwingt laut VFA 24 4 mg/kgKG Prednisolon i.v.", false], ["Salbutamol steht im Epiglottitis-Zweig der VFA", false]], "VFA 24 zeigt nach der Adrenalinverneblung 100 mg Prednisolon rektal; Salbutamol gehört zum separaten Asthma-Zweig."),
  q(9, "Weshalb sind Adrenalin und Prednisolon im VFA-Pfad nicht austauschbar?", [["Inhalatives Adrenalin kann über α-vermittelte Vasokonstriktion Schleimhaut rasch abschwellen lassen", true], ["Prednisolon wirkt antiinflammatorisch, aber nicht als gleich schneller Ersatz", true], ["Ein nachlassender Adrenalineffekt verlangt weitere Beobachtung", true], ["Prednisolon erweitert die Bronchien unmittelbar durch β₂-Stimulation", false], ["Adrenalin wirkt ausschließlich als Antibiotikum", false]], "Epinephrin und Glukokortikoid haben verschiedene Wirkmechanismen und Zeitprofile."),
  q(10, "Ein Kind hat exspiratorisches Giemen ohne bellenden Husten oder Schluckstörung. Welche VFA-Abgrenzung ist wichtig?", [["Schweren Asthmaanfall als eigenen Zweig prüfen", true], ["Salbutamol zielt auf die Bronchialmuskulatur", true], ["Ein inspiratorischer Stridor würde erneut an einen oberen Atemweg denken lassen", true], ["Salbutamol ist Standard gegen supraglottische Schwellung", false], ["Die Lage des Atemwegshindernisses ist für die Medikamentenwahl belanglos", false]], "VFA 24 trennt schweren Asthmaanfall von Epiglottitis/Pseudokrupp; Salbutamol ist ein β₂-Bronchodilatator."),
  q(11, "Welche Angaben sind bei einem Kind mit unklarem Stridor für die Differenzialdiagnose besonders nützlich?", [["Beginn plötzlich nach Essen oder Spielen", true], ["Schluckfähigkeit und Speichelfluss", true], ["Inspiratorisches versus exspiratorisches Geräusch", true], ["Ausschließlich die Körpertemperatur", false], ["Nur die Vorerkrankung Asthma ohne aktuelle Befunde", false]], "Fremdkörper, Epiglottitis, Pseudokrupp und Asthma unterscheiden sich durch Kontext, Lokalisation und Begleitsymptome."),
  q(12, "Ein Kind mit vermuteter Epiglottitis kann noch ausreichend selbst atmen. Welche Entscheidungen sind fachlich tragfähig?", [["Transport in Klinik mit Kinderintensivstation voranmelden", true], ["Atemwegs- und Beatmungsbereitschaft herstellen", true], ["O₂ nur so anbieten, wie es ohne zusätzliche Panik toleriert wird", true], ["Zur Diagnosesicherung den Rachen gegen den Willen des Kindes eröffnen", false], ["Klinischen Transport bis nach einer vollständigen Laborabklärung aufschieben", false]], "Der bedrohte Atemweg verlangt minimale Provokation und zügigen Transport; VFA 24 fordert die telefonische Voranmeldung."),
  q(13, "Welche Aussagen zur kühlen Luft bei Pseudokrupp sind angemessen?", [["Die Thüringer VFA 24 nennt sie als ergänzende Maßnahme", true], ["Sie darf eine notwendige Überwachung nicht ersetzen", true], ["Das Kind sollte dabei ruhig bleiben und nicht auskühlen", true], ["Ihre Wirkung ist so sicher, dass Adrenalin und Transport entfallen", false], ["Feuchte Luft ist die definitive Therapie einer Epiglottitis", false]], "Kühle, feuchte Luft steht im Pseudokrupp-Zweig; die klinische Evidenz ist uneinheitlich und Maßnahmen dürfen nicht verzögert werden."),
  q(14, "Welche Aussagen zum VFA-24-Zugang und zur Versorgung passen?", [["Bei Pseudokrupp ist ein i.v.-Zugang meist nicht erforderlich", true], ["Bei Epiglottitis darf ein belastender Zugang den Atemweg nicht gefährden", true], ["Kontinuierliches Monitoring und Transport gelten für beide Zweige", true], ["Vor Adrenalin muss bei jedem Kind zwingend ein i.v.-Zugang liegen", false], ["Ein bereits gebesserter Husten macht die Verlaufskontrolle entbehrlich", false]], "VFA 24 erlaubt den Zugang ggf. parallel, weist aber auf die meist fehlende Notwendigkeit bei Pseudokrupp hin."),
  q(15, "Welche Unterschiede in Stimme und Schlucken sind als Prüfungsmerkmale belastbar?", [["Kloßige Stimme und Schluckstörung stützen Epiglottitis", true], ["Heiserkeit und bellender Husten stützen Pseudokrupp", true], ["Speichelfluss kann Ausdruck schmerzhaft eingeschränkten Schluckens sein", true], ["Heiserkeit schließt jede Atemwegsgefahr aus", false], ["Bellender Husten ist das Leitsymptom der Epiglottitis", false]], "Die Merkmalskombination entscheidet; kein einzelner Befund ist absolut."),
  q(16, "Ein vierjähriges Kind mit bellendem Husten wird still, blass und somnolent. Was ist richtig?", [["Erschöpfung oder Hypoventilation sind möglich", true], ["Atemweg, Ventilation und Kreislauf sofort erneut beurteilen", true], ["Notarzt- und Beatmungsbereitschaft eskalieren", true], ["Weniger Husten beweist eine erfolgreiche Therapie", false], ["Eine zunächst normale SpO₂ macht Re-Evaluation überflüssig", false]], "Nachlassende Lautstärke kann bei sinkendem Luftstrom eine Verschlechterung markieren."),
  q(17, "Welche Gegenüberstellung trifft Ätiologie und Verlauf am besten?", [["Pseudokrupp ist meist viral", true], ["Epiglottitis ist klassisch bakteriell und kann rasch fortschreiten", true], ["Hib-Impfung vermindert das Risiko, schließt andere Erreger aber nicht aus", true], ["Jede Epiglottitis tritt ausschließlich bei ungeimpften Kindern auf", false], ["Pseudokrupp beweist eine bakterielle Sepsis", false]], "Script und ergänzende Quellen unterscheiden einen meist viralen subglottischen von einem klassisch bakteriellen supraglottischen Prozess."),
  q(18, "Ein Kind mit Fieber, inspiratorischem Stridor und Speichelfluss soll untersucht werden. Welche Risiken und Prioritäten gehören in die Teamentscheidung?", [["Atemwegsverlegung kann rasch vollständig werden", true], ["Manipulationen können die Lage verschlechtern", true], ["Die geeignete Zielklinik muss früh informiert werden", true], ["Eine normale Herzfrequenz garantiert Atemwegsstabilität", false], ["Der Stridor allein rechtfertigt Salbutamol statt VFA-24-Epiglottitis-Pfad", false]], "Epiglottitis bleibt ein zeitkritischer Atemwegsnotfall mit geringer Manipulation und Voranmeldung."),
  q(19, "Welche Befunde sprechen gegen eine reine obere Atemwegsverlegung und für zusätzliche Differenzialdiagnosen?", [["Plötzlicher Beginn beim Essen ohne Infektzeichen spricht für Fremdkörper", true], ["Urtikaria plus Schwellung und Kreislaufreaktion spricht für Anaphylaxie", true], ["Überwiegend exspiratorisches Giemen spricht für Bronchoobstruktion", true], ["Bellender Husten zwingt zur Diagnose eines Bronchialasthmas", false], ["Speichelfluss beweist einen unkomplizierten Pseudokrupp", false]], "Kontext und Begleitzeichen trennen Fremdkörper, Anaphylaxie und Asthma vom Pseudokrupp/Epiglottitis-Vergleich."),
  q(20, "Was muss bei der Übergabe eines nach VFA 24 versorgten Kindes konkret berichtet werden?", [["Zeitlicher Verlauf von Stimme, Stridor, Atemarbeit und Vigilanz", true], ["Adrenalinmenge, Applikationsweg und Beobachtung der Wirkung", true], ["Prednisolon-Gabe und Zeitpunkt", true], ["Nur die Verdachtsdiagnose ohne Vitalverlauf", false], ["Die Gabe von Salbutamol als Pseudokrupp-Standard dokumentieren, obwohl sie nicht erfolgte", false]], "Die Übergabe braucht Verlauf, Re-Evaluation, VFA-Maßnahmen und Wirkung; besonders bei Epiglottitis ist die Klinik voranzumelden."),
];

export const pseudokruppEpiglottitisFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "pseudokrupp-epiglottitis-card-01", area: "Definition", question: "Definieren Sie Epiglottitis und Pseudokrupp anhand der anatomischen Lokalisation und der Gefahr.", answer: "Epiglottitis: akute Entzündung/Schwellung der Epiglottis und supraglottischer Strukturen mit Gefahr rascher Atemwegsverlegung. Pseudokrupp: meist virale subglottische Laryngotracheitis mit Verengung des kindlichen Atemwegs." },
  { id: "pseudokrupp-epiglottitis-card-02", area: "Anatomie", question: "Warum kann dieselbe Schleimhautschwellung beim Kind ausgeprägtere Atemnot auslösen als beim Erwachsenen?", answer: "Der Ausgangsdurchmesser ist kleiner; zusätzliche Schwellung verkleinert das Lumen relativ stark und steigert den Widerstand. Höherer O₂-Bedarf und geringere Reserve begünstigen schnelle Verschlechterung." },
  { id: "pseudokrupp-epiglottitis-card-03", area: "Klinische Trennung", question: "Nennen Sie fünf Merkmale, die Epiglottitis gegenüber Pseudokrupp wahrscheinlicher machen.", answer: "Plötzlicher Beginn, hohes Fieber, schwer kranker Eindruck, Schluckschmerz/-störung, Speichelfluss und kloßige Stimme. Inspiratorischer Stridor allein trennt nicht." },
  { id: "pseudokrupp-epiglottitis-card-04", area: "Klinische Trennung", question: "Ein Kind hustet bellend und ist heiser. Welche Befunde würden die Entscheidung sofort in Richtung Epiglottitis verändern?", answer: "Rascher schwerer Verlauf, hohes Fieber, Speichelfluss oder Unfähigkeit zu schlucken, kloßige Stimme, Schonhaltung und deutlich reduzierter Allgemeinzustand. Kein einzelner Befund ist absolut." },
  { id: "pseudokrupp-epiglottitis-card-05", area: "Pathophysiologie", question: "Leiten Sie Stridor und Husten bei Pseudokrupp aus der Schwellung her und erklären Sie die klinische Gefahr eines leiser werdenden Stridors.", answer: "Die subglottische Engstelle erzeugt turbulente inspiratorische Luftströmung; Kehlkopfbeteiligung erklärt Heiserkeit und bellenden Husten. Leiserer Stridor kann durch sinkenden Luftstrom bei Erschöpfung entstehen, nicht nur durch Besserung." },
  { id: "pseudokrupp-epiglottitis-card-06", area: "Atemwegsmanagement", question: "Warum sind forcierte Racheninspektion und flaches Hinlegen bei vermuteter Epiglottitis problematisch?", answer: "Stress und Manipulation können eine kritische obere Atemwegsverlegung verschlimmern. Wunschposition und Bezugsperson belassen, ruhige Beurteilung, Notarzt und geeignete Kinderklinik früh organisieren." },
  { id: "pseudokrupp-epiglottitis-card-07", area: "VFA 24", question: "Welche Adrenalin-Zubereitung und Verneblung nennt die Thüringer VFA 24 für Epiglottitis/Pseudokrupp?", answer: "4 mg Adrenalin in 4 ml unverdünnt über Kinderverneblermaske mit 6 l/min O₂ vernebeln und die Verneblung durchlaufen lassen; alternativ Fertiginhalat laut VFA." },
  { id: "pseudokrupp-epiglottitis-card-08", area: "VFA 24", question: "Welche Glukokortikoid-Gabe folgt in VFA 24 und welche abweichenden Skriptangaben wurden nicht übernommen?", answer: "100 mg Prednisolon rektal als Suppositorium. Die Skriptangaben zur gewichtsabhängigen Adrenalinverdünnung und zu 2–4 mg/kg Prednisolon i.v. sind nicht der VFA-24-Pfad." },
  { id: "pseudokrupp-epiglottitis-card-09", area: "Pharmakologie", question: "Vergleichen Sie den Zweck von inhaliertem Adrenalin und Prednisolon bei oberer Atemwegsobstruktion.", answer: "Adrenalin kann über α-vermittelte Vasokonstriktion die Schleimhaut rasch abschwellen lassen; Prednisolon hemmt Entzündung und Ödem mit langsamerem Wirkungseintritt. Deshalb weiterhin überwachen und transportieren." },
  { id: "pseudokrupp-epiglottitis-card-10", area: "Differenzialdiagnose", question: "Warum ist Salbutamol bei reinem Pseudokrupp oder Epiglottitis nicht der passende VFA-24-Standard?", answer: "Salbutamol stimuliert β₂-Rezeptoren der Bronchialmuskulatur und behandelt Bronchospasmus im getrennten Asthma-Zweig. Es beseitigt keine supraglottische oder subglottische Schleimhautschwellung." },
  { id: "pseudokrupp-epiglottitis-card-11", area: "Eskalation", question: "Ein Kind mit zuvor lautem Stridor ist nun schläfrig und leise. Wie begründen Sie die nächste Entscheidung?", answer: "Nicht als Besserung werten: sinkender Luftstrom, Hypoventilation und Erschöpfung sind möglich. Sofort cABCDE wiederholen, Atem-/Beatmungsbereitschaft und Notarzt eskalieren, Transportpriorität erhöhen." },
  { id: "pseudokrupp-epiglottitis-card-12", area: "Übergabe", question: "Welche Informationen gehören bei Verdacht auf Epiglottitis in Voranmeldung und Übergabe?", answer: "Beginn und Dynamik, Schlucken/Speichel, Stimme, Stridor und Atemarbeit, Vigilanz, SpO₂/Vitalverlauf, Wunschposition, O₂/Adrenalin/Prednisolon mit Zeit und Wirkung, Nachforderung und Atemwegslage." },
];
