import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function PseudokruppEpiglottitisLesson({ Vfa, children }: Props) {
  const section = (number: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>Kindernotfall · zwei obere Atemwegsbilder</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;
  const versus = (left: ReactNode, right: ReactNode) => <div className="pe-vs-grid"><div className="pe-vs-side epiglottitis"><small>Epiglottitis · oberhalb der Stimmritze</small>{left}</div><div className="pe-vs-side pseudokrupp"><small>Pseudokrupp · unterhalb der Stimmritze</small>{right}</div></div>;
  return <article className="lesson-article rippenfraktur-lesson pe-lesson">
    <div className="lesson-intro"><p className="lead">Beide Erkrankungen können einen inspiratorischen Stridor auslösen. Für die Prüfung zählt die schnelle Trennung: <b>Speichelfluss, Schluckschmerz und schwer kranker Eindruck</b> sprechen für Epiglottitis; <b>bellender Husten und Heiserkeit</b> für Pseudokrupp. Ein erschöpftes Kind kann trotz leiser werdendem Stridor akut gefährdet sein.</p></div>

    {section("01", "Definition", versus(<><h3>Entzündung am Kehldeckel</h3><p>Akute, potenziell lebensbedrohliche Entzündung und Schwellung der Epiglottis sowie benachbarter supraglottischer Strukturen. Der Kehlkopfeingang kann sich rasch verlegen.</p></>, <><h3>Schwellung unter der Stimmritze</h3><p>Meist virusbedingte Laryngotracheitis mit Schleimhautschwellung im subglottischen Bereich. Der enge kindliche Atemweg wird weiter verengt; die Luft strömt hörbar turbulent.</p></>))}

    {section("02", "Anatomie und Physiologie", <><div className="pe-airway-layers"><span>Mund / Rachen</span><i>↓</i><span>Epiglottis · schützt beim Schlucken den Kehlkopfeingang</span><i>↓</i><span>Stimmritze</span><i>↓</i><span>Subglottis / Luftröhre</span></div>{versus(<><h3>Supraglottisch</h3><p>Die Schwellung sitzt am oder über dem Kehlkopfeingang. Schlucken und der Umgang mit Speichel werden schmerzhaft und schwierig.</p></>, <><h3>Subglottisch</h3><p>Die Schwellung liegt unter den Stimmlippen. Schon wenig zusätzliche Schleimhautdicke steigert im kleinen kindlichen Atemweg den Widerstand erheblich.</p></>)}<div className="pulmo-anatomy-grid"><div><small>Kleiner Atemweg</small><b>Wenig Reserve</b><p>Schwellungen wirken sich relativ stärker aus als beim Erwachsenen.</p></div><div><small>Säugling</small><b>Relativ große Zunge</b><p>Bei Erschöpfung oder Bewusstseinsminderung kann sie den Atemweg zusätzlich verlegen; den Kopf altersgerecht neutral lagern.</p></div><div><small>Stoffwechsel</small><b>Hoher O₂-Bedarf</b><p>Desaturation und Wärmeverlust können bei kleinen Kindern rascher auftreten.</p></div></div></>)}

    {section("03", "Pathophysiologie und Ursachen", <>{versus(<><h3>Rasch zunehmende Schwellung</h3><ul><li>Meist bakterielle Infektion; Hib ist der klassische Erreger, andere Bakterien sind möglich.</li><li>Schwellung der supraglottischen Schleimhaut verengt den Kehlkopfeingang.</li><li>Schmerz und Schluckstörung erklären Speichelfluss und kloßige Stimme.</li></ul></>, <><h3>Virus und enger Atemweg</h3><ul><li>Meist virale Infektion, besonders Parainfluenza; auch weitere Atemwegsviren.</li><li>Subglottische Schleimhautschwellung verengt den Atemweg.</li><li>Turbulente Einatmung erzeugt Stridor; die Kehlkopfbeteiligung erklärt Heiserkeit und bellenden Husten.</li></ul></>)}<p><b>Einordnung:</b> Pseudokrupp tritt vor allem im Kleinkindalter auf, Epiglottitis klassisch bei ungeimpften Kindern. Alter oder Hib-Impfung allein dürfen eine Epiglottitis jedoch nicht ausschließen.</p></>)}

    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", <><div className="pe-comparison" role="table" aria-label="Leitsymptome im direkten Vergleich"><div role="row" className="pe-comparison-head"><b role="columnheader">Merkmal</b><b role="columnheader">Epiglottitis</b><b role="columnheader">Pseudokrupp</b></div>{[["Beginn", "Plötzlich, rasche Verschlechterung", "Oft nachts nach Infekt"],["Temperatur / Eindruck", "Hohes Fieber, schwer krank", "Kein oder leichtes Fieber, anfangs oft guter AZ"],["Stimme / Husten", "Kloßige Sprache, Husten eher selten", "Heiserkeit, bellender Husten"],["Schlucken / Speichel", "Schmerz, Schluckstörung, Speichelfluss", "Meist keine Schluckstörung, kein Speichelfluss"],["Atemgeräusch", "Inspiratorischer Stridor möglich", "Inspiratorischer Stridor möglich"]].map(([a,b,c]) => <div role="row" key={a}><b role="rowheader">{a}</b><span role="cell">{b}</span><span role="cell">{c}</span></div>)}</div><aside className="red-flags"><span>!</span><div><small>Red Flag</small><h3>Speichelfluss + Schluckschmerz + toxischer Eindruck</h3><p>Epiglottitis bis zum Beweis des Gegenteils mitdenken. Den Mund nicht gegen den Willen des Kindes inspizieren oder das Kind flach hinlegen.</p></div></aside></>)}

    {section("05", "Komplikationen und Gefahren", <>{versus(<><h3>Plötzlicher Atemwegsverlust</h3><ul><li>Komplette Verlegung, Hypoxie, Atemstillstand.</li><li>Manipulation, Angst oder erzwungene Lagerung können verschlechtern.</li><li>Bradykardie ist beim hypoxischen Kind ein spätes Warnzeichen.</li></ul></>, <><h3>Zunehmende Atemarbeit</h3><ul><li>Einziehungen, Erschöpfung, Hypoxie und respiratorische Insuffizienz.</li><li>Leiser werdender Stridor kann bei sinkendem Luftstrom ein Alarmsignal sein.</li><li>Bewusstseinsminderung, Zyanose und Bradykardie sind späte Gefahrenzeichen.</li></ul></>)}<p><b>Prüfungsfalle:</b> „Es ist wieder ruhig“ beweist keine Besserung. Atemarbeit, Vigilanz, Hautfarbe, Sättigung und – soweit verfügbar – Kapnographie im Verlauf gemeinsam beurteilen.</p></>)}

    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", <div className="material-chips">{["Kindernotfallrucksack / kognitive Hilfe", "PSA und situationsgerechter Eigenschutz", "O₂ und Kindervernebler", "Absaugung", "Beatmungsbeutel und Kindermasken", "Atemwegsmaterial", "SpO₂ / EKG / RR", "Kapnographie bei Atemunterstützung", "Prednisolon-Suppositorium", "Adrenalin zur Inhalation"].map(x => <span key={x}>{x}</span>)}</div>)}

    {section("07", "Erstmaßnahmen und Anamnese", <><div className="pulmo-care-grid"><div><span>01</span><b>Kind ruhig halten</b><small>Bezugsperson einbeziehen, Wunschposition belassen, unnötige Trennung und Stress vermeiden.</small></div><div><span>02</span><b>cABCDE</b><small>Atemweg, Atemarbeit, Stridor, SpO₂, Kreislauf und Bewusstsein fortlaufend beurteilen.</small></div><div><span>03</span><b>O₂ nach Bedarf</b><small>So anbieten, wie das Kind es toleriert; Maske nicht gewaltsam aufsetzen.</small></div><div><span>04</span><b>Früh nachfordern</b><small>Bei Epiglottitis oder anhaltender Atemnot Notarzt und geeignete Zielklinik früh einbinden.</small></div></div>{versus(<><h3>Keine Racheninspektion erzwingen</h3><p>Keine unnötige Manipulation am Mund, kein erzwungenes Hinlegen; Transport und Atemwegsbereitschaft priorisieren.</p></>, <><h3>Belastung reduzieren</h3><p>Aufrechte Wunschposition, beruhigen, kühle Luft nur als tolerierte Ergänzung. Sie ersetzt weder Überwachung noch VFA-Therapie.</p></>)}<h3>SAMPLERS · gezielt</h3><div className="samplers-grid">{[["S · Symptome","Beginn, Husten, Stimme, Schlucken, Stridor"],["A · Allergien","Bekannte Unverträglichkeiten"],["M · Medikamente","Bisherige Inhalationen / Zäpfchen"],["P · Vorgeschichte","Atemwegserkrankungen, Hib-Impfstatus"],["L · Letzte Aufnahme","Trinken und Schlucken möglich?"],["E · Ereignis","Nächtlicher Beginn, Infekt, Aspiration"],["R · Risiken","Fremdkörper, Anaphylaxie, Inhalationstrauma"],["S · Sonstiges","Elternbeobachtung, Verlauf, Gewicht"]].map(([a,b]) => <p key={a}><b>{a}</b>{b}</p>)}</div></>)}

    {section("08", "Differenzialdiagnosen und Entscheidung", <><div className="pe-decision"><div><small>Bellender Husten + Heiserkeit</small><b>Pseudokrupp wahrscheinlicher</b><p>Inspiratorischer Stridor passt zur oberen Atemwegsverengung. Schwere und Erschöpfung dennoch prüfen.</p></div><div><small>Schluckschmerz + Speichelfluss</small><b>Epiglottitis priorisieren</b><p>Bei raschem Beginn und schwerem Krankheitsgefühl Atemwegsverlust befürchten; keine Rachenmanipulation.</p></div><div><small>Exspiratorisches Giemen</small><b>Asthma / Bronchoobstruktion prüfen</b><p>Salbutamol wirkt an den Bronchien, nicht gegen eine supraglottische oder subglottische Schwellung.</p></div></div><div className="differential-grid">{["Fremdkörperaspiration", "Anaphylaxie", "Asthma / Bronchoobstruktion", "Bronchiolitis", "Inhalationstrauma", "Bakterielle Tracheitis", "Pneumonie"].map(x => <span key={x}>{x}</span>)}</div></>)}

    {section("09", "Weitere Maßnahmen · Thüringer VFA 24", <><div className="pe-vfa-dose"><div><small>Für die Epiglottitis- und Pseudokrupp-Spalte</small><b>Adrenalin inhalativ</b><p><strong>4 mg in 4 ml, unverdünnt</strong>, über Kinderverneblermaske mit <strong>6 l/min O₂</strong>. Verneblung durchlaufen lassen; alternativ Fertiginhalat laut VFA.</p></div><div><small>Danach laut VFA 24</small><b>Prednisolon rektal</b><p><strong>100 mg</strong> als Suppositorium. Es wirkt entzündungshemmend, aber nicht so unmittelbar wie inhaliertes Adrenalin.</p></div></div><p>Kind und Eltern beruhigen, Bezugspersonen einbinden, kontinuierlich überwachen und transportieren. Ein i.v.-Zugang kann parallel erwogen werden, ist bei Pseudokrupp meist nicht erforderlich; bei vermuteter Epiglottitis darf er Atemwegssicherung und Transport nicht durch Stress verzögern.</p><aside className="diagnostic-boundary"><span>!</span><div><b>Salbutamol ist kein Ersatz</b><p>Die <b>1,5 mg Salbutamolsulfat</b> der VFA 24 stehen im <b>separaten schweren Asthma-Zweig</b>. Der β₂-Agonist erweitert Bronchien; er beseitigt keine Schwellung am Kehlkopfeingang oder unterhalb der Stimmritze.</p></div></aside><p>Bei Epiglottitis: <b>zügiger Transport in eine Klinik mit Kinderintensivstation nach telefonischer Voranmeldung</b>. Bei drohender respiratorischer Insuffizienz Beatmung und erweitertes Atemwegsmanagement mit dem nachgeforderten Team vorbereiten, ohne das wache Kind unnötig zu provozieren.</p></>)}

    {section("10", "VFA Thüringen 2026/2027", <><p>Die Original-VFA 24 zeigt die drei getrennten Wege für Epiglottitis, Pseudokrupp und schweren Asthmaanfall. Die Arzneiangaben oben stammen aus den ersten beiden Spalten und der gemeinsamen Therapiezeile.</p><div className="vfa-stack"><Vfa src="/lessons/pseudokrupp-epiglottitis/vfa-24.png" alt="Thüringer VFA 24: Epiglottitis, Pseudokrupp-Anfall und schwerer Asthmaanfall beim Kind mit getrennten Entscheidungspfaden" caption="VFA 24 · Epiglottitis vs. Pseudokrupp · Original 2026/2027" /></div></>)}

    {children}
    <p className="lesson-source">Hauptgrundlage: „Print 13.pdf“. Medikamentenmengen und Entscheidungswege: <a href="https://www.aelrd-thueringen.de/verfahrensanweisungen-fuer-den-thueringer-rettungsdienst-algorithmen/" target="_blank" rel="noreferrer">Thüringer VFA 24 und B2A, 2026/2027</a>. Ergänzend: <a href="https://rd-factsheets.de/fs/epiglottitis/" target="_blank" rel="noreferrer">Epiglottitis</a>, <a href="https://rd-factsheets.de/fs/laryngotracheobronchitis-pseudokrupp/" target="_blank" rel="noreferrer">Pseudokrupp</a>, <a href="https://rd-factsheets.de/fs/epinephrin-2/" target="_blank" rel="noreferrer">Epinephrin</a>, <a href="https://rd-factsheets.de/fs/prednisolon/" target="_blank" rel="noreferrer">Prednisolon</a> und <a href="https://rd-factsheets.de/fs/salbutamol-2/" target="_blank" rel="noreferrer">Salbutamol</a>. Maßgeblich im Einsatz sind aktuelle VFA und ärztliche Anweisung.</p>
  </article>;
}
