import { supplementalQuestions } from "./supplemental-questions";

export type LegalFlashcard = { id: string; area: string; question: string; answer: string };

export type LegalQuestion = {
  id: string;
  prompt: string;
  options: { text: string; correct?: boolean }[];
  source: string;
  difficulty: 1 | 2 | 3;
  mode: "multiple";
};

export const rechtskundeFlashcards: LegalFlashcard[] = [
  { id: "recht-card-01", area: "Rechtsordnung", question: "Ordnen Sie Verfassung, formelles Gesetz, Rechtsverordnung und Satzung hierarchisch ein.", answer: "Höherrangiges Recht bindet niederrangiges Recht: Verfassung → formelles Gesetz → Rechtsverordnung → Satzung. Zusätzlich sind Unionsrecht und die jeweilige Gesetzgebungskompetenz zu beachten." },
  { id: "recht-card-02", area: "NotSanG", question: "Welche zwei kumulativen Voraussetzungen nennt § 2a NotSanG für eigenverantwortliche heilkundliche Maßnahmen?", answer: "Die Maßnahme wurde in der Ausbildung erlernt und wird beherrscht; außerdem ist sie erforderlich, um Lebensgefahr oder wesentliche Folgeschäden abzuwenden. Sie gilt bis zum Eintreffen des Notarztes oder bis zum Beginn weiterer ärztlicher, auch teleärztlicher, Versorgung." },
  { id: "recht-card-03", area: "NotSanG", question: "Grenzen Sie § 4 Abs. 2 Nr. 1 c von § 4 Abs. 2 Nr. 2 c NotSanG ab.", answer: "Nr. 1 c beschreibt eigenverantwortlich erlernte und beherrschte Erstversorgungsmaßnahmen in einer vitalen oder folgenschweren Lage. Nr. 2 c betrifft die eigenständige Durchführung heilkundlicher Maßnahmen nach standardmäßiger Vorgabe, Überprüfung und Verantwortung durch den ÄLRD oder entsprechend verantwortliche Ärzte." },
  { id: "recht-card-04", area: "ThürRettG", question: "Welche Rolle hat die Ärztliche Leitung Rettungsdienst bei standardisierten heilkundlichen Maßnahmen?", answer: "Sie gibt geeignete Maßnahmen für definierte Zustandsbilder standardmäßig vor, überprüft die Anwendung und trägt die ärztliche Systemverantwortung. Die ausführende Person behält Auswahl-, Durchführungs-, Überwachungs- und Dokumentationsverantwortung im konkreten Einsatz." },
  { id: "recht-card-05", area: "Strafrecht", question: "Prüfen Sie eine Straftat in der klassischen Reihenfolge.", answer: "Tatbestand (objektiv und subjektiv) → Rechtswidrigkeit mit möglichen Rechtfertigungsgründen → Schuld. Bei Unterlassen kommen Garantenstellung, Handlungsmöglichkeit und hypothetische Kausalität hinzu." },
  { id: "recht-card-06", area: "Einwilligung", question: "Welche Voraussetzungen machen eine Einwilligung in eine medizinische Maßnahme wirksam?", answer: "Einwilligungsfähigkeit, hinreichende Aufklärung, Freiwilligkeit, Bezug auf die konkrete Maßnahme und Erklärung vor der Maßnahme. Im zeitkritischen Notfall kann bei Einwilligungsunfähigkeit der mutmaßliche Wille maßgeblich sein." },
  { id: "recht-card-07", area: "ThürPsychKG", question: "Grenzen Sie die schnelle von der geplanten öffentlich-rechtlichen Unterbringung in Thüringen ab.", answer: "Schnell: § 9 ThürPsychKG erlaubt dem Sozialpsychiatrischen Dienst bei dringenden Anhaltspunkten und nicht rechtzeitig erreichbarer Gerichtsentscheidung eine vorläufige Unterbringung für höchstens 24 Stunden; der Antrag nach § 8 ist unverzüglich zu stellen. Geplant: Voraussetzungen nach § 7, regulärer Antrag mit Gutachten nach § 8 und gerichtliche Entscheidung." },
  { id: "recht-card-08", area: "Fixierung", question: "Wie trennen Sie Unterbringung und Fixierung, und welche Kerngrenze gilt für eine nicht nur kurzfristige Fixierung?", answer: "Schnelle oder geplante Unterbringung bezeichnet den Weg in die Einrichtung. Die Fixierung ist eine zusätzliche Sicherungsmaßnahme bei bereits untergebrachten Patienten nach § 14 ThürPsychKG. Nicht nur kurzfristige Fixierungen brauchen grundsätzlich eine vorherige richterliche Entscheidung; kurzfristig ist in der Regel eine absehbare Dauer unter 30 Minuten." },
  { id: "recht-card-09", area: "Schweigepflicht", question: "Wie wirkt die Schweigepflicht nach dem Tod und gegenüber Angehörigen?", answer: "Die Schweigepflicht endet nicht mit dem Tod. Angehörige – auch Ehepartner – haben kein automatisches Recht auf medizinische Informationen. Erforderlich sind Einwilligung, mutmaßliche Einwilligung oder eine gesetzliche beziehungsweise rechtfertigende Offenbarungsbefugnis." },
  { id: "recht-card-10", area: "Straßenverkehr", question: "Grenzen Sie Sonderrechte und Wegerecht ab.", answer: "§ 35 Abs. 5a StVO befreit Rettungsdienstfahrzeuge bei höchster Eile unter Wahrung öffentlicher Sicherheit und Ordnung von StVO-Vorschriften. § 38 Abs. 1 StVO: Nur blaues Blinklicht zusammen mit Einsatzhorn ordnet anderen an, sofort freie Bahn zu schaffen." },
  { id: "recht-card-11", area: "Patientenwille", question: "Wie wird eine Patientenverfügung nach § 1827 BGB angewendet?", answer: "Es wird geprüft, ob die schriftlichen Festlegungen auf die aktuelle Lebens- und Behandlungssituation zutreffen. Dann ist ihnen Geltung zu verschaffen. Andernfalls sind Behandlungswünsche oder der mutmaßliche Wille anhand konkreter Anhaltspunkte zu ermitteln." },
  { id: "recht-card-12", area: "BtMG", question: "Welche Voraussetzungen müssen für § 13 Abs. 1b BtMG zusammen vorliegen?", answer: "Notfallsanitäter verabreichen ein Anlage-III-Betäubungsmittel im Rahmen einer heilkundlichen Maßnahme; standardisierte ärztliche Vorgaben liegen vor; ärztliches Eintreffen kann nicht abgewartet werden; die Gabe ist zur Gefahrenabwehr oder zur Beseitigung beziehungsweise Linderung erheblicher Beschwerden erforderlich. Nachweis und Dokumentation bleiben Pflicht." },
  { id: "recht-card-13", area: "Rechtsnorm", question: "Definieren Sie Rechtsnorm und nennen Sie zwei Merkmale.", answer: "Eine Rechtsnorm ist eine verbindliche Regel des Rechts, die menschliches Verhalten ordnet und bei Verstößen staatlich durchgesetzt werden kann. Kerneigenschaften sind der allgemeine rechtliche Geltungsanspruch und die staatliche Durchsetzbarkeit beziehungsweise eine vorgesehene Rechtsfolge." },
  { id: "recht-card-14", area: "Rechtsquellen", question: "Nennen und unterscheiden Sie Gesetz, Rechtsverordnung, Satzung und Gewohnheitsrecht.", answer: "Gesetz: parlamentarisch beschlossen. Rechtsverordnung: von der Exekutive aufgrund gesetzlicher Ermächtigung. Satzung: autonome Regelung einer juristischen Person des öffentlichen Rechts. Gewohnheitsrecht: langdauernde gleichmäßige Übung mit Rechtsüberzeugung." },
  { id: "recht-card-15", area: "ThürRettG", question: "Definieren Sie Notfallpatienten nach § 3 Abs. 2 ThürRettG.", answer: "Notfallpatienten sind Verletzte oder Erkrankte, die sich in Lebensgefahr befinden oder bei denen schwere gesundheitliche Schäden zu befürchten sind." },
  { id: "recht-card-16", area: "ThürRettG", question: "Grenzen Sie Krankentransport und Krankenfahrt ab.", answer: "Krankentransport: Person benötigt nach ärztlicher Beurteilung während der Beförderung fachgerechte medizinische Betreuung oder ein besonders ausgestattetes Rettungsmittel beziehungsweise dies ist zu erwarten. Krankenfahrt: Weder fachgerechte Betreuung/Hilfeleistung noch Rettungsmittel sind erforderlich." },
  { id: "recht-card-17", area: "ThürRettG", question: "Wer trägt den bodengebundenen Rettungsdienst in Thüringen?", answer: "Grundsätzlich die Landkreise und kreisfreien Städte beziehungsweise gebildete Rettungsdienstzweckverbände. Für Luftrettung und besondere überregionale Aufgaben gelten weitere Zuständigkeiten." },
  { id: "recht-card-18", area: "Berufsbezeichnung", question: "Welche Voraussetzungen nennt § 2 Abs. 1 NotSanG für die Erlaubnis?", answer: "Vorgeschriebene Ausbildungszeit und bestandene staatliche Prüfung; Zuverlässigkeit; gesundheitliche Eignung; erforderliche Kenntnisse der deutschen Sprache." },
  { id: "recht-card-19", area: "Berufserlaubnis", question: "Unterscheiden Sie Rücknahme und Widerruf der NotSan-Erlaubnis.", answer: "Rücknahme: Eine Voraussetzung nach § 2 Abs. 1 Nr. 1 bis 3 fehlte bereits bei Erteilung. Widerruf: Die Zuverlässigkeit fällt später weg; bei später fehlender gesundheitlicher Eignung kann widerrufen werden. Eine Pflichtverletzung wirkt nicht automatisch, kann aber Unzuverlässigkeit begründen; daneben ist Verzicht möglich." },
  { id: "recht-card-20", area: "Krankenhausrecht", question: "Welche Pflicht folgt aus § 18 ThürKHG, und wie ist § 323c StGB abzugrenzen?", answer: "§ 18 ThürKHG verpflichtet das Krankenhaus im Rahmen von Versorgungsauftrag und Leistungsfähigkeit vorrangig zur Aufnahme und Versorgung von Notfallpatienten; bei Engpässen bleiben Notaufnahme, Erstversorgung und gefahrlose Weiterverlegung abzusichern. § 323c StGB ist die allgemeine Strafnorm zur erforderlichen und zumutbaren Hilfeleistung, nicht die spezielle Aufnahmegrundlage." },
  { id: "recht-card-21", area: "Ausbildung", question: "Welche Mindestinhalte nennt § 12 NotSanG für den Ausbildungsvertrag?", answer: "Berufsbezeichnung; Beginn und Dauer; Ausbildungs- und Prüfungsverordnung sowie zeitliche/sachliche Gliederung; Arbeitszeit; Probezeit; Vergütung; Urlaub; Kündigungsvoraussetzungen; tarifliche Bestimmungen und Dienstvereinbarungen." },
  { id: "recht-card-22", area: "Staatsrecht", question: "Was schützt die Ewigkeitsgarantie des Art. 79 Abs. 3 GG?", answer: "Die Gliederung des Bundes in Länder, die grundsätzliche Mitwirkung der Länder bei der Gesetzgebung sowie die in Art. 1 und Art. 20 GG niedergelegten Grundsätze dürfen durch Verfassungsänderung nicht berührt werden." },
  { id: "recht-card-23", area: "Patientenrechte", question: "Welche Kernrechte enthalten §§ 630a bis 630h BGB?", answer: "Behandlung nach fachlichem Standard, Information und Aufklärung, Einwilligung, zeitnahe und nachvollziehbare Dokumentation, Einsicht in die Behandlungsakte sowie besondere Beweislastregeln." },
  { id: "recht-card-24", area: "Unterbringung", question: "Welche drei Unterbringungsarten müssen unterschieden werden?", answer: "Öffentlich-rechtliche Unterbringung nach ThürPsychKG zur Abwehr einer krankheitsbedingten gegenwärtigen Gefahr; zivilrechtliche Unterbringung nach § 1831 BGB durch Betreuer oder ausdrücklich Bevollmächtigte mit gerichtlicher Genehmigung; strafrechtliche Unterbringung als gerichtlich angeordnete Maßregel nach §§ 63 oder 64 StGB nach einer rechtswidrigen Tat." },
  { id: "recht-card-25", area: "ThürPsychKG", question: "Grenzen Sie reguläre und vorläufige öffentlich-rechtliche Unterbringung ab.", answer: "Regulär: Voraussetzungen des § 7 ThürPsychKG, Antrag des Sozialpsychiatrischen Dienstes nach § 8 und gerichtliche Entscheidung. Vorläufig: Bei dringenden Anhaltspunkten und nicht rechtzeitig erreichbarer Gerichtsentscheidung darf der Sozialpsychiatrische Dienst nach § 9 höchstens 24 Stunden ab Beginn anordnen und muss unverzüglich den gerichtlichen Antrag stellen." },
  { id: "recht-card-26", area: "Betreuungsrecht", question: "Warum genügen Betreuung oder Vorsorgevollmacht nicht allein für eine Unterbringung?", answer: "Der Betreuer benötigt einen ausdrücklich gerichtlich angeordneten Aufgabenbereich für Unterbringung beziehungsweise freiheitsentziehende Maßnahmen. Eine Vorsorgevollmacht muss schriftlich sein und diese Maßnahmen ausdrücklich umfassen. Zusätzlich ist grundsätzlich die Genehmigung des Betreuungsgerichts erforderlich; bei Gefahr durch Aufschub ist sie unverzüglich nachzuholen." },
  { id: "recht-card-27", area: "Fixierung", question: "Welche Kernanforderungen gelten für eine nicht nur kurzfristige Fixierung nach ThürPsychKG?", answer: "Gegenwärtige erhebliche Gefahr, kein milderes geeignetes Mittel, Verhältnismäßigkeit, grundsätzlich vorherige gerichtliche Entscheidung, bei Gefahr im Verzug enge Nachholungspflichten, ärztliche Überwachung, ununterbrochene Eins-zu-eins-Betreuung, sofortige Beendigung bei Wegfall der Voraussetzungen, Nachbesprechung sowie umfassende Dokumentation. Kurzfristig bedeutet in der Regel absehbar weniger als 30 Minuten." },
  { id: "recht-card-28", area: "Fixierung", question: "Welche strafrechtliche Bedeutung kann eine Fixierung ohne tragfähige Rechtsgrundlage haben?", answer: "Festhalten, Einsperren oder eine vergleichbare Aufhebung der Fortbewegungsfreiheit kann § 239 StGB erfüllen. Rechtmäßig kann der Eingriff insbesondere durch wirksame Einwilligung oder eine passende gesetzliche Rechtfertigung sein. § 34 StGB verlangt eine gegenwärtige, nicht anders abwendbare Gefahr, wesentliches Überwiegen des geschützten Interesses und ein angemessenes Mittel." },
];

const rechtskundeBaseQuestions: LegalQuestion[] = [
  { id: "recht-q-01", prompt: "Welche Aussagen zur Normenhierarchie und zu juristischen Personen treffen zu?", options: [
    { text: "Eine Rechtsverordnung braucht grundsätzlich eine gesetzliche Ermächtigungsgrundlage.", correct: true },
    { text: "Eine Satzung darf höherrangigem Recht widersprechen, wenn sie lokal beschlossen wurde." },
    { text: "Die Rechtsfähigkeit einer juristischen Person hängt von ihrer Rechtsform und regelmäßig von Errichtung, Anerkennung oder Eintragung ab.", correct: true },
    { text: "Jeder Zusammenschluss von genau 21 Personen wird ohne Weiteres zur juristischen Person." },
  ], source: "Rechtsverordnungen und Satzungen stehen unter dem Gesetz; juristische Personen entstehen nach den Regeln ihrer jeweiligen Rechtsform, nicht durch eine starre Mitgliederzahl.", difficulty: 1, mode: "multiple" },
  { id: "recht-q-02", prompt: "Welche Aussagen zur strafrechtlichen Verantwortlichkeit Minderjähriger sind richtig?", options: [
    { text: "Wer bei der Tat noch nicht 14 Jahre alt ist, ist nach § 19 StGB schuldunfähig.", correct: true },
    { text: "Bei 14- bis 17-Jährigen setzt Jugendstrafrecht zusätzlich die nötige Reife nach § 3 JGG voraus.", correct: true },
    { text: "Ab dem 18. Geburtstag ist Jugendstrafrecht unter allen Umständen ausgeschlossen." },
    { text: "Bei Heranwachsenden von 18 bis 20 Jahren kann unter den Voraussetzungen des § 105 JGG Jugendstrafrecht angewandt werden.", correct: true },
  ], source: "§ 19 StGB sowie §§ 3 und 105 JGG unterscheiden Kinder, Jugendliche und Heranwachsende; starre Aussagen nur anhand des Alters greifen zu kurz.", difficulty: 1, mode: "multiple" },
  { id: "recht-q-03", prompt: "Welche Aussagen beschreiben § 2a NotSanG korrekt?", options: [
    { text: "Die Maßnahme muss in der Ausbildung erlernt worden sein und von der handelnden Person beherrscht werden.", correct: true },
    { text: "Die Maßnahme muss erforderlich sein, um Lebensgefahr oder wesentliche Folgeschäden abzuwenden.", correct: true },
    { text: "Die Befugnis endet erst mit persönlichem Eintreffen eines Notarztes; teleärztliche Versorgung ist unbeachtlich." },
    { text: "Eine vorherige individuelle ärztliche Anordnung ist Tatbestandsvoraussetzung jeder Maßnahme nach § 2a." },
  ], source: "§ 2a NotSanG erlaubt die eigenverantwortliche Durchführung bis zum Eintreffen des Notarztes oder Beginn weiterer ärztlicher, auch teleärztlicher, Versorgung bei zwei kumulativen Voraussetzungen.", difficulty: 1, mode: "multiple" },
  { id: "recht-q-04", prompt: "Welche Zuordnungen zum Ausbildungsziel nach § 4 Abs. 2 NotSanG sind richtig?", options: [
    { text: "Nr. 1 b: Gesundheitszustand beurteilen, vitale Bedrohung erkennen und über Nachforderungen entscheiden.", correct: true },
    { text: "Nr. 1 c: erlernte und beherrschte Maßnahmen zur Vermeidung einer Verschlechterung bei Lebensgefahr oder drohenden wesentlichen Folgeschäden.", correct: true },
    { text: "Nr. 2 b: eigenständiges Durchführen ärztlich veranlasster Maßnahmen.", correct: true },
    { text: "Nr. 2 c: freie Ausübung jeder heilkundlichen Maßnahme ohne standardmäßige ärztliche Vorgabe." },
  ], source: "§ 4 Abs. 2 NotSanG trennt eigenverantwortliche Aufgaben von der Mitwirkung, darunter ärztlich veranlasste und standardmäßig vorgegebene heilkundliche Maßnahmen.", difficulty: 1, mode: "multiple" },
  { id: "recht-q-05", prompt: "Welche Aussagen zur Prüfung einer Straftat sind zutreffend?", options: [
    { text: "Nach erfüllt geprüftem Tatbestand folgen Rechtswidrigkeit und Schuld.", correct: true },
    { text: "Notwehr nach § 32 StGB setzt einen gegenwärtigen rechtswidrigen Angriff voraus.", correct: true },
    { text: "Rechtfertigender Notstand nach § 34 StGB verlangt unter anderem eine Interessenabwägung und Angemessenheit.", correct: true },
    { text: "Jede Vorbereitungshandlung ist unabhängig vom Delikt strafbar." },
  ], source: "Klassischer Deliktsaufbau: Tatbestand, Rechtswidrigkeit, Schuld. Vorbereitungen sind grundsätzlich straflos, soweit das Gesetz nicht ausnahmsweise anderes bestimmt.", difficulty: 1, mode: "multiple" },
  { id: "recht-q-06", prompt: "Welche Aussagen zum Unterlassen im Rettungsdienst treffen zu?", options: [
    { text: "§ 323c StGB erfasst erforderliche und zumutbare Hilfeleistung auch ohne besondere Garantenstellung.", correct: true },
    { text: "Ein unechtes Unterlassungsdelikt setzt eine Rechtspflicht zum Einstehen für den Erfolg voraus.", correct: true },
    { text: "Die Übernahme der Patientenversorgung kann eine Garantenstellung begründen.", correct: true },
    { text: "Eine Garantenstellung führt automatisch zur Strafbarkeit, selbst wenn keine mögliche und zumutbare Handlung bestand." },
  ], source: "Unterlassungsdelikte erfordern je nach Tatbestand Garantenpflicht, Handlungsmöglichkeit, Zumutbarkeit und die weiteren Voraussetzungen der jeweiligen Norm.", difficulty: 2, mode: "multiple" },
  { id: "recht-q-07", prompt: "Eine einwilligungsfähige Patientin lehnt nach verständlicher Aufklärung den Transport ab. Welche Schritte sind rechtlich besonders wichtig?", options: [
    { text: "Einwilligungsfähigkeit und Verständnis der Risiken nachvollziehbar prüfen und dokumentieren.", correct: true },
    { text: "Über relevante Risiken, Alternativen und Warnzeichen aufklären und eine erneute Kontaktaufnahme ermöglichen.", correct: true },
    { text: "Die Ablehnung allein wegen einer medizinisch unvernünftigen Entscheidung ignorieren." },
    { text: "Bei fortbestehender Einwilligungsfähigkeit die autonome Entscheidung respektieren.", correct: true },
  ], source: "Selbstbestimmung erlaubt auch medizinisch unvernünftige Entscheidungen. Entscheidend sind Einwilligungsfähigkeit, Aufklärung, Freiwilligkeit und saubere Dokumentation.", difficulty: 2, mode: "multiple" },
  { id: "recht-q-08", prompt: "Welche Aussagen zur Behandlung Einwilligungsunfähiger sind richtig?", options: [
    { text: "Bei unaufschiebbarer Behandlung kann der mutmaßliche Wille eine Maßnahme rechtfertigen.", correct: true },
    { text: "Eine einschlägige Patientenverfügung ist auch unabhängig von Art und Stadium der Erkrankung zu beachten.", correct: true },
    { text: "Eine Patientenverfügung ist nur wirksam, wenn Arzt und Vertreter inhaltlich derselben Meinung sind." },
    { text: "Ist die Verfügung nicht einschlägig, sind konkrete frühere Äußerungen und Wertvorstellungen für den mutmaßlichen Willen relevant.", correct: true },
  ], source: "§ 1827 BGB verlangt die Prüfung der konkreten Passung; andernfalls sind Behandlungswünsche und mutmaßlicher Wille anhand konkreter Anhaltspunkte festzustellen.", difficulty: 2, mode: "multiple" },
  { id: "recht-q-09", prompt: "Welche Aussagen zur Schweigepflicht im Rettungsdienst treffen zu?", options: [
    { text: "Sie besteht grundsätzlich auch nach dem Tod fort.", correct: true },
    { text: "Ehegatten und Eltern volljähriger Patienten haben automatisch ein vollständiges Auskunftsrecht." },
    { text: "Im Behandlungsteam dürfen nur für die Versorgung erforderliche Informationen auf tragfähiger Rechtsgrundlage weitergegeben werden.", correct: true },
    { text: "Eine Offenbarung kann durch Einwilligung, mutmaßliche Einwilligung oder gesetzliche beziehungsweise rechtfertigende Befugnis gedeckt sein.", correct: true },
  ], source: "§ 203 StGB schützt anvertraute Geheimnisse; Tod oder Verwandtschaft beseitigen die Schweigepflicht nicht automatisch.", difficulty: 2, mode: "multiple" },
  { id: "recht-q-10", prompt: "Welche Aussagen zur sozialen Sicherung sind korrekt?", options: [
    { text: "Die soziale Pflegeversicherung ist im SGB XI geregelt.", correct: true },
    { text: "Volle Erwerbsminderung liegt grundsätzlich bei einer Leistungsfähigkeit von unter drei Stunden täglich unter den üblichen Bedingungen des allgemeinen Arbeitsmarktes vor.", correct: true },
    { text: "Teilweise Erwerbsminderung liegt grundsätzlich bei drei bis unter sechs Stunden täglich vor.", correct: true },
    { text: "Das SGB IX ist das Gesetzbuch der sozialen Pflegeversicherung." },
  ], source: "Pflegeversicherung: SGB XI. Erwerbsminderungsrente: grundsätzlich unter drei Stunden voll, drei bis unter sechs Stunden teilweise.", difficulty: 2, mode: "multiple" },
  { id: "recht-q-11", prompt: "Welche Aussagen zu § 35 und § 38 StVO sind richtig?", options: [
    { text: "§ 35 Abs. 5a kann Rettungsdienstfahrzeuge bei höchster Eile von StVO-Vorschriften befreien.", correct: true },
    { text: "Sonderrechte dürfen nur unter gebührender Berücksichtigung der öffentlichen Sicherheit und Ordnung ausgeübt werden.", correct: true },
    { text: "Erst blaues Blinklicht zusammen mit Einsatzhorn ordnet anderen Verkehrsteilnehmern an, sofort freie Bahn zu schaffen.", correct: true },
    { text: "Blaues Blinklicht allein erzeugt stets das Wegerecht nach § 38 Abs. 1." },
  ], source: "§ 35 StVO regelt Sonderrechte; § 38 Abs. 1 StVO die Anordnung freier Bahn durch blaues Blinklicht zusammen mit Einsatzhorn.", difficulty: 2, mode: "multiple" },
  { id: "recht-q-12", prompt: "Welche Aussagen zur ärztlichen Delegation sind richtig?", options: [
    { text: "Die anordnende Person trägt Verantwortung für Indikation, Auswahl einer geeigneten Person und klare Anordnung.", correct: true },
    { text: "Die ausführende Person trägt Verantwortung für Übernahme, fachgerechte Durchführung, Überwachung und Rückmeldung.", correct: true },
    { text: "Erkennbare fehlende Kompetenz oder eine unklare beziehungsweise gefährliche Anordnung muss angesprochen und gegebenenfalls abgelehnt werden.", correct: true },
    { text: "Mit der Delegation geht jede Verantwortung vollständig auf den ÄLRD über." },
  ], source: "Delegation verteilt Anordnungs-, Auswahl-, Übernahme- und Durchführungsverantwortung; sie beseitigt nicht die Eigenverantwortung der ausführenden Person.", difficulty: 2, mode: "multiple" },
  { id: "recht-q-13", prompt: "Welche Aussagen grenzen die schnelle und die geplante Unterbringung nach ThürPsychKG korrekt ab?", options: [
    { text: "§ 9 betrifft die vorläufige Unterbringung, wenn eine gerichtliche Entscheidung nicht rechtzeitig herbeigeführt werden kann.", correct: true },
    { text: "Die Anordnung nach § 9 erfolgt durch den Sozialpsychiatrischen Dienst und ist auf höchstens 24 Stunden ab Beginn begrenzt.", correct: true },
    { text: "Beim regulären Weg bilden § 7 die materiellen Voraussetzungen und § 8 Antrag, Gutachten und gerichtliches Verfahren ab.", correct: true },
    { text: "Eine vorläufige Unterbringung nach § 9 erlaubt automatisch jede Fixierung für 24 Stunden ohne weitere Prüfung." },
  ], source: "Das Skript unterscheidet den schnellen Weg nach § 9 vom geplanten regulären Verfahren nach §§ 7 und 8. Unterbringung und eine zusätzliche Fixierung nach § 14 müssen getrennt geprüft werden.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-14", prompt: "Welche Aussagen gibt § 14 ThürPsychKG für besondere Sicherungsmaßnahmen in der Einrichtung vor?", options: [
    { text: "Eine nicht nur kurzfristige Fixierung bedarf grundsätzlich einer vorherigen richterlichen Entscheidung.", correct: true },
    { text: "Als kurzfristig gilt eine Fixierung in der Regel, wenn absehbar unter 30 Minuten.", correct: true },
    { text: "Während einer Fixierung ist eine ununterbrochene Eins-zu-eins-Betreuung durch therapeutisches oder pflegerisches Personal sicherzustellen.", correct: true },
    { text: "Eine ärztliche Anordnung berechtigt stets zu einer Fixierung für 24 Stunden ohne gerichtliche Beteiligung." },
  ], source: "ThürPsychKG § 14 enthält Richtervorbehalt, kurze Ausnahmegrenze, engmaschige Überwachung, Eins-zu-eins-Betreuung und Dokumentationspflichten.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-15", prompt: "Welche Konstellationen können eine Datenweitergabe trotz Schweigepflicht rechtfertigen?", options: [
    { text: "Wirksame Einwilligung der betroffenen Person.", correct: true },
    { text: "Mutmaßliche Einwilligung bei erforderlicher Weitergabe zur anschließenden Behandlung.", correct: true },
    { text: "Gesetzliche Mitteilungsbefugnis oder rechtfertigender Notstand bei entsprechend gewichtiger Gefahr.", correct: true },
    { text: "Bloße Neugier eines Familienangehörigen mit zutreffendem Nachnamen." },
  ], source: "Offenbarung ist nur mit Einwilligung oder tragfähiger gesetzlicher beziehungsweise rechtfertigender Grundlage zulässig und auf das Erforderliche zu begrenzen.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-16", prompt: "Welche Aussagen zur Gabe eines Anlage-III-Betäubungsmittels nach § 13 Abs. 1b BtMG sind richtig?", options: [
    { text: "Eine standardisierte ärztliche Vorgabe muss die Anwendung tragen.", correct: true },
    { text: "Das Eintreffen eines Arztes darf nicht abgewartet werden können.", correct: true },
    { text: "Die Gabe muss zur Abwehr gesundheitlicher Gefahren oder zur Beseitigung beziehungsweise Linderung erheblicher Beschwerden erforderlich sein.", correct: true },
    { text: "Die Vorschrift erlaubt Notfallsanitätern jede beliebige Anlage-II-Substanz ohne Dokumentation." },
  ], source: "§ 13 Abs. 1b BtMG ist eng auf Anlage III, standardisierte Vorgaben, zeitliche Unaufschiebbarkeit und Erforderlichkeit begrenzt; Nachweis- und Dokumentationspflichten bleiben bestehen.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-17", prompt: "Ein Notfallsanitäter beherrscht eine invasive Maßnahme, doch die Lage erlaubt gefahrlos das sofortige teleärztliche Gespräch. Welche Aussagen sind vertretbar?", options: [
    { text: "§ 2a ist keine allgemeine Wunschbefugnis; seine konkrete Erforderlichkeit muss geprüft werden.", correct: true },
    { text: "Mit Beginn weiterer teleärztlicher Versorgung ist die zeitliche Grenze des § 2a erreicht.", correct: true },
    { text: "Beherrschen allein genügt, selbst wenn weder Lebensgefahr noch wesentliche Folgeschäden drohen." },
    { text: "Die Entscheidung und ihre medizinisch-rechtliche Begründung gehören in die Dokumentation.", correct: true },
  ], source: "§ 2a verlangt Beherrschen und konkrete Erforderlichkeit und endet auch mit Beginn einer weiteren teleärztlichen Versorgung.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-18", prompt: "Welche Aussagen bilden eine rechtssichere präklinische Entscheidungslogik am besten ab?", options: [
    { text: "Patientenwille und Einwilligungsfähigkeit klären; bei fehlender Fähigkeit Vertretung, Verfügung oder mutmaßlichen Willen prüfen.", correct: true },
    { text: "Für Eingriff und Datenweitergabe jeweils Rechtsgrundlage, Erforderlichkeit und Verhältnismäßigkeit getrennt prüfen.", correct: true },
    { text: "Bei Delegation Kompetenzgrenzen erkennen, Remonstration nutzen und Verlauf einschließlich Wirkung und Nebenwirkung dokumentieren.", correct: true },
    { text: "Eine medizinisch richtige Maßnahme ist unabhängig von Einwilligung, Zuständigkeit und Dokumentation immer rechtmäßig." },
  ], source: "Prüfungssicheres Handeln verbindet medizinische Indikation mit Patientenwillen, Befugnis, Verhältnismäßigkeit, Kompetenz, Überwachung und Dokumentation.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-19", prompt: "Welche Aussagen kennzeichnen eine Rechtsnorm zutreffend?", options: [
    { text: "Sie ordnet menschliches Verhalten mit rechtlichem Verbindlichkeitsanspruch.", correct: true },
    { text: "Ein Verstoß kann eine staatlich durchsetzbare Rechtsfolge auslösen.", correct: true },
    { text: "Sie richtet sich typischerweise abstrakt an einen bestimmten oder bestimmbaren Personenkreis.", correct: true },
    { text: "Jede moralische Erwartung ist allein deshalb eine Rechtsnorm." },
    { text: "Eine Rechtsnorm muss zwingend in einem Parlamentsgesetz stehen." },
  ], source: "Rechtsnormen sind verbindliche, staatlich durchsetzbare Regeln. Sie können insbesondere in Gesetzen, Rechtsverordnungen und Satzungen enthalten oder als Gewohnheitsrecht anerkannt sein.", difficulty: 2, mode: "multiple" },
  { id: "recht-q-20", prompt: "Welche Zuordnungen von Rechtsquellen und Rangordnung sind richtig?", options: [
    { text: "Das NotSanG ist ein formelles Bundesgesetz.", correct: true },
    { text: "Das ThürRettG ist ein formelles Landesgesetz.", correct: true },
    { text: "Die NotSan-APrV ist eine Rechtsverordnung, die eine gesetzliche Ermächtigungsgrundlage benötigt.", correct: true },
    { text: "Eine kommunale Satzung darf höherrangigem Bundes- oder Landesrecht widersprechen, wenn sie einstimmig beschlossen wurde." },
    { text: "Art. 31 GG ordnet für Normkollisionen an: Bundesrecht bricht Landesrecht.", correct: true },
  ], source: "Die Normenhierarchie bindet niederrangiges Recht. Daneben sind Gesetzgebungskompetenz und das Verhältnis von Bundes- zu Landesrecht zu beachten.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-21", prompt: "Welche Patienten erfüllen die Begriffsbestimmung des Notfallpatienten nach § 3 Abs. 2 ThürRettG?", options: [
    { text: "Ein Verletzter mit gegenwärtiger Lebensgefahr.", correct: true },
    { text: "Eine Erkrankte, bei der schwere gesundheitliche Schäden zu befürchten sind.", correct: true },
    { text: "Jede Person mit ärztlich verordneter Krankenfahrt unabhängig vom Zustand." },
    { text: "Ein aktuell kompensierter Patient, bei dem ohne unverzügliche Versorgung ein schwerer Gesundheitsschaden droht.", correct: true },
    { text: "Jede hilfsbedürftige Person allein wegen fehlender eigener Transportmöglichkeit." },
  ], source: "§ 3 Abs. 2 ThürRettG stellt auf Lebensgefahr oder zu befürchtende schwere gesundheitliche Schäden bei Verletzten oder Erkrankten ab.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-22", prompt: "Welche Fallzuordnungen grenzen Krankentransport und Krankenfahrt nach dem ThürRettG korrekt ab?", options: [
    { text: "Während der Fahrt ist fachgerechte medizinische Betreuung erforderlich: Krankentransport.", correct: true },
    { text: "Ein besonders ausgestattetes Rettungsmittel ist wegen des Zustands erforderlich: Krankentransport.", correct: true },
    { text: "Es sind weder fachgerechte Betreuung/Hilfeleistung noch ein Rettungsmittel erforderlich: Krankenfahrt.", correct: true },
    { text: "Der Zielort Krankenhaus macht jede Beförderung automatisch zum Krankentransport." },
    { text: "Die ärztliche Beurteilung des Betreuungs- und Transportbedarfs ist für die gesetzliche Abgrenzung bedeutsam.", correct: true },
  ], source: "Entscheidend ist der medizinische Betreuungs- beziehungsweise Rettungsmittelbedarf, nicht allein Zielort oder Diagnose.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-23", prompt: "Welche Aussagen zu den Aufgabenträgern des Rettungsdienstes in Thüringen treffen zu?", options: [
    { text: "Landkreise sind grundsätzlich Aufgabenträger des bodengebundenen Rettungsdienstes.", correct: true },
    { text: "Kreisfreie Städte sind grundsätzlich Aufgabenträger des bodengebundenen Rettungsdienstes.", correct: true },
    { text: "Rettungsdienstzweckverbände können die Trägerfunktion übernehmen.", correct: true },
    { text: "Jede einzelne Rettungswache ist kraft Gesetzes selbstständiger Aufgabenträger." },
    { text: "Die Durchführung durch eine Hilfsorganisation macht diese automatisch zum gesetzlichen Aufgabenträger." },
  ], source: "Aufgabenträgerschaft und praktische Durchführung sind zu trennen. Träger sind grundsätzlich Landkreise, kreisfreie Städte oder Rettungsdienstzweckverbände.", difficulty: 2, mode: "multiple" },
  { id: "recht-q-24", prompt: "Ein angefahrenes Krankenhaus meldet fehlende Betten und eingeschränkte personelle Kapazität. Welche Aussagen zu § 18 ThürKHG sind vertretbar?", options: [
    { text: "Die Pflicht zur Notaufnahme entfällt durch einen Kapazitätsengpass nicht automatisch.", correct: true },
    { text: "Eine ausreichende Erstversorgung muss in jedem Fall abgesichert werden.", correct: true },
    { text: "Weiterführende Maßnahmen müssen so weit erfolgen, dass eine Verlegung keine Patientengefährdung erwarten lässt.", correct: true },
    { text: "Das Krankenhaus muss unabhängig von Versorgungsauftrag und Leistungsfähigkeit jede denkbare Spezialbehandlung dauerhaft vorhalten." },
    { text: "Die Aufnahme- und Versorgungspflicht besteht vorrangig im Rahmen von Versorgungsauftrag und Leistungsfähigkeit.", correct: true },
  ], source: "§ 18 ThürKHG verbindet vorrangige Notfallversorgung mit Versorgungsauftrag und Leistungsfähigkeit; Engpässe beseitigen nicht die Pflicht zu Notaufnahme und sicherer Erstversorgung.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-25", prompt: "Welche Aussagen grenzen § 18 ThürKHG und § 323c StGB korrekt voneinander ab?", options: [
    { text: "§ 18 ThürKHG regelt speziell die Aufnahme und Behandlung von Notfallpatienten durch Krankenhäuser in Thüringen.", correct: true },
    { text: "§ 323c StGB erfasst allgemein unterlassene erforderliche und zumutbare Hilfe bei Unglücksfällen, gemeiner Gefahr oder Not.", correct: true },
    { text: "§ 323c StGB ist die alleinige organisationsrechtliche Grundlage jedes Thüringer Krankenhausversorgungsauftrags." },
    { text: "Bei einer Abweisung können neben krankenhausrechtlichen Folgen je nach Fall weitere straf- oder haftungsrechtliche Fragen entstehen.", correct: true },
    { text: "Eine nicht erfüllbare oder unzumutbare Hilfeleistung ist nach § 323c StGB stets strafbar." },
  ], source: "Spezielle landesrechtliche Aufnahmepflicht und allgemeine strafrechtliche Hilfeleistungspflicht sind getrennt zu prüfen.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-26", prompt: "Welche Voraussetzungen müssen für die Erteilung der Erlaubnis zum Führen der Berufsbezeichnung Notfallsanitäter nach § 2 Abs. 1 NotSanG vorliegen?", options: [
    { text: "Die vorgeschriebene Ausbildungszeit wurde abgeleistet und die staatliche Prüfung bestanden.", correct: true },
    { text: "Es bestehen keine Tatsachen, aus denen sich Unzuverlässigkeit zur Berufsausübung ergibt.", correct: true },
    { text: "Die Person ist gesundheitlich nicht ungeeignet.", correct: true },
    { text: "Die erforderlichen Kenntnisse der deutschen Sprache liegen vor.", correct: true },
    { text: "Eine mindestens fünfjährige Tätigkeit als Rettungssanitäter ist immer zwingend." },
  ], source: "§ 2 Abs. 1 NotSanG nennt Ausbildung und Prüfung, Zuverlässigkeit, gesundheitliche Eignung und erforderliche Deutschkenntnisse.", difficulty: 2, mode: "multiple" },
  { id: "recht-q-27", prompt: "Welche Aussagen zu Rücknahme, Widerruf und Verzicht bei der NotSan-Erlaubnis sind richtig?", options: [
    { text: "Fehlte eine Voraussetzung nach § 2 Abs. 1 Nr. 1 bis 3 bereits bei Erteilung, ist eine Rücknahme vorgesehen.", correct: true },
    { text: "Fällt die Zuverlässigkeit später weg, ist die Erlaubnis zu widerrufen.", correct: true },
    { text: "Bei später weggefallener gesundheitlicher Eignung kann die Erlaubnis widerrufen werden.", correct: true },
    { text: "Jede einzelne Berufspflichtverletzung beendet die Erlaubnis automatisch ohne behördliche Entscheidung." },
    { text: "Ein Verzicht auf die Erlaubnis ist rechtlich vorgesehen und wird im Vorwarnmechanismus ausdrücklich erfasst.", correct: true },
  ], source: "§ 2 Abs. 2 NotSanG unterscheidet Rücknahme und Widerruf. Pflichtverletzungen sind nur insoweit relevant, wie sie gesetzliche Voraussetzungen wie Zuverlässigkeit betreffen.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-28", prompt: "Welche Angaben gehören nach § 12 Abs. 2 NotSanG mindestens in den Ausbildungsvertrag?", options: [
    { text: "Beginn und Dauer der Ausbildung sowie die Berufsbezeichnung.", correct: true },
    { text: "Regelmäßige Arbeitszeit, Probezeit, Vergütung und Urlaub.", correct: true },
    { text: "Ausbildungs- und Prüfungsverordnung sowie inhaltliche und zeitliche Gliederung der praktischen Ausbildung.", correct: true },
    { text: "Kündigungsvoraussetzungen und zugrunde liegende tarifliche Bestimmungen oder Dienstvereinbarungen.", correct: true },
    { text: "Eine Garantie der späteren unbefristeten Übernahme." },
  ], source: "§ 12 Abs. 2 NotSanG nennt neun Mindestbestandteile. Eine Übernahmegarantie gehört nicht dazu.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-29", prompt: "Welche Aussagen zur Probezeit in der Notfallsanitäterausbildung treffen zu?", options: [
    { text: "Die Probezeit beträgt nach § 16 NotSanG vier Monate.", correct: true },
    { text: "Während der Probezeit kann jede Vertragspartei jederzeit ohne Kündigungsfrist kündigen.", correct: true },
    { text: "Nach der Probezeit gelten besondere gesetzliche Anforderungen an die Kündigung.", correct: true },
    { text: "Die Probezeit kann im Ausbildungsvertrag vollständig weggelassen werden, obwohl § 12 ihre Angabe verlangt." },
    { text: "Die Probezeit beträgt für jede NotSan-Ausbildung zwingend sechs Monate." },
  ], source: "§§ 12, 16 und 18 NotSanG regeln Vertragsangabe, viermonatige Probezeit und Kündigung.", difficulty: 2, mode: "multiple" },
  { id: "recht-q-30", prompt: "Welche Aussagen beschreiben zentrale Patientenrechte nach §§ 630a bis 630h BGB?", options: [
    { text: "Die Behandlung muss grundsätzlich dem anerkannten fachlichen Standard zum Behandlungszeitpunkt entsprechen.", correct: true },
    { text: "Eine wirksame Einwilligung setzt grundsätzlich vorherige verständliche Aufklärung voraus.", correct: true },
    { text: "Wesentliche Befunde, Maßnahmen, Wirkungen, Einwilligungen und Aufklärungen sind zeitnah zu dokumentieren.", correct: true },
    { text: "Patienten haben grundsätzlich Anspruch auf Einsicht in ihre vollständige Behandlungsakte.", correct: true },
    { text: "Einwilligungen sind nach Erklärung bis zum Behandlungsende unwiderruflich." },
  ], source: "Das Patientenrechtegesetz bündelt fachlichen Standard, Einwilligung, Aufklärung, Dokumentation, Einsicht und Beweislastregeln im BGB.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-31", prompt: "Welche Aussagen zur Dokumentation einer präklinischen Behandlung sind rechtlich und praktisch tragfähig?", options: [
    { text: "Sie soll in unmittelbarem zeitlichen Zusammenhang mit der Behandlung erfolgen.", correct: true },
    { text: "Berichtigungen müssen den ursprünglichen Inhalt und den Zeitpunkt der Änderung erkennbar lassen.", correct: true },
    { text: "Wesentliche Befunde, Maßnahmen, Dosierungen, Wirkungen sowie Einwilligung oder Ablehnung gehören hinein.", correct: true },
    { text: "Nicht dokumentierte wesentliche Maßnahmen können beweisrechtlich als nicht durchgeführt vermutet werden.", correct: true },
    { text: "Eine nachträgliche unkenntliche Löschung falscher Einträge ist rechtlich vorzugswürdig." },
  ], source: "§§ 630f und 630h BGB verbinden zeitnahe, änderungssichere Dokumentation mit beweisrechtlichen Folgen.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-32", prompt: "Welche Verfassungsgrundsätze schützt die Ewigkeitsgarantie des Art. 79 Abs. 3 GG vor einer abschaffenden Verfassungsänderung?", options: [
    { text: "Die Gliederung des Bundes in Länder.", correct: true },
    { text: "Die grundsätzliche Mitwirkung der Länder bei der Gesetzgebung.", correct: true },
    { text: "Die in Art. 1 GG niedergelegte Menschenwürdegarantie und Grundrechtsbindung.", correct: true },
    { text: "Die in Art. 20 GG niedergelegten tragenden Strukturprinzipien.", correct: true },
    { text: "Jede einzelne Vorschrift des Grundgesetzes in ihrem aktuellen Wortlaut." },
  ], source: "Art. 79 Abs. 3 GG schützt die genannten Struktur- und Verfassungsgrundsätze, nicht unveränderlich jeden einzelnen Verfassungssatz.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-33", prompt: "Ein Patient mit möglichem zeitkritischem Notfall soll in ein Krankenhaus gebracht werden, das eingeschränkte Kapazität meldet. Welche rechtlichen Prüfschritte sind sinnvoll?", options: [
    { text: "Die medizinische Eignung des Zielkrankenhauses und den Versorgungsauftrag berücksichtigen.", correct: true },
    { text: "Die Notaufnahme- und Erstversorgungspflicht nach § 18 ThürKHG von der planbaren Weiterbehandlung unterscheiden.", correct: true },
    { text: "Eine mögliche Weiterverlegung darf erst erfolgen, wenn eine Patientengefährdung dadurch nicht zu erwarten ist.", correct: true },
    { text: "Kapazitätsmeldung und medizinisch-organisatorische Abstimmung nachvollziehbar dokumentieren.", correct: true },
    { text: "Eine Kapazitätsmeldung berechtigt das Rettungsteam stets, jede weitere Versorgung ohne Ersatzlösung zu beenden." },
  ], source: "Präklinisch sind medizinische Eignung, Versorgungsauftrag, Notaufnahme, sichere Erstversorgung, Verlegungsfähigkeit und nachvollziehbare Kommunikation zusammenzuführen.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-34", prompt: "Welche Zuordnungen der Unterbringungsarten sind rechtlich zutreffend?", options: [
    { text: "Eine krankheitsbedingte gegenwärtige erhebliche Eigen- oder Fremdgefährdung kann den öffentlich-rechtlichen Weg nach ThürPsychKG eröffnen.", correct: true },
    { text: "Eine Betreuung mit ausdrücklich angeordnetem Aufgabenbereich kann unter den Voraussetzungen des § 1831 BGB für den zivilrechtlichen Weg bedeutsam sein.", correct: true },
    { text: "Die Unterbringung nach §§ 63 oder 64 StGB ist eine gerichtlich angeordnete strafrechtliche Maßregel nach einer rechtswidrigen Tat.", correct: true },
    { text: "Jede der drei Unterbringungsarten darf allein durch das Rettungsteam ohne Beteiligung weiterer Stellen angeordnet werden." },
    { text: "Eine strafrechtliche Unterbringung ersetzt im akuten Einsatz automatisch die Gefahrenprüfung nach dem ThürPsychKG." },
  ], source: "Öffentlich-rechtlicher Gefahrenabwehrweg, betreuungsrechtlicher Schutzweg und strafrechtliche Maßregel haben unterschiedliche Voraussetzungen, Akteure und Verfahren.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-35", prompt: "Ein psychotischer Patient kündigt konkret an, sich unmittelbar das Leben zu nehmen. Welche Aussagen zur öffentlich-rechtlichen Unterbringung in Thüringen sind richtig?", options: [
    { text: "Die Gefahr muss infolge der psychischen Erkrankung bestehen und gegenwärtig sein.", correct: true },
    { text: "Es ist zu prüfen, ob die Gefahr durch ein milderes Mittel abgewendet werden kann.", correct: true },
    { text: "Kann eine gerichtliche Entscheidung nicht rechtzeitig erreicht werden, darf der Sozialpsychiatrische Dienst bei dringenden Anhaltspunkten vorläufig anordnen.", correct: true },
    { text: "Die vorläufige Anordnung nach § 9 ThürPsychKG gilt höchstens 24 Stunden ab Beginn; der gerichtliche Antrag ist unverzüglich zu stellen.", correct: true },
    { text: "Allein die Ablehnung einer empfohlenen Behandlung erfüllt stets die Voraussetzungen des § 7 ThürPsychKG." },
  ], source: "§§ 7 bis 9 ThürPsychKG verlangen eine krankheitsbedingte gegenwärtige erhebliche Gefahr, fehlende mildere Mittel und ein gesetzlich geregeltes Verfahren.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-36", prompt: "Ein Betreuer fordert, eine Patientin gegen ihren Willen in eine geschlossene Einrichtung zu bringen. Welche Prüfungen sind erforderlich?", options: [
    { text: "Der konkrete gerichtlich angeordnete Aufgabenbereich des Betreuers muss die freiheitsentziehende Unterbringung ausdrücklich umfassen.", correct: true },
    { text: "Die materiellen Voraussetzungen des § 1831 BGB müssen erfüllt sein.", correct: true },
    { text: "Grundsätzlich ist die Genehmigung des Betreuungsgerichts erforderlich.", correct: true },
    { text: "Bei Gefahr durch Aufschub kann ohne vorherige Genehmigung gehandelt werden; die Genehmigung ist unverzüglich nachzuholen.", correct: true },
    { text: "Die bloße Betreuerbestellung für Vermögensangelegenheiten erlaubt jede freiheitsentziehende Maßnahme." },
  ], source: "Betreuung ist keine Generalvollmacht. Aufgabenbereich, Voraussetzungen des § 1831 BGB und gerichtliche Genehmigung sind jeweils gesondert zu prüfen.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-37", prompt: "Welche Aussagen zur Fixierung und zu freiheitsentziehenden Maßnahmen sind richtig?", options: [
    { text: "Ein Unterbringungsbeschluss erlaubt nicht automatisch eine zusätzliche Fixierung.", correct: true },
    { text: "Bei einer nicht nur kurzfristigen Fixierung besteht grundsätzlich ein Richtervorbehalt.", correct: true },
    { text: "Eine absehbar weniger als 30 Minuten dauernde Fixierung gilt nach dem ThürPsychKG in der Regel als kurzfristig.", correct: true },
    { text: "Ortungschip und Sensormatte sind allein durch ihre Überwachungsfunktion stets Freiheitsentziehungen." },
    { text: "Präklinischer Zwang braucht eine eigenständige Rechtsgrundlage und muss als mildestes geeignetes Mittel erforderlich und verhältnismäßig sein.", correct: true },
  ], source: "Unterbringung, Fixierung und bloße Überwachung sind zu trennen. Entscheidend sind Rechtsgrundlage, tatsächliche Wirkung, Erforderlichkeit, Richtervorbehalt und Sicherungspflichten.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-38", prompt: "Ein Patient wird präklinisch gegen seinen natürlichen Willen an der Trage festgehalten. Welche rechtlichen Aussagen sind richtig?", options: [
    { text: "Die Maßnahme kann den Tatbestand der Freiheitsberaubung nach § 239 StGB erfüllen.", correct: true },
    { text: "Eine wirksame Einwilligung oder eine andere tragfähige Rechtfertigung muss gesondert geprüft werden.", correct: true },
    { text: "§ 34 StGB setzt eine gegenwärtige, nicht anders abwendbare Gefahr und eine Interessenabwägung voraus.", correct: true },
    { text: "Die bloße Diagnose einer psychischen Erkrankung rechtfertigt das Festhalten unabhängig von einer konkreten Gefahr." },
    { text: "Ein bestehender Unterbringungsbeschluss macht jede Art und Dauer einer Fixierung automatisch rechtmäßig." },
  ], source: "Freiheitsentziehung ist tatbestandsmäßig von ihrer möglichen Rechtfertigung zu trennen. Diagnose oder Unterbringung ersetzen nicht die Prüfung des konkreten Zwangsmittels.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-39", prompt: "Welche Rechtsnormen sind für die Bearbeitung eines Falles zum Thüringer Rettungsdienstrecht unmittelbar einschlägig?", options: [
    { text: "Das ThürRettG regelt insbesondere Aufgaben, Begriffe und Aufgabenträger des Rettungsdienstes in Thüringen.", correct: true },
    { text: "Das NotSanG regelt unter anderem Berufsbezeichnung, Ausbildung und heilkundliche Befugnisse von Notfallsanitätern.", correct: true },
    { text: "Das ThürKHG kann für die Aufnahme und Versorgung eines Notfallpatienten durch ein Krankenhaus relevant sein.", correct: true },
    { text: "Die StVO ist die alleinige Rechtsgrundlage für Berufsbezeichnung und Krankenhausaufnahme." },
    { text: "Örtliche Dienstanweisungen stehen im Rang über Bundes- und Landesgesetzen." },
  ], source: "Prüfungsvorbereitung nach dem Fallbeispiel Rettungsdienstrecht Thüringen: Die einschlägige Norm richtet sich nach der Teilfrage; Organisations-, Berufs- und Krankenhausrecht sind zu trennen.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-40", prompt: "Bei welchen Konstellationen liegt nach § 3 Abs. 2 ThürRettG ein Notfallpatient vor?", options: [
    { text: "Eine Verletzte befindet sich aktuell in Lebensgefahr.", correct: true },
    { text: "Bei einem Erkrankten sind ohne sofortige Versorgung schwere gesundheitliche Schäden zu befürchten.", correct: true },
    { text: "Eine äußerlich stabile Patientin ist wegen einer zeitkritischen inneren Blutung von schweren Gesundheitsschäden bedroht.", correct: true },
    { text: "Eine Person benötigt ausschließlich eine Beförderungsmöglichkeit, medizinische Gefahren bestehen nicht." },
    { text: "Jede ärztlich verordnete Beförderung ist unabhängig vom Gesundheitszustand Notfallrettung." },
  ], source: "Der Begriff knüpft an Lebensgefahr oder zu befürchtende schwere gesundheitliche Schäden an. Sichtbare Instabilität ist keine zwingende Voraussetzung.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-41", prompt: "Vier Patienten sollen befördert werden. Welche Zuordnungen sind rechtlich tragfähig?", options: [
    { text: "Kontinuierliche fachgerechte medizinische Betreuung während der Fahrt erforderlich: Krankentransport.", correct: true },
    { text: "Ein besonders ausgestattetes Rettungsmittel ist aufgrund des Zustands voraussichtlich erforderlich: Krankentransport.", correct: true },
    { text: "Weder fachgerechte Betreuung noch ein Rettungsmittel sind erforderlich: Krankenfahrt.", correct: true },
    { text: "Der Zielort ist eine Arztpraxis; deshalb handelt es sich zwingend um eine Krankenfahrt." },
    { text: "Eine Krankenhausentlassung schließt einen Krankentransport grundsätzlich aus." },
  ], source: "Nicht Zielort oder Anlass entscheiden, sondern der nach ärztlicher Beurteilung bestehende Betreuungs- und Rettungsmittelbedarf.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-42", prompt: "Welche Zuordnungen der Aufgabenträgerschaft im Thüringer Rettungsdienst sind richtig?", options: [
    { text: "Landkreise und kreisfreie Städte tragen grundsätzlich den bodengebundenen Rettungsdienst einschließlich Berg- und Wasserrettung.", correct: true },
    { text: "Ein Rettungsdienstzweckverband kann die kommunale Aufgabenträgerschaft wahrnehmen.", correct: true },
    { text: "Die Kassenärztliche Vereinigung Thüringen ist Aufgabenträgerin der notärztlichen Versorgung im bodengebundenen Rettungsdienst.", correct: true },
    { text: "Der Freistaat Thüringen ist Aufgabenträger der Luftrettung.", correct: true },
    { text: "Eine beauftragte Hilfsorganisation wird allein durch die Durchführung automatisch gesetzlicher Aufgabenträger." },
  ], source: "Aufgabenträgerschaft und Durchführung sind zu unterscheiden. § 5 ThürRettG verteilt bodengebundenen Rettungsdienst, notärztliche Versorgung und Luftrettung auf unterschiedliche Träger.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-43", prompt: "Ein zeitkritischer Notfallpatient erreicht ein geeignetes Thüringer Krankenhaus, dessen Notaufnahme eine Kapazitätsabmeldung gemeldet hat. Welche Aussagen sind richtig?", options: [
    { text: "Eine Kapazitätsabmeldung beseitigt die Pflicht zur Notaufnahme nicht automatisch.", correct: true },
    { text: "Versorgungsauftrag und tatsächliche Leistungsfähigkeit des Krankenhauses bleiben zu berücksichtigen.", correct: true },
    { text: "Mindestens eine ausreichende Erstversorgung und eine gefahrlose Weiterverlegung müssen abgesichert werden.", correct: true },
    { text: "Eine Verweigerung kann neben § 18 ThürKHG weitere haftungs- oder strafrechtliche Fragen auslösen.", correct: true },
    { text: "Jede Kapazitätsabmeldung verpflichtet den Rettungsdienst ohne medizinische Abwägung zur sofortigen Weiterfahrt." },
  ], source: "§ 18 ThürKHG verpflichtet im Rahmen von Versorgungsauftrag und Leistungsfähigkeit zur vorrangigen Notfallversorgung; organisatorische Meldungen ersetzen keine Einzelfallprüfung.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-44", prompt: "Ein Arbeitgeber droht einem Notfallsanitäter nach einem Konflikt mit dem ÄLRD, ihm die Berufsbezeichnung zu entziehen. Welche Aussagen treffen zu?", options: [
    { text: "Der Arbeitgeber kann die staatliche Erlaubnis nicht durch eine arbeitsrechtliche Erklärung zurücknehmen oder widerrufen.", correct: true },
    { text: "Über Erteilung, Rücknahme und Widerruf entscheidet die zuständige Behörde nach den gesetzlichen Voraussetzungen.", correct: true },
    { text: "Eine Pflichtverletzung kann Tatsachen liefern, aus denen sich fehlende Zuverlässigkeit ergibt, beendet die Erlaubnis aber nicht automatisch.", correct: true },
    { text: "Der ÄLRD kann die staatliche Berufsbezeichnung jederzeit ohne Verwaltungsverfahren aberkennen." },
    { text: "Arbeitsrechtliche Folgen und berufsrechtlicher Erlaubnisstatus sind getrennt zu prüfen.", correct: true },
  ], source: "Die Erlaubnis zum Führen der Berufsbezeichnung ist ein staatlicher Status. Arbeitgeber- oder ÄLRD-Entscheidungen ersetzen keine behördliche Entscheidung nach dem NotSanG.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-45", prompt: "Eine Absolventin beantragt die Erlaubnis zum Führen der Berufsbezeichnung. Welche Voraussetzungen müssen zusammen geprüft werden?", options: [
    { text: "Vorgeschriebene Ausbildungszeit und bestandene staatliche Prüfung.", correct: true },
    { text: "Zuverlässigkeit zur Berufsausübung.", correct: true },
    { text: "Gesundheitliche Eignung zur Berufsausübung.", correct: true },
    { text: "Erforderliche Kenntnisse der deutschen Sprache.", correct: true },
    { text: "Zwingende Zustimmung des späteren Arbeitgebers oder des örtlichen ÄLRD." },
  ], source: "§ 2 Abs. 1 NotSanG nennt vier Voraussetzungen. Eine Zustimmung des Arbeitgebers oder ÄLRD gehört nicht dazu.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-46", prompt: "Welche Fallkonstellationen sind bei einer bereits erteilten NotSan-Erlaubnis rechtlich korrekt zugeordnet?", options: [
    { text: "Eine relevante Voraussetzung fehlte bereits bei Erteilung: Rücknahme ist zu prüfen.", correct: true },
    { text: "Die erforderliche Zuverlässigkeit fällt erst später weg: Die Erlaubnis ist zu widerrufen.", correct: true },
    { text: "Die gesundheitliche Eignung fällt erst später weg: Die Erlaubnis kann widerrufen werden.", correct: true },
    { text: "Eine einzelne Meinungsverschiedenheit mit dem Arbeitgeber: Die Erlaubnis erlischt unmittelbar." },
    { text: "Eine arbeitsrechtliche Kündigung und der Fortbestand der staatlichen Erlaubnis sind eigenständig zu beurteilen.", correct: true },
  ], source: "§ 2 Abs. 2 NotSanG unterscheidet nach dem Zeitpunkt und der betroffenen Voraussetzung zwischen Rücknahme sowie zwingendem oder möglichem Widerruf.", difficulty: 3, mode: "multiple" },
  { id: "recht-q-47", prompt: "Welche Vorgehensweise eignet sich für eine strukturierte Prüfung eines rettungsdienstrechtlichen Falles in Thüringen?", options: [
    { text: "Zuerst den Sachverhalt und die konkrete Rechtsfrage trennen: Organisation, Patientenstatus, Transport, Krankenhaus oder Berufsrecht.", correct: true },
    { text: "Anschließend die einschlägige Rechtsgrundlage und deren Tatbestandsvoraussetzungen benennen.", correct: true },
    { text: "Den Sachverhalt unter die Voraussetzungen einordnen und Rechtsfolgen sowie Zuständigkeiten ableiten.", correct: true },
    { text: "Ähnliche Begriffe wie Krankenfahrt und Krankentransport ausdrücklich voneinander abgrenzen.", correct: true },
    { text: "Die gewünschte praktische Lösung zuerst festlegen und danach eine beliebige Norm als Begründung auswählen." },
  ], source: "Prüfungsschema: Rechtsfrage erkennen → Norm benennen → Voraussetzungen definieren → Sachverhalt zuordnen → Rechtsfolge und Zuständigkeit begründen.", difficulty: 3, mode: "multiple" },
];

export const rechtskundeQuestions: LegalQuestion[] = [...rechtskundeBaseQuestions, ...supplementalQuestions.rechtskunde];
