import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";
type Option = [string, boolean];
function q(n: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  const shift = n % options.length;
  return { id: `rippenfraktur-q-${String(n).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty };
}

export const rippenfrakturQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Nach einem Sturz sind drei benachbarte Rippen jeweils einfach gebrochen. Welche Einordnungen treffen zu?", [["Es liegt eine Rippenserienfraktur vor", true], ["Ein freies Thoraxsegment ist damit bereits bewiesen", false], ["Schmerzbedingte Minderventilation bleibt möglich", true], ["Ein Pneumothorax ist bei einfachen Brüchen ausgeschlossen", false], ["Die Atemfunktion muss im Verlauf kontrolliert werden", true]], "Eine Serienfraktur betrifft mindestens drei benachbarte Rippen. Ein freies Segment erfordert zusätzliche Unterbrechungen; Atemstörungen sind dennoch möglich.", 2),
  q(2, "Welche anatomischen Aussagen erklären die Stabilität und Beweglichkeit des Thorax?", [["Die Rippen 1–7 sind über eigenen Knorpel sternal verbunden", true], ["Die Rippen 11/12 besitzen kein Rippen-Querfortsatz-Gelenk", true], ["Die Rippen 8–10 sind vorn völlig unverbunden", false], ["Die Rippen 11/12 enden mit Knorpel in der Bauchwand", true], ["Jede Rippe besitzt zwei Gelenke zur Brustwirbelsäule", false]], "Rippen 8–10 sind indirekt über den Rippenbogen verbunden; 11/12 haben weder Sternumkontakt noch ein Costotransversalgelenk.", 2),
  q(3, "Welche Aussagen zur Pleura passen zur Atemmechanik?", [["Die Pleura visceralis haftet der Lunge fest an", true], ["Der Flüssigkeitsfilm ermöglicht reibungsarmes Gleiten", true], ["Die Pleura parietalis ist weitgehend schmerzunempfindlich", false], ["Luft im Pleuraspalt kann die mechanische Kopplung stören", true], ["Der Pleuraspalt ist physiologisch ein luftgefüllter Raum", false]], "Lungenfell, schmerzempfindliches Rippenfell und Flüssigkeitsfilm ermöglichen die Kopplung; ein Pneumothorax stört sie.", 2),
  q(4, "Eine Patientin atmet nach Thoraxaufprall flach, NRS 8. Welche Zusammenhänge sind schlüssig?", [["Schmerz kann die Inspiration begrenzen", true], ["Schonatmung kann die Belüftung vermindern", true], ["Ein normaler erster SpO₂-Wert schließt eine Kontusion aus", false], ["Wirksame Analgesie kann die Atemmechanik verbessern", true], ["Allein die Schmerzstärke quantifiziert den Blutverlust", false]], "Atemabhängiger Schmerz fördert Schonatmung. Begleitverletzungen und spätere Verschlechterung bleiben trotz anfänglich normaler Sättigung möglich.", 2),
  q(5, "Welche Befunde gelten als unsichere Frakturzeichen?", [["Lokaler Schmerz", true], ["Hämatom und Schwellung", true], ["Abnorme knöcherne Beweglichkeit", false], ["Schmerzbedingter Funktionsverlust", true], ["Aus der Wunde sichtbare Knochenfragmente", false]], "Schmerz, Hämatom, Schwellung und Funktionsverlust sind unsicher. Sichtbare Fragmente und abnorme Beweglichkeit gehören zu den sicheren Zeichen.", 2),
  q(6, "Bei der Thoraxuntersuchung ist eine Krepitation tastbar. Welche Schlussfolgerungen sind angemessen?", [["Subkutane Luft kann ebenfalls ein Knistern verursachen", true], ["Knochenreiben und Hautemphysem sind zu unterscheiden", true], ["Kräftige wiederholte Kompression sichert die Diagnose schonend", false], ["Der Befund rechtfertigt eine erneute Atembeurteilung", true], ["Hautemphysem beweist einen hämorrhagischen Schock", false]], "Knistern ist nicht automatisch knöcherne Krepitation. Keine Provokation; respiratorische Begleitverletzungen prüfen.", 2),
  q(7, "Welche Befund-Risiko-Zuordnungen passen bei Rippenfrakturen?", [["Obere Rippen: mögliche schwere intrathorakale Begleitverletzung", true], ["Untere linke Rippen: mögliche Milzverletzung", true], ["Untere rechte Rippen: mögliche Leberverletzung", true], ["Mittlere Rippen: ausschließlich lokale Weichteilverletzung", false], ["Frakturhöhe: verlässlicher Ausschluss anderer Organverletzungen", false]], "Die Höhe lenkt die Suche, ersetzt aber nicht die vollständige Traumabeurteilung.", 2),
  q(8, "Welche Aussagen zu Frakturbegriffen sind korrekt?", [["Eine geschlossene Fraktur kann erhebliche Weichteilschäden haben", true], ["Eine dislozierte Fraktur beschreibt verschobene Fragmente", true], ["Eine offene Fraktur setzt eine sichtbare Knochenfreilegung voraus", false], ["Grünholz bezeichnet eine unvollständige kindliche Biegungsfraktur", true], ["Trümmerfraktur und offene Fraktur sind gleichbedeutend", false]], "Offen bedeutet Verbindung zur Außenwelt; sichtbarer Knochen ist nicht erforderlich. Form, Dislokation und Hautstatus sind getrennte Merkmale.", 2),
  q(9, "Drei benachbarte Rippen sind jeweils an zwei Stellen gebrochen. Welche Befunde oder Konsequenzen passen?", [["Ein freies Thoraxwandsegment kann entstehen", true], ["Bei Spontanatmung kann das Segment inspiratorisch einwärts treten", true], ["Paradoxe Atmung muss bei jeder Untersuchung sichtbar sein", false], ["Eine begleitende Lungenkontusion kann die Atmung zusätzlich stören", true], ["Das Segment muss präklinisch durch starke Kompression geprüft werden", false]], "Das instabile Segment kann paradoxe Bewegung zeigen. Sichtbarkeit variiert; Lungenkontusion und Schmerz beeinflussen die Atemfunktion.", 3),
  q(10, "Nach einem Thoraxtrauma ist das linke Atemgeräusch abgeschwächt, der Kreislauf stabil. Welche Aussagen sind richtig?", [["Ein Pneumothorax gehört zur Arbeitsdiagnose", true], ["Engmaschige klinische Verlaufskontrollen sind erforderlich", true], ["Die Befundkombination erfüllt bereits vollständig VFA 07", false], ["Ein Hämatothorax ist ebenfalls zu bedenken", true], ["Ein stabiler Blutdruck schließt jede Pleuraverletzung aus", false]], "Abgeschwächtes Atemgeräusch kann zu Pneumo- oder Hämatothorax passen. VFA 07 fordert zusätzlich hämodynamische Instabilität.", 3),
  q(11, "Ein Patient entwickelt nach Rippenfraktur zunehmende Dyspnoe, einseitig stark vermindertes Atemgeräusch und Hypotonie. Welche Überlegungen treffen zu?", [["Ein Spannungspneumothorax ist zeitkritisch zu berücksichtigen", true], ["Venöser Rückstrom und Herzfüllung können behindert sein", true], ["Ein hämorrhagischer Schock durch Blutung bleibt parallel möglich", true], ["Eine SpO₂-Messung muss die Eskalation bis zur Normalisierung verzögern", false], ["Hypotonie beweist eine isolierte Myokardkontusion", false]], "Spannung kann obstruktiven Schock auslösen. Blutung und andere Begleitverletzungen werden gleichzeitig berücksichtigt.", 3),
  q(12, "Welche Aussagen unterscheiden Hämatothorax und Spannungspneumothorax?", [["Beim Hämatothorax kann absoluter Blutvolumenverlust entstehen", true], ["Spannung kann den venösen Rückstrom mechanisch vermindern", true], ["Beide können die Atemfunktion beeinträchtigen", true], ["Eine Nadeldekompression behebt regelhaft den Blutverlust", false], ["Nur der Hämatothorax kann hämodynamisch relevant werden", false]], "Blutverlust und Füllungsbehinderung sind verschiedene Schockmechanismen; beide können mit Ventilationsstörung einhergehen.", 3),
  q(13, "Nach initial stabilen Werten sinkt die SpO₂ bei einem Patienten mit Thoraxaufprall. Welche Bewertungen sind sinnvoll?", [["Eine Lungenkontusion kann sich verzögert bemerkbar machen", true], ["Eine erneute Untersuchung muss einen Pneumothorax einbeziehen", true], ["Atemarbeit, Vigilanz und Kreislauf gehören zur Re-Evaluation", true], ["Der erste Normalbefund erlaubt den Ausschluss einer Thoraxverletzung", false], ["Die sinkende SpO₂ ist durch den Rippenbruch bereits ausreichend erklärt", false]], "Der Verlauf ist entscheidend; eine Verschlechterung verlangt neue Ursachenprüfung statt Festhalten am Erstbefund.", 3),
  q(14, "Welche Anamneseangaben beeinflussen die Versorgung einer älteren Patientin nach Thoraxsturz?", [["Antikoagulation", true], ["Vorbestehende Lungenerkrankung", true], ["Unfallmechanismus und zeitlicher Verlauf", true], ["Ein niedriger NRS ersetzt die Medikamentenanamnese", false], ["Eine normale SpO₂ macht die Herzvorgeschichte entbehrlich", false]], "Blutungsrisiko, respiratorische Reserve und Mechanismus beeinflussen Risiko und Versorgung.", 2),
  q(15, "NRS 7 nach Thoraxtrauma: Welche Schritte gehören zum Analgesiepfad der VFA 35?", [["Schmerzursache mit OPQRST ergründen", true], ["cABCDE und Begleitverletzungen berücksichtigen", true], ["Wirkstoffauswahl nach Vorgabe des zuständigen ÄLRD", true], ["Alleine anhand der NRS-Zahl Morphin zwingend bevorzugen", false], ["Ursachenbehandlung bis zur vollständigen Schmerzfreiheit aussetzen", false]], "VFA 35 verbindet NRS ≥ 5 mit Ursachenklärung, Basisversorgung und lokaler Wirkstoffauswahl.", 3),
  q(16, "Welche Aussagen zur Vorbereitung von Morphin nach B2A sind richtig?", [["10 mg in 1 ml werden mit 9 ml NaCl ergänzt", true], ["Die Endkonzentration beträgt 1 mg/ml", true], ["4 mg entsprechen bei dieser Zubereitung 4 ml", true], ["10 mg plus 10 ml NaCl ergeben ebenfalls 1 mg/ml", false], ["Die Ausgangsampulle darf mit 1 mg/ml verwechselt werden", false]], "1 ml Wirkstofflösung + 9 ml NaCl = 10 ml mit insgesamt 10 mg. Die unverdünnte Ampulle enthält 10 mg/ml.", 3),
  q(17, "Ein 80-kg-Erwachsener erhält Morphin nach VFA 38 bei 1 mg/ml. Welche Angaben stimmen?", [["Die Initialdosis beträgt laut Tabelle 4 mg", true], ["Die Initialdosis entspricht 4 ml", true], ["Nach 5 Minuten kann bei Bedarf eine halbe Dosis folgen", true], ["Die erste Wiederholungsdosis beträgt 4 mg", false], ["Die maximale Gesamtmenge beträgt 10 ml der unverdünnten Ampulle", false]], "Für 80 kg: initial 4 mg = 4 ml; halbe Dosis 2 mg. Maximal insgesamt 10 mg, nicht 10 ml unverdünnt.", 3),
  q(18, "Esketamin 50 mg/2 ml wird mit 8 ml NaCl aufgezogen. Für einen 70-kg-Erwachsenen werden 0,2 mg/kg berechnet. Welche Ergebnisse sind korrekt?", [["Endkonzentration 5 mg/ml", true], ["Initialdosis 14 mg beziehungsweise 2,8 ml", true], ["Halbe Initialdosis 7 mg beziehungsweise 1,4 ml", true], ["Endkonzentration 25 mg/ml", false], ["Initialdosis 7 mg beziehungsweise 2,8 ml", false]], "50 mg auf 10 ml ergeben 5 mg/ml. 70 × 0,2 = 14 mg; 14 ÷ 5 = 2,8 ml.", 3),
  q(19, "Welche Elemente gehören zum Erwachsenenpfad Esketamin nach VFA 36?", [["1 mg Midazolam i.v. vor Esketamin", true], ["Langsame Initialgabe von 0,2 mg/kg Esketamin i.v.", true], ["NRS-Kontrolle nach 5 Minuten", true], ["Repetition mit voller Initialdosis nach einer Minute", false], ["Verzicht auf Beatmungsbereitschaft bei erhaltener Spontanatmung", false]], "VFA 36 nennt Begleitmedikation, langsame Initialgabe, Kontrolle nach 5 Minuten und bei Bedarf halbe Initialdosis.", 3),
  q(20, "Nach Analgesie sinkt der NRS von 8 auf 3, gleichzeitig wird die Atmung flacher und die Vigilanz nimmt ab. Welche Entscheidungen passen?", [["Die Atemwegs- und Ventilationssituation erneut beurteilen", true], ["Medikamentenwirkung und Begleitverletzung als Ursachen prüfen", true], ["Weitere Gabe anhand des Gesamtbefunds neu bewerten", true], ["Die niedrigere NRS belegt einen insgesamt komplikationslosen Erfolg", false], ["Nur den Schmerzwert dokumentieren, da das Therapieziel erreicht ist", false]], "Analgesieerfolg ist nicht nur NRS-Senkung. Vigilanz und Atmung können eine gefährliche Verschlechterung anzeigen.", 3),
  q(21, "Welche Aussagen entsprechen der Thüringer VFA 07?", [["Thoraxtrauma mit einseitig abgeschwächtem Atemgeräusch und hämodynamischer Instabilität ist die Indikationskonstellation", true], ["Als Orte werden 2. ICR medioclavikulär oder 4./5. ICR vordere Axillarlinie genannt", true], ["Die Punktion erfolgt über den Rippenoberrand", true], ["Eine isolierte NRS 8 bei stabilem Kreislauf erfüllt die Indikation", false], ["Eine Kanüle von 3 cm erfüllt die angegebene Mindestlänge", false]], "VFA 07 nennt die klinische Kombination, beide Punktionsorte, Rippenoberrand und mindestens 6,5 cm Kanülenlänge.", 3),
  q(22, "Nach Entlastung bleibt ein Thoraxtraumapatient instabil. Welche Bewertungen sind angemessen?", [["Respiratorische und hämodynamische Wirkung getrennt prüfen", true], ["Differenzialdiagnosen und weitere Blutungsquellen prüfen", true], ["Monitoring und zeitkritischen Transport fortführen", true], ["Das Entweichen von Luft beweist die vollständige Stabilisierung", false], ["Eine einmalige Intervention macht Re-Evaluation entbehrlich", false]], "Die VFA fordert die Prüfung beider Stabilisierungskomponenten. Ein technischer Effekt ersetzt keine klinische Wirksamkeitskontrolle.", 3),
  q(23, "Eine Patientin hat linksseitige untere Rippenschmerzen, zunehmende Bauchschmerzen und Tachykardie. Welche Überlegungen sind richtig?", [["Eine Milzverletzung ist mitzudenken", true], ["Eine innere Blutung kann den Kreislauf verschlechtern", true], ["Thorax- und Abdomenbefund müssen gemeinsam beurteilt werden", true], ["Der lokalisierte Rippenschmerz erklärt den Kreislaufbefund hinreichend", false], ["Fehlende äußere Blutung spricht gegen relevanten Blutverlust", false]], "Untere Rippenfrakturen können mit abdominalen Organverletzungen einhergehen; äußerlich unauffällige Blutung schließt Schock nicht aus.", 3),
  q(24, "Nach Verkehrsunfall bestehen Rippenschmerz, zunehmende Dyspnoe und Hypotonie. Welche Prioritäten sind richtig?", [["cABCDE erneut durchführen und lebensbedrohliche Ursachen behandeln", true], ["Notarzt und geeignete Zielklinik früh einbinden", true], ["Mechanismus, Befundverlauf und Maßnahmen für die Übergabe sichern", true], ["Die genaue Anzahl gebrochener Rippen zuerst endgültig bestimmen", false], ["Weitere Diagnostik und Transport bis zum NRS 0 verschieben", false]], "Vitalbedrohung, zeitkritische Versorgung und strukturierte Übergabe haben Vorrang vor einer präklinisch nicht sicher möglichen Frakturklassifikation.", 3),
];

export const rippenfrakturFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "rippenfraktur-card-01", area: "Definition", question: "Grenzen Sie Rippenfraktur, Rippenserienfraktur und instabilen Thorax ab.", answer: "Fraktur: Bruch einer oder mehrerer Rippen. Serie: mindestens drei benachbarte Rippen. Instabiler Thorax: mindestens drei benachbarte Rippen jeweils an mindestens zwei Stellen gebrochen, sodass ein freies Segment entstehen kann." },
  { id: "rippenfraktur-card-02", area: "Anatomie", question: "Erklären Sie Sternumverbindung und Besonderheiten der Rippen 1–7, 8–10 und 11–12.", answer: "1–7 über eigenen Knorpel direkt zum Sternum; 8–10 indirekt über den Rippenbogen; 11–12 mit Knorpelenden in der Bauchwand ohne Sternumverbindung und ohne Rippen-Querfortsatz-Gelenk." },
  { id: "rippenfraktur-card-03", area: "Pleura", question: "Wie wirken Pleurablätter, Flüssigkeitsfilm und intrapleuraler Druck bei der Atmung zusammen?", answer: "Viszerale Pleura haftet der Lunge an, parietale Pleura kleidet Thoraxwand/Zwerchfell aus und ist schmerzempfindlich. Flüssigkeitsfilm ermöglicht Gleiten; normalerweise negativer Druck unterstützt die Kopplung von Lunge und Thorax." },
  { id: "rippenfraktur-card-04", area: "Pathophysiologie", question: "Begründen Sie, weshalb ein Rippenbruch ohne Pneumothorax trotzdem respiratorisch relevant sein kann.", answer: "Atemabhängiger Schmerz verursacht Schonatmung und geringere Ventilation. Eine begleitende Lungenkontusion kann den Gasaustausch zusätzlich und auch verzögert verschlechtern." },
  { id: "rippenfraktur-card-05", area: "Frakturzeichen", question: "Unterscheiden Sie sichere und unsichere Frakturzeichen und erklären Sie die Untersuchungsgrenze.", answer: "Unsicher: Schmerz, Hämatom, Schwellung, Funktionsverlust. Sicher: abnorme Beweglichkeit, Knochenreiben, Fehlstellung, sichtbare Fragmente. Keine provozierende Kompression; Hautemphysem kann ebenfalls knistern." },
  { id: "rippenfraktur-card-06", area: "Frakturhöhe", question: "Welche Begleitverletzungen suchen Sie bei oberen, mittleren und unteren Rippenfrakturen?", answer: "Oben bei relevantem Mechanismus schwere intrathorakale Verletzungen; mittig insbesondere Pneumothorax und Lungenkontusion; unten Leber-/Milzverletzung und innere Blutung. Die Höhe ersetzt keine vollständige Untersuchung." },
  { id: "rippenfraktur-card-07", area: "Instabiler Thorax", question: "Erklären Sie paradoxe Atmung und weshalb fehlende Sichtbarkeit keine Entwarnung erlaubt.", answer: "Bei Spontanatmung zieht ein freies Segment inspiratorisch einwärts und kann exspiratorisch auswärts treten. Schmerz, Lagerung und Atmungsform beeinflussen die Sichtbarkeit; relevante Verletzungen können trotzdem bestehen." },
  { id: "rippenfraktur-card-08", area: "Schockformen", question: "Ordnen Sie Spannungspneumothorax, Hämatothorax, Myokardkontusion und hohe Rückenmarkverletzung den Schockmechanismen zu.", answer: "Spannung: obstruktive Füllungsbehinderung. Hämatothorax: absoluter Blutverlust/hypovolämisch. Myokardkontusion: mögliche Pumpstörung/kardiogen. Hohe Rückenmarkverletzung: Sympathikusausfall mit Vasodilatation/neurogen." },
  { id: "rippenfraktur-card-09", area: "Erstmaßnahmen", question: "Priorisieren Sie Untersuchung und Versorgung bei schmerzhafter Rippenfraktur mit Dyspnoe.", answer: "cABCDE, Inspektion, vorsichtige Palpation, beidseitige Auskultation; Atemarbeit, AF, SpO₂, RR, Puls und Vigilanz. Schonende Lagerung nach Befund, bedarfsgerechter O₂, Analgesie, Notarzt/Transport nach Zustand und wiederholte Kontrollen." },
  { id: "rippenfraktur-card-10", area: "Anamnese", question: "Welche SAMPLERS-Punkte sind bei älterem Thoraxtraumapatienten besonders relevant?", answer: "Antikoagulation und sedierende Medikamente, Lungen-/Herzvorgeschichte, Osteoporose, Mechanismus und Zeitverlauf, Atemnot und NRS. Sie beeinflussen Blutungsrisiko, respiratorische Reserve und Therapie." },
  { id: "rippenfraktur-card-11", area: "Morphin", question: "Berechnen Sie Initial- und halbe Wiederholungsdosis für 80 kg nach VFA 38 bei 1 mg/ml; nennen Sie Kontrolle und Höchstmenge.", answer: "Initial 4 mg = 4 ml. Nach 5 Minuten Wirkung prüfen; gegebenenfalls halbe Dosis 2 mg = 2 ml. Maximal insgesamt 10 mg; Atmung, Vigilanz, RR, EKG und NRS überwachen." },
  { id: "rippenfraktur-card-12", area: "Esketamin", question: "Berechnen Sie für 70 kg die Initial- und halbe Dosis bei 5 mg/ml nach VFA 36.", answer: "Initial 0,2 mg/kg = 14 mg = 2,8 ml; halbe Dosis 0,1 mg/kg = 7 mg = 1,4 ml. Erwachsenenpfad: zuvor 1 mg Midazolam i.v.; Kontrolle nach 5 Minuten und weitere Schritte gemäß Algorithmus." },
  { id: "rippenfraktur-card-13", area: "VFA 07", question: "Wann ist die Entlastung nach Thüringer VFA 07 angezeigt und woran beurteilen Sie den Erfolg?", answer: "Thoraxtrauma mit mindestens einseitig abgeschwächtem Atemgeräusch UND hämodynamischer Instabilität. Erfolg an respiratorischer UND hämodynamischer Stabilisierung prüfen; bei ausbleibender Wirkung Differenzialdiagnosen prüfen, Monitoring und Transport fortführen." },
  { id: "rippenfraktur-card-14", area: "Fallentscheidung", question: "NRS fällt nach Analgesie, Vigilanz und Atmung verschlechtern sich. Wie bewerten Sie den vermeintlichen Therapieerfolg?", answer: "NRS-Senkung allein reicht nicht. cABCDE neu bewerten, Atemweg/Ventilation sichern, Medikamentenwirkung und Begleitverletzung prüfen, weitere Gabe neu entscheiden und Verlauf dokumentieren." },
];
