import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct?: boolean];
function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  return { id: `schock-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: options.map(([text, correct]) => ({ text, correct })), source, difficulty };
}

export const schockFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "schock-card-01", area: "Definition", question: "Definieren Sie Schock ohne sich auf einen Blutdruckwert zu beschränken.", answer: "Akute Kreislaufinsuffizienz mit unzureichender Gewebeperfusion und einem Missverhältnis zwischen Sauerstoffangebot und Sauerstoffbedarf. Unbehandelt folgen Zellschädigung, Organversagen und Kreislaufstillstand." },
  { id: "schock-card-02", area: "Sauerstoffangebot", question: "Wovon hängt das Sauerstoffangebot an das Gewebe ab?", answer: "Vereinfacht gilt: DO₂ = Herzzeitvolumen × arterieller Sauerstoffgehalt. Das Herzzeitvolumen ergibt sich aus Herzfrequenz × Schlagvolumen; der arterielle Sauerstoffgehalt hängt vor allem von Hämoglobin und dessen Sättigung ab." },
  { id: "schock-card-03", area: "Blut", question: "Warum kann eine SpO₂ von 100 % bei hämorrhagischem Schock täuschen?", answer: "Die SpO₂ beschreibt die prozentuale Sättigung des vorhandenen Hämoglobins. Nach Erythrozytenverlust kann das restliche Hämoglobin vollständig gesättigt sein, obwohl die gesamte Sauerstofftransportkapazität deutlich vermindert ist." },
  { id: "schock-card-04", area: "Hämostase", question: "Erklären Sie primäre und sekundäre Hämostase.", answer: "Primär haften und aggregieren Thrombozyten am verletzten Gefäß. Sekundär entsteht über die Gerinnungskaskade Fibrin, das den Thrombozytenpfropf stabilisiert. Vasokonstriktion reduziert zuvor den Blutfluss." },
  { id: "schock-card-05", area: "Schockformen", question: "Nennen Sie die vier Hauptformen und ihren Kernmechanismus.", answer: "Hypovolämisch: Volumen fehlt. Kardiogen: Pumpe versagt. Obstruktiv: Füllung oder Auswurf ist mechanisch blockiert. Distributiv: Gefäßweitstellung und Fehlverteilung erzeugen eine relative Hypovolämie." },
  { id: "schock-card-06", area: "Kompensation", question: "Wie kompensiert der Körper einen beginnenden Volumenmangel?", answer: "Barorezeptorvermittelte Sympathikusaktivierung steigert Herzfrequenz und Kontraktilität; arterielle Vasokonstriktion erhöht den Widerstand, venöse Konstriktion mobilisiert Blut und die Zentralisation priorisiert Herz und Gehirn." },
  { id: "schock-card-07", area: "Mikrozirkulation", question: "Wie entsteht aus Minderperfusion eine sich selbst verstärkende Schockspirale?", answer: "Hypoxie erzwingt anaeroben Stoffwechsel mit Laktat und Azidose. ATP-Mangel und Endothelschaden erhöhen die Permeabilität, Flüssigkeit tritt aus, die Mikrozirkulation stagniert und Gerinnung sowie Organfunktion verschlechtern sich weiter." },
  { id: "schock-card-08", area: "Phasen", question: "Grenzen Sie kompensierten, dekompensierten und irreversiblen Schock ab.", answer: "Kompensiert: Blutdruck kann trotz früher Perfusionszeichen normal sein. Dekompensiert: Blutdruck und Organperfusion fallen, Vigilanz und Mikrozirkulation verschlechtern sich. Irreversibel: schwere Zell- und Organschäden lassen sich nicht mehr beherrschen." },
  { id: "schock-card-09", area: "Neurogen", question: "Erklären Sie die Hämodynamik des neurogenen Schocks.", answer: "Eine hohe Rückenmarkläsion, häufig oberhalb Th6, unterbricht sympathische Bahnen. Arterien und Venen dilatieren, Gefäßwiderstand und venöser Rückstrom sinken; die fehlende sympathische Herzanregung kann eine Bradykardie verursachen." },
  { id: "schock-card-10", area: "Neurogen", question: "Worin unterscheiden sich neurogener und spinaler Schock?", answer: "Der neurogene Schock ist eine Kreislaufstörung durch Sympathikusausfall. Der spinale Schock ist ein vorübergehender Ausfall spinaler Reflexe mit schlaffer Lähmung unterhalb der Läsion. Beide können gemeinsam auftreten, sind aber nicht synonym." },
  { id: "schock-card-11", area: "Diagnostik", question: "Wie wird der Schockindex berechnet und welche Grenzen hat er?", answer: "Herzfrequenz geteilt durch systolischen Blutdruck; über 0,9 ist beim Trauma ein Warnsignal. Betablocker, Schrittmacher, Alter, Schwangerschaft, Schmerz und neurogener Schock können ihn verfälschen." },
  { id: "schock-card-12", area: "Trauma", question: "Welche großen Blutungsräume suchen Sie beim instabilen Traumapatienten?", answer: "Thorax, Abdomen, Becken, lange Röhrenknochen und äußere Blutungsquellen. Parallel wird nach obstruktiven Ursachen wie Spannungspneumothorax oder Tamponade gesucht." },
  { id: "schock-card-13", area: "Gerinnung", question: "Erklären Sie die letale Raute.", answer: "Hypothermie, Azidose, Koagulopathie und Hypokalzämie verstärken sich gegenseitig. Dadurch nehmen Blutung und Kreislaufversagen zu, während Gerinnung, Myokardfunktion und Gefäßreaktion abnehmen." },
  { id: "schock-card-14", area: "VFA L2", question: "Welche Zielblutdrücke nennt der Thüringer Traumaalgorithmus?", answer: "Nicht beherrschbare Blutung ohne Sonderfall: RRsys etwa 80 mmHg. Führendes oder isoliertes SHT: mindestens 90 mmHg. Schwangere ab dem 5. Monat: 120 mmHg. Kinder: etwa 70 + 2 × Alter." },
  { id: "schock-card-15", area: "VFA L2", question: "Wann und wie wird Tranexamsäure nach L2 gegeben?", answer: "Bei Erwachsenen mit lebensbedrohlicher Blutung und/oder hämorrhagischem Schock: 1 g als Kurzinfusion über 10 Minuten. Die Gabe ergänzt, ersetzt aber niemals Blutungskontrolle und schnellen Transport." },
  { id: "schock-card-16", area: "Entscheidung", question: "Warum darf ein vermuteter neurogener Schock die Blutungssuche nicht beenden?", answer: "Traumapatienten können gleichzeitig bluten. Warme Haut und Bradykardie stützen den neurogenen Mechanismus, schließen hämorrhagische oder obstruktive Ursachen aber nicht aus." },
  { id: "schock-card-17", area: "Differenzialdiagnostik", question: "Welche Befunde lenken eher zum kardiogenen als zum hypovolämischen Schock?", answer: "Kardiale Vorgeschichte oder ACS-Symptome, Rhythmusstörung, pulmonaler Rückstau und gestaute Halsvenen sprechen eher kardiogen. EKG, Auskultation, Mechanismus und Verlauf müssen zusammengeführt werden." },
  { id: "schock-card-18", area: "Versorgung", question: "Formulieren Sie die präklinische Schockstrategie in einem Satz.", answer: "Lebensbedrohliche Ursache sofort behandeln, Oxygenierung und Perfusion zielgerichtet sichern, Auskühlung verhindern, Vitaltrend wiederholt prüfen und ohne vermeidbare Verzögerung in die geeignete Zielklinik transportieren." },
];

export const schockQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen definieren einen Schock fachlich korrekt?", [["Das Sauerstoffangebot reicht für den Gewebebedarf nicht aus", true], ["Eine gestörte Mikrozirkulation kann trotz zunächst normalem Blutdruck vorliegen", true], ["Unbehandelt sind Zellschädigung und Multiorganversagen möglich", true], ["Erst ein systolischer Blutdruck unter 90 mmHg begründet einen Schock"]], "Schock ist eine Perfusions- und Oxygenierungsstörung; die Hypotonie kann spät auftreten.", 2),
  q(2, "Welche Größen bestimmen das Sauerstoffangebot an das Gewebe wesentlich?", [["Herzzeitvolumen", true], ["Hämoglobinkonzentration", true], ["Arterielle Sauerstoffsättigung", true], ["Allein die gemessene Atemfrequenz"]], "DO₂ wird vereinfacht aus Herzzeitvolumen und arteriellem Sauerstoffgehalt bestimmt.", 2),
  q(3, "Ein Patient hat nach massiver Blutung eine SpO₂ von 100 %. Welche Schlussfolgerungen sind zulässig?", [["Das vorhandene Hämoglobin kann vollständig gesättigt sein", true], ["Die gesamte Sauerstofftransportkapazität kann trotzdem vermindert sein", true], ["Klinik und Perfusionszeichen bleiben entscheidend", true], ["Ein hämorrhagischer Schock ist damit ausgeschlossen"]], "Pulsoxymetrie misst die prozentuale Sättigung, nicht die absolute Menge an Hämoglobin oder transportiertem Sauerstoff.", 3),
  q(4, "Welche Zuordnungen zu Blutbestandteilen stimmen?", [["Erythrozyten transportieren Sauerstoff über Hämoglobin", true], ["Thrombozyten tragen zur primären Hämostase bei", true], ["Plasmatische Faktoren stabilisieren den Pfropf durch Fibrinbildung", true], ["Leukozyten erzeugen den arteriellen Blutdruck"]], "Erythrozyten, Thrombozyten und plasmatische Gerinnung haben verschiedene Funktionen; Leukozyten dienen vor allem der Abwehr.", 2),
  q(5, "Welche Veränderungen gehören zur frühen Kompensation eines Volumenmangels?", [["Tachykardie und gesteigerte Kontraktilität", true], ["Arterielle Vasokonstriktion mit Zentralisation", true], ["Venokonstriktion mit Mobilisierung des Blutreservoirs", true], ["Generalisierte Vasodilatation zur Blutdrucksteigerung"]], "Die sympathoadrenerge Reaktion erhält vorübergehend Herzzeitvolumen und zentrale Organperfusion.", 3),
  q(6, "Welche Aussagen beschreiben die Dekompensation?", [["Anaerober Stoffwechsel fördert Laktatbildung und Azidose", true], ["Endothelschaden und Kapillarleck verstärken den intravasalen Mangel", true], ["Mikrozirkulationsstörung und Gerinnungsaktivierung schädigen Organe", true], ["Der Blutdruck bleibt definitionsgemäß dauerhaft normal"]], "Anhaltende Minderperfusion führt zu Azidose, Permeabilitätsstörung, Stase und Organschaden.", 3),
  q(7, "Welche Zuordnungen von Schockform und Mechanismus sind korrekt?", [["Hypovolämisch: verminderte Vorlast durch Volumenverlust", true], ["Kardiogen: unzureichende Pumpfunktion", true], ["Obstruktiv: mechanisch behinderte Füllung oder Auswurfleistung", true], ["Distributiv: ausschließlich Verlust von Erythrozyten"]], "Distributive Formen beruhen auf Vasodilatation und Fehlverteilung, nicht zwingend auf Blutverlust.", 2),
  q(8, "Welche Ursachen gehören zum obstruktiven Schock?", [["Spannungspneumothorax", true], ["Herzbeuteltamponade", true], ["Massive Lungenarterienembolie", true], ["Isolierte Gastroenteritis"]], "Obstruktive Ursachen blockieren Füllung oder Auswurf des Herzens.", 2),
  q(9, "Welche Konstellationen können einen distributiven Schock verursachen?", [["Sepsis mit Vasoplegie und Kapillarleck", true], ["Anaphylaxie mit Mediatorfreisetzung", true], ["Hohe Rückenmarkläsion mit Sympathikusausfall", true], ["Isolierter Blutverlust ohne Gefäßweitstellung"]], "Septisch, anaphylaktisch und neurogen sind distributive Mechanismen; Blutverlust ist hypovolämisch.", 2),
  q(10, "Welche Aussagen zum neurogenen Schock treffen zu?", [["Eine Läsion oberhalb Th6 kann wichtige sympathische Bahnen unterbrechen", true], ["Vasodilatation senkt Gefäßwiderstand und venösen Rückstrom", true], ["Fehlende sympathische Herzanregung kann eine Bradykardie erklären", true], ["Blasse kaltschweißige Haut und ausgeprägte Tachykardie müssen immer vorliegen"]], "Typisch können Hypotonie, warme trockene Haut und relative Bradykardie sein; Blutung bleibt auszuschließen.", 3),
  q(11, "Welche Aussagen grenzen neurogenen und spinalen Schock richtig ab?", [["Der neurogene Schock ist eine hämodynamische Störung", true], ["Der spinale Schock beschreibt vorübergehenden Reflexausfall und schlaffe Lähmung", true], ["Beide Zustände können gleichzeitig vorkommen", true], ["Beide Begriffe sind vollständig synonym"]], "Neurogen beschreibt Kreislaufregulation, spinal die vorübergehende neurologische Reflexlage.", 3),
  q(12, "Ein Traumapatient ist hypotensiv, bradykard und unterhalb Th4 gelähmt. Welche Entscheidungen sind richtig?", [["Ein neurogener Schock ist plausibel", true], ["Hämorrhagische und obstruktive Ursachen werden parallel gesucht", true], ["Atmung und neurologischer Verlauf werden seriell beurteilt", true], ["Die Blutungssuche kann wegen der Bradykardie beendet werden"]], "Die Konstellation stützt den neurogenen Mechanismus, schließt Mischursachen aber nicht aus.", 3),
  q(13, "Welche Befunde können einen kompensierten Schock stützen, obwohl der RRsys noch normal ist?", [["Verlängerte Rekapillarisierung und kühle Akren", true], ["Tachykardie mit schwachem peripherem Puls", true], ["Unruhe oder neu auftretende Verwirrtheit", true], ["Ein stabiler Einzelwert ohne Trendbeobachtung"]], "Frühe Schockzeichen ergeben sich aus Perfusion, Haut, Puls, Atmung, Bewusstsein und Verlauf.", 3),
  q(14, "Welche Aussagen zum Schockindex sind korrekt?", [["Er wird aus Herzfrequenz geteilt durch systolischen Blutdruck berechnet", true], ["Ein Wert über 0,9 ist beim Trauma ein Warnsignal", true], ["Betablocker und neurogener Schock können seine Aussage verzerren", true], ["Ein Wert unter 0,9 schließt relevante Blutung sicher aus"]], "Der Schockindex unterstützt die Einschätzung, ersetzt aber weder cABCDE noch Trend und Gesamteindruck.", 3),
  q(15, "Welche Faktoren bilden die letale Raute des Blutungsschocks?", [["Hypothermie", true], ["Azidose", true], ["Koagulopathie", true], ["Hypokalzämie", true]], "Die vier Faktoren verstärken Blutung, Kreislaufversagen und Gerinnungsstörung gegenseitig.", 2),
  q(16, "Welche Aussagen zur präklinischen Hämoglobinbeurteilung bei akuter Blutung sind richtig?", [["Ein früher Hb-Wert kann den Blutverlust unterschätzen", true], ["Klinische Dynamik und Blutungszeichen bleiben maßgeblich", true], ["Kristalloide Flüssigkeit kann den Hb-Wert später durch Verdünnung senken", true], ["Ein initial normaler Hb-Wert schließt eine lebensbedrohliche Blutung aus"]], "Bei akutem Verlust gehen Plasma und Zellen zunächst gemeinsam verloren; Konzentrationswerte spiegeln die verlorene Gesamtmenge nicht sofort wider.", 3),
  q(17, "Welche Maßnahmen folgen im Traumaalgorithmus unmittelbar aus einer lebensbedrohlichen äußeren Blutung?", [["Manuelle Kompression", true], ["Kompressionsverband gegebenenfalls mit Hämostyptikum", true], ["Tourniquet bei entsprechender Extremitätenblutung", true], ["Transport erst nach vollständiger Normalisierung aller Vitalwerte"]], "L2 priorisiert die gestufte Blutungskontrolle und parallele zeitkritische Transportstrategie.", 3),
  q(18, "Ein Erwachsener hat eine nicht beherrschbare innere Blutung ohne führendes SHT. Welche Aussagen entsprechen L2?", [["Volumentherapie erfolgt reduziert", true], ["Ziel ist ein RRsys von etwa 80 mmHg", true], ["Definitive Blutungskontrolle und schneller Transport haben Priorität", true], ["RRsys 120 mmHg muss präklinisch zwingend erreicht werden"]], "Bei nicht beherrschbarer Blutung nennt L2 permissive Hypotonie um 80 mmHg, sofern kein Sonderziel gilt.", 3),
  q(19, "Welche Sonderziele nennt der Thüringer Traumaalgorithmus?", [["Führendes oder isoliertes SHT: RRsys mindestens 90 mmHg", true], ["Schwangere ab dem 5. Monat: RRsys 120 mmHg", true], ["Kinder: RRsys etwa 70 + 2 × Alter", true], ["Jeder Erwachsene mit Blutung: RRsys mindestens 140 mmHg"]], "Die Zielwerte werden an zerebrale Perfusion, Schwangerschaft und Alter angepasst.", 3),
  q(20, "Welche Aussagen zur Tranexamsäure nach L2 stimmen?", [["Indikation sind lebensbedrohliche Blutung und/oder hämorrhagischer Schock beim Erwachsenen", true], ["Es werden 1 g als Kurzinfusion über 10 Minuten gegeben", true], ["Die Antifibrinolyse ergänzt die mechanische und definitive Blutungskontrolle", true], ["Die Gabe ersetzt Tourniquet, Beckenschlinge und Operation"]], "Tranexamsäure stabilisiert Fibrin, stoppt aber keine mechanische Blutungsquelle.", 3),
  q(21, "Welche Aussagen zur letalen Raute begründen den Wärmeerhalt?", [["Hypothermie beeinträchtigt Gerinnungsreaktionen", true], ["Kalte Umgebung und Exposition fördern weitere Auskühlung", true], ["Warme Umgebung und angewärmte Materialien unterbrechen die Schockspirale", true], ["Wärmeerhalt ist erst nach Klinikaufnahme relevant"]], "Wärmeerhalt beginnt präklinisch und gehört unter E zum Traumaalgorithmus.", 3),
  q(22, "Welche Konstellationen sprechen eher gegen eine pauschale Schocklagerung?", [["Kardiogener Schock mit Lungenödem", true], ["Thoraxverletzung mit Atemnot", true], ["Führendes Schädel-Hirn-Trauma", true], ["Jede kompensierte Exsikkose ohne Beschwerden"]], "Die Lagerung richtet sich nach Ursache, Atmung, Verletzungsmuster und Kreislauf; Beine hoch ist keine universelle Schocktherapie.", 3),
  q(23, "Welche Befunde sprechen eher für kardiogenen als für reinen hypovolämischen Schock?", [["ACS-Symptome oder relevante Rhythmusstörung", true], ["Pulmonale Stauungszeichen", true], ["Gestaute Halsvenen bei passendem Gesamtbild", true], ["Sichtbare arterielle Blutung an einer Extremität"]], "Kardiogener Schock verbindet Pumpversagen mit Rückstau; Befunde müssen im Kontext bewertet werden.", 3),
  q(24, "Welche Befunde lenken beim instabilen Traumapatienten zur obstruktiven Ursache?", [["Einseitig deutlich vermindertes Atemgeräusch mit zunehmender Dyspnoe", true], ["Kreislaufverschlechterung nach positiver Druckbeatmung", true], ["PEA bei passendem Thoraxmechanismus", true], ["Isolierte verlängerte Rekapillarisierung ohne Thoraxbefund"]], "Spannungspneumothorax und Tamponade sind klinisch zeitkritische obstruktive Ursachen.", 3),
  q(25, "Welche Aussagen zeigen eine gute Re-Evaluation beim Schock?", [["Vitalwerte werden als Trend dokumentiert", true], ["Bewusstsein, Haut, Pulsqualität und Rekapillarisierung werden erneut geprüft", true], ["Nach jeder Intervention werden Wirkung und Nebenwirkung beurteilt", true], ["Nach einem normalen Blutdruckwert kann die Überwachung beendet werden"]], "Schock ist dynamisch; serielle cABCDE-Runden und Wirkungsprüfung sind zentral.", 3),
  q(26, "Welche Übergabeinformationen sind bei Schock besonders entscheidend?", [["Vermutete Ursache und mögliche Blutungsquelle", true], ["Zeitlicher Verlauf von Kreislauf, Bewusstsein und Atmung", true], ["Interventionen mit Zeitpunkt, Dosis und Wirkung", true], ["Nur der zuletzt gemessene Blutdruck"]], "Eine belastbare Übergabe verbindet Ursache, Dynamik, Befunde, Maßnahmen und deren Wirkung.", 3),
];
