import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct?: boolean];
const q = (number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion => ({ id: `schussverletzung-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: options.map(([text, correct]) => ({ text, correct })), source, difficulty });

export const schussverletzungFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "schussverletzung-card-01", area: "Definition", question: "Welche Formen der Schussverletzung werden nach der Eindringtiefe unterschieden?", answer: "Prellschuss, Streifschuss, Steckschuss und Durchschuss. Der äußere Wundtyp erlaubt keine sichere Aussage über den inneren Schaden." },
  { id: "schussverletzung-card-02", area: "Ballistik", question: "Warum beeinflusst die Geschwindigkeit den Gewebeschaden besonders stark?", answer: "Die kinetische Energie beträgt näherungsweise E = ½mv². Geschwindigkeit geht quadratisch ein; Gewebeschaden hängt zusätzlich von Projektilform, Rotation, Fragmentation, Winkel und Gewebe ab." },
  { id: "schussverletzung-card-03", area: "Wundkanal", question: "Unterscheiden Sie permanente Wundhöhle und temporäre Kavitation.", answer: "Die permanente Höhle ist der direkt zerstörte Wundkanal. Temporäre Kavitation ist die kurzzeitige radiale Dehnung des umliegenden Gewebes durch Energieübertragung und kann zusätzliche Schäden verursachen." },
  { id: "schussverletzung-card-04", area: "Anatomie", question: "Welche Strukturen sind bei einer proximalen Oberschenkelschussverletzung besonders bedroht?", answer: "A. und V. femoralis beziehungsweise ihre Äste, begleitende Nerven, Muskulatur und Femur. Folgen sind Exsanguination, distale Ischämie, neurologischer Ausfall, Fraktur und Kompartmentsyndrom." },
  { id: "schussverletzung-card-05", area: "Eigenschutz", question: "Was steht vor der medizinischen Versorgung einer Schussverletzung?", answer: "Sichere Lage und polizeiliche Freigabe. Weitere Täter, Waffen, aggressive Personen, Rückzugsweg und Teamkommunikation müssen berücksichtigt werden." },
  { id: "schussverletzung-card-06", area: "Blutung", question: "Wie wird eine lebensbedrohliche komprimierbare Blutung stufenweise kontrolliert?", answer: "Direkter Druck, bei tiefer zugänglicher Wunde Packing mit Hämostyptikum, fester Kompressionsverband und bei nicht beherrschbarer Extremitätenblutung Tourniquet proximal der Wunde, nicht über Gelenk; Zeit dokumentieren." },
  { id: "schussverletzung-card-07", area: "Grenzen", question: "Wo darf nicht blind gepackt werden?", answer: "Nicht in Thorax, Abdomen oder andere Körperhöhlen. Packing ist für zugängliche, komprimierbare tiefe Wunden vorgesehen; nichtkomprimierbare Blutungen benötigen schnellstmögliche definitive Versorgung." },
  { id: "schussverletzung-card-08", area: "Schock", question: "Warum kann eine Schussverletzung bei zunächst normalem Blutdruck lebensbedrohlich sein?", answer: "Kompensationsmechanismen halten den Blutdruck anfangs aufrecht. Haut, Rekapillarisierung, Pulsqualität, Bewusstsein und Vitaltrend können eine Minderperfusion früher anzeigen." },
  { id: "schussverletzung-card-09", area: "Thorax", question: "Welche Konstellation spricht für die Thüringer Entlastungspunktion?", answer: "Passendes Thoraxtrauma, mindestens einseitig vermindertes Atemgeräusch und hämodynamische Instabilität. Die Diagnose ist klinisch und darf bei vitaler Bedrohung nicht auf Bildgebung warten." },
  { id: "schussverletzung-card-10", area: "Entlastung", question: "Nennen Sie die Punktionsorte und Kernregeln der VFA 07.", answer: "2. ICR medioklavikular oder 4./5. ICR vordere Axillarlinie; mindestens 6,5 cm Kanüle, 90 Grad zur Thoraxwand, über dem Rippenoberrand. Danach Mandrin entfernen, fixieren und Wirkung re-evaluieren." },
  { id: "schussverletzung-card-11", area: "Fremdkörper", question: "Warum wird ein Projektil präklinisch nicht entfernt?", answer: "Es kann Gefäße tamponieren; Entfernung kann die Blutung verstärken. Zudem ist es forensisch relevant. Auch Wunden werden nicht sondiert oder unnötig gereinigt." },
  { id: "schussverletzung-card-12", area: "Untersuchung", question: "Was umfasst die schnelle Traumauntersuchung bei einer Schussverletzung?", answer: "Nach Behandlung der cABCDE-Probleme standardisiert Vorder- und Rückseite von Kopf bis Fuß untersuchen, alle Wunden suchen, Thorax und große Blutungsräume beurteilen, pDMS prüfen und anschließend cABCDE wiederholen." },
  { id: "schussverletzung-card-13", area: "Spurenerhalt", question: "Wie werden Therapie und Spurenerhalt miteinander vereinbart?", answer: "Lebensrettende Maßnahmen haben Vorrang. Kleidung möglichst nicht durch Wundöffnungen schneiden, nichts unnötig reinigen oder entfernen und Veränderungen sowie Übergabe von Fundstücken exakt dokumentieren." },
  { id: "schussverletzung-card-14", area: "Analgesie", question: "Welche Grundregeln gelten für Esketamin oder Morphin bei starken traumatischen Schmerzen?", answer: "Erst unmittelbar lebensbedrohliche cABCDE-Probleme behandeln. Danach VFA 35 und den gewählten Pfad 36 oder 38 mit Gewichtstabelle, langsamer Gabe, Monitoring, Beatmungsbereitschaft und wiederholter Wirkungsprüfung anwenden." },
  { id: "schussverletzung-card-15", area: "Transport", question: "Was kennzeichnet Load-go-and-treat bei kritischer Schussverletzung?", answer: "Lebensrettende Sofortmaßnahmen und Transportvorbereitung laufen parallel. Geeignetes Traumazentrum früh voranmelden; nicht zwingende Maßnahmen dürfen die definitive Blutungs- oder Organversorgung nicht verzögern." },
];

export const schussverletzungQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen zur äußeren Erscheinung einer Schussverletzung sind fachlich richtig?", [["Eine kleine Eintrittswunde kann mit schweren inneren Verletzungen einhergehen", true], ["Eine Austrittswunde ist nicht regelhaft größer als die Eintrittswunde", true], ["Aus der Hautwunde lässt sich das Kaliber präklinisch sicher bestimmen"], ["Die Projektilbahn kann durch Knochen oder Fragmentation abweichen", true], ["Wenig äußere Blutung schließt eine innere Blutung aus"]], "Wundgröße, Blutmenge und gedachte Verbindungslinie bilden den inneren Schaden nicht zuverlässig ab.", 3),
  q(2, "Welche Faktoren beeinflussen die Energieabgabe eines Projektils im Körper?", [["Masse und Geschwindigkeit", true], ["Projektilform, Rotation und Fragmentation", true], ["Trefferwinkel und getroffene Gewebeart", true], ["Ausschließlich der Durchmesser der Eintrittswunde"], ["Interaktion mit Knochen und Gewebegrenzen", true]], "Die Formel E = ½mv² erklärt nur einen Teil; die konkrete Gewebeinteraktion bestimmt die Energieabgabe.", 3),
  q(3, "Welche Aussagen zu permanenter Wundhöhle und temporärer Kavitation stimmen?", [["Die permanente Höhle entspricht direkt zerstörtem Gewebe", true], ["Temporäre Kavitation dehnt umliegendes Gewebe kurzzeitig radial", true], ["Unelastische Organe können durch Kavitation zusätzlich geschädigt werden", true], ["Temporäre Kavitation ist an der Haut immer vollständig sichtbar"], ["Sekundärfragmente können zusätzliche Wundkanäle erzeugen", true]], "Direkte Zerstörung, Kavitation und Sekundärfragmente erklären die Diskrepanz zwischen äußerem und innerem Befund.", 3),
  q(4, "Welche Gefahren folgen aus einer Schussverletzung des proximalen Oberschenkels?", [["Massive arterielle oder venöse Blutung", true], ["Distale Extremitätenischämie", true], ["Nervenläsion mit motorischem oder sensiblem Defizit", true], ["Femurfraktur und sekundäre Fragmente", true], ["Eine erhaltene Hauttemperatur schließt jede Gefäßverletzung sicher aus"]], "Gefäße, Nerven, Muskulatur und Knochen liegen eng zusammen; Verlauf und pDMS sind entscheidend.", 3),
  q(5, "Welche Schritte sind bei unklarer Sicherheitslage richtig?", [["Bereitstellungsraum außerhalb des Gefahrenbereichs wählen", true], ["Polizeiliche Freigabe vor Annäherung abwarten", true], ["Rückzugsweg und Kommunikation im Team festlegen", true], ["Zur Zeitersparnis allein in einen ungesicherten Bereich vorgehen"], ["Bei neuer Bedrohung Versorgung abbrechen und Sicherheit wiederherstellen", true]], "Eigenschutz hat Vorrang; ohne sichere Lage entsteht ein zusätzlicher Patient.", 3),
  q(6, "Eine tiefe, stark blutende Extremitätenwunde ist komprimierbar. Welche Maßnahmen sind geeignet?", [["Sofortiger direkter Druck", true], ["Wundpacking mit geeignetem Material", true], ["Fester Kompressionsverband", true], ["Tourniquet bei nicht anders kontrollierbarer lebensbedrohlicher Blutung", true], ["Blinde Sondierung zur Suche nach dem verletzten Gefäß"]], "Komprimierbare Blutungen werden mechanisch kontrolliert; Exploration ist keine präklinische Aufgabe.", 3),
  q(7, "Welche Aussagen zur Tourniquet-Anlage sind richtig?", [["Es wird proximal der Extremitätenwunde angelegt", true], ["Es soll nicht über einem Gelenk liegen", true], ["Anlagezeit und Verlauf werden dokumentiert", true], ["Blutungskontrolle und distaler Befund werden kontrolliert", true], ["Es wird zur Routinekontrolle in kurzen Abständen vollständig gelöst"]], "Ein korrekt angelegtes Tourniquet wird kontrolliert und dokumentiert, aber nicht routinemäßig präklinisch gelöst.", 3),
  q(8, "Welche Aussagen grenzen Wundpacking korrekt ab?", [["Es eignet sich für zugängliche tiefe, komprimierbare Wunden", true], ["Hämostyptische Gaze kann die Blutungskontrolle unterstützen", true], ["Nach dem Packing ist anhaltender fester Druck notwendig", true], ["Eine Thoraxhöhle wird bei penetrierender Verletzung blind ausgestopft"], ["Nichtkomprimierbare Rumpfblutung verlangt rasche definitive Versorgung", true]], "Packing ist eine Stop-the-Bleed-Maßnahme für komprimierbare Wunden, nicht für Körperhöhlen.", 3),
  q(9, "Welche Befunde können einen kompensierten hämorrhagischen Schock anzeigen, obwohl der Blutdruck noch normal ist?", [["Tachykardie und schwache periphere Pulse", true], ["Blasse, kühle oder kaltschweißige Haut", true], ["Verlängerte Rekapillarisierungszeit", true], ["Unruhe oder zunehmende Somnolenz", true], ["Ein einzelner normaler systolischer Blutdruck schließt den Schock aus"]], "Der Blutdruck kann durch Kompensation lange erhalten bleiben; Perfusionszeichen und Trend sind früher aussagekräftig.", 3),
  q(10, "Welche Befunde sprechen nach Thoraxschuss für einen Spannungspneumothorax mit Entlastungsindikation?", [["Einseitig deutlich vermindertes Atemgeräusch", true], ["Hämodynamische Instabilität", true], ["Akute Verschlechterung unter Überdruckbeatmung", true], ["Isolierter lokaler Schmerz bei stabilem Kreislauf"], ["Passende klinische Konstellation auch ohne Röntgenbestätigung", true]], "VFA 07 verbindet Thoraxtrauma, Seitenunterschied des Atemgeräuschs und Instabilität; vital bedrohliche Spannung ist klinisch.", 3),
  q(11, "Welche technischen Aussagen zur Entlastungspunktion entsprechen der Thüringer VFA?", [["2. ICR medioklavikular ist ein möglicher Ort", true], ["4./5. ICR vordere Axillarlinie ist ein möglicher Ort", true], ["Die Kanüle soll mindestens 6,5 cm lang sein", true], ["Punktion im 90-Grad-Winkel über dem Rippenoberrand", true], ["Nach Luftentweichen entfällt jede weitere Wirkungskontrolle"]], "Nach Mandrinentfernung und Fixierung müssen respiratorische und hämodynamische Wirkung erneut beurteilt werden.", 3),
  q(12, "Nach einer Thoraxentlastung bleibt der Patient instabil. Welche Schritte sind notwendig?", [["Punktion und klinische Wirkung erneut beurteilen", true], ["Erneute Spannung oder technischen Misserfolg mitdenken", true], ["Hämatothorax, Tamponade und weitere Blutungsquellen prüfen", true], ["Zeitkritischen Transport fortsetzen", true], ["Instabilität allein der Analgesie zuschreiben"]], "Eine einzelne Intervention beendet weder Re-Evaluation noch Differenzialdiagnostik.", 3),
  q(13, "Welche Maßnahmen gehören zur cABCDE-Versorgung einer kritischen Schussverletzung?", [["Kritische äußere Blutung vor der detaillierten Untersuchung kontrollieren", true], ["Atemweg und Absaugmöglichkeit sichern", true], ["Thorax beidseits untersuchen und Beatmung überwachen", true], ["Weitere große Blutungsräume und pDMS beurteilen", true], ["Den Patienten vollständig entkleidet auskühlen lassen"]], "cABCDE priorisiert reversible Todesursachen; Exploration wird mit konsequentem Wärmeerhalt verbunden.", 3),
  q(14, "Welche Elemente gehören zur schnellen Traumauntersuchung nach den Sofortmaßnahmen?", [["Vorder- und Rückseite standardisiert untersuchen", true], ["Alle sichtbaren Wunden zählen und dokumentieren", true], ["Thorax, Abdomen, Becken und Extremitäten berücksichtigen", true], ["Nach Abschluss cABCDE erneut beginnen", true], ["Jede Wunde mit einer Sonde auf Tiefe prüfen"]], "Der Bodycheck findet weitere Verletzungen, ohne Wunden zu explorieren oder den Transport unnötig zu verzögern.", 3),
  q(15, "Welche Maßnahmen verbinden medizinische Versorgung und Spurenerhalt richtig?", [["Lebensrettende Maßnahmen haben Vorrang", true], ["Kleidung möglichst nicht durch sichtbare Wundöffnungen schneiden", true], ["Projektile und Fremdkörper nicht unnötig entfernen", true], ["Durchgeführte Veränderungen und Übergaben dokumentieren", true], ["Wunden vor Polizeieintreffen gründlich reinigen"]], "Spuren werden soweit möglich geschützt, ohne die medizinische Versorgung einzuschränken.", 3),
  q(16, "Welche Aussagen zum Belassen eines Projektils sind korrekt?", [["Es kann ein verletztes Gefäß teilweise tamponieren", true], ["Entfernung kann eine Blutung verstärken", true], ["Lage und Entfernung gehören in die definitive klinische Versorgung", true], ["Das Projektil kann forensisch relevant sein", true], ["Jedes oberflächlich sichtbare Projektil muss zur Druckentlastung sofort entfernt werden"]], "Keine präklinische Projektilentfernung oder Wundexploration.", 3),
  q(17, "Welche Aussagen zur Analgesie mit Esketamin sind prüfungsrelevant?", [["Unmittelbar lebensbedrohliche cABCDE-Probleme werden zuerst behandelt", true], ["Der traumatische Schmerzpfad erfordert die Thüringer VFA und Gewichtstabelle", true], ["Monitoring und Beatmungsbereitschaft bleiben erforderlich", true], ["Wirkung und Nebenwirkungen werden nach der Gabe re-evaluiert", true], ["Esketamin macht Blutungskontrolle und Immobilisation entbehrlich"]], "Analgesie ergänzt Ursachenbehandlung, Überwachung und Transport; Dosierung folgt ausschließlich VFA 36/B2B.", 3),
  q(18, "Welche Aussagen zur Morphingabe bei starken traumatischen Schmerzen stimmen?", [["Die Gabe erfolgt langsam i.v. nach Gewichtstabelle", true], ["Atemfunktion, Kreislauf und Vigilanz werden überwacht", true], ["Nach fünf Minuten wird die Wirkung geprüft", true], ["Repetition und Maximaldosis richten sich nach VFA 38", true], ["Eine Atemdepression ist bei korrekter Gabe grundsätzlich ausgeschlossen"]], "Morphin erfordert titrierte Gabe, engmaschige Überwachung und Re-Evaluation.", 3),
  q(19, "Wann passt Tranexamsäure zum Traumaalgorithmus?", [["Bei lebensbedrohlicher traumatischer Blutung des Erwachsenen", true], ["Bei hämorrhagischem Schock nach Trauma", true], ["Zusätzlich zur mechanischen und definitiven Blutungskontrolle", true], ["Als Ersatz für Tourniquet, Packing oder Operation"], ["Nicht allein wegen einer kleinen stabilen Wunde ohne Blutungszeichen", true]], "TXA ist Teil eines Blutungskonzepts bei schwerer traumatischer Blutung, keine pauschale Gabe nach jedem Schuss.", 3),
  q(20, "Welche Komplikationen können nach Thoraxschuss gleichzeitig vorliegen?", [["Pneumothorax", true], ["Hämatothorax", true], ["Herzbeuteltamponade", true], ["Verletzung großer Gefäße", true], ["Eine einzelne kleine Wunde schließt kombinierte Verletzungen aus"]], "Der Wundkanal kann mehrere Strukturen treffen; respiratorische und zirkulatorische Ursachen können kombiniert sein.", 3),
  q(21, "Welche Befunde verlangen eine besonders frühe Traumazentrum-Voranmeldung?", [["Unkontrollierte oder rezidivierende kritische Blutung", true], ["Schockzeichen oder Vitaltrendverschlechterung", true], ["Thorax-, Hals-, Kopf-, Abdomen- oder Beckentreffer", true], ["Neurologische oder distale vaskuläre Ausfälle", true], ["Ausschließlich ein stabiler oberflächlicher Streifschuss ohne weitere Auffälligkeit"]], "Zielklinik und Ressourcenbedarf ergeben sich aus Region, Physiologie, Verlauf und vermuteten Begleitverletzungen.", 3),
  q(22, "Welche Aussagen kennzeichnen Load-go-and-treat bei kritischer Schussverletzung?", [["Sofortmaßnahmen und Transportvorbereitung laufen parallel", true], ["Ein geeignetes Traumazentrum wird früh ausgewählt", true], ["Nicht zwingende Maßnahmen dürfen die definitive Versorgung nicht verzögern", true], ["Re-Evaluation wird während des Transports fortgesetzt", true], ["Vor Abfahrt muss jede anatomische Verletzung sicher diagnostiziert sein"]], "Bei penetrierendem kritischem Trauma zählt die Zeit bis zur definitiven Blutungs- und Organversorgung.", 3),
  q(23, "Welche Informationen gehören in die strukturierte Übergabe?", [["Sicherheitslage und Ereigniszeitpunkt", true], ["Gefundene Wunden und vermutete Körperregionen", true], ["cABCDE-Befunde und Vitaltrend", true], ["Blutungskontrolle, Tourniquetzeit, Medikamente und Wirkung", true], ["Unbestätigte Angaben zu Täter oder Kaliber als sichere medizinische Diagnose"]], "Die Übergabe trennt beobachtete Befunde, Maßnahmen, Verlauf und unbestätigte Informationen klar.", 3),
  q(24, "Welche Aussagen sind typische Prüfungsfallen bei Schussverletzungen?", [["Die sichtbare Wundgröße bildet den inneren Schaden nicht zuverlässig ab", true], ["Ein normaler Blutdruck kann einen kompensierten Schock verdecken", true], ["Nach einer gefundenen Wunde muss weiter nach zusätzlichen Wunden gesucht werden", true], ["Ein Projektilverlauf ist aus Ein- und Austritt immer geradlinig rekonstruierbar"], ["Erfolgreiche Blutungskontrolle ersetzt keine erneute cABCDE-Beurteilung", true]], "Schussverletzungen verlangen dynamische Gesamtbeurteilung statt Schlussfolgerungen aus einem Einzelbefund.", 3),
];
