import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function StichverletzungLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, kicker: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>{kicker}</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;

  return <article className="lesson-article angina-pectoris-lesson reference-reading-lesson polytrauma-lesson stichverletzung-lesson">
    <div className="lesson-intro"><p className="lead">Eine kleine Stichöffnung kann eine große innere Verletzung verbergen. Entscheidend sind deshalb <b>Eigenschutz, cABCDE, die betroffene Körperregion, der Vitaltrend und der schnelle Weg zur definitiven Blutungs- oder Organversorgung</b> – nicht die sichtbare Wundgröße.</p></div>

    {section("01", "Penetrierendes Trauma", "Definition", <><p>Eine <b>Stichverletzung</b> entsteht, wenn ein spitzer oder scharfkantiger Gegenstand Haut und tiefer liegendes Gewebe durchdringt. Der Wundkanal kann Gefäße, Nerven, Organe oder Körperhöhlen verletzen. Äußerlich geringe Blutung schließt eine lebensbedrohliche innere Blutung nicht aus.</p><div className="pulmo-risk-grid"><div><b>Stich- oder Punktionswunde</b><p>Meist kleine Eintrittsöffnung mit unterschiedlich tiefem Wundkanal.</p></div><div><b>Pfählungsverletzung</b><p>Der Gegenstand verbleibt im Körper und kann verletzte Gefäße teilweise tamponieren.</p></div><div><b>Durchspießung</b><p>Ein Gegenstand hat zwei Körperöffnungen erzeugt oder durchdringt den Körper sichtbar.</p></div><div><b>Schnitt-Stich-Verletzung</b><p>Kombination aus schmalem Wundkanal und längerer Haut- oder Weichteileröffnung.</p></div></div><aside className="red-flags"><span>!</span><div><small>Prüfungsgrundsatz</small><h3>Wundkanal nie aus der Hautöffnung ableiten</h3><p>Länge, Richtung und Tiefe sind präklinisch nicht sicher rekonstruierbar. Weder sondieren noch den Fremdkörper entfernen.</p></div></aside></>)}

    {section("02", "Gefährdete Räume und Organe", "Anatomie und Physiologie", <><div className="reading-columns"><div><Figure src="/lessons/thoraxtrauma/page1-Im1.jpg" alt="Anatomische Übersicht des Thorax" caption="Thorax · knöcherner Schutz, Pleura, Lunge, Herz und große Gefäße" wide /><h3>Thorax</h3><ul className="script-list"><li><b>Pleura:</b> Luft oder Blut im Pleuraspalt beeinträchtigt die Lungenentfaltung.</li><li><b>Lunge:</b> Verletzung kann Pneumo- oder Hämatothorax verursachen.</li><li><b>Herz und Perikard:</b> Blut im Herzbeutel kann die diastolische Füllung blockieren.</li><li><b>Große Gefäße:</b> Verletzungen können binnen Minuten zur Exsanguination führen.</li></ul></div><div><Figure src="/lessons/abdominaltrauma/verdauungssystem.jpg" alt="Beschriftete Anatomie von Abdomen und Verdauungsorganen" caption="Abdomen · Lagebeziehungen von Leber, Magen, Milz, Darm und Pankreas" wide /><h3>Abdomen und Retroperitoneum</h3><ul className="script-list"><li><b>Leber und Milz:</b> stark durchblutete Organe mit erheblichem Blutungspotenzial.</li><li><b>Magen und Darm:</b> Hohlorganverletzung kann Inhalt freisetzen und später Peritonitis oder Sepsis auslösen.</li><li><b>Mesenterium:</b> enthält Gefäße; Verletzungen können stark und zunächst verborgen bluten.</li><li><b>Nieren und große Gefäße:</b> liegen retroperitoneal; Blutungen können äußerlich lange unauffällig bleiben.</li></ul></div></div><Figure src="/lessons/abdominaltrauma/arterielle-versorgung.jpg" alt="Arterielle Versorgung der Bauchorgane" caption="Arterielle Gefäßversorgung · eine kleine äußere Wunde kann große Gefäße oder Organäste treffen" wide /></>)}

    {section("03", "Mechanismus und Wundkanal", "Ursachen und Pathophysiologie", <><div className="pulmo-risk-grid"><div><b>Gewalttat</b><p>Messer, Schere, Schraubendreher oder andere spitze Gegenstände; mehrere Wunden und weitere Täter mitdenken.</p></div><div><b>Unfall</b><p>Sturz auf Glas, Metall, Zaun oder Werkzeug; häufig komplexe Pfählungs- und Begleitverletzungen.</p></div><div><b>Arbeits- und Sportereignis</b><p>Nadeln, Maschinen, Haken oder Sportgeräte können tiefe, kontaminierte Kanäle erzeugen.</p></div><div><b>Selbstverletzung</b><p>Zusätzlich zur somatischen Versorgung auf erneute Gefährdung, Intoxikation und psychiatrischen Hilfebedarf achten.</p></div></div><div className="pulmo-path"><span>Gefäß-/Organläsion</span><i>→</i><span>äußere oder innere Blutung</span><i>→</i><span>Vorlast ↓</span><i>→</i><span>HZV ↓</span><i>→</i><span>Gewebehypoxie</span></div><p>Ein im Körper steckender Gegenstand kann Gefäße komprimieren. Wird er entfernt, kann die bislang begrenzte Blutung plötzlich massiv werden. Elastische Gewebe können sich nach Passage wieder zusammenziehen; die Eintrittsöffnung unterschätzt dann die Tiefe.</p><aside className="knowledge-note"><b>Hämorrhagischer Schock</b><p>Sympathische Kompensation hält den Blutdruck zunächst aufrecht. Tachykardie, blasse-kühle Haut, verlängerte Rekapillarisierung, Unruhe, schwache periphere Pulse und ein ungünstiger Vitaltrend können die Minderperfusion früher zeigen als die Hypotonie.</p></aside></>)}

    {section("04", "Region entscheidet über das Verletzungsmuster", "Symptome der Arbeitsdiagnose", <><div className="pulmo-risk-grid"><div><b>Hals</b><p>Dyspnoe, Stridor, Heiserkeit, Hämoptyse, zunehmendes Hämatom, neurologische Ausfälle oder starke Blutung.</p></div><div><b>Thorax</b><p>Dyspnoe, einseitig vermindertes Atemgeräusch, Thoraxschmerz, Hypoxämie, Instabilität oder gestaute Halsvenen.</p></div><div><b>Abdomen / Flanke / Rücken</b><p>Schmerz, Abwehrspannung, Distension, Eviszeration, Schockzeichen oder zunächst nur diskreter Befund.</p></div><div><b>Extremität / Übergangszone</b><p>Starke Blutung, fehlender Puls, blasse-kalte Extremität, Sensibilitäts- oder Motorikausfall; pDMS im Verlauf.</p></div><div><b>Kopf / Gesicht</b><p>Bewusstseinsstörung, Blutung, Augenverletzung, Liquorzeichen oder drohende Atemwegsverlegung.</p></div><div><b>Allgemeine Schockzeichen</b><p>Tachykardie, Kaltschweißigkeit, Rekapillarisierung verlängert, Unruhe, Durst, Vigilanzabfall; Hypotonie ist ein spätes Zeichen.</p></div></div><aside className="diagnostic-boundary"><span>!</span><div><b>Serienuntersuchung statt Momentaufnahme</b><p>Ein initial weiches Abdomen oder normaler Blutdruck schließt eine relevante penetrierende Verletzung nicht aus. cABCDE und Vitalparameter wiederholt beurteilen.</p></div></aside></>)}

    {section("05", "Sofort lebensbedrohlich und zeitverzögert", "Komplikationen und Gefahren", <><div className="pulmo-risk-grid"><div><b>Massive Blutung</b><p>Äußerlich, intrathorakal, intraabdominell oder retroperitoneal – bis zum Kreislaufstillstand.</p></div><div><b>Spannungspneumothorax</b><p>Steigender intrathorakaler Druck verschlechtert Ventilation und venösen Rückstrom; besonders unter Überdruckbeatmung.</p></div><div><b>Herzbeuteltamponade</b><p>Perikardblut komprimiert das Herz und vermindert Füllung, Schlagvolumen und Herzzeitvolumen.</p></div><div><b>Hämatothorax</b><p>Verbindet Blutverlust mit eingeschränkter Lungenentfaltung.</p></div><div><b>Peritonitis / Sepsis</b><p>Hohlorganinhalt und Keime verursachen im Verlauf lokale Entzündung und gegebenenfalls Organfunktionsstörung.</p></div><div><b>Nerven- und Ischämieschaden</b><p>Gefäß- oder Nervenläsion gefährdet Funktion und Extremität.</p></div></div><h3>Letale Trias</h3><div className="pulmo-vfa-flow"><div><span>01</span><b>Hypothermie</b><small>Exposition und Blutverlust stören Gerinnungsenzyme und Thrombozyten.</small></div><div><span>02</span><b>Azidose</b><small>Minderperfusion führt zu anaerobem Stoffwechsel und Laktatanstieg.</small></div><div><span>03</span><b>Koagulopathie</b><small>Die Blutstillung versagt; weitere Blutung verstärkt Auskühlung und Azidose.</small></div><div><span>↺</span><b>Teufelskreis</b><small>Blutungskontrolle, Wärmeerhalt und definitive Versorgung müssen parallel erfolgen.</small></div></div></>)}

    {section("06", "Material nach Region und Blutungsrisiko", "Einsatzmaterialien", <div className="material-chips">{["PSA und Funk", "Traumatasche", "Sterile Wundauflagen", "Kompressionsverband", "Hämostyptikum / Packing-Gaze", "Tourniquet", "Polstermaterial für Fremdkörper", "Thoraxverband nach lokalem Standard", "Entlastungskanüle nach VFA", "Absaugung / Atemweg", "Sauerstoff / Beatmung", "Monitoring / Kapnografie", "i.v.- / i.o.-Material", "Wärmeerhalt", "TXA-Kurzinfusion", "Analgesie nach VFA", "Vakuummatratze / Trage"].map(item => <span key={item}>{item}</span>)}</div>)}

    {section("07", "Sicherheit, cABCDE und SAMPLERS", "Erstmaßnahmen und Diagnostik", <><aside className="red-flags"><span>!</span><div><small>Vor Patientenkontakt</small><h3>Eigensicherheit und polizeiliche Freigabe</h3><p>Gefahrenbereich, Täter, Waffen, Scherben, Nadeln, aggressive Personen und Rückzugsweg beurteilen. Bei Gewalttaten erst nach Freigabe vorgehen; neue Gefahr beendet die medizinische Annäherung.</p></div></aside><div className="pulmo-care-grid"><div><span>c</span><b>Kritische Blutung</b><small>Direkter Druck, Kompressionsverband; Packing nur in zugänglicher komprimierbarer Wunde, Tourniquet nur an geeigneter Extremität.</small></div><div><span>A</span><b>Atemweg</b><small>Hals- und Gesichtsverletzung, Blut, Schwellung und Aspiration beachten; frühe Eskalation vorbereiten.</small></div><div><span>B</span><b>Atmung</b><small>Thorax inspizieren, auskultieren, SpO₂/Kapnografie; Spannungspneumothorax klinisch erkennen und nach VFA behandeln.</small></div><div><span>C</span><b>Kreislauf</b><small>Weitere Blutungsräume suchen, Zugänge, Trend, TXA-Indikation und zielgerichtete Volumentherapie nach Traumaalgorithmus.</small></div><div><span>D</span><b>Neurologie</b><small>GCS, Pupillen, BZ; pDMS distal bei Extremitätenverletzungen vor und nach Maßnahmen.</small></div><div><span>E</span><b>Entkleiden / Erhalten</b><small>Vorder- und Rückseite untersuchen, jede Wunde dokumentieren und konsequent wärmen.</small></div></div><h3>Fremdkörper und offene Wunden</h3><ul className="script-list"><li><b>Belassen und polstern:</b> Gegenstand nicht entfernen, nicht bewegen und nicht direkt komprimieren.</li><li><b>Kompression um den Gegenstand:</b> Blutung mit Polsterung und Druck auf das umgebende Gewebe kontrollieren.</li><li><b>Nicht blind packen:</b> Thorax, Abdomen und andere Körperhöhlen werden nicht ausgestopft.</li><li><b>Eviszeration:</b> Organe nicht zurückverlagern; feucht-steril, locker und ohne Druck abdecken.</li><li><b>Spuren:</b> Lebensrettung geht vor. Wunde nicht reinigen oder sondieren; Veränderungen sachlich dokumentieren.</li></ul><h3>SAMPLERS · kurz und einsatzrelevant</h3><div className="samplers-grid">{[["S", "Schmerz, Dyspnoe, Blutung, Taubheit"], ["A", "Allergien"], ["M", "Antikoagulanzien / Thrombozytenhemmer"], ["P", "Gerinnung, Vorerkrankungen"], ["L", "Letzte Nahrung / Flüssigkeit"], ["E", "Zeitpunkt, Gegenstand, Verlauf"], ["R", "Risiken, Gewaltlage, weitere Verletzte"], ["S", "Schwangerschaft berücksichtigen"]].map(([label,text]) => <p key={label}><b>{label}</b>{text}</p>)}</div></>)}

    {section("08", "Region, Physiologie und Zeitkritik", "Differenzialdiagnosen und Entscheidungsfindung", <><div className="differential-grid">{["Oberflächliche Schnittwunde", "Schussverletzung", "Pfählungsverletzung", "Spannungspneumothorax", "Hämatothorax", "Herzbeuteltamponade", "Aortendissektion / Aneurysmaruptur", "Stumpfes Thorax- oder Abdominaltrauma", "Hohlorganverletzung", "Isolierte Gefäß- oder Nervenverletzung", "SHT / Intoxikation als Ursache veränderter Vigilanz"].map(item => <span key={item}>{item}</span>)}</div><h3>Entscheidungsweg</h3><div className="pulmo-vfa-flow"><div><span>01</span><b>Ist die Lage sicher?</b><small>Ohne sichere Einsatzstelle kein ungeschützter Patientenzugang.</small></div><div><span>02</span><b>Welche Region?</b><small>Hals, Thorax, Abdomen, Kopf oder Übergangszone bedeuten hohe Organ- und Blutungsgefahr.</small></div><div><span>03</span><b>Ist der Patient instabil?</b><small>Perfusions-, Atem- und Bewusstseinsverlauf zählen mehr als ein einzelner Messwert.</small></div><div><span>04</span><b>Welche reversible Todesursache?</b><small>Komprimierbare Blutung stoppen, Spannung entlasten, Atemweg sichern – Transport parallel vorbereiten.</small></div></div><aside className="knowledge-note"><b>Prüfungsfalle</b><p>Keine Verletzung allein aus Messerlänge, Ein- und Austrittsöffnung oder vermeintlicher Stichrichtung ausschließen. Der Verlauf kann durch Bewegung, Knochenkontakt und Organverschiebung abweichen.</p></aside></>)}

    {section("09", "Blutungskontrolle, Analgesie und Zielklinik", "Weitere Maßnahmen", <><h3>Medikamentenkarte · Tranexamsäure</h3><div className="pulmo-risk-grid"><div><b>Wirkung</b><p>Antifibrinolytikum: besetzt Lysinbindungsstellen am Plasminogen und vermindert dessen Aktivierung zu Plasmin. Bestehendes Fibrin wird langsamer abgebaut.</p></div><div><b>Indikation nach Traumaalgorithmus</b><p>Erwachsene mit lebensbedrohlicher traumatischer Blutung und/oder hypovolämischem Schock.</p></div><div><b>Dosierung und Zubereitung</b><p><b>1 g als Kurzinfusion über 10 Minuten.</b> Die B2A-Anlage zeigt 10 ml Wirkstoff plus 90 ml NaCl 0,9 %.</p></div><div><b>Risiken und Prüfpunkte</b><p>Thromboembolische Ereignisse, Krampfanfälle, Sehstörungen, gastrointestinale Beschwerden und Hypotonie bei zu schneller Gabe; unter anderem akute Thrombose, schwere Nierenfunktionsstörung und Krampfanamnese beachten.</p></div></div><aside className="knowledge-note"><b>TXA ist kein Gefäßverschluss</b><p>Es stabilisiert Gerinnsel, ersetzt aber weder Kompression, Packing oder Tourniquet noch die definitive operative oder interventionelle Blutstillung.</p></aside><h3>Starke Schmerzen</h3><div className="reading-columns"><div><h3>Esketamin · VFA 36</h3><p>Nach Behandlung unmittelbar vitaler cABCDE-Probleme gewichtsbezogen nach VFA, mit Midazolam-Pfad, Monitoring, Beatmungsbereitschaft und Re-Evaluation.</p></div><div><h3>Morphin · VFA 38</h3><p>Langsam i.v. nach Gewichtstabelle; Atmung, Kreislauf, Vigilanz und Wirkung nach fünf Minuten kontrollieren. Wiederholung und Maximaldosis ausschließlich nach VFA.</p></div></div><h3>Kreislaufstrategie und Transport</h3><ul className="script-list"><li><b>Unkontrollierte Blutung ohne führendes SHT:</b> permissive Strategie mit systolischem Zielwert um 80 mmHg nach Traumaalgorithmus.</li><li><b>Führendes oder isoliertes SHT:</b> systolisch mindestens 90 mmHg anstreben.</li><li><b>Load, go and treat:</b> lebensrettende Maßnahmen, Voranmeldung und Transportvorbereitung parallel.</li><li><b>Zielklinik:</b> geeignete Traumaversorgung mit sofortiger chirurgischer/interventioneller Möglichkeit; Region und Instabilität früh melden.</li><li><b>Teamkommunikation:</b> klare Rollen, Closed Loop, gemeinsames Lagebild mit Polizei und Feuerwehr; medizinische Versorgung hat nach Freigabe Vorrang.</li></ul></>)}

    {section("10", "Thüringen 2026/2027", "Verfahrensanweisungen und Anlagen", <><div className="vfa-stack"><Vfa src="/lessons/sht/vfa-trauma-l2.png" alt="Thüringer Leitalgorithmus Trauma L2" caption="L2 · Traumaalgorithmus" /><Vfa src="/lessons/thoraxtrauma/vfa-entlastungspunktion-07.png" alt="Thüringer VFA 07 Entlastungspunktion" caption="VFA 07 · Entlastungspunktion bei Spannungspneumothorax" /><Vfa src="/lessons/sht/vfa-schmerz-basis-35.png" alt="Thüringer VFA 35 starke Schmerzzustände" caption="VFA 35 · Starke Schmerzzustände" /><Vfa src="/lessons/sht/vfa-esketamin-36.png" alt="Thüringer VFA 36 Esketamin" caption="VFA 36 · Esketamin" /><Vfa src="/lessons/sht/vfa-morphin-38.png" alt="Thüringer VFA 38 Morphin" caption="VFA 38 · Morphin" /></div><h3>Zubereitung und Gewichtstabellen</h3><div className="vfa-stack"><Vfa src="/lessons/abdominaltrauma/txa-anlage-b2a.png" alt="Anlage B2A Tranexamsäure" caption="B2A · Tranexamsäure" /><Vfa src="/lessons/sht/medikamentenliste-morphin.png" alt="Anlage B2A Morphin" caption="B2A · Morphin" /><Vfa src="/lessons/wirbelsaeulentrauma/anlage-b2a-esketamin.png" alt="Anlage B2A Esketamin" caption="B2A · Esketamin" /><Vfa src="/lessons/wirbelsaeulentrauma/anlage-b2b-esketamin.png" alt="Anlage B2B Esketamin Gewichtstabelle" caption="B2B · Esketamin" /><Vfa src="/lessons/wirbelsaeulentrauma/anlage-b2b-morphin.png" alt="Anlage B2B Morphin Gewichtstabelle" caption="B2B · Morphin" /></div></>)}

    {children}
    <p className="lesson-source">Hauptgrundlage: bereitgestellte Unterlagen „32. Stichverletzung“. Fachlich abgeglichen mit der <a href="https://register.awmf.org/assets/guidelines/187-023l_S3_Polytrauma-Schwerverletzten-Behandlung_2023-06.pdf" target="_blank" rel="noreferrer">S3-Leitlinie Polytrauma/Schwerverletzten-Behandlung</a>. Dosierungen, Blutdruckziele und Zubereitungen richten sich ausschließlich nach den Thüringer VFA 2026/2027.</p>
  </article>;
}
