import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct?: boolean];
const q = (number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion => ({ id: `stichverletzung-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: options.map(([text, correct]) => ({ text, correct })), source, difficulty });

export const stichverletzungFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "stichverletzung-card-01", area: "Definition", question: "Warum darf die sichtbare Wundgröße nicht zur Einschätzung der Verletzungstiefe verwendet werden?", answer: "Elastische Gewebe können sich nach Passage zusammenziehen. Ein schmaler Wundkanal kann dennoch große Gefäße, Organe oder Körperhöhlen treffen und erheblich innerlich bluten." },
  { id: "stichverletzung-card-02", area: "Fremdkörper", question: "Warum bleibt ein steckender Gegenstand präklinisch im Körper?", answer: "Er kann ein verletztes Gefäß tamponieren. Entfernung kann eine massive Blutung auslösen und gehört unter kontrollierte klinische Bedingungen. Der Gegenstand wird stabilisiert und nicht direkt komprimiert." },
  { id: "stichverletzung-card-03", area: "Eigenschutz", question: "Welche Sicherheitsfragen müssen vor dem Patientenkontakt geklärt sein?", answer: "Ist die Lage polizeilich freigegeben? Gibt es Täter, Waffen, Scherben, Nadeln, aggressive Personen oder weitere Gefahren? Wo sind Rückzugsweg und Bereitstellungsraum?" },
  { id: "stichverletzung-card-04", area: "Thorax", question: "Welche vier vitalen Thoraxkomplikationen müssen bei einer Stichverletzung bedacht werden?", answer: "Spannungspneumothorax, Hämatothorax, Herzbeuteltamponade und Verletzung großer Gefäße; mehrere können gleichzeitig vorliegen." },
  { id: "stichverletzung-card-05", area: "Abdomen", question: "Warum kann eine abdominelle Stichverletzung anfangs klinisch unauffällig wirken?", answer: "Blut kann intraabdominell oder retroperitoneal verborgen bleiben; Peritonealreizung und Hohlorganfolgen können sich verzögert entwickeln. Ein weiches Abdomen schließt die Verletzung nicht aus." },
  { id: "stichverletzung-card-06", area: "Blutung", question: "Wo ist Wundpacking sinnvoll und wo nicht?", answer: "Bei zugänglichen tiefen, komprimierbaren Wunden, besonders an Extremitäten oder Übergangszonen. Nicht blind in Thorax, Abdomen oder andere Körperhöhlen packen." },
  { id: "stichverletzung-card-07", area: "Schock", question: "Welche frühen Zeichen sprechen trotz normalen Blutdrucks für hämorrhagischen Schock?", answer: "Tachykardie, schwache periphere Pulse, blasse-kühle oder kaltschweißige Haut, verlängerte Rekapillarisierung, Unruhe und Vigilanzveränderung sowie ein ungünstiger Trend." },
  { id: "stichverletzung-card-08", area: "Extremität", question: "Was wird bei einer Stichverletzung einer Extremität zusätzlich dokumentiert?", answer: "pDMS – periphere Durchblutung, Motorik und Sensibilität – vor und nach Verband, Kompression, Tourniquet oder Schienung." },
  { id: "stichverletzung-card-09", area: "Eviszeration", question: "Wie werden ausgetretene Bauchorgane versorgt?", answer: "Nicht zurückverlagern, nicht komprimieren und nicht manipulieren; feucht-steril und locker abdecken, Wärmeerhalt und rascher Transport." },
  { id: "stichverletzung-card-10", area: "TXA", question: "Wann und wie nennt der Thüringer Traumaalgorithmus Tranexamsäure?", answer: "Bei erwachsenen Traumapatienten mit lebensbedrohlicher Blutung und/oder hypovolämischem Schock: 1 g als Kurzinfusion über 10 Minuten; mechanische Blutungskontrolle bleibt erforderlich." },
  { id: "stichverletzung-card-11", area: "Kreislauf", question: "Welche systolischen Zielwerte unterscheiden sich bei unkontrollierter Blutung und führendem SHT?", answer: "Ohne führendes SHT etwa 80 mmHg; bei führendem oder isoliertem SHT mindestens 90 mmHg – jeweils nach Thüringer Traumaalgorithmus und klinischem Verlauf." },
  { id: "stichverletzung-card-12", area: "Letale Trias", question: "Wie verstärken sich Hypothermie, Azidose und Koagulopathie?", answer: "Auskühlung und Azidose verschlechtern Gerinnungsenzyme und Thrombozyten; zunehmende Blutung verstärkt Hypoperfusion, Azidose und Wärmeverlust – ein selbstverstärkender Kreislauf." },
  { id: "stichverletzung-card-13", area: "Analgesie", question: "Welche Grundsätze gelten für die Analgesie bei Stichverletzung?", answer: "Zuerst reversible cABCDE-Lebensgefahren behandeln, dann VFA 35 mit Esketamin- oder Morphinpfad, Monitoring, Beatmungsbereitschaft und wiederholte Wirkungskontrolle." },
  { id: "stichverletzung-card-14", area: "Transport", question: "Was bedeutet Load, go and treat bei einer kritischen Stichverletzung?", answer: "Nur unmittelbar lebensrettende Maßnahmen vor Ort; Blutungskontrolle, Wärmeerhalt, Analgesie, Voranmeldung und Transportvorbereitung laufen parallel zur raschen definitiven chirurgischen Versorgung." },
  { id: "stichverletzung-card-15", area: "Spuren", question: "Wie werden medizinische Versorgung und Spurenerhalt vereinbart?", answer: "Lebensrettung hat Vorrang. Wunden nicht unnötig reinigen oder sondieren, Gegenstände belassen, Kleidung möglichst nicht durch die Wunde schneiden und alle Veränderungen dokumentieren." },
];

export const stichverletzungQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen zur Beurteilung einer Stichverletzung sind richtig?", [["Eine kleine Hautöffnung kann mit einer schweren Organverletzung einhergehen", true], ["Wenig äußere Blutung schließt eine innere Blutung nicht aus", true], ["Der Wundkanal lässt sich aus der sichtbaren Stichrichtung sicher rekonstruieren"], ["Der Vitaltrend ist wichtiger als ein einzelner Normalwert", true], ["Die Messerlänge beweist die erreichte Organtiefe"]], "Äußere Wunde, angenommene Richtung und Gegenstandslänge bilden den inneren Schaden nicht zuverlässig ab."),
  q(2, "Welche Maßnahmen sind bei einer Stichverletzung im Rahmen einer Gewalttat richtig?", [["Polizeiliche Freigabe vor dem Vorgehen abwarten", true], ["Rückzugsweg und Bereitstellungsraum festlegen", true], ["Weitere Täter oder Waffen mitdenken", true], ["Zur Zeitersparnis allein in den ungesicherten Bereich gehen"], ["Bei neuer Gefahr die Sicherheit erneut herstellen", true]], "Eigenschutz und sichere Lage gehen dem Patientenzugang voraus."),
  q(3, "Ein Messer steckt noch im Thorax. Welche Aussagen stimmen?", [["Das Messer bleibt grundsätzlich in situ", true], ["Es wird gegen Bewegung gepolstert und stabilisiert", true], ["Direkter Druck auf den Gegenstand ist zu vermeiden", true], ["Zur Beurteilung der Tiefe wird es kurz herausgezogen"], ["Entfernung kann eine tamponierende Wirkung aufheben", true]], "Steckende Fremdkörper werden präklinisch nicht entfernt oder bewegt."),
  q(4, "Welche Folgen sind nach einer thorakalen Stichverletzung gleichzeitig möglich?", [["Pneumothorax", true], ["Hämatothorax", true], ["Herzbeuteltamponade", true], ["Verletzung großer Gefäße", true], ["Eine kleine Wunde schließt kombinierte Schäden aus"]], "Penetrierende Thoraxverletzungen können respiratorische und zirkulatorische Ursachen kombinieren."),
  q(5, "Welche Konstellation stützt klinisch den Verdacht auf einen Spannungspneumothorax?", [["Einseitig deutlich vermindertes Atemgeräusch", true], ["Hämodynamische Instabilität", true], ["Akute Verschlechterung unter Überdruckbeatmung", true], ["Isolierter lokaler Schmerz bei stabilem Verlauf"], ["Passender Mechanismus ohne notwendige Röntgenbestätigung", true]], "Die vital bedrohliche Spannung wird klinisch erkannt und nach VFA behandelt."),
  q(6, "Welche Befunde passen eher zu einer Herzbeuteltamponade nach Stichverletzung?", [["Kreislaufinstabilität bei penetrierender präkordialer Verletzung", true], ["Zunehmende Zeichen verminderten Herzzeitvolumens", true], ["Gestaute Halsvenen können auftreten", true], ["Ein fehlendes klassisches Vollbild schließt die Tamponade sicher aus"], ["Ein unauffälliges Atemgeräusch widerlegt die Tamponade"]], "Klassische Zeichen können unvollständig sein; Region, Physiologie und Verlauf bestimmen den Verdacht."),
  q(7, "Welche Aussagen gelten für eine abdominelle Stichverletzung?", [["Ein weiches Abdomen schließt eine relevante Verletzung nicht aus", true], ["Retroperitoneale Blutungen können äußerlich verborgen bleiben", true], ["Hohlorganverletzungen können verzögert peritoneale Zeichen verursachen", true], ["Fehlende Abwehrspannung beendet die Verlaufskontrolle"], ["Leber, Milz, Mesenterium und große Gefäße haben relevantes Blutungspotenzial", true]], "Der Abdominalbefund ist dynamisch und wird seriell beurteilt."),
  q(8, "Wie wird eine Eviszeration nach Bauchstich versorgt?", [["Ausgetretene Organe nicht zurückverlagern", true], ["Feucht-steril und locker abdecken", true], ["Direkten Druck auf die Organe vermeiden", true], ["Organe zur Kontaminationsreduktion kräftig spülen"], ["Wärmeerhalt und schneller Transport", true]], "Manipulation und Kompression sind zu vermeiden; definitive Versorgung erfolgt chirurgisch."),
  q(9, "Welche Aussagen grenzen Wundpacking korrekt ab?", [["Es eignet sich für zugängliche tiefe, komprimierbare Wunden", true], ["Nach dem Packing ist anhaltender Druck erforderlich", true], ["Hämostyptische Gaze kann unterstützen", true], ["Eine Thoraxhöhle wird blind ausgestopft"], ["Nichtkomprimierbare Rumpfblutung braucht rasche definitive Versorgung", true]], "Packing ist eine Maßnahme für komprimierbare Wunden, nicht für Körperhöhlen."),
  q(10, "Welche Schritte passen zu einer lebensbedrohlichen Extremitätenblutung?", [["Sofort direkter Druck", true], ["Kompressionsverband oder geeignetes Packing", true], ["Tourniquet bei nicht kontrollierbarer lebensbedrohlicher Blutung", true], ["pDMS und Anlagezeit dokumentieren", true], ["Tourniquet routinemäßig alle zehn Minuten lösen"]], "Blutungskontrolle folgt einer wirksamen Eskalation; ein effektives Tourniquet wird nicht routinemäßig gelöst."),
  q(11, "Welche Befunde können einen kompensierten hämorrhagischen Schock anzeigen?", [["Tachykardie und schwache periphere Pulse", true], ["Blasse, kühle oder kaltschweißige Haut", true], ["Verlängerte Rekapillarisierung", true], ["Unruhe oder Vigilanzabnahme", true], ["Ein normaler Einzelblutdruck schließt den Schock aus"]], "Perfusionszeichen und Trend können die Dekompensation früher zeigen als die Hypotonie."),
  q(12, "Welche Zusammenhänge der letalen Trias sind richtig?", [["Hypothermie beeinträchtigt Gerinnungsenzyme und Thrombozyten", true], ["Hypoperfusion fördert anaeroben Stoffwechsel und Azidose", true], ["Koagulopathie verstärkt die weitere Blutung", true], ["Wärmeerhalt ist erst nach Blutdrucknormalisierung relevant"], ["Die drei Faktoren verstärken sich gegenseitig", true]], "Blutungskontrolle und Wärmeerhalt unterbrechen den selbstverstärkenden Kreislauf."),
  q(13, "Welche Maßnahmen gehören zur schnellen Traumauntersuchung?", [["Vorder- und Rückseite standardisiert untersuchen", true], ["Alle Wunden erfassen und dokumentieren", true], ["Thorax, Abdomen, Becken und Extremitäten beurteilen", true], ["Nach dem Bodycheck cABCDE erneut beginnen", true], ["Jede Wunde mit einer Sonde auf Tiefe prüfen"]], "Der Bodycheck findet weitere Verletzungen, ohne Wunden zu explorieren."),
  q(14, "Welche Befunde einer Halsstichverletzung sind besonders kritisch?", [["Zunehmendes Hämatom", true], ["Stridor oder Heiserkeit", true], ["Hämoptyse oder Luftaustritt", true], ["Neurologische Defizite", true], ["Eine kleine Eintrittsöffnung ohne Blutung beendet die Atemwegsbeobachtung"]], "Halsverletzungen können Atemweg, Gefäße, Nerven, Ösophagus und Trachea gefährden."),
  q(15, "Welche Aussagen zur pDMS-Kontrolle sind richtig?", [["Sie prüft periphere Durchblutung, Motorik und Sensibilität", true], ["Sie wird vor und nach Verband oder Tourniquet dokumentiert", true], ["Sie hilft Gefäß- und Nervenläsionen zu erkennen", true], ["Ein tastbarer Puls schließt jede Gefäßverletzung aus"], ["Verlauf und Seitenvergleich sind relevant", true]], "pDMS ist ein Verlaufsbefund und ersetzt keine Gesamtbeurteilung."),
  q(16, "Wann ist Tranexamsäure im Traumaalgorithmus passend?", [["Bei erwachsenen Traumapatienten mit lebensbedrohlicher Blutung", true], ["Bei hypovolämischem Schock nach Trauma", true], ["Als 1 g Kurzinfusion über 10 Minuten", true], ["Als Ersatz für mechanische Blutungskontrolle"], ["Nicht pauschal bei jeder oberflächlichen Stichwunde", true]], "TXA ergänzt die Blutungskontrolle bei passender VFA-Indikation."),
  q(17, "Welche Kreislaufziele passen zur Thüringer Traumaversorgung?", [["Bei unkontrollierter Blutung ohne führendes SHT systolisch etwa 80 mmHg", true], ["Bei führendem oder isoliertem SHT systolisch mindestens 90 mmHg", true], ["Volumen und Verlauf werden zielgerichtet re-evaluiert", true], ["Jede traumatische Blutung wird sofort auf 120 mmHg systolisch angehoben"], ["Die Blutdruckstrategie ersetzt keine Blutungskontrolle"]], "Perfusionsziel und SHT-Sonderfall werden unterschieden; definitive Blutstillung bleibt entscheidend."),
  q(18, "Welche Grundsätze gelten für die Analgesie?", [["Unmittelbar lebensbedrohliche cABCDE-Probleme werden zuerst behandelt", true], ["Esketamin oder Morphin werden nach dem passenden VFA-Pfad dosiert", true], ["Monitoring und Beatmungsbereitschaft bleiben erforderlich", true], ["Wirkung und Nebenwirkungen werden re-evaluiert", true], ["Analgesie macht eine operative Versorgung entbehrlich"]], "Analgesie ergänzt, aber ersetzt weder Ursachenbehandlung noch Transport."),
  q(19, "Welche Aussagen zu Sauerstoff und Beatmung sind fachlich richtig?", [["Sauerstoff wird an Oxygenierung und klinischen Befund angepasst", true], ["Bei Ateminsuffizienz wird das Atemwegs- und Beatmungsmanagement eskaliert", true], ["Überdruckbeatmung kann einen Spannungspneumothorax verschärfen", true], ["Jede Stichverletzung erfordert unabhängig vom Befund zwingend 15 l/min Sauerstoff"], ["Kapnografie unterstützt bei Beatmung und Analgosedierung", true]], "Therapie richtet sich nach Physiologie und VFA, nicht nach einer pauschalen Flussrate."),
  q(20, "Welche Aussagen zu Infektion und Sepsis stimmen?", [["Kontamination und Hohlorganverletzung erhöhen das Infektionsrisiko", true], ["Peritonitis kann sich zeitverzögert entwickeln", true], ["Sepsis ist eher eine mögliche Verlaufskomplikation als typischer Sofortbefund", true], ["Präklinische Wundsondierung senkt zuverlässig das Infektionsrisiko"], ["Sterile Abdeckung und rasche definitive Versorgung sind wichtig", true]], "Akut dominieren Blutung und Organverletzung; Infektion und Sepsis bleiben relevante spätere Gefahren."),
  q(21, "Welche Aussagen verbinden Versorgung und Spurenerhalt korrekt?", [["Lebensrettende Maßnahmen haben Vorrang", true], ["Wunden werden nicht unnötig gereinigt oder sondiert", true], ["Veränderungen und Fundstücke werden dokumentiert", true], ["Kleidung wird möglichst nicht durch sichtbare Wundöffnungen geschnitten", true], ["Medizinische Maßnahmen warten grundsätzlich auf die vollständige Spurensicherung"]], "Nach Freigabe gilt Leben vor Spur; unnötige Veränderungen werden vermieden."),
  q(22, "Welche Kriterien sprechen für zeitkritischen Transport in ein geeignetes Traumazentrum?", [["Unkontrollierte oder rezidivierende kritische Blutung", true], ["Hals-, Thorax-, Abdomen-, Kopf- oder Übergangszonenverletzung", true], ["Schockzeichen oder negativer Vitaltrend", true], ["Neurologischer oder distaler vaskulärer Ausfall", true], ["Ausschließlich eine oberflächliche stabile Hautläsion ohne weitere Auffälligkeit"]], "Region, Physiologie, Verlauf und vermutete Begleitverletzung bestimmen die Zielklinik."),
  q(23, "Welche Aussagen kennzeichnen Load, go and treat?", [["Lebensrettende Maßnahmen und Transportvorbereitung laufen parallel", true], ["Die Zielklinik wird früh vorangemeldet", true], ["Nicht zwingende Maßnahmen dürfen die definitive Versorgung nicht verzögern", true], ["cABCDE wird während des Transports wiederholt", true], ["Vor Abfahrt muss der vollständige Wundkanal diagnostiziert sein"]], "Bei kritischem penetrierendem Trauma zählt die Zeit zur definitiven Blutungs- und Organversorgung."),
  q(24, "Welche Aussagen sind typische Prüfungsfallen bei Stichverletzungen?", [["Eine gefundene Wunde beendet den Bodycheck nicht", true], ["Ein normaler Blutdruck kann einen kompensierten Schock verdecken", true], ["Ein Fremdkörper kann tamponieren und bleibt deshalb liegen", true], ["Fehlende Abwehrspannung schließt eine Bauchorganverletzung aus"], ["Thorax- und Abdomenwunden werden nicht blind gepackt", true]], "Dynamische Gesamtbeurteilung verhindert gefährliche Fehlschlüsse aus Einzelbefunden."),
];
