export type TerminologyFlashcard = { id: string; area: string; question: string; answer: string };

export type TerminologyQuestion = {
  id: string;
  prompt: string;
  options: { text: string; correct?: boolean }[];
  source: string;
  difficulty: 1 | 2 | 3;
  mode: "multiple";
};

export const terminologyFlashcards: TerminologyFlashcard[] = [
  { id: "term-card-01", area: "Grundlagen", question: "Was bedeuten Terminologie und Nomenklatur?", answer: "Terminologie ist die Lehre beziehungsweise das geordnete System der Fachbegriffe eines Fachgebiets. Eine Nomenklatur ist ein verbindlich oder systematisch geordnetes Verzeichnis von Benennungen, beispielsweise die anatomische Nomenklatur." },
  { id: "term-card-02", area: "Grundlagen", question: "Welche Grundprinzipien soll medizinische Fachsprache erfüllen?", answer: "Sachlichkeit, Eindeutigkeit, Systematik, Präzision und möglichst ökonomische Verständigung. Ein Begriff soll im Kontext klar sein und Missverständnisse in Dokumentation und Übergabe reduzieren." },
  { id: "term-card-03", area: "Grundlagen", question: "Warum nutzt die Medizin viele lateinische und griechische Wortbestandteile?", answer: "Sie ermöglichen international wiedererkennbare, systematisch zusammensetzbare und relativ sprachunabhängige Begriffe. Die Bedeutung wird häufig aus Präfix, Wortstamm und Suffix erschlossen." },
  { id: "term-card-04", area: "Grundlagen", question: "Was sind Nomina anatomica und pathologische Fachbegriffe?", answer: "Nomina anatomica bezeichnen regelhaft Strukturen und Lagebeziehungen des Körpers. Pathologische Fachbegriffe beschreiben Krankheiten, Ursachen, Veränderungen, Symptome oder Krankheitsprozesse." },
  { id: "term-card-05", area: "Wortbildung", question: "Welche Funktion haben Präfix, Wortstamm und Suffix?", answer: "Das Präfix steht vor dem Stamm und verändert etwa Lage, Menge oder Zeitbezug. Der Wortstamm trägt die Kernbedeutung. Das Suffix kennzeichnet beispielsweise Vorgang, Zustand, Entzündung oder Fachgebiet." },
  { id: "term-card-06", area: "Wortbildung", question: "Was bedeutet peri-?", answer: "Um … herum beziehungsweise die Umgebung betreffend, zum Beispiel Perikard: Hülle um das Herz." },
  { id: "term-card-07", area: "Wortbildung", question: "Was bedeuten supra-, infra-, intra- und extra-?", answer: "Supra-: oberhalb. Infra-: unterhalb. Intra-: innerhalb. Extra-: außerhalb beziehungsweise zusätzlich, abhängig vom Kontext." },
  { id: "term-card-08", area: "Wortbildung", question: "Was bedeuten ante-, post- und ad-?", answer: "Ante-: vor. Post-: nach beziehungsweise hinter. Ad-: zu, an oder heran. Die genaue Übersetzung ergibt sich aus dem Gesamtbegriff." },
  { id: "term-card-09", area: "Wortbildung", question: "Was bedeuten -logie und -spiratio?", answer: "-logie bezeichnet die Lehre oder Wissenschaft eines Gebiets. Spiratio bedeutet Atmung; Inspiration ist Einatmung, Exspiration Ausatmung." },
  { id: "term-card-10", area: "Anatomie", question: "Welche lateinischen beziehungsweise griechischen Bezeichnungen gehören zu Niere, Leber, Herz und Großhirn?", answer: "Niere: ren beziehungsweise nephr-. Leber: hepar beziehungsweise hepat-. Herz: cor beziehungsweise kardi-. Großhirn: cerebrum beziehungsweise enzephal-/zerebr-." },
  { id: "term-card-11", area: "Anatomie", question: "Welche Fachwörter gehören zu Milz, Brustkorb, Ast und Stamm?", answer: "Milz: lien beziehungsweise splen-. Brustkorb: thorax. Ast: ramus. Stamm: truncus." },
  { id: "term-card-12", area: "Anatomie", question: "Was bedeuten radix und sinus anatomisch?", answer: "Radix bedeutet Wurzel beziehungsweise Ursprung. Sinus bezeichnet je nach Kontext einen Hohlraum, Kanal oder erweiterten venösen Raum; die pauschale Übersetzung nur als ‚Sammelort‘ ist zu eng." },
  { id: "term-card-13", area: "Benennungen", question: "Was sind Synonym, Homonym und Eponym?", answer: "Synonyme sind verschiedene Wörter mit gleicher oder sehr ähnlicher Bedeutung. Ein Homonym ist dieselbe Wortform mit unterschiedlichen Bedeutungen. Ein Eponym ist eine Benennung nach einer Person, etwa Morbus Parkinson." },
  { id: "term-card-14", area: "Benennungen", question: "Was ist eine Metonymie?", answer: "Eine Metonymie ersetzt einen Ausdruck durch einen sachlich eng verbundenen anderen Ausdruck, beispielsweise ‚das EKG zeigt‘ statt ‚die EKG-Aufzeichnung zeigt‘. Sie ist nicht einfach jede bildhafte Darstellung." },
  { id: "term-card-15", area: "Kommunikation", question: "Welche Funktionen kann Sprache erfüllen?", answer: "Deskriptiv/informativ: Sachverhalte mitteilen. Expressiv: innere Zustände ausdrücken. Kommunikativ/sozial: Beziehung und Verständigung herstellen. Argumentativ/kritisch: Positionen begründen, vergleichen und hinterfragen." },
  { id: "term-card-16", area: "Kommunikation", question: "Wie unterscheiden sich lokutionärer, illokutionärer und perlokutionärer Sprechakt?", answer: "Lokution: das tatsächlich Gesagte mit sprachlicher Bedeutung. Illokution: die damit vollzogene Handlung oder Absicht, etwa warnen oder auffordern. Perlokution: die beim Gegenüber erzielte Wirkung, etwa Beruhigung oder Verhaltensänderung. ‚Militärstil‘ ist keine korrekte Definition." },
  { id: "term-card-17", area: "Kommunikation", question: "Was bedeuten aktiver und passiver Wortschatz?", answer: "Aktiver Wortschatz wird selbstständig korrekt verwendet. Passiver Wortschatz wird verstanden, aber nicht oder kaum selbst benutzt." },
  { id: "term-card-18", area: "Kommunikation", question: "Was beschreiben elaborierter und restringierter Sprachcode?", answer: "Die Begriffe stammen aus der Soziolinguistik. Elaboriert bezeichnet eher explizite, differenzierte und kontextunabhängige Formulierungen; restringiert eher knappe, kontextgebundene Ausdrucksweisen. Beides darf nicht als Bewertung von Intelligenz oder Person missverstanden werden." },
  { id: "term-card-19", area: "Epidemiologie", question: "Was ist Inzidenz?", answer: "Die Zahl neu auftretender Krankheitsfälle in einer definierten Population innerhalb eines festgelegten Zeitraums. Als Inzidenzrate wird sie auf die beobachtete Population beziehungsweise Personenzeit bezogen." },
  { id: "term-card-20", area: "Epidemiologie", question: "Was ist Prävalenz?", answer: "Der Anteil beziehungsweise die Häufigkeit aller bestehenden Fälle einer Krankheit in einer definierten Population zu einem Zeitpunkt oder während eines Zeitraums." },
  { id: "term-card-21", area: "Epidemiologie", question: "Was bedeuten Morbidität und Mortalität?", answer: "Morbidität beschreibt Krankheitshäufigkeit beziehungsweise Krankheitslast in einer Population. Mortalität beschreibt Sterbefälle in einer Population innerhalb eines definierten Zeitraums, meist bezogen auf die Gesamtpopulation." },
  { id: "term-card-22", area: "Epidemiologie", question: "Was bedeuten Letalität und Letalitätsrate?", answer: "Letalität ist die Tödlichkeit einer Erkrankung. Die Letalitätsrate setzt die an dieser Erkrankung Verstorbenen ins Verhältnis zu allen an dieser Erkrankung Erkrankten, nicht zur Gesamtbevölkerung." },
  { id: "term-card-23", area: "Epidemiologie", question: "Was bedeutet Vulnerabilität?", answer: "Erhöhte Verletzlichkeit oder Anfälligkeit gegenüber gesundheitlichen Schäden. Sie kann durch biologische, psychische, soziale oder umweltbezogene Faktoren entstehen und ist mehr als nur Krankheitsanfälligkeit." },
  { id: "term-card-24", area: "Epidemiologie", question: "Was bedeutet Exposition?", answer: "Kontakt beziehungsweise Ausgesetztsein gegenüber einem äußeren Einfluss oder Risikofaktor, etwa einem Gefahrstoff, Erreger, Lärm oder Strahlung. Exposition bedeutet noch nicht automatisch Erkrankung." },
  { id: "term-card-25", area: "Gesundheit", question: "Wie definiert die WHO Gesundheit?", answer: "Als Zustand vollständigen körperlichen, geistigen und sozialen Wohlbefindens und nicht lediglich als Freisein von Krankheit oder Gebrechen. Die Formulierung ist ein normatives Gesundheitsverständnis, kein einzelner klinischer Messwert." },
  { id: "term-card-26", area: "Gesundheit", question: "Was ist das biomedizinische Gesundheitsverständnis?", answer: "Es betrachtet Gesundheit vereinfacht vor allem als Abwesenheit feststellbarer Krankheit oder Funktionsstörung. Dieses Modell ist enger als das biopsychosoziale beziehungsweise WHO-Verständnis." },
  { id: "term-card-27", area: "Therapie", question: "Wie unterscheiden sich kausale, symptomatische und palliative Therapie?", answer: "Kausal behandelt die Ursache. Symptomatisch lindert Krankheitszeichen, ohne zwingend die Ursache zu beseitigen. Palliativ zielt bei nicht heilbarer, lebensbegrenzender Erkrankung auf Lebensqualität und Linderung belastender Symptome sowie psychosoziale Unterstützung." },
  { id: "term-card-28", area: "Therapie", question: "Was bedeutet diätetische Therapie?", answer: "Gezielte Veränderung von Ernährung und Nährstoffzufuhr zur Prävention oder Behandlung. Sie ist nicht gleichbedeutend mit jeder allgemeinen Veränderung der Lebensweise." },
  { id: "term-card-29", area: "Prävention", question: "Was ist Primärprävention?", answer: "Maßnahmen vor Entstehung einer Krankheit, die Risikofaktoren verringern oder Schutzfaktoren stärken, beispielsweise Impfung oder Rauchprävention." },
  { id: "term-card-30", area: "Prävention", question: "Was ist Sekundärprävention?", answer: "Früherkennung und frühe Behandlung einer bereits begonnenen, häufig noch symptomarmen Erkrankung, um Fortschreiten und Folgen zu verhindern, beispielsweise durch Darmkrebsfrüherkennung." },
  { id: "term-card-31", area: "Prävention", question: "Was ist Tertiärprävention?", answer: "Maßnahmen nach manifester Erkrankung zur Begrenzung von Folgeschäden, Rückfällen und Teilhabeeinschränkungen, einschließlich Rehabilitation." },
  { id: "term-card-32", area: "Entzündung", question: "Wie heißen die fünf klassischen Entzündungszeichen?", answer: "Rubor: Rötung. Calor: Überwärmung. Tumor: Schwellung. Dolor: Schmerz. Functio laesa: Funktionsverlust beziehungsweise Funktionseinschränkung." },
  { id: "term-card-33", area: "Atmung", question: "Wie unterscheiden sich Hypoxämie und Hypoxie?", answer: "Hypoxämie bezeichnet primär einen erniedrigten Sauerstoffpartialdruck im arteriellen Blut. Hypoxie bezeichnet eine unzureichende Sauerstoffversorgung des Gewebes. Eine Hypoxämie kann Hypoxie verursachen; umgekehrt kann Gewebehypoxie etwa bei Anämie, Kohlenmonoxidvergiftung oder Minderperfusion trotz unauffälligem PaO₂ bestehen." },
  { id: "term-card-34", area: "Beziehung", question: "Wie unterscheiden sich Empathie und Sympathie?", answer: "Empathie ist das verstehende Einfühlen in Erleben und Perspektive einer Person, ohne diese Gefühle vollständig zu übernehmen. Sympathie ist persönliche Zuneigung beziehungsweise positives Mitgefühl." },
  { id: "term-card-35", area: "Evidenz", question: "Was bedeutet Evidenz in der evidenzbasierten Medizin?", answer: "Systematisch gewonnene und kritisch bewertete wissenschaftliche Erkenntnisse. Evidenzbasierte Entscheidungen verbinden bestmögliche externe Evidenz mit klinischer Expertise sowie Werten und Präferenzen der Patienten." },
  { id: "term-card-36", area: "Evidenz", question: "Wie unterscheiden sich Leitlinie, Richtlinie und Standard?", answer: "Leitlinien sind systematisch entwickelte Entscheidungshilfen und erlauben begründete Abweichungen. Richtlinien sind im jeweiligen Geltungsbereich rechtlich oder institutionell verbindlich. Ein Standard beschreibt ein festgelegtes fachliches Qualitätsniveau beziehungsweise erwartetes Vorgehen; seine Bindung hängt vom Kontext ab." },
  { id: "term-card-37", area: "Farbstämme", question: "Welche Wortstämme bedeuten weiß, schwarz, grau, grün und rot?", answer: "Weiß: leuk-/alb-. Schwarz: melan-/nigr-. Grau: poli-/grise-. Grün beziehungsweise blaugrün: glauk-. Rot: erythr-/rubr-. Die konkrete Form richtet sich nach dem zusammengesetzten Begriff." },
  { id: "term-card-38", area: "Krankheitslehre", question: "Nach welchen Gesichtspunkten lassen sich Krankheiten beschreiben?", answer: "Topografie beziehungsweise Lokalisation, Ätiologie beziehungsweise Ursache, Pathogenese beziehungsweise Entstehungsmechanismus, Morphologie beziehungsweise strukturelle Veränderung sowie Funktion, Verlauf und klinische Ausprägung." },
];

export const terminologyQuestions: TerminologyQuestion[] = [
  { id: "term-q-01", prompt: "Welche Aussagen zu Terminologie und Nomenklatur sind fachlich richtig?", options: [{ text: "Terminologie umfasst Fachbegriffe und ihre systematische Verwendung.", correct: true }, { text: "Eine Nomenklatur ist ein geordnetes Benennungssystem.", correct: true }, { text: "Eindeutigkeit und Systematik sind zentrale Ziele medizinischer Fachsprache.", correct: true }, { text: "Eponyme sind immer eindeutiger als systematische Bezeichnungen." }], source: "Terminologie ordnet Fachbegriffe; Nomenklaturen vereinheitlichen Benennungen. Eponyme können historisch gebräuchlich, aber ohne Kontext weniger aussagekräftig sein.", difficulty: 2, mode: "multiple" },
  { id: "term-q-02", prompt: "Welche Zerlegungen medizinischer Begriffe sind korrekt?", options: [{ text: "Perikard: peri- bezeichnet die Lage um das Herz.", correct: true }, { text: "Intravenös: intra- bedeutet innerhalb, venös bezieht sich auf eine Vene.", correct: true }, { text: "Suprapubisch: supra- bedeutet oberhalb.", correct: true }, { text: "Exspiration: extra- bedeutet außerhalb." }], source: "Präfix, Stamm und Suffix müssen im Gesamtbegriff beurteilt werden. Exspiration enthält ex- im Sinn von heraus und spiratio für Atmung, nicht das Präfix extra-.", difficulty: 3, mode: "multiple" },
  { id: "term-q-03", prompt: "Welche Begriffspaare sind richtig zugeordnet?", options: [{ text: "Ren / nephr- – Niere", correct: true }, { text: "Hepar / hepat- – Leber", correct: true }, { text: "Cor / kardi- – Herz", correct: true }, { text: "Lien / splen- – Lunge" }], source: "Lien und splen- bezeichnen die Milz; die Lunge wird unter anderem mit pulmo beziehungsweise pneumon- bezeichnet.", difficulty: 2, mode: "multiple" },
  { id: "term-q-04", prompt: "Welche Aussagen zu Synonym, Homonym, Eponym und Metonymie stimmen?", options: [{ text: "Synonyme besitzen gleiche oder sehr ähnliche Bedeutung.", correct: true }, { text: "Homonyme haben dieselbe Wortform, aber verschiedene Bedeutungen.", correct: true }, { text: "Ein Eponym ist nach einer Person benannt.", correct: true }, { text: "Metonymie ist stets eine anatomische Benennung nach einer Person." }], source: "Metonymie beruht auf sachlicher Nähe; eine Personenbenennung ist ein Eponym.", difficulty: 2, mode: "multiple" },
  { id: "term-q-05", prompt: "Welche Zuordnungen der Sprechakttheorie sind korrekt?", options: [{ text: "Lokution: sprachlich geäußerte Aussage und ihre Bedeutung.", correct: true }, { text: "Illokution: mit der Äußerung vollzogene Absicht, etwa warnen.", correct: true }, { text: "Perlokution: beim Gegenüber erzielte Wirkung.", correct: true }, { text: "Perlokution bedeutet grundsätzlich militärischen Befehlston." }], source: "Die drei Ebenen unterscheiden Äußerung, kommunikative Handlung und Wirkung. Ein bestimmter Sprachstil ist keine Definition der Perlokution.", difficulty: 3, mode: "multiple" },
  { id: "term-q-06", prompt: "Welche Aussagen zu Inzidenz und Prävalenz treffen zu?", options: [{ text: "Inzidenz betrachtet neu auftretende Fälle in einem definierten Zeitraum.", correct: true }, { text: "Prävalenz umfasst bestehende Fälle in einer definierten Population.", correct: true }, { text: "Eine lange Krankheitsdauer kann die Prävalenz erhöhen.", correct: true }, { text: "Inzidenz und Prävalenz sind immer identisch, wenn dieselbe Krankheit betrachtet wird." }], source: "Inzidenz misst Neuerkrankungsgeschehen, Prävalenz den Bestand. Krankheitsdauer und Heilung beziehungsweise Tod beeinflussen die Prävalenz.", difficulty: 3, mode: "multiple" },
  { id: "term-q-07", prompt: "Welche Nenner unterscheiden Mortalität und Letalität?", options: [{ text: "Mortalität bezieht Todesfälle auf eine Population.", correct: true }, { text: "Letalität bezieht krankheitsbezogene Todesfälle auf die Erkrankten.", correct: true }, { text: "Eine Krankheit kann hohe Letalität, aber geringe bevölkerungsbezogene Mortalität haben.", correct: true }, { text: "Letalität wird immer auf alle Einwohner eines Landes bezogen." }], source: "Mortalität ist populationsbezogen, Letalität fallbezogen. Deshalb können sich beide Maßzahlen deutlich unterscheiden.", difficulty: 3, mode: "multiple" },
  { id: "term-q-08", prompt: "Welche Aussagen zu Vulnerabilität und Exposition sind richtig?", options: [{ text: "Vulnerabilität beschreibt erhöhte Verletzlichkeit gegenüber Schaden.", correct: true }, { text: "Exposition bezeichnet Kontakt mit einem äußeren Einfluss.", correct: true }, { text: "Eine Exposition führt zwingend zur Erkrankung." }, { text: "Biologische und soziale Faktoren können Vulnerabilität beeinflussen.", correct: true }], source: "Exposition ist eine Voraussetzung vieler Schädigungen, aber keine Erkrankungsgarantie. Dosis, Dauer, Schutzfaktoren und Vulnerabilität beeinflussen das Risiko.", difficulty: 2, mode: "multiple" },
  { id: "term-q-09", prompt: "Welche Aussagen beschreiben das WHO-Gesundheitsverständnis korrekt?", options: [{ text: "Es umfasst körperliches, psychisches und soziales Wohlbefinden.", correct: true }, { text: "Gesundheit wird nicht nur als Abwesenheit von Krankheit verstanden.", correct: true }, { text: "Die Definition ist ein normatives, umfassendes Konzept.", correct: true }, { text: "Gesundheit liegt nach WHO ausschließlich bei unauffälligen Laborwerten vor." }], source: "Die WHO-Definition erweitert das rein biomedizinische Verständnis um psychisches und soziales Wohlbefinden.", difficulty: 2, mode: "multiple" },
  { id: "term-q-10", prompt: "Welche Zuordnungen von Therapieformen sind richtig?", options: [{ text: "Antibiotische Behandlung einer bakteriellen Infektion kann kausal sein.", correct: true }, { text: "Antipyrese kann symptomatisch wirken.", correct: true }, { text: "Palliative Behandlung zielt auf Lebensqualität und Symptomlinderung.", correct: true }, { text: "Diätetische Therapie bedeutet jede beliebige Lebensstiländerung." }], source: "Kausal behandelt Ursachen, symptomatisch Krankheitszeichen und palliativ belastende Symptome sowie Lebensqualität. Diätetik bezieht sich gezielt auf Ernährung.", difficulty: 3, mode: "multiple" },
  { id: "term-q-11", prompt: "Welche Beispiele sind den Präventionsstufen richtig zugeordnet?", options: [{ text: "Impfung vor Erkrankung – Primärprävention.", correct: true }, { text: "Screening zur Früherkennung – Sekundärprävention.", correct: true }, { text: "Rehabilitation nach Schlaganfall – Tertiärprävention.", correct: true }, { text: "Akutversorgung eines manifesten Herzinfarkts – Primärprävention." }], source: "Primär verhindert Entstehung, sekundär erkennt früh, tertiär reduziert Folgen und Rückfälle einer manifesten Erkrankung.", difficulty: 2, mode: "multiple" },
  { id: "term-q-12", prompt: "Welche Aussagen zu Hypoxämie und Hypoxie stimmen?", options: [{ text: "Hypoxämie betrifft den Sauerstoff im arteriellen Blut.", correct: true }, { text: "Hypoxie bezeichnet unzureichende Sauerstoffversorgung von Gewebe.", correct: true }, { text: "Eine Anämie kann Gewebehypoxie trotz unauffälligem PaO₂ begünstigen.", correct: true }, { text: "Hypoxämie und Hypoxie sind definitionsgleich." }], source: "Blutoxygenierung und Gewebeoxygenierung sind gekoppelt, aber nicht identisch. Sauerstoffgehalt, Perfusion und Verbrauch beeinflussen die Gewebeversorgung.", difficulty: 3, mode: "multiple" },
  { id: "term-q-13", prompt: "Welche klassischen Entzündungszeichen sind korrekt übersetzt?", options: [{ text: "Rubor – Rötung", correct: true }, { text: "Calor – Überwärmung", correct: true }, { text: "Tumor – Schwellung", correct: true }, { text: "Functio laesa – gesteigerte Funktion" }], source: "Functio laesa bedeutet Funktionsverlust beziehungsweise Funktionseinschränkung; Dolor bezeichnet Schmerz.", difficulty: 2, mode: "multiple" },
  { id: "term-q-14", prompt: "Welche Aussagen zu Leitlinien, Richtlinien und Standards sind richtig?", options: [{ text: "Leitlinien sind systematisch entwickelte Entscheidungshilfen.", correct: true }, { text: "Von Leitlinien kann im begründeten Einzelfall abgewichen werden.", correct: true }, { text: "Richtlinien können in ihrem Geltungsbereich verbindlich sein.", correct: true }, { text: "Jeder Standard ist automatisch ein Gesetz." }], source: "Bindungswirkung und Funktion müssen getrennt werden. Leitlinien geben Entscheidungskorridore, Richtlinien können verbindlich sein, Standards definieren ein fachliches Niveau.", difficulty: 3, mode: "multiple" },
  { id: "term-q-15", prompt: "Welche Bestandteile gehören zu evidenzbasierten Entscheidungen?", options: [{ text: "Bestverfügbare wissenschaftliche Erkenntnisse.", correct: true }, { text: "Klinische beziehungsweise professionelle Expertise.", correct: true }, { text: "Werte und Präferenzen der betroffenen Person.", correct: true }, { text: "Ausschließlich persönliche Erfahrung ohne kritische Prüfung." }], source: "Evidenzbasierte Praxis verbindet externe Evidenz, Expertise und Patientenperspektive; keiner der drei Bereiche genügt allein.", difficulty: 3, mode: "multiple" },
  { id: "term-q-16", prompt: "Welche sprachlichen Funktionen sind richtig beschrieben?", options: [{ text: "Deskriptiv: Informationen vermitteln.", correct: true }, { text: "Expressiv: innere Zustände ausdrücken.", correct: true }, { text: "Argumentativ: Positionen begründen oder hinterfragen.", correct: true }, { text: "Kommunikativ: ausschließlich medizinische Diagnosen verschlüsseln." }], source: "Kommunikative beziehungsweise soziale Funktion schafft Verständigung und Beziehung; sie ist nicht auf medizinische Codes beschränkt.", difficulty: 2, mode: "multiple" },
  { id: "term-q-17", prompt: "Welche Aussagen zu aktivem und passivem Wortschatz stimmen?", options: [{ text: "Passiver Wortschatz wird verstanden, aber nicht sicher selbst verwendet.", correct: true }, { text: "Aktiver Wortschatz kann situationsgerecht eingesetzt werden.", correct: true }, { text: "Ein Fachbegriff kann zunächst passiv und später aktiv beherrscht werden.", correct: true }, { text: "Passiver Wortschatz bedeutet, dass ein Wort unbekannt ist." }], source: "Passiv beherrschte Wörter werden erkannt und verstanden; aktiv beherrschte Wörter werden selbst korrekt produziert.", difficulty: 2, mode: "multiple" },
  { id: "term-q-18", prompt: "Welche Aussagen zum elaborierten und restringierten Sprachcode sind angemessen?", options: [{ text: "Die Begriffe beschreiben sprachliche Ausdrucksweisen, nicht Intelligenz.", correct: true }, { text: "Elaborierte Sprache ist tendenziell expliziter und kontextunabhängiger.", correct: true }, { text: "Restringierte Sprache kann knapp und stark kontextgebunden sein.", correct: true }, { text: "Patienten mit knapper Sprache sind grundsätzlich nicht einwilligungsfähig." }], source: "Sprachstil darf nicht mit kognitiver Fähigkeit oder Einwilligungsfähigkeit gleichgesetzt werden. Rettungsdienstliche Kommunikation muss verständlich und wertschätzend bleiben.", difficulty: 3, mode: "multiple" },
  { id: "term-q-19", prompt: "Welche anatomischen Wortstämme sind korrekt?", options: [{ text: "splen- – Milz", correct: true }, { text: "hepat- – Leber", correct: true }, { text: "kardi- – Herz", correct: true }, { text: "nephr- – Großhirn" }], source: "Nephr- bezeichnet die Niere; Großhirn wird mit cerebrum beziehungsweise zerebr-/enzephal- beschrieben.", difficulty: 2, mode: "multiple" },
  { id: "term-q-20", prompt: "Welche Aussagen zur Krankheitsbeschreibung sind fachlich?", options: [{ text: "Ätiologie beschreibt Ursachen.", correct: true }, { text: "Pathogenese beschreibt Entstehungsmechanismen und Entwicklung.", correct: true }, { text: "Morphologie beschreibt strukturelle Veränderungen.", correct: true }, { text: "Topografie beschreibt ausschließlich die Letalität." }], source: "Topografie betrifft Ort und Verteilung; Ätiologie, Pathogenese und Morphologie beantworten andere Fragen des Krankheitsbildes.", difficulty: 3, mode: "multiple" },
  { id: "term-q-21", prompt: "Ein Patient hat bei schwerer Anämie einen unauffälligen arteriellen PaO₂, zeigt aber Zeichen einer Gewebehypoxie. Welche Aussagen sind korrekt?", options: [{ text: "Ein normaler PaO₂ schließt eine verminderte Sauerstofftransportkapazität nicht aus.", correct: true }, { text: "Hypoxämie ist hier allein durch den normalen PaO₂ bewiesen." }, { text: "Der Hämoglobingehalt beeinflusst den arteriellen Sauerstoffgehalt.", correct: true }, { text: "Hypoxie beschreibt die unzureichende Sauerstoffversorgung des Gewebes.", correct: true }, { text: "Hypoxie und Hypoxämie sind unabhängig vom Mechanismus bedeutungsgleich." }], source: "PaO₂ beschreibt den gelösten Sauerstoffdruck, nicht allein die gesamte Transportkapazität. Hypoxie kann trotz normalem PaO₂ bei zu wenig funktionsfähigem Hämoglobin oder unzureichender Perfusion entstehen.", difficulty: 3, mode: "multiple" },
  { id: "term-q-22", prompt: "Welche Begriffsanalysen sind sprachlich und medizinisch korrekt?", options: [{ text: "Perikarditis: Entzündung des Herzbeutels.", correct: true }, { text: "Intravenös: innerhalb beziehungsweise in eine Vene betreffend.", correct: true }, { text: "Hepatomegalie: Verkleinerung der Leber." }, { text: "Nephrektomie: operative Entfernung einer Niere oder eines Nierenanteils.", correct: true }, { text: "Bradykardie: beschleunigte Herzfrequenz." }], source: "Wortstamm und Suffix bestimmen gemeinsam die Bedeutung: hepat- Leber, -megalie Vergrößerung, nephr- Niere, -ektomie operative Entfernung und brady- langsam.", difficulty: 3, mode: "multiple" },
  { id: "term-q-23", prompt: "In einer Population von 10.000 Personen bestehen am Stichtag 300 Krankheitsfälle; im Folgejahr treten 40 neue Fälle auf. Welche Aussagen sind richtig?", options: [{ text: "Die 300 bestehenden Fälle gehören zur Punktprävalenz am Stichtag.", correct: true }, { text: "Die 40 neuen Fälle beschreiben das Neuerkrankungsgeschehen.", correct: true }, { text: "Für eine exakte Inzidenzberechnung muss die betrachtete Risikopopulation beziehungsweise Personenzeit definiert sein.", correct: true }, { text: "Die 300 Fälle sind automatisch identisch mit der Jahresinzidenz." }, { text: "Eine längere Krankheitsdauer kann die Prävalenz erhöhen, ohne dass die Inzidenz im gleichen Maß steigt.", correct: true }], source: "Prävalenz erfasst bestehende Fälle, Inzidenz neue Fälle. Für belastbare Raten braucht es einen definierten Nenner und Zeitraum; die Krankheitsdauer beeinflusst besonders die Prävalenz.", difficulty: 3, mode: "multiple" },
  { id: "term-q-24", prompt: "Welche Aussagen unterscheiden Mortalität und Letalität in einem seltenen, häufig tödlichen Krankheitsbild korrekt?", options: [{ text: "Die Letalität kann hoch sein, obwohl die populationsbezogene Mortalität niedrig bleibt.", correct: true }, { text: "Die Letalität setzt krankheitsbezogene Todesfälle ins Verhältnis zu den Erkrankten.", correct: true }, { text: "Die Mortalität bezieht Todesfälle auf eine definierte Population und einen Zeitraum.", correct: true }, { text: "Bei einer seltenen Erkrankung müssen Letalität und Mortalität denselben Zahlenwert haben." }, { text: "Für beide Maßzahlen ist der Nenner immer die Gesamtbevölkerung." }], source: "Eine seltene Krankheit kann für Betroffene sehr tödlich sein und dennoch nur wenige Todesfälle in der Gesamtbevölkerung verursachen. Entscheidend ist der unterschiedliche Nenner.", difficulty: 3, mode: "multiple" },
  { id: "term-q-25", prompt: "Welche Maßnahmen sind den Präventionsstufen korrekt zugeordnet?", options: [{ text: "Rauchprävention vor Entstehung einer COPD: Primärprävention.", correct: true }, { text: "Screening einer symptomarmen Risikogruppe: Sekundärprävention.", correct: true }, { text: "Rehabilitation zur Begrenzung von Folgeschäden nach Schlaganfall: Tertiärprävention.", correct: true }, { text: "Akuttherapie eines manifesten Spannungspneumothorax: Sekundärprävention." }, { text: "Rückfallprophylaxe nach bereits eingetretener Erkrankung kann Tertiärprävention sein.", correct: true }], source: "Primärprävention verhindert Entstehung, Sekundärprävention dient der Früherkennung und Tertiärprävention begrenzt Folgen oder Rückfälle einer manifesten Erkrankung.", difficulty: 3, mode: "multiple" },
  { id: "term-q-26", prompt: "Welche Formulierungen verwenden Ätiologie, Pathogenese, Morphologie und Topografie korrekt?", options: [{ text: "Rauchen als Ursache einer Erkrankung betrifft die Ätiologie.", correct: true }, { text: "Die schrittweise Entstehung eines Gefäßverschlusses gehört zur Pathogenese.", correct: true }, { text: "Ein histologisch sichtbarer Gewebeumbau ist eine morphologische Veränderung.", correct: true }, { text: "Die Lokalisation einer Läsion beschreibt ihre Topografie.", correct: true }, { text: "Der klinische Verlauf ist definitionsgleich mit der Ätiologie." }], source: "Ätiologie fragt nach der Ursache, Pathogenese nach dem Entstehungsweg, Morphologie nach Strukturveränderungen und Topografie nach Ort beziehungsweise Verteilung.", difficulty: 3, mode: "multiple" },
  { id: "term-q-27", prompt: "Welche Aussagen zur evidenzbasierten Entscheidung sind korrekt?", options: [{ text: "Eine Leitlinie unterstützt Entscheidungen, ersetzt aber nicht die Prüfung des Einzelfalls.", correct: true }, { text: "Professionelle Expertise verbindet externe Evidenz mit der konkreten Versorgungssituation.", correct: true }, { text: "Werte und Präferenzen des einwilligungsfähigen Patienten gehören in die Entscheidung.", correct: true }, { text: "Persönliche Erfahrung allein ist bereits vollständige evidenzbasierte Praxis." }, { text: "Eine begründete Abweichung von einer Leitlinie muss fachlich nachvollziehbar sein.", correct: true }], source: "Evidenzbasierte Praxis verbindet wissenschaftliche Erkenntnisse, professionelle Expertise und Patientenperspektive. Leitlinien geben einen Entscheidungskorridor, keine gedankenlose Einzelfallautomatik.", difficulty: 3, mode: "multiple" },
  { id: "term-q-28", prompt: "Ein Notfallsanitäter sagt: „Bitte setzen Sie sich jetzt hin.“ Welche Analysen des Sprechakts sind möglich?", options: [{ text: "Der geäußerte Satz und seine sprachliche Bedeutung gehören zur Lokution.", correct: true }, { text: "Die Aufforderung als kommunikative Handlung gehört zur Illokution.", correct: true }, { text: "Dass der Patient sich tatsächlich setzt, kann eine perlokutionäre Wirkung sein.", correct: true }, { text: "Die Illokution beschreibt ausschließlich die Lautstärke des Satzes." }, { text: "Perlokution ist unabhängig von jeder Wirkung beim Empfänger." }], source: "Lokution bezeichnet das Gesagte, Illokution die damit vollzogene Handlung und Perlokution die beim Gegenüber erzielte Wirkung.", difficulty: 3, mode: "multiple" },
];
