"use client";

import { ReactNode, useRef } from "react";

function TerminologySection({ number, kicker, title, children }: { number: string; kicker: string; title: string; children: ReactNode }) {
  return <details className="communication-section terminology-section"><summary><span>{number}</span><div><small>{kicker}</small><h2>{title}</h2></div><i>⌄</i></summary><div className="communication-section-content">{children}</div></details>;
}

export default function TerminologyLesson({ onBack, finale }: { onBack: () => void; finale: ReactNode }) {
  const flowRef = useRef<HTMLDivElement>(null);
  const toggleAll = (open: boolean) => flowRef.current?.querySelectorAll<HTMLDetailsElement>("details").forEach(section => { section.open = open; });
  return <section className="page-section legal-reader communication-reader terminology-reader">
    <button className="back-button" onClick={onBack}>← Schriftliche Fachbereiche</button>
    <header className="communication-hero terminology-hero"><div><span className="eyebrow light">Schriftliche Prüfung · Terminologie</span><h1>Begriffe zerlegen.<br />Bedeutung verstehen. Präzise sprechen.</h1><p>Medizinische Fachsprache sicher entschlüsseln und in Dokumentation, Übergabe und Prüfung korrekt anwenden.</p></div><div><b>10</b><span>Lernfelder</span><small>38 geprüfte Karteikarten</small></div></header>
    <aside className="communication-focus terminology-focus"><span>Ab</span><div><b>Prüfungsfokus</b><p>Nicht isoliert auswendig lernen: Wortbestandteile erkennen, eng verwandte Begriffe abgrenzen und die Bedeutung auf einen klinischen Satz übertragen.</p></div></aside>
    <div className="communication-toolbar" role="group" aria-label="Leseabschnitte steuern"><button type="button" onClick={() => toggleAll(true)}>Alles ausklappen</button><button type="button" onClick={() => toggleAll(false)}>Alles einklappen</button><small>Alle Lernfelder sind beim Einstieg übersichtlich eingeklappt.</small></div>
    <div className="communication-reading-flow" ref={flowRef}>
      <TerminologySection number="01" kicker="Grundlage" title="Terminologie, Nomenklatur und Fachsprache"><div className="communication-copy"><div className="terminology-compare"><article><span>Terminologie</span><b>System der Fachbegriffe</b><p>Begriffe, Bedeutungen und ihre fachgerechte Verwendung innerhalb eines Wissensgebiets.</p></article><article><span>Nomenklatur</span><b>Geordnete Benennung</b><p>Systematisch festgelegte Namen, beispielsweise für anatomische Strukturen.</p></article></div><div className="terminology-principles"><span>Sachlich</span><span>Eindeutig</span><span>Systematisch</span><span>Präzise</span><span>Verständlich</span></div><div className="communication-grid"><article><b>Sachlich</b><p>Beobachtungen und Befunde ohne Wertung, Vorwurf oder Spekulation beschreiben.</p></article><article><b>Eindeutig</b><p>Begriffe so wählen, dass möglichst keine unterschiedlichen Auslegungen entstehen.</p></article><article><b>Systematisch</b><p>Informationen nach einer festen, nachvollziehbaren Ordnung erfassen und weitergeben.</p></article><article><b>Präzise</b><p>Ort, Zeit, Ausmaß und relevante Merkmale möglichst genau statt nur allgemein benennen.</p></article><article><b>Verständlich</b><p>Sprache an Empfänger und Situation anpassen; Fachbegriffe bei Bedarf erklären.</p></article></div><p>Diese Merkmale sichern Übergabe, Dokumentation und Zusammenarbeit. Lateinische und griechische Bestandteile machen Begriffe international wiedererkennbar und zusammensetzbar. Im Patientengespräch muss Fachsprache dennoch in verständliche Alltagssprache übersetzt werden.</p></div></TerminologySection>

      <TerminologySection number="02" kicker="Wortbildung" title="Präfix + Stamm + Suffix"><div className="communication-copy"><div className="terminology-formula"><span><small>Präfix</small><b>peri-</b><em>Lage / Beziehung</em></span><i>+</i><span><small>Stamm</small><b>kard</b><em>Herz</em></span><i>+</i><span><small>Suffix</small><b>-itis</b><em>Entzündung</em></span><i>=</i><span className="result"><small>Gesamtbegriff</small><b>Perikarditis</b><em>Entzündung des Herzbeutels</em></span></div><div className="terminology-affix-grid"><article><b>peri-</b><p>um … herum</p></article><article><b>supra- / infra-</b><p>oberhalb / unterhalb</p></article><article><b>intra- / extra-</b><p>innerhalb / außerhalb</p></article><article><b>ante- / post-</b><p>vor / nach beziehungsweise hinter</p></article><article><b>ad-</b><p>zu, an, heran</p></article><article><b>-logie</b><p>Lehre, Wissenschaft</p></article></div></div></TerminologySection>

      <TerminologySection number="03" kicker="Anatomie" title="Organstämme sicher zuordnen"><div className="communication-copy"><div className="terminology-organ-grid"><article><span>Niere</span><b>ren · nephr-</b></article><article><span>Leber</span><b>hepar · hepat-</b></article><article><span>Herz</span><b>cor · kardi-</b></article><article><span>Großhirn</span><b>cerebrum · zerebr-</b></article><article><span>Milz</span><b>lien · splen-</b></article><article><span>Brustkorb</span><b>thorax</b></article></div><div className="communication-grid"><article><b>Radix</b><p>Wurzel oder Ursprung.</p></article><article><b>Ramus</b><p>Ast beziehungsweise Abzweigung.</p></article><article><b>Truncus</b><p>Stamm.</p></article><article><b>Sinus</b><p>Je nach Kontext Hohlraum, Kanal oder erweiterter venöser Raum.</p></article></div></div></TerminologySection>

      <TerminologySection number="04" kicker="Benennungen" title="Synonym, Homonym, Eponym und Metonymie"><div className="communication-copy"><div className="terminology-definition-grid"><article><b>Synonym</b><p>Verschiedene Wörter mit gleicher oder sehr ähnlicher Bedeutung.</p></article><article><b>Homonym</b><p>Gleiche Wortform mit unterschiedlichen Bedeutungen.</p></article><article><b>Eponym</b><p>Benennung nach einer Person, etwa Morbus Parkinson.</p></article><article><b>Metonymie</b><p>Ersetzung durch einen sachlich eng verbundenen Ausdruck.</p></article></div><aside className="communication-exam-tip"><b>Korrigiert</b><p>Metonymie ist nicht pauschal „bildhafte Darstellung“. Ein Bildvergleich wäre eher eine Metapher. Medizinische Eponyme sind historisch gebräuchlich, aber oft weniger selbsterklärend als systematische Begriffe.</p></aside></div></TerminologySection>

      <TerminologySection number="05" kicker="Sprache" title="Sprechakte und sprachliche Funktionen"><div className="communication-copy"><div className="terminology-speech-flow"><span><b>Lokution</b><small>Was wird gesagt?</small></span><i>→</i><span><b>Illokution</b><small>Welche Handlung / Absicht?</small></span><i>→</i><span><b>Perlokution</b><small>Welche Wirkung entsteht?</small></span></div><div className="communication-grid"><article><b>Deskriptiv</b><p>Information geben oder erhalten.</p></article><article><b>Expressiv</b><p>Innere Zustände ausdrücken.</p></article><article><b>Kommunikativ</b><p>Verständigung und Beziehung herstellen.</p></article><article><b>Argumentativ</b><p>Positionen begründen und hinterfragen.</p></article></div><aside className="communication-exam-tip"><b>Korrigiert</b><p>Perlokution bedeutet die erzielte Wirkung einer Äußerung – nicht „Militärstil“. Die beabsichtigte kommunikative Handlung gehört zur Illokution.</p></aside></div></TerminologySection>

      <TerminologySection number="06" kicker="Epidemiologie" title="Häufigkeit und Risiko richtig benennen"><div className="communication-copy"><div className="terminology-epi-grid"><article><span>Neue Fälle</span><b>Inzidenz</b><p>Neuerkrankungen in Population und Zeitraum.</p></article><article><span>Alle Fälle</span><b>Prävalenz</b><p>Bestehende Fälle zu Zeitpunkt oder im Zeitraum.</p></article><article><span>Krankheitslast</span><b>Morbidität</b><p>Erkrankungshäufigkeit in einer Population.</p></article><article><span>Population</span><b>Mortalität</b><p>Todesfälle bezogen auf die Bevölkerung.</p></article><article><span>Erkrankte</span><b>Letalität</b><p>Krankheitsbezogene Todesfälle unter Erkrankten.</p></article><article><span>Verletzlichkeit</span><b>Vulnerabilität</b><p>Anfälligkeit für gesundheitlichen Schaden.</p></article></div><aside className="communication-case"><small>Wichtige Abgrenzung</small><p>Exposition bedeutet Kontakt mit einem Einfluss. Ob daraus eine Erkrankung entsteht, hängt unter anderem von Dosis, Dauer, Schutzfaktoren und Vulnerabilität ab.</p></aside></div></TerminologySection>

      <TerminologySection number="07" kicker="Gesundheit & Therapie" title="Ziel und Art der Behandlung unterscheiden"><div className="communication-copy"><div className="terminology-health-card"><b>WHO-Gesundheitsverständnis</b><p>Körperliches, psychisches und soziales Wohlbefinden – nicht nur Abwesenheit von Krankheit. Das biomedizinische Modell betrachtet demgegenüber vor allem Krankheit und Funktionsstörung.</p></div><div className="terminology-therapy-grid"><article><b>Kausal</b><p>Ursache behandeln.</p></article><article><b>Symptomatisch</b><p>Krankheitszeichen lindern.</p></article><article><b>Palliativ</b><p>Lebensqualität und Linderung bei nicht heilbarer, lebensbegrenzender Erkrankung.</p></article><article><b>Diätetisch</b><p>Ernährung und Nährstoffzufuhr gezielt verändern.</p></article></div></div></TerminologySection>

      <TerminologySection number="08" kicker="Prävention" title="Vor Entstehung, früh erkennen, Folgen begrenzen"><div className="communication-copy"><div className="terminology-prevention-flow"><article><span>1</span><b>Primär</b><p>Krankheitsentstehung verhindern.</p><small>Beispiel: Impfung</small></article><i>→</i><article><span>2</span><b>Sekundär</b><p>Früh erkennen und behandeln.</p><small>Beispiel: Darmkrebsfrüherkennung</small></article><i>→</i><article><span>3</span><b>Tertiär</b><p>Folgen und Rückfälle begrenzen.</p><small>Beispiel: Rehabilitation</small></article></div></div></TerminologySection>

      <TerminologySection number="09" kicker="Klinische Begriffe" title="Entzündung, Sauerstoff und Beziehung"><div className="communication-copy"><div className="terminology-inflammation"><span><b>Rubor</b>Rötung</span><span><b>Calor</b>Überwärmung</span><span><b>Tumor</b>Schwellung</span><span><b>Dolor</b>Schmerz</span><span><b>Functio laesa</b>Funktionseinschränkung</span></div><div className="communication-compare"><article><small>Arterielles Blut</small><h3>Hypoxämie</h3><p>Primär ein erniedrigter arterieller Sauerstoffpartialdruck. Der Sauerstoffgehalt hängt zusätzlich vor allem vom funktionsfähigen Hämoglobin ab.</p></article><article><small>Gewebe</small><h3>Hypoxie</h3><p>Unzureichende Sauerstoffversorgung des Gewebes – möglich durch Oxygenierungs-, Transport- oder Perfusionsstörung.</p></article></div><div className="communication-compare"><article><small>Verstehen</small><h3>Empathie</h3><p>Perspektive und Erleben nachvollziehen, ohne sie vollständig zu übernehmen.</p></article><article><small>Zuneigung</small><h3>Sympathie</h3><p>Persönliches positives Gefühl oder Mitgefühl.</p></article></div></div></TerminologySection>

      <TerminologySection number="10" kicker="Wissen bewerten" title="Evidenz, Leitlinie, Richtlinie und Standard"><div className="communication-copy"><div className="terminology-evidence"><span>Wissenschaftliche Evidenz</span><i>+</i><span>Professionelle Expertise</span><i>+</i><span>Werte und Präferenzen</span><i>=</i><span className="result">Evidenzbasierte Entscheidung</span></div><div className="terminology-definition-grid"><article><b>Leitlinie</b><p>Systematisch entwickelte Entscheidungshilfe; begründete Abweichung ist möglich.</p></article><article><b>Richtlinie</b><p>Im jeweiligen Geltungsbereich verbindliche Regelung.</p></article><article><b>Standard</b><p>Festgelegtes fachliches Qualitätsniveau oder erwartetes Vorgehen.</p></article><article><b>Krankheitsbeschreibung</b><p>Topografie, Ätiologie, Pathogenese, Morphologie, Funktion und Verlauf.</p></article></div></div></TerminologySection>
    </div>
    {finale}
    <section className="legal-sources communication-sources"><span className="eyebrow">Fachlicher Abgleich</span><h2>Was aus den Karteikarten korrigiert wurde</h2><p>Doppelte Begriffe wurden zusammengeführt. Präzisiert wurden besonders Metonymie, Sprechakte, Evidenz, Leitlinien/Richtlinien/Standards, Palliativ- und diätetische Therapie, Präventionsstufen, Sinus sowie die Abgrenzungen Inzidenz/Prävalenz, Mortalität/Letalität und Hypoxämie/Hypoxie.</p></section>
  </section>;
}
