import { supplementalQuestions } from "./supplemental-questions";

export type ThoraxtraumaChoiceQuestion = {
  id: string;
  mode: "multiple";
  prompt: string;
  options: Array<{ text: string; correct?: boolean }>;
  source: string;
  difficulty: 1 | 2 | 3;
};

export type ThoraxtraumaFlashcard = {
  id: string;
  area: string;
  question: string;
  answer: string;
};

export const thoraxtraumaFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "thorax-card-01", area: "Definition", question: "Definieren Sie das Thoraxtrauma und nennen Sie die beiden Grundmechanismen.", answer: "Stumpfe oder penetrierende Gewalteinwirkung auf den Thorax mit Gefahr von Frakturen oder Verletzungen intrathorakaler Organe und nachfolgenden vitalen Funktionsstörungen. Grundmechanismen sind stumpfes und penetrierendes Thoraxtrauma." },
  { id: "thorax-card-02", area: "Pleura", question: "Erklären Sie Pleura visceralis, Pleura parietalis und Pleuraspalt.", answer: "Die Pleura visceralis liegt der Lunge an, die schmerzempfindliche Pleura parietalis der Thoraxwand und dem Zwerchfell. Dazwischen liegt der flüssigkeitsbenetzte Pleuraspalt. Unterdruck sowie Adhäsions- und Kohäsionskräfte koppeln Lunge und Brustwand und ermöglichen reibungsarmes Gleiten." },
  { id: "thorax-card-03", area: "Thorax", question: "Welche Strukturen bilden den Brustkorb und welche Funktion erfüllt er?", answer: "Zwölf Brustwirbel, zwölf Rippenpaare und Sternum bilden den Brustkorb. Die Rippen besitzen knöcherne und knorpelige Anteile; die 11. und 12. Rippe haben keine Verbindung zum Sternum. Der Thorax schützt innere Organe und beteiligt sich an der Atemmechanik." },
  { id: "thorax-card-04", area: "Pneumothorax", question: "Grenzen Sie offenen, geschlossenen und Spannungspneumothorax ab.", answer: "Offen: Luft tritt über eine Thoraxwandverletzung in den Pleuraspalt ein und aus. Geschlossen: Luft gelangt von innen in den Pleuraspalt, ohne Verbindung nach außen. Spannungspneumothorax: Ventilmechanismus verhindert das Entweichen; Druck, Lungenkollaps, Mediastinalverlagerung und Kompression großer Gefäße bedrohen Atmung und Kreislauf." },
  { id: "thorax-card-05", area: "Verletzungsmuster", question: "Erklären Sie Hämatothorax, Lungenkontusion und Rippenserienfraktur.", answer: "Beim Hämatothorax sammelt sich Blut im Pleuraspalt, komprimiert die Lunge und verursacht zugleich Volumenverlust. Die Lungenkontusion führt zu Einblutungen und Ödemen im Lungengewebe. Mindestens drei benachbarte Rippenfrakturen können einen instabilen Thorax mit paradoxer Atmung verursachen." },
  { id: "thorax-card-06", area: "Gefahren", question: "Ordnen Sie die Schockformen den Thoraxverletzungen zu.", answer: "Obstruktiv: Spannungspneumothorax oder Herzbeuteltamponade mit behinderter Herzfüllung. Kardiogen: Herzkontusion oder direkte Herzverletzung mit reduzierter Pumpleistung. Hypovolämisch: Hämatothorax oder Aortenruptur. Neurogen: hohe Rückenmarksverletzung mit Sympathikusausfall." },
  { id: "thorax-card-07", area: "Symptome", question: "Welche Befunde stützen die Arbeitsdiagnose Thoraxtrauma?", answer: "Passender Mechanismus, Dyspnoe, Tachypnoe, Zyanose, atemabhängiger Thoraxschmerz, Schonatmung, asymmetrische Atemexkursion, Prellmarken, Hämatome, Wunden, Krepitation oder Stufenbildung, paradoxe Atmung sowie einseitig vermindertes oder fehlendes Atemgeräusch." },
  { id: "thorax-card-08", area: "Spannungspneumothorax", question: "Welche Befundkombination macht einen Spannungspneumothorax besonders wahrscheinlich?", answer: "Zunehmende Dyspnoe und Unruhe, einseitig abgeschwächtes oder fehlendes Atemgeräusch, Hypotonie und Tachykardie. Gestaute Halsvenen und hypersonorer Klopfschall können hinzukommen; eine Trachealverlagerung ist ein Spätzeichen." },
  { id: "thorax-card-09", area: "VFA 07", question: "Welche Indikation verlangt die Thüringer VFA 07 für die Entlastungspunktion?", answer: "Thoraxtrauma mit mindestens einseitig abgeschwächtem Atemgeräusch UND hämodynamischer Instabilität. Beide Kriterien müssen gemeinsam beurteilt werden." },
  { id: "thorax-card-10", area: "Entlastungspunktion", question: "Beschreiben Sie die Durchführung nach VFA 07.", answer: "Punktionsort 2. ICR medioklavikular oder 4./5. ICR vordere Axillarlinie; geeignete Thoraxpunktionskanüle mindestens 6,5 cm; im 90-Grad-Winkel über den Rippenoberrand punktieren. Bei Luftentweichen Stahlmandrin entfernen, Kanüle fixieren und respiratorische sowie hämodynamische Wirkung re-evaluieren." },
  { id: "thorax-card-11", area: "Analgesie", question: "Wie werden Esketamin und Morphin bei starkem traumatischem Schmerz eingeordnet?", answer: "Ab NRS 5: cABCDE, Ursache und OPQRST, dann Auswahl nach Vorgabe des zuständigen ÄLRD. VFA 36: Erwachsene Esketamin langsam 0,2 mg/kg i.v., bei Bedarf nach fünf und zehn Minuten je halbe Initialdosis. VFA 38: Morphin ab 40 kg langsam nach Gewichtstabelle, nach fünf Minuten bei Bedarf halbe Dosis, insgesamt maximal 10 mg. Monitoring und Beatmungsbereitschaft sind obligat." },
  { id: "thorax-card-12", area: "Einsatzstrategie", question: "Wie strukturieren Sie die präklinische Versorgung eines kritischen Thoraxtraumas?", answer: "Kritische Blutung und cABCDE, früh kritisch/nicht kritisch entscheiden, Sauerstoff und Atemwegs-/Beatmungsbereitschaft, Monitoring, zielgerichtete Thoraxuntersuchung, gegebenenfalls VFA-Entlastung, i.v.-Zugang, SAMPLERS/OPQRST, frühe Notarztnachforderung und schneller Transport ins geeignete Traumazentrum mit wiederholter Re-Evaluation und Dokumentation." },
];

const thoraxtraumaBaseQuestions: ThoraxtraumaChoiceQuestion[] = [
  { id: "thorax-q-01", mode: "multiple", prompt: "Welche Aussagen beschreiben ein Thoraxtrauma korrekt?", options: [{ text: "Es kann durch stumpfe oder penetrierende Gewalteinwirkung entstehen", correct: true }, { text: "Frakturen und Verletzungen intrathorakaler Organe können vitale Funktionen gefährden", correct: true }, { text: "Eine äußerlich geschlossene Thoraxwand schließt relevante innere Verletzungen aus" }, { text: "Nur eine nachgewiesene Rippenfraktur erfüllt die Definition" }], source: "Die Definition umfasst stumpfe und penetrierende Mechanismen sowie Frakturen oder Organverletzungen mit möglicher vitaler Funktionsstörung.", difficulty: 1 },
  { id: "thorax-q-02", mode: "multiple", prompt: "Welche Zuordnungen zur Pleura sind richtig?", options: [{ text: "Die Pleura visceralis liegt der Lunge an", correct: true }, { text: "Die Pleura parietalis liegt Thoraxwand und Zwerchfell an und ist schmerzempfindlich", correct: true }, { text: "Seröse Flüssigkeit ermöglicht ein reibungsarmes Gleiten der Pleurablätter", correct: true }, { text: "Der Pleuraspalt ist physiologisch mit Umgebungsluft gefüllt" }], source: "Pleuraspalt, Flüssigkeitsfilm und Unterdruck koppeln Lunge und Thoraxwand und unterstützen die Atemmechanik.", difficulty: 1 },
  { id: "thorax-q-03", mode: "multiple", prompt: "Welche Aussagen zum knöchernen Thorax treffen zu?", options: [{ text: "Er besteht aus zwölf Brustwirbeln, zwölf Rippenpaaren und Sternum", correct: true }, { text: "Die 11. und 12. Rippe besitzen keine Verbindung zum Sternum", correct: true }, { text: "Das Anheben der schräg verlaufenden Rippen erweitert den Brustkorb", correct: true }, { text: "Alle Rippen bestehen ausschließlich aus Knorpel" }], source: "Der Brustkorb schützt die inneren Organe und ist an der Atemmechanik beteiligt.", difficulty: 1 },
  { id: "thorax-q-04", mode: "multiple", prompt: "Welche Aussagen grenzen Pneumothoraxformen korrekt voneinander ab?", options: [{ text: "Beim offenen Pneumothorax besteht eine Verbindung durch die Thoraxwand nach außen", correct: true }, { text: "Beim geschlossenen Pneumothorax gelangt Luft von innen in den Pleuraspalt", correct: true }, { text: "Beim Spannungspneumothorax verhindert ein Ventilmechanismus das Entweichen von Luft", correct: true }, { text: "Ein Spannungspneumothorax betrifft ausschließlich die Ventilation und nie den Kreislauf" }], source: "Die Druckzunahme beim Spannungspneumothorax bedroht durch Lungenkollaps und Gefäßkompression Atmung und Kreislauf.", difficulty: 1 },
  { id: "thorax-q-05", mode: "multiple", prompt: "Welche Folgen gehören zur Pathophysiologie des Spannungspneumothorax?", options: [{ text: "Zunehmender intrapleuraler Druck mit Kollaps der betroffenen Lunge", correct: true }, { text: "Mediastinalverlagerung und Kompression großer venöser Gefäße", correct: true }, { text: "Verminderter venöser Rückstrom mit Abfall von Herzzeitvolumen und Blutdruck", correct: true }, { text: "Zwingend sofortiger massiver Blutverlust in den Pleuraspalt" }], source: "Der Ventilmechanismus führt zu Druckaufbau, verminderter Ventilation und obstruktiver Kreislaufbeeinträchtigung.", difficulty: 2 },
  { id: "thorax-q-06", mode: "multiple", prompt: "Welche Aussagen zu Hämatothorax und Lungenkontusion sind richtig?", options: [{ text: "Ein Hämatothorax komprimiert die Lunge und vermindert die Belüftung", correct: true }, { text: "Der Blutverlust in den Pleuraspalt kann einen hämorrhagischen Schock auslösen", correct: true }, { text: "Eine Lungenkontusion verursacht Einblutung und Ödem im Lungengewebe", correct: true }, { text: "Eine Lungenkontusion setzt zwingend eine offene Thoraxverletzung voraus" }], source: "Hämatothorax verbindet respiratorische Einschränkung und Volumenverlust; die Lungenkontusion entsteht typischerweise nach stumpfer Gewalt.", difficulty: 2 },
  { id: "thorax-q-07", mode: "multiple", prompt: "Welche Zuordnungen zu weiteren Thoraxverletzungen sind korrekt?", options: [{ text: "Herzbeuteltamponade: Blut im Perikard behindert die Herzfüllung", correct: true }, { text: "Aortenruptur: möglicher massiver Blutverlust und Volumenmangelschock", correct: true }, { text: "Zwerchfellruptur: Bauchorgane können in den Brustkorb verlagert werden", correct: true }, { text: "Rippenserienfraktur: paradoxe Atmung ist grundsätzlich ausgeschlossen" }], source: "Tamponade, Aorten- und Zwerchfellverletzung sowie instabiler Thorax gehören zu den schweren Verletzungsmustern.", difficulty: 2 },
  { id: "thorax-q-08", mode: "multiple", prompt: "Welche Befunde stützen die Arbeitsdiagnose Thoraxtrauma?", options: [{ text: "Atemabhängiger Thoraxschmerz, Dyspnoe und Schonatmung", correct: true }, { text: "Prellmarken, Wunden, Krepitation oder Stufenbildung", correct: true }, { text: "Asymmetrische Atemexkursion oder einseitig fehlendes Atemgeräusch", correct: true }, { text: "Ein unauffälliger erster Blutdruck schließt eine relevante Verletzung aus" }], source: "Mechanismus, sicht- und tastbare Verletzungszeichen sowie respiratorische Befunde werden gemeinsam und wiederholt beurteilt.", difficulty: 2 },
  { id: "thorax-q-09", mode: "multiple", prompt: "Welche Befunde sprechen bei Thoraxtrauma für eine zunehmende Spannungskomponente?", options: [{ text: "Zunehmende Dyspnoe und Unruhe", correct: true }, { text: "Einseitig fehlendes Atemgeräusch zusammen mit Hypotonie und Tachykardie", correct: true }, { text: "Gestaute Halsvenen oder hypersonorer Klopfschall können hinzukommen", correct: true }, { text: "Eine fehlende Trachealverlagerung schließt den Spannungspneumothorax früh sicher aus" }], source: "Die Trachealverlagerung ist ein Spätzeichen; die Entscheidung beruht auf dem klinischen Gesamtbild und der Dynamik.", difficulty: 2 },
  { id: "thorax-q-10", mode: "multiple", prompt: "Welche Schockzuordnungen sind beim Thoraxtrauma begründet?", options: [{ text: "Spannungspneumothorax und Herzbeuteltamponade können einen obstruktiven Schock verursachen", correct: true }, { text: "Herzkontusion kann die Pumpleistung reduzieren und einen kardiogenen Schock begünstigen", correct: true }, { text: "Hämatothorax und Aortenruptur können zum hypovolämischen Schock führen", correct: true }, { text: "Eine hohe Rückenmarksverletzung verursacht ausschließlich einen obstruktiven Schock" }], source: "Das Skript unterscheidet obstruktive, kardiogene, hypovolämische und bei Wirbelsäulenverletzung mögliche neurogene Schockmechanismen.", difficulty: 2 },
  { id: "thorax-q-11", mode: "multiple", prompt: "Welche Materialien sind bei einem relevanten Thoraxtrauma sinnvoll mitzunehmen beziehungsweise bereitzuhalten?", options: [{ text: "EKG/Monitoring und Kapnometrie", correct: true }, { text: "Beatmungsgerät, Sauerstoff und Absaugung", correct: true }, { text: "Traumatasche, Medikamente und gegebenenfalls Immobilisationsmaterial", correct: true }, { text: "Ausschließlich ein Blutdruckmessgerät, da Atemwegs- und Beatmungsmaterial nicht benötigt werden" }], source: "Das Skript nennt EKG, Medumat, Absaugung, Traumatasche, Medikamente, mögliche Immobilisation, CO-Warner und Kapnometrie.", difficulty: 2 },
  { id: "thorax-q-12", mode: "multiple", prompt: "Welche Schritte strukturieren Erstmaßnahmen und Anamnese korrekt?", options: [{ text: "Kritische Blutung prüfen und anschließend cABCDE durchführen", correct: true }, { text: "Früh zwischen kritischem und nicht kritischem Verlauf unterscheiden", correct: true }, { text: "SAMPLERS und OPQRST ergänzen die strukturierte Untersuchung, ohne sie zu verzögern", correct: true }, { text: "Bei nicht kritischem Eindruck sind Verlaufskontrollen grundsätzlich entbehrlich" }], source: "Erstmaßnahmen richten sich nach Notfallbild und Diagnose; cABCDE, Kritikalität, gezielte Anamnese und wiederholte Beurteilung gehören zusammen.", difficulty: 2 },
  { id: "thorax-q-13", mode: "multiple", prompt: "Welche Kriterien müssen nach VFA 07 für eine Entlastungspunktion gemeinsam vorliegen?", options: [{ text: "Ein Thoraxtrauma", correct: true }, { text: "Mindestens einseitig abgeschwächtes Atemgeräusch", correct: true }, { text: "Hämodynamische Instabilität", correct: true }, { text: "Eine radiologische Bestätigung vor jeder präklinischen Maßnahme" }], source: "VFA 07 verbindet Thoraxtrauma, mindestens einseitig abgeschwächtes Atemgeräusch UND hämodynamische Instabilität.", difficulty: 3 },
  { id: "thorax-q-14", mode: "multiple", prompt: "Welche Aussagen zur Durchführung der Entlastungspunktion entsprechen VFA 07?", options: [{ text: "Mögliche Punktionsorte sind 2. ICR medioklavikular oder 4./5. ICR vordere Axillarlinie", correct: true }, { text: "Die geeignete Thoraxpunktionskanüle soll mindestens 6,5 cm lang sein", correct: true }, { text: "Punktion im 90-Grad-Winkel über den Oberrand der Rippe", correct: true }, { text: "Der Stahlmandrin verbleibt nach hörbarem Luftentweichen dauerhaft in situ" }], source: "Nach Luftentweichen wird der Stahlmandrin entfernt, die Kanüle fixiert und die Wirkung re-evaluiert.", difficulty: 3 },
  { id: "thorax-q-15", mode: "multiple", prompt: "Nach Entlastung bleibt der Patient respiratorisch und hämodynamisch instabil. Welche Konsequenzen entsprechen VFA 07?", options: [{ text: "Eine Verschlechterung beziehungsweise Wiederholung des Problems wird erneut beurteilt", correct: true }, { text: "Differenzialdiagnosen wie Tubusfehllage, LAE, ACS, Aortendissektion oder Asthma/COPD werden geprüft", correct: true }, { text: "Monitoring und Transport werden fortgeführt", correct: true }, { text: "Die fehlende Stabilisierung beweist automatisch eine falsche Punktionsseite" }], source: "VFA 07 verlangt Re-Evaluation und bei fehlender Stabilisierung die Prüfung relevanter Differenzialdiagnosen.", difficulty: 3 },
  { id: "thorax-q-16", mode: "multiple", prompt: "Welche Aussagen gelten für starke traumatische Schmerzen nach VFA 35?", options: [{ text: "Der Basisalgorithmus beginnt bei NRS mindestens 5", correct: true }, { text: "Schmerzursache und OPQRST werden erhoben", correct: true }, { text: "Bei traumatischem Schmerz führen die vorgesehenen Pfade zu Esketamin oder Morphin", correct: true }, { text: "Eine Analgesie ersetzt die Behandlung des zugrunde liegenden Thoraxtraumas" }], source: "VFA 35 verbindet cABCDE, OPQRST, ursachenbezogene Pfadauswahl, Behandlung des Notfallbildes, Monitoring und Transport.", difficulty: 3 },
  { id: "thorax-q-17", mode: "multiple", prompt: "Welche Aussagen unterscheiden Esketamin- und Morphinpfad korrekt?", options: [{ text: "Esketamin für Erwachsene wird langsam mit 0,2 mg/kg i.v. initial dosiert", correct: true }, { text: "Bei unzureichender Wirkung sieht der Esketaminpfad nach fünf und zehn Minuten je die halbe Initialdosis vor", correct: true }, { text: "Morphin wird ab 40 kg langsam nach Gewichtstabelle gegeben und bei Bedarf nach fünf Minuten mit halber Dosis wiederholt", correct: true }, { text: "Morphin darf nach VFA 38 ohne Obergrenze wiederholt werden" }], source: "VFA 36 nennt Esketamin 0,2 mg/kg mit halber Repetition; VFA 38 Morphin nach Tabelle mit halber Repetition bis maximal 10 mg.", difficulty: 3 },
  { id: "thorax-q-18", mode: "multiple", prompt: "Welche Prioritäten sind bei einem instabilen Thoraxtrauma schlüssig?", options: [{ text: "Frühe Notarztnachforderung und parallele Vorbereitung des schnellen Transports", correct: true }, { text: "Geeignetes Traumazentrum anhand Kritikalität und Verletzungsmuster auswählen", correct: true }, { text: "Atmung, Kreislauf, Schmerz und Wirkung der Maßnahmen fortlaufend re-evaluieren und dokumentieren", correct: true }, { text: "Die Transportentscheidung bis zur vollständigen Schmerzfreiheit zurückstellen" }], source: "Das Skript fordert frühe Notarztnachforderung, schnellen Transport, kontinuierliches Monitoring, konsequente Analgesie und genaue Dokumentation.", difficulty: 3 },
];

export const thoraxtraumaQuestions: ThoraxtraumaChoiceQuestion[] = [...thoraxtraumaBaseQuestions, ...supplementalQuestions.thoraxtrauma];
