import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct: boolean];
function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  const shift = (number * 3) % options.length;
  return { id: `ulkusblutung-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty };
}

export const ulkusblutungFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "ulkusblutung-card-01", area: "Definition", question: "Grenzen Sie Erosion und Ulkus histologisch voneinander ab.", answer: "Eine Erosion bleibt oberflächlich und überschreitet die Muscularis mucosae nicht. Ein Ulkus reicht durch die Muscularis mucosae mindestens in die Submukosa und kann dort größere Gefäße eröffnen." },
  { id: "ulkusblutung-card-02", area: "Anatomie", question: "Nennen Sie die Wandschichten des oberen Gastrointestinaltrakts von innen nach außen.", answer: "Mukosa mit Muscularis mucosae, Submukosa, Muscularis propria und Serosa beziehungsweise abschnittsabhängig Adventitia. Größere Blutgefäße verlaufen in der Submukosa." },
  { id: "ulkusblutung-card-03", area: "Gefäße", question: "Welche Gefäße sind bei schweren gastroduodenalen Ulkusblutungen besonders relevant?", answer: "Beim posterioren Duodenalulkus besonders die A. gastroduodenalis, bei Ulzera an der kleinen Magenkurvatur unter anderem die A. gastrica sinistra. Die genaue Quelle wird endoskopisch bestimmt." },
  { id: "ulkusblutung-card-04", area: "Schleimhautschutz", question: "Welche Faktoren schützen die Magenschleimhaut vor Säure und Pepsin?", answer: "Mukus-Bikarbonat-Barriere, intakte Epithelverbindungen, gute Durchblutung, schnelle Restitution und prostaglandinvermittelte Schleim-, Bikarbonat- und Perfusionsförderung." },
  { id: "ulkusblutung-card-05", area: "Pathophysiologie", question: "Warum erhöhen NSAR und ASS das Ulkus- und Blutungsrisiko?", answer: "Vor allem COX-1-Hemmung senkt protektive Prostaglandine. Schleim, Bikarbonat, Perfusion und Reparatur nehmen ab. Die Thrombozytenhemmung von ASS kann eine entstandene Blutung zusätzlich verstärken." },
  { id: "ulkusblutung-card-06", area: "Blutungszeichen", question: "Wie entstehen Hämatemesis, Kaffeesatzerbrechen und Meläna?", answer: "Rasche obere GI-Blutung kann als rotes Blut erbrochen werden. Kontakt mit Magensäure führt zu dunklem Kaffeesatzmaterial. Verdautes Blut wird nach Darmpassage als schwarzer klebriger Teerstuhl ausgeschieden." },
  { id: "ulkusblutung-card-07", area: "Prüfungsfalle", question: "Warum lässt sich Ulkus- gegen Varizenblutung nicht anhand der Blutfarbe sicher unterscheiden?", answer: "Beide Quellen können bei rascher Blutung hellrote Hämatemesis verursachen. Kaffeesatz beweist lediglich Säurekontakt. Anamnese und Begleitzeichen verändern Wahrscheinlichkeiten, die Endoskopie sichert die Quelle." },
  { id: "ulkusblutung-card-08", area: "Schock", question: "Welche Befunde sprechen für einen beginnenden hämorrhagischen Schock, obwohl der Blutdruck noch normal ist?", answer: "Tachykardie, steigender Schockindex, Kaltschweißigkeit, Blässe, verlängerte Rekapillarisierung, periphere Kälte, Unruhe, Durst, Synkope und abnehmende Urinausscheidung. Betablocker können die Tachykardie maskieren." },
  { id: "ulkusblutung-card-09", area: "Atemweg", question: "Warum ist der Atemweg bei massiver oberer GI-Blutung besonders anspruchsvoll?", answer: "Blut, Koagel und Erbrochenes verlegen den Atemweg, verschlechtern Präoxygenierung und Sicht und erhöhen die Aspirationsgefahr. Leistungsfähige Absaugung und ein früh geplanter, erfahrener Atemwegszugang sind entscheidend." },
  { id: "ulkusblutung-card-10", area: "Differenzialdiagnosen", question: "Welche Blutungsquellen müssen von der Ulkusblutung abgegrenzt werden?", answer: "Ösophagus-/Fundusvarizen, Mallory-Weiss-Läsion, erosive Gastritis, Ösophagitis, Tumor, Aortoenterische Fistel, verschlucktes Blut und Hämoptyse; bei akutem Abdomen zusätzlich Perforation und vaskuläre Ursachen." },
  { id: "ulkusblutung-card-11", area: "Perforation", question: "Welche Konstellation spricht für eine Ulkusperforation?", answer: "Plötzlich maximaler Vernichtungsschmerz, Abwehrspannung bis bretthartes Abdomen, Peritonismus und mögliche Schockzeichen. Das ist eine zeitkritische chirurgische Situation." },
  { id: "ulkusblutung-card-12", area: "TXA", question: "Erklären Sie den Wirkmechanismus der Tranexamsäure.", answer: "Tranexamsäure blockiert Lysinbindungsstellen des Plasminogens, vermindert dessen Aktivierung zu Plasmin und hemmt so die Fibrinolyse. Sie stabilisiert ein Gerinnsel, verschließt aber kein eröffnetes Gefäß." },
  { id: "ulkusblutung-card-13", area: "TXA-Grenze", question: "Warum ist Tranexamsäure bei Ulkusblutung keine Routinegabe?", answer: "Die S2k-Leitlinie 2025 empfiehlt keine generelle präendoskopische Gabe. HALT-IT zeigte keine Senkung der blutungsbedingten Mortalität, aber mehr venöse Thromboembolien. Die Thüringer B2A-Zubereitung stammt aus dem Trauma-Pfad." },
  { id: "ulkusblutung-card-14", area: "Klinik", question: "Was bedeuten Glasgow-Blatchford-Score und Forrest-Klassifikation?", answer: "Der Glasgow-Blatchford-Score stratifiziert vor Endoskopie den Interventions- und Überwachungsbedarf. Forrest klassifiziert erst endoskopisch Blutungsstigmata von aktiv spritzend/sickernd bis zum sauberen Ulkusgrund." },
  { id: "ulkusblutung-card-15", area: "Übergabe", question: "Welche Angaben gehören in die Übergabe einer oberen GI-Blutung?", answer: "Zeit und geschätzte Dynamik der Blutung, Hämatemesis/Meläna, Vitaltrend und Perfusion, Synkope, Abdomen, Ulkus-/Leber-/Aortenanamnese, Antithrombotika, letzte Einnahme, Zugänge, Flüssigkeit, Atemwegsstatus und Maßnahmenwirkung." },
];

export const ulkusblutungQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen grenzen Erosion und Ulkus korrekt ab?", [["Eine Erosion überschreitet die Muscularis mucosae nicht", true], ["Ein Ulkus reicht mindestens in die Submukosa", true], ["Ein Ulkus kann größere submuköse Gefäße eröffnen", true], ["Jede Erosion perforiert definitionsgemäß die Serosa", false], ["Erosion und Ulkus sind histologisch identisch", false]], "Die Tiefe des Gewebedefekts trennt Erosion und Ulkus.", 1),
  q(2, "Welche Reihenfolge beschreibt die Wandschichten vom Lumen nach außen?", [["Mukosa – Submukosa – Muscularis propria – Serosa/Adventitia", true], ["Die Muscularis mucosae gehört zur Mukosa", true], ["Größere Gefäße verlaufen unter anderem in der Submukosa", true], ["Die Serosa liegt immer lumenseitig", false], ["Die Submukosa liegt außerhalb der Serosa", false]], "Die Schichtenfolge erklärt Blutung, Penetration und Perforation.", 2),
  q(3, "Welche Aussagen zur Magenphysiologie sind richtig?", [["Belegzellen bilden Salzsäure und Intrinsic Factor", true], ["Hauptzellen geben Pepsinogen ab", true], ["Mukus und Bikarbonat schützen die Oberfläche", true], ["Prostaglandine fördern Schleimhautdurchblutung und Schutzsekretion", true], ["Pepsin wird ausschließlich in der Harnblase aktiviert", false]], "Säure, Pepsin und Schutzbarriere stehen physiologisch im Gleichgewicht.", 2),
  q(4, "Welche Zusammenhänge erklären ein NSAR-assoziiertes Ulkus?", [["COX-1-Hemmung vermindert protektive Prostaglandine", true], ["Schleim- und Bikarbonatsekretion können abnehmen", true], ["Die Schleimhautperfusion und Reparatur können beeinträchtigt werden", true], ["ASS kann zusätzlich die Thrombozytenfunktion hemmen", true], ["NSAR erhöhen den Schutz durch obligate Schleimvermehrung", false]], "NSAR schwächen mehrere prostaglandinabhängige Schutzmechanismen.", 3),
  q(5, "Welche Faktoren erhöhen das Risiko einer gastroduodenalen Ulkuskrankheit oder Blutung?", [["Helicobacter pylori", true], ["NSAR beziehungsweise ASS", true], ["Frühere Ulkusblutung und höheres Alter", true], ["Kombination antithrombotischer Medikamente", true], ["Eine intakte Mukus-Bikarbonat-Barriere ohne Noxen", false]], "Infektion, Medikamente und individuelle Risikofaktoren wirken oft zusammen.", 2),
  q(6, "Welche Aussagen zu Hämatemesis und Kaffeesatzerbrechen stimmen?", [["Rotes Blut kann eine rasche obere GI-Blutung anzeigen", true], ["Kaffeesatzmaterial entsteht durch Kontakt von Blut mit Magensäure", true], ["Die Blutfarbe trennt Ulkus- und Varizenblutung nicht sicher", true], ["Kaffeesatzerbrechen beweist eine Blutung aus dem Duodenum", false], ["Hellrotes Blut schließt eine Ulkusblutung aus", false]], "Die Erscheinung beschreibt Dynamik und Säurekontakt, nicht sicher die Quelle.", 2),
  q(7, "Welche Befunde sprechen für Meläna?", [["Schwarzer, glänzender und klebriger Stuhl", true], ["Typischer intensiver Geruch", true], ["Entstehung durch Verdauung von Blut während der Darmpassage", true], ["Meläna kann auch nach bereits sistierter oberer Blutung fortbestehen", true], ["Meläna ist definitionsgemäß hellrotes Blut auf dem Toilettenpapier", false]], "Meläna ist verdautes Blut und beweist keine aktuell fortgesetzte Blutung.", 2),
  q(8, "Welche Befunde können einen frühen hämorrhagischen Schock anzeigen, obwohl der RR noch normal ist?", [["Tachykardie und steigender Schockindex", true], ["Kaltschweißigkeit und verlängerte Rekapillarisierung", true], ["Unruhe, Schwäche oder Synkope", true], ["Periphere Kälte und Blässe", true], ["Ein normaler Einzelblutdruck schließt relevanten Blutverlust sicher aus", false]], "Blutdruckabfall ist häufig ein spätes Zeichen; Verlauf und Perfusion sind entscheidend.", 3),
  q(9, "Welche Faktoren können die klinische Schockbeurteilung erschweren?", [["Betablocker können die Tachykardie begrenzen", true], ["Arterielle Hypertonie kann einen relativen Druckabfall verschleiern", true], ["Akuter Hb-Wert kann initial noch normal sein", true], ["Alter und kardiale Vorerkrankung verändern die Kompensation", true], ["Meläna erlaubt eine exakte Volumenberechnung", false]], "Kompensation, Medikamente und zeitverzögerte Laborveränderungen erzeugen Prüfungsfallen.", 3),
  q(10, "Welche Gefäßbezüge sind bei Ulkusblutungen prüfungsrelevant?", [["Ein posteriores Duodenalulkus kann die A. gastroduodenalis arrodieren", true], ["Ein Ulkus an der kleinen Kurvatur kann Äste der A. gastrica sinistra betreffen", true], ["Größere submuköse Gefäße erklären massive Blutungen", true], ["Die genaue Quelle wird meist endoskopisch festgestellt", true], ["Jede Ulkusblutung stammt aus der V. cava inferior", false]], "Gefäßlage und Ulkuslokalisation beeinflussen die Blutungsdynamik.", 3),
  q(11, "Welche Komplikationen einer Ulkuskrankheit sind möglich?", [["Blutung mit hämorrhagischem Schock", true], ["Perforation mit Peritonitis", true], ["Penetration in Nachbarorgane", true], ["Narbenbedingte Magenausgangsstenose", true], ["Obligate folgenlose Spontanheilung", false]], "Ulkuskrankheit kann bluten, durchbrechen, eindringen oder narbig verengen.", 2),
  q(12, "Welche Konstellation passt zu einer Ulkusperforation?", [["Plötzlich maximaler Oberbauchschmerz", true], ["Brettharte Abwehrspannung", true], ["Peritonismus und mögliche Schockzeichen", true], ["Zeitkritische chirurgische Versorgung", true], ["Beruhigende Entlassung bei nachlassendem Schmerz ohne Untersuchung", false]], "Perforation ist ein akutes Abdomen und verlangt sofortige chirurgische Abklärung.", 3),
  q(13, "Welche Maßnahmen sind bei massiver Hämatemesis vorrangig?", [["Leistungsfähige Absaugung vorbereiten und einsetzen", true], ["Atemwegs- und Aspirationsrisiko fortlaufend beurteilen", true], ["Erfahrene Atemwegshilfe früh nachfordern", true], ["Präoxygenierung und schwierige Sicht durch Blut einplanen", true], ["Den Patienten flach oral trinken lassen", false]], "Blut und Koagel machen obere GI-Blutung zu einem potenziell schwierigen Atemwegsnotfall.", 3),
  q(14, "Welche kreislaufbezogenen Maßnahmen sind bei instabiler oberer GI-Blutung angemessen?", [["Zwei großlumige periphere i.v.-Zugänge anstreben", true], ["Balancierte Kristalloide titriert zur Perfusionsstabilisierung", true], ["Vitaltrend und klinische Perfusion wiederholt erfassen", true], ["Wärmeerhalt und zeitkritischer Transport", true], ["Unbegrenzte Infusion bis zur Hypertonie unabhängig von Blutungsverlauf", false]], "Perfusion sichern, Verdünnung und Überinfusion vermeiden und definitive Blutstillung nicht verzögern.", 3),
  q(15, "Welche Differenzialdiagnosen einer vermuteten Ulkusblutung sind besonders relevant?", [["Ösophagus- oder Fundusvarizenblutung", true], ["Mallory-Weiss-Läsion", true], ["Erosive Gastritis oder Tumorblutung", true], ["Aortoenterische Fistel nach Aorteneingriff", true], ["Ausschließlich unkomplizierter Muskelkater", false]], "Obere GI-Blutung beschreibt zunächst ein Syndrom mit mehreren möglichen Quellen.", 3),
  q(16, "Welche Befunde erhöhen die Wahrscheinlichkeit einer Varizenblutung?", [["Bekannte Leberzirrhose oder portale Hypertension", true], ["Aszites, Ikterus oder bekannte Varizen", true], ["Massive Hämatemesis ohne typische Ulkusanamnese", true], ["Frühere Varizenblutung", true], ["Fehlende Leberzeichen schließen Varizen sicher aus", false]], "Leber- und Varizenanamnese verändern die Wahrscheinlichkeit, die Endoskopie sichert die Quelle.", 3),
  q(17, "Welche Anamnese macht eine aortoenterische Fistel besonders verdächtig?", [["Aortenprothese oder vorausgegangener Aorteneingriff", true], ["Kleine vorausgehende Warnblutung", true], ["Plötzliche massive GI-Blutung", true], ["Unmittelbare Änderung von Dringlichkeit und Zielklinik", true], ["Ausschluss allein durch einen vorübergehend normalen Blutdruck", false]], "Die Herald Bleed nach Aorteneingriff ist eine seltene, aber hochgefährliche Prüfungsfalle.", 3),
  q(18, "Welche Aussagen zur Tranexamsäure sind pharmakologisch richtig?", [["Sie vermindert die Aktivierung von Plasminogen zu Plasmin", true], ["Sie hemmt den Abbau von Fibrin", true], ["Sie stabilisiert vorhandene Gerinnsel", true], ["Sie ersetzt keine endoskopische Blutstillung", true], ["Sie löst Fibrinthromben gezielt auf", false]], "Tranexamsäure ist ein Antifibrinolytikum, kein Thrombolytikum.", 2),
  q(19, "Welche Risiken sind bei Tranexamsäure prüfungsrelevant?", [["Venöse Thromboembolien", true], ["Krampfanfälle, besonders bei hoher Exposition", true], ["Hypotonie bei zu schneller intravenöser Gabe", true], ["Dosisanpassung beziehungsweise Vorsicht bei Niereninsuffizienz", true], ["Garantierte Blutstillung ohne Nebenwirkungen", false]], "Antifibrinolyse verlangt eine passende Indikation und Risikoprüfung.", 3),
  q(20, "Wie ist Tranexamsäure bei nichttraumatischer Ulkusblutung einzuordnen?", [["Sie soll bei GI-Blutung präendoskopisch nicht generell gegeben werden", true], ["HALT-IT zeigte keine Senkung der blutungsbedingten Mortalität", true], ["HALT-IT zeigte mehr venöse Thromboembolien unter TXA", true], ["Die Thüringer Trauma-Zubereitung darf nicht automatisch übertragen werden", true], ["Jede Meläna ist eine verbindliche präklinische TXA-Indikation", false]], "Leitlinie und HALT-IT sprechen gegen eine unkritische Routinegabe.", 3),
  q(21, "Welche Aussage beschreibt die Thüringer TXA-Zubereitung korrekt, ohne die Indikation zu verfälschen?", [["Die B2A-Lernansicht zeigt 1 g in 10 ml Wirkstoff", true], ["90 ml NaCl ergänzen auf 100 ml", true], ["Die Kurzinfusion läuft über 10 Minuten", true], ["Diese Zubereitung gehört zum Trauma-Pfad", true], ["Die Zubereitung macht jede Ulkusblutung automatisch zur VFA-Indikation", false]], "Zubereitung und Indikation sind getrennt zu prüfen.", 3),
  q(22, "Welche Aussagen zu Glasgow-Blatchford-Score und Forrest-Klassifikation stimmen?", [["Der Glasgow-Blatchford-Score wird vor Endoskopie zur Risikostratifikation genutzt", true], ["Forrest beschreibt endoskopische Blutungsstigmata", true], ["Forrest Ia bezeichnet eine spritzende aktive Blutung", true], ["Forrest III bezeichnet einen sauberen Ulkusgrund", true], ["Beide Scores ersetzen präklinisch cABCDE", false]], "Die Instrumente gehören zu unterschiedlichen Zeitpunkten und ersetzen keine Akutbeurteilung.", 3),
  q(23, "Welche Angaben sind für die Voranmeldung besonders wertvoll?", [["Vitaltrend, Schockindex und klinische Perfusion", true], ["Art, Menge und zeitlicher Verlauf von Hämatemesis oder Meläna", true], ["Antikoagulanzien, Thrombozytenhemmer und letzte Einnahme", true], ["Ulkus-, Leber-, Varizen- und Aortenanamnese", true], ["Nur die Bezeichnung ‚Bauchschmerz‘ ohne Verlauf", false]], "Die Zielklinik benötigt Dynamik, Risiken, Schweregrad und bisherige Maßnahmen.", 3),
  q(24, "Ein Patient hat wiederholt rote Hämatemesis, kalte Haut, RR 108/68 mmHg und Puls 118/min. Welche Bewertungen sind richtig?", [["Der Schockindex liegt über 1 und ist auffällig", true], ["Der noch nicht hypotone Blutdruck schließt Schock nicht aus", true], ["Absaugung, Zugänge, Wärmeerhalt und zeitkritischer Transport sind erforderlich", true], ["Ulkus- und Varizenblutung bleiben differenzialdiagnostisch offen", true], ["Routine-TXA ist allein aufgrund der Hämatemesis zwingend", false]], "Kompensierter Schock und offene Blutungsquelle verlangen parallele Stabilisierung und definitive Versorgung.", 3),
];
