import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; children: ReactNode };

export default function UlkusblutungLesson({ Figure, children }: Props) {
  const section = (number: string, kicker: string, title: string, body: ReactNode) => <details open className="lesson-section rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>{kicker}</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;

  return <article className="lesson-article angina-pectoris-lesson reference-reading-lesson akutes-abdomen-lesson ulkusblutung-lesson">
    <div className="lesson-intro"><p className="lead">Hämatemesis, Kaffeesatzerbrechen oder Meläna können die erste sichtbare Manifestation einer gastroduodenalen Ulkusblutung sein. Präklinisch stehen Atemwegsschutz, Erkennen des hämorrhagischen Schocks, rascher Transport und die Abgrenzung anderer Blutungsquellen im Vordergrund.</p></div>

    {section("01", "Defekt bis unter die Schleimhaut", "Definition", <><p>Ein <b>gastroduodenales Ulkus</b> ist ein umschriebener Defekt der Magen- oder Duodenalschleimhaut, der die Muscularis mucosae überschreitet und in die Submukosa oder tiefer reicht. Erodiert der Defekt ein Gefäß, entsteht eine obere gastrointestinale Blutung.</p><div className="pulmo-compare"><div><small>Erosion</small><h3>Oberflächlicher Defekt</h3><p>Bleibt auf Mukosa beziehungsweise Epithel begrenzt und überschreitet die Muscularis mucosae nicht.</p></div><div><small>Ulkus</small><h3>Tiefer Gewebedefekt</h3><p>Reicht mindestens in die Submukosa; Blutung, Penetration, Perforation und Narbenstenose sind möglich.</p></div></div><aside className="knowledge-note"><b>Arbeitsdiagnose statt Enddiagnose</b><p>Die Blutungsquelle lässt sich präklinisch nicht sicher lokalisieren. „Verdacht auf obere GI-Blutung, möglicherweise Ulkusblutung“ ist bei passender Klinik die fachlich saubere Formulierung.</p></aside></>)}

    {section("02", "Magen, Duodenum und Gefäßversorgung", "Anatomie und Physiologie", <><Figure src="/lessons/akutes-abdomen/magen.jpg" alt="Beschriftete Anatomie des Magens mit Ösophagus, Duodenum, Pylorus und Muskelschichten" caption="Magen und Duodenum · Lage, Abschnitte und Muskelschichten" wide /><Figure src="/lessons/abdominaltrauma/wandaufbau.jpg" alt="Wandschichten des Gastrointestinaltrakts mit Mukosa, Submukosa, Muskularis und Serosa" caption="Wandaufbau des Gastrointestinaltrakts · vom Lumen nach außen" wide /><div className="pulmo-care-grid"><div><span>M</span><b>Mukosa</b><small>Epithel, Drüsen, Schleim-Bikarbonat-Barriere und Muscularis mucosae.</small></div><div><span>S</span><b>Submukosa</b><small>Bindegewebe mit größeren Blut- und Lymphgefäßen sowie Nervenplexus.</small></div><div><span>↔</span><b>Muscularis propria</b><small>Im Magen drei Muskelschichten; Durchmischung und Weitertransport des Chymus.</small></div><div><span>○</span><b>Serosa</b><small>Äußere Gleit- und Bindegewebsschicht der intraperitonealen Organabschnitte.</small></div></div><div className="pulmo-compare"><div><small>Schutzfaktoren</small><h3>Mukus, Bikarbonat und Perfusion</h3><p>Schleim und Bikarbonat halten Säure vom Epithel fern. Prostaglandine fördern Schleimhautdurchblutung, Sekretion und Reparatur.</p></div><div><small>Aggressive Faktoren</small><h3>Säure und Pepsin</h3><p>Belegzellen bilden Salzsäure und Intrinsic Factor; Hauptzellen geben Pepsinogen ab. Im sauren Milieu entsteht das eiweißspaltende Pepsin.</p></div></div><p>Die arterielle Versorgung stammt aus Ästen des Truncus coeliacus. Klinisch bedeutsam sind unter anderem die <b>A. gastroduodenalis</b> hinter dem proximalen Duodenum und die <b>A. gastrica sinistra</b> an der kleinen Kurvatur: Wird ein größeres Gefäß arrodiert, kann die Blutung rasch lebensbedrohlich werden.</p></>)}

    {section("03", "Schutzbarriere verliert gegen Säure", "Ursachen und Pathophysiologie", <><div className="pulmo-path"><span>Schleimhautschaden</span><i>→</i><span>Barriereverlust</span><i>→</i><span>Säure-/Pepsinwirkung</span><i>→</i><span>Ulkus</span><i>→</i><span>Gefäßarrosion</span></div><div className="pulmo-risk-grid"><div><b>Helicobacter pylori</b><p>Chronische Entzündung verändert Schleimhautschutz und Säureregulation. Besonders häufig ist die Verbindung mit Duodenalulzera.</p></div><div><b>NSAR und ASS</b><p>Vor allem die COX-1-Hemmung vermindert protektive Prostaglandine. Schleim, Bikarbonat, Perfusion und Reparatur nehmen ab; Blutungsrisiken addieren sich unter Antikoagulation.</p></div><div><b>Weitere Faktoren</b><p>Nikotin, Alkohol, schwere akute Erkrankung, frühere Ulzera, höheres Alter und kombinierte antithrombotische Therapie erhöhen das Risiko.</p></div></div><p>Durchdringt das Ulkus die Submukosa, kann es ein Gefäß eröffnen. Blut gelangt in das Lumen, reagiert teilweise mit Magensäure und erscheint als Kaffeesatz; bei rascher Blutung kann es unverändert rot erbrochen werden. Blutabbau und Darmpassage führen zur schwarzen, klebrigen Meläna.</p><aside className="red-flags"><span>!</span><div><small>Prüfungsfalle</small><h3>Blutfarbe beweist die Quelle nicht</h3><p>Hellrote Hämatemesis kann sowohl bei massiver Ulkusblutung als auch bei Varizenblutung auftreten. Kaffeesatzerbrechen zeigt Kontakt mit Magensäure, nicht sicher die genaue Läsion.</p></div></aside></>)}

    {section("04", "Blutung erkennen und quantifizieren", "Symptome und Befunde", <><div className="pulmo-symptoms"><span>Hämatemesis</span><span>Kaffeesatzerbrechen</span><span>Meläna / Teerstuhl</span><span>Epigastrischer Schmerz</span><span>Übelkeit und Schwäche</span><span>Synkope oder Präsynkope</span></div><div className="pulmo-compare"><div><small>Frühe Kreislaufkompensation</small><h3>Tachykardie, Blässe, Kaltschweißigkeit</h3><p>Normotonie schließt eine relevante Blutung nicht aus. Medikamente wie Betablocker können eine Tachykardie maskieren.</p></div><div><small>Dekompensation</small><h3>Hypotonie, Vigilanzminderung, Oligurie</h3><p>Ein steigender Schockindex, verlängerte Rekapillarisierungszeit und periphere Kälte sprechen für kritische Minderperfusion.</p></div></div><p>Ulcus ventriculi verursacht häufig nahrungsabhängigen epigastrischen Schmerz; beim Duodenalulkus sind Nüchtern-, Nacht- oder Spätschmerz typisch. Diese Muster sind nicht zuverlässig genug, um die Blutungsquelle im Einsatz sicher festzulegen.</p></>)}

    {section("05", "Blutung, Perforation und Aspiration", "Komplikationen und Gefahren", <><div className="pulmo-risk-grid"><div><b>Hämorrhagischer Schock</b><p>Anhaltender Blutverlust vermindert Vorlast und Herzzeitvolumen; Organe werden hypoperfundiert. Blutdruckabfall ist ein spätes Zeichen.</p></div><div><b>Aspiration</b><p>Blut, Koagel und Erbrochenes können den Atemweg verlegen und aspiriert werden. Absaugung und Atemwegsplan müssen sofort verfügbar sein.</p></div><div><b>Perforation</b><p>Plötzlicher Vernichtungsschmerz, bretthartes Abdomen und Peritonismus sprechen für den Durchbruch in die freie Bauchhöhle.</p></div><div><b>Penetration / Stenose</b><p>Ein Ulkus kann in Nachbarorgane wie das Pankreas eindringen oder durch Vernarbung den Magenausgang verengen.</p></div></div><aside className="diagnostic-boundary"><span>!</span><div><b>Normales Hämoglobin beruhigt präklinisch nicht</b><p>Bei akuter Blutung kann der Hb-Wert initial noch normal sein, weil Blutbestandteile und Plasma gleichzeitig verloren gehen. Entscheidend sind Klinik, Verlauf und Perfusion.</p></div></aside></>)}

    {section("06", "Alles für Blutung und Atemweg", "Einsatzmaterialien", <div className="material-chips">{["Notfallrucksack", "Absaugung mit großlumigem Katheter", "Sauerstoff und Beatmung", "Monitoring / 12-Kanal-EKG", "BZ und Temperatur", "Zwei großlumige i.v.-Zugänge", "Balancierte Kristalloide", "Material zur Atemwegssicherung", "Wärmeerhalt", "Trage / Vakuummatratze"].map(item => <span key={item}>{item}</span>)}</div>)}

    {section("07", "cABCDE und Blutungsanamnese", "Erstmaßnahmen und Diagnostik", <><div className="pulmo-care-grid"><div><span>A</span><b>Atemweg schützen</b><small>Blut absaugen, Oberkörper bei wachem Patienten erhöht; bei Bewusstseinsstörung lage- und situationsgerecht sichern.</small></div><div><span>B</span><b>Oxygenierung prüfen</b><small>SpO₂ und Atemarbeit überwachen; Sauerstoff nach Hypoxämie und klinischer Situation, nicht unkritisch allein wegen der Blutung.</small></div><div><span>C</span><b>Blutungsschock behandeln</b><small>Monitoring, wiederholter RR, Rekapillarisierung, Schockindex, zwei i.v.-Zugänge und titrierte balancierte Kristalloide bei Instabilität.</small></div><div><span>D/E</span><b>Verlauf und Wärme</b><small>Vigilanz, BZ, Temperatur, Abdomen, Haut, Meläna und Begleitzeichen wiederholt erfassen; konsequenter Wärmeerhalt.</small></div></div><h3>SAMPLERS · fokussiert</h3><div className="samplers-grid">{[["S · Symptome", "Menge und Verlauf von Blut, Meläna, Schmerz, Synkope"], ["A · Allergien", "Medikamente, Kontrastmittel"], ["M · Medikamente", "ASS, NSAR, DOAK, VKA, Heparin, Steroide"], ["P · Vorgeschichte", "Ulkus, H. pylori, Zirrhose, Varizen, Aorteneingriff"], ["L · Letzte Aufnahme", "Nahrung, Alkohol, letzter Medikamentenzeitpunkt"], ["E · Ereignis", "Erbrechen, Schmerzbeginn, Kollaps, Blutungsbeginn"], ["R · Risiken", "Frühere GI-Blutung, Antikoagulation, Lebererkrankung"], ["S · Schwangerschaft", "Bei passender Patientin differenzialdiagnostisch relevant"]].map(([label, text]) => <p key={label}><b>{label}</b>{text}</p>)}</div><p><b>Transportentscheidung:</b> Instabilität, fortgesetzte Hämatemesis, Synkope, relevante Komorbidität oder Antikoagulation bedeuten zeitkritischen Transport mit Voranmeldung in eine Klinik mit Endoskopie, Intensivmedizin und Interventionsmöglichkeit. Stabilisierung und Transport laufen parallel.</p></>)}

    {section("08", "Nicht jede Hämatemesis ist ein Ulkus", "Differenzialdiagnosen und Entscheidungen", <><div className="differential-grid">{["Ösophagus- oder Fundusvarizenblutung", "Mallory-Weiss-Läsion", "Erosive Gastritis / Duodenitis", "Refluxösophagitis", "Tumorblutung", "Aortoenterische Fistel", "Verschlucktes Blut aus Nase oder Mund", "Hämoptyse", "Perforiertes Ulkus", "Akutes Koronarsyndrom"].map(item => <span key={item}>{item}</span>)}</div><div className="pulmo-compare"><div><small>Ulkusblutung</small><h3>Risikofaktoren und epigastrische Beschwerden</h3><p>H. pylori, NSAR, frühere Ulzera und typische Schmerzgeschichte stützen die Vermutung, beweisen sie aber nicht.</p></div><div><small>Varizenblutung</small><h3>Hinweise auf portale Hypertension</h3><p>Leberzirrhose, Aszites, Ikterus, bekannte Varizen oder massive schmerzlose Hämatemesis erhöhen die Wahrscheinlichkeit.</p></div></div><aside className="red-flags"><span>!</span><div><small>Seltene Hochrisiko-DD</small><h3>Aortoenterische Fistel</h3><p>Nach Aortenprothese oder Aorteneingriff kann eine scheinbar kleine „Herald Bleed“ einer exsanguinierenden Blutung vorausgehen. Diese Anamnese verändert Zielklinik und Dringlichkeit sofort.</p></div></aside></>)}

    {section("09", "Antifibrinolyse mit klarer Grenze", "Tranexamsäure", <><div className="pulmo-compare"><div><small>Wirkprinzip</small><h3>Stabilisiert bestehendes Fibrin</h3><p>Tranexamsäure besetzt Lysinbindungsstellen am Plasminogen und vermindert dessen Aktivierung zu Plasmin. Dadurch wird der Abbau von Fibrin gebremst; ein Gefäßverschluss oder eine endoskopische Blutstillung wird dadurch nicht ersetzt.</p></div><div><small>Nebenwirkungen und Risiken</small><h3>Thrombose und Krampfanfälle beachten</h3><p>Übelkeit, Erbrechen, Diarrhö, Hypotonie bei zu schneller Gabe, Sehstörungen, Krampfanfälle und thromboembolische Ereignisse sind prüfungsrelevant. Bei aktiver Thromboembolie, schwerer Niereninsuffizienz oder Überempfindlichkeit ist besondere Zurückhaltung erforderlich.</p></div></div><aside className="diagnostic-boundary"><span>!</span><div><b>Keine generelle Gabe bei Ulkusblutung</b><p>Die deutsche S2k-Leitlinie 2025 empfiehlt, Tranexamsäure bei gastrointestinaler Blutung präendoskopisch nicht generell zu geben. HALT-IT zeigte keinen Rückgang der blutungsbedingten Mortalität, aber mehr venöse Thromboembolien. Die Thüringer B2A-Zubereitung gehört zum traumatischen Blutungspfad und darf nicht automatisch auf eine nichttraumatische Ulkusblutung übertragen werden.</p></div></aside><p><b>Prüfungsformulierung:</b> Wirkstoff, Wirkung, Risiken und vorhandene Trauma-Zubereitung erklären – bei isolierter Ulkusblutung jedoch keine Routineindikation behaupten. Eine Gabe wäre nur auf einer hierfür gültigen ärztlichen Anordnung oder spezifischen SOP zu begründen.</p></>)}

    {section("10", "Ziel ist definitive Blutstillung", "Weitere Maßnahmen", <><div className="pulmo-vfa-flow"><div><span>1</span><b>NA früh nachfordern</b><small>Bei Schock, fortgesetzter Hämatemesis, Vigilanzabfall, Atemwegsgefahr oder relevanter Komorbidität.</small></div><div><span>2</span><b>Perfusion titriert sichern</b><small>Balancierte Kristalloide bei Instabilität; Überinfusion und unnötig hohe Druckziele bei unkontrollierter Blutung vermeiden.</small></div><div><span>3</span><b>Atemweg vorausplanen</b><small>Absaugung, Präoxygenierung und erfahrenes Atemwegsteam; Blut und Koagel erschweren die Sicht.</small></div><div><span>4</span><b>Endoskopiezentrum</b><small>Voranmeldung mit Vitaltrend, Blutungszeichen, Antithrombotika, Zugängen, Volumen und Atemwegsstatus.</small></div></div><div className="pulmo-compare"><div><small>Klinische Risikostratifikation</small><h3>Glasgow-Blatchford-Score</h3><p>Hilft klinisch vor der Endoskopie, Interventions- und Überwachungsbedarf einzuschätzen. Präklinisch ersetzt er weder cABCDE noch die Transportentscheidung.</p></div><div><small>Endoskopischer Befund</small><h3>Forrest-Klassifikation</h3><p>Ia spritzend, Ib sickernd, IIa sichtbares Gefäß, IIb adhärentes Koagel, IIc Hämatinbelag, III sauberer Ulkusgrund. Sie wird erst endoskopisch erhoben.</p></div></div><p>Die definitive Blutstillung erfolgt endoskopisch, gegebenenfalls angiografisch oder operativ. Nüchternheit, lückenlose Dokumentation und eine strukturierte Übergabe sind präklinisch entscheidend.</p></>)}

    {children}
    <p className="lesson-source">Hauptgrundlage: bereitgestellte Unterlagen „9. Ulkusblutung“. Fachlich abgeglichen mit der S2k-Leitlinie Gastrointestinale Blutung 2025, der ESGE-Leitlinie zur nichtvarikösen oberen GI-Blutung und HALT-IT. Medikamentendosierungen und Zubereitungen werden ausschließlich im Rahmen der Thüringer VFA 2026/2027 dargestellt.</p>
  </article>;
}
