import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; children: ReactNode };

export default function UnterkuehlungLesson({ Figure, children }: Props) {
  const section = (number: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>Unterkühlung</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;
  return <article className="lesson-article rippenfraktur-lesson unterkuehlung-lesson">
    <div className="lesson-intro"><p className="lead">Bei Unterkühlung zählt nicht nur die gemessene Temperatur: Bewusstsein, Kreislauf, Begleitverletzungen und der zeitliche Verlauf bestimmen, wie vorsichtig gerettet und wohin transportiert wird.</p></div>
    {section("01", "Definition", <><p>Eine akzidentelle Unterkühlung liegt vor, wenn die Körperkerntemperatur unbeabsichtigt unter <b>35 °C</b> sinkt. Wärmeverlust übersteigt dabei Wärmebildung und Wärmezufuhr.</p><div className="pulmo-compare"><div><small>Akut</small><h3>Rasche Auskühlung</h3><p>Etwa nach Eintauchen in kaltes Wasser oder Verschüttung. Auch eine Person, die zunächst noch wach wirkt, kann sich rasch verschlechtern.</p></div><div><small>Subakut</small><h3>Allmähliche Auskühlung</h3><p>Etwa bei längerem Liegen, Alkohol- oder Medikamenteneinfluss, Erkrankung oder unzureichendem Schutz vor Kälte.</p></div></div></>)}
    {section("02", "Anatomie und Physiologie", <><p>Die Haut trennt den Körper von der Umgebung und beteiligt sich über Durchblutung, Schweißbildung und Sinneswahrnehmung an der Temperaturregulation. Der Hypothalamus koordiniert die Reaktion auf Kälte.</p><div className="pulmo-anatomy-grid"><div><small>Außen</small><b>Epidermis</b><p>Gefäßlose Barriere gegen die Umgebung; Versorgung aus den tieferen Hautschichten.</p></div><div><small>Mitte</small><b>Dermis</b><p>Gefäße, Nerven, Rezeptoren, Haarfollikel und Drüsen; die Hautdurchblutung beeinflusst den Wärmeverlust.</p></div><div><small>Innen</small><b>Subkutis</b><p>Fettgewebe als Energiespeicher und Wärmeisolator; Übergang zur darunterliegenden Muskulatur.</p></div></div><Figure src="/lessons/unterkuehlung/haut-1.jpg" alt="Beschriftete anatomische Schichten der Haut mit Blutgefäßen, Nerven, Rezeptoren und Unterhautfettgewebe" caption="Hautaufbau · Originalabbildung aus Print 11" wide /><Figure src="/lessons/unterkuehlung/haut-2.jpg" alt="Schematische Hautschichten mit Epidermis, Dermis und Subkutis" caption="Hautschichten im Überblick · Originalabbildung aus Print 11" wide /><p>Bei Kälte verengen sich periphere Gefäße und verringern den Wärmeverlust. Muskelzittern erzeugt zusätzlich Wärme, steigert aber Sauerstoff- und Energiebedarf. Mit fortschreitender Unterkühlung lassen Schutzreaktionen, Bewusstsein und Organfunktionen nach.</p></>)}
    {section("03", "Pathophysiologie und Ursachen", <><div className="pulmo-path"><span>Wärmeverlust</span><i>→</i><span>Vasokonstriktion / Zittern</span><i>→</i><span>Kerntemperatur fällt</span><i>→</i><span>Organfunktionen verlangsamen sich</span></div><div className="pulmo-risk-grid"><div><b>Wärmeverlust</b><p>Nasse Kleidung, kaltes Wasser, Wind, kalter Untergrund oder lange Exposition erhöhen die Auskühlung.</p></div><div><b>Verminderte Gegenregulation</b><p>Erschöpfung, Alkohol, Sedierung, Bewusstseinsstörung, Unterzuckerung oder schwere Krankheit erschweren Wärmeerzeugung und Selbstrettung.</p></div></div><p>Kälte kann eine Diurese begünstigen. Gerinnung und Thrombozytenfunktion werden bei tiefer Hypothermie beeinträchtigt; Blutung und Trauma bleiben deshalb besonders relevant. Bei Bergung, Bewegung oder Wiedererwärmung kann die Kerntemperatur weiter fallen (<b>Afterdrop</b>). Bei schwer Unterkühlten kann die Rettung zudem einen Kreislaufkollaps auslösen (<b>rescue collapse</b>).</p><aside className="diagnostic-boundary"><span>!</span><div><b>Schonende Rettung</b><p>Vor allem bei tiefer Unterkühlung möglichst waagerecht und vorsichtig bewegen. Traumabedingte Immobilisationsmaßnahmen nach Befund durchführen – Unterkühlung allein macht keine vollständige Immobilisierung erforderlich.</p></div></aside></>)}
    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", <><div className="pulmo-symptoms">{["Kälteexposition / nasse Kleidung", "Kalte Haut, Blässe", "Zittern – später mögliches Ausbleiben", "Verlangsamung und Koordinationsstörung", "Verwirrtheit bis Bewusstlosigkeit", "Langsame Atmung und Bradykardie"].map(x => <span key={x}>{x}</span>)}</div><p>Verwirrtheit, inadäquates Verhalten und gelegentlich paradoxes Entkleiden können zur fortgeschrittenen Unterkühlung gehören. Das Fehlen von Zittern schließt sie nicht aus. Atmung und Puls können so schwach sein, dass eine kurze Routinekontrolle sie übersieht.</p><aside className="red-flags"><span>!</span><div><small>Red Flags</small><h3>Instabilität erkennen</h3><p>Herzfrequenz &lt; 45/min, systolischer Blutdruck &lt; 90 mmHg, ventrikuläre Arrhythmie oder Kerntemperatur &lt; 30 °C sprechen nach ERC 2025 für ein erhöhtes Risiko eines Kreislaufstillstands und erfordern die frühe Abstimmung mit einem ECLS-Zentrum.</p></div></aside></>)}
    {section("05", "Komplikationen und Gefahren", <><div className="rib-fracture-grid">{[["Rhythmusstörungen", "Mit sinkender Kerntemperatur nehmen Bradykardie und das Risiko ventrikulärer Arrhythmien zu."], ["Atem- und Kreislaufstillstand", "Lebenszeichen können extrem schwach sein; vor der Einordnung gründlich und bis zu einer Minute prüfen."], ["Gerinnungsstörung", "Trauma und Blutung können durch die kältebedingte Gerinnungshemmung verschärft werden."], ["Rescue collapse / Afterdrop", "Bei Bergung und Wiedererwärmung kann die Kerntemperatur weiter fallen oder der Kreislauf kollabieren."], ["Begleitursache übersehen", "Intoxikation, Hypoglykämie, Sepsis und Verletzungen können Ursache und Folge der Exposition zugleich sein."]].map(([a,b]) => <div key={a}><b>{a}</b><span>{b}</span></div>)}</div></>)}
    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", <div className="material-chips">{["Wärmeschutz / Decken", "Nässeschutz und trockene Kleidung", "Isolierende Unterlage", "Niedrig messendes Kerntemperatur-Thermometer", "EKG / RR / SpO₂", "BZ-Messung", "Atemwegs- und Reanimationsausrüstung", "Material für vorsichtigen Transport", "Traumamaterial nach Lage"].map(x => <span key={x}>{x}</span>)}</div>)}
    {section("07", "Erstmaßnahmen und Anamnese", <><div className="pulmo-care-grid"><div><span>01</span><b>Eigenschutz &amp; Bergung</b><small>Aus Kälte und Nässe retten; schwere Hypothermie möglichst schonend und waagerecht bewegen.</small></div><div><span>02</span><b>cABCDE</b><small>Atemweg, Atmung, Kreislauf, Blutungen, Verletzungen und Bewusstsein beurteilen.</small></div><div><span>03</span><b>Wärme erhalten</b><small>Vor Wind und Boden isolieren; nasse Kleidung in warmer Umgebung entfernen oder trocken einhüllen, ohne weitere Auskühlung.</small></div><div><span>04</span><b>Messen &amp; überwachen</b><small>Niedrig messende Kerntemperatur, EKG, BZ und Vitalverlauf; Standardthermometer kann versagen.</small></div></div><h3>SAMPLERS · fokussiert</h3><div className="samplers-grid">{[["S · Symptome", "Zittern, Bewusstsein, Atmung, Schmerz"], ["A · Allergien", "Bekannte Unverträglichkeiten"], ["M · Medikamente", "Sedativa, Betablocker, Antikoagulanzien"], ["P · Vorgeschichte", "Herz, Stoffwechsel, Neurologie"], ["L · Letzte Aufnahme", "Nahrung, Alkohol, andere Substanzen"], ["E · Ereignis", "Exposition, Wasser, Wind, Liegezeit"], ["R · Risiken", "Trauma, Ertrinken, Verschüttung"], ["S · Schwangerschaft", "Falls relevant"]].map(([a,b]) => <p key={a}><b>{a}</b>{b}</p>)}</div><p>Bei Bewusstlosigkeit Atmung und Puls bis zu <b>einer Minute</b> prüfen. Ist keine Kerntemperatur messbar, die klinische Stadieneinteilung nur als Orientierung verwenden; Intoxikation, Trauma oder Hypoglykämie können den Bewusstseinszustand unabhängig von der Temperatur verändern.</p></>)}
    {section("08", "Differenzialdiagnosen und Entscheidungsfindung", <><div className="differential-grid">{["Hypoglykämie", "Alkohol-/Medikamentenintoxikation", "Schlaganfall", "Schädel-Hirn-Trauma", "Sepsis", "Endokrine Entgleisung", "Ertrinken / Asphyxie", "Andere Schockursache"].map(x => <span key={x}>{x}</span>)}</div><h3>Revidierte Schweizer Stadien · klinische Orientierung</h3><div className="pulmo-care-grid"><div><span>I</span><b>Wach</b><small>Meist etwa 35 bis 32 °C.</small></div><div><span>II</span><b>Bewusstsein beeinträchtigt</b><small>Meist &lt; 32 bis 28 °C.</small></div><div><span>III</span><b>Bewusstlos, Lebenszeichen</b><small>Meist unter 28 °C; Temperaturbereiche sind keine harte Diagnosegrenze.</small></div><div><span>IV</span><b>Keine Lebenszeichen</b><small>Temperatur variabel; Reanimationsentscheidung nach Gesamtbefund.</small></div></div><p>Eine vorhandene Temperaturmessung und die wiederholte Beurteilung von Atmung, Kreislauf und Begleiterkrankungen sind wichtiger als eine starre Zuordnung nach Bewusstsein allein.</p></>)}
    {section("09", "Weitere Maßnahmen", <><div className="pulmo-vfa-flow"><div><span>↗</span><b>Schonend transportieren</b><small>Aus- und Umlagerung ohne unnötige Belastung; Wärmeverlust weiter begrenzen.</small></div><div><span>⚑</span><b>Früh abstimmen</b><small>Bei Instabilität oder &lt; 30 °C Notarzt und ECLS-Zentrum früh einbinden.</small></div><div><span>↻</span><b>Verlauf prüfen</b><small>Bewusstsein, EKG, Atmung, Blutdruck und Kerntemperatur wiederholt beurteilen.</small></div><div><span>→</span><b>Zielklinik wählen</b><small>Bei drohendem oder bestehendem Stillstand ECLS/ECMO-Eignung und Transportfähigkeit abklären.</small></div></div><p>Passive Wärmeerhaltung und – je nach Schwere und Ausstattung – aktive externe Wärme beziehungsweise erwärmte Infusionen erfolgen ohne Verzögerung zeitkritischer Versorgung. Traumata, Hypoxie und Hypoglykämie parallel behandeln.</p></>)}
    {section("10", "Reanimationssituationen · ERC 2025", <>
      <div className="hypo-resus-check"><span>01 · Entscheidung</span><div><h3>Lebenszeichen bis zu 1 Minute prüfen</h3><p>Bei Bewusstlosigkeit können Atmung und Puls extrem schwach sein. EKG und niedrig messende Kerntemperatur ergänzen die klinische Prüfung.</p></div></div>
      <div className="hypo-resus-branches">
        <div className="hypo-resus-branch stable"><small>Lebenszeichen vorhanden</small><h3>Keine CPR</h3><p>Schonend und waagerecht retten, isolieren, überwachen und die Kerntemperatur verfolgen.</p><b>Bei HF &lt; 45/min, systolischem RR &lt; 90 mmHg, ventrikulärer Arrhythmie oder &lt; 30 °C: ECLS-Zentrum früh kontaktieren.</b></div>
        <div className="hypo-resus-branch arrest"><small>Keine Lebenszeichen</small><h3>CPR beginnen</h3><p>Kontinuierliche Thoraxkompressionen und Beatmung nach ALS; Normoxie anstreben und ECLS/ECMO-Ziel früh abstimmen.</p><b>Unter 28 °C sind verzögerte oder intermittierende CPR nur Ausnahmen, wenn sofortige bzw. durchgehende CPR wegen Gefahr oder schwieriger Rettung unmöglich ist.</b></div>
      </div>
      <div className="hypo-resus-divider"><span>02 · Während der Reanimation</span></div>
      <div className="hypo-resus-rules">
        <div><span className="hypo-resus-icon">↯</span><h3>VF / pVT</h3><p>Bis zu <b>3 Schocks</b>. Bleibt der Rhythmus refraktär, weitere Versuche bis zur Erwärmung auf <b>über 30 °C</b> zurückstellen.</p></div>
        <div><span className="hypo-resus-icon">↻</span><h3>CPR &amp; Wärme</h3><p>CPR grundsätzlich <b>kontinuierlich</b> fortführen. Aktive Wiedererwärmung und Transport zur geeigneten Klinik organisieren.</p></div>
      </div>
      <h3 className="hypo-resus-subtitle">Adrenalin nach Kerntemperatur</h3>
      <div className="hypo-temp-grid">
        <div><span>Unter 30 °C</span><p>Gabe kann bis zur Erwärmung zurückgestellt werden. Ist ECPR nicht zeitnah erreichbar, kann <b>einmal 1 mg i.v.</b> erwogen werden; keine üblichen Wiederholungsintervalle.</p></div>
        <div><span>30 bis &lt; 35 °C</span><p>Intervalle gegenüber dem Standard <b>verdoppeln</b> (etwa alle 6–10 Minuten).</p></div>
        <div><span>Ab 35 °C</span><p><b>Standard-ALS</b> für die Medikamentengabe.</p></div>
      </div>
      <p className="hypo-resus-note">Asphyxie vor Auskühlung, schweres Trauma und andere Ursachen verändern die Prognose. Die Reihenfolge der Ereignisse gehört deshalb in die Übergabe.</p>
      <p className="hypo-resus-source">Für diesen Sonderfall ist im bereitgestellten Thüringer VFA-Heft keine eigene Unterkühlungs-VFA enthalten. <a href="https://www.erc.edu/media/wwufbysp/gl2025-06-spec-circ-e.pdf" target="_blank" rel="noreferrer">ERC 2025 · Originalleitlinie ↗</a></p>
    </>)}
    {children}
    <p className="lesson-source">Grundlage: Print 11.pdf (Definition, Hautabbildungen und Themenstruktur). Präklinische Sonderregeln: <a href="https://www.erc.edu/media/wwufbysp/gl2025-06-spec-circ-e.pdf" target="_blank" rel="noreferrer">ERC-Leitlinien 2025</a>. Abgleich: <a href="https://www.aelrd-thueringen.de/verfahrensanweisungen-fuer-den-thueringer-rettungsdienst-algorithmen/" target="_blank" rel="noreferrer">Thüringer VFA 2026/27</a>.</p>
  </article>;
}
