import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";
type Option = [string, boolean];
function q(n: number, prompt: string, options: Option[], source: string): ThoraxtraumaChoiceQuestion {
  const shift = n % options.length;
  return { id: `unterkuehlung-q-${String(n).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty: 3 };
}

export const unterkuehlungQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Nach einer kalten Nacht wird eine Person mit 34,4 °C Kerntemperatur gefunden. Welche Aussagen sind zutreffend?", [["Eine akzidentelle Unterkühlung liegt vor", true], ["Die Temperatur allein legt die Ursache der Bewusstseinsstörung fest", false], ["Der weitere Wärmeverlust muss begrenzt werden", true], ["Ein Wert über 32 °C schließt relevante Verletzungen aus", false]], "Akzidentelle Hypothermie beginnt unter 35 °C; parallel nach auslösenden und begleitenden Problemen suchen."),
  q(2, "Welche Befundkonstellationen sprechen für eine rasche oder allmähliche Auskühlung?", [["Eintauchen in kaltes Wasser kann rasch auskühlen", true], ["Langes Liegen unter Alkoholeinfluss kann subakut auskühlen", true], ["Eine nasse Person verliert bei Wind zusätzlich Wärme", true], ["Nur bei Lufttemperaturen unter 0 °C ist Hypothermie möglich", false], ["Subakute Auskühlung setzt ein kaltes Gewässer voraus", false]], "Wasser, Wind und Expositionsdauer sind entscheidend; auch mäßig kalte Umgebungen können gefährlich sein."),
  q(3, "Welche Zuordnungen zu Hautschichten und Wärmehaushalt sind korrekt?", [["Die Epidermis ist selbst gefäßlos", true], ["Die Dermis enthält Gefäße und Sinnesrezeptoren", true], ["Fettgewebe der Subkutis trägt zur Isolation bei", true], ["Die Epidermis reguliert Wärme durch eigene Arterien", false], ["Die Subkutis besteht ausschließlich aus Muskelgewebe", false]], "Die Hautabbildungen zeigen die gefäßlose Epidermis, vaskularisierte Dermis und fettgewebsreiche Subkutis."),
  q(4, "Welche physiologischen Reaktionen sind bei beginnender Kälteexposition zu erwarten?", [["Periphere Vasokonstriktion vermindert den Wärmeverlust", true], ["Muskelzittern steigert den Energiebedarf", true], ["Zittern senkt den Sauerstoffbedarf der Muskulatur", false], ["Vasodilatation der Haut ist der wichtigste initiale Wärmeschutz", false]], "Kälteabwehr besteht wesentlich aus verringerter Hautdurchblutung und Wärmeproduktion durch Zittern."),
  q(5, "Ein erschöpfter Patient hört nach längerem deutlichem Zittern auf zu zittern. Welche Schlussfolgerungen passen?", [["Das kann Ausdruck fortschreitender Unterkühlung sein", true], ["Bewusstsein und Kerntemperatur sind erneut zu prüfen", true], ["Fehlendes Zittern belegt eine stabile Normaltemperatur", false], ["Andere Ursachen der Vigilanzänderung bleiben möglich", true], ["Die Exposition darf nun ohne Wärmeschutz fortgeführt werden", false]], "Mit Fortschreiten kann Zittern nachlassen; der Befund ist keine Entwarnung."),
  q(6, "Welche Faktoren erschweren die natürliche Kälteabwehr oder die Selbstrettung?", [["Alkoholintoxikation", true], ["Sedierende Medikamente", true], ["Trockene Kleidung als Ursache der Auskühlung", false], ["Bewusstseinsklarheit garantiert normale Kerntemperatur", false]], "Intoxikation, Sedierung und Stoffwechselstörungen begünstigen Unterkühlung und können Symptome überlagern."),
  q(7, "Nach Bergung aus kaltem Wasser sinkt die Kerntemperatur weiter. Welche Aussagen sind angemessen?", [["Ein Afterdrop ist möglich", true], ["Kälte aus der Peripherie kann bei der Temperaturumverteilung eine Rolle spielen", true], ["Schonende, möglichst waagerechte Rettung ist bei schwerer Hypothermie sinnvoll", true], ["Jeder Temperaturabfall beweist eine fehlerhafte Messung", false], ["Kräftige Bewegung der Extremitäten ist immer die erste Gegenmaßnahme", false]], "Afterdrop und rescue collapse machen ein vorsichtiges Vorgehen bei tiefer Hypothermie wichtig."),
  q(8, "Welche Aussagen zur kältebedingten Gerinnungsstörung sind richtig?", [["Traumatische Blutung kann durch Unterkühlung verschärft werden", true], ["Gerinnungsenzyme und Thrombozytenfunktion können beeinträchtigt sein", true], ["Äußere Blutungen bleiben im cABCDE vorrangig zu versorgen", true], ["Kälte verbessert zuverlässig die Hämostase beim Schwerverletzten", false], ["Eine normale Hautfarbe schließt die Koagulopathie sicher aus", false]], "Kälte und Blutung können sich gegenseitig verstärken; Blutungskontrolle und Wärmeerhalt gehören zusammen."),
  q(9, "Welche Befunde können eine fortgeschrittene Hypothermie stützen, ohne sie allein zu beweisen?", [["Vigilanzabnahme", true], ["Bradykardie", true], ["Verlangsamte Atmung", true], ["Normale einmalige Pulsoxymetrie als Ausschlusskriterium", false], ["Fehlendes Zittern als sicherer Beweis für Normothermie", false]], "Bewusstsein, Atmung und Kreislauf verändern sich, sind aber durch andere Erkrankungen beeinflussbar."),
  q(10, "Eine bewusstlose, stark unterkühlte Person zeigt kaum erkennbare Lebenszeichen. Welche Schritte sind richtig?", [["Atmung und Puls bis zu einer Minute prüfen", true], ["Ein niedrig messendes Kerntemperaturverfahren anstreben", true], ["EKG-Monitoring und wiederholte Gesamtbeurteilung einsetzen", true], ["Nach fünf Sekunden ohne tastbaren Radialpuls sicheren Stillstand annehmen", false], ["Eine kalte Haut schließt Restkreislauf aus", false]], "Bei tiefer Hypothermie können Atmung und Puls extrem schwach sein; ERC empfiehlt bis zu eine Minute Prüfung."),
  q(11, "Welche Aussagen zur Kerntemperaturmessung bei Unterkühlung treffen zu?", [["Ein gewöhnliches Thermometer kann unterhalb seines Messbereichs versagen", true], ["Bei spontaner Atmung kann eine geeignete tympanale Messung genutzt werden", true], ["Bei gesichertem Atemweg ist eine ösophageale Messung möglich", true], ["Axilläre Hauttemperatur ist stets identisch mit Kerntemperatur", false], ["Die EKG-Frequenz ersetzt eine Kerntemperaturmessung exakt", false]], "Niedrig messende Kerntemperaturverfahren sind nötig; Messort und Atemwegssituation beeinflussen die Wahl."),
  q(12, "Welche Aussagen zu den revidierten Schweizer Hypothermiestadien sind korrekt?", [["Stadium I: wach", true], ["Stadium II: Bewusstsein beeinträchtigt", true], ["Stadium III: bewusstlos mit Lebenszeichen", true], ["Stadium IV verlangt zwingend eine Kerntemperatur unter 24 °C", false], ["Intoxikation kann die klinische Einstufung nicht verfälschen", false]], "Klinische Stadien orientieren sich vor allem an Bewusstsein und Lebenszeichen; Temperaturbereiche überlappen."),
  q(13, "Ein Patient ist bewusstlos, aber atmet und hat tastbaren Puls. Kerntemperatur 27 °C. Welche Bewertungen passen?", [["Das Bild ist mit Stadium III vereinbar", true], ["Atemweg und Atmung sind wiederholt zu beurteilen", true], ["Kreislaufstillstand darf nicht allein aus der Temperatur abgeleitet werden", true], ["Der Patient ist definitionsgemäß im Stadium IV", false], ["Ein spontaner Puls schließt ein erhöhtes Arrest-Risiko aus", false]], "Stadium III bedeutet Bewusstlosigkeit bei vorhandenen Lebenszeichen; tiefe Temperatur bleibt hochriskant."),
  q(14, "Welche Befunde kennzeichnen nach ERC 2025 ein hohes Risiko für hypothermen Kreislaufstillstand?", [["Herzfrequenz unter 45/min", true], ["Systolischer Blutdruck unter 90 mmHg", true], ["Ventrikuläre Arrhythmie", true], ["Kerntemperatur unter 30 °C", true], ["Kerntemperatur über 35 °C als alleiniges Kriterium", false], ["Normale Hautdurchblutung als Hochrisikokriterium", false]], "Zusätzlich gilt eine Kerntemperatur unter 30 °C als Hochrisikomerkmal; ECLS-Zentrum früh kontaktieren."),
  q(15, "Welche Entscheidungen passen bei 29 °C, systolisch 82 mmHg und ventrikulären Extrasystolen?", [["Hohes Arrest-Risiko erkennen", true], ["Notarzt und ECLS-fähige Zielstruktur früh abstimmen", true], ["Schonende Bewegung und Monitoring priorisieren", true], ["Wegen vorhandenen Pulses auf weitere Überwachung verzichten", false], ["Zielklinik allein nach der kürzesten Fahrtstrecke auswählen", false]], "Mehrere Hochrisikokriterien liegen vor; die Zielklinikentscheidung ist eine frühe Team- und Zentrumsentscheidung."),
  q(16, "Welche Vorgehensweisen passen zur Bergung einer schwer unterkühlten Person?", [["Unnötiges Aufrichten vermeiden", true], ["Weitere Auskühlung während der Rettung begrenzen", true], ["Vorsichtig und möglichst waagerecht bewegen", true], ["Traumabedingte Immobilisation richtet sich nach Verletzungsverdacht", true], ["Ausnahmslos alle Unterkühlten ohne Befund vollständig immobilisieren", false], ["Kräftiges Durchbewegen zur Kreislaufaktivierung als Routine", false]], "Schonende waagerechte Bergung vermindert Belastung; Trauma-Immobilisation richtet sich nach Verletzungsverdacht."),
  q(17, "Was ist beim Umgang mit durchnässter Kleidung und Umgebung richtig?", [["Wind- und Bodenkontakt vermindern", true], ["Nasse Kleidung geschützt vor weiterer Auskühlung entfernen oder trocken einhüllen", true], ["Wärmeschutz während Monitoring und Transport fortsetzen", true], ["Entkleiden im kalten Wind ist unabhängig vom Zustand immer besser", false], ["Eine Isolierung unter dem Patienten ist unnötig", false]], "Entkleiden darf keinen zusätzlichen Wärmeverlust erzeugen; trockene Isolierung ist auch unter dem Körper wichtig."),
  q(18, "Welche Differenzialdiagnosen beziehungsweise Begleitursachen sind bei Verwirrtheit in Kälte relevant?", [["Hypoglykämie", true], ["Intoxikation", true], ["SHT oder Schlaganfall", true], ["Sepsis", true], ["Kälteexposition beweist eine ausschließlich thermische Ursache", false], ["Normale Temperatur der Hände schließt Sepsis aus", false]], "Hypothermie kann Folge oder Begleitbefund anderer akuter Erkrankungen sein."),
  q(19, "Eine hypotherme Person hat einen gesicherten Kreislaufstillstand. Welche Aussagen entsprechen ERC 2025?", [["Kontinuierliche CPR ist grundsätzlich anzustreben", true], ["ECLS-Eignung und Transport früh abstimmen", true], ["Bei unter 28 °C und unmöglicher sofortiger/durchgehender CPR kann eine Ausnahme erwogen werden", true], ["Mechanische CPR kann bei schwierigem Transport hilfreich sein", true], ["Bei jedem Transport sind routinemäßig feste CPR-Pausen vorgesehen", false], ["Unterkühlung macht Reanimation grundsätzlich aussichtslos", false]], "Intermittierende oder verzögerte CPR ist eine eng begrenzte Ausnahme, kein Standard-Transportmodus."),
  q(20, "Bei VF und 26 °C bleiben drei Defibrillationsversuche ohne Erfolg. Welche Aussagen sind richtig?", [["Weitere Schocks werden bis über 30 °C zurückgestellt", true], ["CPR und Wiedererwärmung werden fortgeführt", true], ["ECLS-Zentrum ist früh zu berücksichtigen", true], ["Alle zwei Minuten sind beliebig viele weitere Schocks ohne Temperaturschwelle vorgeschrieben", false], ["Nach dem dritten Schock wird die Reanimation beendet", false]], "Bei refraktärem VF/pVT maximal drei Schocks bis zur Erwärmung über 30 °C; Wiedererwärmung und CPR gehen weiter."),
  q(21, "Welche Aussagen zur Adrenalingabe bei hypothermem Kreislaufstillstand entsprechen ERC 2025?", [["Unter 30 °C kann Adrenalin bis zur Erwärmung zurückgestellt werden", true], ["Falls ECPR nicht zeitnah erreichbar ist, kann eine einmalige 1-mg-Gabe erwogen werden", true], ["Zwischen 30 und 35 °C werden die üblichen Gabeintervalle verdoppelt", true], ["Unter 30 °C gilt immer das normale 3–5-Minuten-Intervall", false], ["Ab 35 °C bleibt eine Adrenalingabe grundsätzlich verboten", false]], "ERC 2025 differenziert nach Temperatur und ECPR-Erreichbarkeit; keine wiederholten Standardgaben unter 30 °C."),
  q(22, "Bei 32 °C läuft die Reanimation. Welche Aussagen sind nach ERC 2025 angemessen?", [["Adrenalinintervalle sind gegenüber dem Standard verdoppelt", true], ["Die Wirkung der Erwärmung auf den Rhythmus ist zu berücksichtigen", true], ["Adrenalin wird im Abstand von 60 Sekunden gegeben", false], ["Die modifizierten Regeln gelten bis 40 °C unverändert", false]], "Zwischen 30 und 35 °C verlängerte Intervalle, ab 35 °C Standardalgorithmus."),
  q(23, "Welche Aussagen sind zur Prognose und Entscheidung bei hypothermem Stillstand richtig?", [["Hypothermie vor Hypoxie kann neuroprotektiv sein", true], ["Asphyxie vor Auskühlung verschlechtert die Ausgangslage", true], ["Schweres Trauma muss getrennt beurteilt werden", true], ["Ein einzelner niedriger Temperaturwert beweist günstige Prognose", false], ["Die Unfallumstände sind für die Zielklinik irrelevant", false]], "Die Reihenfolge von Auskühlung und Sauerstoffmangel sowie Begleittrauma sind prognostisch wesentlich."),
  q(24, "Welche Aussagen zur präklinischen Übergabe einer Unterkühlung sind wichtig?", [["Expositionsart und vermutete Dauer mitteilen", true], ["Kerntemperatur mit Messort und Verlauf nennen", true], ["Bewusstseins-, EKG- und Kreislaufverlauf berichten", true], ["Vorherige Asphyxie oder Trauma dürfen wegen der Kälte ausgelassen werden", false], ["Wärmeschutzmaßnahmen haben keinen Einfluss auf die Übergabe", false]], "Zeitverlauf, Messmethode, Begleitursachen und Reanimations-/Erwärmungsmaßnahmen sind entscheidungsrelevant."),
  q(25, "Eine stark unterkühlte Person mit Kälteexposition hat BZ 34 mg/dl und reduzierte Vigilanz. Welche Überlegungen passen?", [["Hypoglykämie ist eine behandelbare konkurrierende Ursache", true], ["Die Temperatur erklärt die Vigilanz nicht automatisch allein", true], ["BZ-Korrektur und Wärmeschutz sind parallel zu planen", true], ["Die Unterkühlung verbietet eine BZ-Messung", false], ["Die Hypoglykämie kann die Selbstrettung behindert haben", true], ["Erst nach vollständiger Erwärmung darf Hypoglykämie behandelt werden", false]], "cABCDE, BZ und Wärmeschutz laufen parallel; nicht an einer einzigen Erklärung festhalten."),
  q(26, "Welche Maßnahmen sind bei schwerer Hypothermie ohne Kreislaufstillstand sinnvoll?", [["EKG- und Vitalmonitoring", true], ["Schonende, wärmegeschützte Lagerung", true], ["Frühzeitige Abstimmung über ECLS-Ziel bei Instabilität", true], ["Routinehafte Defibrillation allein wegen Bradykardie", false], ["Transportverzögerung bis zur präklinischen Normothermie", false]], "Stabilisierung, Wärmeerhalt und geeignete Zielklinikplanung dürfen sich nicht gegenseitig verzögern."),
];

export const unterkuehlungFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "unterkuehlung-card-01", area: "Definition", question: "Definieren Sie akzidentelle Unterkühlung und unterscheiden Sie rasche von allmählicher Auskühlung.", answer: "Unbeabsichtigte Körperkerntemperatur unter 35 °C. Rasch etwa beim Eintauchen in kaltes Wasser; allmählich beim langen Liegen oder ungeschützter Exposition, oft mit Intoxikation oder Krankheit." },
  { id: "unterkuehlung-card-02", area: "Haut", question: "Welche Rolle spielen Epidermis, Dermis und Subkutis bei der Kälteexposition?", answer: "Epidermis: gefäßlose Barriere. Dermis: Gefäße, Rezeptoren und Drüsen, Hautdurchblutung beeinflusst Wärmeverlust. Subkutis: Fettgewebe als Isolation und Energiespeicher." },
  { id: "unterkuehlung-card-03", area: "Regulation", question: "Erklären Sie Vasokonstriktion und Muskelzittern einschließlich ihrer Grenzen.", answer: "Periphere Vasokonstriktion reduziert Wärmeabgabe; Zittern erzeugt Wärme, benötigt aber Sauerstoff und Energie. Bei fortschreitender Auskühlung/Erschöpfung können Schutzreaktionen nachlassen." },
  { id: "unterkuehlung-card-04", area: "Afterdrop", question: "Was bedeuten Afterdrop und rescue collapse für die Bergung?", answer: "Nach der Bergung/Wiedererwärmung kann die Kerntemperatur weiter fallen; schwere Hypothermie kann bei Rettung mit Kreislaufkollaps einhergehen. Vorsichtig, möglichst waagerecht bewegen und weitere Auskühlung vermeiden." },
  { id: "unterkuehlung-card-05", area: "Stadien", question: "Ordnen Sie die revidierten Schweizer Stadien I bis IV ein und nennen Sie eine wichtige Einschränkung.", answer: "I wach, II beeinträchtigtes Bewusstsein, III bewusstlos mit Lebenszeichen, IV keine Lebenszeichen. Temperaturbereiche überlappen; Trauma, Intoxikation oder Hypoglykämie können Bewusstsein unabhängig von der Hypothermie verändern." },
  { id: "unterkuehlung-card-06", area: "Messung", question: "Wie prüfen Sie Lebenszeichen und Temperatur bei einer bewusstlosen, schwer unterkühlten Person?", answer: "Atmung und Puls bis zu einer Minute prüfen, EKG einsetzen. Niedrig messende Kerntemperatur anstreben; tympanal bei Spontanatmung, ösophageal bei gesichertem Atemweg. Standardthermometer/Hauttemperatur reichen oft nicht." },
  { id: "unterkuehlung-card-07", area: "Risiko", question: "Welche vier ERC-2025-Merkmale kennzeichnen ein erhöhtes Risiko für Kreislaufstillstand?", answer: "Herzfrequenz unter 45/min, systolischer Blutdruck unter 90 mmHg, ventrikuläre Arrhythmie oder Kerntemperatur unter 30 °C. Früh ECLS-Zentrum einbeziehen." },
  { id: "unterkuehlung-card-08", area: "Erstmaßnahmen", question: "Skizzieren Sie die ersten präklinischen Schritte bei einem nassen, bewusstseinsgetrübten Patienten im Freien.", answer: "Eigenschutz und schonende Rettung, cABCDE und Blutungskontrolle, vor Wind/Boden/Nässe schützen, niedrig messende Kerntemperatur/EKG/BZ/Vitalverlauf, differenzialdiagnostisch Trauma, Hypoglykämie und Intoxikation prüfen; Notarzt/Zielklinik nach Risiko." },
  { id: "unterkuehlung-card-09", area: "Reanimation", question: "Wann ist intermittierende oder verzögerte CPR nach ERC 2025 überhaupt erwägenswert?", answer: "Nur als Ausnahme bei Kerntemperatur unter 28 °C, wenn CPR nicht sofort begonnen oder nicht durchgehend sicher durchgeführt werden kann, etwa wegen Gefahr oder Gelände. Kontinuierliche CPR ist der Regelfall." },
  { id: "unterkuehlung-card-10", area: "Defibrillation", question: "Wie gehen Sie bei refraktärem VF/pVT und 26 °C Kerntemperatur mit Schocks um?", answer: "Bis zu drei Schocks; bleiben diese erfolglos, weitere Defibrillation bis über 30 °C zurückstellen. CPR und Wiedererwärmung fortführen und ECLS-Zentrum früh abstimmen." },
  { id: "unterkuehlung-card-11", area: "Adrenalin", question: "Erklären Sie die ERC-2025-Regeln für Adrenalin unter 30 °C, zwischen 30 und 35 °C sowie ab 35 °C.", answer: "Unter 30 °C kann bis zur Erwärmung pausiert werden; wenn ECPR nicht zeitnah möglich ist, kann einmal 1 mg i.v. erwogen werden. Bei 30–35 °C Intervall verdoppeln (ca. 6–10 Minuten); ab 35 °C Standardalgorithmus." },
  { id: "unterkuehlung-card-12", area: "Differenzialdiagnose", question: "Warum dürfen Sie die Vigilanzminderung bei Kälteexposition nicht allein der Temperatur zuschreiben?", answer: "Hypoglykämie, Intoxikation, SHT, Schlaganfall, Sepsis und andere Schockursachen können gleichzeitig bestehen oder die Exposition ausgelöst haben. BZ, cABCDE und Ereignisanamnese gezielt einbeziehen." },
  { id: "unterkuehlung-card-13", area: "Gerinnung", question: "Welche Wechselwirkung besteht zwischen Trauma, Blutung und Unterkühlung?", answer: "Kälte beeinträchtigt Gerinnung/Thrombozytenfunktion, wodurch Blutung zunehmen kann; Schock und Exposition fördern weitere Auskühlung. Blutungskontrolle und Wärmeerhalt sind parallele Prioritäten." },
  { id: "unterkuehlung-card-14", area: "Übergabe", question: "Welche Angaben beeinflussen ECLS-Triage und Prognose besonders?", answer: "Expositions- und Ereignisablauf, mögliche Asphyxie vor Auskühlung, Trauma, Kerntemperatur mit Messmethode/Verlauf, Lebenszeichen und EKG, Reanimationsdauer, Wärme- und Bergungsmaßnahmen sowie Kreislaufrisiko." },
];
