import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; children: ReactNode };

export default function VenenthromboseLesson({ Figure, children }: Props) {
  const section = (number: string, kicker: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>{kicker}</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;

  return <article className="lesson-article angina-pectoris-lesson venenthrombose-lesson">
    <div className="lesson-intro"><p className="lead">Einseitige Schwellung, Schmerz und venöse Risikofaktoren begründen den Verdacht – beweisen die Thrombose aber nicht. Präklinisch stehen gefährliche Verläufe, schonender Transport und die strukturierte Übergabe im Mittelpunkt.</p></div>

    {section("01", "Begriff und Abgrenzung", "Definition", <><p>Bei einer Venenthrombose entsteht innerhalb einer Vene ein Blutgerinnsel, das den venösen Rückstrom teilweise oder vollständig behindert. Klinisch besonders relevant ist die tiefe Venenthrombose der Extremitäten. Eine oberflächliche Venenthrombose betrifft dagegen oberflächennahe Venen und zeigt sich häufig als schmerzhafter, geröteter Venenstrang.</p><aside className="knowledge-note"><b>Prüfungspräzision</b><p>„Thrombose“ bezeichnet die lokale Gerinnselbildung. Erst wenn sich Material ablöst und mit dem Blutstrom verschleppt wird, entsteht eine Embolie.</p></aside></>)}

    {section("02", "Gefäßwand und Rückstrom", "Anatomie und Physiologie", <><Figure src="/lessons/venenthrombose/vene-arterie-beschriftet.png" alt="Beschrifteter Vergleich von Vene und Arterie mit Gefäßwandschichten und Venenklappen" caption="Vene und Arterie · beschrifteter Gefäßwandvergleich" wide /><div className="pulmo-compare"><div><small>Arterie</small><h3>Druck- und Widerstandsgefäß</h3><p>Blutfluss vom Herzen weg. Kräftige Tunica media, relativ kleineres und formstabiles Lumen; Arteriolen steuern den peripheren Widerstand.</p></div><div><small>Vene</small><h3>Kapazitäts- und Rückstromgefäß</h3><p>Blutfluss zum Herzen hin. Dünnere Media, größeres kollabierbares Lumen; Venen speichern einen großen Anteil des Blutvolumens.</p></div></div><div className="pulmo-anatomy-grid"><div><small>Innen</small><b>Tunica intima</b><p>Endotheliale Oberfläche. Venenklappen sind taschenförmige Duplikaturen der Intima und lenken den Strom herzwärts.</p></div><div><small>Mitte</small><b>Tunica media</b><p>Glatte Muskulatur und elastische Fasern. In Arterien deutlich kräftiger als in Venen.</p></div><div><small>Außen</small><b>Tunica adventitia</b><p>Bindegewebige Verankerung; bei großen Gefäßen Versorgung durch Vasa vasorum.</p></div></div><h3>Venensystem der Extremität</h3><div className="pulmo-care-grid"><div><span>T</span><b>Tiefe Venen</b><small>Subfaszial; führen den Hauptanteil des Blutes aus Muskulatur und Extremität zum Herzen zurück.</small></div><div><span>O</span><b>Oberflächliche Venen</b><small>Epifaszial im Unterhautgewebe; bilden ein oberflächliches Venennetz.</small></div><div><span>P</span><b>Perforansvenen</b><small>Verbinden oberflächliche mit tiefen Venen; intakte Klappen lenken den Fluss in die Tiefe.</small></div><div><span>↥</span><b>Rückstromhilfen</b><small>Muskelpumpe, Gelenkpumpe, Atemdruckschwankungen und Venenklappen arbeiten zusammen.</small></div></div><p>Ausnahmen von der einfachen Sauerstoffregel: Pulmonalarterien führen sauerstoffarmes Blut vom rechten Herzen zur Lunge, Pulmonalvenen sauerstoffreiches Blut zum linken Vorhof. Arterie und Vene werden deshalb nach Flussrichtung, nicht nach Sauerstoffgehalt definiert.</p></>)}

    {section("03", "Virchow-Trias", "Ursachen und Pathophysiologie", <><Figure src="/lessons/venenthrombose/virchow-trias.jpg" alt="Virchow-Trias mit verlangsamtem Blutfluss, erhöhter Gerinnungsneigung und Gefäßwandschaden" caption="Virchow-Trias · drei Wege zur Thrombusbildung" wide /><div className="pulmo-path"><span>Stase</span><i>＋</i><span>Endothelschaden</span><i>＋</i><span>Hyperkoagulabilität</span><i>→</i><span>Thrombus</span></div><div className="pulmo-risk-grid"><div><b>Stase</b><p>Immobilisation, lange Reise, Herzinsuffizienz, Lähmung oder venöse Abflussbehinderung.</p></div><div><b>Endothelschaden</b><p>Operation, Trauma, Entzündung, liegender Katheter oder vorausgegangene Thrombose.</p></div><div><b>Hyperkoagulabilität</b><p>Tumorerkrankung, Schwangerschaft/Wochenbett, Östrogene, angeborene Thrombophilie oder Exsikkose.</p></div></div><p>Der arterielle Einstrom bleibt zunächst erhalten, während der venöse Abfluss behindert ist. Dadurch steigen venöser und kapillärer Druck: Flüssigkeit tritt ins Interstitium, die Extremität schwillt an und spannt.</p></>)}

    {section("04", "Arbeitsdiagnose stützen", "Symptome und Befunde", <><div className="pulmo-symptoms"><span>Einseitige Umfangszunahme</span><span>Schwellung und Spannungsgefühl</span><span>Schmerz oder Druckempfindlichkeit</span><span>Überwärmung</span><span>Rötlich-livide Verfärbung</span><span>Prallere oberflächliche Venen</span></div><p>Die Zeichen sind unspezifisch und können einzeln fehlen. Erhaltene arterielle Pulse passen zur venösen Abflussstörung; sie schließen eine tiefe Venenthrombose nicht aus.</p><aside className="diagnostic-boundary"><span>!</span><div><b>Keine schmerzhaften Provokationstests erzwingen</b><p>Homan-, Payr- oder Meyer-Zeichen besitzen keine ausreichende diagnostische Sicherheit. Eine Thrombose wird nicht durch kräftiges Drücken oder forcierte Fußbewegung bewiesen oder ausgeschlossen.</p></div></aside></>)}

    {section("05", "Zeitkritische Verläufe", "Komplikationen und Gefahren", <><div className="pulmo-risk-grid"><div><b>Lungenarterienembolie</b><p>Gelöstes Thrombusmaterial gelangt über Hohlvenen, rechtes Herz und Pulmonalarterie in die Lungenstrombahn. Plötzliche Dyspnoe, Thoraxschmerz, Synkope oder Schock verändern sofort die Priorität.</p></div><div><b>Postthrombotisches Syndrom</b><p>Klappenschaden und chronische venöse Hypertension führen zu Ödemen, Hautveränderungen und Ulzera.</p></div><div><b>Phlegmasia</b><p>Massive venöse Abflussblockade mit extremer Schwellung, Zyanose, starkem Schmerz und bedrohter Extremität.</p></div></div><aside className="knowledge-note"><b>Embolieweg exakt erklären</b><p>Eine gewöhnliche tiefe Venenthrombose verursacht typischerweise eine Lungenembolie. Eine arterielle Embolie, etwa im Gehirn, setzt einen Rechts-links-Übertritt wie einen relevanten kardialen Shunt voraus.</p></aside></>)}

    {section("06", "Vorbereitet zum Patienten", "Einsatzmaterialien", <div className="material-chips">{["Notfallrucksack", "Monitoring / 12-Kanal-EKG", "Blutdruck und SpO₂", "i.v.-Material", "Sauerstoff / Beatmung", "Absaugung", "Trage oder Tragestuhl", "Material für Reanimationsbereitschaft"].map(item => <span key={item}>{item}</span>)}</div>)}

    {section("07", "cABCDE und SAMPLERS", "Erstmaßnahmen und Diagnostik", <><div className="pulmo-care-grid"><div><span>01</span><b>cABCDE</b><small>Dyspnoe, Schock, Synkope oder Thoraxschmerz als mögliche Emboliezeichen sofort priorisieren.</small></div><div><span>02</span><b>Schonung</b><small>Betroffene Extremität ruhig und bequem lagern; nicht massieren oder belastend „testen“.</small></div><div><span>03</span><b>Vergleich</b><small>Seite, Umfang, Farbe, Temperatur, Schmerz, Pulse und pDMS dokumentieren.</small></div><div><span>04</span><b>Transport</b><small>Schonend transportieren, Verlauf überwachen und Zielklinik strukturiert voranmelden.</small></div></div><h3>SAMPLERS · fokussiert</h3><div className="samplers-grid">{[["S · Symptome", "Beginn, Verlauf, Dyspnoe, Thoraxschmerz"], ["A · Allergien", "Arzneimittel und Kontrastmittel"], ["M · Medikamente", "Antikoagulation, Hormone, Tumortherapie"], ["P · Vorgeschichte", "Thrombose, Embolie, Tumor, Herzinsuffizienz"], ["L · Letzte Aufnahme", "Nahrung und Flüssigkeit"], ["E · Ereignis", "OP, Trauma, Reise, Immobilisation"], ["R · Risiken", "Schwangerschaft, Wochenbett, Thrombophilie"], ["S · Schwangerschaft", "Woche und Wochenbett"]].map(([label, text]) => <p key={label}><b>{label}</b>{text}</p>)}</div><p>Präklinische Befunde begründen eine Verdachtsdiagnose. Die Bestätigung erfolgt klinisch vor allem durch Kompressionssonografie in Verbindung mit einer strukturierten klinischen Wahrscheinlichkeitsbeurteilung.</p></>)}

    {section("08", "Nicht verwechseln", "Differenzialdiagnosen und Entscheidungen", <><div className="differential-grid">{["Akuter arterieller Verschluss", "Erysipel / Zellulitis", "Rupturierte Baker-Zyste", "Muskel- oder Sehnenverletzung", "Lymphödem", "Chronisch-venöse Insuffizienz", "Rechtsherzinsuffizienz", "Kompartmentsyndrom"].map(item => <span key={item}>{item}</span>)}</div><div className="pulmo-compare"><div><small>Venöse Abflussstörung</small><h3>Eher warm und geschwollen</h3><p>Stauung, Umfangszunahme und Spannungsgefühl; arterielle Pulse meist erhalten.</p></div><div><small>Akuter arterieller Verschluss</small><h3>Eher kalt und minderperfundiert</h3><p>Plötzlicher Schmerz, Blässe, Pulslosigkeit, Sensibilitäts- und Motorikstörung sind Warnzeichen.</p></div></div></>)}

    {section("09", "Diagnose sichern, Risiken beherrschen", "Weitere Maßnahmen", <><div className="pulmo-vfa-flow"><div><span>↔</span><b>Verlauf kontrollieren</b><small>Vitalparameter, Beschwerden, Beinumfang und Zeichen einer Lungenembolie erneut beurteilen.</small></div><div><span>US</span><b>Kompressionssonografie</b><small>Die klinische Diagnostik prüft die Komprimierbarkeit der betroffenen tiefen Venen im Seitenvergleich.</small></div><div><span>Rx</span><b>Klinische Therapie</b><small>Antikoagulation, Kompression und in ausgewählten schweren Fällen interventionelle oder operative Verfahren.</small></div><div><span>→</span><b>Übergabe</b><small>Zeitverlauf, Seite, Risikofaktoren, Antikoagulation und Emboliezeichen vollständig übermitteln.</small></div></div><aside className="red-flags"><span>!</span><div><small>Präklinische Grenze</small><h3>Keine eigenständige Gerinnungstherapie auf bloßen Verdacht</h3><p>Eine unbestätigte Venenthrombose führt nicht pauschal zur präklinischen Antikoagulation oder Lyse. Bei Zeichen einer Lungenarterienembolie gilt die Versorgung des dann führenden Notfallbildes.</p></div></aside></>)}

    {section("10", "Mündliche Prüfung", "Entscheidungsübersicht", <><div className="pulmo-path"><span>Verdacht</span><i>→</i><span>cABCDE</span><i>→</i><span>Emboliezeichen?</span><i>→</i><span>Schonender Transport</span><i>→</i><span>Diagnosesicherung</span></div><p>Eine starke Prüfungsantwort verbindet die Virchow-Trias mit dem erhöhten venösen Druck, grenzt die warme geschwollene Extremität vom akuten arteriellen Verschluss ab und erklärt den Embolieweg anatomisch korrekt.</p></>)}

    {children}
    <p className="lesson-source">Hauptgrundlage: bereitgestellte Unterlagen „7. Venenthrombose“. Ergänzende Einordnung dient der rettungsdienstlichen Entscheidungsfindung; Diagnosesicherung und definitive Therapie erfolgen klinisch.</p>
  </article>;
}
