import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [text: string, correct: boolean];
function q(number: number, prompt: string, options: Option[], source: string, difficulty: 1 | 2 | 3 = 3): ThoraxtraumaChoiceQuestion {
  const shift = (number * 2) % options.length;
  return { id: `venenthrombose-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty };
}

export const venenthromboseFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "venenthrombose-card-01", area: "Definition", question: "Definieren Sie Venenthrombose, Thrombus und Embolie trennscharf.", answer: "Die Venenthrombose ist die intravasale Gerinnselbildung in einer Vene mit teilweiser oder vollständiger Abflussbehinderung. Der Thrombus liegt am Entstehungsort; erst abgelöstes, verschlepptes Material heißt Embolus und kann eine Embolie verursachen." },
  { id: "venenthrombose-card-02", area: "Gefäßwand", question: "Nennen Sie die drei Gefäßwandschichten und den wichtigsten Unterschied zwischen Arterie und Vene.", answer: "Tunica intima, media und adventitia. Arterien besitzen für das Hochdrucksystem eine kräftigere Media und ein formstabileres Lumen; Venen haben dünnere Wände, ein größeres kollabierbares Lumen und dienen als Kapazitätsgefäße." },
  { id: "venenthrombose-card-03", area: "Venenklappen", question: "Aus welcher Schicht entstehen Venenklappen und wie unterstützen sie den Rückstrom?", answer: "Venenklappen sind taschenförmige Duplikaturen der Tunica intima. Sie verhindern den Rückfluss und wandeln die intermittierende Muskel- und Gelenkpumpe in einen gerichteten Strom zum Herzen um." },
  { id: "venenthrombose-card-04", area: "Venensystem", question: "Grenzen Sie tiefe, oberflächliche und perforierende Venen voneinander ab.", answer: "Tiefe Venen liegen subfaszial und führen den Hauptstrom. Oberflächliche Venen liegen epifaszial im Unterhautgewebe. Perforansvenen verbinden beide Systeme; intakte Klappen lenken Blut von oberflächlich nach tief." },
  { id: "venenthrombose-card-05", area: "Rückstrom", question: "Welche Mechanismen fördern den venösen Rückstrom aus den Beinen?", answer: "Muskel- und Gelenkpumpe komprimieren Venen, Venenklappen verhindern Rückfluss, Inspiration senkt den intrathorakalen Druck, und Venentonus sowie benachbarte arterielle Pulsationen unterstützen den Rücktransport." },
  { id: "venenthrombose-card-06", area: "Virchow-Trias", question: "Erklären Sie die Virchow-Trias mit je zwei Beispielen.", answer: "Stase: Immobilisation, Herzinsuffizienz. Endothelschaden: Operation, Trauma. Hyperkoagulabilität: Tumor, Schwangerschaft/Östrogene oder angeborene Thrombophilie. Mehrere Faktoren können gleichzeitig wirken." },
  { id: "venenthrombose-card-07", area: "Pathophysiologie", question: "Warum schwillt die Extremität trotz weiterbestehendem arteriellem Einstrom an?", answer: "Der venöse Abfluss ist behindert, der arterielle Einstrom zunächst erhalten. Venöser und kapillärer Druck steigen, Flüssigkeit filtriert ins Interstitium und verursacht Ödem, Umfangszunahme und Spannungsgefühl." },
  { id: "venenthrombose-card-08", area: "Arbeitsdiagnose", question: "Welche Befundkonstellation stützt eine tiefe Venenthrombose, ohne sie zu beweisen?", answer: "Einseitige Schwellung, Umfangszunahme, Schmerz oder Druckempfindlichkeit, Überwärmung, rötlich-livide Verfärbung und prallere Venen bei passendem Risikoprofil. Einzelzeichen sind unspezifisch." },
  { id: "venenthrombose-card-09", area: "Prüfungsfalle", question: "Warum eignen sich Homan-, Payr- und Meyer-Zeichen nicht zum sicheren Ausschluss?", answer: "Sie besitzen unzureichende Sensitivität und Spezifität. Schmerzprovokation beweist oder widerlegt die Thrombose nicht; entscheidend sind Gesamtkonstellation und klinische Diagnosesicherung." },
  { id: "venenthrombose-card-10", area: "Komplikation", question: "Beschreiben Sie den anatomischen Embolieweg einer tiefen Beinvenenthrombose.", answer: "Tiefe Bein-/Beckenvene → Vena cava inferior → rechter Vorhof → rechter Ventrikel → Truncus pulmonalis/Pulmonalarterien. Dort kann der Embolus eine Lungenarterienembolie auslösen." },
  { id: "venenthrombose-card-11", area: "Abgrenzung", question: "Vergleichen Sie tiefe Venenthrombose und akuten arteriellen Extremitätenverschluss.", answer: "TVT eher warm, geschwollen und gespannt mit meist erhaltenen Pulsen. Arterieller Verschluss eher plötzlich schmerzhaft, blass/kalt, pulslos und mit Sensibilitäts- oder Motorikstörung. Mischbilder und Ausnahmen erfordern cABCDE und pDMS." },
  { id: "venenthrombose-card-12", area: "Gefahr", question: "Was kennzeichnet eine Phlegmasia cerulea dolens?", answer: "Eine massive venöse Abflussblockade mit extremer Schwellung, Zyanose, starkem Schmerz und möglicher arterieller Minderperfusion. Sie bedroht Extremität und Kreislauf und ist zeitkritisch." },
  { id: "venenthrombose-card-13", area: "Diagnostik", question: "Wie wird die tiefe Venenthrombose klinisch gesichert?", answer: "Durch strukturierte klinische Wahrscheinlichkeitsbeurteilung und Kompressionssonografie; je nach Wahrscheinlichkeit ergänzt ein D-Dimer-Test den klinischen Algorithmus. Präklinische Einzelbefunde sichern die Diagnose nicht." },
  { id: "venenthrombose-card-14", area: "Präklinik", question: "Welche Maßnahmen sind bei isoliertem TVT-Verdacht sinnvoll?", answer: "cABCDE, fokussierte SAMPLERS-Anamnese, Seitenvergleich und pDMS, ruhige bequeme Lagerung, kein Massieren oder belastendes Testen, schonender Transport, Verlaufskontrolle und strukturierte Klinikübergabe." },
  { id: "venenthrombose-card-15", area: "Entscheidung", question: "Welche Veränderung macht aus dem Beinbefund einen möglichen unmittelbar vitalen Notfall?", answer: "Neu auftretende Dyspnoe, Thoraxschmerz, Synkope, Hypoxämie, Tachykardie, Hypotonie oder Schock sprechen für eine mögliche Lungenarterienembolie und erfordern sofortige Prioritätsanpassung." },
];

export const venenthromboseQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Welche Aussagen unterscheiden Arterien und Venen anatomisch korrekt?", [["Arterien besitzen im Regelfall eine kräftigere Tunica media", true], ["Venen besitzen meist ein größeres, leichter kollabierbares Lumen", true], ["Venenklappen sind Duplikaturen der Tunica intima", true], ["Jede Vene enthält unabhängig von ihrer Lage Klappen", false], ["Arterien werden allein durch den Sauerstoffgehalt des Blutes definiert", false]], "Gefäße werden nach Flussrichtung definiert; Wandbau und Klappenausstattung entsprechen ihrer hämodynamischen Aufgabe.", 1),
  q(2, "Welche Funktionen passen zum venösen System?", [["Kapazitätsspeicher für einen großen Anteil des Blutvolumens", true], ["Rücktransport des Blutes zum Herzen", true], ["Zusammenarbeit von Klappen und Muskelpumpe", true], ["Erzeugung des systolischen Auswurfdrucks", false], ["Primäre Regulation des peripheren Widerstands durch Arteriolen", false]], "Venen speichern Blut und führen es unter niedrigem Druck zum Herzen zurück.", 1),
  q(3, "Welche Aussagen zu Lungengefäßen zeigen die korrekte Gefäßdefinition?", [["Pulmonalarterien führen Blut vom rechten Herzen zur Lunge", true], ["Pulmonalvenen führen Blut von der Lunge zum linken Vorhof", true], ["Die Benennung richtet sich nach der Flussrichtung zum oder vom Herzen", true], ["Pulmonalvenen sind Arterien, weil sie sauerstoffreiches Blut führen", false], ["Pulmonalarterien führen physiologisch sauerstoffreiches Blut", false]], "Arterie bedeutet vom Herzen weg, Vene zum Herzen hin; der Sauerstoffgehalt ist nicht das Definitionsmerkmal.", 1),
  q(4, "Welche Zuordnungen zum Venensystem der Extremität sind korrekt?", [["Tiefe Venen verlaufen subfaszial", true], ["Oberflächliche Venen liegen epifaszial", true], ["Perforansvenen verbinden oberflächliches und tiefes System", true], ["Der Hauptstrom des Beines verläuft ausschließlich oberflächlich", false], ["Intakte Perforansklappen lenken den Fluss regelhaft von tief nach oberflächlich", false]], "Tiefe Venen führen den Hauptstrom; Perforansvenen leiten bei intakten Klappen von oberflächlich nach tief.", 2),
  q(5, "Welche Mechanismen fördern den venösen Rückstrom aus dem Bein?", [["Kompression der Venen durch die Skelettmuskulatur", true], ["Gerichtete Ventilfunktion intakter Venenklappen", true], ["Inspiratorische Druckänderungen zwischen Abdomen und Thorax", true], ["Dauerhafte vollständige Erschlaffung aller Venenwände", false], ["Ausschließliche Wirkung der Schwerkraft im Stehen", false]], "Muskel-/Gelenkpumpe, Klappen, Atmung und Venentonus unterstützen den Rückstrom.", 2),
  q(6, "Welche Faktoren gehören zur Virchow-Trias?", [["Verlangsamter Blutfluss", true], ["Schädigung des Endothels", true], ["Erhöhte Gerinnungsneigung", true], ["Isolierte arterielle Hyperoxie", false], ["Physiologische Fibrinolyse ohne Risikofaktor", false]], "Stase, Endothelschaden und Hyperkoagulabilität bilden die Virchow-Trias.", 1),
  q(7, "Welche Konstellationen fördern vor allem eine venöse Stase?", [["Längere Immobilisation nach Operation", true], ["Ausgeprägte Herzinsuffizienz", true], ["Langstreckenreise mit wenig Bewegung", true], ["Regelmäßige Aktivierung der Wadenmuskelpumpe", false], ["Intakte Venenklappen bei normaler Mobilität", false]], "Bewegungsmangel und reduzierte Kreislauffunktion verlangsamen den venösen Fluss.", 2),
  q(8, "Welche Situationen fördern überwiegend Endothelschaden oder Hyperkoagulabilität?", [["Größere Operation oder direktes Gefäßtrauma", true], ["Aktive Tumorerkrankung", true], ["Schwangerschaft beziehungsweise Wochenbett", true], ["Unbelastete Mobilität ohne weitere Risikofaktoren", false], ["Physiologische Hämodilution als alleiniger Schutzfaktor", false]], "Operation/Trauma schädigen das Endothel; Tumor und Schwangerschaft erhöhen unter anderem die Gerinnungsbereitschaft.", 2),
  q(9, "Welche Schritte erklären die einseitige Schwellung bei tiefer Venenthrombose?", [["Der venöse Abfluss ist behindert", true], ["Der venöse und kapilläre Druck steigt", true], ["Flüssigkeit tritt vermehrt ins Interstitium", true], ["Der arterielle Einstrom endet zwingend sofort vollständig", false], ["Das Ödem entsteht ausschließlich durch verminderte Lymphproduktion", false]], "Fortbestehender Einstrom bei behindertem Abfluss erhöht den hydrostatischen Druck und fördert das Ödem.", 2),
  q(10, "Welche Befunde stützen eine tiefe Venenthrombose, ohne sie zu beweisen?", [["Einseitige Umfangszunahme und Spannungsgefühl", true], ["Überwärmung und rötlich-livide Verfärbung", true], ["Druckschmerz bei passendem Risikoprofil", true], ["Erhaltene Fußpulse schließen die Diagnose sicher aus", false], ["Fehlende Rötung widerlegt jede tiefe Thrombose", false]], "Die typische Konstellation bleibt unspezifisch; einzelne fehlende oder vorhandene Zeichen sind nicht beweisend.", 2),
  q(11, "Welche Aussagen zu klassischen klinischen Provokationszeichen sind richtig?", [["Ihre Sensitivität und Spezifität reichen für eine sichere Diagnose nicht aus", true], ["Ein negatives Zeichen schließt eine Thrombose nicht aus", true], ["Kräftige Schmerzprovokation ist präklinisch entbehrlich", true], ["Ein positives Homan-Zeichen beweist eine proximale TVT", false], ["Mehrere negative Zeichen ersetzen die Kompressionssonografie", false]], "Provokationszeichen dürfen nicht überbewertet werden und ersetzen keine strukturierte Diagnostik.", 3),
  q(12, "Welche Stationen durchläuft ein Embolus aus einer tiefen Beinvene typischerweise?", [["Vena cava inferior", true], ["Rechter Vorhof und rechter Ventrikel", true], ["Pulmonalarterie", true], ["Linker Ventrikel vor dem rechten Vorhof", false], ["Arteria cerebri media ohne Rechts-links-Shunt", false]], "Der typische venöse Embolieweg endet in der pulmonalen Strombahn.", 2),
  q(13, "Welche Befunde bei vermuteter TVT lassen zusätzlich an eine Lungenarterienembolie denken?", [["Plötzlich einsetzende Dyspnoe", true], ["Thoraxschmerz oder Synkope", true], ["Hypoxämie, Hypotonie oder Schock", true], ["Isolierte seit Jahren unveränderte Varikosis", false], ["Ein normal tastbarer Fußpuls als Emboliebeweis", false]], "Neue respiratorische oder hämodynamische Zeichen machen die mögliche Lungenembolie zum führenden Notfallbild.", 2),
  q(14, "Welche Folgen können nach tiefer Venenthrombose auftreten?", [["Lungenarterienembolie", true], ["Postthrombotisches Syndrom", true], ["Phlegmasia mit bedrohter Extremität", true], ["Zwingend ein ischämischer Schlaganfall ohne Shunt", false], ["Dauerhafte Verbesserung der Venenklappenfunktion", false]], "Akut drohen Embolie und massive Abflussblockade, langfristig eine chronische venöse Hypertension.", 2),
  q(15, "Welche Befunde passen eher zum akuten arteriellen Extremitätenverschluss als zur isolierten TVT?", [["Kalte, blasse Extremität", true], ["Fehlende periphere Pulse", true], ["Neue Sensibilitäts- oder Motorikstörung", true], ["Warme einseitige Schwellung bei erhaltenen Pulsen", false], ["Prallere oberflächliche Venen als einziges Zeichen", false]], "Pulslosigkeit, Kälte, Blässe und neurologische Defizite sprechen für arterielle Minderperfusion.", 3),
  q(16, "Welche Maßnahmen sind bei isoliertem TVT-Verdacht präklinisch sinnvoll?", [["cABCDE und wiederholte Kontrolle auf Emboliezeichen", true], ["Schonende Lagerung und Transportplanung", true], ["Risikofaktoren und bestehende Antikoagulation erfragen", true], ["Kräftige Massage der betroffenen Extremität", false], ["Belastungstest bis zur Schmerzverstärkung", false]], "Strukturierte Beurteilung, Schonung, Anamnese und Transport sind angemessen; Manipulation und Belastungsprovokation nicht.", 2),
  q(17, "Welche Angaben gehören in eine hochwertige Übergabe bei TVT-Verdacht?", [["Exakter Beginn und Verlauf der Beschwerden", true], ["Seitenvergleich, Umfang, Hautbefund, Pulse und pDMS", true], ["Operation, Immobilisation, Tumor, Hormone und frühere Thrombosen", true], ["Nur die Diagnosebezeichnung ohne Befunde", false], ["Das Weglassen neu aufgetretener Dyspnoe bei normaler SpO₂", false]], "Zeitverlauf, Befunde, Risikoprofil und mögliche Emboliezeichen steuern die klinische Diagnostik.", 2),
  q(18, "Welche Aussagen zur klinischen Diagnosesicherung treffen zu?", [["Die Kompressionssonografie beurteilt die Komprimierbarkeit tiefer Venen", true], ["Eine klinische Wahrscheinlichkeitsbeurteilung steuert den weiteren Algorithmus", true], ["D-Dimere können abhängig von der Vortestwahrscheinlichkeit einbezogen werden", true], ["Ein einzelnes präklinisches Schmerzzeichen sichert die Diagnose", false], ["Eine normale Pulsoxymetrie schließt die TVT aus", false]], "Diagnosesicherung kombiniert Wahrscheinlichkeit und geeignete klinische Tests; Pulsoxymetrie diagnostiziert keine TVT.", 3),
  q(19, "Welche Aussagen zur präklinischen Gerinnungstherapie sind angemessen?", [["Eine unbestätigte TVT führt nicht pauschal zur eigenständigen Heparingabe", true], ["Eine Lyse ist keine Routinebehandlung des isolierten TVT-Verdachts", true], ["Bei Lungenemboliezeichen wird der entsprechende Notfallpfad priorisiert", true], ["Jede einseitige Schwellung verlangt sofortige präklinische Thrombolyse", false], ["Antikoagulation ist unabhängig von Blutung und Differenzialdiagnosen risikofrei", false]], "Therapieentscheidungen benötigen bestätigte Indikation, Kontraindikationsprüfung und den passenden Behandlungsweg.", 3),
  q(20, "Welche Aussagen zur oberflächlichen und tiefen Venenthrombose sind richtig?", [["Eine oberflächliche Thrombose kann als druckschmerzhafter geröteter Strang imponieren", true], ["Die tiefe Venenthrombose ist besonders wegen der Emboliegefahr relevant", true], ["Die Ausdehnung und Nähe zum tiefen System beeinflussen die klinische Bedeutung", true], ["Jede oberflächliche Venenthrombose ist grundsätzlich bedeutungslos", false], ["Beide Formen lassen sich sicher allein durch Hautfarbe unterscheiden", false]], "Lokalisation und Ausdehnung bestimmen Risiko und Diagnostik; klinische Zeichen allein genügen nicht.", 3),
  q(21, "Eine Patientin hat nach Operation ein warmes, geschwollenes Bein und neue Atemnot. Welche Entscheidungen sind richtig?", [["Eine TVT mit Lungenarterienembolie ist eine plausible Verbindung", true], ["cABCDE und hämodynamische Beurteilung haben Vorrang vor Detailtests am Bein", true], ["Monitoring, schonender Transport und frühe Voranmeldung sind begründet", true], ["Die Atemnot wird wegen der Beinschwellung zunächst ignoriert", false], ["Kräftige Wadenkompression ist zur Diagnosesicherung erforderlich", false]], "Respiratorische und hämodynamische Gefährdung bestimmt die Priorität; der Beinbefund liefert den möglichen Ursprung.", 3),
  q(22, "Welche Konstellation passt am ehesten zu einer Phlegmasia cerulea dolens?", [["Massive Schwellung mit livid-zyanotischer Verfärbung", true], ["Starker Schmerz und gespannte Extremität", true], ["Mögliche Beeinträchtigung auch der arteriellen Perfusion", true], ["Kleine seit Jahren unveränderte Besenreiser ohne Beschwerden", false], ["Isolierte lokale Rötung an einer oberflächlichen Kanüle ohne Schwellung", false]], "Die Phlegmasia ist eine massive venöse Abflussblockade und bedroht Extremität und Kreislauf.", 3),
  q(23, "Welche Aussagen erklären das postthrombotische Syndrom?", [["Thrombus und Entzündung können Venenklappen schädigen", true], ["Chronischer Reflux erhöht den venösen Druck", true], ["Ödeme, Hautveränderungen und Ulzera können folgen", true], ["Es entsteht durch dauerhaft verbesserte Klappenschlussfähigkeit", false], ["Es ist eine ausschließlich arterielle Spätfolge", false]], "Klappeninsuffizienz nach TVT führt zu chronischer venöser Hypertension und Gewebeschäden.", 3),
  q(24, "Welche zusammenhängende Prüfungsantwort ist fachlich korrekt?", [["Stase, Endothelschaden und Hyperkoagulabilität erklären die Thrombusentstehung", true], ["Behinderter Abfluss bei fortbestehendem Einstrom erklärt Ödem und Spannungsgefühl", true], ["Der typische Embolieweg führt über rechtes Herz in die Pulmonalarterien", true], ["Erhaltene Pulse widerlegen die venöse Abflussstörung", false], ["Ein negatives Homan-Zeichen beendet die weitere Abklärung", false]], "Die vollständige Herleitung verbindet Ursache, lokale Hämodynamik, klinische Zeichen und Emboliegefahr.", 3),
];
