import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [string, boolean];
function q(number: number, prompt: string, options: Option[], source: string): ThoraxtraumaChoiceQuestion {
  const shift = number % options.length;
  return { id: `verbrennung-q-${String(number).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty: 3 };
}

export const verbrennungQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Nach einer Verbrühung ist die Haut gerötet und blasig. Welche Aussagen tragen zur fachlichen Einordnung bei?", [["Feuchte Hitze ist der auslösende Mechanismus", true], ["Blasenbildung spricht gegen eine isolierte Verbrennung I°", true], ["Der Schmerz allein legt die betroffene Körperoberfläche fest", false], ["Temperatur und Einwirkzeit beeinflussen die Gewebetiefe", true], ["Chemische Verätzungen werden automatisch mit derselben VFA vollständig erfasst", false]], "Verbrühung beruht auf feuchter Hitze; Grad, Fläche und Mechanismus sind getrennte Größen."),
  q(2, "Welche Funktionen der Haut erklären die Gefährdung nach ausgedehnter Verbrennung?", [["Die Barriere begrenzt Wasserverlust und Keimeintritt", true], ["Durchblutung und Schweißbildung tragen zur Temperaturregulation bei", true], ["Die Epidermis enthält die größten Hautgefäße", false], ["Sensorische Endigungen melden Schmerz und Temperatur", true], ["Subkutanes Fett verhindert jeden Wärmeverlust", false]], "Barriere, Thermoregulation und Sensorik gehen bei großflächiger Schädigung teilweise verloren."),
  q(3, "Eine tiefe Verbrennung wirkt zentral schmerzarm, die Umgebung ist hochschmerzhaft. Welche Deutungen sind richtig?", [["Zentral können Nervenendigungen zerstört sein", true], ["Randzonen können eine andere Verbrennungstiefe haben", true], ["Schmerzarmut beweist geringe Verletzungstiefe", false], ["Die gesamte Fläche darf nicht anhand eines Punkts klassifiziert werden", true], ["Ein III°-Zentrum ist stets feucht-rosig und berührungsempfindlich", false]], "Tiefe Areale verlieren Sensibilität; gemischte Tiefen sind möglich."),
  q(4, "Welcher Mechanismus führt bei schwerer Verbrennung zum Volumenmangel?", [["Kapillarpermeabilität steigt und Flüssigkeit tritt ins Interstitium", true], ["Die geschädigte Hautbarriere erhöht Verluste", true], ["Entzündungsmediatoren fördern die systemische Reaktion", true], ["Die Gefäße werden durch die verbrannte Epidermis neu gebildet", false], ["Ein normales erstes RR schließt spätere Verschlechterung aus", false]], "Kapillarleck und Barriereverlust können intravasales Volumen vermindern; Verlaufskontrolle bleibt nötig."),
  q(5, "Ein Erwachsener hat beide Arme und den vorderen Rumpf verbrannt. Welche Schätzungen nach der Neunerregel stimmen?", [["Beide Arme zusammen entsprechen 18 % KOF", true], ["Der vordere Rumpf entspricht 18 % KOF", true], ["Die Summe beträgt näherungsweise 36 % KOF", true], ["Ein einzelner Arm entspricht 18 % KOF", false], ["Die Anteile gelten unverändert für ein Kleinkind", false]], "Erwachsene: je Arm 9 %, Rumpf vorn 18 %. Kinderproportionen weichen ab."),
  q(6, "Bei kleinen verstreuten Arealen wird die Körperoberfläche abgeschätzt. Welche Aussagen sind tragfähig?", [["Die Patientenhandfläche einschließlich Finger dient näherungsweise als 1-%-Vergleich", true], ["Neunerregel und Handflächenmethode sind Schätzverfahren", true], ["Bei Kindern unterscheidet sich die Verteilung von Kopf und Beinen", true], ["Die Handfläche der behandelnden Person ist immer der korrekte Maßstab", false], ["Die Fläche ersetzt die Einschätzung der Verbrennungstiefe", false]], "Fläche und Tiefe separat schätzen; für kleine Areale die Hand des Patienten verwenden."),
  q(7, "Nach Wohnungsbrand bestehen Heiserkeit und Ruß im Mund, die SpO₂ beträgt 99 %. Welche Entscheidungen sind angemessen?", [["Ein Inhalationstrauma bleibt möglich", true], ["Eine CO-Intoxikation wird durch konventionelle SpO₂ nicht ausgeschlossen", true], ["Atemwegsschwellung kann sich im Verlauf verstärken", true], ["Die normale Sättigung erlaubt die Entlassung vor Ort", false], ["Die äußere Hautfläche ist für die Atemwegsentscheidung allein ausschlaggebend", false]], "Ruß und Heiserkeit sind Red Flags; konventionelle Pulsoxymetrie kann CO-Hb nicht sicher unterscheiden."),
  q(8, "Welche Aussagen zum CO-Risiko nach einem Brand passen zum präklinischen Vorgehen?", [["CO entsteht bei unvollständiger Verbrennung", true], ["Eigenschutz und CO-Warner sind am Brandort relevant", true], ["Kopfschmerz und Vigilanzstörung können Hinweise sein", true], ["Ein unauffälliger Pulsoxymeterwert schließt CO aus", false], ["CO ist wegen seines Geruchs zuverlässig erkennbar", false]], "CO ist unsichtbar und geruchlos; Exposition und klinischer Befund führen zur Verdachtsdiagnose."),
  q(9, "Die Thüringer VFA 34 fragt nach Inhalationstrauma. Welche der folgenden Schritte sind dort genannt?", [["Sauerstoffgabe", true], ["Vernebelung von 5 mg Adrenalin", true], ["Prüfung, ob CPAP indiziert ist", true], ["Pauschale Gabe von Furosemid", false], ["Verzicht auf Atemwegsbeurteilung bis zum Transportende", false]], "VFA 34 nennt O₂, 5 mg Adrenalin per Vernebelung und die CPAP-Indikationsprüfung."),
  q(10, "Ein 60-kg-Patient erhält kristalloide Lösung nach VFA 34. Welche Rechnungen und Grenzen stimmen?", [["10 ml/kgKG/h entsprechen maximal 600 ml/h", true], ["In 30 Minuten wären bei dieser Höchstrate rechnerisch 300 ml möglich", true], ["Die Höchstrate ist nicht automatisch die benötigte Rate", true], ["600 ml müssen sofort als Bolus gegeben werden", false], ["Die Parkland-Formel ersetzt die VFA-Höchstgeschwindigkeit", false]], "60 × 10 = 600 ml/h; 600 × 0,5 h = 300 ml. Die VFA formuliert ausdrücklich ein Maximum."),
  q(11, "Eine 80-kg-Patientin wird 45 Minuten präklinisch versorgt. Welche Werte liefert allein die Obergrenze der VFA 34?", [["Maximalrate 800 ml/h", true], ["Rechnerisch 600 ml in 45 Minuten bei durchgehender Höchstrate", true], ["Ein individueller geringerer Bedarf bleibt möglich", true], ["Maximalrate 80 ml/h", false], ["45 Minuten verändern den Faktor auf 10 ml/kgKG je Minute", false]], "80 × 10 = 800 ml/h; 800 × 45/60 = 600 ml. Maximum ist kein Therapieziel."),
  q(12, "Eine 6-jährige Patientin hat eine IIa°-Verbrennung von 6 % KOF. Welche Aussagen passen zur Thüringer VFA 34?", [["Das Kinderkriterium IIa° über 5 % KOF ist erfüllt", true], ["Die Transportorganisation für ein Verbrennungszentrum ist zu prüfen", true], ["Die Erwachsenen-Schwelle von über 20 % ist hierfür nicht maßgeblich", true], ["Erst ab 10 % III° besteht bei Kindern eine Zentrumindikation", false], ["Ein Inhalationstrauma wäre erst ab zusätzlicher großer Hautfläche relevant", false]], "Für Kinder nennt VFA 34 IIa° > 5 % KOF als Zentrumskriterium."),
  q(13, "Ein Kind hat IIb° auf 2 % KOF. Welche Schlussfolgerungen sind zutreffend?", [["Die VFA-34-Kinderschwelle IIb°/III° über 1 % KOF ist überschritten", true], ["Die Tiefe ist neben der Fläche entscheidend", true], ["Ein Zentrumskriterium kann trotz kleiner Fläche bestehen", true], ["Die geringe Fläche schließt ein Zentrum immer aus", false], ["Wärmeerhalt ist nur bei Erwachsenen wichtig", false]], "Bei Kindern gilt IIb° oder III° > 1 % KOF; Wärmeverlust ist besonders relevant."),
  q(14, "Welche erwachsenen Patienten erfüllen unabhängig von der Prozentzahl ein Zentrumskriterium der VFA 34?", [["Verbrennung an Händen oder Füßen", true], ["Inhalationsschaden", true], ["Elektrische Verletzung", true], ["Isolierte kleine I°-Rötung des Unterarms ohne Besonderheit", false], ["Jede 2-%-IIa°-Fläche an unkritischer Rumpfstelle", false]], "VFA 34 nennt kritische Lokalisationen, Inhalations- und elektrische Verletzung separat."),
  q(15, "Ein 63-jähriger Erwachsener hat eine thermische Verletzung. Welche VFA-34-Kriterien sind unabhängig vom Flächenwert zu prüfen?", [["Alter über 60 Jahre", true], ["Vorerkrankungen", true], ["Mechanische Begleitverletzungen", true], ["Nur die Handflächenmethode, nicht Lokalisation und Mechanismus", false], ["Die Entscheidung ausschließlich nach dem Schmerzwert", false]], "Alter > 60, Vorerkrankung und mechanische Begleitverletzung sind zusätzliche Zentrumskriterien."),
  q(16, "Nach einer Explosion zeigen sich Verbrühung und Verdacht auf Thoraxtrauma. Welche Priorisierung entspricht VFA 34?", [["cABCDE und lebensbedrohliche Begleitverletzung zuerst", true], ["Trauma-Leitalgorithmus bei entsprechender Begleitverletzung", true], ["Verbrennungsfläche und Tiefe anschließend erfassen", true], ["Wundgröße zuerst exakt vermessen, bevor die Atmung geprüft wird", false], ["Der Brandmechanismus schließt mechanische Verletzungen aus", false]], "Vitalbedrohliche Begleitverletzungen werden nach cABCDE und Traumaalgorithmus priorisiert."),
  q(17, "Welche Aussagen zur lokalen Erstversorgung gemäß Thüringer VFA 34 sind richtig?", [["Wärmeerhalt ist ausdrücklich genannt", true], ["Die VFA 34 fordert ausdrücklich: keine Kühlung", true], ["Wundversorgung gehört dazu", true], ["Großflächige Kühlung hat Vorrang vor Wärmeerhalt", false], ["Blasen werden präklinisch routinemäßig eröffnet", false]], "Die Original-VFA nennt Wärmeerhalt, keine Kühlung und Wundversorgung."),
  q(18, "Eine Brandverletzte ist wach, entwickelt aber zunehmenden Stridor. Welche Aussagen sind angemessen?", [["Atemwegsödem ist zeitkritisch zu berücksichtigen", true], ["Atemweg und Atmung wiederholt beurteilen", true], ["Frühe Notarzt-/Atemwegshilfe und Transportplanung sind sinnvoll", true], ["Abwarten bis zum vollständigen Verschluss ist sicherer", false], ["Nur die Infusionsrate entscheidet über die Atemwegssicherung", false]], "Ein Inhalationstrauma kann progredient anschwellen; Atemwegssicherung und Transport werden früh geplant."),
  q(19, "Welche Befunde können bei einem Brandpatienten parallel bestehen und müssen getrennt bewertet werden?", [["Thermische Hautverletzung", true], ["Toxische Rauchgasexposition", true], ["Mechanische Verletzung durch Explosion oder Sturz", true], ["Normale SpO₂ als Beweis gegen CO", false], ["Nur die sichtbar tiefste Stelle als Maß für alle Areale", false]], "Haut, Atemwege, Toxine und Begleittrauma sind eigenständige Prüfpfade."),
  q(20, "Ein Erwachsener hat 22 % KOF Grad II, ist zunächst kreislaufstabil. Welche Aussagen passen zur VFA 34?", [["Die Flächenschwelle für ein Verbrennungszentrum ist überschritten", true], ["Transportorganisation kann früh eingeleitet werden", true], ["Monitoring und Re-Evaluation bleiben erforderlich", true], ["Kreislaufstabilität hebt das Zentrumskriterium auf", false], ["Die maximale Infusionsrate muss ohne Prüfung ausgeschöpft werden", false]], "Bei Erwachsenen nennt VFA 34 mehr als 20 % KOF Grad II; Stabilität ersetzt die Verlaufsbeurteilung nicht."),
  q(21, "Welche Maßnahmen sind bei chemischer Exposition zusätzlich zum allgemeinen Verbrennungsbefund nötig?", [["Eigenschutz und Stoffidentifikation", true], ["Dekontamination nach Stoff und Lage", true], ["Atemwegs- und Kreislaufbeurteilung", true], ["Blindes Neutralisieren jeder Säure mit einer Lauge", false], ["Gleichsetzung jedes chemischen Traumas mit einer reinen Verbrühung", false]], "Chemische Verletzung erfordert stoffbezogene Dekontamination und Gefahrenbeurteilung."),
  q(22, "Welche Angaben gehören zur strukturierten Übergabe einer Schwerbrandverletzten?", [["Mechanismus und Expositionsdauer", true], ["Grad, Fläche und kritische Lokalisationen", true], ["Atemwegsbefund, Rauchgasverdacht und Vitaltrend", true], ["Nur die nach 10 Minuten errechnete Infusionsmenge", false], ["Zentrumskriterien erst in der Zielklinik besprechen", false]], "VFA-Entscheidungen und Verlauf hängen von Mechanismus, Ausmaß, Atemweg und Kreislauf ab."),
];

export const verbrennungFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "verbrennung-card-01", area: "Definition", question: "Grenzen Sie Verbrennung, Verbrühung und chemische Verletzung nach Energieeintrag ab.", answer: "Verbrennung: thermische Schädigung durch trockene Hitze; Verbrühung: feuchte Hitze durch Flüssigkeit oder Dampf. Chemische Verletzungen erfordern zusätzlich stoffbezogene Gefahren- und Dekontaminationsbeurteilung." },
  { id: "verbrennung-card-02", area: "Haut", question: "Erklären Sie Aufbau und Versorgungsprinzip von Epidermis, Dermis und Subkutis.", answer: "Epidermis: gefäßlose Schutzschicht, Diffusion aus Tiefe. Dermis: gefäß- und nervenreich, Bindegewebe sowie Drüsen/Follikel. Subkutis: lockeres Fett- und Bindegewebe mit größeren Gefäßen; Isolation und Polster." },
  { id: "verbrennung-card-03", area: "Pathophysiologie", question: "Leiten Sie vom Hitzeschaden bis zum Verbrennungsschock die wesentlichen Schritte ab.", answer: "Proteindenaturierung und Zellschaden → Barriereverlust und Mediatorfreisetzung → Kapillarleck und Flüssigkeitsverschiebung ins Gewebe → intravasaler Volumenmangel, Ödem, Kreislaufbelastung und mögliches Schockbild." },
  { id: "verbrennung-card-04", area: "Tiefe", question: "Woran unterscheiden Sie IIa°, IIb°, III° und IV° und weshalb kann tiefer Schaden schmerzarm sein?", answer: "IIa: feucht-rosig, Blasen, stark schmerzhaft. IIb: tiefer, eher blass/trocken und weniger sensibel. III: vollständige Hautzerstörung, lederartig; Nervenendigungen zentral zerstört. IV: tiefere Strukturen. Randzonen können anders aussehen und schmerzen." },
  { id: "verbrennung-card-05", area: "Fläche", question: "Berechnen Sie nach der Neunerregel beide Arme und den vorderen Rumpf beim Erwachsenen; nennen Sie die Grenze bei Kindern.", answer: "Je Arm 9 %, Rumpf vorn 18 %, zusammen etwa 36 % KOF. Bei Kindern sind Kopf- und Beinanteile anders; Kinderschema nutzen. Patientenhand einschließlich Finger entspricht näherungsweise 1 %." },
  { id: "verbrennung-card-06", area: "Inhalation", question: "Welche Hinweise und Verlaufssorgen machen einen Brandpatienten mit 99 % SpO₂ trotzdem kritisch?", answer: "Brandraum, Ruß in Mund/Nase, Heiserkeit oder Stridor deuten auf Inhalationstrauma; Atemwegsödem kann progredient sein. Eine normale Standard-SpO₂ schließt CO-Hb nicht aus. Atemweg, Vigilanz und Kreislauf wiederholt prüfen." },
  { id: "verbrennung-card-07", area: "CO", question: "Weshalb ist ein CO-Warner für das Team wichtig und weshalb reicht die konventionelle Pulsoxymetrie nicht?", answer: "CO kann bei unvollständiger Verbrennung unsichtbar und geruchlos entstehen. Der CO-Warner dient dem Eigenschutz. Standard-Pulsoxymeter unterscheiden CO-Hb nicht sicher von Oxyhämoglobin." },
  { id: "verbrennung-card-08", area: "VFA 34", question: "Welche zusätzlichen Schritte nennt die Thüringer VFA 34 bei Inhalationstrauma?", answer: "Sauerstoffgabe, Vernebelung von 5 mg Adrenalin und Prüfung einer CPAP-Indikation; dabei Atemweg und respiratorischen Verlauf eng überwachen und frühzeitig Hilfe/Transport organisieren." },
  { id: "verbrennung-card-09", area: "VFA 34", question: "Wie lautet die präklinische Infusionsgrenze und was bedeutet das Wort ‚maximal‘? Rechnen Sie für 75 kg.", answer: "Kristalloide maximal 10 ml/kgKG/h; 75 kg → höchstens 750 ml/h. Das ist eine Obergrenze, keine automatisch zu infundierende Zielrate. Klinischer Verlauf und Begleitverletzungen bleiben entscheidend." },
  { id: "verbrennung-card-10", area: "Zentrum", question: "Nennen Sie die Erwachsenen-Schwellen und drei flächenunabhängige Zentrumskriterien.", answer: "Erwachsene: >20 % KOF Grad II oder >10 % KOF Grad III. Unabhängig davon zum Beispiel Gesicht/Hals, Hände/Füße, Inhalationsschaden, elektrische Verletzung, Begleittrauma, Vorerkrankung oder Alter >60 Jahre." },
  { id: "verbrennung-card-11", area: "Pädiatrie", question: "Welche engeren Zentrumskriterien nennt VFA 34 für Kinder?", answer: "Alter <1 Jahr; IIa° >5 % KOF; IIb°/III° >1 % KOF; außerdem Inhalationstrauma sowie chemische oder elektrische Verletzungen. Wärmeerhalt besonders beachten." },
  { id: "verbrennung-card-12", area: "Entscheidung", question: "Priorisieren Sie die Versorgung bei Verbrennung mit Explosionsmechanismus, Stridor und Hypotonie.", answer: "Eigenschutz, cABCDE, Atemweg und Atmung sofort sichern/beurteilen, lebensbedrohliche Begleitverletzung nach Traumaalgorithmus, O₂ und enges Monitoring. Früh Notarzt und Zentrumstransport organisieren; Wunddetails und Flächenabschätzung erst nach Vitalprioritäten." },
];
