import type { ComponentType, ReactNode } from "react";
import BurnInfusionCalculator from "./verbrennung-infusion-calculator";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = { Figure: ComponentType<FigureProps>; Vfa: ComponentType<FigureProps>; children: ReactNode };

export default function VerbrennungLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, title: string, body: ReactNode) => <details open className="rib-section" key={number}><summary><header className="chapter-heading"><span>{number}</span><div><small>Verbrennung / Verbrühung</small><h2>{title}</h2></div></header><i aria-hidden="true">⌄</i></summary><div className="lesson-prose script-copy">{body}</div></details>;

  return <article className="lesson-article verbrennung-lesson">
    <div className="lesson-intro"><p className="lead">Ausmaß, Tiefe, Atemweg und Begleitverletzungen gemeinsam beurteilen. Wärmeerhalt und die frühzeitige Wahl einer geeigneten Zielklinik sind bei relevanten Verbrennungen entscheidend.</p></div>

    {section("01", "Definition", <><p>Eine Verbrennung ist eine Schädigung der Haut und gegebenenfalls tieferer Gewebe durch thermische Einwirkung. Trockene Hitze entsteht etwa durch Feuer oder heiße Gegenstände; feuchte Hitze durch heiße Flüssigkeiten oder Dampf heißt Verbrühung. Elektrische, chemische und Strahlenschäden müssen nach ihrem jeweiligen Mechanismus zusätzlich beurteilt werden.</p></>)}

    {section("02", "Anatomie und Physiologie", <><div className="pulmo-anatomy-grid"><div><small>Außen</small><b>Epidermis</b><p>Mehrschichtig verhorntes, gefäßloses Epithel. Schutzbarriere; Ernährung durch Diffusion aus tieferen Schichten.</p></div><div><small>Mitte</small><b>Dermis</b><p>Gefäß- und nervenreiches Bindegewebe mit Papillar- und Geflechtschicht; enthält unter anderem Haarfollikel, Talg- und Schweißdrüsen.</p></div><div><small>Innen</small><b>Subkutis</b><p>Lockeres Binde- und Fettgewebe mit größeren Gefäßen und Nerven; Polster, Wärmeisolation und Energiespeicher.</p></div></div><p>Die Haut schützt vor Wärme- und Wasserverlust, Mikroorganismen und mechanischen Reizen. Durchblutung und Schweißabgabe regulieren die Temperatur; Rezeptoren vermitteln Berührung, Druck, Vibration, Temperatur und Schmerz.</p><Figure src="/lessons/unterkuehlung/haut-1.jpg" alt="Beschriftete Hautschichten mit Blutgefäßen, Nerven, Rezeptoren und Unterhautfettgewebe" caption="Hautaufbau mit Gefäßen und Rezeptoren · Anatomieabbildung aus Unterkühlung" wide /><Figure src="/lessons/unterkuehlung/haut-2.jpg" alt="Schematische Darstellung von Epidermis, Dermis und Subkutis" caption="Epidermis, Dermis und Subkutis im Überblick · Anatomieabbildung aus Unterkühlung" wide /></>)}

    {section("03", "Ursachen und Pathophysiologie", <><div className="pulmo-path"><span>Hitze / Energie</span><i>→</i><span>Proteindenaturierung</span><i>→</i><span>Barriereverlust</span><i>→</i><span>Kapillarleck</span><i>→</i><span>Ödem und Volumenverschiebung</span></div><p>Temperatur, Einwirkzeit, Medium und betroffene Fläche bestimmen die Schwere. Die Gewebeschädigung setzt Entzündungsmediatoren frei; Plasma tritt aus geschädigten Kapillaren ins Gewebe. Bei ausgedehnten Verbrennungen drohen intravasaler Volumenmangel, Schock, gestörte Temperaturregulation und eine systemische Entzündungsreaktion.</p><div className="pulmo-compare"><div><small>Lokal</small><h3>Schichttiefe</h3><p>Die Verbrennungstiefe bestimmt Wundgrund, Blasenbildung und Schmerzempfinden.</p></div><div><small>Systemisch</small><h3>Fläche und Verlauf</h3><p>Große betroffene Flächen verstärken Flüssigkeitsverschiebung, Hypothermie und Kreislaufbelastung.</p></div></div></>)}

    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", <><div className="burn-grade-grid"><div><span>I°</span><b>Epidermis</b><p>Rötung und Schmerz, keine Blasen.</p></div><div><span>IIa°</span><b>Oberflächliche Dermis</b><p>Feuchter, rosiger Wundgrund, Blasen; Berührung stark schmerzhaft.</p></div><div><span>IIb°</span><b>Tiefe Dermis</b><p>Eher trockener, blasser/weißer Wundgrund; Sensibilität vermindert.</p></div><div><span>III°</span><b>Vollständige Hautzerstörung</b><p>Weißlich bis grau-schwarz, lederartig; im tief zerstörten Zentrum oft schmerzarm.</p></div><div><span>IV°</span><b>Tiefere Gewebe</b><p>Auch Muskeln, Sehnen oder Knochen betroffen; Verkohlung möglich.</p></div></div><p><b>Wichtig:</b> Fehlender Schmerz im tiefen Zentrum bedeutet keine Entwarnung; angrenzende oberflächlichere Areale können sehr schmerzhaft sein. Tiefe und Fläche können präklinisch nur abgeschätzt werden.</p><aside className="knowledge-note"><b>Körperoberfläche abschätzen</b><p>Erwachsene: Kopf 9 %, jeder Arm 9 %, Rumpf vorn 18 % und hinten 18 %, jedes Bein 18 %, Genitalbereich 1 %. Die Handfläche des Patienten einschließlich Finger entspricht näherungsweise 1 %. Bei Kindern gelten andere Anteile, vor allem für Kopf und Beine.</p></aside><Figure src="/lessons/verbrennung/neunerregel-print14.png" alt="Neunerregel für Erwachsene und Kinder aus Print 14, Seite 5" caption="Neunerregel · Ausschnitt aus Print 14, Seite 5" wide /></>)}

    {section("05", "Komplikationen und Gefahren", <><div className="pulmo-risk-grid"><div><b>Früh</b><p>Atemwegsödem, respiratorische Insuffizienz, Volumenmangel/Schock, Hypothermie und begleitende Traumata.</p></div><div><b>Im Verlauf</b><p>Infektion, Sepsis, Kompartmentsyndrom und Organfunktionsstörungen bei schwerer Verbrennung.</p></div></div><aside className="red-flags"><span>!</span><div><small>Red Flags</small><h3>Inhalationstrauma und CO mitdenken</h3><p>Brand in geschlossenem Raum, Ruß an Mund/Nase, Heiserkeit, Stridor, Husten oder zunehmende Atemarbeit machen einen gefährdeten Atemweg wahrscheinlich. Die Schwellung kann sich verzögert verstärken. Kohlenmonoxid entsteht bei unvollständiger Verbrennung; Kopfschmerz, Schwindel oder Vigilanzstörung können Hinweise sein. Eine normale konventionelle SpO₂ schließt eine CO-Intoxikation nicht aus.</p></div></aside><p>Kinder kühlen wegen ihrer relativ großen Körperoberfläche und dünneren Haut schneller aus. Bei Chemikalienkontakt zählen Eigenschutz, Stoffidentifikation und Dekontamination; die thermische Verbrennungs-VFA allein deckt diesen Mechanismus nicht ab.</p></>)}

    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", <div className="material-chips">{["Persönliche Schutzausrüstung / CO-Warner", "Notfallrucksack", "EKG / RR / SpO₂", "O₂ und Beatmungsgerät", "Absaugung", "i.v.-Material / Kristalloide", "Sterile Wundauflagen", "Wärmeerhalt", "Analgesie nach VFA"].map(item => <span key={item}>{item}</span>)}</div>)}

    {section("07", "Erstmaßnahmen und Anamnese", <><div className="pulmo-care-grid"><div><span>01</span><b>Eigenschutz</b><small>Brandort erst nach Freigabe betreten; Feuer, Strom, Chemikalien und CO beachten.</small></div><div><span>02</span><b>cABCDE</b><small>Begleitverletzungen, Atemweg, Atmung und Kreislauf vor Wunddetails beurteilen.</small></div><div><span>03</span><b>Wärmeerhalt</b><small>VFA 34: keine Kühlung; Wunden versorgen und RTW vorwärmen.</small></div><div><span>04</span><b>Ausmaß</b><small>Neunerregel, Grad, Lokalisation und Verlauf dokumentieren.</small></div></div><h3>SAMPLERS · fokussiert</h3><div className="samplers-grid">{[["S · Symptome", "Schmerz, Atemnot, Heiserkeit"], ["A · Allergien", "Relevante Unverträglichkeiten"], ["M · Medikamente", "Vormedikation / Antikoagulation"], ["P · Vorgeschichte", "Herz/Lunge, Risikofaktoren"], ["L · Letzte Aufnahme", "Essen, Trinken"], ["E · Ereignis", "Medium, Dauer, Brandraum"], ["R · Risiken", "Strom, Chemikalien, Trauma"], ["S · Schwangerschaft", "Falls zutreffend"]].map(([label, text]) => <p key={label}><b>{label}</b>{text}</p>)}</div><p>Bei Rauchgasexposition Sauerstoff hochdosiert geben und Atemweg fortlaufend beurteilen; ein CO-Verdacht darf nicht durch eine scheinbar normale Pulsoxymetrie entkräftet werden. Bei Stromunfall auch ein 12-Kanal-EKG ableiten.</p></>)}

    {section("08", "Differenzialdiagnosen und Entscheidung", <><div className="differential-grid">{["Verbrühung", "Chemische Verätzung", "Elektrische Verletzung", "Strahlenschaden", "Erfrierung", "Rauchgas-/CO-Intoxikation", "Inhalationstrauma", "Mechanisches Begleittrauma"].map(item => <span key={item}>{item}</span>)}</div><p>Eine sichtbare Hautverbrennung erklärt nicht automatisch Dyspnoe oder Bewusstseinsstörung: Atemweg, Rauchgasexposition und weitere Verletzungen getrennt beurteilen. Bei schwerem Schmerz führt VFA 34 zum Basisalgorithmus starke Schmerzzustände; bei lebensbedrohlicher Begleitverletzung zum Trauma-Leitalgorithmus.</p></>)}

    {section("09", "Weitere Maßnahmen nach Thüringer VFA", <><div className="pulmo-vfa-flow"><div><span>A/B</span><b>Inhalationstrauma?</b><small>O₂; VFA 34 nennt 5 mg Adrenalin vernebelt und die Prüfung einer CPAP-Indikation. Bei drohendem Atemwegsverlust früh eskalieren.</small></div><div><span>NRS</span><b>Starke Schmerzen?</b><small>Basisalgorithmus VFA 35 und die passende Analgesie-VFA prüfen.</small></div><div><span>i.v.</span><b>Kristalloide</b><small>Höchstens 10 ml/kgKG/h nach VFA 34. Die berechnete Rate ist eine Obergrenze, keine automatische Zielrate.</small></div><div><span>→</span><b>Transport</b><small>Monitoring, frühe Voranmeldung, Kriterien für ein Verbrennungszentrum prüfen.</small></div></div><div className="pulmo-compare"><div><small>Erwachsene · Zentrumskriterien</small><h3>Fläche oder kritische Region</h3><p>&gt;20 % KOF Grad II oder &gt;10 % KOF Grad III; Gesicht/Hals, Hände, Füße, Anogenitalregion und weitere komplizierte Regionen.</p></div><div><small>Kinder · Zentrumskriterien</small><h3>Niedrigere Schwellen</h3><p>Alter &lt;1 Jahr; IIa° &gt;5 % KOF; IIb° oder III° &gt;1 % KOF. Auch Inhalations-, elektrische oder chemische Verletzungen.</p></div></div><p>Weitere Zentrumskriterien der VFA: Inhalationsschaden, mechanische Begleitverletzungen, elektrische Verletzung, relevante Vorerkrankung oder Alter &lt;8 beziehungsweise &gt;60 Jahre. Ein thermisches Trauma mit Zentrumskriterium ist nach Anlage B3B ein Anlass zur Notarztnachforderung.</p></>)}

    {section("10", "VFA Thüringen 2026/2027", <><p>Die Original-VFA ist einklappbar und im Vollbild lesbar. Therapieentscheidungen richten sich nach Indikation, klinischem Verlauf, lokaler Freigabe und der jeweils gültigen Originalfassung.</p><Vfa src="/lessons/verbrennung/vfa-34-print14.png" alt="VFA 34 Verbrennungen aus Print 14, Seite 5, mit Maßnahmen, Zentrumskriterien und maximaler Infusionsrate" caption="VFA 34 · Verbrennungen · Print 14, Seite 5" /><BurnInfusionCalculator /></>)}

    {children}
    <p className="lesson-source">Grundlage und Abbildungen: „Print 14.pdf“. Ergänzende fachliche Grundlage: „36 - Verbrennung/Verbrühung.pdf“. Maßnahmen und Grenzwerte: <a href="https://www.aelrd-thueringen.de/download/verfahrensanweisungen-2026-27/" target="_blank" rel="noreferrer">Thüringer VFA 2026/27, Nr. 34</a>.</p>
  </article>;
}
