import type { ThoraxtraumaChoiceQuestion, ThoraxtraumaFlashcard } from "./thoraxtrauma-data";

type Option = [string, boolean];
function q(n: number, prompt: string, options: Option[], source: string): ThoraxtraumaChoiceQuestion {
  const shift = n % options.length;
  return { id: `vorhofflimmern-q-${String(n).padStart(2, "0")}`, mode: "multiple", prompt, options: [...options.slice(shift), ...options.slice(0, shift)].map(([text, correct]) => ({ text, ...(correct ? { correct: true } : {}) })), source, difficulty: 3 };
}

export const vorhofflimmernQuestions: ThoraxtraumaChoiceQuestion[] = [
  q(1, "Eine 76-Jährige klagt über Palpitationen. Der Puls ist unregelmäßig, RR 132/78 mmHg, sie ist wach und ohne Dyspnoe. Welche Schritte sind angemessen?", [["Ein 12-Kanal-EKG zur Rhythmusbeurteilung ableiten", true], ["Kreislauf und Beschwerden im Verlauf erneut prüfen", true], ["Beginn und bisherige Antikoagulation erfragen", true], ["Allein wegen des unregelmäßigen Pulses sofort synchronisiert kardiovertieren", false], ["Aus einer einzigen stabilen RR-Messung dauerhaft stabile Hämodynamik ableiten", false]], "Der unregelmäßige Puls begründet Verdacht; EKG, Anamnese und Re-Evaluation entscheiden über das weitere Vorgehen."),
  q(2, "Welche Befundkombinationen stützen Vorhofflimmern im 12-Kanal-EKG?", [["R-R-Abstände ohne regelmäßiges Muster", true], ["Keine geordneten P-Wellen vor jedem QRS", true], ["Meist schmale QRS-Komplexe bei normaler Kammerleitung", true], ["Zwingend klar sichtbare f-Wellen in jeder Ableitung", false], ["Konstant gleiche R-R-Abstände als Kernmerkmal", false]], "Absolute Arrhythmie und fehlende geordnete P-Wellen sind zentral; f-Wellen können diskret oder nicht erkennbar sein."),
  q(3, "Ein Patient hat Vorhofflimmern mit 155/min und zunehmender Atemnot. Welche Befunde machen eine hämodynamische Instabilität wahrscheinlich?", [["Neu aufgetretenes Lungenödem", true], ["Myokardischämische Beschwerden", true], ["Synkope im zeitlichen Zusammenhang", true], ["Allein die Zahl 155/min bei sonst unauffälliger Perfusion", false], ["Ein vorhandener Medikamentenplan ohne Symptome", false]], "VFA 20 nennt Synkope, Schock, Herzinsuffizienz und Myokardischämie als Instabilitätskriterien."),
  q(4, "Welche Aufgaben erfüllen Sinusknoten und AV-Knoten beim normalen Rhythmus und beim Vorhofflimmern?", [["Der Sinusknoten initiiert normalerweise die geordnete Vorhoferregung", true], ["Der AV-Knoten verzögert die physiologische Überleitung", true], ["Bei VHF erreicht nur ein unregelmäßiger Teil der Vorhoferregungen die Kammern", true], ["Der AV-Knoten erzeugt beim VHF jede einzelne Vorhof-Flimmerwelle", false], ["Die Purkinje-Fasern filtern primär die Vorhoferregung", false]], "Die geordnete Sinuserregung fehlt; der AV-Knoten begrenzt und variiert die Kammerüberleitung."),
  q(5, "Weshalb kann die Auswurfleistung beim Vorhofflimmern sinken?", [["Die wirksame Vorhofkontraktion als Füllungsbeitrag fällt weg", true], ["Eine hohe Kammerfrequenz verkürzt die Diastole", true], ["Eine bestehende Herzinsuffizienz kann die Minderleistung verstärken", true], ["Der linke Ventrikel erhält grundsätzlich kein Blut mehr aus den Lungenvenen", false], ["Das Herzminutenvolumen sinkt bei allen Patienten zwingend exakt um 20 Prozent", false]], "Der Verlust des atrial kick und eine verkürzte Füllungszeit wirken je nach Herzfunktion unterschiedlich stark."),
  q(6, "Welche Konstellationen können Vorhofflimmern begünstigen oder auslösen?", [["Arterielle Hypertonie und Vorhofbelastung", true], ["Mitralklappenfehler oder Herzinsuffizienz", true], ["Hyperthyreose, Infekt oder Elektrolytstörung", true], ["Allein ein normaler SpO₂-Wert als gesicherter Auslöser", false], ["Vorhofflimmern ausschließlich nach akutem Myokardinfarkt", false]], "Kardiale Struktur-/Druckbelastung und extrakardiale Trigger sind zu unterscheiden."),
  q(7, "Was erklärt das Schlaganfallrisiko bei Vorhofflimmern am besten?", [["Die fehlende effektive Vorhofkontraktion kann Blutstase fördern", true], ["Im linken Herzohr können sich Thromben bilden", true], ["Ein arteriell eingeschwemmter Embolus kann eine Hirnarterie verschließen", true], ["Die absolute Arrhythmie zerstört unmittelbar die Hirngefäßwand", false], ["Ein tastbarer Pulsdefizitwert bestimmt allein das Embolierisiko", false]], "Stase und Thromben im linken Vorhof/Herzohr können kardioembolische Schlaganfälle verursachen."),
  q(8, "Eine Person mit neu dokumentiertem Vorhofflimmern berichtet von unklarer Dauer. Welche Informationen gehören in die Übergabe?", [["Letzter sicher normaler Rhythmus bzw. Beginn der Beschwerden", true], ["Antikoagulans, Einnahmetreue und letzte Dosis", true], ["12-Kanal-EKG und Kreislaufverlauf", true], ["Eine unbelegte Aussage, VHF bestehe sicher erst seit dem Eintreffen des RTW", false], ["Nur die erste gemessene Herzfrequenz ohne Verlauf", false]], "Dauer und Antikoagulation beeinflussen die spätere Rhythmus- und Schlaganfallrisikoentscheidung."),
  q(9, "Eine Patientin mit VHF ist kaltschweißig, systolisch 75 mmHg und zunehmend verwirrt. Was ist richtig?", [["Schockzeichen im Kontext der Tachykardie sind zeitkritisch", true], ["Notarzt und Defibrillator mit Synchro-Funktion früh vorbereiten", true], ["VFA 20 und wiederholte cABCDE-Beurteilung sind relevant", true], ["Zunächst ausschließlich die Verlaufsform paroxysmal oder permanent bestimmen", false], ["Bei vorhandenen QRS-Komplexen einen pulslosen Zustand grundsätzlich ausschließen", false]], "Instabilität bestimmt die Dringlichkeit; Rhythmusname und Verlaufsform sind nachrangig."),
  q(10, "Welche Abgrenzung zwischen Vorhofflimmern und häufigen Differenzialdiagnosen ist korrekt?", [["Sinustachykardie zeigt gewöhnlich geordnete P-Wellen und regelmäßige Überleitung", true], ["Eine AV-knotenabhängige SVT ist meist regelmäßig", true], ["Vorhofflattern kann bei wechselnder AV-Überleitung ebenfalls unregelmäßig sein", true], ["Vorhofflattern ist unabhängig von der Überleitung immer absolut regelmäßig", false], ["Eine ventrikuläre Tachykardie ist definitionsgemäß immer schmal und harmlos", false]], "Rhythmusregelmäßigkeit und Vorhofaktivität helfen, sind aber keine alleinige Diagnosesicherung."),
  q(11, "Welche Aussagen zur Einteilung von Vorhofflimmern stimmen?", [["Paroxysmales VHF kann spontan enden", true], ["Persistierendes VHF endet nicht innerhalb von sieben Tagen spontan bzw. erfordert Intervention", true], ["Permanentes VHF ist als dauerhaft akzeptierter Rhythmus definiert", true], ["Erstdiagnostiziert bedeutet automatisch hämodynamisch instabil", false], ["Permanent bedeutet lediglich, dass eine einzige Kardioversion erfolglos war", false]], "Verlaufsform und aktueller Kreislaufzustand sind getrennte Kategorien."),
  q(12, "Ein unregelmäßig breiter und sehr schneller Rhythmus fällt im Monitor auf. Welche Entscheidungen sind angemessen?", [["Den Rhythmus nicht vorschnell als gewöhnliches schmal-komplexes VHF behandeln", true], ["Eine Präexzitation oder ventrikuläre Ursache mitbedenken", true], ["Sofort 12-Kanal-EKG, Hämodynamik und ärztliche Unterstützung priorisieren", true], ["Schematisch AV-knotenhemmende Mittel geben, bevor die QRS-Form geklärt ist", false], ["Breite QRS-Komplexe machen die weitere Überwachung entbehrlich", false]], "Bei unregelmäßig breiter Tachykardie ist präexzitiertes VHF eine gefährliche Möglichkeit; die Differenzialdiagnose steuert die Therapie."),
  q(13, "Welche Vorgehensweisen entsprechen dem Beginn der Thüringer VFA 20?", [["cABCDE und Leitalgorithmen vor der Rhythmustherapie berücksichtigen", true], ["Möglichen Volumenmangel prüfen", true], ["Instabilitätskriterien einschließlich Schock und Ischämie erheben", true], ["Jedes VHF ohne Beschwerden unmittelbar kardiovertieren", false], ["Die Synchronisation unabhängig vom Gerätemodus voraussetzen", false]], "VFA 20 beginnt mit cABCDE, prüft Volumenmangel und entscheidet anhand der Instabilitätskriterien."),
  q(14, "Welche Reihenfolge nennt VFA 20 für bis zu drei biphasische Kardioversionsversuche?", [["Erster Versuch 120 J synchronisiert", true], ["Zweiter Versuch 150 J", true], ["Dritter Versuch 200 J synchronisiert", true], ["Alle Versuche ohne Kontrolle der Synchronisation auslösen", false], ["Mit 300 J beginnen und bei Misserfolg senken", false]], "Die Original-VFA nennt 120, 150 und 200 J; Synchronisation und gerätespezifische Prüfung sind zentral."),
  q(15, "Nach erfolgter Konversion: Welche unmittelbaren Kontrollen verlangt der VFA-Pfad?", [["Erneute ABCDE-Beurteilung", true], ["Periphere und zentrale Pulse prüfen", true], ["Kontinuierliches Monitoring und Transport fortsetzen", true], ["Den Kreislauf allein aus einer hübschen EKG-Kurve ableiten", false], ["Die Beurteilung beenden, sobald Sinusrhythmus sichtbar ist", false]], "Ein elektrischer Rhythmusnachweis ersetzt weder Puls- noch Perfusionskontrolle."),
  q(16, "Der instabile Rhythmus konvertiert nach den initialen Versuchen nicht. Welche Aussagen zur VFA 20 sind richtig?", [["Die VFA sieht einmalig 300 mg Amiodaron als Kurzinfusion vor", true], ["Anschließend ist bei weiterem Misserfolg eine einmalige Wiederholung mit 200 J vorgesehen", true], ["Zwischen den Schritten bleiben Rhythmus und Kreislauf zu beurteilen", true], ["Amiodaron wird ohne Indikationsprüfung bei jedem stabilen VHF gegeben", false], ["Beliebig viele Wiederholungen mit 120 J sind der vorgesehene Endpfad", false]], "VFA 20 führt nach Misserfolg zu 300 mg Amiodaron als KI und ggf. einer Wiederholung mit 200 J."),
  q(17, "Wie wird Amiodaron für den KI-Schritt nach Anlage B2A vorbereitet?", [["Zwei Ampullen zu je 150 mg/3 ml ergeben 300 mg in 6 ml", true], ["Zu 6 ml Wirkstofflösung kommen 94 ml NaCl 0,9 Prozent", true], ["Die resultierende Konzentration beträgt 3 mg/ml", true], ["Die KI-Zubereitung entspricht der unverdünnten CPR-Konzentration von 50 mg/ml", false], ["300 mg werden mit 6 ml NaCl auf ein Gesamtvolumen von 12 ml gebracht", false]], "B2A: 300 mg (6 ml) plus 94 ml NaCl ergeben 100 ml mit 3 mg/ml; die CPR-Angabe ist ein anderer Pfad."),
  q(18, "Welche Zusammenhänge sprechen bei VHF für eine kardiale Dekompensation?", [["Eine hohe Kammerfrequenz verkürzt die ventrikuläre Füllungszeit", true], ["Der Verlust des Vorhofbeitrags kann bei vorbestehender Dysfunktion besonders relevant sein", true], ["Ein Rückstau bei Linksherzschwäche kann zu Lungenödem führen", true], ["Ein unregelmäßiger Puls beweist eine erhaltene Ejektionsfraktion", false], ["Dyspnoe ist bei VHF unabhängig vom Kreislauf stets psychogen", false]], "Hohe Frequenz, fehlender atrial kick und vorbestehende Herzschwäche können sich gegenseitig verstärken."),
  q(19, "Bei VHF und Thoraxschmerz: Welche Überlegungen gehören zur präklinischen Entscheidung?", [["Myokardischämie ist ein Instabilitätskriterium der VFA 20", true], ["Ein ACS kann gleichzeitig Auslöser oder Folge verstärkter Ischämie sein", true], ["12-Kanal-EKG und Verlauf der Beschwerden sind zu dokumentieren", true], ["Der Rhythmusname allein schließt ein STEMI sicher aus", false], ["Thoraxschmerz darf erst nach einer geplanten Kardioversion beurteilt werden", false]], "VHF erklärt pektanginöse Beschwerden nicht abschließend; ein ACS kann koexistieren."),
  q(20, "Ein Patient mit bekanntem VHF hat Schwindel, bleibt aber normotensiv und klar. Welche Folgerungen sind richtig?", [["Schwindel ernst nehmen und Perfusion wiederholt prüfen", true], ["Eine aktuelle Synkope oder drohender Schock würde die Entscheidung ändern", true], ["Eine bloß bekannte VHF-Diagnose ersetzt kein aktuelles 12-Kanal-EKG", true], ["Normotonie schließt eine spätere Verschlechterung sicher aus", false], ["Eine Notfallkardioversion ist bei jedem Schwindel unabhängig vom Gesamtbefund Pflicht", false]], "Beschwerden und Kreislauf müssen im Kontext beurteilt und im Verlauf kontrolliert werden."),
  q(21, "Welche Aussagen zur Sauerstoffgabe und Lagerung bei symptomatischem VHF sind tragfähig?", [["Atemarbeit und SpO₂ gehören zur cABCDE-Beurteilung", true], ["O₂ wird an Oxygenierung und lokalen Vorgaben ausgerichtet", true], ["Lagerung orientiert sich an Dyspnoe und Kreislaufzustand", true], ["O₂ ist bei jeder normalen Sättigung als feste Hochdosis erforderlich", false], ["Ein sitzender Patient mit Schock muss unabhängig vom Zustand aufrecht bleiben", false]], "Atem- und Kreislaufbefund bestimmen unterstützende Maßnahmen, nicht ein starres Schema."),
  q(22, "Warum ist ein möglicher Pulsdefizit-Befund bei VHF kein Ersatz für die EKG-Analyse?", [["Nicht jede elektrische Kammererregung erzeugt einen peripher tastbaren Puls", true], ["Der Befund kann Hinweise auf eine schwankende Schlagvolumenbildung geben", true], ["Die Rhythmusdiagnose benötigt die elektrische Dokumentation", true], ["Aus dem Pulsdefizit lässt sich die Vorhoffrequenz exakt berechnen", false], ["Ein fehlendes Pulsdefizit schließt VHF sicher aus", false]], "Pulsdefizit ist ein klinischer Zusatzbefund; R-R-Muster und Vorhofaktivität werden im EKG beurteilt."),
  q(23, "Welche Übergabe trennt ein stabiles vom instabilen Vorhofflimmern sinnvoll?", [["EKG-Befund mit QRS-Breite und Kammerfrequenz", true], ["Vitalzeichenverlauf und konkrete Instabilitätszeichen", true], ["Beginn, Medikamente, Antikoagulation und Wirkung von Maßnahmen", true], ["Nur die Bezeichnung ‚Vorhofflimmern‘ ohne Verlauf", false], ["Ausschließlich die höchste einmal gemessene Pulsfrequenz", false]], "Die Therapieentscheidung beruht auf Rhythmus plus klinischem Zustand und Verlauf."),
  q(24, "Welche Aussage zur Antikoagulation bei neu erkanntem VHF ist präklinisch richtig?", [["Eine bestehende Antikoagulation und letzte Einnahme müssen erfragt werden", true], ["Das Embolierisiko ist durch Blutstase im linken Vorhof/Herzohr begründet", true], ["Eine spätere Antikoagulationsentscheidung braucht ärztliche Risikoabwägung", true], ["Ohne weitere Indikation wird präklinisch eigenständig Heparin nur wegen des VHF begonnen", false], ["Ein einzelnes normales 12-Kanal-EKG nach spontaner Konversion schließt früheres VHF aus", false]], "Die präklinische Aufgabe ist Risiko- und Medikationsanamnese sowie Übergabe, nicht eine pauschale Antikoagulation."),
  q(25, "Ein Patient mit VHF verliert plötzlich das Bewusstsein und atmet nicht normal. Welche Prioritäten gelten?", [["Unverzüglich Kreislaufstillstand prüfen und Reanimation beginnen", true], ["Defibrillatorrhythmus nach Reanimationsalgorithmus beurteilen", true], ["Die frühere VHF-Diagnose ist für die aktuelle Schockbarkeit nicht entscheidend", true], ["Bei jedem QRS im Monitor ist eine Pulskontrolle unnötig", false], ["Weiter synchronisiert kardiovertieren, ohne den Kreislaufstillstand zu beachten", false]], "Bei fehlenden Kreislaufzeichen gilt der Reanimationspfad; der vorherige Rhythmusname ist kein Ersatz für die aktuelle Beurteilung."),
  q(26, "Welche Zusammenhänge erklären, weshalb Vorhofflimmern nach einem ersten Trigger anhalten oder wiederkehren kann?", [["Vorhofdehnung und Fibrose können die Erregungsausbreitung ungleichmäßig machen", true], ["Impulse an den Lungenvenen können das Flimmern auslösen", true], ["Kreisende Erregungen können die Vorhöfe wiederholt aktivieren", true], ["Der AV-Knoten erzeugt das strukturelle Remodeling der Vorhöfe", false], ["Jede vorzeitige Vorhoferregung führt unabhängig vom Gewebe dauerhaft zu VHF", false]], "Auslöser und anfälliges Vorhofgewebe wirken zusammen; elektrische und strukturelle Veränderungen können weitere Episoden begünstigen."),
  q(27, "Ein Patient fragt, weshalb beim Vorhofflimmern vor allem das linke Herzohr mit Schlaganfällen verbunden ist. Welche Erklärungen sind richtig?", [["Das linke Herzohr mündet in den linken Vorhof; ein dort entstandener Embolus kann über die Aorta in Hirnarterien gelangen", true], ["Fehlende geordnete Kontraktion begünstigt Blutstase in der trabekulierten Aussackung", true], ["Thromben im rechten Herzohr sind bei VHF seltener und gelangen ohne Kurzschluss zunächst in den Lungenkreislauf", true], ["Ein Thrombus im rechten Herzohr verursacht ohne zusätzliche Verbindung zwischen den Kreisläufen typischerweise einen Hirnarterienverschluss", false], ["Ein normal tastbarer peripherer Puls beweist auch bei VHF eine normale mechanische Entleerung des linken Herzohres", false]], "Beide Herzohren gehören zu den Vorhöfen, aber Blutweg und Häufigkeit der Thrombenbildung unterscheiden sich."),
];

export const vorhofflimmernFlashcards: ThoraxtraumaFlashcard[] = [
  { id: "vorhofflimmern-card-01", area: "Definition", question: "Definieren Sie Vorhofflimmern und erklären Sie den Unterschied zwischen Vorhof- und Kammerfrequenz.", answer: "Unkoordinierte Vorhoferregung mit etwa 350–600/min und unregelmäßiger Überleitung. Der AV-Knoten filtert die vielen Vorhofimpulse, deshalb ist die Kammerfrequenz deutlich niedriger und absolut unregelmäßig." },
  { id: "vorhofflimmern-card-02", area: "Anatomie", question: "Zeichnen Sie den normalen Erregungsweg vom Sinusknoten bis zur Kammermuskulatur und benennen Sie den Schutzmechanismus bei VHF.", answer: "Sinusknoten → Vorhöfe → AV-Knoten → His-Bündel → Tawara-Schenkel → Purkinje-Fasern → Kammermyokard. Der AV-Knoten verzögert/limitiert die Überleitung und verhindert, dass alle Vorhofimpulse die Kammern erreichen." },
  { id: "vorhofflimmern-card-03", area: "Pathophysiologie", question: "Leiten Sie von VHF eine mögliche akute Herzinsuffizienz her.", answer: "Fehlende wirksame Vorhofkontraktion vermindert die Kammerfüllung; hohe Kammerfrequenz verkürzt die Diastole. Bei eingeschränkter Pumpfunktion sinkt das Herzzeitvolumen, Rückstau und Lungenödem sind möglich." },
  { id: "vorhofflimmern-card-04", area: "Thromboembolie", question: "Warum ist besonders das linke Herzohr für einen ischämischen Schlaganfall relevant?", answer: "In der trabekulierten Ausstülpung kann bei fehlender Vorhofkontraktion Blut stagnieren und ein Thrombus entstehen. Embolisation über linke Kammer und Aorta kann eine Hirnarterie verschließen." },
  { id: "vorhofflimmern-card-05", area: "EKG", question: "Nennen Sie die drei wichtigsten EKG-Merkmale und eine wichtige Ausnahme bei Vorhofflimmern.", answer: "Irregulär-irreguläre R-R-Abstände, keine geordneten P-Wellen, meist schmale QRS bei normaler Überleitung. f-Wellen können diskret sein; ein breiter unregelmäßiger Rhythmus erfordert gesonderte Einordnung, etwa Schenkelblock oder Präexzitation." },
  { id: "vorhofflimmern-card-06", area: "Einteilung", question: "Unterscheiden Sie paroxysmales, persistierendes, permanentes und erstdiagnostiziertes VHF.", answer: "Paroxysmal endet spontan meist innerhalb von sieben Tagen; persistierend endet nicht spontan innerhalb dieser Zeit oder braucht Intervention; permanent ist als dauerhafter Rhythmus akzeptiert; erstdiagnostiziert beschreibt nur die erstmalige Dokumentation." },
  { id: "vorhofflimmern-card-07", area: "Entscheidung", question: "Ein Patient hat VHF 170/min. Welche Befunde entscheiden über Notfallkardioversion statt allein die Frequenz?", answer: "Synkope, Schock, Herzinsuffizienz/Lungenödem oder Myokardischämie im Zusammenhang mit der Tachykardie; zusätzlich cABCDE, Perfusion, Bewusstsein, SpO₂, EKG und Verlauf. Instabilität nach VFA 20 zeitkritisch behandeln." },
  { id: "vorhofflimmern-card-08", area: "Differenzialdiagnose", question: "Wie grenzen Sie VHF von Sinustachykardie, Vorhofflattern, regelmäßiger SVT und breiter Tachykardie ab?", answer: "VHF: keine geordneten P-Wellen und völlig unregelmäßige R-R-Abstände. Sinustachykardie: P vor QRS, meist regelmäßig. Flattern: mögliche Flatterwellen, bei variabler Überleitung auch unregelmäßig. AV-knotenabhängige SVT meist regelmäßig. Breite Tachykardie erfordert VT/Präexzitation als gefährliche Differenzialdiagnose." },
  { id: "vorhofflimmern-card-09", area: "VFA 20", question: "Nennen Sie die VFA-20-Sequenz der synchronisierten biphasischen Kardioversion und die Kontrollen nach Konversion.", answer: "Gerätespezifische Synchronisation prüfen; bis zu drei Versuche mit 120, 150 und 200 J. Nach Konversion sofort ABCDE sowie periphere und zentrale Pulse prüfen; Monitoring und Transport fortsetzen." },
  { id: "vorhofflimmern-card-10", area: "VFA 20 / B2A", question: "Wie geht VFA 20 bei ausbleibender Konversion weiter, und wie wird das vorgesehene Amiodaron nach B2A vorbereitet?", answer: "Einmalig 300 mg Amiodaron als Kurzinfusion; bei weiterem Misserfolg einmalige Wiederholung direkt mit 200 J. B2A: 300 mg = 6 ml aus 150 mg/3 ml, plus 94 ml NaCl 0,9 % auf 100 ml = 3 mg/ml." },
  { id: "vorhofflimmern-card-11", area: "Anamnese", question: "Welche Anamneseangaben sind für VHF und spätere klinische Entscheidungen besonders wichtig?", answer: "Beginn/letzter sicher normaler Rhythmus, Symptomverlauf, Synkope/Ischämie/Dyspnoe, bekannte VHF-Episoden, kardiale Erkrankungen und mögliche Trigger sowie Art, Regelmäßigkeit und letzte Einnahme der Antikoagulation." },
  { id: "vorhofflimmern-card-12", area: "Präklinische Grenze", question: "Welche drei Maßnahmen dürfen nicht schematisch allein wegen einer VHF-Diagnose erfolgen?", answer: "Keine Notfallkardioversion ohne passende Instabilität bzw. Indikationsprüfung; keine eigenständige pauschale Antikoagulation nur wegen VHF; keine unkritische AV-knotenhemmende Behandlung bei unregelmäßig breiter Tachykardie/Präexzitationsverdacht. Maßgeblich sind EKG, klinischer Zustand und VFA." },
];
