import type { ComponentType, ReactNode } from "react";

type FigureProps = { src: string; alt: string; caption: string; wide?: boolean };
type Props = {
  Figure: ComponentType<FigureProps>;
  Vfa: ComponentType<FigureProps>;
  children: ReactNode;
};
export default function WirbelsaeulentraumaLesson({ Figure, Vfa, children }: Props) {
  const section = (number: string, title: string, body: ReactNode) => <section className="lesson-section" key={number}><header className="chapter-heading"><span>{number}</span><div><small>Wirbelsäulentrauma</small><h2>{title}</h2></div></header><div className="lesson-prose script-copy">{body}</div></section>;
  return <article className="lesson-article">
    <div className="lesson-intro"><p className="lead">Verletzung der Wirbelsäule und der angrenzenden Weichteile durch direkte oder indirekte Gewalteinwirkung.</p><p>Unfallmechanismus, neurologischer Befund und Verlauf bestimmen die Versorgung. Ein fehlendes neurologisches Defizit beweist keine stabile Wirbelsäule.</p></div>
    {section("01", "Definition und Grundverständnis", <p>Betroffen sein können Wirbelkörper, Wirbelbögen, Bandscheiben, Bänder und angrenzende Weichteile. Verletzungen des Rückenmarks oder der Nervenwurzeln können hinzukommen. Knöcherne Verletzung und neurologischer Schaden werden deshalb getrennt beurteilt.</p>)}
    {section("02", "Anatomie und Physiologie", <>
      <p>Die Wirbelsäule verbindet Kopf, Ober- und Unterkörper. Sie sorgt für Stabilität, Lastenverteilung und Schutz des Rückenmarks. 24 bewegliche Wirbel gliedern sich in 7 Halswirbel, 12 Brustwirbel und 5 Lendenwirbel. Dazu kommen 5 zum Kreuzbein verwachsene Wirbel und meist 4, variabel 3–5 Steißbeinwirbel.</p>
      <div className="reading-columns"><div><h3>Hals- und Brustwirbelsäule</h3><p>Halslordose und Brustkyphose gehören zur physiologischen Krümmung. Atlas und Hinterhaupt ermöglichen insbesondere die Nickbewegung; das Gelenk zwischen Atlas und Axis mit dem Dens ermöglicht vor allem Rotation. Die Brustwirbelsäule bildet mit Rippen und Sternum den stabilisierenden Brustkorb.</p></div><div><h3>Lendenwirbelsäule und Becken</h3><p>Die kräftigen Lendenwirbel tragen große Lasten und bilden die Lendenlordose. Das Kreuzbein verbindet Wirbelsäule und Becken; es besitzt eine kyphotische Krümmung. Das Steißbein bildet den unteren Abschluss und enthält kein Rückenmark.</p></div></div>
      <h3>Wirbel und Spinalkanal</h3><p>Wirbelkörper, Wirbelbogen, Dorn- und Querfortsätze bilden die Grundstruktur. Die übereinanderliegenden Wirbellöcher bilden den Wirbelkanal.</p>
      <Figure src="/lessons/wirbelsaeulentrauma/Im1.jpg" alt="Beschrifteter Wirbel mit Wirbelkörper, Wirbelbogen und Fortsätzen" caption="Aufbau eines Wirbels" />
      <h3>Bandscheiben</h3><p>Regelhaft liegen 23 Bandscheiben zwischen C2/C3 und L5/S1. Zwischen Atlas und Axis liegt keine Bandscheibe. Der äußere Faserring (Anulus fibrosus) umgibt den wasserreichen Gallertkern (Nucleus pulposus). Beide verteilen Druck und wirken als Stoßdämpfer. Der Austausch von Flüssigkeit, Nährstoffen und Stoffwechselprodukten erfolgt über Diffusion.</p>
      <Figure src="/lessons/wirbelsaeulentrauma/Im3.jpg" alt="Wirbel und Bandscheibe mit Faserring, Gallertkern und austretenden Nerven" caption="Bandscheibe und angrenzende Strukturen" />
      <h3>Rückenmark</h3><p>Die Medulla spinalis liegt im Wirbelkanal und reicht beim Erwachsenen vom Hirnstamm bis etwa L1/L2. Darunter verlaufen Nervenwurzeln weiter. Innen liegt schmetterlingsförmige graue Substanz für Verarbeitung und Verschaltung; außen verlaufen die Nervenbahnen der weißen Substanz.</p><ul className="script-list"><li><b>Vorderhorn:</b> motorische Nervenzellen zur Muskelsteuerung.</li><li><b>Hinterhorn:</b> Verarbeitung sensibler Informationen aus der Peripherie.</li><li><b>Seitenhorn:</b> vegetative Funktionen, insbesondere sympathische Neurone im thorakolumbalen Bereich.</li></ul>
      <Figure src="/lessons/wirbelsaeulentrauma/Im2.jpg" alt="Rückenmarksquerschnitt mit grauer und weißer Substanz sowie Nervenwurzeln" caption="Rückenmarksquerschnitt und Nervenbahnen" wide />
    </>)}
    {section("03", "Pathophysiologie und Ursachen", <>
      <p>Frakturen, Band- oder Bandscheibenverletzungen können Instabilität verursachen. Rückenmark und Nervenwurzeln können direkt oder sekundär geschädigt werden. Je höher eine Rückenmarksläsion liegt, desto umfangreicher können neurologische, respiratorische und autonome Ausfälle sein.</p>
      <ul className="script-list"><li><b>Hyperextension:</b> Überstreckung, beispielsweise beim Verkehrsunfall; mögliche Hangman-Fraktur des Axis. Eine schwere Rückenmarksschädigung ist möglich, aber nicht zwangsläufig.</li><li><b>Hyperflexion:</b> starke Vorwärtsbeugung mit Verletzung von Wirbeln, Bändern oder Bandscheiben.</li><li><b>Kompression:</b> axiale Stauchung beim Kopfsprung oder Sturz auf Kopf, Füße oder Gesäß; Wirbelkörper können komprimiert oder gesprengt werden.</li><li><b>Rotation und Scherkräfte:</b> Verdrehung oder Verschiebung mit knöcherner und ligamentärer Verletzung.</li></ul>
      <h3>Neurogener Schock</h3><p>Der Ausfall sympathischer Kreislaufregulation kann Vasodilatation, relative Hypovolämie und Hypotonie verursachen. Bradykardie und gestörte Thermoregulation können hinzukommen. Blutverlust durch Begleitverletzungen muss gleichzeitig gesucht werden.</p><aside className="knowledge-note"><b>Neurogen ist nicht gleich spinal</b><p>Der neurogene Schock beschreibt die Kreislaufstörung. Der spinale Schock bezeichnet den vorübergehenden Ausfall neurologischer Funktionen und Reflexe unterhalb einer Rückenmarksläsion.</p></aside>
      <h3>Schleudertrauma</h3><p>Ein Beschleunigungs-/Abbremsmechanismus kann Nackenbeschwerden, muskuläre Befunde und gegebenenfalls neurologische Ausfälle verursachen. Fraktur oder Luxation sind gesondert zu erfassen. Eine Graduierung allein aus dem Unfallmechanismus ist nicht möglich.</p>
    </>)}
    {section("04", "Welche Symptome stützen die Arbeitsdiagnose?", <>
      <ul className="script-list"><li>Starker, lokalisierbarer Wirbelsäulenschmerz und Druckschmerz über Dornfortsätzen.</li><li>Fehlstellung oder Stufenbildung; keine provozierende Prüfung durch Bewegung.</li><li>Kribbeln, Taubheit oder Ameisenlaufen an Armen und Beinen.</li><li>Schwäche oder Lähmung, im Seitenvergleich erheben.</li><li>Neu aufgetretene Blasen-/Mastdarmstörung, etwa Harnverhalt oder Inkontinenz.</li></ul>
      <aside className="red-flags"><span>!</span><div><small>Red Flags</small><h3>Neurologische Ausfälle oder Atemstörung</h3><p>Neue Paresen, zunehmende Sensibilitätsstörungen, nachlassende Ventilation oder Kreislaufinstabilität erfordern sofortige Re-Evaluation und zeitkritische Versorgung.</p></div></aside>
    </>)}
    {section("05", "Komplikationen und Gefahren", <>
      <p>Rückenmarksschäden können eine Querschnittlähmung verursachen. Unnötige Bewegung und unsachgemäße Rettung können eine sekundäre Verschlechterung begünstigen. Auch Hypoxie und Kreislaufstörungen gefährden die Versorgung des geschädigten Gewebes.</p>
      <h3>Hohe Halsmarkverletzung</h3><p>Die Segmente C3–C5 stellen die Versorgung des Nervus phrenicus. Eine Schädigung dieser Segmente oder der darüberliegenden Bahnen kann die Zwerchfellfunktion beeinträchtigen. Auch die Interkostalmuskulatur kann ausfallen; Atemstillstand ist möglich. Instabile Verletzungen von C1/C2 können das obere Halsmark beziehungsweise den Übergang zum Hirnstamm gefährden.</p>
      <p>SHT, Thorax-, Abdomen-, Becken- und Extremitätenverletzungen werden parallel gesucht. Ein vermuteter neurogener Schock darf die Suche nach einer Blutung nicht beenden.</p>
    </>)}
    {section("06", "Welche Einsatzmaterialien nehmen Sie mit?", <div className="material-chips">{["Notfallrucksack", "EKG / Monitoring", "Traumatasche", "Sauerstoff / Beatmungsgerät", "Absaugung", "i.v.-Material", "Morphin", "Esketamin / Ketanest", "Vakuummatratze", "HWS-Stütze nach Befund", "Schaufeltrage / Rettungsboard", "Wärmeerhalt", "CO-Warner"].map(x=><span key={x}>{x}</span>)}</div>)}
    {section("07", "Erstmaßnahmen und Anamnese", <>
      <p>Einsatzstelle und Mechanismus erfassen, Eigenschutz beachten und bei Verdacht einen Helfer zur manuellen In-line-Stabilisierung (MILS) am Kopf einsetzen. Kritische Blutungen und cABCDE priorisieren. Notwendige Atemwegs- oder Beatmungsmaßnahmen dürfen durch die Immobilisation nicht verzögert werden.</p>
      <ul className="script-list"><li>Atmung, Oxygenierung und Kreislauf beurteilen; Sauerstoff bedarfsgerecht, Beatmungsbereitschaft herstellen.</li><li>Motorik, Sensibilität und periphere Durchblutung im Seitenvergleich dokumentieren; vor und nach Umlagerungen erneut prüfen.</li><li>Monitoring, i.v.-Zugang, Wärmeerhalt und koordinierte Bewegungsbegrenzung nach Befund.</li><li>Keine gewaltsame Korrektur einer schmerzhaften Fehlstellung.</li><li>BEFAST bei passender Differenzialdiagnose ergänzen; es ersetzt keine Untersuchung der Rückenmarksfunktionen.</li></ul>
      <h3>SAMPLERS und OPQRST</h3><div className="samplers-grid"><p><b>S · Symptome</b>Schmerz, Parästhesien, Kraftverlust, Blasen-/Mastdarmstörung und Beginn.</p><p><b>A · Allergien</b>Bekannte Allergien und Unverträglichkeiten.</p><p><b>M · Medikamente</b>Antikoagulation, Analgetika und sedierende Substanzen.</p><p><b>P · Vorgeschichte</b>Wirbelsäulenerkrankungen und vorbestehende neurologische Defizite.</p><p><b>L · Letzte Aufnahme</b>Nahrung, Flüssigkeit und Substanzen.</p><p><b>E · Ereignis</b>Mechanismus, Höhe, Kraftrichtung und zeitlicher Verlauf.</p><p><b>R · Risiken</b>Osteoporose, Begleiterkrankungen und Begleitverletzungen.</p><p><b>S · Schwangerschaft</b>Falls zutreffend erfragen.</p></div><p>OPQRST erfasst Beginn, Auslöser/Linderung, Qualität, Lokalisation/Ausstrahlung, Stärke und Verlauf des Schmerzes. NRS initial und wiederholt dokumentieren.</p>
    </>)}
    {section("08", "Differenzialdiagnosen und Entscheidungsfindung", <>
      <div className="differential-grid">{["Muskelzerrung / Prellung", "Bandscheibenvorfall", "SHT / Hirnblutung", "Schlaganfall", "Thorax- und Abdominaltrauma", "Becken- und Extremitätentrauma"].map(x=><span key={x}>{x}</span>)}</div>
      <p>Relevanter Mechanismus, Wirbelsäulenschmerz, Druckschmerz oder neurologische Ausfälle stützen den Verdacht. Bewusstseinsstörung, Intoxikation und Ablenkverletzungen vermindern die Zuverlässigkeit der Untersuchung. Fehlende Beschwerden bei einem zuverlässig untersuchbaren Patienten senken die Wahrscheinlichkeit, ersetzen aber keine strukturierte Beurteilung nach lokalem Standard.</p>
    </>)}
    {section("09", "Weitere Maßnahmen und Analgesie", <>
      <p>Schonende Rettung und achsengerechte Lagerung, beispielsweise auf der Vakuummatratze mit Kopfstabilisierung. Eine HWS-Stütze allein stabilisiert nicht die gesamte Wirbelsäule. Notarzt früh nachfordern, ein geeignetes Traumazentrum voranmelden und Transportmittel nach Dringlichkeit und Zeitvorteil wählen.</p>
      <p>Neurologischen Status, Atmung, Kreislauf und Schmerz wiederholt kontrollieren. Mechanismus, Ausgangsbefund, Veränderungen, Medikamente mit Zeiten und Wirkung vollständig dokumentieren.</p>
      <h3>VFA 35: Starke Schmerzzustände</h3><p>Ab NRS 5 erfolgt die strukturierte Schmerzbeurteilung mit cABCDE, OPQRST und ursachenbezogener Auswahl nach den Vorgaben des zuständigen ÄLRD. Für traumatischen Schmerz sind hier Morphin und Esketamin dargestellt.</p>
      <div className="reading-columns"><div><h3>Morphin · VFA 38</h3><p>Langsame i.v.-Gabe nach Gewichtstabelle; Kinder unter 40 kg werden im Algorithmus auf den Kinder-Esketaminpfad verwiesen. Nach fünf Minuten Wirkung prüfen, bei Bedarf halbe Dosis gemäß Algorithmus wiederholen, maximal insgesamt 10 mg. Beatmungsbereitschaft, EKG, Blutdruck und NRS-Verlauf beachten.</p></div><div><h3>Esketamin / Ketanest · VFA 36</h3><p>Der Erwachsenenpfad zeigt 1 mg Midazolam i.v. als Begleitmedikation und anschließend langsam 0,2 mg/kg Esketamin i.v. Bei unzureichender Wirkung halbe Initialdosis (0,1 mg/kg) nach den Kontrollschritten im Originalalgorithmus. Beatmungsbereitschaft und kontinuierliche Überwachung sind erforderlich.</p></div></div>
    </>)}
    {section("10", "VFA Thüringen 2026/2027 und Dosierungsanlagen", <>
      <div className="vfa-stack"><Vfa src="/lessons/sht/vfa-schmerz-basis-35.png" alt="VFA 35 Basisalgorithmus starke Schmerzzustände" caption="VFA 35 · Starke Schmerzzustände" /><Vfa src="/lessons/sht/vfa-morphin-38.png" alt="VFA 38 Morphin mit Dosierungstabelle und Verlaufskontrolle" caption="VFA 38 · Morphin" /><Vfa src="/lessons/sht/vfa-esketamin-36.png" alt="VFA 36 Esketamin für Erwachsene mit Begleitmedikation" caption="VFA 36 · Esketamin / Ketanest" /></div>
      <h3>Vorbereitung und Konzentration · Anlage B2A</h3><p><b>Morphin:</b> 10 mg in 1 ml plus 9 ml NaCl 0,9 % ergeben 10 ml mit 1 mg/ml. <b>Esketamin:</b> 50 mg in 2 ml plus 8 ml NaCl 0,9 % ergeben 10 ml mit 5 mg/ml. Wirkstoff, Ausgangskonzentration, Endvolumen und Beschriftung prüfen.</p>
      <Figure src="/lessons/sht/medikamentenliste-morphin.png" alt="Anlage B2A Morphin Verdünnung auf 1 mg pro ml" caption="Anlage B2A · Morphin" wide />
      <Figure src="/lessons/wirbelsaeulentrauma/anlage-b2a-esketamin.png" alt="Anlage B2A Esketamin Verdünnung auf 5 mg pro ml" caption="Anlage B2A · Esketamin / Ketanest" wide />
      <h3>Gewichtsbezogene Dosierungen · Anlage B2B</h3><p>Die folgenden Originalausschnitte zeigen ausschließlich die beiden benötigten Tabellen. Bei Esketamin sind mg und ml bei 5 mg/ml angegeben; bei Morphin gilt die vorbereitete Konzentration von 1 mg/ml.</p>
      <Figure src="/lessons/wirbelsaeulentrauma/anlage-b2b-morphin.png" alt="Original Dosierungstabelle Morphin 40 bis 110 kg aus Anlage B2B" caption="Anlage B2B · Morphin-Dosierung" wide />
      <Figure src="/lessons/wirbelsaeulentrauma/anlage-b2b-esketamin.png" alt="Original Dosierungstabelle Esketamin 0,2 mg pro kg und 5 mg pro ml aus Anlage B2B" caption="Anlage B2B · Esketamin-Dosierung" wide />
    </>)}
    {children}
    <p className="lesson-source">Grundlage: Print 6.pdf · Analgesie und Dosierungen: Thüringer VFA 2026/2027, 35, 36, 38 und Anlagen B2A/B2B. Fachlicher Abgleich der Rettung und Immobilisation: <a href="https://register.awmf.org/assets/guidelines/187-023l_S3_Polytrauma-Schwerverletzten-Behandlung_2023-06.pdf" target="_blank" rel="noreferrer">S3-Leitlinie Polytrauma / Schwerverletzten-Behandlung</a>.</p>
  </article>;
}
